### ISSUE TITLE
P2P shuffle fails on frames containing mixed numeric/string columns

### ISSUE THREAD

**Issue by charlesbluca** [dask/dask#10014]
**Describe the issue**:
The `p2p` shuffle algorithm fails when working with frames that contain columns of mixed numeric/string dtypes; this error occurs during computation when Arrow attempts to cast the entire column to a numeric dtype:

```
2023-03-02 13:12:52,204 - distributed.shuffle - ERROR - shuffle_transfer failed during shuffle 4b4e0d18244b9cc2b7aadf328a683932
Traceback (most recent call last):
  File "/raid/charlesb/mambaforge/envs/bug-ci-failures-p2p/lib/python3.9/site-packages/distributed/shuffle/_shuffle.py", line 58, in shuffle_transfer
    return _get_worker_extension().add_partition(
  File "/raid/charlesb/mambaforge/envs/bug-ci-failures-p2p/lib/python3.9/site-packages/distributed/shuffle/_worker_extension.py", line 628, in add_partition
    shuffle = self.get_or_create_shuffle(shuffle_id, type=type, **kwargs)
  File "/raid/charlesb/mambaforge/envs/bug-ci-failures-p2p/lib/python3.9/site-packages/distributed/shuffle/_worker_extension.py", line 879, in get_or_create_shuffle
    return sync(
  File "/raid/charlesb/mambaforge/envs/bug-ci-failures-p2p/lib/python3.9/site-packages/distributed/utils.py", line 405, in sync
    raise exc.with_traceback(tb)
  File "/raid/charlesb/mambaforge/envs/bug-ci-failures-p2p/lib/python3.9/site-packages/distributed/utils.py", line 378, in f
    result = yield future
  File "/raid/charlesb/mambaforge/envs/bug-ci-failures-p2p/lib/python3.9/site-packages/tornado/gen.py", line 769, in run
    value = future.result()
  File "/raid/charlesb/mambaforge/envs/bug-ci-failures-p2p/lib/python3.9/site-packages/distributed/shuffle/_worker_extension.py", line 709, in _get_or_create_shuffle
    shuffle = await self._refresh_shuffle(
  File "/raid/charlesb/mambaforge/envs/bug-ci-failures-p2p/lib/python3.9/site-packages/distributed/shuffle/_worker_extension.py", line 758, in _refresh_shuffle
    "schema": pa.Schema.from_pandas(kwargs["empty"])
  File "pyarrow/types.pxi", line 1739, in pyarrow.lib.Schema.from_pandas
  File "/raid/charlesb/mambaforge/envs/bug-ci-failures-p2p/lib/python3.9/site-packages/pyarrow/pandas_compat.py", line 551, in dataframe_to_types
    type_ = pa.array(c, from_pandas=True).type
  File "pyarrow/array.pxi", line 316, in pyarrow.lib.array
  File "pyarrow/array.pxi", line 83, in pyarrow.lib._ndarray_to_array
  File "pyarrow/error.pxi", line 100, in pyarrow.lib.check_status
pyarrow.lib.ArrowInvalid: Could not convert 'a' with type str: tried to convert to double
2023-03-02 13:12:52,278 - distributed.worker - WARNING - Compute Failed
Key:       ('shuffle-transfer-4b4e0d18244b9cc2b7aadf328a683932', 0)
Function:  shuffle_transfer
args:      (     c  _partitions
0  0.1            0
1    a            0
2    b            0
3    c            0, '4b4e0d18244b9cc2b7aadf328a683932', 0, 1, '_partitions')
kwargs:    {}
Exception: "RuntimeError('shuffle_transfer failed during shuffle 4b4e0d18244b9cc2b7aadf328a683932')"
```

**Minimal Complete Verifiable Example**:

```python
import dask
import dask.dataframe as dd
from distributed import Client

client = Client()

ddf = dd.from_dict({
    "c": [0.1, "a", "b", "c"]
}, npartitions=1)

with dask.config.set({"dataframe.shuffle.algorithm" : "p2p"}):
    res = ddf.groupby("c").apply(lambda x: x).compute()
```

**Anything else we need to know?**:
This failure can be avoided by manually setting `dataframe.shuffle.algorithm` to disk or tasks, not sure if this could be handled more gracefully with either a warning or implicit fallback behavior; opening because this change in behavior caused some failures downstream in dask-sql (xref https://github.com/dask-contrib/dask-sql/pull/1067).

**Environment**:

- Dask version: `main`
- Python version: 3.10
- Operating System: ubuntu-20.04
- Install method (conda, pip, source): source

**Comment by jrbourbeau** [comment]
Thanks @charlesbluca! I'm able to reproduce. Interestingly if you remove the numeric value, and only have text data, things works.

cc @hendrikmakait @fjetter for visibility

**Comment by Cognitus-Stuti** [comment]
The issue persists in v2024.5.2 any particular resolutions for the same

**Comment by Cognitus-Stuti** [comment]
The shuffle is happens in sort_values
