### ISSUE TITLE
2023.3.1: docuemnattion not ready for sphinx 6.1.3

### ISSUE THREAD

**Issue by kloczek** [dask/dask#10057]
Looks like it isn not possible to build `dask` documentation using latest sphinx 6.1.3
<details>

```console
+ /usr/bin/sphinx-build -n -T -b man docs/source build/sphinx/man
Running Sphinx v6.1.3
making output directory... done
[autosummary] generating autosummary for: 10-minutes-to-dask.rst, api.rst, array-api.rst, array-assignment.rst, array-best-practices.rst, array-chunks.rst, array-creation.rst, array-design.rst, array-gufunc.rst, array-overlap.rst, ..., scheduler-overview.rst, scheduling-policy.rst, scheduling.rst, shared.rst, spark.rst, spec.rst, support.rst, understanding-performance.rst, user-interfaces.rst, why.rst
[autosummary] generating autosummary for: /home/tkloczko/rpmbuild/BUILD/dask-2023.3.1/docs/source/generated/dask.array.Array.all.rst, /home/tkloczko/rpmbuild/BUILD/dask-2023.3.1/docs/source/generated/dask.array.Array.any.rst, /home/tkloczko/rpmbuild/BUILD/dask-2023.3.1/docs/source/generated/dask.array.Array.argmax.rst, /home/tkloczko/rpmbuild/BUILD/dask-2023.3.1/docs/source/generated/dask.array.Array.argmin.rst, /home/tkloczko/rpmbuild/BUILD/dask-2023.3.1/docs/source/generated/dask.array.Array.argtopk.rst, /home/tkloczko/rpmbuild/BUILD/dask-2023.3.1/docs/source/generated/dask.array.Array.astype.rst, /home/tkloczko/rpmbuild/BUILD/dask-2023.3.1/docs/source/generated/dask.array.Array.blocks.rst, /home/tkloczko/rpmbuild/BUILD/dask-2023.3.1/docs/source/generated/dask.array.Array.choose.rst, /home/tkloczko/rpmbuild/BUILD/dask-2023.3.1/docs/source/generated/dask.array.Array.chunks.rst, /home/tkloczko/rpmbuild/BUILD/dask-2023.3.1/docs/source/generated/dask.array.Array.chunksize.rst, ..., /home/tkloczko/rpmbuild/BUILD/dask-2023.3.1/docs/source/generated/dask.dataframe.tseries.resample.Resampler.ohlc.rst, /home/tkloczko/rpmbuild/BUILD/dask-2023.3.1/docs/source/generated/dask.dataframe.tseries.resample.Resampler.prod.rst, /home/tkloczko/rpmbuild/BUILD/dask-2023.3.1/docs/source/generated/dask.dataframe.tseries.resample.Resampler.quantile.rst, /home/tkloczko/rpmbuild/BUILD/dask-2023.3.1/docs/source/generated/dask.dataframe.tseries.resample.Resampler.rst, /home/tkloczko/rpmbuild/BUILD/dask-2023.3.1/docs/source/generated/dask.dataframe.tseries.resample.Resampler.sem.rst, /home/tkloczko/rpmbuild/BUILD/dask-2023.3.1/docs/source/generated/dask.dataframe.tseries.resample.Resampler.size.rst, /home/tkloczko/rpmbuild/BUILD/dask-2023.3.1/docs/source/generated/dask.dataframe.tseries.resample.Resampler.std.rst, /home/tkloczko/rpmbuild/BUILD/dask-2023.3.1/docs/source/generated/dask.dataframe.tseries.resample.Resampler.sum.rst, /home/tkloczko/rpmbuild/BUILD/dask-2023.3.1/docs/source/generated/dask.dataframe.tseries.resample.Resampler.var.rst, /home/tkloczko/rpmbuild/BUILD/dask-2023.3.1/docs/source/generated/dask.dataframe.utils.make_meta.rst
building [mo]: targets for 0 po files that are out of date
writing output...
building [man]: all manpages
updating environment: [new config] 1018 added, 0 changed, 0 removed
executing 10-minutes-to-dask-minutes-to-dask
reading sources... [  2%] changelog
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/docutils/statemachine.py", line 299, in next_line
    self.line = self.input_lines[self.line_offset]
  File "/usr/lib/python3.8/site-packages/docutils/statemachine.py", line 1136, in __getitem__
    return self.data[i]
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/docutils/statemachine.py", line 226, in run
    self.next_line()
  File "/usr/lib/python3.8/site-packages/docutils/statemachine.py", line 302, in next_line
    raise EOFError
EOFError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/sphinx/cmd/build.py", line 284, in build_main
    app.build(args.force_all, args.filenames)
  File "/usr/lib/python3.8/site-packages/sphinx/application.py", line 347, in build
    self.builder.build_update()
  File "/usr/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 308, in build_update
    self.build(['__all__'], to_build)
  File "/usr/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 327, in build
    updated_docnames = set(self.read())
  File "/usr/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 434, in read
    self._read_serial(docnames)
  File "/usr/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 455, in _read_serial
    self.read_doc(docname)
  File "/usr/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 511, in read_doc
    publisher.publish()
  File "/usr/lib/python3.8/site-packages/docutils/core.py", line 224, in publish
    self.document = self.reader.read(self.source, self.parser,
  File "/usr/lib/python3.8/site-packages/sphinx/io.py", line 105, in read
    self.parse()
  File "/usr/lib/python3.8/site-packages/docutils/readers/__init__.py", line 76, in parse
    self.parser.parse(self.input, document)
  File "/usr/lib/python3.8/site-packages/sphinx/parsers.py", line 80, in parse
    self.statemachine.run(inputlines, document, inliner=self.inliner)
  File "/usr/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 169, in run
    results = StateMachineWS.run(self, input_lines, input_offset,
  File "/usr/lib/python3.8/site-packages/docutils/statemachine.py", line 233, in run
    context, next_state, result = self.check_line(
  File "/usr/lib/python3.8/site-packages/docutils/statemachine.py", line 445, in check_line
    return method(match, context, next_state)
  File "/usr/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 2785, in underline
    self.section(title, source, style, lineno - 1, messages)
  File "/usr/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 325, in section
    self.new_subsection(title, lineno, messages)
  File "/usr/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 391, in new_subsection
    newabsoffset = self.nested_parse(
  File "/usr/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 279, in nested_parse
    state_machine.run(block, input_offset, memo=self.memo,
  File "/usr/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 195, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "/usr/lib/python3.8/site-packages/docutils/statemachine.py", line 233, in run
    context, next_state, result = self.check_line(
  File "/usr/lib/python3.8/site-packages/docutils/statemachine.py", line 445, in check_line
    return method(match, context, next_state)
  File "/usr/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 2785, in underline
    self.section(title, source, style, lineno - 1, messages)
  File "/usr/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 325, in section
    self.new_subsection(title, lineno, messages)
  File "/usr/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 391, in new_subsection
    newabsoffset = self.nested_parse(
  File "/usr/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 279, in nested_parse
    state_machine.run(block, input_offset, memo=self.memo,
  File "/usr/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 195, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "/usr/lib/python3.8/site-packages/docutils/statemachine.py", line 233, in run
    context, next_state, result = self.check_line(
  File "/usr/lib/python3.8/site-packages/docutils/statemachine.py", line 445, in check_line
    return method(match, context, next_state)
  File "/usr/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 2785, in underline
    self.section(title, source, style, lineno - 1, messages)
  File "/usr/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 325, in section
    self.new_subsection(title, lineno, messages)
  File "/usr/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 391, in new_subsection
    newabsoffset = self.nested_parse(
  File "/usr/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 279, in nested_parse
    state_machine.run(block, input_offset, memo=self.memo,
  File "/usr/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 195, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "/usr/lib/python3.8/site-packages/docutils/statemachine.py", line 233, in run
    context, next_state, result = self.check_line(
  File "/usr/lib/python3.8/site-packages/docutils/statemachine.py", line 445, in check_line
    return method(match, context, next_state)
  File "/usr/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 1273, in bullet
    i, blank_finish = self.list_item(match.end())
  File "/usr/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 1295, in list_item
    self.nested_parse(indented, input_offset=line_offset,
  File "/usr/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 279, in nested_parse
    state_machine.run(block, input_offset, memo=self.memo,
  File "/usr/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 195, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "/usr/lib/python3.8/site-packages/docutils/statemachine.py", line 239, in run
    result = state.eof(context)
  File "/usr/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 2725, in eof
    self.blank(None, context, None)
  File "/usr/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 2716, in blank
    paragraph, literalnext = self.paragraph(
  File "/usr/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 416, in paragraph
    textnodes, messages = self.inline_text(text, lineno)
  File "/usr/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 425, in inline_text
    nodes, messages = self.inliner.parse(text, lineno,
  File "/usr/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 649, in parse
    before, inlines, remaining, sysmessages = method(self, match,
  File "/usr/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 792, in interpreted_or_phrase_ref
    nodelist, messages = self.interpreted(rawsource, escaped, role,
  File "/usr/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 889, in interpreted
    nodes, messages2 = role_fn(role, rawsource, text, lineno, self)
  File "/usr/lib/python3.8/site-packages/sphinx/ext/extlinks.py", line 103, in role
    title = caption % part
TypeError: not all arguments converted during string formatting

Exception occurred:
  File "/usr/lib/python3.8/site-packages/sphinx/ext/extlinks.py", line 103, in role
    title = caption % part
TypeError: not all arguments converted during string formatting
The full traceback has been saved in /tmp/sphinx-err-3l5jo8g3.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!


[tkloczko@pers-jacek SPECS]$ cat /tmp/sphinx-err-3l5jo8g3.log
# Platform:         linux; (Linux-6.1.10-200.fc37.x86_64-x86_64-with-glibc2.34)
# Sphinx version:   6.1.3
# Python version:   3.8.16 (CPython)
# Docutils version: 0.19
# Jinja2 version:   3.1.2
# Pygments version: 2.14.0

# Last messages:
#   reading sources... [  1%] array-slicing
#   reading sources... [  1%] array-sparse
#   reading sources... [  1%] array-stack
#   reading sources... [  1%] array-stats
#   reading sources... [  1%] bag
#   reading sources... [  1%] bag-api
#   reading sources... [  1%] bag-creation
#   reading sources... [  1%] best-practices
#   reading sources... [  1%] caching
#   reading sources... [  2%] changelog

# Loaded extensions:
#   sphinx.ext.mathjax (6.1.3)
#   sphinxcontrib.applehelp (1.0.4)
#   sphinxcontrib.devhelp (1.0.2)
#   sphinxcontrib.htmlhelp (2.0.0)
#   sphinxcontrib.serializinghtml (1.1.5)
#   sphinxcontrib.qthelp (1.0.3)
#   alabaster (0.7.13)
#   sphinx.ext.autodoc.preserve_defaults (6.1.3)
#   sphinx.ext.autodoc.type_comment (6.1.3)
#   sphinx.ext.autodoc.typehints (6.1.3)
#   sphinx.ext.autodoc (6.1.3)
#   sphinx.ext.doctest (6.1.3)
#   sphinx.ext.intersphinx (6.1.3)
#   sphinx.ext.autosummary (6.1.3)
#   sphinx_autosummary_accessors (2022.4.0)
#   sphinx.ext.extlinks (6.1.3)
#   sphinx.ext.viewcode (6.1.3)
#   numpydoc (1.5.0)
#   sphinx_click.ext (unknown version)
#   dask_sphinx_theme.ext.dask_config_sphinx_ext (0.1)
#   sphinx_tabs.tabs (unknown version)
#   sphinx_remove_toctrees (unknown version)
#   IPython.sphinxext.ipython_console_highlighting (unknown version)
#   IPython.sphinxext.ipython_directive (unknown version)
#   jupyter_sphinx (0.4.0)
#   sphinx_copybutton (0.5.1)

# Traceback:
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/docutils/statemachine.py", line 299, in next_line
    self.line = self.input_lines[self.line_offset]
  File "/usr/lib/python3.8/site-packages/docutils/statemachine.py", line 1136, in __getitem__
    return self.data[i]
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/docutils/statemachine.py", line 226, in run
    self.next_line()
  File "/usr/lib/python3.8/site-packages/docutils/statemachine.py", line 302, in next_line
    raise EOFError
EOFError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/sphinx/cmd/build.py", line 284, in build_main
    app.build(args.force_all, args.filenames)
  File "/usr/lib/python3.8/site-packages/sphinx/application.py", line 347, in build
    self.builder.build_update()
  File "/usr/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 308, in build_update
    self.build(['__all__'], to_build)
  File "/usr/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 327, in build
    updated_docnames = set(self.read())
  File "/usr/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 434, in read
    self._read_serial(docnames)
  File "/usr/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 455, in _read_serial
    self.read_doc(docname)
  File "/usr/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 511, in read_doc
    publisher.publish()
  File "/usr/lib/python3.8/site-packages/docutils/core.py", line 224, in publish
    self.document = self.reader.read(self.source, self.parser,
  File "/usr/lib/python3.8/site-packages/sphinx/io.py", line 105, in read
    self.parse()
  File "/usr/lib/python3.8/site-packages/docutils/readers/__init__.py", line 76, in parse
    self.parser.parse(self.input, document)
  File "/usr/lib/python3.8/site-packages/sphinx/parsers.py", line 80, in parse
    self.statemachine.run(inputlines, document, inliner=self.inliner)
  File "/usr/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 169, in run
    results = StateMachineWS.run(self, input_lines, input_offset,
  File "/usr/lib/python3.8/site-packages/docutils/statemachine.py", line 233, in run
    context, next_state, result = self.check_line(
  File "/usr/lib/python3.8/site-packages/docutils/statemachine.py", line 445, in check_line
    return method(match, context, next_state)
  File "/usr/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 2785, in underline
    self.section(title, source, style, lineno - 1, messages)
  File "/usr/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 325, in section
    self.new_subsection(title, lineno, messages)
  File "/usr/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 391, in new_subsection
    newabsoffset = self.nested_parse(
  File "/usr/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 279, in nested_parse
    state_machine.run(block, input_offset, memo=self.memo,
  File "/usr/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 195, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "/usr/lib/python3.8/site-packages/docutils/statemachine.py", line 233, in run
    context, next_state, result = self.check_line(
  File "/usr/lib/python3.8/site-packages/docutils/statemachine.py", line 445, in check_line
    return method(match, context, next_state)
  File "/usr/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 2785, in underline
    self.section(title, source, style, lineno - 1, messages)
  File "/usr/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 325, in section
    self.new_subsection(title, lineno, messages)
  File "/usr/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 391, in new_subsection
    newabsoffset = self.nested_parse(
  File "/usr/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 279, in nested_parse
    state_machine.run(block, input_offset, memo=self.memo,
  File "/usr/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 195, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "/usr/lib/python3.8/site-packages/docutils/statemachine.py", line 233, in run
    context, next_state, result = self.check_line(
  File "/usr/lib/python3.8/site-packages/docutils/statemachine.py", line 445, in check_line
    return method(match, context, next_state)
  File "/usr/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 2785, in underline
    self.section(title, source, style, lineno - 1, messages)
  File "/usr/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 325, in section
    self.new_subsection(title, lineno, messages)
  File "/usr/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 391, in new_subsection
    newabsoffset = self.nested_parse(
  File "/usr/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 279, in nested_parse
    state_machine.run(block, input_offset, memo=self.memo,
  File "/usr/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 195, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "/usr/lib/python3.8/site-packages/docutils/statemachine.py", line 233, in run
    context, next_state, result = self.check_line(
  File "/usr/lib/python3.8/site-packages/docutils/statemachine.py", line 445, in check_line
    return method(match, context, next_state)
  File "/usr/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 1273, in bullet
    i, blank_finish = self.list_item(match.end())
  File "/usr/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 1295, in list_item
    self.nested_parse(indented, input_offset=line_offset,
  File "/usr/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 279, in nested_parse
    state_machine.run(block, input_offset, memo=self.memo,
  File "/usr/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 195, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "/usr/lib/python3.8/site-packages/docutils/statemachine.py", line 239, in run
    result = state.eof(context)
  File "/usr/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 2725, in eof
    self.blank(None, context, None)
  File "/usr/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 2716, in blank
    paragraph, literalnext = self.paragraph(
  File "/usr/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 416, in paragraph
    textnodes, messages = self.inline_text(text, lineno)
  File "/usr/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 425, in inline_text
    nodes, messages = self.inliner.parse(text, lineno,
  File "/usr/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 649, in parse
    before, inlines, remaining, sysmessages = method(self, match,
  File "/usr/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 792, in interpreted_or_phrase_ref
    nodelist, messages = self.interpreted(rawsource, escaped, role,
  File "/usr/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 889, in interpreted
    nodes, messages2 = role_fn(role, rawsource, text, lineno, self)
  File "/usr/lib/python3.8/site-packages/sphinx/ext/extlinks.py", line 103, in role
    title = caption % part
```
</details>
Looks lie build fails in `sphinx_copybutton`.

**Comment by jrbourbeau** [comment]
Thanks for surfacing this @kloczek. I'm able to reproduce. 

It looks like this might be https://github.com/sphinx-doc/sphinx/issues/11094. Is this something you're interested in resolving? (no obligation though)

**Comment by kloczek** [comment]
On first look it looks like it may be the cause.
I have several other (probably ~40) modules packaged as rpm packages (+1.1k) which have simillar issues.

**Comment by jrbourbeau** [comment]
Also wanted to cross-reference https://github.com/dask/dask/issues/9311. There is some context in that issue around how we're currently pinning some of our documentation dependencies

**Comment by kloczek** [comment]
As I'm interesten all all cases of packaging python modules docuemtation only producing man pages (roff output) to be honest I;m more and more would be interested sphinx solution to skip use some sphinx ext dependencies when exect output format is rendered.
Why? Because most of the sphinx extensions are only about producieng html output and they have Z-E-R-O impact on produced roff output 😋
