### ISSUE TITLE
Documentation build failing

### ISSUE THREAD

**Issue by jrbourbeau** [dask/dask#10099]
Our docs build has started failing with

```
Running Sphinx v4.5.0
loading translations [en]... done
making output directory... done
loading intersphinx inventory from https://docs.python.org/3/objects.inv...
loading intersphinx inventory from https://pandas.pydata.org/pandas-docs/stable/objects.inv...
loading intersphinx inventory from https://numpy.org/doc/stable/objects.inv...
loading intersphinx inventory from https://asyncssh.readthedocs.io/en/latest/objects.inv...
loading intersphinx inventory from https://distributed.dask.org/en/latest/objects.inv...
loading intersphinx inventory from https://arrow.apache.org/docs/objects.inv...
loading intersphinx inventory from https://zarr.readthedocs.io/en/latest/objects.inv...
loading intersphinx inventory from https://scikit-image.org/docs/dev/objects.inv...
loading intersphinx inventory from https://filesystem-spec.readthedocs.io/en/latest/objects.inv...
loading intersphinx inventory from https://click.palletsprojects.com/en/latest/objects.inv...
loading intersphinx inventory from https://docs.scipy.org/doc/scipy/objects.inv...
[autosummary] generating autosummary for: 10-minutes-to-dask.rst, api.rst, array-api.rst, array-assignment.rst, array-best-practices.rst, array-chunks.rst, array-creation.rst, array-design.rst, array-gufunc.rst, array-overlap.rst, ..., scheduler-overview.rst, scheduling-policy.rst, scheduling.rst, shared.rst, spark.rst, spec.rst, support.rst, understanding-performance.rst, user-interfaces.rst, why.rst
[autosummary] generating autosummary for: /home/docs/checkouts/readthedocs.org/user_builds/dask/checkouts/10098/docs/source/generated/dask.array.Array.all.rst, /home/docs/checkouts/readthedocs.org/user_builds/dask/checkouts/10098/docs/source/generated/dask.array.Array.any.rst, /home/docs/checkouts/readthedocs.org/user_builds/dask/checkouts/10098/docs/source/generated/dask.array.Array.argmax.rst, /home/docs/checkouts/readthedocs.org/user_builds/dask/checkouts/10098/docs/source/generated/dask.array.Array.argmin.rst, /home/docs/checkouts/readthedocs.org/user_builds/dask/checkouts/10098/docs/source/generated/dask.array.Array.argtopk.rst, /home/docs/checkouts/readthedocs.org/user_builds/dask/checkouts/10098/docs/source/generated/dask.array.Array.astype.rst, /home/docs/checkouts/readthedocs.org/user_builds/dask/checkouts/10098/docs/source/generated/dask.array.Array.blocks.rst, /home/docs/checkouts/readthedocs.org/user_builds/dask/checkouts/10098/docs/source/generated/dask.array.Array.choose.rst, /home/docs/checkouts/readthedocs.org/user_builds/dask/checkouts/10098/docs/source/generated/dask.array.Array.chunks.rst, /home/docs/checkouts/readthedocs.org/user_builds/dask/checkouts/10098/docs/source/generated/dask.array.Array.chunksize.rst, ..., /home/docs/checkouts/readthedocs.org/user_builds/dask/checkouts/10098/docs/source/generated/dask.dataframe.tseries.resample.Resampler.ohlc.rst, /home/docs/checkouts/readthedocs.org/user_builds/dask/checkouts/10098/docs/source/generated/dask.dataframe.tseries.resample.Resampler.prod.rst, /home/docs/checkouts/readthedocs.org/user_builds/dask/checkouts/10098/docs/source/generated/dask.dataframe.tseries.resample.Resampler.quantile.rst, /home/docs/checkouts/readthedocs.org/user_builds/dask/checkouts/10098/docs/source/generated/dask.dataframe.tseries.resample.Resampler.rst, /home/docs/checkouts/readthedocs.org/user_builds/dask/checkouts/10098/docs/source/generated/dask.dataframe.tseries.resample.Resampler.sem.rst, /home/docs/checkouts/readthedocs.org/user_builds/dask/checkouts/10098/docs/source/generated/dask.dataframe.tseries.resample.Resampler.size.rst, /home/docs/checkouts/readthedocs.org/user_builds/dask/checkouts/10098/docs/source/generated/dask.dataframe.tseries.resample.Resampler.std.rst, /home/docs/checkouts/readthedocs.org/user_builds/dask/checkouts/10098/docs/source/generated/dask.dataframe.tseries.resample.Resampler.sum.rst, /home/docs/checkouts/readthedocs.org/user_builds/dask/checkouts/10098/docs/source/generated/dask.dataframe.tseries.resample.Resampler.var.rst, /home/docs/checkouts/readthedocs.org/user_builds/dask/checkouts/10098/docs/source/generated/dask.dataframe.utils.make_meta.rst
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 95 source files that are out of date
updating environment: [new config] 1021 added, 0 changed, 0 removed
reading sources... [  0%] 10-minutes-to-dask
executing 10-minutes-to-dask

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/dask/envs/10098/lib/python3.9/site-packages/jupyter_sphinx/utils.py", line 13, in blank_nb
    spec = get_kernel_spec(kernel_name)
  File "/home/docs/checkouts/readthedocs.org/user_builds/dask/envs/10098/lib/python3.9/site-packages/jupyter_client/kernelspec.py", line 426, in get_kernel_spec
    return KernelSpecManager().get_kernel_spec(kernel_name)
  File "/home/docs/checkouts/readthedocs.org/user_builds/dask/envs/10098/lib/python3.9/site-packages/jupyter_client/kernelspec.py", line 287, in get_kernel_spec
    raise NoSuchKernel(kernel_name)
jupyter_client.kernelspec.NoSuchKernel: No such kernel named python3

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/dask/envs/10098/lib/python3.9/site-packages/sphinx/cmd/build.py", line 276, in build_main
    app.build(args.force_all, filenames)
  File "/home/docs/checkouts/readthedocs.org/user_builds/dask/envs/10098/lib/python3.9/site-packages/sphinx/application.py", line 330, in build
    self.builder.build_update()
  File "/home/docs/checkouts/readthedocs.org/user_builds/dask/envs/10098/lib/python3.9/site-packages/sphinx/builders/__init__.py", line 286, in build_update
    self.build(to_build,
  File "/home/docs/checkouts/readthedocs.org/user_builds/dask/envs/10098/lib/python3.9/site-packages/sphinx/builders/__init__.py", line 300, in build
    updated_docnames = set(self.read())
  File "/home/docs/checkouts/readthedocs.org/user_builds/dask/envs/10098/lib/python3.9/site-packages/sphinx/builders/__init__.py", line 407, in read
    self._read_serial(docnames)
  File "/home/docs/checkouts/readthedocs.org/user_builds/dask/envs/10098/lib/python3.9/site-packages/sphinx/builders/__init__.py", line 428, in _read_serial
    self.read_doc(docname)
  File "/home/docs/checkouts/readthedocs.org/user_builds/dask/envs/10098/lib/python3.9/site-packages/sphinx/builders/__init__.py", line 468, in read_doc
    doctree = read_doc(self.app, self.env, self.env.doc2path(docname))
  File "/home/docs/checkouts/readthedocs.org/user_builds/dask/envs/10098/lib/python3.9/site-packages/sphinx/io.py", line 181, in read_doc
    pub.publish()
  File "/home/docs/checkouts/readthedocs.org/user_builds/dask/envs/10098/lib/python3.9/site-packages/docutils/core.py", line 219, in publish
    self.apply_transforms()
  File "/home/docs/checkouts/readthedocs.org/user_builds/dask/envs/10098/lib/python3.9/site-packages/docutils/core.py", line 200, in apply_transforms
    self.document.transformer.apply_transforms()
  File "/home/docs/checkouts/readthedocs.org/user_builds/dask/envs/10098/lib/python3.9/site-packages/sphinx/transforms/__init__.py", line 79, in apply_transforms
    super().apply_transforms()
  File "/home/docs/checkouts/readthedocs.org/user_builds/dask/envs/10098/lib/python3.9/site-packages/docutils/transforms/__init__.py", line 171, in apply_transforms
    transform.apply(**kwargs)
  File "/home/docs/checkouts/readthedocs.org/user_builds/dask/envs/10098/lib/python3.9/site-packages/jupyter_sphinx/execute.py", line 158, in apply
    notebook = execute_cells(
  File "/home/docs/checkouts/readthedocs.org/user_builds/dask/envs/10098/lib/python3.9/site-packages/jupyter_sphinx/execute.py", line 288, in execute_cells
    notebook = blank_nb(kernel_name)
  File "/home/docs/checkouts/readthedocs.org/user_builds/dask/envs/10098/lib/python3.9/site-packages/jupyter_sphinx/utils.py", line 15, in blank_nb
    raise ExtensionError("Unable to find kernel", orig_exc=e)
sphinx.errors.ExtensionError: Unable to find kernel (exception: No such kernel named python3)

Extension error:
Unable to find kernel (exception: No such kernel named python3)
```

See [this build](https://readthedocs.org/projects/dask/builds/19854932/) for an example

**Comment by jrbourbeau** [comment]
Closed via https://github.com/dask/dask/pull/10103 -- thanks @graingert
