### ISSUE TITLE
`ddf.set_index('col')` fails with pyarrow timestamp dtype column

### ISSUE THREAD

**Issue by bphillips-exos** [dask/dask#10160]
**Describe the issue**:
The `set_index` operation fails on dask dataframes when the column dtype is a pyarrow timestamp.

**Minimal Complete Verifiable Example**:

```python
import pandas as pd
import pyarrow as pa
import dask.dataframe as dd

ts_series = pd.Series([pd.Timestamp('2022-01-01')], dtype='datetime64[ns]')
pa_ts_series = pd.Series(
    data=[pd.Timestamp('2022-01-01')],
    dtype=pd.ArrowDtype(pa.timestamp('ns')),
)

df = pd.DataFrame({'ts': ts_series, 'pa_ts': pa_ts_series})

df.set_index('ts')  # works
df.set_index('pa_ts')  # works

ddf = dd.from_pandas(df, npartitions=1)

ddf.set_index('ts')  # works
ddf.set_index('pa_ts')  # fails
```

**Environment**:

- Pandas version: 2.0.0
- Dask version: 2023.3.2
- Python version: 3.10

**Traceback**:
```
Traceback (most recent call last):
  File "/Users/bphillips/workspace/exos-chronos/zz.py", line 20, in <module>
    ddf.set_index('pa_ts')  # fails
  File "/Users/bphillips/workspace/exos-chronos/.venv/lib/python3.10/site-packages/dask/dataframe/core.py", line 5199, in set_index
    return set_index(
  File "/Users/bphillips/workspace/exos-chronos/.venv/lib/python3.10/site-packages/dask/dataframe/shuffle.py", line 236, in set_index
    return result.map_partitions(M.sort_index)
  File "/Users/bphillips/workspace/exos-chronos/.venv/lib/python3.10/site-packages/dask/dataframe/core.py", line 998, in map_partitions
    return map_partitions(func, self, *args, **kwargs)
  File "/Users/bphillips/workspace/exos-chronos/.venv/lib/python3.10/site-packages/dask/dataframe/core.py", line 6863, in map_partitions
    meta = _get_meta_map_partitions(args, dfs, func, kwargs, meta, parent_meta)
  File "/Users/bphillips/workspace/exos-chronos/.venv/lib/python3.10/site-packages/dask/dataframe/core.py", line 6974, in _get_meta_map_partitions
    meta = _emulate(func, *args, udf=True, **kwargs)
  File "/Users/bphillips/workspace/exos-chronos/.venv/lib/python3.10/site-packages/dask/dataframe/core.py", line 6792, in _emulate
    with raise_on_meta_error(funcname(func), udf=udf), check_numeric_only_deprecation():
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/Users/bphillips/workspace/exos-chronos/.venv/lib/python3.10/site-packages/dask/dataframe/utils.py", line 214, in raise_on_meta_error
    raise ValueError(msg) from e
ValueError: Metadata inference failed in `sort_index`.

You have supplied a custom function and Dask is unable to 
determine the type of output that that function returns. 

To resolve this please provide a meta= keyword.
The docstring of the Dask function you ran should have more information.

Original error is below:
------------------------
ArrowTypeError("object of type <class 'str'> cannot be converted to int")

Traceback:
---------
  File "/Users/bphillips/workspace/exos-chronos/.venv/lib/python3.10/site-packages/dask/dataframe/utils.py", line 193, in raise_on_meta_error
    yield
  File "/Users/bphillips/workspace/exos-chronos/.venv/lib/python3.10/site-packages/dask/dataframe/core.py", line 6793, in _emulate
    return func(*_extract_meta(args, True), **_extract_meta(kwargs, True))
  File "/Users/bphillips/workspace/exos-chronos/.venv/lib/python3.10/site-packages/dask/dataframe/core.py", line 6773, in _extract_meta
    return tuple(_extract_meta(_x, nonempty) for _x in x)
  File "/Users/bphillips/workspace/exos-chronos/.venv/lib/python3.10/site-packages/dask/dataframe/core.py", line 6773, in <genexpr>
    return tuple(_extract_meta(_x, nonempty) for _x in x)
  File "/Users/bphillips/workspace/exos-chronos/.venv/lib/python3.10/site-packages/dask/dataframe/core.py", line 6769, in _extract_meta
    return x._meta_nonempty if nonempty else x._meta
  File "/Users/bphillips/workspace/exos-chronos/.venv/lib/python3.10/site-packages/dask/dataframe/core.py", line 558, in _meta_nonempty
    return meta_nonempty(self._meta)
  File "/Users/bphillips/workspace/exos-chronos/.venv/lib/python3.10/site-packages/dask/utils.py", line 642, in __call__
    return meth(arg, *args, **kwargs)
  File "/Users/bphillips/workspace/exos-chronos/.venv/lib/python3.10/site-packages/dask/dataframe/backends.py", line 314, in meta_nonempty_dataframe
    idx = meta_nonempty(x.index)
  File "/Users/bphillips/workspace/exos-chronos/.venv/lib/python3.10/site-packages/dask/utils.py", line 642, in __call__
    return meth(arg, *args, **kwargs)
  File "/Users/bphillips/workspace/exos-chronos/.venv/lib/python3.10/site-packages/dask/dataframe/backends.py", line 343, in _nonempty_index
    return pd.Index(["a", "b"], name=idx.name, dtype=idx.dtype)
  File "/Users/bphillips/workspace/exos-chronos/.venv/lib/python3.10/site-packages/pandas/core/indexes/base.py", line 551, in __new__
    arr = sanitize_array(data, None, dtype=dtype, copy=copy)
  File "/Users/bphillips/workspace/exos-chronos/.venv/lib/python3.10/site-packages/pandas/core/construction.py", line 559, in sanitize_array
    subarr = cls._from_sequence(data, dtype=dtype, copy=copy)
  File "/Users/bphillips/workspace/exos-chronos/.venv/lib/python3.10/site-packages/pandas/core/arrays/arrow/array.py", line 253, in _from_sequence
    scalars = pa.array(scalars, type=pa_dtype, from_pandas=True)
  File "pyarrow/array.pxi", line 320, in pyarrow.lib.array
  File "pyarrow/array.pxi", line 39, in pyarrow.lib._sequence_to_array
  File "pyarrow/error.pxi", line 144, in pyarrow.lib.pyarrow_internal_check_status
  File "pyarrow/error.pxi", line 123, in pyarrow.lib.check_status
```

**Comment by bphillips-exos** [comment]
A related example, although happy to move into another issue if appropriate. Seems to be tied to meta generation when the index is a pyarrow timestamp dtype

```python
index = pd.Series(
    data=[pd.Timestamp('2022-01-01')],
    dtype=pd.ArrowDtype(pa.timestamp('ns')),
)
str_series = pd.Series(['a'], index=index, dtype=pd.ArrowDtype(pa.string()))

df = pd.DataFrame(data={'str': str_series}, index=index)
ddf = dd.from_pandas(df, npartitions=1)

df['str'] = df['str'].astype(str)  # works
ddf['str'] = ddf['str'].astype(str)  # fails
```

**Comment by jrbourbeau** [comment]
Thanks for report @bphillips-exos. I'm able to reproduce.

cc @phofl for when you're back online
