### ISSUE TITLE
ZeroDivisionError when chunksize=-1, and small doc error

### ISSUE THREAD

**Issue by kasparthommen** [dask/dask#10297]
# 1. Bug

```python
import dask

def process(i: int) -> int:
    return 2 * i

if __name__ == '__main__':
    jobs = [dask.delayed(process)(i) for i in range(4)]
    results = dask.compute(*jobs, scheduler='processes', num_workers=4, chunksize=-1)
```

This leads to the following error:

```
Traceback (most recent call last):
  File "C:\Users\xxx\xxx\xxx\xxx\xxx\xxx\error.py", line 8, in <module>
    results = dask.compute(*jobs, scheduler='processes', num_workers=4, chunksize=-1)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\...\.conda\envs\p311\Lib\site-packages\dask\base.py", line 599, in compute
    results = schedule(dsk, keys, **kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\...\.conda\envs\p311\Lib\site-packages\dask\multiprocessing.py", line 233, in get
    result = get_async(
             ^^^^^^^^^^
  File "C:\Users\...\.conda\envs\p311\Lib\site-packages\dask\local.py", line 499, in get_async
    fire_tasks(chunksize)
  File "C:\Users\...\.conda\envs\p311\Lib\site-packages\dask\local.py", line 490, in fire_tasks
    for i in range(-(len(args) // -chunksize)):
                     ~~~~~~~~~~^^~~~~~~~~~~~
ZeroDivisionError: integer division or modulo by zero
```

# 2. Doc error
The documentation states that `chunksize` defaults to `5`, but `6` is actually used:

https://github.com/dask/dask/blob/cdb183a2dddfac6d1fb445be66f1c62f91434c13/dask/multiprocessing.py#L179-L184

**Comment by paciorek** [comment]
I also experienced these issues.

In addition, I'm wondering about the default of 5 (or 6). If a user has a small number of tasks relative to the number of workers, e.g., the simple case of 4 tasks and 4 workers, with this default, Dask will run through the tasks serially as discussed in #10292 . I'm wondering why the default is not -1 (once the bug with that is fixed).

As a separate comment on documentation, I think it would be helpful to have the use of `chunksize` documented with `config.set()` and/or `compute()` (but noting #10292 discussion about why documenting it in that context is tricky). I had a hard time understanding the chunking behavior without going into the code base. Perhaps I just missed it somewhere, but searching for "chunksize" in the docs led to a bunch of hits related to chunking in distributed data objects rather than chunking of tasks.

A reason for better documentation of this option is that depending on the heterogeneity of the completion time of the tasks, a user might prefer static allocation (with even division of tasks) or dynamic allocation of tasks one by one (to avoid the possibililty that the slow tasks are clumped on on or more workers).
