### ISSUE TITLE
Cache is not thread safe

### ISSUE THREAD

**Issue by andy-sweet** [dask/dask#10396]
**Describe the issue**:

Computing any dask graphs while using the same cache on multiple threads can cause errors.

This has been previously reported in a variety of issues (e.g. https://github.com/dask/dask/issues/896, https://github.com/dask/distributed/issues/2372, https://github.com/napari/napari/issues/5591, https://github.com/haesleinhuepf/napari-time-slicer/pull/6), but I wrote a new issue with a reproducer to clarify the underlying cause.

**Minimal Complete Verifiable Example**:

The following Python code should always raise an exception on the non-main thread.

```python
import numpy as np
import dask.array as da
from dask.cache import Cache
from threading import Condition, RLock, Thread

# Extend the regular cache so that we block execution after
# _pretask has finished but before _posttask has started.
class BlockingCache(Cache):
    def __init__(self, cache):
        super().__init__(cache)
        self.task_finished = Condition()
        self.posttask_lock = RLock()

    def _posttask(self, key, value, dsk, state, id):
        with self.task_finished:
            self.task_finished.notify()
        with self.posttask_lock:
            super()._posttask(key, value, dsk, state, id)


def cached_array_index(cache, array, index):
    with cache:
        return array[index].compute()


def test_multithreaded_access():
    array = da.from_array([0, 1])
    # Cache size is irrelevant because we don't need it here.
    cache = BlockingCache(1)
    thread = Thread(target=cached_array_index, args=(cache, array, 0))
    # Hold the posttask_lock to prevent the other thread from
    # executing the actual cache's _posttask callback.
    with cache.posttask_lock:
        with cache.task_finished:
            thread.start()
            # Wait for the other thread to reach _posttask.
            cache.task_finished.wait()
        # Execute the whole graph on the main thread.
        cached_array_index(cache, array, 1)
    # Wait for the other thread to finish executing.
    thread.join()

if __name__ == '__main__':
    test_multithreaded_access()
```

Here is the error I get on my local machine.

```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/Users/asweet/software/miniconda3/envs/napari-cryoet-data-portal-dev/lib/python3.9/threading.py", line 980, in _bootstrap_inner
    self.run()
  File "/Users/asweet/software/miniconda3/envs/napari-cryoet-data-portal-dev/lib/python3.9/threading.py", line 917, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/asweet/data/bugs/5591/simplified_dask.py", line 23, in cached_array_index
    return array[index].compute()
  File "/Users/asweet/software/miniconda3/envs/napari-cryoet-data-portal-dev/lib/python3.9/site-packages/dask/base.py", line 310, in compute
    (result,) = compute(self, traverse=False, **kwargs)
  File "/Users/asweet/software/miniconda3/envs/napari-cryoet-data-portal-dev/lib/python3.9/site-packages/dask/base.py", line 595, in compute
    results = schedule(dsk, keys, **kwargs)
  File "/Users/asweet/software/miniconda3/envs/napari-cryoet-data-portal-dev/lib/python3.9/site-packages/dask/threaded.py", line 89, in get
    results = get_async(
  File "/Users/asweet/software/miniconda3/envs/napari-cryoet-data-portal-dev/lib/python3.9/site-packages/dask/local.py", line 516, in get_async
    f(key, res, dsk, state, worker_id)
  File "/Users/asweet/data/bugs/5591/simplified_dask.py", line 18, in _posttask
    super()._posttask(key, value, dsk, state, id)
  File "/Users/asweet/software/miniconda3/envs/napari-cryoet-data-portal-dev/lib/python3.9/site-packages/dask/cache.py", line 58, in _posttask
    duration = default_timer() - self.starttimes[key]
KeyError: ('getitem-8d24cd8febbf60810a2497062186234f',)
```

I also [created a diagram to show what's happening here](https://github.com/andy-sweet/napari-diagrams/blob/main/dask-cache-multithread-error.drawio.svg).

Note that in this case, the tasks are different, but that doesn't matter since `Cache._finish` clears `Cache.starttimes`. There is another more interesting variant of this bug where the cache actually gets used.

```python
def test_multithreaded_access_same_key():
    array = da.from_array([0, 1])
    # Cache is not big enough to store even one result, so each
    # array access will cause a task to be executed.
    cache = BlockingCache(1)
    thread = Thread(target=cached_array_index, args=(cache, array, 0))
    with cache.posttask_lock:
        with cache.task_finished:
            thread.start()
            cache.task_finished.wait()
        cached_array_index(cache, array, 0)
    thread.join()
```

Any fix here should probably fix both of these tests as a minimum.

**Anything else we need to know?**:

I'm mostly coming here from napari (https://github.com/napari/napari/pull/5610). Based on comments from the related issues, it sounds like there was no intent to make `Cache` thread safe and there may not be much motivation to make it thread safe in the future. I think that's fine, but hope this issue is still hopeful for others running into the same issue.

One potential fix is to change the implementation of `Cache._posttask` and `Cache._finish` to be the following.

```python
    def _posttask(self, key, value, dsk, state, id):
        if starttime := self.starttimes.pop(key, None):
            duration = default_timer() - starttime
            if deps := state["dependencies"][key]:
                duration += max(self.durations.get(k, 0) for k in deps)
            self.durations[key] = duration
            nb = self._nbytes(value) + overhead + sys.getsizeof(key) * 4
            self.cache.put(key, value, cost=duration / nb / 1e9, nbytes=nb)

    def _finish(self, dsk, state, errored):
        self.durations.clear()
```

This fixes the tests above and seems to make some vague sense to me (i.e. don't update the cache when a stale task finishes), but I don't know enough about dask to state that with much certainty.

**Environment**:

- Dask version: 2023.6.1
- Python version: Python 3.9.6
- Operating System: macOS 13.4 (Intel)
- Install method (conda, pip, source): pip

**Comment by mrocklin** [comment]
I just briefly chatted with @jni .  My sense is that a PR making dask.cache.Cache threadsafe (or a PR to cachey doing it, if that solves the problem) would be welcome.  Any lack of engagement here is due only to lack of attention, not any kind of disagreement.  

I'm hopeful that a `threading.Lock` in the right few places will suffice.
