### ISSUE TITLE
RecursionError: An error occurred while calling the read_csv method registered to the pandas backend

### ISSUE THREAD

**Issue by quankhuc** [dask/dask#10403]
I tried to read a csv file from google cloud storage bucket. I am using the function read_csv() but encounter `RecursionError`. I appreciate any guidance to fix this issue.

** Steps to reproduce**
1. Create a bucket in google cloud storage amd upload an example csv file
2. Get the service account json file
3. Create a quick start FastAPI project
4. Run the route to get the csv file

**Minimal Complete Verifiable Example**:

```python
@live_trading_router.get("/get_csv_file_from_gcp")
async def get_csv_file_from_gcp():
    # Create a temporary file with some content
    ddf: DaskDataFrame = dd.read_csv(
            f"gcs://path-to-csv-file",
            storage_options={"token": "service-account.json"},
        )
    df: PandasDataFrame = ddf.compute()
    return JSONResponse(status_code=200, content={"message": "success"})
```

**Stack trace**:
```zsh
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/Users/quankhuc/anaconda3/envs/TradingBot/lib/python3.11/site-packages/dask/backends.py", line 136, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/quankhuc/anaconda3/envs/TradingBot/lib/python3.11/site-packages/dask/dataframe/io/csv.py", line 760, in read
    return read_pandas(
           ^^^^^^^^^^^^
  File "/Users/quankhuc/anaconda3/envs/TradingBot/lib/python3.11/site-packages/dask/dataframe/io/csv.py", line 561, in read_pandas
    b_out = read_bytes(
            ^^^^^^^^^^^
  File "/Users/quankhuc/anaconda3/envs/TradingBot/lib/python3.11/site-packages/dask/bytes/core.py", line 111, in read_bytes
    size = fs.info(path)["size"]
           ^^^^^^^^^^^^^
  File "/Users/quankhuc/anaconda3/envs/TradingBot/lib/python3.11/site-packages/fsspec/asyn.py", line 115, in wrapper
    return sync(self.loop, func, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/quankhuc/anaconda3/envs/TradingBot/lib/python3.11/site-packages/fsspec/asyn.py", line 100, in sync
    raise return_result
  File "/Users/quankhuc/anaconda3/envs/TradingBot/lib/python3.11/site-packages/fsspec/asyn.py", line 55, in _runner
    result[0] = await coro
                ^^^^^^^^^^
  File "/Users/quankhuc/anaconda3/envs/TradingBot/lib/python3.11/site-packages/gcsfs/core.py", line 802, in _info
    exact = await self._get_object(path)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/quankhuc/anaconda3/envs/TradingBot/lib/python3.11/site-packages/gcsfs/core.py", line 503, in _get_object
    res = await self._call(
          ^^^^^^^^^^^^^^^^^
  File "/Users/quankhuc/anaconda3/envs/TradingBot/lib/python3.11/site-packages/gcsfs/core.py", line 430, in _call
    status, headers, info, contents = await self._request(
                                      ^^^^^^^^^^^^^^^^^^^^
  File "/Users/quankhuc/anaconda3/envs/TradingBot/lib/python3.11/site-packages/decorator.py", line 221, in fun
    return await caller(func, *(extras + args), **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/quankhuc/anaconda3/envs/TradingBot/lib/python3.11/site-packages/gcsfs/retry.py", line 114, in retry_request
    return await func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/quankhuc/anaconda3/envs/TradingBot/lib/python3.11/site-packages/gcsfs/core.py", line 414, in _request
    headers=self._get_headers(headers),
            ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/quankhuc/anaconda3/envs/TradingBot/lib/python3.11/site-packages/gcsfs/core.py", line 393, in _get_headers
    self.credentials.apply(out)
  File "/Users/quankhuc/anaconda3/envs/TradingBot/lib/python3.11/site-packages/gcsfs/credentials.py", line 187, in apply
    self.maybe_refresh()
  File "/Users/quankhuc/anaconda3/envs/TradingBot/lib/python3.11/site-packages/gcsfs/credentials.py", line 182, in maybe_refresh
    self.credentials.refresh(req)
  File "/Users/quankhuc/anaconda3/envs/TradingBot/lib/python3.11/site-packages/google/oauth2/service_account.py", line 434, in refresh
    access_token, expiry, _ = _client.jwt_grant(
                              ^^^^^^^^^^^^^^^^^^
  File "/Users/quankhuc/anaconda3/envs/TradingBot/lib/python3.11/site-packages/google/oauth2/_client.py", line 312, in jwt_grant
    response_data = _token_endpoint_request(
                    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/quankhuc/anaconda3/envs/TradingBot/lib/python3.11/site-packages/google/oauth2/_client.py", line 272, in _token_endpoint_request
    response_status_ok, response_data, retryable_error = _token_endpoint_request_no_throw(
                                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/quankhuc/anaconda3/envs/TradingBot/lib/python3.11/site-packages/google/oauth2/_client.py", line 219, in _token_endpoint_request_no_throw
    request_succeeded, response_data, retryable_error = _perform_request()
                                                        ^^^^^^^^^^^^^^^^^^
  File "/Users/quankhuc/anaconda3/envs/TradingBot/lib/python3.11/site-packages/google/oauth2/_client.py", line 195, in _perform_request
    response = request(
               ^^^^^^^^
  File "/Users/quankhuc/anaconda3/envs/TradingBot/lib/python3.11/site-packages/google/auth/transport/requests.py", line 193, in __call__
    response = self.session.request(
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/quankhuc/anaconda3/envs/TradingBot/lib/python3.11/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/quankhuc/anaconda3/envs/TradingBot/lib/python3.11/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/quankhuc/anaconda3/envs/TradingBot/lib/python3.11/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/Users/quankhuc/anaconda3/envs/TradingBot/lib/python3.11/site-packages/urllib3/connectionpool.py", line 714, in urlopen
    httplib_response = self._make_request(
                       ^^^^^^^^^^^^^^^^^^^
  File "/Users/quankhuc/anaconda3/envs/TradingBot/lib/python3.11/site-packages/urllib3/connectionpool.py", line 403, in _make_request
    self._validate_conn(conn)
  File "/Users/quankhuc/anaconda3/envs/TradingBot/lib/python3.11/site-packages/urllib3/connectionpool.py", line 1053, in _validate_conn
    conn.connect()
  File "/Users/quankhuc/anaconda3/envs/TradingBot/lib/python3.11/site-packages/urllib3/connection.py", line 400, in connect
    self.ssl_context = create_urllib3_context(
                       ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/quankhuc/anaconda3/envs/TradingBot/lib/python3.11/site-packages/urllib3/util/ssl_.py", line 312, in create_urllib3_context
    context.options |= options
    ^^^^^^^^^^^^^^^
  File "/Users/quankhuc/anaconda3/envs/TradingBot/lib/python3.11/ssl.py", line 624, in options
    super(SSLContext, SSLContext).options.__set__(self, value)
  File "/Users/quankhuc/anaconda3/envs/TradingBot/lib/python3.11/ssl.py", line 624, in options
    super(SSLContext, SSLContext).options.__set__(self, value)
  File "/Users/quankhuc/anaconda3/envs/TradingBot/lib/python3.11/ssl.py", line 624, in options
    super(SSLContext, SSLContext).options.__set__(self, value)
  [Previous line repeated 482 more times]
RecursionError: maximum recursion depth exceeded

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/quankhuc/anaconda3/envs/TradingBot/lib/python3.11/site-packages/uvicorn/protocols/http/httptools_impl.py", line 435, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/quankhuc/anaconda3/envs/TradingBot/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/quankhuc/anaconda3/envs/TradingBot/lib/python3.11/site-packages/fastapi/applications.py", line 282, in __call__
    await super().__call__(scope, receive, send)
  File "/Users/quankhuc/anaconda3/envs/TradingBot/lib/python3.11/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/quankhuc/anaconda3/envs/TradingBot/lib/python3.11/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/Users/quankhuc/anaconda3/envs/TradingBot/lib/python3.11/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/Users/quankhuc/anaconda3/envs/TradingBot/lib/python3.11/site-packages/starlette/middleware/cors.py", line 83, in __call__
    await self.app(scope, receive, send)
  File "/Users/quankhuc/anaconda3/envs/TradingBot/lib/python3.11/site-packages/starlette/middleware/authentication.py", line 48, in __call__
    await self.app(scope, receive, send)
  File "/Users/quankhuc/Documents/GitHub/Trading-Bot-FastAPI/core/fastapi/middlewares/sqlalchemy.py", line 19, in __call__
    raise exception
  File "/Users/quankhuc/Documents/GitHub/Trading-Bot-FastAPI/core/fastapi/middlewares/sqlalchemy.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "/Users/quankhuc/Documents/GitHub/Trading-Bot-FastAPI/core/fastapi/middlewares/response_logger.py", line 37, in __call__
    await self.app(scope, receive, _logging_send)
  File "/Users/quankhuc/anaconda3/envs/TradingBot/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/Users/quankhuc/anaconda3/envs/TradingBot/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/Users/quankhuc/anaconda3/envs/TradingBot/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
    raise e
  File "/Users/quankhuc/anaconda3/envs/TradingBot/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "/Users/quankhuc/anaconda3/envs/TradingBot/lib/python3.11/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/Users/quankhuc/anaconda3/envs/TradingBot/lib/python3.11/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/Users/quankhuc/anaconda3/envs/TradingBot/lib/python3.11/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
               ^^^^^^^^^^^^^^^^^^^
  File "/Users/quankhuc/anaconda3/envs/TradingBot/lib/python3.11/site-packages/fastapi/routing.py", line 241, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/quankhuc/anaconda3/envs/TradingBot/lib/python3.11/site-packages/fastapi/routing.py", line 167, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/quankhuc/Documents/GitHub/Trading-Bot-FastAPI/api/v1/live_trading/live_trading.py", line 51, in test_sending_data_to_gcp
    ddf: DaskDataFrame = dd.read_csv(
                         ^^^^^^^^^^^^
  File "/Users/quankhuc/anaconda3/envs/TradingBot/lib/python3.11/site-packages/dask/backends.py", line 138, in wrapper
    raise type(e)(
RecursionError: An error occurred while calling the read_csv method registered to the pandas backend.
Original Message: maximum recursion depth exceeded
```

**Environment**:

- Dask version: Version: 2023.7.0
- Python version: 3.11.3
- Operating System: Mac OSX ARM 1
- Install method (conda, pip, source): pip 23.1.2

**Comment by jrbourbeau** [comment]
Thanks for the issue @quankhuc. There are quite a few things going on in your use case. Are you able to isolate things more? For example, does the `dd.read_csv` call run successfully outside the fastapi project?

**Comment by quankhuc** [comment]
Thank you for your response. I was able to run it somehow again when I created a quick start FastAPI in a blank file. Thank you for your help!

**Comment by jrbourbeau** [comment]
No problem -- glad to hear things are working
