### ISSUE TITLE
"ValueError: bytes object is too large" for calculation on LocalCluster breaks code running with older dask versions

### ISSUE THREAD

**Issue by Pescatore23** [dask/dask#10429]
**Describe the issue**:

After updating to dask 2023.7.1, previously working (unfortunately don't remember the previous version) code (see MCVE below) crashes with the following error:

```
/mpc/homes/fische_r/miniconda3/lib/python3.10/site-packages/distributed/client.py:3141: UserWarning: Sending large graph of size 6.99 GiB.
This may cause some slowdown.
Consider scattering data ahead of time and using futures.
  warnings.warn(
2023-07-26 11:29:12,673 - distributed.protocol.core - CRITICAL - Failed to Serialize
Traceback (most recent call last):
  File "/mpc/homes/fische_r/miniconda3/lib/python3.10/site-packages/distributed/protocol/core.py", line 109, in dumps
    frames[0] = msgpack.dumps(msg, default=_encode_default, use_bin_type=True)
  File "/mpc/homes/fische_r/miniconda3/lib/python3.10/site-packages/msgpack/__init__.py", line 38, in packb
    return Packer(**kwargs).pack(o)
  File "msgpack/_packer.pyx", line 294, in msgpack._cmsgpack.Packer.pack
  File "msgpack/_packer.pyx", line 300, in msgpack._cmsgpack.Packer.pack
  File "msgpack/_packer.pyx", line 297, in msgpack._cmsgpack.Packer.pack
  File "msgpack/_packer.pyx", line 264, in msgpack._cmsgpack.Packer._pack
  File "msgpack/_packer.pyx", line 231, in msgpack._cmsgpack.Packer._pack
  File "msgpack/_packer.pyx", line 264, in msgpack._cmsgpack.Packer._pack
  File "msgpack/_packer.pyx", line 202, in msgpack._cmsgpack.Packer._pack
ValueError: bytes object is too large
2023-07-26 11:29:12,723 - distributed.comm.utils - ERROR - bytes object is too large
Traceback (most recent call last):
  File "/mpc/homes/fische_r/miniconda3/lib/python3.10/site-packages/distributed/comm/utils.py", line 55, in _to_frames
    return list(protocol.dumps(msg, **kwargs))
  File "/mpc/homes/fische_r/miniconda3/lib/python3.10/site-packages/distributed/protocol/core.py", line 109, in dumps
    frames[0] = msgpack.dumps(msg, default=_encode_default, use_bin_type=True)
  File "/mpc/homes/fische_r/miniconda3/lib/python3.10/site-packages/msgpack/__init__.py", line 38, in packb
    return Packer(**kwargs).pack(o)
  File "msgpack/_packer.pyx", line 294, in msgpack._cmsgpack.Packer.pack
  File "msgpack/_packer.pyx", line 300, in msgpack._cmsgpack.Packer.pack
  File "msgpack/_packer.pyx", line 297, in msgpack._cmsgpack.Packer.pack
  File "msgpack/_packer.pyx", line 264, in msgpack._cmsgpack.Packer._pack
  File "msgpack/_packer.pyx", line 231, in msgpack._cmsgpack.Packer._pack
  File "msgpack/_packer.pyx", line 264, in msgpack._cmsgpack.Packer._pack
  File "msgpack/_packer.pyx", line 202, in msgpack._cmsgpack.Packer._pack
ValueError: bytes object is too large
2023-07-26 11:29:12,743 - distributed.batched - ERROR - Error in batched write
Traceback (most recent call last):
  File "/mpc/homes/fische_r/miniconda3/lib/python3.10/site-packages/distributed/batched.py", line 115, in _background_send
    nbytes = yield coro
  File "/mpc/homes/fische_r/miniconda3/lib/python3.10/site-packages/tornado/gen.py", line 767, in run
    value = future.result()
  File "/mpc/homes/fische_r/miniconda3/lib/python3.10/site-packages/distributed/comm/tcp.py", line 271, in write
    frames = await to_frames(
  File "/mpc/homes/fische_r/miniconda3/lib/python3.10/site-packages/distributed/comm/utils.py", line 70, in to_frames
    return await offload(_to_frames)
  File "/mpc/homes/fische_r/miniconda3/lib/python3.10/site-packages/distributed/utils.py", line 1519, in run_in_executor_with_context
    return await loop.run_in_executor(
  File "/mpc/homes/fische_r/miniconda3/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/mpc/homes/fische_r/miniconda3/lib/python3.10/site-packages/distributed/utils.py", line 1520, in <lambda>
    executor, lambda: context.run(func, *args, **kwargs)
  File "/mpc/homes/fische_r/miniconda3/lib/python3.10/site-packages/distributed/comm/utils.py", line 55, in _to_frames
    return list(protocol.dumps(msg, **kwargs))
  File "/mpc/homes/fische_r/miniconda3/lib/python3.10/site-packages/distributed/protocol/core.py", line 109, in dumps
    frames[0] = msgpack.dumps(msg, default=_encode_default, use_bin_type=True)
  File "/mpc/homes/fische_r/miniconda3/lib/python3.10/site-packages/msgpack/__init__.py", line 38, in packb
    return Packer(**kwargs).pack(o)
  File "msgpack/_packer.pyx", line 294, in msgpack._cmsgpack.Packer.pack
  File "msgpack/_packer.pyx", line 300, in msgpack._cmsgpack.Packer.pack
  File "msgpack/_packer.pyx", line 297, in msgpack._cmsgpack.Packer.pack
  File "msgpack/_packer.pyx", line 264, in msgpack._cmsgpack.Packer._pack
  File "msgpack/_packer.pyx", line 231, in msgpack._cmsgpack.Packer._pack
  File "msgpack/_packer.pyx", line 264, in msgpack._cmsgpack.Packer._pack
  File "msgpack/_packer.pyx", line 202, in msgpack._cmsgpack.Packer._pack
ValueError: bytes object is too large

---------------------------------------------------------------------------
CancelledError                            Traceback (most recent call last)
Cell In[15], line 1
----> 1 blur = blur.compute()

File ~/miniconda3/lib/python3.10/site-packages/distributed/client.py:2248, in Client._gather(self, futures, errors, direct, local_worker)
   2246     else:
   2247         raise exception.with_traceback(traceback)
-> 2248     raise exc
   2249 if errors == "skip":
   2250     bad_keys.add(key)

CancelledError: ('_trim-f29bbfe41246458b3b3430ad0e74d59d', 4, 0, 5, 0)
```

The calculation completes for smaller data arrays with a warning,

```
/mpc/homes/fische_r/miniconda3/lib/python3.10/site-packages/distributed/client.py:3141: UserWarning: Sending large graph of size 0.93 GiB.
This may cause some slowdown.
Consider scattering data ahead of time and using futures.
  warnings.warn(
```

or if not using the LocalScheduler (not calling ```Client()```), as long as the calculation fits into RAM. 

It appears to me that the graph may not be larger than 4GiB, see https://github.com/dask/distributed/issues/5498#issuecomment-962172751

**Minimal Complete Verifiable Example**:

```python
import numpy as np
from skimage import filters
import dask
import dask.array
from dask.distributed import  Client, LocalCluster

memlim = '750GB' #3/4 of available RAM on machine

cluster = LocalCluster(memory_limit = memlim, n_workers=1)

client = Client(cluster) # code runs just fine without calling the LocalCluster, i.e. on the threaded? scheduler

def Gaussian_Blur_space(da, sigma):      
    deptharray = np.ones(da.ndim)+4*sigma
    deptharray[-1] = 0
    sigmas = np.ones(deptharray.shape)*sigma
    deptharray = tuple(np.min([deptharray, da.shape], axis=0))

    sigmas[-1] = 0
    G = da.map_overlap(filters.gaussian, depth=deptharray, boundary='nearest', sigma = sigmas, preserve_range=True)
    return G

shp = (750, 100, 400, 50) # typical shape of image data: (750, 108, 2016, 53)

im = (np.random.rand(*shp)*10000).astype(np.uint16)

da = dask.array.from_array(im, chunks='auto')

blur = Gaussian_Blur_space(da, 1)

blur = blur.compute()
```

**Anything else we need to know?**:

I am regularily dealing with large 4D image data (time resolved X-ray tomography) and dask has helped me up to now to deal with image processing of this larger-than-memory data by spilling tasks to disk. If there is a different, maybe "proper", way to implement and apply filters like the 4D Gaussian Blur above, I am happy to learn of a suitable reference.
For me, it is a lesson to pay more attention to proper management of virtual envs ;)

**Environment**:

- Dask version: 2023.7.1
- Python version: 3.10.12
- Operating System: red hat linux
- Install method (conda, pip, source): conda

**Comment by Pescatore23** [comment]
the code runs just fine when creating the dask array in dask following the tips in https://docs.dask.org/en/stable/best-practices.html#load-data-with-dask:
```da = dask.array.random.randint(1, 16000, shp)```

Now, I just need to find a way to read my data directly into dask and I should be fine. 

Sorry about the fuzz and you can close the issue if you want.
Thanks a lot for your work :)

**Comment by fjetter** [comment]
The ValueError is mildly concerning and something we should have a look at. If you found a way to bypass it, that's great.

> If there is a different, maybe "proper", way to implement and apply filters like the 4D Gaussian Blur above, I am happy to learn of a suitable reference.

I'm unfortunately not a domain expert for image processing but have you checked out [dask-image](https://image.dask.org/en/latest/)? There are some gaussian filters but I don't know if this is the same as you are doing https://image.dask.org/en/latest/dask_image.ndfilters.html#dask_image.ndfilters.gaussian_filter 


> Now, I just need to find a way to read my data directly into dask and I should be fine.

For usage related questions, I recommend asking a question on [discourse](https://dask.discourse.group/). 


> Sorry about the fuzz and you can close the issue if you want.

No worries. Feel free to re-open if you are encountering this again

**Comment by Pescatore23** [comment]
Thanks for pointing to the discourse and the heads-up to check out dask-image again. It seemed a bit quiet recently. Might be actually interesting to reconsider using dask-image instead of mapping scikit-image
