### ISSUE TITLE
to_csv doesn't support file-like objects

### ISSUE THREAD

**Issue by Martmists-GH** [dask/dask#10564]

**Comment by benrutter** [comment]
Hi @Martmists-GH, do you have any detail on this?

I tried to recreate the issue and I guess this is the issue you're talking about:

```python
import pandas as pd
import dask.dataframe as dd

df = pd.DataFrame({"a": [1, 2, 3]})

with open("eg.csv", "w") as file:
    df.to_csv(file)

ddf = dd.from_pandas(df, npartitions=2)

with open("eg.csv", "w") as file:
    ddf.to_csv(file)
```

pandas will write fine to an io stream object like that, but dask throws a "UnsupportedOperation".

I'm not really an authority at all on anything much, but it seems like if it was implemented, it would mean write operations couldn't be parallelized (dask will by default save to lots of different csvs which is really handy for big data).

Would a more expressive error message saying something along those lines been nicer? Or is there something specific you're trying to achieve that involves writing to a file-like object>

**Comment by Martmists-GH** [comment]
Hmm, I'm not getting an UnsupportedOperation but an AttributeError:

```py
>>> import pandas as pd
>>> import dask.dataframe as dd
>>> import io
>>> df = pd.DataFrame({"a":[1,2,3],"b":[4,5,6]})
>>> ddf = dd.from_pandas(df, npartitions=1)
>>> out = io.StringIO()
>>> ddf.to_csv(out)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\M66G898\.pyenv-win-venv\envs\nn_monitoring\Lib\site-packages\dask\dataframe\core.py", line 1897, in to_csv
    return to_csv(self, filename, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\M66G898\.pyenv-win-venv\envs\nn_monitoring\Lib\site-packages\dask\dataframe\io\csv.py", line 955, in to_csv
    files = open_files(
            ^^^^^^^^^^^
  File "C:\Users\M66G898\.pyenv-win-venv\envs\nn_monitoring\Lib\site-packages\fsspec\core.py", line 280, in open_files
    fs, fs_token, paths = get_fs_token_paths(
                          ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\M66G898\.pyenv-win-venv\envs\nn_monitoring\Lib\site-packages\fsspec\core.py", line 610, in get_fs_token_paths
    chain = _un_chain(urlpath0, storage_options or {})
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\M66G898\.pyenv-win-venv\envs\nn_monitoring\Lib\site-packages\fsspec\core.py", line 331, in _un_chain
    bit = cls._strip_protocol(bit)
          ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\M66G898\.pyenv-win-venv\envs\nn_monitoring\Lib\site-packages\fsspec\implementations\local.py", line 214, in _strip_protocol
    if path.startswith("file://"):
       ^^^^^^^^^^^^^^^
AttributeError: '_io.StringIO' object has no attribute 'startswith'
```

It's fine if it's not fully parallelized for writing as (at least for our use-case) it will only write aggregated results. Perhaps it would be an idea to support file-like objects without parallelizing, but warn the user about the writes not being parallel?

**Comment by benrutter** [comment]
That makes sense, the dask documentation calls that first argument "filename" and says it has to be a string or a list. Someone closer to the project could probably comment better, but it doesn't look like writing to IO objects is part of the designed behaviour.

If you did need to do that for some reason, you could compute first (you'd need everything stored in memory to have it in a single IO object anyway)

```python
ddf.compute().to_csv(out)
```
