### ISSUE TITLE
DataFrameGroupBy.agg numeric_only incompatible with pd.NamedAgg

### ISSUE THREAD

**Issue by Martmists-GH** [dask/dask#10566]
due to .agg being wrapped with numeric_only_not_implemented, I need to explicitly pass `numeric_only=True`. However, this argument is never popped from kwargs, meaning `reconstruct_func` is called with `numeric_only=True` still in kwargs, and results in `is_multi_agg_with_relabel` returning False, as it doesn't match a relabel aggregation. This causes a `TypeError: Must provide 'func' or tuples of '(column, aggfunc).`

**Comment by rjzamora** [comment]
Thanks for raising this issue @Martmists-GH (and for submitting #10588).  Can you share [a reproducer](http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports)?

**Comment by Martmists-GH** [comment]
```py
>>> import pandas as pd
>>> import dask.dataframe as dd
>>> df = pd.DataFrame({"a":[1,1,2,2],"b":[1,2,3,4],"c":["w","x","y","z"]})
>>> ddf = dd.from_pandas(df, npartitions=1)
>>> ddf.groupby("a").agg(c=pd.NamedAgg("b", "sum"))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/mart/.pyenv/versions/temp/lib/python3.11/site-packages/dask/dataframe/groupby.py", line 339, in wrapper
    raise NotImplementedError(
NotImplementedError: 'numeric_only=False' is not implemented in Dask.
>>> ddf.groupby("a").agg(numeric_only=True, c=pd.NamedAgg("b", "sum"))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/mart/.pyenv/versions/temp/lib/python3.11/site-packages/dask/dataframe/groupby.py", line 352, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mart/.pyenv/versions/temp/lib/python3.11/site-packages/dask/dataframe/groupby.py", line 2928, in agg
    return self.aggregate(
           ^^^^^^^^^^^^^^^
  File "/home/mart/.pyenv/versions/temp/lib/python3.11/site-packages/dask/dataframe/groupby.py", line 2917, in aggregate
    return super().aggregate(
           ^^^^^^^^^^^^^^^^^^
  File "/home/mart/.pyenv/versions/temp/lib/python3.11/site-packages/dask/dataframe/groupby.py", line 2222, in aggregate
    relabeling, arg, columns, order = reconstruct_func(arg, **kwargs)
                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mart/.pyenv/versions/temp/lib/python3.11/site-packages/pandas/core/apply.py", line 1476, in reconstruct_func
    raise TypeError("Must provide 'func' or tuples of '(column, aggfunc).")
TypeError: Must provide 'func' or tuples of '(column, aggfunc).
```

**Comment by tRosenflanz** [comment]
Having the same issue

**Comment by tRosenflanz** [comment]
Found a workaround. Since the code only checks for `numeric_only = False`, we can just pass numeric_only as some random aggregation and it will pass as it is numeric_only is no longer False. The column can be dropped afterwards.

`ddf.groupby("a").agg(numeric_only=d=pd.NamedAgg("b", "sum"), d=pd.NamedAgg("b", "sum")).drop(columns=['numeric_only'])` works as intended

**Comment by Martmists-GH** [comment]
we ended up using pyasm to inject a `kwargs.pop('numeric_only')` at the start of the function as temporary workaround.

**Comment by CarlaFernandez** [comment]
Having this same issue, any updates?
