### ISSUE TITLE
Dask requires read permission for writing dataframe parquet to s3

### ISSUE THREAD

**Issue by trgmg** [dask/dask#10635]
**Describe the issue**:
I cannot write a dataframe to an s3 bucket without READ permission to that bucket. Is that expected behavior? I cannot find anything anywhere regarding this.

**Minimal Complete Verifiable Example**:

```python
import pandas as pd
import dask.dataframe as dd

bucket_name = "my-amazing-bucket"
object_key = "banana.parquet"
df = pd.DataFrame({"A": [0, 1, 2], "B": ["ba", "na", "na"]})
df = dd.from_pandas(df, npartitions=2)
df.to_parquet(f"s3://{bucket_name}/{object_key}")
```

If the corresponding role only has write permission like so it doesn't work:
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Action": [
                "s3:PutObject",
                "s3:PutObjectLegalHold",
                "s3:PutObjectRetention",
                "s3:PutObjectTagging",
                "s3:PutObjectVersionTagging",
                "s3:Abort*"
            ],
            "Resource": "arn:aws:s3:::my-amazing-bucket/*",
            "Effect": "Allow"
        }
    ]
}
```

Giving the following error:
```
Traceback (most recent call last):
File "/usr/local/lib/python3.9/site-packages/s3fs/core.py", line 110, in _error_wrapper
return await func(*args, **kwargs)
File "/usr/local/lib/python3.9/site-packages/aiobotocore/client.py", line 265, in _make_api_call
raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (403) when calling the HeadObject operation: Forbidden
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
File "/work/src/banana.py", line 8, in <module>
df.to_parquet(f"s3://{bucket_name}/{key}")
File "/usr/local/lib/python3.9/site-packages/dask/dataframe/core.py", line 5721, in to_parquet
return to_parquet(self, path, *args, **kwargs)
File "/usr/local/lib/python3.9/site-packages/dask/dataframe/io/parquet/core.py", line 868, in to_parquet
if fs.exists(path) and fs.isdir(path):
File "/usr/local/lib/python3.9/site-packages/fsspec/asyn.py", line 111, in wrapper
return sync(self.loop, func, *args, **kwargs)
File "/usr/local/lib/python3.9/site-packages/fsspec/asyn.py", line 96, in sync
raise return_result
File "/usr/local/lib/python3.9/site-packages/fsspec/asyn.py", line 53, in _runner
result[0] = await coro
File "/usr/local/lib/python3.9/site-packages/s3fs/core.py", line 888, in _exists
await self._info(path, bucket, key, version_id=version_id)
File "/usr/local/lib/python3.9/site-packages/s3fs/core.py", line 1140, in _info
out = await self._call_s3(
File "/usr/local/lib/python3.9/site-packages/s3fs/core.py", line 332, in _call_s3
return await _error_wrapper(
File "/usr/local/lib/python3.9/site-packages/s3fs/core.py", line 137, in _error_wrapper
raise err
PermissionError: Forbidden
```

But if the role also has read permission to the bucket, it works:
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Action": [
                "s3:GetObject*",
                "s3:GetBucket*",
                "s3:List*"
            ],
            "Resource": [
                "arn:aws:s3:::my-amazing-bucket",
                "arn:aws:s3:::my-amazing-bucket/*"
            ],
            "Effect": "Allow"
        },
        {
            "Action": [
                "s3:PutObject",
                "s3:PutObjectLegalHold",
                "s3:PutObjectRetention",
                "s3:PutObjectTagging",
                "s3:PutObjectVersionTagging",
                "s3:Abort*"
            ],
            "Resource": "arn:aws:s3:::my-amazing-bucket/*",
            "Effect": "Allow"
        }
    ]
}
```

**Anything else we need to know?**:
Writing a dataframe with pandas only requires write permission. (Comment the line `df = dd.from_pandas(df, npartitions=2)`)

**Environment**:

- Dask version: 2023.11.0
- Python version: Python 3.9.18
- Operating System: Linux - docker base image: `public.ecr.aws/docker/library/python:3.9-slim`
- Install method (conda, pip, source): pip

**Comment by fjetter** [comment]
This is expected behavior. Contrary to pandas, dask is almost always writing multiple files in a directory like structure and we'll need to check whether that directory exists or not. At least for non-remote file systems...

I haven't verified this but I believe this implementation is performing a simple HEAD request to the object path to get some metadata so you'll probably just need a [`GetObjectAttributes`](https://docs.aws.amazon.com/AmazonS3/latest/API/API_GetObjectAttributes.html) and not a full `GetObject` if that makes a difference to you. We're not actually reading any payload data here, just scouting the area.
