### ISSUE TITLE
2023.11.0: pytest 7.4.3 is failing with error while parsing the warning configuration

### ISSUE THREAD

**Issue by kloczek** [dask/dask#10649]
```console
+ /usr/bin/pytest -ra -q --pyargs dask
ERROR: while parsing the following warning configuration:

  ignore:.*:dask.tests.warning_aliases.RemovedIn20Warning

This error occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/_pytest/config/__init__.py", line 1761, in parse_warning_filter
    category: Type[Warning] = _resolve_warning_category(category_)
  File "/usr/lib/python3.8/site-packages/_pytest/config/__init__.py", line 1799, in _resolve_warning_category
    m = __import__(module, None, None, [klass])
  File "/home/tkloczko/rpmbuild/BUILDROOT/python-dask-2023.11.0-2.fc35.x86_64/usr/lib/python3.8/site-packages/dask/__init__.py", line 3, in <module>
    from dask import config, datasets
  File "/home/tkloczko/rpmbuild/BUILDROOT/python-dask-2023.11.0-2.fc35.x86_64/usr/lib/python3.8/site-packages/dask/config.py", line 17, in <module>
    from dask.typing import no_default
  File "/home/tkloczko/rpmbuild/BUILDROOT/python-dask-2023.11.0-2.fc35.x86_64/usr/lib/python3.8/site-packages/dask/typing.py", line 28, in <module>
    Key: TypeAlias = Union[str, bytes, int, float, tuple["Key", ...]]
TypeError: 'type' object is not subscriptable
```

**Comment by QuLogic** [comment]
Python 3.9 is required: https://github.com/dask/dask/blob/2023.11.0/pyproject.toml#L29
