### ISSUE TITLE
TypeError: float() argument must be a string or a real number, not 'csr_matrix'

### ISSUE THREAD

**Issue by erico-imgproj** [dask/dask#10999]
**Describe the issue**:
During a NLP task to generate a cluster of 6 Million documents with HDBSCAN, dask is not capable of executing the clustering task. It returns the message 
```python
TypeError: float() argument must be a string or a real number, not 'csr_matrix'
```
I tried to use the full dataset, but my server runs out of memory, so I used 

```python
X_per = da.from_array(X).persist()
```
to load the data and try to get some clusters out. The following example is based in part on the example given in 
[https://examples.dask.org/machine-learning/text-vectorization.html](url). The example provided works fine on my environment, but the clustering task is not working properly.

**Minimal Complete Verifiable Example**:

```python
import pandas as pd
fulldf=pd.DataFrame({"_id":{"0":"GSf83ngBH54tuwn8_T8k","1":"Gif83ngBH54tuwn8_T8k","2":"Hyf83ngBH54tuwn8_T8k","3":"Jyf83ngBH54tuwn8_T8k","4":"KSf83ngBH54tuwn8_T8k","5":"Nyf83ngBH54tuwn8_T8k","6":"OSf83ngBH54tuwn8_T8k","7":"Oyf83ngBH54tuwn8_T8k","8":"Pif83ngBH54tuwn8_T8k","9":"Pyf83ngBH54tuwn8_T8k","10":"RCf83ngBH54tuwn8_T8k","11":"Tyf83ngBH54tuwn8_T8k","12":"UCf83ngBH54tuwn8_T8k","13":"USf83ngBH54tuwn8_T8k","14":"Uyf83ngBH54tuwn8_T8k","15":"VCf83ngBH54tuwn8_T8k","16":"WCf83ngBH54tuwn8_T8k","17":"WSf83ngBH54tuwn8_T8k","18":"Wyf83ngBH54tuwn8_T8k","19":"YCf83ngBH54tuwn8_T8k"},"origphrase":{"0":"23 DOSAGE FORMS, COMPOSITION AND PACKAGING ..........................................","1":"24 PART II: SCIENTIFIC INFORMATION ..........................................................................","2":"38 REFERENCES ...........................................................................................................","3":"Oral Delayed","4":"Tablet \\/ 40 mg esomeprazole Crospovidone, hypromellose, hydroxypropyl cellulose, glyceryl monostearate, macrogol, magnesium stearate,","5":"reflux esophagitis  ","6":"Co-administration with rilprivirine is contraindicated.","7":"In the presence of any alarm symptom","8":"Pseudomembranous colitis has been reported with nearly all antibacterial agents, including clarithromycin and amoxicillin, and may range in severity from mild to life threatening.","9":"Therefore, it is important to consider this diagnosis in patients who present with diarrhea subsequent to the administration of antibacterial agents.","10":"In moderate to severe cases, consideration should be given to management with fluids and electrolytes, protein supplementation, and treatment with an antibacterial drug clinically effective against Clostridium difficile colitis.","11":"loading dose\\/75mg daily maintenance dose and esomeprazole 40 mg once daily resulting in decreased exposure to the active metabolite of clopidogrel by an average of 40%, and resulting in decreased maximum inhibition of ADP induced platelet aggregation by an average of 14%.","12":"Based on these data, concomitant use of esomeprazole and clopidogrel should be avoided see DRUG INTERACTIONS.","13":"Concomitant use of Proton Pump Inhibitors PPIs with Methotrexate:","14":"A temporary withdrawal of the PPI may be considered in some patients receiving treatments with high dose methotrexate see DRUG INTERACTIONS.","15":"Carcinogenesis and Mutagenesis Long-term toxicity studies of omeprazole, revealed the gastric mucosa as the target organ.","16":"No ECL-cell carcinoids were identified in the carcinogenicity study in mice or in long-term up to 7 years general toxicity studies in dogs.","17":"A vast number of studies have revealed that pronounced and sustained hypergastrinemia is the mechanism behind the development of the gastric ECL-cell carcinoids in the rat.","18":"Partial fundectomy in rats results in hypergastrinemia and gastric ECL-cell carcinoids in the remaining part of the fundic mucosa, towards the end of the rats\\u2019 life span.","19":"The effect of esomeprazole on serum gastrin concentrations was evaluated in approximately 2,700 patients in clinical trials up to 8 weeks and in over 1,300 patients for up to 6-12 months daily doses of either 20 or 40 mg."},"pm":{"0":59893,"1":59893,"2":59893,"3":59893,"4":59893,"5":59893,"6":59893,"7":59893,"8":59893,"9":59893,"10":59893,"11":59893,"12":59893,"13":59893,"14":59893,"15":59893,"16":59893,"17":59893,"18":59893,"19":59893}})
import dask
from dask_ml.feature_extraction.text import CountVectorizer
import dask.bag as db
import sparse
from sklearn.cluster import HDBSCAN
from sklearn.feature_extraction.text import HashingVectorizer

import dask.array as da
from dask_cuda import LocalCUDACluster
from dask.distributed import Client
import joblib
import sklearn.pipeline

fulldf.origphrase = fulldf.origphrase.astype(str)

cluster = LocalCUDACluster()
client = Client(cluster)
#vectorizer = CountVectorizer()
vectorizer = HashingVectorizer() #TfidfVectorizer(stop_words='english')
corpus = db.from_sequence(fulldf.origphrase , npartitions=500)
X = vectorizer.fit_transform(corpus)
X_per = da.from_array(X).persist()

clus = HDBSCAN(min_cluster_size=20)
with joblib.parallel_backend('dask'):
     yhat = clus.fit_predict( X_per ) #ERROR happens in this line

```

**Anything else we need to know?**:
The error seems related to the fact I pass a dask.array as parameter. 

```python-traceback
TypeError: float() argument must be a string or a real number, not 'csr_matrix'
The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "/home/erico/lab/packages_dask/sklearn/cluster/_hdbscan/hdbscan.py", line 921, in fit_predict
    self.fit(X)
  File "/home/erico/lab/packages_dask/sklearn/base.py", line 1474, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/home/erico/lab/packages_dask/sklearn/cluster/_hdbscan/hdbscan.py", line 721, in fit
    X = self._validate_data(
  File "/home/erico/lab/packages_dask/sklearn/base.py", line 633, in _validate_data
    out = check_array(X, input_name="X", **check_params)
  File "/home/erico/lab/packages_dask/sklearn/utils/validation.py", line 997, in check_array
    array = _asarray_with_order(array, order=order, dtype=dtype, xp=xp)
  File "/home/erico/lab/packages_dask/sklearn/utils/_array_api.py", line 521, in _asarray_with_order
    array = numpy.asarray(array, order=order, dtype=dtype)
ValueError: setting an array element with a sequence.
```

**Environment**:

- Dask version: '2024.1.1'
- Python version:  Python 3.10.13 (main, Oct  4 2023, 08:39:12) [GCC 8.3.0] on linux
- Operating System:``` Linux HRE-GPU-DRONE 5.15.64-1-pve #1 SMP PVE 5.15.64-1 (Thu, 13 Oct 2022 10:30:34 +0200) x86_64 GNU/Linux```
- Install method (conda, pip, source): pip

**Comment by erico-imgproj** [comment]
Some progress: By adding the `compute()` method in the line where there was the error, the system runs but now I get another error 
```python
yhat = clus.fit_predict( X_per.compute() )
```


```python-traceback
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "/home/erico/lab/packages_dask/sklearn/cluster/_hdbscan/hdbscan.py", line 921, in fit_predict
    self.fit(X)
  File "/home/erico/lab/packages_dask/sklearn/base.py", line 1474, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/home/erico/lab/packages_dask/sklearn/cluster/_hdbscan/hdbscan.py", line 865, in fit
    self._single_linkage_tree_ = mst_func(**kwargs)
  File "/home/erico/lab/packages_dask/sklearn/cluster/_hdbscan/hdbscan.py", line 245, in _hdbscan_brute
    distance_matrix = pairwise_distances(
  File "/home/erico/lab/packages_dask/sklearn/utils/_param_validation.py", line 213, in wrapper
    return func(*args, **kwargs)
  File "/home/erico/lab/packages_dask/sklearn/metrics/pairwise.py", line 2331, in pairwise_distances
    return _parallel_pairwise(X, Y, func, n_jobs, **kwds)
  File "/home/erico/lab/packages_dask/sklearn/metrics/pairwise.py", line 1875, in _parallel_pairwise
    ret = np.empty((X.shape[0], Y.shape[0]), dtype=dtype, order="F")
numpy.core._exceptions._ArrayMemoryError: Unable to allocate 285. TiB for an array with shape (6261516, 6261516) and data type float64
```

So the issue seems to be solved.
