### ISSUE TITLE
Dataframe constructed from single partition bag cannot be shuffled with query planning enabled

### ISSUE THREAD

**Issue by b-phi** [dask/dask#11002]
As best I can tell, this is only an issue when the bag has a single partition.

```python
import dask

dask.config.set({'dataframe.query-planning': True})

import dask.bag as db

if __name__ == '__main__':
    bag = db.from_sequence(['A', 'B', 'C'], npartitions=1)
    df = bag.to_dataframe(columns=['symbol'])
    symbols = sorted(df['symbol'].drop_duplicates().compute())
    df = df.set_index('symbol', divisions=symbols + [symbols[-1]])
    print(df.compute())
```

> Traceback (most recent call last):
  File ".../dev.py", line 12, in <module>
    print(df.compute())
  File "/usr/local/lib/python3.10/site-packages/dask_expr/_collection.py", line 452, in compute
    return DaskMethodsMixin.compute(out, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/dask/base.py", line 375, in compute
    (result,) = compute(self, traverse=False, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/dask/base.py", line 654, in compute
    dsk = collections_to_dsk(collections, optimize_graph, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/dask/base.py", line 426, in collections_to_dsk
    dsk, keys = _extract_graph_and_keys(val)
  File "/usr/local/lib/python3.10/site-packages/dask/base.py", line 452, in _extract_graph_and_keys
    graphs.append(v.__dask_graph__())
  File "/usr/local/lib/python3.10/site-packages/dask_expr/_collection.py", line 467, in __dask_graph__
    return out.__dask_graph__()
  File "/usr/local/lib/python3.10/site-packages/dask_expr/_core.py", line 485, in __dask_graph__
    layers.append(expr._layer())
  File "/usr/local/lib/python3.10/site-packages/dask_expr/_repartition.py", line 166, in _layer
    new_partitions_boundaries = self._partitions_boundaries
  File "/usr/local/lib/python3.10/functools.py", line 981, in __get__
    val = self.func(instance)
  File "/usr/local/lib/python3.10/site-packages/dask_expr/_repartition.py", line 154, in _partitions_boundaries
    assert npartitions_input > npartitions
AssertionError

**Environment**:

- Pandas version: 2.2.1
- Dask version: 2024.3.0
- Dask Expr version: 1.0.1
- Python version: 3.10.10
- Operating System: OSX
- Install method (conda, pip, source): pip

**Comment by phofl** [comment]
Ah sorry about that, we have a shortcut for dfs with 1 partition that didn't account for the divisions argument properly

put up a pr to fix

**Comment by b-phi** [comment]
Thanks @phofl, appreciate the quick turnaround on these!
