### ISSUE TITLE
Bug in map_blocks when iterating over multiple arrays

### ISSUE THREAD

**Issue by astrofrog** [dask/dask#11188]
**Describe the issue**:

When iterating over two arrays with map_blocks, I am running into an issue where each call to the function to process each chunk gets chunks with mismatching dimensions.

**Minimal Complete Verifiable Example**:

```python
from dask import array as da

array1 = da.zeros((100, 24)).rechunk((41, 24))
array2 = da.zeros((100,)).rechunk((41,))

def process_chunk(a, b):
    print(a.shape, b.shape)
    return a + b[:, None]

r = da.map_blocks(process_chunk, array1, array2)
r.compute()
```

This gives:

```
(0, 0) (0,)
(1, 1) (1,)
(18, 24) (18,)
(18, 24) (41,)
(18, 24) (41,)
(41, 24) (41,)
(41, 24) (18,)
Traceback (most recent call last):
(41, 24) (18,)
  File "/home/tom/Projects/parallel-modeling-examples/eis/minimal.py", line 11, in <module>
(41, 24) (41,)
(41, 24) (41,)
    r.compute()
(41, 24) (41,)
  File "/home/tom/python/dev/lib/python3.12/site-packages/dask/base.py", line 376, in compute
    (result,) = compute(self, traverse=False, **kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tom/python/dev/lib/python3.12/site-packages/dask/base.py", line 662, in compute
    results = schedule(dsk, keys, **kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tom/Projects/parallel-modeling-examples/eis/minimal.py", line 8, in process_chunk
    return a + b[:, None]
           ~~^~~~~~~~~~~~
ValueError: operands could not be broadcast together with shapes (18,24) (41,1) 
```

Normally there should only be three sets of chunks to iterate over - two with size 41 and one with size 18. However, it looks like more workers get called than this, and some of them have mismatching dimensions for a and be (41 for one and 18 for the other).

**Environment**:

- Dask version: 2024.6.0
- Python version: 3.12.4
- Operating System: Ubuntu
- Install method (conda, pip, source): pip

**Comment by phofl** [comment]
Thanks for your report. This basically follows the broadcasting rules of Numpy, i.e. we are broadasting to the second dimension:

```
arr = np.arange(0, 20).reshape(5, 4)
arr + np.arange(0, 4)

[[ 0  2  4  6]
 [ 4  6  8 10]
 [ 8 10 12 14]
 [12 14 16 18]
 [16 18 20 22]]

```

**Comment by phofl** [comment]
Closing this as expected behavior, it's also documented in the docstrign a little further down that we are aligning blocks along every dimension
