### ISSUE TITLE
More support for serialization & deserialization.

### ISSUE THREAD

**Issue by muazhari** [dask/dask#11215]
**Describe the issue**:
FastAPI is known to can't be pickled by default pickle and dill. 
Click [here](https://github.com/encode/starlette/discussions/2308) for the details.
However, Ray pickler can.

**Minimal Complete Verifiable Example**:

```python
import asyncio
import os

import dask
import httpx
from dask.distributed import Client
from distributed import LocalCluster
from fastapi import FastAPI

if __name__ == '__main__':
    cluster = LocalCluster(threads_per_worker=1)
    client = Client(cluster)
    print(client.scheduler_info())


    async def root():
        return {"message": "Hello World"}


    queue = dask.distributed.Queue()
    for i in range(os.cpu_count()):
        app = FastAPI()
        app.i = i
        app.add_api_route("/", root, methods=["GET"])
        queue.put(app)


    def task():
        v = queue.get()
        client = httpx.AsyncClient(app=v, base_url="http://run")
        response_future = client.get("/")
        response = asyncio.run(response_future)
        print(response.json())
        queue.put(v)
        return v

    def run_dask():
        futures = [client.submit(task) for i in range(5000)]
        for future in dask.distributed.as_completed(futures):
            val = future.result()
            print(val.i)

    run_dask()
```

**Anything else we need to know?**:
Error logs:
```python
/usr/bin/python3 /workspace/playground/two_test.py 
/usr/local/lib/python3.10/dist-packages/distributed/node.py:182: UserWarning: Port 8787 is already in use.
Perhaps you already have a cluster running?
Hosting the HTTP server on port 45089 instead
  warnings.warn(
1
{'type': 'Scheduler', 'id': 'Scheduler-09680619-0876-46a0-bc9c-98b24374eb6d', 'address': 'tcp://127.0.0.1:41949', 'services': {'dashboard': 45089}, 'started': 1720063868.7480896, 'workers': {'tcp://127.0.0.1:33055': {'type': 'Worker', 'id': 0, 'host': '127.0.0.1', 'resources': {}, 'local_directory': '/tmp/dask-scratch-space/worker-1xu525vd', 'name': 0, 'nthreads': 1, 'memory_limit': 16634433536, 'last_seen': 1720063869.8395233, 'services': {'dashboard': 39113}, 'metrics': {'task_counts': {}, 'bandwidth': {'total': 100000000, 'workers': {}, 'types': {}}, 'digests_total_since_heartbeat': {}, 'managed_bytes': 0, 'spilled_bytes': {'memory': 0, 'disk': 0}, 'transfer': {'incoming_bytes': 0, 'incoming_count': 0, 'incoming_count_total': 0, 'outgoing_bytes': 0, 'outgoing_count': 0, 'outgoing_count_total': 0}, 'event_loop_interval': 0.02, 'cpu': 0.0, 'memory': 117628928, 'time': 1720063869.6350815, 'host_net_io': {'read_bps': 27891.876894116896, 'write_bps': 27891.876894116896}, 'host_disk_io': {'read_bps': 0.0, 'write_bps': 0.0}, 'num_fds': 18, 'gpu-memory-total': 25757220864, 'gpu_utilization': 0, 'gpu_memory_used': 649797632}, 'status': 'running', 'nanny': 'tcp://127.0.0.1:43315'}}}
2024-07-04 03:31:10,117 - distributed.protocol.core - CRITICAL - Failed to deserialize
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/distributed/protocol/core.py", line 175, in loads
    return msgpack.loads(
  File "msgpack/_unpacker.pyx", line 194, in msgpack._cmsgpack.unpackb
  File "/usr/local/lib/python3.10/dist-packages/distributed/protocol/core.py", line 172, in _decode_default
    return pickle.loads(sub_header["pickled-obj"], buffers=sub_frames)
  File "/usr/local/lib/python3.10/dist-packages/distributed/protocol/pickle.py", line 96, in loads
    return pickle.loads(x)
  File "/usr/local/lib/python3.10/dist-packages/starlette/datastructures.py", line 699, in __getattr__
    return self._state[key]
  File "/usr/local/lib/python3.10/dist-packages/starlette/datastructures.py", line 699, in __getattr__
    return self._state[key]
  File "/usr/local/lib/python3.10/dist-packages/starlette/datastructures.py", line 699, in __getattr__
    return self._state[key]
  [Previous line repeated 977 more times]
RecursionError: maximum recursion depth exceeded
2024-07-04 03:31:10,119 - distributed.core - ERROR - Exception while reading from tcp://127.0.0.1:51526
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/distributed/core.py", line 900, in _handle_comm
    msg = await comm.read()
  File "/usr/local/lib/python3.10/dist-packages/distributed/comm/tcp.py", line 247, in read
    msg = await from_frames(
  File "/usr/local/lib/python3.10/dist-packages/distributed/comm/utils.py", line 78, in from_frames
    res = _from_frames()
  File "/usr/local/lib/python3.10/dist-packages/distributed/comm/utils.py", line 61, in _from_frames
    return protocol.loads(
  File "/usr/local/lib/python3.10/dist-packages/distributed/protocol/core.py", line 175, in loads
    return msgpack.loads(
  File "msgpack/_unpacker.pyx", line 194, in msgpack._cmsgpack.unpackb
  File "/usr/local/lib/python3.10/dist-packages/distributed/protocol/core.py", line 172, in _decode_default
    return pickle.loads(sub_header["pickled-obj"], buffers=sub_frames)
  File "/usr/local/lib/python3.10/dist-packages/distributed/protocol/pickle.py", line 96, in loads
    return pickle.loads(x)
  File "/usr/local/lib/python3.10/dist-packages/starlette/datastructures.py", line 699, in __getattr__
    return self._state[key]
  File "/usr/local/lib/python3.10/dist-packages/starlette/datastructures.py", line 699, in __getattr__
    return self._state[key]
  File "/usr/local/lib/python3.10/dist-packages/starlette/datastructures.py", line 699, in __getattr__
    return self._state[key]
  [Previous line repeated 977 more times]
RecursionError: maximum recursion depth exceeded
2024-07-04 03:31:10,134 - distributed.protocol.pickle - ERROR - Failed to serialize maximum recursion depth exceeded.
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/distributed/core.py", line 900, in _handle_comm
    msg = await comm.read()
  File "/usr/local/lib/python3.10/dist-packages/distributed/comm/tcp.py", line 247, in read
    msg = await from_frames(
  File "/usr/local/lib/python3.10/dist-packages/distributed/comm/utils.py", line 78, in from_frames
    res = _from_frames()
  File "/usr/local/lib/python3.10/dist-packages/distributed/comm/utils.py", line 61, in _from_frames
    return protocol.loads(
  File "/usr/local/lib/python3.10/dist-packages/distributed/protocol/core.py", line 175, in loads
    return msgpack.loads(
  File "msgpack/_unpacker.pyx", line 194, in msgpack._cmsgpack.unpackb
  File "/usr/local/lib/python3.10/dist-packages/distributed/protocol/core.py", line 172, in _decode_default
    return pickle.loads(sub_header["pickled-obj"], buffers=sub_frames)
  File "/usr/local/lib/python3.10/dist-packages/distributed/protocol/pickle.py", line 96, in loads
    return pickle.loads(x)
  File "/usr/local/lib/python3.10/dist-packages/starlette/datastructures.py", line 699, in __getattr__
    return self._state[key]
  File "/usr/local/lib/python3.10/dist-packages/starlette/datastructures.py", line 699, in __getattr__
    return self._state[key]
  File "/usr/local/lib/python3.10/dist-packages/starlette/datastructures.py", line 699, in __getattr__
    return self._state[key]
  [Previous line repeated 977 more times]
RecursionError: maximum recursion depth exceeded

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/distributed/protocol/pickle.py", line 63, in dumps
    result = pickle.dumps(x, **dump_kwargs)
RecursionError: maximum recursion depth exceeded while pickling an object

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/distributed/protocol/pickle.py", line 68, in dumps
    pickler.dump(x)
  File "/usr/local/lib/python3.10/dist-packages/distributed/protocol/pickle.py", line 24, in reducer_override
    if _always_use_pickle_for(obj):
RecursionError: maximum recursion depth exceeded

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/cloudpickle/cloudpickle.py", line 1245, in dump
    return super().dump(obj)
  File "/usr/lib/python3.10/collections/__init__.py", line 986, in __getitem__
    return self.__missing__(key)            # support subclasses that define __missing__
  File "/usr/lib/python3.10/collections/__init__.py", line 978, in __missing__
    raise KeyError(key)
RecursionError: maximum recursion depth exceeded while calling a Python object

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/distributed/protocol/pickle.py", line 81, in dumps
    result = cloudpickle.dumps(x, **dump_kwargs)
  File "/usr/local/lib/python3.10/dist-packages/cloudpickle/cloudpickle.py", line 1479, in dumps
    cp.dump(obj)
  File "/usr/local/lib/python3.10/dist-packages/cloudpickle/cloudpickle.py", line 1249, in dump
    raise pickle.PicklingError(msg) from e
_pickle.PicklingError: Could not pickle object as excessively deep recursion required.
2024-07-04 03:31:10,147 - distributed.protocol.pickle - ERROR - Failed to serialize <traceback object at 0x7f941009f600>.
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/distributed/core.py", line 900, in _handle_comm
    msg = await comm.read()
  File "/usr/local/lib/python3.10/dist-packages/distributed/comm/tcp.py", line 247, in read
    msg = await from_frames(
  File "/usr/local/lib/python3.10/dist-packages/distributed/comm/utils.py", line 78, in from_frames
    res = _from_frames()
  File "/usr/local/lib/python3.10/dist-packages/distributed/comm/utils.py", line 61, in _from_frames
    return protocol.loads(
  File "/usr/local/lib/python3.10/dist-packages/distributed/protocol/core.py", line 175, in loads
    return msgpack.loads(
  File "msgpack/_unpacker.pyx", line 194, in msgpack._cmsgpack.unpackb
  File "/usr/local/lib/python3.10/dist-packages/distributed/protocol/core.py", line 172, in _decode_default
    return pickle.loads(sub_header["pickled-obj"], buffers=sub_frames)
  File "/usr/local/lib/python3.10/dist-packages/distributed/protocol/pickle.py", line 96, in loads
    return pickle.loads(x)
  File "/usr/local/lib/python3.10/dist-packages/starlette/datastructures.py", line 699, in __getattr__
    return self._state[key]
  File "/usr/local/lib/python3.10/dist-packages/starlette/datastructures.py", line 699, in __getattr__
    return self._state[key]
  File "/usr/local/lib/python3.10/dist-packages/starlette/datastructures.py", line 699, in __getattr__
    return self._state[key]
  [Previous line repeated 977 more times]
RecursionError: maximum recursion depth exceeded

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/distributed/protocol/pickle.py", line 63, in dumps
    result = pickle.dumps(x, **dump_kwargs)
RecursionError: maximum recursion depth exceeded while pickling an object

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/distributed/protocol/pickle.py", line 68, in dumps
    pickler.dump(x)
  File "/usr/local/lib/python3.10/dist-packages/distributed/protocol/pickle.py", line 27, in reducer_override
    serialize = dask_serialize.dispatch(type(obj))
  File "/usr/local/lib/python3.10/dist-packages/dask/utils.py", line 766, in dispatch
    raise TypeError(f"No dispatch for {cls}")
RecursionError: maximum recursion depth exceeded while getting the str of an object

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/cloudpickle/cloudpickle.py", line 1245, in dump
    return super().dump(obj)
  File "/usr/local/lib/python3.10/dist-packages/cloudpickle/cloudpickle.py", line 1323, in reducer_override
    is_anyclass = issubclass(t, type)
RecursionError: maximum recursion depth exceeded while calling a Python object

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/distributed/protocol/pickle.py", line 81, in dumps
    result = cloudpickle.dumps(x, **dump_kwargs)
  File "/usr/local/lib/python3.10/dist-packages/cloudpickle/cloudpickle.py", line 1479, in dumps
    cp.dump(obj)
  File "/usr/local/lib/python3.10/dist-packages/cloudpickle/cloudpickle.py", line 1249, in dump
    raise pickle.PicklingError(msg) from e
_pickle.PicklingError: Could not pickle object as excessively deep recursion required.
Traceback (most recent call last):
  File "/workspace/playground/two_test.py", line 32, in <module>
    queue.put(app)
  File "/usr/local/lib/python3.10/dist-packages/distributed/queues.py", line 236, in put
    return self.client.sync(self._put, value, timeout=timeout, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/distributed/utils.py", line 358, in sync
    return sync(
  File "/usr/local/lib/python3.10/dist-packages/distributed/utils.py", line 434, in sync
    raise error
  File "/usr/local/lib/python3.10/dist-packages/distributed/utils.py", line 408, in f
    result = yield future
  File "/usr/local/lib/python3.10/dist-packages/tornado/gen.py", line 766, in run
    value = future.result()
  File "/usr/local/lib/python3.10/dist-packages/distributed/queues.py", line 220, in _put
    await self.client.scheduler.queue_put(
  File "/usr/local/lib/python3.10/dist-packages/distributed/core.py", line 1395, in send_recv_from_rpc
    return await send_recv(comm=comm, op=key, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/distributed/core.py", line 1177, in send_recv
    _, exc, tb = clean_exception(**response)
  File "/usr/local/lib/python3.10/dist-packages/distributed/core.py", line 1862, in clean_exception
    assert isinstance(traceback, types.TracebackType) or traceback is None
AssertionError

Process finished with exit code 1
```

**Environment**:

- Dask version: 2024.5.1
- Python version: 3.10.12
- Operating System: windows 11
- Install method (conda, pip, source): pip

**Comment by fjetter** [comment]
> Contradictly, dask supports alternative pickler based on [this](https://distributed.dask.org/en/latest/serialization.html).
Why it doesn't fall back to other methods?

Dask tries pickle and cloudpickle and if both fails it requires the user to define how to (de-)serialize an object. This is outlined on the link you are pointing to https://distributed.dask.org/en/latest/serialization.html, see specifically https://distributed.dask.org/en/latest/serialization.html#id3

**Comment by muazhari** [comment]
> > Contradictly, dask supports alternative pickler based on [this](https://distributed.dask.org/en/latest/serialization.html).
> > Why it doesn't fall back to other methods?
> 
> Dask tries pickle and cloudpickle and if both fails it requires the user to define how to (de-)serialize an object. This is outlined on the link you are pointing to https://distributed.dask.org/en/latest/serialization.html, see specifically https://distributed.dask.org/en/latest/serialization.html#id3

Can you support more/all object types to be serialized/deserialized in default setting? If the ray library can do that, you can too.

**Comment by fjetter** [comment]
> Can you support more/all object types to be serialized/deserialized in the default setting?

Well, _all_ is not possible since libraries can actually opt-out of pickle and in those cases we'll have to implement custom code. We're certainly happy to add serializers for commonly used libraries. fastapi is certainly popular enough for us to accept a serializer for. We have plenty of third party libraries supported this way, see https://github.com/dask/distributed/blob/main/distributed/protocol/__init__.py (register_lazy registers this thing if the lib is importable)

The only way Ray is able to support this is because they are also implementing an "addon", see https://github.com/ray-project/ray/blob/master/python/ray/util/serialization_addons.py

Are you interested in contributing a patch?
