### ISSUE TITLE
Dask indexing problem with cupy

### ISSUE THREAD

**Issue by miguelcarcamov** [dask/dask#11266]
Hi, I want to index an array and then set those values to something.

So, this is the example that DOES NOT work.

**Minimal Complete Verifiable Example**:

```python
import dask.array as da
import dask

dask.config.set({"array.backend": "cupy"})

data = da.random.random((20000,3))
condition = data[:,0] > 0.5
idx = da.flatnonzero(condition).compute()
vis[idx] *= -1

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/miguel/.conda/envs/pyralysis-env/lib/python3.12/site-packages/dask/array/core.py", line 1926, in __setitem__
    dsk = setitem_array(out, self, key, value)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/miguel/.conda/envs/pyralysis-env/lib/python3.12/site-packages/dask/array/slicing.py", line 1843, in setitem_array
    raise ValueError(
ValueError: could not broadcast input array from shape(9961, 3) into shape (3,)
```

**Anything else we need to know?**:
The example above works with `numpy` as backend, works with ´numpy´ and ´cupy´.

**Environment**:

- Dask version: dask==2024.6.0
- Python version: Python 3.12.4
- Operating System: Manjaro Linux x86_64
- Install method (conda, pip, source): conda environment, package installed via pip

**Comment by quasiben** [comment]
Hmm, in the example above, `vis` is not defined.  If I replace `vis` with `data` I do get the error you posted above.  I'm not sure what's going on yet.  When @rjzamora returns from PTO maybe he has an idea.  I'll spend some time investigating and see I can figure out what's going on

**Comment by miguelcarcamov** [comment]
> Hmm, in the example above, `vis` is not defined. If I replace `vis` with `data` I do get the error you posted above. I'm not sure what's going on yet. When @rjzamora returns from PTO maybe he has an idea. I'll spend some time investigating and see I can figure out what's going on

Yep, sorry I have fixed the example above so users can reproduce the error. Thank you for investigating the issue :)

**Comment by rjzamora** [comment]
As far as I can tell, [setitem_array](https://github.com/dask/dask/blob/67b2852d5f48d46527e3ac9c78122b483aef4057/dask/array/slicing.py#L1415) (used to build the graph for the `data[idx] *= -1` assignment) uses some code that isn't compatible with `cupy`. For example, [there is a `np.ndarray` instance check instead of a `is_arraylike`](https://github.com/dask/dask/blob/67b2852d5f48d46527e3ac9c78122b483aef4057/dask/array/slicing.py#L1340).

There also seems to be **very** recent code that uses numpy explicitly in a way that will not work when the underlying data is cupy (for example https://github.com/dask/dask/pull/11267 and https://github.com/dask/dask/pull/11291 will further break your example). cc @phofl (just for awareness - not because you have any responsibility to fix anything)

I'll try to find a way to address the functionality described in this issue, but it does look like there are a large number of other legitimate dask-array failures in gpuCI at the moment as well...

**Comment by miguelcarcamov** [comment]
@rjzamora thank you for the answer, now the bug is more clear to me, let me know once there is some fixes on this please :)

**Comment by rjzamora** [comment]
> let me know once there is some fixes on this please

Thanks for the bump @miguelcarcamov - I'm hopeful that https://github.com/dask/dask/pull/11421 will resolve this issue.
