### ISSUE TITLE
Parquet read with `filesystem="arrow"` fails when `distributed` isn't imported first

### ISSUE THREAD

**Issue by rjzamora** [dask/dask#11352]
**Describe the issue**:

While experimenting with `dd.read_parquet(..., filesystem="arrow")`, I noticed that I get a strange error whenever `distributed` hasn't been imported beforehand. I'm not sure what is going on, or how long this has been the case.

**Minimal Complete Verifiable Example**:

```python
import pandas as pd
pd.DataFrame({"a": range(10)}).to_parquet("test.parquet")

# import distributed
import dask.dataframe as dd
df = dd.read_parquet("/home/nfs/rzamora/workspace/cudf-24.10-v2/test.parquet", filesystem="arrow")
df.compute()
```
**Error**:
```
...

File [/.../dask/config.py:615](/.../dask/config.py#line=614), in get(key, default, config, override_with)
    613 k = canonical_name(k, result)
    614 try:
--> 615     result = result[k]
    616 except (TypeError, IndexError, KeyError):
    617     if default is no_default:

KeyError: 'distributed'
```
Note that there is no error when the `import distributed` line is uncommented.

**Comment by jrbourbeau** [comment]
Thanks @rjzamora. I'm able to reproduce -- this is certainly a weird one. 

If I add these prints to the `get_scheduler` call where this config option is being raised

```diff
diff --git a/dask/base.py b/dask/base.py
index 25b8b0c20..b3e9703fb 100644
--- a/dask/base.py
+++ b/dask/base.py
@@ -1574,6 +1574,11 @@ def get_scheduler(get=None, scheduler=None, collections=None, cls=None):

     try:
         from distributed import get_client
+        import dask
+        import sys
+
+        print(f"\n\n{sys.modules['distributed'] = }")
+        print(f"{dask.config.get('distributed') = }\n\n")

         return get_client().get
     except (ImportError, ValueError):
```

I get this output:

```


sys.modules['distributed'] = <module 'distributed' from '/Users/james/mambaforge/envs/dask-py311/lib/python3.11/site-packages/distributed/__init__.py'>
dask.config.get('distributed') = {'diagnostics': {'computations': {'nframes': 0, 'max-history': 100, 'ignore-modules': ['asyncio', 'functools', 'threading', 'datashader', 'dask', 'debugpy', 'distributed', 'coiled', 'cudf', 'cuml', 'matplotlib', 'pluggy', 'prefect', 'rechunker', 'xarray', 'xgboost', 'xdist'], 'ignore-files': ['runpy\\.py', 'pytest', 'py\\.test', 'pytest-script\\.py', '_pytest', 'pycharm', 'vscode_pytest', 'get_output_via_markers\\.py']}, 'nvml': True, 'cudf': False, 'erred-tasks': {'max-history': 100}}, 'version': 2, 'scheduler': {'allowed-failures': 3, 'bandwidth': 100000000, 'blocked-handlers': [], 'contact-address': None, 'default-data-size': '1kiB', 'events-cleanup-delay': '1h', 'idle-timeout': None, 'no-workers-timeout': None, 'work-stealing': True, 'work-stealing-interval': '100ms', 'worker-saturation': 1.1, 'worker-ttl': '5 minutes', 'preload': [], 'preload-argv': [], 'unknown-task-duration': '500ms', 'default-task-durations': {'rechunk-split': '1us', 'split-shuffle': '1us', 'split-taskshuffle': '1us', 'split-stage': '1us'}, 'validate': False, 'dashboard': {'status': {'task-stream-length': 1000}, 'tasks': {'task-stream-length': 100000}, 'tls': {'ca-file': None, 'key': None, 'cert': None}, 'bokeh-application': {'allow_websocket_origin': ['*'], 'keep_alive_milliseconds': 500, 'check_unused_sessions_milliseconds': 500}}, 'locks': {'lease-validation-interval': '10s', 'lease-timeout': '30s'}, 'http': {'routes': ['distributed.http.scheduler.prometheus', 'distributed.http.scheduler.info', 'distributed.http.scheduler.json', 'distributed.http.health', 'distributed.http.proxy', 'distributed.http.statics']}, 'allowed-imports': ['dask', 'distributed'], 'active-memory-manager': {'start': True, 'interval': '2s', 'measure': 'optimistic', 'policies': [{'class': 'distributed.active_memory_manager.ReduceReplicas'}]}}, 'worker': {'blocked-handlers': [], 'multiprocessing-method': 'spawn', 'use-file-locking': True, 'transfer': {'message-bytes-limit': '50MB'}, 'connections': {'outgoing': 50, 'incoming': 10}, 'preload': [], 'preload-argv': [], 'daemon': True, 'validate': False, 'resources': {}, 'lifetime': {'duration': None, 'stagger': '0 seconds', 'restart': False}, 'profile': {'enabled': True, 'interval': '10ms', 'cycle': '1000ms', 'low-level': False}, 'memory': {'recent-to-old-time': '30s', 'rebalance': {'measure': 'optimistic', 'sender-min': 0.3, 'recipient-max': 0.6, 'sender-recipient-gap': 0.1}, 'transfer': 0.1, 'target': 0.6, 'spill': 0.7, 'pause': 0.8, 'terminate': 0.95, 'max-spill': False, 'spill-compression': 'auto', 'monitor-interval': '100ms'}, 'http': {'routes': ['distributed.http.worker.prometheus', 'distributed.http.health', 'distributed.http.statics']}}, 'nanny': {'preload': [], 'preload-argv': [], 'environ': {}, 'pre-spawn-environ': {'MALLOC_TRIM_THRESHOLD_': 65536, 'OMP_NUM_THREADS': 1, 'MKL_NUM_THREADS': 1, 'OPENBLAS_NUM_THREADS': 1}}, 'client': {'heartbeat': '5s', 'scheduler-info-interval': '2s', 'security-loader': None, 'preload': [], 'preload-argv': []}, 'deploy': {'lost-worker-timeout': '15s', 'cluster-repr-interval': '500ms'}, 'adaptive': {'interval': '1s', 'target-duration': '5s', 'minimum': 0, 'maximum': inf, 'wait-count': 3}, 'comm': {'retry': {'count': 0, 'delay': {'min': '1s', 'max': '20s'}}, 'compression': False, 'shard': '64MiB', 'offload': '10MiB', 'default-scheme': 'tcp', 'socket-backlog': 2048, 'ucx': {'cuda-copy': None, 'tcp': None, 'nvlink': None, 'infiniband': None, 'rdmacm': None, 'create-cuda-context': None, 'environment': {}}, 'zstd': {'level': 3, 'threads': 0}, 'timeouts': {'connect': '30s', 'tcp': '30s'}, 'require-encryption': None, 'tls': {'ciphers': None, 'min-version': 1.2, 'max-version': None, 'ca-file': None, 'scheduler': {'cert': None, 'key': None}, 'worker': {'key': None, 'cert': None}, 'client': {'key': None, 'cert': None}}, 'websockets': {'shard': '8MiB'}}, 'p2p': {'comm': {'retry': {'count': 10, 'delay': {'min': '1s', 'max': '30s'}}}, 'disk': True}, 'dashboard': {'link': '{scheme}://{host}:{port}/status', 'export-tool': False, 'graph-max-items': 5000, 'prometheus': {'namespace': 'dask'}}, 'admin': {'large-graph-warning-threshold': '10MB', 'tick': {'interval': '20ms', 'limit': '3s', 'cycle': '1s'}, 'max-error-length': 10000, 'log-length': 10000, 'log-format': '%(asctime)s - %(name)s - %(levelname)s - %(message)s', 'low-level-log-length': 1000, 'pdb-on-err': False, 'system-monitor': {'interval': '500ms', 'log-length': 7200, 'disk': True, 'host-cpu': False, 'gil': {'enabled': True, 'interval': '1ms'}}, 'event-loop': 'tornado'}, 'rmm': {'pool-size': None}}




sys.modules['distributed'] = <module 'distributed' from '/Users/james/mambaforge/envs/dask-py311/lib/python3.11/site-packages/distributed/__init__.py'>
Traceback (most recent call last):
  File "/Users/james/projects/dask/dask/test.py", line 12, in <module>
    print(df.compute())
          ^^^^^^^^^^^^
  File "/Users/james/projects/dask/dask-expr/dask_expr/_collection.py", line 477, in compute
    return DaskMethodsMixin.compute(out, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/james/projects/dask/dask/dask/base.py", line 376, in compute
    (result,) = compute(self, traverse=False, **kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/james/projects/dask/dask/dask/base.py", line 649, in compute
    schedule = get_scheduler(
               ^^^^^^^^^^^^^^
  File "/Users/james/projects/dask/dask/dask/base.py", line 1581, in get_scheduler
    print(f"{dask.config.get('distributed') = }\n\n")
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/james/projects/dask/dask/dask/config.py", line 615, in get
    result = result[k]
             ~~~~~~^^^
KeyError: 'distributed'
```

Which means that early on the `distributed` config is properly loaded but then when we go to do this computation, the config has be altered such that we don't have the right distributed config anymore.

**Comment by 64dB0y** [comment]
to fix your trouble check this fix, i see it in another issue,
https://github.com/Jostino/RimWorld-it/releases/tag/fix
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by mrocklin** [comment]
There was a comment on this thread that I assumed was an attempt at spreading malware.  I've reported and blocked the user.
