### ISSUE TITLE
Error with read_csv using dask.dataframe

### ISSUE THREAD

**Issue by koverholt** [dask/dask#1166]
I get an error when using `dd.read_csv` using Dask 0.9.0. This works with Dask 0.8.2 and pandas 0.18.1. Steps to reproduce are below:

Download a sample CSV file from the GDELT dataset:

```
$ wget https://s3.amazonaws.com/blaze-data/gdelt/csv/20140101.export.csv
```

Perform an operation with Dask.Dataframe:

```
>>> import dask.dataframe as dd
>>> df = dd.read_csv('20140101.export.csv', sep='\t', header=None)
>>> df.head()

ValueError                                Traceback (most recent call last)
<ipython-input-3-2569c44faf66> in <module>()
----> 1 df.head()

/Users/koverholt/anaconda3/lib/python3.5/site-packages/dask/dataframe/core.py in head(self, n, compute)
    369 
    370         if compute:
--> 371             result = result.compute()
    372         return result
    373 

/Users/koverholt/anaconda3/lib/python3.5/site-packages/dask/base.py in compute(self, **kwargs)
     35 
     36     def compute(self, **kwargs):
---> 37         return compute(self, **kwargs)[0]
     38 
     39     @classmethod

/Users/koverholt/anaconda3/lib/python3.5/site-packages/dask/base.py in compute(*args, **kwargs)
    108                 for opt, val in groups.items()])
    109     keys = [var._keys() for var in variables]
--> 110     results = get(dsk, keys, **kwargs)
    111 
    112     results_iter = iter(results)

/Users/koverholt/anaconda3/lib/python3.5/site-packages/dask/threaded.py in get(dsk, result, cache, num_workers, **kwargs)
     55     results = get_async(pool.apply_async, len(pool._pool), dsk, result,
     56                         cache=cache, queue=queue, get_id=_thread_get_id,
---> 57                         **kwargs)
     58 
     59     return results

/Users/koverholt/anaconda3/lib/python3.5/site-packages/dask/async.py in get_async(apply_async, num_workers, dsk, result, cache, queue, get_id, raise_on_exception, rerun_exceptions_locally, callbacks, **kwargs)
    486                 _execute_task(task, data)  # Re-execute locally
    487             else:
--> 488                 raise(remote_exception(res, tb))
    489         state['cache'][key] = res
    490         finish_task(dsk, key, state, results, keyorder.get)

ValueError: could not convert string to float: 'HRW'

Traceback
---------
  File "/Users/koverholt/anaconda3/lib/python3.5/site-packages/dask/async.py", line 267, in execute_task
    result = _execute_task(task, data)
  File "/Users/koverholt/anaconda3/lib/python3.5/site-packages/dask/async.py", line 249, in _execute_task
    return func(*args2)
  File "/Users/koverholt/anaconda3/lib/python3.5/site-packages/dask/dataframe/csv.py", line 43, in bytes_read_csv
    coerce_dtypes(df, dtypes)
  File "/Users/koverholt/anaconda3/lib/python3.5/site-packages/dask/dataframe/csv.py", line 67, in coerce_dtypes
    df[c] = df[c].astype(dtypes[c])
  File "/Users/koverholt/anaconda3/lib/python3.5/site-packages/pandas/core/generic.py", line 2950, in astype
    raise_on_error=raise_on_error, **kwargs)
  File "/Users/koverholt/anaconda3/lib/python3.5/site-packages/pandas/core/internals.py", line 2938, in astype
    return self.apply('astype', dtype=dtype, **kwargs)
  File "/Users/koverholt/anaconda3/lib/python3.5/site-packages/pandas/core/internals.py", line 2890, in apply
    applied = getattr(b, f)(**kwargs)
  File "/Users/koverholt/anaconda3/lib/python3.5/site-packages/pandas/core/internals.py", line 434, in astype
    values=values, **kwargs)
  File "/Users/koverholt/anaconda3/lib/python3.5/site-packages/pandas/core/internals.py", line 477, in _astype
    values = com._astype_nansafe(values.ravel(), dtype, copy=True)
  File "/Users/koverholt/anaconda3/lib/python3.5/site-packages/pandas/core/common.py", line 1920, in _astype_nansafe
    return arr.astype(dtype)
```

**Comment by mrocklin** [comment]
Can you try with https://github.com/dask/dask/pull/1164

**Comment by koverholt** [comment]
Tried with #1164, same error/issue.

**Comment by mrocklin** [comment]
From the first 10kB it guessed dtypes.  In all of these rows there were only empty values for certain columns (8, 9, 10, ...) and Pandas apparently defaults to `float` in this case.  Well beyond this first sample of the data we find that there was actually text data in these columns, not floats, causing the error that you're seeing here.  We can resolve this by reading in more data with pandas and using that to inform the dtypes.

```python
In [1]: import pandas as pd

In [2]: df = pd.read_csv('20140101.export.csv', sep='\t', header=None, nrows=10000)

In [3]: dt = df.dtypes.to_dict()

In [4]: import dask.dataframe as dd

In [5]: df = dd.read_csv('20140101.export.csv', sep='\t', header=None, dtype=dt)

In [6]: df.head()
Out[6]: 
          0         1       2     3         4    5          6    7    8    9   \
0  281451675  20040104  200401  2004  2004.011  NaN        NaN  NaN  NaN  NaN   
1  281451676  20040104  200401  2004  2004.011  IDN  INDONESIA  IDN  NaN  NaN   
2  281451677  20040104  200401  2004  2004.011  IDN  INDONESIA  IDN  NaN  NaN   
3  281451678  20040104  200401  2004  2004.011  IDN  INDONESIA  IDN  NaN  NaN   
4  281451679  20040104  200401  2004  2004.011  IDN  INDONESIA  IDN  NaN  NaN   

                         ...                                48 49  \
0                        ...                                GM  1   
1                        ...                               NaN  4   
2                        ...                               NaN  4   
3                        ...                          10205777  4   
4                        ...                                AS  4   

                                 50  51    52        53       54        55  \
0                           Germany  GM    GM  51.00000    9.000        GM   
1  Jakarta, Jakarta Raya, Indonesia  ID  ID04  -6.17444  106.829  -2679652   
2       Bali, Jawa Timur, Indonesia  ID  ID08  -7.10460  112.337  10205777   
3  Jakarta, Jakarta Raya, Indonesia  ID  ID04  -6.17444  106.829  -2679652   
4  Jakarta, Jakarta Raya, Indonesia  ID  ID04  -6.17444  106.829  -2679652   

         56                                                 57  
0  20140101  http://www.bankinfosecurity.com/nsa-reacts-to-...  
1  20140101  http://www.gulf-times.com/asean-philippines/18...  
2  20140101  http://www.themalaymailonline.com/world/articl...  
3  20140101  http://www.skynews.com.au/world/article.aspx?i...  
4  20140101  http://www.skynews.com.au/world/article.aspx?i...  

[5 rows x 58 columns]

In [7]: len(df)
Out[7]: 73336
```

**Comment by mrocklin** [comment]
I'm not sure how to solve this problem generally.

We could increase the default sample size to read when determining initial dtypes.  We could also improve error messages.

**Comment by koverholt** [comment]
Thanks for the detailed info. Now I see the `sample=` argument in `dd.read_csv`, and I'm happy with using that to set the sample size.

**Comment by jcrist** [comment]
I believe this has been resolved (through both code and doc improvements). Closing.

**Comment by Umersaeed81** [comment]
cell = dd.read_csv('*.csv',\
                   skiprows=[0,1,2,3,4,5],\
                   skipfooter=1,
                    engine='python',\
                    na_values=['NIL','/0'],
                    parse_dates=["Date"],assume_missing=True)
