### ISSUE TITLE
Handle fixed format hdf tables with dataframe

### ISSUE THREAD

**Issue by mrocklin** [dask/dask#1167]
There is a lot of complexity around HDF5 flavors used with Pandas. In particular "fixed" format hdf5 files are somewhat opaque and can not be cut easily.  Dask.dataframe currently chokes on these.  

We should do one of the following:

1.  Raise informative error messages
2.  Accept them as single-partition dask.dataframes
3.  Accept them in glob strings as multi-partition dask.dataframes

cc pvanderlinden

**Comment by pvanderlinden** [comment]
When you try to read from hdf5 but use a missing key, you get the following message:
```
>>> dd.read_hdf('random.h5', 'qwe')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/paul/.virtualenvs/parrallel/lib/python3.4/site-packages/dask/dataframe/io.py", line 561, in read_hdf
    for path in paths])
  File "/home/paul/.virtualenvs/parrallel/lib/python3.4/site-packages/dask/dataframe/io.py", line 561, in <listcomp>
    for path in paths])
  File "/home/paul/.virtualenvs/parrallel/lib/python3.4/site-packages/dask/dataframe/io.py", line 501, in _read_single_hdf
    for k, s in zip(keys, stops)])
  File "/home/paul/.virtualenvs/parrallel/lib/python3.4/site-packages/dask/dataframe/multi.py", line 511, in concat
    raise ValueError('Input must be a list longer than 0')
ValueError: Input must be a list longer than 0
```

**Comment by pvanderlinden** [comment]
When you try to read hdf5 created by pytables, but dask can't read for example because it has compression on a table, you get the following error:

```
>>> dd.read_hdf('random.h5', 'quote')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/paul/.virtualenvs/parrallel/lib/python3.4/site-packages/dask/dataframe/io.py", line 561, in read_hdf
    for path in paths])
  File "/home/paul/.virtualenvs/parrallel/lib/python3.4/site-packages/dask/dataframe/io.py", line 561, in <listcomp>
    for path in paths])
  File "/home/paul/.virtualenvs/parrallel/lib/python3.4/site-packages/dask/dataframe/io.py", line 501, in _read_single_hdf
    for k, s in zip(keys, stops)])
  File "/home/paul/.virtualenvs/parrallel/lib/python3.4/site-packages/dask/dataframe/io.py", line 501, in <listcomp>
    for k, s in zip(keys, stops)])
  File "/home/paul/.virtualenvs/parrallel/lib/python3.4/site-packages/dask/dataframe/io.py", line 476, in one_path_one_key
    empty = pd.read_hdf(path, key, stop=0)
  File "/home/paul/.virtualenvs/parrallel/lib/python3.4/site-packages/pandas/io/pytables.py", line 330, in read_hdf
    return store.select(key, auto_close=auto_close, **kwargs)
  File "/home/paul/.virtualenvs/parrallel/lib/python3.4/site-packages/pandas/io/pytables.py", line 680, in select
    return it.get_result()
  File "/home/paul/.virtualenvs/parrallel/lib/python3.4/site-packages/pandas/io/pytables.py", line 1364, in get_result
    results = self.func(self.start, self.stop, where)
  File "/home/paul/.virtualenvs/parrallel/lib/python3.4/site-packages/pandas/io/pytables.py", line 673, in func
    columns=columns, **kwargs)
  File "/home/paul/.virtualenvs/parrallel/lib/python3.4/site-packages/pandas/io/pytables.py", line 4054, in read
    mgr = BlockManager([block], [cols_, index_])
  File "/home/paul/.virtualenvs/parrallel/lib/python3.4/site-packages/pandas/core/internals.py", line 2594, in __init__
    self._verify_integrity()
  File "/home/paul/.virtualenvs/parrallel/lib/python3.4/site-packages/pandas/core/internals.py", line 2804, in _verify_integrity
    construction_error(tot_items, block.shape[1:], self.axes)
  File "/home/paul/.virtualenvs/parrallel/lib/python3.4/site-packages/pandas/core/internals.py", line 3968, in construction_error
    raise ValueError("Empty data passed with indices specified.")
ValueError: Empty data passed with indices specified.
```

**Comment by pvanderlinden** [comment]
I will add more info if I find more cases. I can also isolate the code on how to make these hdf5 files, of that is helpful?

**Comment by mrocklin** [comment]
An code example creating the file referred to in the second comment would
be quite helpful, yes.

**Comment by nirizr** [comment]
For anyone coming across this: supporting fixed format is now somewhat easier by writing partitions to different hdf5 datasets or files.
It is now possible save each partition to a different fixed dataset, and we could allow reading those.

It's mostly a question of user demand now, I think.
