### ISSUE TITLE
dask.DataFrame.read_csv: ValueError: Cannot convert NA to integer

### ISSUE THREAD

**Issue by bkomboz** [dask/dask#1262]
I have the following snippet to read a csv with dask.  

    import dask.dataframe as dd
    df = dd.read_csv('/path/to/data.csv', sep = ';', header = 0, encoding = 'utf-8')
    df.head(5)

The error I get:

    ---------------------------------------------------------------------------
    ValueError                                Traceback (most recent call last)
    <ipython-input-12-919f0aa6a2cb> in <module>()
          1 import dask.dataframe as dd
          2 df = dd.read_csv('/path/to/data.csv', sep = ';', header = 0, encoding = 'utf-8')
    ----> 3 df.head(5)
    
    /home/vkcem4m/software/anaconda/lib/python2.7/site-packages/dask/dataframe/core.pyc in head(self, n, compute)
        369 
        370         if compute:
    --> 371             result = result.compute()
        372         return result
        373 
    
    /home/vkcem4m/software/anaconda/lib/python2.7/site-packages/dask/base.pyc in compute(self, **kwargs)
         35 
         36     def compute(self, **kwargs):
    ---> 37         return compute(self, **kwargs)[0]
         38 
         39     @classmethod
    
    /home/vkcem4m/software/anaconda/lib/python2.7/site-packages/dask/base.pyc in compute(*args, **kwargs)
        108                 for opt, val in groups.items()])
        109     keys = [var._keys() for var in variables]
    --> 110     results = get(dsk, keys, **kwargs)
        111 
        112     results_iter = iter(results)
    
    /home/vkcem4m/software/anaconda/lib/python2.7/site-packages/dask/threaded.pyc in get(dsk, result, cache, num_workers, **kwargs)
         55     results = get_async(pool.apply_async, len(pool._pool), dsk, result,
         56                         cache=cache, queue=queue, get_id=_thread_get_id,
    ---> 57                         **kwargs)
         58 
         59     return results
    
    /home/vkcem4m/software/anaconda/lib/python2.7/site-packages/dask/async.pyc in get_async(apply_async, num_workers, dsk, result, cache, queue, get_id, raise_on_exception, rerun_exceptions_locally, callbacks, **kwargs)
        486                 _execute_task(task, data)  # Re-execute locally
        487             else:
    --> 488                 raise(remote_exception(res, tb))
        489         state['cache'][key] = res
        490         finish_task(dsk, key, state, results, keyorder.get)
    
    ValueError: Cannot convert NA to integer
    
    Traceback
    ---------
      File "/home/vkcem4m/software/anaconda/lib/python2.7/site-packages/dask/async.py", line 267, in execute_task
        result = _execute_task(task, data)
      File "/home/vkcem4m/software/anaconda/lib/python2.7/site-packages/dask/async.py", line 249, in _execute_task
        return func(*args2)
      File "/home/vkcem4m/software/anaconda/lib/python2.7/site-packages/dask/dataframe/csv.py", line 43, in bytes_read_csv
        coerce_dtypes(df, dtypes)
      File "/home/vkcem4m/software/anaconda/lib/python2.7/site-packages/dask/dataframe/csv.py", line 67, in coerce_dtypes
        df[c] = df[c].astype(dtypes[c])
      File "/home/vkcem4m/software/anaconda/lib/python2.7/site-packages/pandas/core/generic.py", line 2632, in astype
        dtype=dtype, copy=copy, raise_on_error=raise_on_error, **kwargs)
      File "/home/vkcem4m/software/anaconda/lib/python2.7/site-packages/pandas/core/internals.py", line 2864, in astype
        return self.apply('astype', dtype=dtype, **kwargs)
      File "/home/vkcem4m/software/anaconda/lib/python2.7/site-packages/pandas/core/internals.py", line 2823, in apply
        applied = getattr(b, f)(**kwargs)
      File "/home/vkcem4m/software/anaconda/lib/python2.7/site-packages/pandas/core/internals.py", line 430, in astype
        values=values, **kwargs)
      File "/home/vkcem4m/software/anaconda/lib/python2.7/site-packages/pandas/core/internals.py", line 472, in _astype
        values = com._astype_nansafe(values.ravel(), dtype, copy=True)
      File "/home/vkcem4m/software/anaconda/lib/python2.7/site-packages/pandas/core/common.py", line 2460, in _astype_nansafe
        raise ValueError('Cannot convert NA to integer')

**Comment by bkomboz** [comment]
dd.read_csv('/path/to/data.csv', sep=';', header=0, encoding='utf-8', dtype='object')

solves the problem. There is a column with mixed dtype.

**Comment by mrocklin** [comment]
Yeah, dask is guessing what the columns are based on the first bit of the file.  Sometimes it gets this wrong.  You probably have a column that is mostly integer valued with a couple of NA's buried in there.  You could also set `dtype={'column-name': float}` for that particular column to get richer dtypes.

**Comment by bkomboz** [comment]
Ok, thanks. I'll close this now.

**Comment by kilojoules** [comment]
+1 I'm stuck on this issue. 

    headers=['pointdatetime', 'turbineid', 'bl1_act']
    dtypes = {'pointdatetime':pd.Timestamp, 'turbineid':int, 'bl1_act':float}
    dat = dd.read_csv('./my_big_data_file.csv', header=0, dtype=dtypes)
    dat.columns = headers
    s = dat[dat.turbineid.isin([1,2,3,4])]
    s.to_csv('plant1.csv')
    
    ValueError                                Traceback (most recent call last)
    <ipython-input-69-8cde63a6372e> in <module>()
    ----> 1 s.to_csv('plant1.csv')
    
    /projects/WINDSE/SCADA/venv/lib/python2.7/site-packages/dask/dataframe/core.pyc in to_csv(self, filename, **kwargs)
        947         """ See dd.to_csv docstring for more information """
        948         from .io import to_csv
    --> 949         return to_csv(self, filename, **kwargs)
        950 
        951     def to_delayed(self):
    
    /projects/WINDSE/SCADA/venv/lib/python2.7/site-packages/dask/dataframe/io/csv.pyc in to_csv(df, filename, name_function, compression, compute, get, **kwargs)
        413 
        414     if compute:
    --> 415         delayed(values).compute(get=get)
        416     else:
        417         return values
    
    /projects/WINDSE/SCADA/venv/lib/python2.7/site-packages/dask/base.pyc in compute(self, **kwargs)
         92             Extra keywords to forward to the scheduler ``get`` function.
         93         """
    ---> 94         (result,) = compute(self, traverse=False, **kwargs)
         95         return result
         96 
    
    /projects/WINDSE/SCADA/venv/lib/python2.7/site-packages/dask/base.pyc in compute(*args, **kwargs)
        199     dsk = collections_to_dsk(variables, optimize_graph, **kwargs)
        200     keys = [var._keys() for var in variables]
    --> 201     results = get(dsk, keys, **kwargs)
        202 
        203     results_iter = iter(results)
    
    /projects/WINDSE/SCADA/venv/lib/python2.7/site-packages/dask/threaded.pyc in get(dsk, result, cache, num_workers, **kwargs)
         74     results = get_async(pool.apply_async, len(pool._pool), dsk, result,
         75                         cache=cache, get_id=_thread_get_id,
    ---> 76                         **kwargs)
         77 
         78     # Cleanup pools associated to dead threads
    
    /projects/WINDSE/SCADA/venv/lib/python2.7/site-packages/dask/async.pyc in get_async(apply_async, num_workers, dsk, result, cache, get_id, raise_on_exception, rerun_exceptions_locally, callbacks, dumps, loads, **kwargs)
        498                     _execute_task(task, data)  # Re-execute locally
        499                 else:
    --> 500                     raise(remote_exception(res, tb))
        501             state['cache'][key] = res
        502             finish_task(dsk, key, state, results, keyorder.get)
    
    ValueError: Cannot convert NA to integer
    
    Traceback
    ---------
      File "/projects/WINDSE/SCADA/venv/lib/python2.7/site-packages/dask/async.py", line 266, in execute_task
        result = _execute_task(task, data)
      File "/projects/WINDSE/SCADA/venv/lib/python2.7/site-packages/dask/async.py", line 247, in _execute_task
        return func(*args2)
      File "/projects/WINDSE/SCADA/venv/lib/python2.7/site-packages/dask/dataframe/io/csv.py", line 57, in pandas_read_text
        coerce_dtypes(df, dtypes)
      File "/projects/WINDSE/SCADA/venv/lib/python2.7/site-packages/dask/dataframe/io/csv.py", line 85, in coerce_dtypes
        df[c] = df[c].astype(dtypes[c])
      File "/projects/WINDSE/SCADA/venv/lib/python2.7/site-packages/pandas/core/generic.py", line 3054, in astype
        raise_on_error=raise_on_error, **kwargs)
      File "/projects/WINDSE/SCADA/venv/lib/python2.7/site-packages/pandas/core/internals.py", line 3189, in astype
        return self.apply('astype', dtype=dtype, **kwargs)
      File "/projects/WINDSE/SCADA/venv/lib/python2.7/site-packages/pandas/core/internals.py", line 3056, in apply
        applied = getattr(b, f)(**kwargs)
      File "/projects/WINDSE/SCADA/venv/lib/python2.7/site-packages/pandas/core/internals.py", line 461, in astype
        values=values, **kwargs)
      File "/projects/WINDSE/SCADA/venv/lib/python2.7/site-packages/pandas/core/internals.py", line 504, in _astype
        values = _astype_nansafe(values.ravel(), dtype, copy=True)
      File "/projects/WINDSE/SCADA/venv/lib/python2.7/site-packages/pandas/types/cast.py", line 531, in _astype_nansafe
        raise ValueError('Cannot convert NA to integer')

**Comment by mrocklin** [comment]
If you're on git-master you can do the following:

    df = dd.read_csv(..., assume_missing=True)

This will also be in the next release, which should be out in a few days.

**Comment by kilojoules** [comment]
Thanks @mrocklin I installed master and tried running my script again, except replacing the read_csv line with `dat = dd.read_csv('./crew_2013_load.csv', header=0, dtype=dtypes, assume_missing=True)`. Now dask is crashing with a different cryptic error:

    Traceback (most recent call last):
      File "reads.py", line 11, in <module>
        s.to_csv('plant1.csv')
      File "/projects/WINDSE/SCADA/venv/lib/python2.7/site-packages/dask-0.14.0_47.g53bba35-py2.7.egg/dask/dataframe/core.py", line 957, in to_csv
        return to_csv(self, filename, **kwargs)
      File "/projects/WINDSE/SCADA/venv/lib/python2.7/site-packages/dask-0.14.0_47.g53bba35-py2.7.egg/dask/dataframe/io/csv.py", line 445, in to_csv
        delayed(values).compute(get=get)
      File "/projects/WINDSE/SCADA/venv/lib/python2.7/site-packages/dask-0.14.0_47.g53bba35-py2.7.egg/dask/base.py", line 95, in compute
        (result,) = compute(self, traverse=False, **kwargs)
      File "/projects/WINDSE/SCADA/venv/lib/python2.7/site-packages/dask-0.14.0_47.g53bba35-py2.7.egg/dask/base.py", line 202, in compute
        results = get(dsk, keys, **kwargs)
      File "/projects/WINDSE/SCADA/venv/lib/python2.7/site-packages/dask-0.14.0_47.g53bba35-py2.7.egg/dask/threaded.py", line 76, in get
        **kwargs)
      File "/projects/WINDSE/SCADA/venv/lib/python2.7/site-packages/dask-0.14.0_47.g53bba35-py2.7.egg/dask/async.py", line 500, in get_async
        raise(remote_exception(res, tb))
    dask.async.IOError: [Errno 2] No such file or directory: 'plant1.csv/16354.part'
    
    Traceback
    ---------
      File "/projects/WINDSE/SCADA/venv/lib/python2.7/site-packages/dask-0.14.0_47.g53bba35-py2.7.egg/dask/async.py", line 266, in execute_task
        result = _execute_task(task, data)
      File "/projects/WINDSE/SCADA/venv/lib/python2.7/site-packages/dask-0.14.0_47.g53bba35-py2.7.egg/dask/async.py", line 247, in _execute_task
        return func(*args2)
      File "/projects/WINDSE/SCADA/venv/lib/python2.7/site-packages/dask-0.14.0_47.g53bba35-py2.7.egg/dask/bytes/core.py", line 38, in write_block_to_file
        with lazy_file as f:
      File "/projects/WINDSE/SCADA/venv/lib/python2.7/site-packages/dask-0.14.0_47.g53bba35-py2.7.egg/dask/bytes/core.py", line 314, in __enter__
        f = f2 = self.myopen(self.path, mode=mode)
      File "/projects/WINDSE/SCADA/venv/lib/python2.7/site-packages/dask-0.14.0_47.g53bba35-py2.7.egg/dask/bytes/local.py", line 63, in open
        return open(path, mode=mode)

**Comment by mrocklin** [comment]
Are you able to provide a reproducible fail case?

**Comment by kilojoules** [comment]
@mrocklin 

    $ cat ex.py 
    import pandas as pd
    import numpy as np
    import dask.dataframe as dd
    dat = pd.DataFrame()
    for i in range(10): 
       dat['col%i'%i] = np.random.random(3000)
       for _ in range(50):
          dat['col%i'%i][200] = np.nan
      
    dat.to_csv('example.csv', header = 0)
    df = dd.read_csv('example.csv', assume_missing=True, header=0)
    df.columns = ['col%i'%i for i in range(11)]
    s = df[df.col3 < 0.5]
    s.to_csv('finished.csv')
    
    
    $ python ex.py 
    /projects/WINDSE/SCADA/venv/lib/python2.7/site-packages/dask-0.14.0_47.g53bba35-py2.7.egg/dask/array/numpy_compat.py:32: RuntimeWarning: divide by zero encountered in divide
      not np.allclose(np.divide(1, .5, dtype='i8'), 2) or
    Traceback (most recent call last):
      File "ex.py", line 14, in <module>
        s.to_csv('finished.csv')
      File "/projects/WINDSE/SCADA/venv/lib/python2.7/site-packages/dask-0.14.0_47.g53bba35-py2.7.egg/dask/dataframe/core.py", line 957, in to_csv
        return to_csv(self, filename, **kwargs)
      File "/projects/WINDSE/SCADA/venv/lib/python2.7/site-packages/dask-0.14.0_47.g53bba35-py2.7.egg/dask/dataframe/io/csv.py", line 445, in to_csv
        delayed(values).compute(get=get)
      File "/projects/WINDSE/SCADA/venv/lib/python2.7/site-packages/dask-0.14.0_47.g53bba35-py2.7.egg/dask/base.py", line 95, in compute
        (result,) = compute(self, traverse=False, **kwargs)
      File "/projects/WINDSE/SCADA/venv/lib/python2.7/site-packages/dask-0.14.0_47.g53bba35-py2.7.egg/dask/base.py", line 202, in compute
        results = get(dsk, keys, **kwargs)
      File "/projects/WINDSE/SCADA/venv/lib/python2.7/site-packages/dask-0.14.0_47.g53bba35-py2.7.egg/dask/threaded.py", line 76, in get
        **kwargs)
      File "/projects/WINDSE/SCADA/venv/lib/python2.7/site-packages/dask-0.14.0_47.g53bba35-py2.7.egg/dask/async.py", line 500, in get_async
        raise(remote_exception(res, tb))
    dask.async.IOError: [Errno 2] No such file or directory: 'finished.csv/0.part'
    
    Traceback
    ---------
      File "/projects/WINDSE/SCADA/venv/lib/python2.7/site-packages/dask-0.14.0_47.g53bba35-py2.7.egg/dask/async.py", line 266, in execute_task
        result = _execute_task(task, data)
      File "/projects/WINDSE/SCADA/venv/lib/python2.7/site-packages/dask-0.14.0_47.g53bba35-py2.7.egg/dask/async.py", line 247, in _execute_task
        return func(*args2)
      File "/projects/WINDSE/SCADA/venv/lib/python2.7/site-packages/dask-0.14.0_47.g53bba35-py2.7.egg/dask/bytes/core.py", line 38, in write_block_to_file
        with lazy_file as f:
      File "/projects/WINDSE/SCADA/venv/lib/python2.7/site-packages/dask-0.14.0_47.g53bba35-py2.7.egg/dask/bytes/core.py", line 314, in __enter__
        f = f2 = self.myopen(self.path, mode=mode)
      File "/projects/WINDSE/SCADA/venv/lib/python2.7/site-packages/dask-0.14.0_47.g53bba35-py2.7.egg/dask/bytes/local.py", line 63, in open
        return open(path, mode=mode)

**Comment by mrocklin** [comment]
The `to_csv` method writes each partition of your dask.dataframe to a separate file.  It expects a directory, not a single filename.  See http://dask.pydata.org/en/latest/dataframe-api.html#dask.dataframe.to_csv

**Comment by mglowacki100** [comment]
I'm facing exactly the same issue, but I use `dd.read_sql_table` instead of `dd.read_csv`. 
I can't find anything similar to `assume_missing=True` for this. 
How to solve it?

**Comment by shahhaard47** [comment]
I need help with the same issue !

> I'm facing exactly the same issue, but I use `dd.read_sql_table` instead of `dd.read_csv`.
> I can't find anything similar to `assume_missing=True` for this.
> How to solve it?

**Comment by jsignell** [comment]
I bet you can explicitly pass in a `meta` object where you can specify that the ones with missing values have type float and that should work the same. But if not, please open a new issue with a reproducible example.
