### ISSUE TITLE
DataFrame.loc does not work with list of indices

### ISSUE THREAD

**Issue by erwindassen** [dask/dask#1298]
If `i = [3, 5, 1]` and `df` is a pandas data frame this returns the numbered rows in the defined order: `df.loc[i]`. 

This is the expected behavior for `dask.dataframe.DataFrame` but if `df` is such an object then `df.loc[i]` does not work. Note that you _can_ give it a slice: `df.loc[3:6]` for example.

On a side note, although using numbers in the example above, `loc` is for labels and as such we could expect partitions made of indices (or multindices) of strings, datetimes, and other objects...

**Comment by mrocklin** [comment]
This is reasonable to do and not particularly hard.  Just needs someone with a bit of time and expertise.

**Comment by mrocklin** [comment]
For short lists you could also use a combination of a list comprehension and `dd.concat`

    dd.concat([df.loc[i] for i in L])

This would be inefficient for large `L` though

**Comment by abast** [comment]
What about this one for larger lists?

`ddf.map_partitions(lambda x: x[x.index.isin(L)])`

**Comment by sinhrks** [comment]
We can use ``_partition_of_index_value`` to map input labels to partitions. Then simply use ``.loc[partitioned_list]`` for each.

- https://github.com/dask/dask/blob/master/dask/dataframe/indexing.py#L164

**Comment by tundo91** [comment]
Hi there, been using 0.14.1, opened #2203. Here's an even simpler example:
```python
print df.get_partition(partition_index).loc[0:1].compute()
print df.get_partition(partition_index).loc[[0, 1]].compute()
```
Output:
```
   Unnamed: 0  best_answer  thread_id  ty_avc    ty_ber  ty_cjr  ty_cpc  \
0           0            1          1       1  0.052174       9      18   
1           1            0          1       1  0.060241       5      11   
....
[2 rows x 24 columns]

Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/Users/erotundo/PycharmProjects/DatasetAnnotatorProj/Analysis/train_binaryBestAnswer.py", line 99, in <module>
    main()
  File "/Users/erotundo/PycharmProjects/DatasetAnnotatorProj/Analysis/train_binaryBestAnswer.py", line 53, in main
    print df.get_partition(partition_index).loc[[0, 1]].compute()
  File "/Users/erotundo/PycharmProjects/DatasetAnnotatorProj/venv/lib/python2.7/site-packages/dask/dataframe/indexing.py", line 50, in __getitem__
    return self._loc(iindexer, cindexer)
  File "/Users/erotundo/PycharmProjects/DatasetAnnotatorProj/venv/lib/python2.7/site-packages/dask/dataframe/indexing.py", line 72, in _loc
    raise KeyError(msg)
KeyError: 'Cannot index with list against unknown division'
```
