### ISSUE TITLE
Dask Array mean example raises ValueError on distributed cluster

### ISSUE THREAD

**Issue by philastrophist** [dask/dask#1387]
```
from distributed import Executor
import dask
import numpy as np

e = Executor()  # localhost executor with 4 processes each with 1 core
x = np.arange(100).reshape(10,10)  # the exception is raised with any array shape
y = da.from_array(x, chunks=(2,2))
yy = e.persist(y)
print yy.mean().compute()
```

This returns:
```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-32-4aa3f1a41912> in <module>()
----> 1 meaned = mean.compute()

C:\Users\User\Anaconda\lib\site-packages\dask\base.pyc in compute(self, **kwargs)
     84             Extra keywords to forward to the scheduler ``get`` function.

     85         """
---> 86         return compute(self, **kwargs)[0]
     87
     88     @classmethod

C:\Users\User\Anaconda\lib\site-packages\dask\base.pyc in compute(*args, **kwargs)
    177         dsk = merge(var.dask for var in variables)
    178     keys = [var._keys() for var in variables]
--> 179     results = get(dsk, keys, **kwargs)
    180
    181     results_iter = iter(results)

C:\Users\User\Anaconda\lib\site-packages\dask\threaded.pyc in get(dsk, result, cache, num_workers, **kwargs)
     55     results = get_async(pool.apply_async, len(pool._pool), dsk, result,
     56                         cache=cache, queue=queue, get_id=_thread_get_id,

---> 57                         **kwargs)
     58
     59     return results

C:\Users\User\Anaconda\lib\site-packages\dask\async.pyc in get_async(apply_async, num_workers, dsk, result, cache, queue, get_id, raise_on_exception, rerun_exceptions_locally, callbacks, **kwargs)
    482                 _execute_task(task, data)  # Re-execute locally
    483             else:
--> 484                 raise(remote_exception(res, tb))
    485         state['cache'][key] = res
    486         finish_task(dsk, key, state, results, keyorder.get)

ValueError: 'axis' entry is out of bounds

Traceback
---------
  File "C:\Users\User\Anaconda\lib\site-packages\dask\async.py", line 267, in execute_task
    result = _execute_task(task, data)
  File "C:\Users\User\Anaconda\lib\site-packages\dask\async.py", line 249, in _execute_task
    return func(*args2)
  File "C:\Users\User\Anaconda\lib\site-packages\dask\array\reductions.py", line 224, in mean_chunk
    n = numel(x, dtype=dtype, **kwargs)
  File "C:\Users\User\Anaconda\lib\site-packages\dask\array\reductions.py", line 215, in numel
    return chunk.sum(np.ones_like(x), **kwargs)
  File "C:\Users\User\Anaconda\lib\site-packages\numpy\core\fromnumeric.py", line 1835, in sum
    out=out, keepdims=keepdims)
  File "C:\Users\User\Anaconda\lib\site-packages\numpy\core\_methods.py", line 32, in _sum
    return umr_sum(a, axis, dtype, out, keepdims)
```

**Comment by mrocklin** [comment]
Your call to `.compute()` is using the threaded scheduler by default.  This can be fixed by one of the following

```python
yy.mean().compute(get=e.get)

dask.set_options(get=e.get)

e = Executor(set_as_default=True)
```

Perhaps it's time to use `set_as_default=True` by default.  This confusion has come up enough times that this change is probably warranted.
