### ISSUE TITLE
Error requirements starting dask-scheduler on HPC cluster

### ISSUE THREAD

**Issue by simone-codeluppi** [dask/dask#1390]
Hi
I installed dask on python3 via pip3 on HPC node. when I run the scheduler I get the following error:

File "/home/x_simco/test/lib/python3.4/site-packages/dask/compatibility.py", line 23, in <module>
    from lzmaffi import (LZMAFile, compress as lzma_compress,
ImportError: No module named 'lzmaffi'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/x_simco/test/bin/dask-scheduler", line 7, in <module>
    from distributed.cli.dask_scheduler import go
  File "/home/x_simco/test/lib/python3.4/site-packages/distributed/__init__.py", line 3, in <module>
    from .center import Center
  File "/home/x_simco/test/lib/python3.4/site-packages/distributed/center.py", line 13, in <module>
    from .core import (Server, read, write, rpc, pingpong, send_recv,
  File "/home/x_simco/test/lib/python3.4/site-packages/distributed/core.py", line 26, in <module>
    from .utils import get_traceback, truncate_exception, ignoring
  File "/home/x_simco/test/lib/python3.4/site-packages/distributed/utils.py", line 15, in <module>
    from dask import istask
  File "/home/x_simco/test/lib/python3.4/site-packages/dask/__init__.py", line 5, in <module>
    from .async import get_sync as get
  File "/home/x_simco/test/lib/python3.4/site-packages/dask/async.py", line 126, in <module>
    from .optimize import cull
  File "/home/x_simco/test/lib/python3.4/site-packages/dask/optimize.py", line 6, in <module>
    from .compatibility import zip_longest
  File "/home/x_simco/test/lib/python3.4/site-packages/dask/compatibility.py", line 26, in <module>
    from lzma import (LZMAFile, compress as lzma_compress,
  File "/software/apps/python/3.4.1/snic-1/lib/python3.4/lzma.py", line 26, in <module>
    from _lzma import *

**Comment by mrocklin** [comment]
Hrm, that's surprising.  I thought that lzma was part of the standard library.  This should be fairly easy to guard against.  I'll post a fix soon.

**Comment by mrocklin** [comment]
@jcrist resolved this in #1391 .  Please let us know if the problem persists.
