### ISSUE TITLE
running out of memory when gathering results in dask distributed

### ISSUE THREAD

**Issue by akcheung** [dask/dask#1412]
I have been playing around with dask distributed with the following code:
```
data = np.random.randint(0, 1000, size=(145, 174, 145, 288))
for i in range(data.shape[-1]):
  v = data[..., i]
  r = delayed(foo)(v)
  jobs.append(r)

# j is another numpy array with the same size as data
j = compute(*jobs, get=executor.get)

for i in range(data.shape[-1]):
  output[..., i] = j[i]

writeToDisk(compress(output))
```
This ran out of memory when executed on a machine with 30GB of RAM after returning MemoryError in Packer. I suppose this is due to the data gathering step receiving too much data from the workers?

I have also tried using persist instead as follows:
```
for i in range(data.shape[-1]): 
  v = data[..., i]
  r = delayed(foo)(v)
  jobs.append(r)

j = executor.persist(jobs)

for i in range(data.shape[-1]):
  output[..., i] = j[i].compute().result()

writeToDisk(compress(output))
```
This returned 
```
distributed.core - ERROR - error return without exception set
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/distributed/core.py", line 269, in write
    frames = protocol.dumps(msg)
  File "/usr/local/lib/python3.4/dist-packages/distributed/protocol.py", line 81, in dumps
    frames = dumps_msgpack(small)
  File "/usr/local/lib/python3.4/dist-packages/distributed/protocol.py", line 153, in dumps_msgpack
    payload = msgpack.dumps(msg, use_bin_type=True)
  File "/usr/local/lib/python3.4/dist-packages/msgpack/__init__.py", line 47, in packb
    return Packer(**kwargs).pack(o)
SystemError: error return without exception set
```
I suppose this is the same problem.

**Comment by mrocklin** [comment]
Are you actually getting a `MemoryError` or the `SystemError` shown in your traceback?

Repeating content from the mailing list for posterity:  Msgpack has a 2GB length limit on bytestrings.  We get around this for explicitly moved data by sending large bytestrings in the top-level message dictionary separately.  However, we don't spider down to all of the sub-messages, and so if large numpy arrays occur directly as inputs to tasks then we don't send them optimally and instead just dump them in with the normal message, with the 2GB limit.  

This change either needs to occur in the dask/distributed or in dask/delayed and how it handles large inputs, or possibly both.

**Comment by akcheung** [comment]
`SystemError` when using `persist`, `MemoryError` in the original code:
```
distributed.core - ERROR -
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/distributed/core.py", line 269, in write
    frames = protocol.dumps(msg)
  File "/usr/local/lib/python3.4/dist-packages/distributed/protocol.py", line 81, in dumps
    frames = dumps_msgpack(small)
  File "/usr/local/lib/python3.4/dist-packages/distributed/protocol.py", line 153, in dumps_msgpack
    payload = msgpack.dumps(msg, use_bin_type=True)
  File "/usr/local/lib/python3.4/dist-packages/msgpack/__init__.py", line 47, in packb
    return Packer(**kwargs).pack(o)
  File "msgpack/_packer.pyx", line 231, in msgpack._packer.Packer.pack (msgpack/_packer.cpp:231)
  File "msgpack/_packer.pyx", line 239, in msgpack._packer.Packer.pack (msgpack/_packer.cpp:239)
MemoryError
```

**Comment by mrocklin** [comment]
The issue of sending large bytestrings in nested messages was resolved in https://github.com/dask/distributed/pull/397
