### ISSUE TITLE
Support simple scalar conversions

### ISSUE THREAD

**Issue by skrah** [dask/dask#1445]
`dask.dataframe.core.Scalar` conversions go through `odo` in blaze, which fails:

```python
>>> import odo
>>> x
<dask.dataframe.core.Scalar object at 0x7f06ad06d048>
>>> odo.odo(x, float)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/conda/miniconda3/envs/blaze/lib/python3.4/site-packages/odo-0.5.0+16.gda7f26d-py3.4.egg/odo/odo.py", line 91, in odo
    return into(target, source, **kwargs)
  File "/home/conda/miniconda3/envs/blaze/lib/python3.4/site-packages/multipledispatch/dispatcher.py", line 164, in __call__
    return func(*args, **kwargs)
  File "/home/conda/miniconda3/envs/blaze/lib/python3.4/site-packages/odo-0.5.0+16.gda7f26d-py3.4.egg/odo/into.py", line 43, in wrapped
    return f(*args, **kwargs)
  File "/home/conda/miniconda3/envs/blaze/lib/python3.4/site-packages/odo-0.5.0+16.gda7f26d-py3.4.egg/odo/into.py", line 53, in into_type
    return convert(a, b, dshape=dshape, **kwargs)
  File "/home/conda/miniconda3/envs/blaze/lib/python3.4/site-packages/odo-0.5.0+16.gda7f26d-py3.4.egg/odo/core.py", line 44, in __call__
    return _transform(self.graph, *args, **kwargs)
  File "/home/conda/miniconda3/envs/blaze/lib/python3.4/site-packages/odo-0.5.0+16.gda7f26d-py3.4.egg/odo/core.py", line 57, in _transform
    ooc_types=ooc_types)
  File "/home/conda/miniconda3/envs/blaze/lib/python3.4/site-packages/odo-0.5.0+16.gda7f26d-py3.4.egg/odo/core.py", line 92, in path
    pth = nx.shortest_path(g, source=source, target=target, weight='cost')
  File "/home/conda/miniconda3/envs/blaze/lib/python3.4/site-packages/networkx/algorithms/shortest_paths/generic.py", line 138, in shortest_path
    paths=nx.dijkstra_path(G,source,target,weight)
  File "/home/conda/miniconda3/envs/blaze/lib/python3.4/site-packages/networkx/algorithms/shortest_paths/weighted.py", line 78, in dijkstra_path
    weight=weight)
  File "/home/conda/miniconda3/envs/blaze/lib/python3.4/site-packages/networkx/algorithms/shortest_paths/weighted.py", line 296, in single_source_dijkstra
    target=target)
  File "/home/conda/miniconda3/envs/blaze/lib/python3.4/site-packages/networkx/algorithms/shortest_paths/weighted.py", line 356, in _dijkstra
    for u, e in G_succ[v].items():
KeyError: <class 'dask.dataframe.core.Scalar'>
```

I wonder if these things need to go through odo.  Would it be possible  to add `__float__` and `__int__` methods to `dask.dataframe.core.Scalar`?

**Comment by mrocklin** [comment]
This is not difficult to add.  However to me it seems safer to have users explicitly call `.compute()` so that they know that what they are doing is triggering a computation and may be costly.

**Comment by mrocklin** [comment]
Thoughts?

**Comment by skrah** [comment]
Yes, I wasn't sure if a computation could be triggered if something is already a scalar.  If that's the case, then the explicit `.compute()` is definitely better.

I'm closing this -- Blaze can duck type on `.compute()` or odo needs another conversion.
