### ISSUE TITLE
Groupby interprets string dict keys as bytes

### ISSUE THREAD

**Issue by alanhdu** [dask/dask#1452]
With Python 3.5 and dask 0.10.1 (and git master), the following code fails with a key error:

```Python
import dask.bag as db
import dask
db.from_sequence([{"a": 1}]).groupby("a").compute(get=dask.async.get_sync)
```

```
Traceback (most recent call last):
  File "test.py", line 5, in <module>
    bag.groupby("a").compute(get=dask.async.get_sync)
  File "/home/alan/anaconda/envs/test/lib/python3.5/site-packages/dask/base.py", line 86, in compute
    return compute(self, **kwargs)[0]
  File "/home/alan/anaconda/envs/test/lib/python3.5/site-packages/dask/base.py", line 179, in compute
    results = get(dsk, keys, **kwargs)
  File "/home/alan/anaconda/envs/test/lib/python3.5/site-packages/dask/async.py", line 523, in get_sync
    raise_on_exception=True, **kwargs)
  File "/home/alan/anaconda/envs/test/lib/python3.5/site-packages/dask/async.py", line 490, in get_async
    fire_task()
  File "/home/alan/anaconda/envs/test/lib/python3.5/site-packages/dask/async.py", line 461, in fire_task
    get_id, raise_on_exception])
  File "/home/alan/anaconda/envs/test/lib/python3.5/site-packages/dask/async.py", line 511, in apply_sync
    return func(*args, **kwds)
  File "/home/alan/anaconda/envs/test/lib/python3.5/site-packages/dask/async.py", line 267, in execute_task
    result = _execute_task(task, data)
  File "/home/alan/anaconda/envs/test/lib/python3.5/site-packages/dask/async.py", line 249, in _execute_task
    return func(*args2)
  File "/home/alan/anaconda/envs/test/lib/python3.5/site-packages/dask/bag/core.py", line 1143, in collect
    d = groupby(grouper, p.get(group, lock=False))
  File "/home/alan/anaconda/envs/test/lib/python3.5/site-packages/toolz/itertoolz.py", line 93, in groupby
    d[key(item)](item)
KeyError: 'a'
```

A `pdb` session shows that somehow the groupby is converting `{"a": 1}` into `{b"a": 1}`, which explains the key error.

**Comment by alanhdu** [comment]
Tracked this down to upstream pandas https://github.com/pydata/pandas/issues/13945. The best workaround I can see is to use `pickle` by default in `partd.Python` instead of `msgpack`.

**Comment by mrocklin** [comment]
This can probably be fixed if we use the `use_bin_type=` and `encoding=` keyword arguments in `partd.Python`

```python
```python
In [1]: import pandas as pd

In [2]: pd.msgpack.unpackb(pd.msgpack.packb("a"))
Out[2]: b'a'

In [3]: pd.msgpack.unpackb(pd.msgpack.packb(u"a", use_bin_type=True), encoding='
   ...: utf8')
Out[3]: 'a'
```

Is this something you'd like to contribute @alanhdu?  I can do it otherwise.  I expect the change to be easy.

**Comment by alanhdu** [comment]
I probably won't have time until the weekend, but I'll definitely take a look then if this is still open.

**Comment by mrocklin** [comment]
It wasn't a hard fix.  Done here: https://github.com/dask/partd/pull/16/files
