### ISSUE TITLE
Operations on filtered dask dataframes fail due to dummy metadata

### ISSUE THREAD

**Issue by paulmayer** [dask/dask#1548]
Depending on the syntax used to trigger an aggregate computation on Series, dummy information in `_Frame`'s `_meta_nonempty` property can cause failures.

Minimal example:
```
print(dask.__version__)  # 0.11.0
data = {'col1': ['a', 'a', 'b'], 'col2': np.asarray([0.0, 1.0, 0.0], dtype=np.float)}
pandas_df = pd.DataFrame(data=data, columns=['col1', 'col2'])
df = dd.from_pandas(pandas_df, npartitions=1)

# let's take a look at _meta depending on the syntax
print(df[df.col1 == 'a'].col2._meta)        # Series([], Name: col2, dtype: float64)
print(df.col2[df.col1 == 'a']._meta)        # foo

# computing a mean over a column
df.col2[df.col1 == 'a'].mean().compute()    # fails with error (allow providing meta-information similarly to apply?)
ret = df[df.col1 == 'a'].col2.mean().compute()    # works
print(ret)                                  # 0.5
```

Traceback:
```
Traceback (most recent call last):
  File "D:/CEMP/workspace/pyCEMP/pyCEMP/old_cemp.py", line 27, in <module>
    df.col2[df.col1 == 'a'].mean().compute()    # fails with error
  File "C:\Users\mayerpa\envs\pylambda\lib\site-packages\dask\dataframe\core.py", line 1387, in mean
    return super(Series, self).mean(axis=axis, skipna=skipna)
  File "C:\Users\mayerpa\envs\pylambda\lib\site-packages\dask\dataframe\core.py", line 949, in mean
    meta = self._meta_nonempty.mean(axis=axis, skipna=skipna)
TypeError: _mean() got an unexpected keyword argument 'skipna'
```
`apply()` already offers a way to pass a meta-DataFrame which is used to construct the result. Would it be possible to also add this to `mean()` and similar operations?

**Comment by jcrist** [comment]
Thanks for the bug report, this was an issue in the implementation of `__getitem__` for Series, fixing now.

> Would it be possible to also add this to mean() and similar operations?

In general these kind of operations should be fully specifiable internally (minus bugs like this), so I'd prefer not to add this option.

**Comment by mrocklin** [comment]
Fixed by https://github.com/dask/dask/pull/1549

**Comment by mrocklin** [comment]
Thanks for the great minimal example @paulmayer .  Huge help!
