### ISSUE TITLE
TypeError: can't pickle _thread.lock objects when multiprocessing on DataFrames

### ISSUE THREAD

**Issue by kaloramik** [dask/dask#1683]
Hi,

I have some code written in pandas where I perform a series of filters to a DataFrame. I am trying to replicate the same logic with Dask DataFrames.

The Original Pandas code looks something like this

``` python
df = pd.read_hdf(file_path, key='df')

df = df[df[['col_1', 'col_2']].notnull().all(axis=1)]
```

The Dask version looks like this

``` python
    ddf = dd.read_hdf(file_path, 'df')
    new_ddf = ddf[ddf['col_1'].notnull() & ddf['col_2'].notnull()].compute()
```

Both snippets work. However, the following snippet 

``` python
    ddf = dd.read_hdf(file_path, 'df')
    new_ddf = ddf[ddf['col_1'].notnull() & ddf['col_2'].notnull()].compute(get=dask.multiprocessing.get)
```

throws 

```
  File "/Users/mik-OD/anaconda/envs/dask/lib/python3.5/site-packages/dask/base.py", line 171, in compute
    results = get(dsk, keys, **kwargs)
  File "/Users/mik-OD/anaconda/envs/dask/lib/python3.5/site-packages/dask/multiprocessing.py", line 83, in get
    queue=queue, get_id=_process_get_id, **kwargs)
  File "/Users/mik-OD/anaconda/envs/dask/lib/python3.5/site-packages/dask/async.py", line 466, in get_async
    fire_task()
  File "/Users/mik-OD/anaconda/envs/dask/lib/python3.5/site-packages/dask/async.py", line 462, in fire_task
    get_id, raise_on_exception])
  File "/Users/mik-OD/anaconda/envs/dask/lib/python3.5/site-packages/toolz/functoolz.py", line 281, in __call__
    return self._partial(*args, **kwargs)
  File "/Users/mik-OD/anaconda/envs/dask/lib/python3.5/site-packages/dask/multiprocessing.py", line 123, in pickle_apply_async
    may_fail = dumps((task, data))
  File "/Users/mik-OD/anaconda/envs/dask/lib/python3.5/site-packages/dask/multiprocessing.py", line 29, in _dumps
    return cloudpickle.dumps(x, protocol=pickle.HIGHEST_PROTOCOL)
  File "/Users/mik-OD/anaconda/envs/dask/lib/python3.5/site-packages/cloudpickle/cloudpickle.py", line 629, in dumps
    cp.dump(obj)
  File "/Users/mik-OD/anaconda/envs/dask/lib/python3.5/site-packages/cloudpickle/cloudpickle.py", line 107, in dump
    return Pickler.dump(self, obj)
  File "/Users/mik-OD/anaconda/envs/dask/lib/python3.5/pickle.py", line 408, in dump
    self.save(obj)
  File "/Users/mik-OD/anaconda/envs/dask/lib/python3.5/pickle.py", line 475, in save
    f(self, obj) # Call unbound method with explicit self
  File "/Users/mik-OD/anaconda/envs/dask/lib/python3.5/pickle.py", line 725, in save_tuple
    save(element)
  File "/Users/mik-OD/anaconda/envs/dask/lib/python3.5/pickle.py", line 475, in save
    f(self, obj) # Call unbound method with explicit self
  File "/Users/mik-OD/anaconda/envs/dask/lib/python3.5/pickle.py", line 740, in save_tuple
    save(element)
  File "/Users/mik-OD/anaconda/envs/dask/lib/python3.5/pickle.py", line 495, in save
    rv = reduce(self.proto)
TypeError: can't pickle _thread.lock objects
```
1. I'm staying within the realm of pandas dataframes, should I be expecting to run into these locking / serialization issues?
2. is there a way to more succinctly represent the filter operation in the dask version?

Thanks!

**Comment by kaloramik** [comment]
Ah I was able to fix the lock issue with 

```python
ddf = dd.read_hdf(file_path, 'df', lock=False)
```

However this causes the code to hang with multiprocessing, but it seems to succeed with a distributed scheduler. 

- Is there any guidance on the usage of the lock parameter? should we just always use it when doing distributed computation?
- Still same question on filtering, I wasn't able to get the dask version to look any more like the regular pandas version 

Thanks

**Comment by mrocklin** [comment]
You could try using a multiprocessing-safe lock:

```python
from multiprocessing import Lock
lock = Lock()

ddf = dd.read_hdf(file_path, 'df', lock=lock)
```

**Comment by abast** [comment]
I think this might be valuable in the documentation.

**Comment by jreback** [comment]
This issue persists even on the distributed scheduler:

setup
```
In [58]: import dask

In [59]: dask.__version__
Out[59]: '0.12.0'

In [60]: import distributed

In [61]: distributed.__version__
Out[61]: '1.14.3'

In [1]: from distributed import LocalCluster, Client

In [2]: c = LocalCluster(nanny=False)

In [3]: client = Client(c)

In [4]: client
Out[4]: <Client: scheduler="127.0.0.1:8786" processes=1 cores=16>

In [6]: df = DataFrame({'A' : ['foo', 'bar', 'baz'], 'B' : [1, 2, 3]})

In [7]: df
Out[7]:
     A  B
0  foo  1
1  bar  2
2  baz  3

In [8]: df.to_hdf('test.h5', 'df', format='table')
```

ok
```
In [13]: ddf = dd.read_hdf('test.h5', 'df', chunksize=1, lock=False)

In [14]: client.persist(ddf)
Out[14]: dd.DataFrame<read-hd..., npartitions=3>
In [11]: ddf = dd.read_hdf('test.h5', 'df', chunksize=1)
```

errors
```
In [11]: ddf = dd.read_hdf('test.h5', 'df', chunksize=1)

In [12]: client.persist(ddf)
C:\Anaconda\envs\bmc3\lib\site-packages\distributed\protocol\pickle.py - INFO - Failed to serialize ('test.h5', '/df', <unlocked _thread.lock object at 0x000000000AAC9EE0>, {'columns': Index(['A', 'B'], dtype='object'), 'stop': 3, 'mode': 'a', 'start': 2})
Traceback (most recent call last):
  File "C:\Anaconda\envs\bmc3\lib\site-packages\distributed\protocol\pickle.py", line 30, in dumps
    result = pickle.dumps(x, protocol=pickle.HIGHEST_PROTOCOL)
TypeError: can't pickle _thread.lock objects
```

**Comment by mrocklin** [comment]
Yes, we will start using dask.utils.SerializableLocks soon.

**Comment by jreback** [comment]
thanks @mrocklin

**Comment by mrocklin** [comment]
We now carefully select a lock based on the scheduler.
