### ISSUE TITLE
dataframe.from_bcolz groupby.mean error

### ISSUE THREAD

**Issue by rabernat** [dask/dask#1703]
I have a large table stored in bcolz format. I want to load it into a dask.dataframe and apply a groupby operation. I am using version 0.11.1.

I have put a sample bcolz dataset online [here](http://www.ldeo.columbia.edu/~rpa/traj_0000-0030.bcolz.tar) (warning: 1.9 GB download, sorry...but if it were small I wouldn't need dask!)

Here is my code:
```python
import bcolz
import dask.dataframe as ddf

fname = 'traj_0000-0030.bcolz'
bc = bcolz.open(rootdir=fname, mode='r')
df = ddf.from_bcolz(bc)

# works
df.groupby('npart')['vort'].count()

# fails
df.groupby('npart')['vort'].mean()
```

Here is the full stack trace:
```
ValueError                                Traceback (most recent call last)
<ipython-input-12-0d662baf9b68> in <module>()
----> 1 df.groupby('npart')['vort'].mean()

/home/rpa/.local/lib/python2.7/site-packages/dask-0.11.1-py2.7.egg/dask/dataframe/groupby.pyc in mean(self)
    248     @derived_from(pd.core.groupby.GroupBy)
    249     def mean(self):
--> 250         return self.sum() / self.count()
    251 
    252     @derived_from(pd.core.groupby.GroupBy)

/home/rpa/.local/lib/python2.7/site-packages/dask-0.11.1-py2.7.egg/dask/dataframe/core.pyc in <lambda>(self, other)
   1028             return lambda self, other: elemwise(op, other, self)
   1029         else:
-> 1030             return lambda self, other: elemwise(op, self, other)
   1031 
   1032     def rolling(self, window, min_periods=None, freq=None, center=False,

/home/rpa/.local/lib/python2.7/site-packages/dask-0.11.1-py2.7.egg/dask/dataframe/core.pyc in elemwise(op, *args, **kwargs)
   2449             msg = 'elemwise with 2 or more DataFrames and Scalar is not supported'
   2450             raise NotImplementedError(msg)
-> 2451         meta = _emulate(op, *args, **kwargs)
   2452 
   2453     return new_dd_object(dsk, _name, meta, divisions)

/home/rpa/.local/lib/python2.7/site-packages/dask-0.11.1-py2.7.egg/dask/dataframe/core.pyc in _emulate(func, *args, **kwargs)
   2606     """
   2607     with raise_on_meta_error(funcname(func)):
-> 2608         return func(*_extract_meta(args, True), **_extract_meta(kwargs, True))
   2609 
   2610 

/usr/local/anaconda/lib/python2.7/contextlib.pyc in __exit__(self, type, value, traceback)
     33                 value = type()
     34             try:
---> 35                 self.gen.throw(type, value, traceback)
     36                 raise RuntimeError("generator didn't stop after throw()")
     37             except StopIteration, exc:

/home/rpa/.local/lib/python2.7/site-packages/dask-0.11.1-py2.7.egg/dask/dataframe/utils.pyc in raise_on_meta_error(funcname)
    157                ).format(" in `{0}`".format(funcname) if funcname else "",
    158                         repr(e), tb)
--> 159         raise ValueError(msg)
    160 
    161 

ValueError: Metadata inference failed in `truediv`.

Original error is below:
------------------------
AttributeError("'module' object has no attribute 'RangeIndex'",)

Traceback:
---------
  File "/home/rpa/.local/lib/python2.7/site-packages/dask-0.11.1-py2.7.egg/dask/dataframe/utils.py", line 146, in raise_on_meta_error
    yield
  File "/home/rpa/.local/lib/python2.7/site-packages/dask-0.11.1-py2.7.egg/dask/dataframe/core.py", line 2608, in _emulate
    return func(*_extract_meta(args, True), **_extract_meta(kwargs, True))
  File "/home/rpa/.local/lib/python2.7/site-packages/dask-0.11.1-py2.7.egg/dask/dataframe/core.py", line 2592, in _extract_meta
    return tuple([_extract_meta(_x, nonempty) for _x in x])
  File "/home/rpa/.local/lib/python2.7/site-packages/dask-0.11.1-py2.7.egg/dask/dataframe/core.py", line 2588, in _extract_meta
    return x._meta_nonempty if nonempty else x._meta
  File "/home/rpa/.local/lib/python2.7/site-packages/dask-0.11.1-py2.7.egg/dask/dataframe/core.py", line 258, in _meta_nonempty
    return meta_nonempty(self._meta)
  File "/home/rpa/.local/lib/python2.7/site-packages/dask-0.11.1-py2.7.egg/dask/dataframe/utils.py", line 328, in meta_nonempty
    idx = _nonempty_index(x.index)
  File "/home/rpa/.local/lib/python2.7/site-packages/dask-0.11.1-py2.7.egg/dask/dataframe/utils.py", line 226, in _nonempty_index
    if typ is pd.RangeIndex:
```

**Comment by jcrist** [comment]
Looks like your version of pandas is too old. Range index was added in pandas 0.18: http://pandas.pydata.org/pandas-docs/version/0.18.0/whatsnew.html. Can you try updating pandas to 0.18+ and see if it works?

**Comment by rabernat** [comment]
Yes, that fixes it. Thanks @jcrist!
