### ISSUE TITLE
Random access to dask array spanning several HDF5 files sometimes leads to IOErrors.

### ISSUE THREAD

**Issue by axeltidemann** [dask/dask#1720]
I create a dask array out of several HDF5 files, but I find that some indices lead to an `IOError: Can't read data (Can't open directory)`. The indices should be continuous, no? I attach an example. The creation of HDF5 files mimic the ones I am working on. 

```python 
import glob
import string
import random

import numpy as np
import pandas as pd
import dask.array as da
import h5py

shapes = [8000, 839, 8000]
width = 2048 # The length of vectors I am working with                                                                                                                               

for i, shape in enumerate(shapes):
    h5name = '{}.h5'.format(i)
    with pd.HDFStore(h5name, mode='w', complevel=9, complib='blosc') as store:
        for _ in range(3): # To simulate chunk writes                                                                                                                                
            X = np.random.random((shape, width))

            # To allow columns this wide, they must be strings, not integers                                                                                                         
            columns = [ 'f{}'.format(i) for i in range(X.shape[1]) ]

            # String indexes of varying length                                                                                                                                       
            index = [ ''.join(random.choice(string.ascii_uppercase + string.digits)
                              for _ in range(np.random.randint(20,51)))
                      for _ in range(shape) ]

            df = pd.DataFrame(data=X, index=index, columns=columns)
            df.index.name='filename'
            store.append('data', df)

h5_files = glob.glob('*.h5')

datasets = [ h5py.File(fn)['/data/table'] for fn in h5_files ]
arrays = [ da.from_array(data, chunks=1000) for data in datasets ]
X = da.concatenate(arrays, axis=0)

print X # Everything seems fine                                                                                                                                                      

trouble = X[2515] # This value I found by trial and error                                                                                                                            
print trouble # Here we can see that the shape is (), so clearly something is wrong
print trouble.compute() # IOError                                                                                                                                   
```

**Comment by mrocklin** [comment]
Hrm, unfortunately this is working fine when I try it out locally.

**Comment by axeltidemann** [comment]
Funnily enough, this works locally on my MacBook as well. This fails consistently on my AWS instance, on which I have developed the code. Then I guess it must be due to different versions of HDF5/h5py/dask. I include the error message I get, in case you (@mrocklin) immediately spot what might be the culprit, while I am investigating what is the reason for this.

```
> python demo_trouble.py 
dask.array<concate..., shape=(50517,), dtype=[('index', 'S50'), ('values_block_0', '<f8', (2048,))], chunksize=(1000,)>
dask.array<getitem..., shape=(), dtype=[('index', 'S50'), ('values_block_0', '<f8', (2048,))], chunksize=()>
Traceback (most recent call last):
  File "demo_trouble.py", line 41, in <module>
    print trouble.compute() # IOError
  File "/usr/local/lib/python2.7/dist-packages/dask/base.py", line 78, in compute
    return compute(self, **kwargs)[0]
  File "/usr/local/lib/python2.7/dist-packages/dask/base.py", line 171, in compute
    results = get(dsk, keys, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/dask/threaded.py", line 71, in get
    **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/dask/async.py", line 481, in get_async
    raise(remote_exception(res, tb))
dask.async.IOError: Can't read data (Can't open directory)

Traceback
---------
  File "/usr/local/lib/python2.7/dist-packages/dask/async.py", line 263, in execute_task
    result = _execute_task(task, data)
  File "/usr/local/lib/python2.7/dist-packages/dask/async.py", line 245, in _execute_task
    return func(*args2)
  File "/usr/local/lib/python2.7/dist-packages/dask/array/core.py", line 48, in getarray
    c = a[b]
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper (/mnt/tmp/h5py/h5py/_objects.c:2687)
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper (/mnt/tmp/h5py/h5py/_objects.c:2645)
  File "/usr/local/lib/python2.7/dist-packages/h5py-2.6.0-py2.7-linux-x86_64.egg/h5py/_hl/dataset.py", line 494, in __getitem__
    self.id.read(mspace, fspace, arr, mtype, dxpl=self._dxpl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper (/mnt/tmp/h5py/h5py/_objects.c:2687)
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper (/mnt/tmp/h5py/h5py/_objects.c:2645)
  File "h5py/h5d.pyx", line 181, in h5py.h5d.DatasetID.read (/mnt/tmp/h5py/h5py/h5d.c:3245)
  File "h5py/_proxy.pyx", line 130, in h5py._proxy.dset_rw (/mnt/tmp/h5py/h5py/_proxy.c:1860)
  File "h5py/_proxy.pyx", line 84, in h5py._proxy.H5PY_H5Dread (/mnt/tmp/h5py/h5py/_proxy.c:1508)
```

**Comment by axeltidemann** [comment]
Locally I had `h5py==2.5.0`, on the AWS instance `2.6.0`. Downgrading to `2.5.0` solved the problem.
