### ISSUE TITLE
read_csv does not find single file without wildcard:

### ISSUE THREAD

**Issue by grst** [dask/dask#1801]
I try to import a single, large (4GB) tab separated file with `dask.dataframe.read_csv`. 
When not specifying a wildcard, the import fails:

```python
import dask.dataframe as dd
gct = dd.read_csv("../data/gtex/GTEx_Analysis_v6_RNA-seq_RNA-SeQCv1.1.8_gene_rpkm.gct*", sep="\t")
gct.tail()
```
works.

Whereas:
```python
gct = dd.read_csv("../data/gtex/GTEx_Analysis_v6_RNA-seq_RNA-SeQCv1.1.8_gene_rpkm.gct", sep="\t")
gct.tail()
```
```
ERROR:distributed.utils:[Errno 2] No such file or directory: '../data/gtex/GTEx_Analysis_v6_RNA-seq_RNA-SeQCv1.1.8_gene_rpkm.gct'
Traceback (most recent call last):
  File "/pstore/home/sturmg/.local/lib/python3.5/site-packages/distributed/utils.py", line 120, in f
    result[0] = yield gen.maybe_future(func(*args, **kwargs))
  File "/pstore/apps/Anaconda3/2.5.0/lib/python3.5/site-packages/tornado/gen.py", line 1008, in run
    value = future.result()
  File "/pstore/apps/Anaconda3/2.5.0/lib/python3.5/site-packages/tornado/concurrent.py", line 232, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 3, in raise_exc_info
  File "/pstore/apps/Anaconda3/2.5.0/lib/python3.5/site-packages/tornado/gen.py", line 1014, in run
    yielded = self.gen.throw(*exc_info)
  File "/pstore/home/sturmg/.local/lib/python3.5/site-packages/distributed/client.py", line 802, in _gather
    d['traceback'])
  File "/pstore/apps/Anaconda3/2.5.0/lib/python3.5/site-packages/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/pstore/home/sturmg/.local/lib/python3.5/site-packages/dask/bytes/local.py", line 74, in read_block_from_file
    with open(path, 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: '../data/gtex/GTEx_Analysis_v6_RNA-seq_RNA-SeQCv1.1.8_gene_rpkm.gct'
```

**Comment by TomAugspurger** [comment]
Just to make sure, that file does exist?

```python
import os
print(os.path.exists('../data/gtex/GTEx_Analysis_v6_RNA-seq_RNA-SeQCv1.1.8_gene_rpkm.gct'))
```

Does that print True?

**Comment by grst** [comment]
Yes, it does. 
And the dataframe does load correctly, by simply adding the star at the end (or actually at any place)

**Comment by jcrist** [comment]
I'm unable to reproduce, even when using the same filename.

```python
In [1]: import os

In [2]: os.makedirs('data/gtex')

In [3]: os.mkdir('some_other_directory')

In [4]: cd some_other_directory/
/Users/jcrist/some_other_directory

In [5]: import pandas as pd

In [6]: df = pd.util.testing.makeDataFrame()

In [7]: df.to_csv('../data/gtex/GTEx_Analysis_v6_RNA-seq_RNA-SeQCv1.1.8_gene_rpkm.gct', index=False)

In [8]: import dask.dataframe as dd

In [9]: ddf = dd.read_csv('../data/gtex/GTEx_Analysis_v6_RNA-seq_RNA-SeQCv1.1.8_gene_rpkm.gct')

In [10]: ddf.head()
Out[10]:
          A         B         C         D
0  0.730028  1.243584 -0.022278 -0.187488
1  0.016825  0.385334 -0.933742 -0.677404
2 -1.000583  1.535114  0.285497 -0.747311
3  2.025770  0.603058  0.300899 -1.670840
4  0.609985  1.016423 -0.408038  0.406228
```

What OS are you using? Is there any way you can make a [reproducible example](https://stackoverflow.com/help/mcve)? Ideally this is something that I could just run `python your_test_case.py` and reproduce the issue.

**Comment by grst** [comment]
Now failing to reproduce myself - in the same jupyter notebook as before. 
The only thing that I could imagine is that I'm now running on a different host on our HPC. 

Anyway - thanks for your support!
