### ISSUE TITLE
Chunk size issue using basic atop example

### ISSUE THREAD

**Issue by serazing** [dask/dask#1832]
I am trying to build large multi-dimensional arrays from 1d array using atop. I have tried an example that I have found in the API documentation but it raises an error due to the chunk sizes. Was there a previous issue related to this before ?

This is the current version of dask I am using:
```
In [1]: import dask
   ...: import dask.array as da
   ...: import operator
   ...: print dask.__version__
   ...: 
0.12.0+7.g5ebc2ac.dirty
```
Here is the example:
```
In [3]: x = da.arange(10, chunks=(5,))
   ...: y = da.arange(5, chunks=(2,))
   ...: z = da.atop(operator.mul, 'ij', x, 'i', y, 'j', dtype='f8')
   ...: z.compute() 
   ...: 
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-3-54020e1f6b27> in <module>()
      2 y = da.arange(5, chunks=(2,))
      3 z = da.atop(operator.mul, 'ij', x, 'i', y, 'j', dtype='f8')
----> 4 z.compute()

/home/serazin/Code/dask/dask/base.pyc in compute(self, **kwargs)
     76             Extra keywords to forward to the scheduler ``get`` function.
     77         """
---> 78         return compute(self, **kwargs)[0]
     79 
     80     @classmethod

/home/serazin/Code/dask/dask/base.pyc in compute(*args, **kwargs)
    176         dsk = merge(var.dask for var in variables)
    177     keys = [var._keys() for var in variables]
--> 178     results = get(dsk, keys, **kwargs)
    179 
    180     results_iter = iter(results)

/home/serazin/Code/dask/dask/threaded.pyc in get(dsk, result, cache, num_workers, **kwargs)
     67     results = get_async(pool.apply_async, len(pool._pool), dsk, result,
     68                         cache=cache, get_id=_thread_get_id,
---> 69                         **kwargs)
     70 
     71     # Cleanup pools associated to dead threads

/home/serazin/Code/dask/dask/async.pyc in get_async(apply_async, num_workers, dsk, result, cache, get_id, raise_on_exception, rerun_exceptions_locally, callbacks, dumps, loads, **kwargs)
    500                     _execute_task(task, data)  # Re-execute locally
    501                 else:
--> 502                     raise(remote_exception(res, tb))
    503             state['cache'][key] = res
    504             finish_task(dsk, key, state, results, keyorder.get)

ValueError: operands could not be broadcast together with shapes (5,) (2,) 

Traceback
---------
  File "dask/async.py", line 268, in execute_task
    result = _execute_task(task, data)
  File "dask/async.py", line 249, in _execute_task
    return func(*args2)
```

**Comment by jcrist** [comment]
Looks like this example has been broken for a long time (at least back to 0.6.0). Note that an extra axis beforehand makes everything work:

```python
from operator import mul
import dask.array as da

x = da.arange(10, chunks=5)
y = da.arange(5, chunks=2)
z = x * y[:, None]
# is equivalent to
z2 = da.atop(mul, 'ji', x, 'i', y[:, None], 'ji', dtype='f8')
```

**Comment by serazing** [comment]
Thanks, this is a useful trick I didn't know about. I have to figure out to generalize those lines for making Ndarray from N 1darray.

I would have liked to use something concise like:

```
from operator import mul
import dask.array as da

x = da.arange(10, chunks=5)
y = da.arange(5, chunks=2)
z = da.arange(8, chunks=3)
w = da.atop(mul, 'ijk', x, 'i', y, 'j', z, 'k', dtype='f8')
```

Dask is actually able to build the graph but there is the same issue at the computation.

**Comment by shoyer** [comment]
Agreed, this example really should work.

**Comment by mrocklin** [comment]
Currently atop assumes that the chunks of the inputs are already in the shape that the input function expects.  Should we always convert the chunks to the alignment implied by the indexing or should we trust that the user provided function knows what it's doing?

**Comment by shoyer** [comment]
Nevermind, I see why the `operator.mul` example does not work. NumPy arrays don't do broadcasting between vectors with different shapes.

I think it's probably better to avoid rechunking implicitly in `atop`, given that this is intentionally a pretty low level function.

**Comment by mrocklin** [comment]
> I think it's probably better to avoid rechunking implicitly in atop, given that this is intentionally a pretty low level function.

Agreed.  Closing.
