### ISSUE TITLE
BUG: meta-data issue after grouping on latest dask

### ISSUE THREAD

**Issue by jreback** [dask/dask#1844]
```
In [4]: dask.__version__
Out[4]: '0.12.0+48.g4ae1a20'

In [5]: df = pd.DataFrame({'A': [1,1,2,2], 'B':[1,2,3,4], 'C':[1,2,3,4]})
In [7]: ddf = dd.from_pandas(df, npartitions=2)

In [8]: ddf
Out[8]: dd.DataFrame<from_pa..., npartitions=2, divisions=(0, 2, 3)>

In [15]: g = ddf.groupby(['A', 'B']).agg(['count', 'sum'])

In [16]: g
Out[16]: dd.DataFrame<aggrega..., npartitions=1>
```

info breaking
```
In [17]: g.info()
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-17-c4700320b5d3> in <module>()
----> 1 g.info()

C:\dev\dask\dask\dataframe\core.py in info(self, buf, verbose, memory_usage)
   2779         computations = dict(zip(computations.keys(), da.compute(*computations.values())))
   2780
-> 2781         column_template = "{0:<%d} {1}" % (self.columns.str.len().max() + 5)
   2782
   2783         if verbose:

C:\Anaconda\envs\dev\lib\site-packages\pandas-0.19.0+149.gac360e9-py3.5-win-amd64.egg\pandas\core\base.py in __get__(self, instance, owner)
    239             # this ensures that Series.str.<method> is well defined
    240             return self.accessor_cls
--> 241         return self.construct_accessor(instance)
    242
    243     def __set__(self, instance, value):

C:\Anaconda\envs\dev\lib\site-packages\pandas-0.19.0+149.gac360e9-py3.5-win-amd64.egg\pandas\core\strings.py in _make_str_accessor(self)
   1855                 message = ("Can only use .str accessor with Index, not "
   1856                            "MultiIndex")
-> 1857                 raise AttributeError(message)
   1858         return StringMethods(self)
   1859

AttributeError: Can only use .str accessor with Index, not MultiIndex

In [18]: g.reset_index()
Out[18]: dd.DataFrame<reset_i..., npartitions=1>
```

reset_index breaking
```
In [19]: g.reset_index().compute()
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-19-b79cff901706> in <module>()
----> 1 g.reset_index().compute()

C:\dev\dask\dask\base.py in compute(self, **kwargs)
     77             Extra keywords to forward to the scheduler ``get`` function.
     78         """
---> 79         return compute(self, **kwargs)[0]
     80
     81     @classmethod

C:\dev\dask\dask\base.py in compute(*args, **kwargs)
    177         dsk = merge(var.dask for var in variables)
    178     keys = [var._keys() for var in variables]
--> 179     results = get(dsk, keys, **kwargs)
    180
    181     results_iter = iter(results)

C:\dev\dask\dask\threaded.py in get(dsk, result, cache, num_workers, **kwargs)
     74     results = get_async(pool.apply_async, len(pool._pool), dsk, result,
     75                         cache=cache, get_id=_thread_get_id,
---> 76                         **kwargs)
     77
     78     # Cleanup pools associated to dead threads

C:\dev\dask\dask\async.py in get_async(apply_async, num_workers, dsk, result, cache, get_id, raise_on_exception, rerun_exceptions_locally, callbacks, dumps, loads, **kwargs)
    491                     _execute_task(task, data)  # Re-execute locally
    492                 else:
--> 493                     raise(remote_exception(res, tb))
    494             state['cache'][key] = res
    495             finish_task(dsk, key, state, results, keyorder.get)

ValueError: Length mismatch: Expected axis has 4 elements, new values have 3 elements

Traceback
---------
  File "C:\dev\dask\dask\async.py", line 268, in execute_task
    result = _execute_task(task, data)
  File "C:\dev\dask\dask\async.py", line 249, in _execute_task
    return func(*args2)
  File "C:\dev\dask\dask\dataframe\core.py", line 3205, in apply_and_enforce
    return _rename(c, df)
  File "C:\dev\dask\dask\dataframe\core.py", line 3242, in _rename
    df.columns = columns
  File "C:\Anaconda\envs\dev\lib\site-packages\pandas-0.19.0+149.gac360e9-py3.5-win-amd64.egg\pandas\core\generic.py", line 2814, in __setattr__
    return object.__setattr__(self, name, value)
  File "pandas\src\properties.pyx", line 65, in pandas.lib.AxisProperty.__set__ (pandas\lib.c:44872)
  File "C:\Anaconda\envs\dev\lib\site-packages\pandas-0.19.0+149.gac360e9-py3.5-win-amd64.egg\pandas\core\generic.py", line 448, in _set_axis
    self._data.set_axis(axis, labels)
  File "C:\Anaconda\envs\dev\lib\site-packages\pandas-0.19.0+149.gac360e9-py3.5-win-amd64.egg\pandas\core\internals.py", line 2803, in set_axis
    (old_len, new_len))
```

correct / works
```
In [20]: g.compute()
Out[20]:
        C
    count sum
A B
1 1     1   1
  2     1   2
2 3     1   3
  4     1   4
```

**Comment by frol** [comment]
I have bumped into this issue with another workflow; I am using chained `map_partitions` adding new columns, here is the reproduction:

```python
import dask.dataframe
import pandas

ddf = dask.dataframe.from_pandas(pandas.DataFrame({'X': [1,2,3,4,5,6]}), npartitions=3)

def add(df, column):
    df[column['name']] = column['value']
    return df

ddf2 = ddf.map_partitions(add, column={'name': 'A', 'value': 1}).map_partitions(add, column={'name': 'B', 'value': 2})
```

Trying to reach the `B` column now:

```python
ddf2.B.compute()
```

I am receiving this backtrace:

```
.../lib/python3.5/site-packages/dask/base.py in compute(self, **kwargs)
     77             Extra keywords to forward to the scheduler ``get`` function.
     78         """
---> 79         return compute(self, **kwargs)[0]
     80
     81     @classmethod

.../lib/python3.5/site-packages/dask/base.py in compute(*args, **kwargs)
    177         dsk = merge(var.dask for var in variables)
    178     keys = [var._keys() for var in variables]
--> 179     results = get(dsk, keys, **kwargs)
    180
    181     results_iter = iter(results)

.../lib/python3.5/site-packages/dask/threaded.py in get(dsk, result, cache, num_workers, **kwargs)
     74     results = get_async(pool.apply_async, len(pool._pool), dsk, result,
     75                         cache=cache, get_id=_thread_get_id,
---> 76                         **kwargs)
     77
     78     # Cleanup pools associated to dead threads

.../lib/python3.5/site-packages/dask/async.py in get_async(apply_async, num_workers, dsk, result, cache, get_id, raise_on_exception, rerun_exceptions_locally, callbacks, dumps, loads, **kwargs)
    491                     _execute_task(task, data)  # Re-execute locally
    492                 else:
--> 493                     raise(remote_exception(res, tb))
    494             state['cache'][key] = res
    495             finish_task(dsk, key, state, results, keyorder.get)

ValueError: Length mismatch: Expected axis has 3 elements, new values have 2 elements

Traceback
---------
  File ".../lib/python3.5/site-packages/dask/async.py", line 268, in execute_task
    result = _execute_task(task, data)
  File ".../lib/python3.5/site-packages/dask/async.py", line 249, in _execute_task
    return func(*args2)
  File ".../lib/python3.5/site-packages/dask/dataframe/core.py", line 3205, in apply_and_enforce
    return _rename(c, df)
  File ".../lib/python3.5/site-packages/dask/dataframe/core.py", line 3242, in _rename
    df.columns = columns
  File ".../lib/python3.5/site-packages/pandas/core/generic.py", line 2757, in __setattr__
    return object.__setattr__(self, name, value)
  File "pandas/src/properties.pyx", line 65, in pandas.lib.AxisProperty.__set__ (pandas/lib.c:46241)
  File ".../lib/python3.5/site-packages/pandas/core/generic.py", line 448, in _set_axis
    self._data.set_axis(axis, labels)
  File ".../lib/python3.5/site-packages/pandas/core/internals.py", line 2802, in set_axis
    (old_len, new_len))
```

Computing the whole dataframe at once (`ddf2.compute()`) and `ddf2.A.compute()` work just fine!

This is a regression in Dask 0.12.0+ (I have tested against the master branch and the bug is still there); Dask 0.11.0 and 0.11.1 are not affected and work as expected.

**Comment by mrocklin** [comment]
I believe that these are two different issues.  

@jreback has an issue with dask.dataframe assuming that all indexes are single-indexes rather than multi-indexes

@frol is using a mutating function within dask.dataframe, which is generally not supported.  I recommend starting the add function with a `df = df.copy()` to see if that resolves the problem.

**Comment by frol** [comment]
@mrocklin `df.copy(deep=False)` works! Thank you!

**Comment by alexcohaniuc** [comment]
any update on @jreback issue?

**Comment by mrocklin** [comment]
No update from me.  If you want to dive in here @alexcohaniuc we could use the help :)
