### ISSUE TITLE
Issue with parquet and categories

### ISSUE THREAD

**Issue by patcpsc** [dask/dask#1905]
I'm not 100% sure if this is a bug or me just not knowing how to use dask, but I'm getting the following bug,  Note the "astype('category')" seems to be the trigger here; pdf['y'] = pdf['y'].astype('f8') does not trigger the problem.

```python
import pandas as pd
import dask.dataframe as da

pd.__version__
# '0.19.2'
import dask
dask.__version__
# '0.13.0'

df = pd.DataFrame({'ID': ['a', 'b', 'a'],'y':[1,2,3]},index=None)
ddf = da.from_pandas(df,npartitions=2)

ddf.to_parquet("/tmp/bug.parq/")

pdf = da.read_parquet('/tmp/bug.parq/')

pdf['ID'] = pdf['ID'].astype('category')
# pdf['y'] = pdf['y'] * 20

pdf.head(2)

pdf.to_parquet('/tmp/bug-write.parq/')
```

Other than this it's running python3.5 in a jupyter web notebook.

This gives me:

```
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
/home/pcaldon/ruleopt/venv/lib/python3.5/site-packages/dask/dataframe/utils.py in raise_on_meta_error(funcname)
    153     try:
--> 154         yield
    155     except Exception as e:

[ ...  lots of trace ... ]

ValueError: Metadata inference failed in `reset_index`.

Original error is below:
------------------------
IndexError('index 0 is out of bounds for axis 0 with size 0',)

Traceback:
---------
  File "/home/pcaldon/ruleopt/venv/lib/python3.5/site-packages/dask/dataframe/utils.py", line 154, in raise_on_meta_error
    yield
  File "/home/pcaldon/ruleopt/venv/lib/python3.5/site-packages/dask/dataframe/core.py", line 2952, in _emulate
    return func(*_extract_meta(args, True), **_extract_meta(kwargs, True))
  File "/home/pcaldon/ruleopt/venv/lib/python3.5/site-packages/dask/dataframe/core.py", line 2936, in _extract_meta
    return tuple([_extract_meta(_x, nonempty) for _x in x])
  File "/home/pcaldon/ruleopt/venv/lib/python3.5/site-packages/dask/dataframe/core.py", line 2936, in <listcomp>
    return tuple([_extract_meta(_x, nonempty) for _x in x])
  File "/home/pcaldon/ruleopt/venv/lib/python3.5/site-packages/dask/dataframe/core.py", line 2932, in _extract_meta
    return x._meta_nonempty if nonempty else x._meta
  File "/home/pcaldon/ruleopt/venv/lib/python3.5/site-packages/dask/dataframe/core.py", line 256, in _meta_nonempty
    return meta_nonempty(self._meta)
  File "/home/pcaldon/ruleopt/venv/lib/python3.5/site-packages/dask/dataframe/utils.py", line 339, in meta_nonempty
    for i, c in enumerate(x.columns)}
  File "/home/pcaldon/ruleopt/venv/lib/python3.5/site-packages/dask/dataframe/utils.py", line 339, in <dictcomp>
    for i, c in enumerate(x.columns)}
  File "/home/pcaldon/ruleopt/venv/lib/python3.5/site-packages/dask/dataframe/utils.py", line 314, in _nonempty_series
    entry = s.cat.categories[0]
  File "/home/pcaldon/ruleopt/venv/lib/python3.5/site-packages/pandas/indexes/base.py", line 1423, in __getitem__
    return getitem(key)


```

**Comment by jcrist** [comment]
Thanks for the good issue report. This was a problem with categorical metadata handling. Fixed by #1907. Your test case above now runs fine:

```python
In [2]: # %load foo.py
   ...: import pandas as pd
   ...: import dask.dataframe as da
   ...: import dask, pandas, fastparquet
   ...:
   ...: df = pd.DataFrame({'ID': ['a', 'b', 'a'],
   ...:                    'y': [1, 2, 3]},
   ...:                   index=None)
   ...: ddf = da.from_pandas(df, npartitions=2)
   ...:
   ...: ddf.to_parquet("/tmp/bug.parq/")
   ...:
   ...: pdf = da.read_parquet('/tmp/bug.parq/')
   ...:
   ...: pdf['ID'] = pdf['ID'].astype('category')
   ...: pdf.head(2)
   ...:
   ...: pdf.to_parquet('/tmp/bug-write.parq/')
   ...:

In [3]: pdf.compute()
Out[3]:
      ID  y
index
0      a  1
1      b  2
2      a  3
```
