### ISSUE TITLE
Errors reading CSV file into Dask dataframe

### ISSUE THREAD

**Issue by koverholt** [dask/dask#1921]
For this data file: http://stat-computing.org/dataexpo/2009/2000.csv.bz2

With these column names and dtypes:

```python
cols = ['year', 'month', 'day_of_month', 'day_of_week', 'deptime', 'crs_deptime', 'arrtime', 
        'crs_arrtime', 'unique_carrier', 'flight_num', 'tail_num', 'actual_elapsed_time',
        'crs_elapsed_time', 'air_time', 'arrdelay', 'depdelay', 'origin', 'dest', 'distance', 
        'taxi_in', 'taxi_out', 'cancelled', 'cancellation_code', 'diverted', 'carrier_delay',
        'weather_delay', 'nas_delay', 'security_delay', 'late_aircraft_delay']

dtypes = {'cancellation_code': object, 'taxi_in': float, 'taxi_out': float, 'cancelled': bool,
          'diverted': bool, 'carrier_delay': float, 'weather_delay': float, 'nas_delay': float,
          'security_delay': float, 'late_aircraft_delay': float, 'tail_num': object,
          'crs_deptime': float, 'crs_arrtime': float, 'flight_num': float, 'crs_elapsed_time': float,
          'distance': float}
```

I can read this CSV file with pandas without errors:

```python
>>> import pandas as pd
>>> data = pd.read_csv('data/2000.csv', header=0, names=cols, dtype=dtypes)
```

But I get errors when reading it into a Dask dataframe:

```python
>>> import dask.dataframe as dd
>>> data = dd.read_csv('data/2000.csv', header=0, names=cols, dtype=dtypes)
>>> data.head()
[##########                              ] | 25% Completed |  2.6s

ValueErrorTraceback (most recent call last)
<ipython-input-30-142c16972e3f> in <module>()
----> 1 get_ipython().run_cell_magic(u'time', u'', u'data.head()')

/projects/tanya/OnTime/envs/default/lib/python2.7/site-packages/IPython/core/interactiveshell.pyc in run_cell_magic(self, magic_name, line, cell)
   2113             magic_arg_s = self.var_expand(line, stack_depth)
   2114             with self.builtin_trap:
-> 2115                 result = fn(magic_arg_s, cell)
   2116             return result
   2117 

<decorator-gen-59> in time(self, line, cell, local_ns)

/projects/tanya/OnTime/envs/default/lib/python2.7/site-packages/IPython/core/magic.pyc in <lambda>(f, *a, **k)
    186     # but it's overkill for just that one bit of state.
    187     def magic_deco(arg):
--> 188         call = lambda f, *a, **k: f(*a, **k)
    189 
    190         if callable(arg):

/projects/tanya/OnTime/envs/default/lib/python2.7/site-packages/IPython/core/magics/execution.pyc in time(self, line, cell, local_ns)
   1174         if mode=='eval':
   1175             st = clock2()
-> 1176             out = eval(code, glob, local_ns)
   1177             end = clock2()
   1178         else:

<timed eval> in <module>()

/projects/tanya/OnTime/envs/default/lib/python2.7/site-packages/dask/dataframe/core.pyc in head(self, n, npartitions, compute)
    496 
    497         if compute:
--> 498             result = result.compute()
    499         return result
    500 

/projects/tanya/OnTime/envs/default/lib/python2.7/site-packages/dask/base.pyc in compute(self, **kwargs)
     84             Extra keywords to forward to the scheduler ``get`` function.
     85         """
---> 86         return compute(self, **kwargs)[0]
     87 
     88     @classmethod

/projects/tanya/OnTime/envs/default/lib/python2.7/site-packages/dask/base.pyc in compute(*args, **kwargs)
    177         dsk = merge(var.dask for var in variables)
    178     keys = [var._keys() for var in variables]
--> 179     results = get(dsk, keys, **kwargs)
    180 
    181     results_iter = iter(results)

/projects/tanya/OnTime/envs/default/lib/python2.7/site-packages/dask/threaded.pyc in get(dsk, result, cache, num_workers, **kwargs)
     56     results = get_async(pool.apply_async, len(pool._pool), dsk, result,
     57                         cache=cache, queue=queue, get_id=_thread_get_id,
---> 58                         **kwargs)
     59 
     60     return results

/projects/tanya/OnTime/envs/default/lib/python2.7/site-packages/dask/async.pyc in get_async(apply_async, num_workers, dsk, result, cache, queue, get_id, raise_on_exception, rerun_exceptions_locally, callbacks, **kwargs)
    479                     _execute_task(task, data)  # Re-execute locally
    480                 else:
--> 481                     raise(remote_exception(res, tb))
    482             state['cache'][key] = res
    483             finish_task(dsk, key, state, results, keyorder.get)

ValueError: Cannot convert NA to integer

Traceback
---------
  File "/projects/tanya/OnTime/envs/default/lib/python2.7/site-packages/dask/async.py", line 263, in execute_task
    result = _execute_task(task, data)
  File "/projects/tanya/OnTime/envs/default/lib/python2.7/site-packages/dask/async.py", line 245, in _execute_task
    return func(*args2)
  File "/projects/tanya/OnTime/envs/default/lib/python2.7/site-packages/dask/dataframe/csv.py", line 49, in bytes_read_csv
    coerce_dtypes(df, dtypes)
  File "/projects/tanya/OnTime/envs/default/lib/python2.7/site-packages/dask/dataframe/csv.py", line 73, in coerce_dtypes
    df[c] = df[c].astype(dtypes[c])
  File "/projects/tanya/OnTime/envs/default/lib/python2.7/site-packages/pandas/core/generic.py", line 3054, in astype
    raise_on_error=raise_on_error, **kwargs)
  File "/projects/tanya/OnTime/envs/default/lib/python2.7/site-packages/pandas/core/internals.py", line 3168, in astype
    return self.apply('astype', dtype=dtype, **kwargs)
  File "/projects/tanya/OnTime/envs/default/lib/python2.7/site-packages/pandas/core/internals.py", line 3035, in apply
    applied = getattr(b, f)(**kwargs)
  File "/projects/tanya/OnTime/envs/default/lib/python2.7/site-packages/pandas/core/internals.py", line 462, in astype
    values=values, **kwargs)
  File "/projects/tanya/OnTime/envs/default/lib/python2.7/site-packages/pandas/core/internals.py", line 505, in _astype
    values = _astype_nansafe(values.ravel(), dtype, copy=True)
  File "/projects/tanya/OnTime/envs/default/lib/python2.7/site-packages/pandas/types/cast.py", line 531, in _astype_nansafe
    raise ValueError('Cannot convert NA to integer')
```

**Comment by jcrist** [comment]
What version of dask/pandas are you using? On the recent releases (and possibly earlier ones) I'm unable to reproduce:

```python
In [1]: %paste
cols = ['year', 'month', 'day_of_month', 'day_of_week', 'deptime', 'crs_deptime', 'arrtime',
        'crs_arrtime', 'unique_carrier', 'flight_num', 'tail_num', 'actual_elapsed_time',
        'crs_elapsed_time', 'air_time', 'arrdelay', 'depdelay', 'origin', 'dest', 'distance',
        'taxi_in', 'taxi_out', 'cancelled', 'cancellation_code', 'diverted', 'carrier_delay',
        'weather_delay', 'nas_delay', 'security_delay', 'late_aircraft_delay']

dtypes = {'cancellation_code': object, 'taxi_in': float, 'taxi_out': float, 'cancelled': bool,
          'diverted': bool, 'carrier_delay': float, 'weather_delay': float, 'nas_delay': float,
          'security_delay': float, 'late_aircraft_delay': float, 'tail_num': object,
          'crs_deptime': float, 'crs_arrtime': float, 'flight_num': float, 'crs_elapsed_time': float,
          'distance': float}

## -- End pasted text --

In [2]: import dask.dataframe as dd

In [3]: data = dd.read_csv('2000.csv', header=0, names=cols, dtype=dtypes)

In [4]: _ = data.head()

In [5]: _ = data.tail()

In [6]: res = data.compute()

In [7]: len(res)
Out[7]: 5683047
```

If you're on a recent-ish version, the error message you're getting indicates a dtype mismatch between the first `sample` bytes (using the name of the keyword to ``dd.read_csv``) and the rest of the file. Some column is inferred to be an integer by the head of the file, but later on turns out to be a float. To fix, either specify the dtype of the offending column(s), or increase the `sample` size passed to `dd.read_csv`.

**Comment by koverholt** [comment]
Thanks for the troubleshooting info. Updating to Dask 0.13.0 works as you mentioned, I should have checked that first but I was using 0.11.0, and I remember running into a similar issue that needed a larger `sample` size before. Much appreciated!
