### ISSUE TITLE
dask.bag test failure on OS X

### ISSUE THREAD

**Issue by pitrou** [dask/dask#2002]
Got this on an OS X machine where I ran the test suite out of curiosity (with Python 3.6):
```
____________________________________________________________________________ test_errors ____________________________________________________________________________
Traceback (most recent call last):
  File "/Users/buildbot/antoine/dask/dask/bag/tests/test_text.py", line 51, in test_errors
    with filetexts({'.test.foo': 'Jos\xe9\nAlice'}):
  File "/Users/buildbot/miniconda3/envs/antoine-dask/lib/python3.6/contextlib.py", line 82, in __enter__
    return next(self.gen)
  File "/Users/buildbot/antoine/dask/dask/utils.py", line 218, in filetexts
    f.write(text)
UnicodeEncodeError: 'ascii' codec can't encode character '\xe9' in position 3: ordinal not in range(128)
```

**Comment by mrocklin** [comment]
I wasn't able to replicate this

**Comment by pitrou** [comment]
Ok, this is because the locale on that machine is the default ASCII locale on Unix. See how the standard streams also use ASCII:
```
In [4]: locale.getpreferredencoding()
Out[4]: 'US-ASCII'

In [6]: sys.stdin
Out[6]: <_io.TextIOWrapper name='<stdin>' mode='r' encoding='US-ASCII'>

In [7]: sys.stdout
Out[7]: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='US-ASCII'>
```
