### ISSUE TITLE
dask.read_csv FileNotFoundError(fn) on EC2 

### ISSUE THREAD

**Issue by data-steve** [dask/dask#2027]
Hi I'm using py27 anaconda-4.1.1 on an EC2 instance and trying to use Dask 0.10.0 and Pandas 0.19.2 to read in a folder of PSV (pipe-delimited csvs) files. These files were written out from Spark into S3 bucket and then I `aws s3 cp`-ed them over. (Still figuring out admin rights for reading directly from s3.)

Anyway, the error is with the data in EC2 already. From EC2 cmd line. I type `python` to get python interpreter.

```
import dask.dataframe as dd
import pandas as pd
df = dd.read_csv('~/data/part-00*.csv', sep="|")
```

And then I get this error.

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/mnt/var/lib/anaconda2/lib/python2.7/site-packages/dask/dataframe/csv.py", line 186, in read_csv
    **(storage_options or {}))
  File "/mnt/var/lib/anaconda2/lib/python2.7/site-packages/dask/bytes/core.py", line 76, in read_bytes
    **kwargs)
  File "/mnt/var/lib/anaconda2/lib/python2.7/site-packages/dask/bytes/local.py", line 23, in read_bytes
    sample, first = read_bytes(filenames[0], delimiter, not_zero,
IndexError: list index out of range
```

If I try the same thing but with only one file: `df = dd.read_csv('~/data/part-001.csv', sep="|")` I get this error:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/mnt/var/lib/anaconda2/lib/python2.7/site-packages/dask/dataframe/csv.py", line 186, in read_csv
    **(storage_options or {}))
  File "/mnt/var/lib/anaconda2/lib/python2.7/site-packages/dask/bytes/core.py", line 76, in read_bytes
    **kwargs)
  File "/mnt/var/lib/anaconda2/lib/python2.7/site-packages/dask/bytes/local.py", line 30, in read_bytes
    raise FileNotFoundError(fn)
IOError: ~/data/part-001.csv
```

But if I use just regular old `pandas.read_csv` on the same file it reads in fine.

```
df = pd.read_csv('~/data/part-001.csv', sep="|")
df.columns
>>>Index([...,....,])
```

Would appreciate help here.

**Comment by martindurant** [comment]
Would you mind trying without the tilde `~` character?

**Comment by data-steve** [comment]
fixed! sorry if that seemed so simple I should have seen it. 

How do I get the dask.dataframe into pandas? I thought there was something like a `to_pandas()` method at end of `read_csv`.

Need rest of my pipeline will work as is now. I'm interested in re-writing for dask later, but need to baby-step it.

**Comment by data-steve** [comment]
also, based on https://github.com/dask/fastparquet/issues/21 it appears that the `read_parquet()` is not available for py27, correct?

**Comment by martindurant** [comment]
`.compute()` would pull the whole dataframe into a local pandas version.

fastparquet does not work with py27 in master and on pypi (pip), but the conda packages are not yet built.

**Comment by data-steve** [comment]
thanks!

**Comment by data-steve** [comment]
ok, tried this

```
df = dd.read_csv("/home/steven.simpson/data/part*.csv", sep="|").compute()
```

and got this

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/mnt/var/lib/anaconda2/lib/python2.7/site-packages/dask/base.py", line 86, in compute
    return compute(self, **kwargs)[0]
  File "/mnt/var/lib/anaconda2/lib/python2.7/site-packages/dask/base.py", line 179, in compute
    results = get(dsk, keys, **kwargs)
  File "/mnt/var/lib/anaconda2/lib/python2.7/site-packages/dask/threaded.py", line 57, in get
    **kwargs)
  File "/mnt/var/lib/anaconda2/lib/python2.7/site-packages/dask/async.py", line 484, in get_async
    raise(remote_exception(res, tb))
dask.async.CParserError: Error tokenizing data. C error: Expected 6 fields in line 557, saw 7


Traceback
---------
  File "/mnt/var/lib/anaconda2/lib/python2.7/site-packages/dask/async.py", line 267, in execute_task
    result = _execute_task(task, data)
  File "/mnt/var/lib/anaconda2/lib/python2.7/site-packages/dask/async.py", line 249, in _execute_task
    return func(*args2)
  File "/mnt/var/lib/anaconda2/lib/python2.7/site-packages/dask/dataframe/csv.py", line 43, in bytes_read_csv
    df = pd.read_csv(bio, **kwargs)
  File "/mnt/var/lib/anaconda2/lib/python2.7/site-packages/pandas/io/parsers.py", line 646, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/mnt/var/lib/anaconda2/lib/python2.7/site-packages/pandas/io/parsers.py", line 401, in _read
    data = parser.read()
  File "/mnt/var/lib/anaconda2/lib/python2.7/site-packages/pandas/io/parsers.py", line 939, in read
    ret = self._engine.read(nrows)
  File "/mnt/var/lib/anaconda2/lib/python2.7/site-packages/pandas/io/parsers.py", line 1508, in read
    data = self._reader.read(nrows)
  File "pandas/parser.pyx", line 848, in pandas.parser.TextReader.read (pandas/parser.c:10415)
  File "pandas/parser.pyx", line 870, in pandas.parser.TextReader._read_low_memory (pandas/parser.c:10691)
  File "pandas/parser.pyx", line 924, in pandas.parser.TextReader._read_rows (pandas/parser.c:11437)
  File "pandas/parser.pyx", line 911, in pandas.parser.TextReader._tokenize_rows (pandas/parser.c:11308)
  File "pandas/parser.pyx", line 2024, in pandas.parser.raise_parser_error (pandas/parser.c:27037)
```

**Comment by martindurant** [comment]
This suggests that the files may not be consistent with one-another in their number of columns, or that one or more files have corrupted lines. It is hard to say more from the information above.

**Comment by martindurant** [comment]
PS: I am attempting to build py27 conda packages for fastparquet now https://github.com/conda-forge/fastparquet-feedstock/pull/6

**Comment by data-steve** [comment]
yeah these files contain text excerpts and regexes among other things, so was hoping the `|` would help with parsing. Maybe need more uncommon character with that?

Or if I keep them in dask and do the typical pandas operations up until i hit my sklearn parts, do you think dask-learn would keep the consistency going?

**Comment by martindurant** [comment]
It is probably best to build a solid ingestion - with appropriate arguments to read_csv (there are many), or by more custom code with dask.delayed - before making a consistent dataframe and then processing further on that. 
A very unique separator might be enough; it can be a multi-character or reg-ex itself, but that is probably slower to run.

**Comment by data-steve** [comment]
any examples of the type of solution you're suggesting: ie, `more custom code with dask.delayed` ?

**Comment by martindurant** [comment]
Here is [one example](https://gist.github.com/mrocklin/e7b7b3a65f2835cda813096332ec73ca) and some [general description](http://dask.pydata.org/en/latest/delayed-collections.html)

**Comment by data-steve** [comment]
thanks!
