### ISSUE TITLE
 AttributeError: 'tuple' object has no attribute 'groupby

### ISSUE THREAD

**Issue by LostInOverflow** [dask/dask#2040]
When I create a `DataFrame`:

```python
df = dataframe.from_pandas(
    pd.DataFrame({"x": range(10), "y": ["a"] * 5 + ["b"] * 5, "z": 1}), 5)
```

And try to set index: with the same number of partitions

```
df.set_index("x", divisions=[0, 2, 4, 6, 8, 10], sorted=True).groupby("y").count().compute()
```

it works as expected. But if number of partitions differs:

```
df.set_index("x", divisions=[0, 2, 5, 8, 10, 12, 14], sorted=True).groupby("y").count().compute()
```

I get confusing exception shown below:

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-205-e8ff0304bc2c> in <module>()
----> 1 df.set_index("x", divisions=[0, 2, 5, 8, 10, 12, 14], sorted=True).groupby("y").count().compute()

/path/to/python3.6/site-packages/dask/base.py in compute(self, **kwargs)
     92             Extra keywords to forward to the scheduler ``get`` function.
     93         """
---> 94         (result,) = compute(self, traverse=False, **kwargs)
     95         return result
     96 

/path/to/python3.6/site-packages/dask/base.py in compute(*args, **kwargs)
    199     dsk = collections_to_dsk(variables, optimize_graph, **kwargs)
    200     keys = [var._keys() for var in variables]
--> 201     results = get(dsk, keys, **kwargs)
    202 
    203     results_iter = iter(results)

/path/to/python3.6/site-packages/dask/threaded.py in get(dsk, result, cache, num_workers, **kwargs)
     74     results = get_async(pool.apply_async, len(pool._pool), dsk, result,
     75                         cache=cache, get_id=_thread_get_id,
---> 76                         **kwargs)
     77 
     78     # Cleanup pools associated to dead threads

/path/to/python3.6/site-packages/dask/async.py in get_async(apply_async, num_workers, dsk, result, cache, get_id, raise_on_exception, rerun_exceptions_locally, callbacks, dumps, loads, **kwargs)
    498                     _execute_task(task, data)  # Re-execute locally
    499                 else:
--> 500                     raise(remote_exception(res, tb))
    501             state['cache'][key] = res
    502             finish_task(dsk, key, state, results, keyorder.get)

AttributeError: 'tuple' object has no attribute 'groupby'

Traceback
---------
  File "/path/to/python3.6/site-packages/dask/async.py", line 266, in execute_task
    result = _execute_task(task, data)
  File "/path/to/python3.6/site-packages/dask/async.py", line 247, in _execute_task
    return func(*args2)
  File "/path/to/python3.6/site-packages/dask/compatibility.py", line 47, in apply
    return func(*args, **kwargs)
  File "/path/to/python3.6/site-packages/dask/dataframe/groupby.py", line 175, in _apply_chunk
    g = _groupby_raise_unaligned(df, by=index)
  File "/path/to/python3.6/site-packages/dask/dataframe/groupby.py", line 133, in _groupby_raise_unaligned
    return df.groupby(**kwargs)
```
Versions

- Python                     3.6.0 
- pandas                    0.19.2
- dask                        0.14.0

**Comment by mrocklin** [comment]
Replicated.  Thanks for the excellent bug report @LostInOverflow .  

I'm actually looking at shuffling / groupbys / set_index now, so this is good timing.

**Comment by mrocklin** [comment]
Digging into this now.  It looks like this is only an issue in the `sorted=True` case.  In this case it looks like we are defining the `divisions=` keyword somewhat differently, which is causing some confusion.  

When using sorted=True we state that we know that the data is already sorted by the new index.  In these cases we can also state the known values of those divisions along the index using the divisions= keyword.  This is an entirely different meaning from how we usually use the divisions= keyword (which is usually "this is what I want my divisions to look like").  This double meaning of the same keyword is obviously an issue.  

Short term @LostInOverflow you probably want this:

```python
df.set_index('x', sorted=True).repartition(divisions=...)
```

**Comment by LostInOverflow** [comment]
Thank you so much @mrocklin!
