### ISSUE TITLE
Saving pivot_table to parquet is unintuitive

### ISSUE THREAD

**Issue by keiv-fly** [dask/dask#2052]
Creating a pivot_table and saving it to parquet file is unintuitive:

```
ddf = dd.from_pandas(df,2)
ddf = ddf.categorize("Field")
ddf = ddf.pivot_table(values="Value", index="Index", columns="Field")
ddf.columns = list(ddf.columns)
ddf = ddf.reset_index()
ddf['index'] = ddf.index.astype('int64')
dd.to_parquet("1.parq", ddf)
```

Without categorize the pivot_table throws an error.
And without 
```
ddf.columns = list(ddf.columns)
ddf = ddf.reset_index()
ddf['index'] = ddf.index.astype('int64')
```
Index column is not saved in the parquet file.

Full code:
```
import dask.dataframe as dd
import pandas as pd


df=pd.DataFrame()
df["Index"]=[1,2,3,1,2,3]
df["Field"]=["A","A","A","B","B","B"]
df["Value"]=[10,20,30,100,120,130]
df

   Index Field  Value
0      1     A     10
1      2     A     20
2      3     A     30
3      1     B    100
4      2     B    120
5      3     B    130


ddf = dd.from_pandas(df,2)
ddf = ddf.categorize("Field")
ddf = ddf.pivot_table(values="Value", index="Index", columns="Field")
ddf.columns = list(ddf.columns)
ddf = ddf.reset_index()
ddf['index'] = ddf.index.astype('int64')
dd.to_parquet("1.parq", ddf)

dd.read_parquet("1.parq").compute()
```

**Comment by martindurant** [comment]
Issues: pivot_table() produces output where the columns are a CategoricalIndex, and the idex type is Object, even though the values are int64.

**Comment by toarchkumar** [comment]
Not sure if entirely related, but pivot_table has issues saving using to_csv and to_hdf because the index isn't present as original dataframe.

For instance:

If I read_sql_table as such:

`dask.set_options(get=dask.async.get_sync) ##Just for testing`
`get = dd.read_sql_table('DATA_TABLE', 'SQL_SERVER_URI', index_col='ACCOUNT_KEY', npartitions=1)`

Whose table looks like:

|| CATEGORY | VALUE |
|-|-------------|---------|
|ACCOUNT_KEY|||
|1            | 222|      1|
|1          |  222|      1|
|1        |   223 |     1|
|2        |    223  |    1|
|2       |     224   |   1|
|2      |      224    |  1|
|2     |       224     | 1|

Then I do pivot_table:

`get['CATEGORY'] = get['CATEGORY'].astype('category')`
`get['CATEGORY'] = get['CATEGORY'].cat.as_known()`
`get = get.pivot_table(index='ACCOUNT_KEY', columns='CATEGORY', values='VALUE', aggfunc='count')`

The pivot_table works, but index 'ACCOUNT_KEY' is gone, and this happens in pandas too but it doesn't cause issues when saving out.

Trying to save it to csv:

`get.to_csv('Test_*.csv', index=False)`

I get the following error quoted below. The original solution doesn't seem to help here because it seems to be looking for the index 'ACCOUNT_KEY' not 'index'. Maybe pandas.DataFrame.reindex would help?

> Traceback (most recent call last):
  File "C:\Users\akumar2\AppData\Local\Continuum\Anaconda3\lib\site-packages\pandas\indexes\base.py", line 2134, in get_loc
    return self._engine.get_loc(key)
  File "pandas\index.pyx", line 132, in pandas.index.IndexEngine.get_loc (pandas\index.c:4433)
  File "pandas\index.pyx", line 154, in pandas.index.IndexEngine.get_loc (pandas\index.c:4279)
  File "pandas\src\hashtable_class_helper.pxi", line 732, in pandas.hashtable.PyObjectHashTable.get_item (pandas\hashtable.c:13742)
  File "pandas\src\hashtable_class_helper.pxi", line 740, in pandas.hashtable.PyObjectHashTable.get_item (pandas\hashtable.c:13696)
KeyError: 'ACCOUNT_KEY'

> During handling of the above exception, another exception occurred:

> Traceback (most recent call last):
  File "test.py", line 59, in <module>
    main()
  File "test.py", line 56, in main
    get.to_csv('Test_*.csv', index=False)
  File "C:\Users\akumar2\AppData\Local\Continuum\Anaconda3\lib\site-packages\dask\dataframe\core.py", line 973, in to_csv
    return to_csv(self, filename, **kwargs)
  File "C:\Users\akumar2\AppData\Local\Continuum\Anaconda3\lib\site-packages\dask\dataframe\io\csv.py", line 448, in to_csv
    delayed(values).compute(get=get)
  File "C:\Users\akumar2\AppData\Local\Continuum\Anaconda3\lib\site-packages\dask\base.py", line 96, in compute
    (result,) = compute(self, traverse=False, **kwargs)
  File "C:\Users\akumar2\AppData\Local\Continuum\Anaconda3\lib\site-packages\dask\base.py", line 203, in compute
    results = get(dsk, keys, **kwargs)
  File "C:\Users\akumar2\AppData\Local\Continuum\Anaconda3\lib\site-packages\dask\async.py", line 569, in get_sync
    raise_on_exception=True, **kwargs)
  File "C:\Users\akumar2\AppData\Local\Continuum\Anaconda3\lib\site-packages\dask\async.py", line 532, in get_async
    fire_task()
  File "C:\Users\akumar2\AppData\Local\Continuum\Anaconda3\lib\site-packages\dask\async.py", line 508, in fire_task
    callback=queue.put)
  File "C:\Users\akumar2\AppData\Local\Continuum\Anaconda3\lib\site-packages\dask\async.py", line 557, in apply_sync
    res = func(*args, **kwds)
  File "C:\Users\akumar2\AppData\Local\Continuum\Anaconda3\lib\site-packages\dask\async.py", line 291, in execute_task
    result = _execute_task(task, data)
  File "C:\Users\akumar2\AppData\Local\Continuum\Anaconda3\lib\site-packages\dask\async.py", line 272, in _execute_task
    return func(*args2)
  File "C:\Users\akumar2\AppData\Local\Continuum\Anaconda3\lib\site-packages\dask\compatibility.py", line 47, in apply
    return func(*args, **kwargs)
  File "C:\Users\akumar2\AppData\Local\Continuum\Anaconda3\lib\site-packages\dask\dataframe\methods.py", line 190, in pivot_count
    values=values, aggfunc='count').astype(np.float64)
  File "C:\Users\akumar2\AppData\Local\Continuum\Anaconda3\lib\site-packages\pandas\tools\pivot.py", line 126, in pivot_table
    grouped = data.groupby(keys)
  File "C:\Users\akumar2\AppData\Local\Continuum\Anaconda3\lib\site-packages\pandas\core\generic.py", line 3991, in groupby
    **kwargs)
  File "C:\Users\akumar2\AppData\Local\Continuum\Anaconda3\lib\site-packages\pandas\core\groupby.py", line 1511, in groupby
    return klass(obj, by, **kwds)
  File "C:\Users\akumar2\AppData\Local\Continuum\Anaconda3\lib\site-packages\pandas\core\groupby.py", line 370, in __init__
    mutated=self.mutated)
  File "C:\Users\akumar2\AppData\Local\Continuum\Anaconda3\lib\site-packages\pandas\core\groupby.py", line 2462, in _get_grouper
    in_axis, name, gpr = True, gpr, obj[gpr]
  File "C:\Users\akumar2\AppData\Local\Continuum\Anaconda3\lib\site-packages\pandas\core\frame.py", line 2059, in __getitem__
    return self._getitem_column(key)
  File "C:\Users\akumar2\AppData\Local\Continuum\Anaconda3\lib\site-packages\pandas\core\frame.py", line 2066, in _getitem_column
    return self._get_item_cache(key)
  File "C:\Users\akumar2\AppData\Local\Continuum\Anaconda3\lib\site-packages\pandas\core\generic.py", line 1386, in _get_item_cache
    values = self._data.get(item)
  File "C:\Users\akumar2\AppData\Local\Continuum\Anaconda3\lib\site-packages\pandas\core\internals.py", line 3543, in get
    loc = self.items.get_loc(item)
  File "C:\Users\akumar2\AppData\Local\Continuum\Anaconda3\lib\site-packages\pandas\indexes\base.py", line 2136, in get_loc
    return self._engine.get_loc(self._maybe_cast_indexer(key))
  File "pandas\index.pyx", line 132, in pandas.index.IndexEngine.get_loc (pandas\index.c:4433)
  File "pandas\index.pyx", line 154, in pandas.index.IndexEngine.get_loc (pandas\index.c:4279)
  File "pandas\src\hashtable_class_helper.pxi", line 732, in pandas.hashtable.PyObjectHashTable.get_item (pandas\hashtable.c:13742)
  File "pandas\src\hashtable_class_helper.pxi", line 740, in pandas.hashtable.PyObjectHashTable.get_item (pandas\hashtable.c:13696)
KeyError: 'ACCOUNT_KEY'

**Comment by zenkzz** [comment]
Hi toarchkumar,

Could you try the following code before saving as csv? These were the lines that solved my parquet problem.

get = get.reset_index()
get['index'] = get.index.astype('int64')

**Comment by toarchkumar** [comment]
Hi zenkzz,

No sorry, it doesn't seem to be the case for to_csv or to_hdf.

```Traceback (most recent call last):
  File "ucp_out.py", line 182, in <module>
    main()
  File "ucp_out.py", line 177, in main
    fetch_data(queries_pivot, 'arch_pivot_potential')
  File "ucp_out.py", line 115, in fetch_data
    ucp_extract_pivot(i, name, 'VALUE', f'ACCOUNT_KEY_{d}', 'CATEGORY', d)
  File "ucp_out.py", line 40, in ucp_extract_pivot
    get.to_hdf(f'data2/{name}.h5', key='index')
  File "C:\Users\akumar2\AppData\Local\Continuum\Anaconda3\lib\site-packages\dask\dataframe\core.py", line 963, in to_hdf
    return to_hdf(self, path_or_buf, key, mode, append, get=get, **kwargs)
  File "C:\Users\akumar2\AppData\Local\Continuum\Anaconda3\lib\site-packages\dask\dataframe\io\hdf.py", line 171, in to_hdf
    _actual_get = effective_get(get, df)
  File "C:\Users\akumar2\AppData\Local\Continuum\Anaconda3\lib\site-packages\dask\utils.py", line 1032, in effective_get
    collection_get = collection._default_get if collection else None
  File "C:\Users\akumar2\AppData\Local\Continuum\Anaconda3\lib\site-packages\dask\dataframe\core.py", line 413, in __len__
    split_every=False).compute()
  File "C:\Users\akumar2\AppData\Local\Continuum\Anaconda3\lib\site-packages\dask\base.py", line 96, in compute
    (result,) = compute(self, traverse=False, **kwargs)
  File "C:\Users\akumar2\AppData\Local\Continuum\Anaconda3\lib\site-packages\dask\base.py", line 203, in compute
    results = get(dsk, keys, **kwargs)
  File "C:\Users\akumar2\AppData\Local\Continuum\Anaconda3\lib\site-packages\dask\threaded.py", line 76, in get
    **kwargs)
  File "C:\Users\akumar2\AppData\Local\Continuum\Anaconda3\lib\site-packages\dask\async.py", line 525, in get_async
    raise(remote_exception(res, tb))
dask.async.KeyError: 'ACCOUNT_KEY'

Traceback
---------
  File "C:\Users\akumar2\AppData\Local\Continuum\Anaconda3\lib\site-packages\dask\async.py", line 291, in execute_task
    result = _execute_task(task, data)
  File "C:\Users\akumar2\AppData\Local\Continuum\Anaconda3\lib\site-packages\dask\async.py", line 272, in _execute_task
    return func(*args2)
  File "C:\Users\akumar2\AppData\Local\Continuum\Anaconda3\lib\site-packages\dask\compatibility.py", line 47, in apply
    return func(*args, **kwargs)
  File "C:\Users\akumar2\AppData\Local\Continuum\Anaconda3\lib\site-packages\dask\dataframe\methods.py", line 196, in pivot_count
    values=values, aggfunc='count').astype(np.float64)
  File "C:\Users\akumar2\AppData\Local\Continuum\Anaconda3\lib\site-packages\pandas\tools\pivot.py", line 126, in pivot_table
    grouped = data.groupby(keys)
  File "C:\Users\akumar2\AppData\Local\Continuum\Anaconda3\lib\site-packages\pandas\core\generic.py", line 3991, in groupby
    **kwargs)
  File "C:\Users\akumar2\AppData\Local\Continuum\Anaconda3\lib\site-packages\pandas\core\groupby.py", line 1511, in groupby
    return klass(obj, by, **kwds)
  File "C:\Users\akumar2\AppData\Local\Continuum\Anaconda3\lib\site-packages\pandas\core\groupby.py", line 370, in __init__
    mutated=self.mutated)
  File "C:\Users\akumar2\AppData\Local\Continuum\Anaconda3\lib\site-packages\pandas\core\groupby.py", line 2462, in _get_grouper
    in_axis, name, gpr = True, gpr, obj[gpr]
  File "C:\Users\akumar2\AppData\Local\Continuum\Anaconda3\lib\site-packages\pandas\core\frame.py", line 2059, in __getitem__
    return self._getitem_column(key)
  File "C:\Users\akumar2\AppData\Local\Continuum\Anaconda3\lib\site-packages\pandas\core\frame.py", line 2066, in _getitem_column
    return self._get_item_cache(key)
  File "C:\Users\akumar2\AppData\Local\Continuum\Anaconda3\lib\site-packages\pandas\core\generic.py", line 1386, in _get_item_cache
    values = self._data.get(item)
  File "C:\Users\akumar2\AppData\Local\Continuum\Anaconda3\lib\site-packages\pandas\core\internals.py", line 3543, in get
    loc = self.items.get_loc(item)
  File "C:\Users\akumar2\AppData\Local\Continuum\Anaconda3\lib\site-packages\pandas\indexes\base.py", line 2136, in get_loc
    return self._engine.get_loc(self._maybe_cast_indexer(key))
  File "pandas\index.pyx", line 132, in pandas.index.IndexEngine.get_loc (pandas\index.c:4433)
  File "pandas\index.pyx", line 154, in pandas.index.IndexEngine.get_loc (pandas\index.c:4279)
  File "pandas\src\hashtable_class_helper.pxi", line 732, in pandas.hashtable.PyObjectHashTable.get_item (pandas\hashtable.c:13742)
  File "pandas\src\hashtable_class_helper.pxi", line 740, in pandas.hashtable.PyObjectHashTable.get_item (pandas\hashtable.c:13696)'```

**Comment by jsignell** [comment]
This seems to be resolved at this point. Closing.
