### ISSUE TITLE
thread.lock serialization error when passing a custom function to a local cluster

### ISSUE THREAD

**Issue by lebedov** [dask/dask#2096]
I'm using dask 0.14.0, distributed 1.16.0, and python 2.7.11 (all installed via conda) on MacOS 10.11.6. When I try to run certain custom Python functions that call various other packages with binary extensions on a local cluster via the following code, 

```python
from distributed import Client, LocalCluster

def func(x):
    # my custom function

args = # some list of args

lc = LocalCluster(10)
c = Client(lc)
results = c.gather(c.map(func, args))
lc.close()
```
I observe the following exception: 
```
Traceback (most recent call last):
  File "process.py", line 151, in <module>
    results = c.gather(c.map(func, args))
  File "/Users/lebedov/anaconda2/lib/python2.7/site-packages/distributed/client.py", line 885, in map
    loose_restrictions, priority=priority, resources=resources)
  File "/Users/lebedov/anaconda2/lib/python2.7/site-packages/distributed/client.py", line 1455, in _graph_to_futures
    'tasks': valmap(dumps_task, dsk3),
  File "/Users/lebedov/anaconda2/lib/python2.7/site-packages/toolz/dicttoolz.py", line 84, in valmap
    rv.update(zip(iterkeys(d), map(func, itervalues(d))))
  File "/Users/lebedov/anaconda2/lib/python2.7/site-packages/distributed/worker.py", line 601, in dumps_task
    return {'function': dumps_function(task[0]),
  File "/Users/lebedov/anaconda2/lib/python2.7/site-packages/distributed/worker.py", line 568, in dumps_function
    b = dumps(func)
  File "/Users/lebedov/anaconda2/lib/python2.7/site-packages/distributed/protocol/pickle.py", line 54, in dumps
    return cloudpickle.dumps(x, protocol=pickle.HIGHEST_PROTOCOL)
  File "/Users/lebedov/anaconda2/lib/python2.7/site-packages/cloudpickle/cloudpickle.py", line 706, in dumps
    cp.dump(obj)
  File "/Users/lebedov/anaconda2/lib/python2.7/site-packages/cloudpickle/cloudpickle.py", line 146, in dump
    return Pickler.dump(self, obj)
  File "/Users/lebedov/anaconda2/lib/python2.7/pickle.py", line 224, in dump
    self.save(obj)
  File "/Users/lebedov/anaconda2/lib/python2.7/pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "/Users/lebedov/anaconda2/lib/python2.7/site-packages/cloudpickle/cloudpickle.py", line 264, in save_function
    self.save_function_tuple(obj)
  File "/Users/lebedov/anaconda2/lib/python2.7/site-packages/cloudpickle/cloudpickle.py", line 317, in save_function_tuple
    save(f_globals)
  File "/Users/lebedov/anaconda2/lib/python2.7/pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "/Users/lebedov/anaconda2/lib/python2.7/pickle.py", line 655, in save_dict
    self._batch_setitems(obj.iteritems())
  File "/Users/lebedov/anaconda2/lib/python2.7/pickle.py", line 687, in _batch_setitems
    save(v)
  File "/Users/lebedov/anaconda2/lib/python2.7/pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "/Users/lebedov/anaconda2/lib/python2.7/site-packages/cloudpickle/cloudpickle.py", line 264, in save_function
    self.save_function_tuple(obj)
  File "/Users/lebedov/anaconda2/lib/python2.7/site-packages/cloudpickle/cloudpickle.py", line 317, in save_function_tuple
    save(f_globals)
  File "/Users/lebedov/anaconda2/lib/python2.7/pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "/Users/lebedov/anaconda2/lib/python2.7/pickle.py", line 655, in save_dict
    self._batch_setitems(obj.iteritems())
  File "/Users/lebedov/anaconda2/lib/python2.7/pickle.py", line 687, in _batch_setitems
    save(v)
  File "/Users/lebedov/anaconda2/lib/python2.7/pickle.py", line 331, in save
    self.save_reduce(obj=obj, *rv)
  File "/Users/lebedov/anaconda2/lib/python2.7/site-packages/cloudpickle/cloudpickle.py", line 604, in save_reduce
    save(state)
  File "/Users/lebedov/anaconda2/lib/python2.7/pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "/Users/lebedov/anaconda2/lib/python2.7/pickle.py", line 655, in save_dict
    self._batch_setitems(obj.iteritems())
  File "/Users/lebedov/anaconda2/lib/python2.7/pickle.py", line 687, in _batch_setitems
    save(v)
  File "/Users/lebedov/anaconda2/lib/python2.7/pickle.py", line 331, in save
    self.save_reduce(obj=obj, *rv)
  File "/Users/lebedov/anaconda2/lib/python2.7/site-packages/cloudpickle/cloudpickle.py", line 604, in save_reduce
    save(state)
  File "/Users/lebedov/anaconda2/lib/python2.7/pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "/Users/lebedov/anaconda2/lib/python2.7/pickle.py", line 655, in save_dict
    self._batch_setitems(obj.iteritems())
  File "/Users/lebedov/anaconda2/lib/python2.7/pickle.py", line 687, in _batch_setitems
    save(v)
  File "/Users/lebedov/anaconda2/lib/python2.7/pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "/Users/lebedov/anaconda2/lib/python2.7/pickle.py", line 606, in save_list
    self._batch_appends(iter(obj))
  File "/Users/lebedov/anaconda2/lib/python2.7/pickle.py", line 642, in _batch_appends
    save(tmp[0])
  File "/Users/lebedov/anaconda2/lib/python2.7/pickle.py", line 331, in save
    self.save_reduce(obj=obj, *rv)
  File "/Users/lebedov/anaconda2/lib/python2.7/site-packages/cloudpickle/cloudpickle.py", line 604, in save_reduce
    save(state)
  File "/Users/lebedov/anaconda2/lib/python2.7/pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "/Users/lebedov/anaconda2/lib/python2.7/pickle.py", line 655, in save_dict
    self._batch_setitems(obj.iteritems())
  File "/Users/lebedov/anaconda2/lib/python2.7/pickle.py", line 687, in _batch_setitems
    save(v)
  File "/Users/lebedov/anaconda2/lib/python2.7/pickle.py", line 331, in save
    self.save_reduce(obj=obj, *rv)
  File "/Users/lebedov/anaconda2/lib/python2.7/site-packages/cloudpickle/cloudpickle.py", line 604, in save_reduce
    save(state)
  File "/Users/lebedov/anaconda2/lib/python2.7/pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "/Users/lebedov/anaconda2/lib/python2.7/pickle.py", line 655, in save_dict
    self._batch_setitems(obj.iteritems())
  File "/Users/lebedov/anaconda2/lib/python2.7/pickle.py", line 687, in _batch_setitems
    save(v)
  File "/Users/lebedov/anaconda2/lib/python2.7/pickle.py", line 306, in save
    rv = reduce(self.proto)
TypeError: can't pickle thread.lock objects
```

There [seems to be a way](https://github.com/dask/distributed/issues/780) to address this when using dask's own interfaces; is there some way to use the serializable lock with a custom function?

The package I'm calling from within my function, incidentally, is [SimpleElastix](https://simpleelastix.github.io/).

**Comment by martindurant** [comment]
SimpleElastix looks like a very nice project, I wish it had been around when I was starting with medical image registration four years ago!

**Comment by mrocklin** [comment]
Are you depending on a `threading.Lock` within your function, either directly or indirectly (such as if the function depended on global variables)?

One way to check this is to try the following:

    cloudpickle.dumps(func)

**Comment by lebedov** [comment]
Apparently there is some indirect dependence (i.e., I'm not using `threading` explicitly); `cloudpickle.dumps(func)` chokes when I run it in the same namespace in which I defined `func()`.

**Comment by mrocklin** [comment]
Yeah, there isn't much that Dask can do here.  The easiest thing to do is
to make the function more easily serializable.  Generally this means making
it self-contained so that it doesn't depend on or affect any variable that
it doesn't take as an explicit input.

**Comment by lebedov** [comment]
dill seems to be able to serialize `threading.Lock` objects, but wrapping the code in a context created with `dask.set_options(func_loads=dill.loads, func_dumps=dill.dumps)` doesn't seem to have any effect (i.e., according to the trace, cloudpickle.dumps is still being used). Am I missing something?

```
with dask.set_options(func_loads=dill.loads, func_dumps=dill.dumps):
    lc = LocalCluster(10)
    c = Client(lc)
    results = c.gather(c.map(func, args))
    lc.close()
```

**Comment by mrocklin** [comment]
The distributed scheduler only uses cloudpickle.

Generally you probably should avoid serializing threading.Lock objects if
possible.

**Comment by lebedov** [comment]
Seems like the problem was a global logger instance that I was accessing in my function.

**Comment by mrocklin** [comment]
Thanks for reporting @lebedov .  Hopefully this issue is helpful for other people in the future.

**Comment by annvakulchyk** [comment]
@lebedov I have the same error I wanted to use `Map.apply()` to log every record which doesn't have all fields properly mapped or has some null values and then create an alert in cloudwatch to spot check them all, is it possible to log the individual record from mapping function or how I can do that?

**Comment by lebedov** [comment]
@annvakulchyk I was able to log by creating  a logger instance inside the function I passed to `Client.map`
