### ISSUE TITLE
Merge/Join with iterable object types

### ISSUE THREAD

**Issue by JasonTam** [dask/dask#2154]
Trying to do a merge or join with an iterable dtype fails when npartitions>1. I guess the shape of the iterable inside the cell is confusing the shape of the partition block.

dask= 0.14.0
```
import pandas as pd
import dask.dataframe as dd

df1 = pd.DataFrame({'col1': range(100),
                    'col2': [[.1, .1]]*100})
df2 = pd.DataFrame({'col1': range(50, 200)})
df3 = df1.merge(df2, how='inner', on='col1')  # works as expected

dd1 = dd.from_pandas(df1, npartitions=2)
dd2 = dd.from_pandas(df2, npartitions=2)
dd3 = dd1.merge(dd2, how='inner', on='col1')  # task planning is ok
dd3.compute()  # fails
```

Error and Traceback:
```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-76-39bd17051944> in <module>()
----> 1 dd3.compute()

/Users/jtam/anaconda2/envs/ipykernel_py3/lib/python3.6/site-packages/dask/base.py in compute(self, **kwargs)
     92             Extra keywords to forward to the scheduler ``get`` function.
     93         """
---> 94         (result,) = compute(self, traverse=False, **kwargs)
     95         return result
     96 

/Users/jtam/anaconda2/envs/ipykernel_py3/lib/python3.6/site-packages/dask/base.py in compute(*args, **kwargs)
    199     dsk = collections_to_dsk(variables, optimize_graph, **kwargs)
    200     keys = [var._keys() for var in variables]
--> 201     results = get(dsk, keys, **kwargs)
    202 
    203     results_iter = iter(results)

/Users/jtam/anaconda2/envs/ipykernel_py3/lib/python3.6/site-packages/dask/threaded.py in get(dsk, result, cache, num_workers, **kwargs)
     74     results = get_async(pool.apply_async, len(pool._pool), dsk, result,
     75                         cache=cache, get_id=_thread_get_id,
---> 76                         **kwargs)
     77 
     78     # Cleanup pools associated to dead threads

/Users/jtam/anaconda2/envs/ipykernel_py3/lib/python3.6/site-packages/dask/async.py in get_async(apply_async, num_workers, dsk, result, cache, get_id, raise_on_exception, rerun_exceptions_locally, callbacks, dumps, loads, **kwargs)
    498                     _execute_task(task, data)  # Re-execute locally
    499                 else:
--> 500                     raise(remote_exception(res, tb))
    501             state['cache'][key] = res
    502             finish_task(dsk, key, state, results, keyorder.get)

ValueError: cannot reshape array of size 38 into shape (1,19)

Traceback
---------
  File "/Users/jtam/anaconda2/envs/ipykernel_py3/lib/python3.6/site-packages/dask/async.py", line 266, in execute_task
    result = _execute_task(task, data)
  File "/Users/jtam/anaconda2/envs/ipykernel_py3/lib/python3.6/site-packages/dask/async.py", line 247, in _execute_task
    return func(*args2)
  File "/Users/jtam/anaconda2/envs/ipykernel_py3/lib/python3.6/site-packages/dask/dataframe/shuffle.py", line 329, in collect
    res = p.get(part)
  File "/Users/jtam/anaconda2/envs/ipykernel_py3/lib/python3.6/site-packages/partd/core.py", line 73, in get
    return self.get([keys], **kwargs)[0]
  File "/Users/jtam/anaconda2/envs/ipykernel_py3/lib/python3.6/site-packages/partd/core.py", line 79, in get
    return self._get(keys, **kwargs)
  File "/Users/jtam/anaconda2/envs/ipykernel_py3/lib/python3.6/site-packages/partd/encode.py", line 30, in _get
    for chunk in raw]
  File "/Users/jtam/anaconda2/envs/ipykernel_py3/lib/python3.6/site-packages/partd/encode.py", line 30, in <listcomp>
    for chunk in raw]
  File "/Users/jtam/anaconda2/envs/ipykernel_py3/lib/python3.6/site-packages/partd/encode.py", line 29, in <listcomp>
    return [self.join([self.decode(frame) for frame in framesplit(chunk)])
  File "/Users/jtam/anaconda2/envs/ipykernel_py3/lib/python3.6/site-packages/partd/pandas.py", line 144, in deserialize
    for block, dt, shape in zip(b_blocks, dtypes, shapes)]
  File "/Users/jtam/anaconda2/envs/ipykernel_py3/lib/python3.6/site-packages/partd/pandas.py", line 144, in <listcomp>
    for block, dt, shape in zip(b_blocks, dtypes, shapes)]
```

**Comment by mrocklin** [comment]
Thank you for the concise and reproducible bug report.  This is perfect. 

However, I'm also not entirely surprised that this failed.  Generally speaking dask.dataframe has not been seriously tested against non-scalar datatypes.

**Comment by mrocklin** [comment]
This seems ok today.

```python
In [1]: import pandas as pd
   ...: import dask.dataframe as dd
   ...: 
   ...: df1 = pd.DataFrame({'col1': range(100),
   ...:                     'col2': [[.1, .1]]*100})
   ...: df2 = pd.DataFrame({'col1': range(50, 200)})
   ...: df3 = df1.merge(df2, how='inner', on='col1')  # works as expected
   ...: 
   ...: dd1 = dd.from_pandas(df1, npartitions=2)
   ...: dd2 = dd.from_pandas(df2, npartitions=2)
   ...: dd3 = dd1.merge(dd2, how='inner', on='col1')  # task planning is ok
   ...: dd3.compute()  # fails
   ...: 
Out[1]: 
    col1        col2
0     51  [0.1, 0.1]
1     52  [0.1, 0.1]
2     55  [0.1, 0.1]
3     57  [0.1, 0.1]
4     60  [0.1, 0.1]
5     61  [0.1, 0.1]
6     62  [0.1, 0.1]
7     63  [0.1, 0.1]
8     64  [0.1, 0.1]
9     65  [0.1, 0.1]
10    66  [0.1, 0.1]
11    68  [0.1, 0.1]
12    71  [0.1, 0.1]
13    74  [0.1, 0.1]
14    75  [0.1, 0.1]
15    76  [0.1, 0.1]
16    78  [0.1, 0.1]
17    79  [0.1, 0.1]
18    82  [0.1, 0.1]
19    84  [0.1, 0.1]
20    85  [0.1, 0.1]
21    86  [0.1, 0.1]
22    87  [0.1, 0.1]
23    88  [0.1, 0.1]
24    89  [0.1, 0.1]
25    91  [0.1, 0.1]
26    94  [0.1, 0.1]
27    96  [0.1, 0.1]
28    97  [0.1, 0.1]
29    98  [0.1, 0.1]
30    99  [0.1, 0.1]
0     50  [0.1, 0.1]
1     53  [0.1, 0.1]
2     54  [0.1, 0.1]
3     56  [0.1, 0.1]
4     58  [0.1, 0.1]
5     59  [0.1, 0.1]
6     67  [0.1, 0.1]
7     69  [0.1, 0.1]
8     70  [0.1, 0.1]
9     72  [0.1, 0.1]
10    73  [0.1, 0.1]
11    77  [0.1, 0.1]
12    80  [0.1, 0.1]
13    81  [0.1, 0.1]
14    83  [0.1, 0.1]
15    90  [0.1, 0.1]
16    92  [0.1, 0.1]
17    93  [0.1, 0.1]
18    95  [0.1, 0.1]

```

Closing
