### ISSUE TITLE
toolz not installed with dask

### ISSUE THREAD

**Issue by NiklasRosenstein** [dask/dask#2159]
After I installed dask via Pip, I get `No module named 'toolz'`

```
Traceback (most recent call last):
  File "/home/niklas/Desktop/norbert/nodepy_modules/.pip/lib/python3.5/site-packages/dask/delayed.py", line 10, in <module>
    from cytoolz import unique, curry, first
ImportError: No module named 'cytoolz'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/nodepy", line 11, in <module>
    load_entry_point('node.py-3.5', 'console_scripts', 'nodepy')()
  File "/home/niklas/Desktop/nodepy/nodepy.py", line 827, in main
    module.exec_()
  File "/home/niklas/Desktop/nodepy/nodepy.py", line 153, in exec_
    exec(self.code, vars(self.namespace))
  File "/home/niklas/Desktop/norbert/backend/post.py", line 9, in <module>
    from dask import delayed
  File "/home/niklas/Desktop/norbert/nodepy_modules/.pip/lib/python3.5/site-packages/dask/delayed.py", line 12, in <module>
    from toolz import unique, curry, first
ImportError: No module named 'toolz'
```

Dask 0.14.1

**Comment by mrocklin** [comment]
See notes in http://dask.pydata.org/en/latest/install.html#pip

**Comment by NiklasRosenstein** [comment]
Missed that portion. Thanks

**Comment by mrocklin** [comment]
No worries.  Thanks for raising a public issue.  Hopefully this helps
people in the future who run into your situation.
