### ISSUE TITLE
Ambiguity of read_parquet 'index' parameter

### ISSUE THREAD

**Issue by wikiped** [dask/dask#2161]
Currently (version: '0.14.1') trying to read parquet storage with `index=None` will raise:
    
    ValueError: Multiple possible indexes exist: ...

Simple example to reproduce:

    import pandas as pd
    import fastparquet as fp
    from dask import dataframe as dd

    DATA_SIZE = 100
    alphas = ['q'] * DATA_SIZE
    ints = [3] * DATA_SIZE
    flts = [3.] * DATA_SIZE
    df = pd.DataFrame({'a': alphas, 'i': ints, 'f': flts})

    fp.write('parquet_wo_index', data=df, compression='snappy')
    dfd = dd.read_parquet('parquet_wo_index', index=None)

Given that the doc for `read_parquet` says:

    index: string or None
        Name of index column to use if that column is sorted
        
...Is it's fair to expect that the file should be read without errors.

However this will only work if `index=False`.

I think it would make more sense to have the default option to 'just-work' and allow raising and other manipulation of the data being read if the user has explicitly asked for it.

The default behavior is coded in the block starting at line [92](https://github.com/dask/dask/blob/2821ff1d84530cb0bbf5eba4dc134fb67b27ccf8/dask/dataframe/io/parquet.py#L92):
    
    if index is False:
        ...

I would suggest to change the the default value of `index` to `False` and reflect it in the docs that `index=None` will automatically select sorted column (if only one exists) as index or if one of sorted columns is named 'index', otherwise `ValueError` will be raised.

This will allow to avoid unexpected failures especially when the scheme of the data being read is not known in advance.

**Comment by mrocklin** [comment]
Yeah, I think there is a choice here between supporting naive users who appreciate being given an index automatically and being clean and not making any choices magically.

Generally dask.dataframe follows the lead on pandas here and tries to provide useful defaults that support novice users.  We fall back on informative errors when these fail that point people to alternatives.  

As a partial solution to your problem I propose that we add a `"or add index=False to specify no index"` message to the error that you received.

**Comment by martindurant** [comment]
It's useful to point out that having a sorted index is potentially very useful, which I think also biases the choice here.

**Comment by wikiped** [comment]
I appreciate `taking care of novice users` motive and do agree that there is value in following pandas lead on what to expect when loading data. Pandas dev-team does seem to prefer recently the `index=False` option as a way to force loading without index.
[Here](https://github.com/pandas-dev/pandas/issues/11733) is relevant discussion.

I made a PR for the doc change.

**Comment by rstuckey** [comment]
Dask/distributed seems to be having issues inferring the column names when there is no index.

For example:
```
import datetime as dt
import numpy as np
import pandas as pd
import pyarrow as pa
import pyarrow.parquet as pq
import dask.dataframe as dd
from dask.distributed import Client

pdf = pd.DataFrame({'Hash' : range(95, 100, 1),
    'LineNo' : range(500, 1000, 100),
    'Timestamp' : [dt.datetime.now() + dt.timedelta(seconds=i) for i in range(5)],
    'lat': np.arange(-1.0, -6.0, -1.0),
    'lon': np.arange(101.0, 106.0, 1.0)}, index = range(5))
tab = pa.Table.from_pandas(pdf)

hdfs = pa.hdfs.connect(hdfsnn, 8020, user='hdfs', driver='libhdfs')

parq_path = '/user/hdfs/test.parquet'
with hdfs.open(parq_path, 'wb') as f:
    pq.write_table(tab, f)

parq_url = 'hdfs://hdfsnn:8020/user/hdfs/test.parquet'
ddf = dd.read_parquet(parq_url, engine='pyarrow')
ddf.head()
```
```
  | Hash | LineNo | Timestamp | lat | lon
-- | -- | -- | -- | -- | --
95 | 500 | 2018-04-17 11:16:44.762892 | -1.0 | 101.0
96 | 600 | 2018-04-17 11:16:45.762911 | -2.0 | 102.0
97 | 700 | 2018-04-17 11:16:46.762916 | -3.0 | 103.0
98 | 800 | 2018-04-17 11:16:47.762919 | -4.0 | 104.0
99 | 900 | 2018-04-17 11:16:48.762923 | -5.0 | 105.0
```
That's ok. If I try the same using a distributed client:
```
client = Client('dasksch:8786')
client.get_versions(check=True)
```
```
{'client': {'host': [('python', '3.6.2.final.0'),
   ('python-bits', 64),
   ('OS', 'Linux'),
   ('OS-release', '3.10.0-693.21.1.el7.x86_64'),
   ('machine', 'x86_64'),
   ('processor', 'x86_64'),
   ('byteorder', 'little'),
   ('LC_ALL', 'None'),
   ('LANG', 'en_AU.UTF-8'),
   ('LOCALE', 'en_AU.UTF-8')],
  'packages': {'optional': [('numpy', '1.11.3'),
    ('pandas', '0.22.0'),
    ('bokeh', '0.12.15'),
    ('lz4', None),
    ('blosc', None)],
   'required': [('dask', '0.17.2'),
    ('distributed', '1.21.5'),
    ('msgpack', '0.4.8'),
    ('cloudpickle', '0.4.0'),
    ('tornado', '4.5.3'),
    ('toolz', '0.8.2')]}},
 'scheduler': {'host': [['python', '3.6.2.final.0'],
   ['python-bits', 64],
   ['OS', 'Linux'],
   ['OS-release', '3.13.0-144-generic'],
   ['machine', 'x86_64'],
   ['processor', 'x86_64'],
   ['byteorder', 'little'],
   ['LC_ALL', 'None'],
   ['LANG', 'en_AU'],
   ['LOCALE', 'en_AU.ISO8859-1']],
  'packages': {'optional': [['numpy', '1.11.3'],
    ['pandas', '0.22.0'],
    ['bokeh', '0.12.15'],
    ['lz4', None],
    ['blosc', None]],
   'required': [['dask', '0.17.2'],
    ['distributed', '1.21.5'],
    ['msgpack', '0.4.8'],
    ['cloudpickle', '0.4.0'],
    ['tornado', '4.5.3'],
    ['toolz', '0.8.2']]}},
 'workers': {'tcp://daskwkr:52695': {'host': [['python',
     '3.6.2.final.0'],
    ['python-bits', 64],
    ['OS', 'Linux'],
    ['OS-release', '3.13.0-144-generic'],
    ['machine', 'x86_64'],
    ['processor', 'x86_64'],
    ['byteorder', 'little'],
    ['LC_ALL', 'None'],
    ['LANG', 'en_AU'],
    ['LOCALE', 'en_AU.ISO8859-1']],
   'packages': {'optional': [['numpy', '1.11.3'],
     ['pandas', '0.22.0'],
     ['bokeh', '0.12.15'],
     ['lz4', None],
     ['blosc', None]],
    'required': [['dask', '0.17.2'],
     ['distributed', '1.21.5'],
     ['msgpack', '0.4.8'],
     ['cloudpickle', '0.4.0'],
     ['tornado', '4.5.3'],
     ['toolz', '0.8.2']]}}}}
```
Reading without explicitly defining the columns results in an error:
```
ddf = dd.read_parquet(parq_url, engine='pyarrow', index=False)
ddf.head()
```
```
distributed.utils - ERROR - None
Traceback (most recent call last):
  File "/opt/anaconda3/envs/fdenv0/lib/python3.6/site-packages/distributed/utils.py", line 238, in f
    result[0] = yield make_coro()
  File "/opt/anaconda3/envs/fdenv0/lib/python3.6/site-packages/tornado/gen.py", line 1055, in run
    value = future.result()
  File "/opt/anaconda3/envs/fdenv0/lib/python3.6/site-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
  File "/opt/anaconda3/envs/fdenv0/lib/python3.6/site-packages/tornado/gen.py", line 1063, in run
    yielded = self.gen.throw(*exc_info)
  File "/opt/anaconda3/envs/fdenv0/lib/python3.6/site-packages/distributed/client.py", line 1386, in _gather
    traceback)
  File "/opt/anaconda3/envs/fdenv0/lib/python3.6/site-packages/six.py", line 692, in reraise
    raise value.with_traceback(tb)
  File "/home/user/.conda/envs/fdenv1/lib/python3.6/site-packages/dask/dataframe/io/parquet.py", line 617, in _read_pyarrow_parquet_piece
  File "/home/user/.conda/envs/fdenv1/lib/python3.6/site-packages/pyarrow/parquet.py", line 348, in read
  File "/home/user/.conda/envs/fdenv1/lib/python3.6/site-packages/pyarrow/parquet.py", line 117, in read
  File "/home/user/.conda/envs/fdenv1/lib/python3.6/site-packages/pyarrow/parquet.py", line 146, in _get_column_indices
  File "_parquet.pyx", line 515, in pyarrow._parquet.ParquetReader.column_name_idx
KeyError: None

---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-11-31779a6b789d> in <module>()
      6 ddf = dd.read_parquet(parq_url, engine='pyarrow', index=False)
      7 #ddf = dd.read_parquet(parq_url, engine='pyarrow', index=False, columns=['Hash', 'LineNo', 'Timestamp', 'lat', 'lon'])
----> 8 ddf.head()

/opt/anaconda3/envs/fdenv0/lib/python3.6/site-packages/dask/dataframe/core.py in head(self, n, npartitions, compute)
    879 
    880         if compute:
--> 881             result = result.compute()
    882         return result
    883 

/opt/anaconda3/envs/fdenv0/lib/python3.6/site-packages/dask/base.py in compute(self, **kwargs)
    153         dask.base.compute
    154         """
--> 155         (result,) = compute(self, traverse=False, **kwargs)
    156         return result
    157 

/opt/anaconda3/envs/fdenv0/lib/python3.6/site-packages/dask/base.py in compute(*args, **kwargs)
    402     postcomputes = [a.__dask_postcompute__() if is_dask_collection(a)
    403                     else (None, a) for a in args]
--> 404     results = get(dsk, keys, **kwargs)
    405     results_iter = iter(results)
    406     return tuple(a if f is None else f(next(results_iter), *a)

/opt/anaconda3/envs/fdenv0/lib/python3.6/site-packages/distributed/client.py in get(self, dsk, keys, restrictions, loose_restrictions, resources, sync, asynchronous, direct, fifo_timeout, **kwargs)
   2083             try:
   2084                 results = self.gather(packed, asynchronous=asynchronous,
-> 2085                                       direct=direct)
   2086             finally:
   2087                 for f in futures.values():

/opt/anaconda3/envs/fdenv0/lib/python3.6/site-packages/distributed/client.py in gather(self, futures, errors, maxsize, direct, asynchronous)
   1506             return self.sync(self._gather, futures, errors=errors,
   1507                              direct=direct, local_worker=local_worker,
-> 1508                              asynchronous=asynchronous)
   1509 
   1510     @gen.coroutine

/opt/anaconda3/envs/fdenv0/lib/python3.6/site-packages/distributed/client.py in sync(self, func, *args, **kwargs)
    613             return future
    614         else:
--> 615             return sync(self.loop, func, *args, **kwargs)
    616 
    617     def __repr__(self):

/opt/anaconda3/envs/fdenv0/lib/python3.6/site-packages/distributed/utils.py in sync(loop, func, *args, **kwargs)
    252             e.wait(10)
    253     if error[0]:
--> 254         six.reraise(*error[0])
    255     else:
    256         return result[0]

/opt/anaconda3/envs/fdenv0/lib/python3.6/site-packages/six.py in reraise(tp, value, tb)
    691             if value.__traceback__ is not tb:
    692                 raise value.with_traceback(tb)
--> 693             raise value
    694         finally:
    695             value = None

/opt/anaconda3/envs/fdenv0/lib/python3.6/site-packages/distributed/utils.py in f()
    236             yield gen.moment
    237             thread_state.asynchronous = True
--> 238             result[0] = yield make_coro()
    239         except Exception as exc:
    240             logger.exception(exc)

/opt/anaconda3/envs/fdenv0/lib/python3.6/site-packages/tornado/gen.py in run(self)
   1053 
   1054                     try:
-> 1055                         value = future.result()
   1056                     except Exception:
   1057                         self.had_exception = True

/opt/anaconda3/envs/fdenv0/lib/python3.6/site-packages/tornado/concurrent.py in result(self, timeout)
    236         if self._exc_info is not None:
    237             try:
--> 238                 raise_exc_info(self._exc_info)
    239             finally:
    240                 self = None

/opt/anaconda3/envs/fdenv0/lib/python3.6/site-packages/tornado/util.py in raise_exc_info(exc_info)

/opt/anaconda3/envs/fdenv0/lib/python3.6/site-packages/tornado/gen.py in run(self)
   1061                     if exc_info is not None:
   1062                         try:
-> 1063                             yielded = self.gen.throw(*exc_info)
   1064                         finally:
   1065                             # Break up a reference to itself

/opt/anaconda3/envs/fdenv0/lib/python3.6/site-packages/distributed/client.py in _gather(self, futures, errors, direct, local_worker)
   1384                             six.reraise(type(exception),
   1385                                         exception,
-> 1386                                         traceback)
   1387                     if errors == 'skip':
   1388                         bad_keys.add(key)

/opt/anaconda3/envs/fdenv0/lib/python3.6/site-packages/six.py in reraise(tp, value, tb)
    690                 value = tp()
    691             if value.__traceback__ is not tb:
--> 692                 raise value.with_traceback(tb)
    693             raise value
    694         finally:

/home/user/.conda/envs/fdenv1/lib/python3.6/site-packages/dask/dataframe/io/parquet.py in _read_pyarrow_parquet_piece()

/home/user/.conda/envs/fdenv1/lib/python3.6/site-packages/pyarrow/parquet.py in read()

/home/user/.conda/envs/fdenv1/lib/python3.6/site-packages/pyarrow/parquet.py in read()

/home/user/.conda/envs/fdenv1/lib/python3.6/site-packages/pyarrow/parquet.py in _get_column_indices()

_parquet.pyx in pyarrow._parquet.ParquetReader.column_name_idx()

KeyError: None
```
Is this intentional? I would have thought the column names could be inferred, regardless of the presence of an index.

If I explicitly define the columns:
```
ddf = dd.read_parquet(parq_url, engine='pyarrow', index=False, columns=['Hash', 'LineNo', 'Timestamp', 'lat', 'lon'])
```
```
  | Hash | LineNo | Timestamp | lat | lon
-- | -- | -- | -- | -- | --
95 | 500 | 2018-04-17 11:16:44.762892 | -1.0 | 101.0
96 | 600 | 2018-04-17 11:16:45.762911 | -2.0 | 102.0
97 | 700 | 2018-04-17 11:16:46.762916 | -3.0 | 103.0
98 | 800 | 2018-04-17 11:16:47.762919 | -4.0 | 104.0
99 | 900 | 2018-04-17 11:16:48.762923 | -5.0 | 105.0
```
As before.

**Comment by mrocklin** [comment]
@rstuckey thanks for the bug report.  Can I suggest that you raise this in a new issue?  it seems to be distinct from the issue originally discussed here.  Also, if you're able to reproduce this without HDFS I suspect that the people will be more likely to step in and try out your example (HDFS is not very common on dev environments.)
