### ISSUE TITLE
Fancy indexing of arrays with length equal to one

### ISSUE THREAD

**Issue by ajarenfo** [dask/dask#2180]
I have an application that needs to take the first and the last element of an array.
If the array has length 1 it should return an array with the only element twice.
This works in numpy but, when i do it with dask.arrays i get the following error:

```python
>>> import numpy as np
>>> import dask
>>> a = np.zeros(1)
>>> a[[0,-1]]
array([ 0.,  0.])
>>> d = dask.array.from_array(a, (1,))
>>> d[[0,-1]]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "dask\array\core.py", line 1243, in __getitem__
    dsk, chunks = slice_array(out, self.name, self.chunks, index)
  File "dask\array\slicing.py", line 139, in slice_array
    dsk_out, bd_out = slice_with_newaxes(out_name, in_name, blockdims, index)
  File "dask\array\slicing.py", line 161, in slice_with_newaxes
    dsk, blockdims2 = slice_wrap_lists(out_name, in_name, blockdims, index2)
  File "dask\array\slicing.py", line 202, in slice_wrap_lists
    check_index(i, sum(bd))
  File "dask\array\slicing.py", line 713, in check_index
    raise IndexError("Index out of bounds %s" % dimension)
IndexError: Index out of bounds 1
```

**Comment by jcrist** [comment]
Sorry for the long delay here. This should be fixed in #2317.
