### ISSUE TITLE
Dask 0.14.1 

### ISSUE THREAD

**Issue by apiszcz** [dask/dask#2196]
This could be a collision with some other module, not sure.
Python 3.5.3, Dask 0.14.1
Removing cytoolz 0.8.2 from the system eliminates the issue
  

File "C:\g\skimage\util\apply_parallel.py", line 8, in <module>
    import dask.array as da
  File "C:\g\dask\array\__init__.py", line 4, in <module>
    from .core import (Array, stack, concatenate, take, tensordot, transpose,
  File "C:\g\dask\array\core.py", line 22, in <module>
    from cytoolz.curried import (partition, concat, pluck, join, first,
  File "C:\g\cytoolz\__init__.py", line 18, in <module>
    comp = compose

**Comment by jcrist** [comment]
This appears to not be the full traceback (no error message/type). Can you post the full traceback? What were you doing that produced the issue? Can you provide a [minimal reprocible example](http://stackoverflow.com/help/mcve)?

**Comment by apiszcz** [comment]
Traceback (most recent call last):
  File "lib\_test\test.py", line 15647, in <module>
    main()
  File "lib\_test\test.py", line 15571, in main
    if 'apfilter2'      in modes: oapf2.run(oc, ol, ou, src)
  File "lib\_test\test.py", line 3266, in run
    mmxy, plyfilter = self.get_polygon_filters(oc, ol, ou, src)
  File "lib\_test\test.py", line 3197, in get_polygon_filters
    from skimage import draw as skdraw
  File "C:\g\test\lib\skimage\__init__.py", line 158, in <module>
    from .util.dtype import *
  File "C:\g\test\lib\skimage\util\__init__.py", line 5, in <module>
    from .apply_parallel import apply_parallel
  File "C:\g\test\lib\skimage\util\apply_parallel.py", line 8, in <module>
    import dask.array as da
  File "C:\g\test\lib\dask\array\__init__.py", line 4, in <module>
    from .core import (Array, stack, concatenate, take, tensordot, transpose,
  File "C:\g\test\lib\dask\array\core.py", line 22, in <module>
    from cytoolz.curried import (partition, concat, pluck, join, first,
  File "C:\g\test\lib\cytoolz\__init__.py", line 18, in <module>
    comp = compose
NameError: name 'compose' is not defined

**Comment by jcrist** [comment]
Hmmm, looks like an installation issue. How did you instally cytoolz? If the compilation step failed, you might see an error like that. Since dask doesn't rely on cytoolz fully (it just makes some operations faster) you should be fine using toolz alone.

**Comment by apiszcz** [comment]
My error, apparently I had the incorrect .pyd for a different version of
python. reinstalled, working now.
Tx
