### ISSUE TITLE
Dataframe.loc not working with indexes list

### ISSUE THREAD

**Issue by tundo91** [dask/dask#2203]
```python
def main():
    df = ddf.read_csv(OUTPUT_PATH_DIR + '*.part.csv', encoding='utf-8')

    splitter = sklearn.model_selection.GroupShuffleSplit(n_splits=1, train_size=0.7, random_state=RND_SEED)

    for partition_index in xrange(df.npartitions):
        X = df.get_partition(partition_index)

        # splitting-train-test: use 'thread_id' as groups labels
        groups = X['thread_id']
        train_indexes, test_indexes = splitter.split(X,  groups=groups).next()

        # get partition's training set... FAILS
        print df.get_partition(partition_index).loc[train_indexes].compute()
```

```
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/Users/erotundo/PycharmProjects/DatasetAnnotatorProj/Analysis/train_binaryBestAnswer.py", line 96, in <module>
    main()
  File "/Users/erotundo/PycharmProjects/DatasetAnnotatorProj/Analysis/train_binaryBestAnswer.py", line 51, in main
    print df.get_partition(partition_index).loc[train_indexes].compute()
  File "/Users/erotundo/PycharmProjects/DatasetAnnotatorProj/venv/lib/python2.7/site-packages/dask/base.py", line 95, in compute
    (result,) = compute(self, traverse=False, **kwargs)
  File "/Users/erotundo/PycharmProjects/DatasetAnnotatorProj/venv/lib/python2.7/site-packages/dask/base.py", line 202, in compute
    results = get(dsk, keys, **kwargs)
  File "/Users/erotundo/PycharmProjects/DatasetAnnotatorProj/venv/lib/python2.7/site-packages/dask/multiprocessing.py", line 87, in get
    dumps=dumps, loads=loads, **kwargs)
  File "/Users/erotundo/PycharmProjects/DatasetAnnotatorProj/venv/lib/python2.7/site-packages/dask/async.py", line 500, in get_async
    raise(remote_exception(res, tb))
dask.async.TypeError: '[   0    1    2 ..., 1679 1680 1681]' is an invalid key

Traceback
---------
  File "/Users/erotundo/PycharmProjects/DatasetAnnotatorProj/venv/lib/python2.7/site-packages/dask/async.py", line 266, in execute_task
    result = _execute_task(task, data)
  File "/Users/erotundo/PycharmProjects/DatasetAnnotatorProj/venv/lib/python2.7/site-packages/dask/async.py", line 247, in _execute_task
    return func(*args2)
  File "/Users/erotundo/PycharmProjects/DatasetAnnotatorProj/venv/lib/python2.7/site-packages/dask/dataframe/core.py", line 3106, in apply_and_enforce
    df = func(*args, **kwargs)
  File "/Users/erotundo/PycharmProjects/DatasetAnnotatorProj/venv/lib/python2.7/site-packages/dask/dataframe/methods.py", line 30, in try_loc
    return loc(df, iindexer, cindexer)
  File "/Users/erotundo/PycharmProjects/DatasetAnnotatorProj/venv/lib/python2.7/site-packages/dask/dataframe/methods.py", line 20, in loc
    return df.loc[iindexer]
  File "/Users/erotundo/PycharmProjects/DatasetAnnotatorProj/venv/lib/python2.7/site-packages/pandas/core/indexing.py", line 1312, in __getitem__
    return self._getitem_axis(key, axis=0)
  File "/Users/erotundo/PycharmProjects/DatasetAnnotatorProj/venv/lib/python2.7/site-packages/pandas/core/indexing.py", line 1453, in _getitem_axis
    return self._get_slice_axis(key, axis=axis)
  File "/Users/erotundo/PycharmProjects/DatasetAnnotatorProj/venv/lib/python2.7/site-packages/pandas/core/indexing.py", line 1334, in _get_slice_axis
    slice_obj.step, kind=self.name)
  File "/Users/erotundo/PycharmProjects/DatasetAnnotatorProj/venv/lib/python2.7/site-packages/pandas/indexes/base.py", line 2997, in slice_indexer
    kind=kind)
  File "/Users/erotundo/PycharmProjects/DatasetAnnotatorProj/venv/lib/python2.7/site-packages/pandas/indexes/base.py", line 3176, in slice_locs
    start_slice = self.get_slice_bound(start, 'left', kind)
  File "/Users/erotundo/PycharmProjects/DatasetAnnotatorProj/venv/lib/python2.7/site-packages/pandas/indexes/base.py", line 3119, in get_slice_bound
    slc = self.get_loc(label)
  File "/Users/erotundo/PycharmProjects/DatasetAnnotatorProj/venv/lib/python2.7/site-packages/pandas/indexes/base.py", line 2134, in get_loc
    return self._engine.get_loc(key)
  File "pandas/index.pyx", line 132, in pandas.index.IndexEngine.get_loc (pandas/index.c:4433)
  File "pandas/index.pyx", line 134, in pandas.index.IndexEngine.get_loc (pandas/index.c:3986)
```

I checked and ```partition_index``` is a valid indices list for the related partition.

Using virtualenv with:
```
python 2.7.10
dask 0.14.1
pandas 0.19.2
```

Related to #1298 and #1999.

**Comment by mrocklin** [comment]
I don't understand your example, but I get the impression that you're trying to use loc with a list on a dataframe without known divisions.  This will never be efficient, but could be done just by checking the list against all partitions.  I think that this would be reasonable to add.

If you had a different issue then I recommend that you provide a minimally failing example if you can find the time to do so.  This would be something simple that replicates the problem, and that we can copy-paste to reproduce the failure locally.  Ideally it wouldn't involve any other libraries or datasets.

**Comment by tundo91** [comment]
Indeed its a dataframe without known divisions. However, I cannot reproduce a minimally failing error so I'm closing this. Tried a lot to play around with ```.loc[list]``` but it works in simple examples...
