### ISSUE TITLE
Weird behavior when concatting dataframes

### ISSUE THREAD

**Issue by shughes-uk** [dask/dask#2211]
I'm having an issue with a timeindex after I run a query then concat new columns based off the return of an apply on a column. If I don't do the query or I don't concat it works ok. Both together seems to cause an issue. I've attached a csv with sample data to use and code that should reproduce the error below. 

```
import pandas as pd
import dask.dataframe

schema_keys = {'index': int, 'timestamp': int, 'origin_port': int}

df = dask.dataframe.read_csv(
    ['test_dask.csv'],
    dtype=schema_keys,
    converters={'timestamp': lambda x: pd.to_datetime(int(x), unit='ns')},
    blocksize=None
)
df = df.set_index('timestamp')
df = df.query("origin_port == 0")


def generate_new_columns(port):
    return pd.Series({'col1': '', 'col2': None})


newcols = df['origin_port'].apply(generate_new_columns, meta={'col1': str, 'col2': object})
df = dask.dataframe.concat([df, newcols], axis=1)
print(df.compute())
```

[test_dask.csv.zip](https://github.com/dask/dask/files/918161/test_dask.csv.zip)

The full traceback is 

```
Traceback (most recent call last):
  File "test_dask.py", line 22, in <module>
    print(df.compute())
  File "/Users/shughes/miniconda3/lib/python3.5/site-packages/dask/base.py", line 96, in compute
    (result,) = compute(self, traverse=False, **kwargs)
  File "/Users/shughes/miniconda3/lib/python3.5/site-packages/dask/base.py", line 203, in compute
    results = get(dsk, keys, **kwargs)
  File "/Users/shughes/miniconda3/lib/python3.5/site-packages/dask/threaded.py", line 76, in get
    **kwargs)
  File "/Users/shughes/miniconda3/lib/python3.5/site-packages/dask/async.py", line 525, in get_async
    raise(remote_exception(res, tb))
dask.async.KeyError: 1483228800084000000

Traceback
---------
  File "/Users/shughes/miniconda3/lib/python3.5/site-packages/dask/async.py", line 291, in execute_task
    result = _execute_task(task, data)
  File "/Users/shughes/miniconda3/lib/python3.5/site-packages/dask/async.py", line 272, in _execute_task
    return func(*args2)
  File "/Users/shughes/miniconda3/lib/python3.5/site-packages/dask/dataframe/methods.py", line 58, in boundary_slice
    result = getattr(df, kind)[start:stop]
  File "/Users/shughes/miniconda3/lib/python3.5/site-packages/pandas/core/indexing.py", line 1312, in __getitem__
    return self._getitem_axis(key, axis=0)
  File "/Users/shughes/miniconda3/lib/python3.5/site-packages/pandas/core/indexing.py", line 1453, in _getitem_axis
    return self._get_slice_axis(key, axis=axis)
  File "/Users/shughes/miniconda3/lib/python3.5/site-packages/pandas/core/indexing.py", line 1334, in _get_slice_axis
    slice_obj.step, kind=self.name)
  File "/Users/shughes/miniconda3/lib/python3.5/site-packages/pandas/tseries/index.py", line 1498, in slice_indexer
    return Index.slice_indexer(self, start, end, step, kind=kind)
  File "/Users/shughes/miniconda3/lib/python3.5/site-packages/pandas/indexes/base.py", line 2997, in slice_indexer
    kind=kind)
  File "/Users/shughes/miniconda3/lib/python3.5/site-packages/pandas/indexes/base.py", line 3176, in slice_locs
    start_slice = self.get_slice_bound(start, 'left', kind)
  File "/Users/shughes/miniconda3/lib/python3.5/site-packages/pandas/indexes/base.py", line 3125, in get_slice_bound
    raise err
  File "/Users/shughes/miniconda3/lib/python3.5/site-packages/pandas/indexes/base.py", line 3119, in get_slice_bound
    slc = self.get_loc(label)
  File "/Users/shughes/miniconda3/lib/python3.5/site-packages/pandas/tseries/index.py", line 1402, in get_loc
    return Index.get_loc(self, key, method, tolerance)
  File "/Users/shughes/miniconda3/lib/python3.5/site-packages/pandas/indexes/base.py", line 2136, in get_loc
    return self._engine.get_loc(self._maybe_cast_indexer(key))
  File "pandas/index.pyx", line 553, in pandas.index.DatetimeEngine.get_loc (pandas/index.c:11829)
  File "pandas/index.pyx", line 578, in pandas.index.DatetimeEngine.get_loc (pandas/index.c:11425)
  File "pandas/index.pyx", line 175, in pandas.index.IndexEngine._get_loc_duplicates (pandas/index.c:4663)
  File "pandas/index.pyx", line 421, in pandas.index.Int64Engine._maybe_get_bool_indexer (pandas/index.c:8636)


```

**Comment by mrocklin** [comment]
Playing with this now.  It looks like the data and the divisions are slightly out of alignment.

```python
> /home/mrocklin/Software/anaconda/lib/python3.6/site-packages/pandas/indexes/base.py(3176)slice_locs()
   3174         start_slice = None
   3175         if start is not None:
-> 3176             start_slice = self.get_slice_bound(start, 'left', kind)
   3177         if start_slice is None:
   3178             start_slice = 0

ipdb> pp self
DatetimeIndex([   '2017-01-01 00:00:00.188000',
               '2017-01-01 00:00:00.404999936',
               '2017-01-01 00:00:00.433000192',
               '2017-01-01 00:00:00.546999808',
                  '2017-01-01 00:00:00.636000',
               '2017-01-01 00:00:00.670000128',
               '2017-01-01 00:00:00.670000128',
               '2017-01-01 00:00:00.848999936',
                  '2017-01-01 00:00:01.116000',
                  '2017-01-01 00:00:01.428000',
               ...
               '2017-01-01 00:14:58.527000064',
               '2017-01-01 00:14:58.653000192',
               '2017-01-01 00:14:58.934000128',
               '2017-01-01 00:14:59.151000064',
               '2017-01-01 00:14:59.464999936',
               '2017-01-01 00:14:59.596999936',
                  '2017-01-01 00:14:59.732000',
               '2017-01-01 00:14:59.787000064',
                  '2017-01-01 00:14:59.824000',
               '2017-01-01 00:14:59.887000064'],
              dtype='datetime64[ns]', name='timestamp', length=6050, freq=None)
ipdb> pp start
Timestamp('2017-01-01 00:00:00.084000')
ipdb> pp kind
'loc'
ipdb> pp self.get_slice_bound(start, 'left', kind)
*** KeyError: 1483228800084000000
```

**Comment by TomAugspurger** [comment]
So it looks like the `.query` hits a row with a division (the first one).
Should that force us to `repartition`?

**Comment by mrocklin** [comment]
Ah, interesting.  No, this shouldn't force a repartition.  Partitions are managed lazily before we are able to look at the values.  What this means I think is that we need to be more robust to the divisions not aligning perfectly with the data.  

Perhaps `boundary_slice` should set the following:

```python
start = min(start, df.index.min())
stop = max(stop, df.index.max())
```

**Comment by TomAugspurger** [comment]
OK, the docs currently say

> Divisions includes the minimum value of every partition’s index and the maximum value of the last partition’s index.

So it will actually be something like "Divisions include a lower bound on every partition's index, and an upper bound on the last partition's index"?

I can look into changing that.

**Comment by mrocklin** [comment]
Yes, I don't think we're able to guarantee the current statement under
filtering operations like query.

**Comment by TomAugspurger** [comment]
Ok, so after #2214 we get

```pytb
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
/Users/taugspurger/Envs/dask-dev/lib/python3.6/site-packages/dask/pand.py in <module>()
     15 df = df.set_index('timestamp')
     16 cdf = dask.dataframe.concat([df, df.query('origin_port == 0')], axis=1)
---> 17 print(cdf.compute())

/Users/taugspurger/Envs/dask-dev/lib/python3.6/site-packages/dask/dask/base.py in compute(self, **kwargs)
     94             Extra keywords to forward to the scheduler ``get`` function.
     95         """
---> 96         (result,) = compute(self, traverse=False, **kwargs)
     97         return result
     98

/Users/taugspurger/Envs/dask-dev/lib/python3.6/site-packages/dask/dask/base.py in compute(*args, **kwargs)
    201     dsk = collections_to_dsk(variables, optimize_graph, **kwargs)
    202     keys = [var._keys() for var in variables]
--> 203     results = get(dsk, keys, **kwargs)
    204
    205     results_iter = iter(results)

/Users/taugspurger/Envs/dask-dev/lib/python3.6/site-packages/dask/dask/async.py in get_sync(dsk, keys, **kwargs)
    567     kwargs.pop('num_workers', None)    # if num_workers present, remove it
    568     return get_async(apply_sync, 1, dsk, keys,
--> 569                      raise_on_exception=True, **kwargs)
    570
    571

/Users/taugspurger/Envs/dask-dev/lib/python3.6/site-packages/dask/dask/async.py in get_async(apply_async, num_workers, dsk, result, cache, get_id, raise_on_exception, rerun_exceptions_locally, callbacks, dumps, loads, **kwargs)
    530
    531             while state['ready'] and len(state['running']) < num_workers:
--> 532                 fire_task()
    533
    534     except BaseException:

/Users/taugspurger/Envs/dask-dev/lib/python3.6/site-packages/dask/dask/async.py in fire_task()
    506                         args=(key, dumps((dsk[key], data)),
    507                               dumps, loads, get_id, raise_on_exception),
--> 508                         callback=queue.put)
    509
    510         # Seed initial tasks into the thread pool

/Users/taugspurger/Envs/dask-dev/lib/python3.6/site-packages/dask/dask/async.py in apply_sync(func, args, kwds, callback)
    555 def apply_sync(func, args=(), kwds={}, callback=None):
    556     """ A naive synchronous version of apply_async """
--> 557     res = func(*args, **kwds)
    558     if callback is not None:
    559         callback(res)

/Users/taugspurger/Envs/dask-dev/lib/python3.6/site-packages/dask/dask/async.py in execute_task(key, task_info, dumps, loads, get_id, raise_on_exception)
    289     try:
    290         task, data = loads(task_info)
--> 291         result = _execute_task(task, data)
    292         id = get_id()
    293         result = dumps((result, None, id))

/Users/taugspurger/Envs/dask-dev/lib/python3.6/site-packages/dask/dask/async.py in _execute_task(arg, cache, dsk)
    270         func, args = arg[0], arg[1:]
    271         args2 = [_execute_task(a, cache) for a in args]
--> 272         return func(*args2)
    273     elif not ishashable(arg):
    274         return arg

/Users/taugspurger/Envs/dask-dev/lib/python3.6/site-packages/dask/dask/dataframe/methods.py in concat(dfs, axis, join, uniform)
    201     """
    202     if axis == 1:
--> 203         return pd.concat(dfs, axis=axis, join=join)
    204
    205     if len(dfs) == 1:

/Users/taugspurger/.virtualenvs/dask-dev/lib/python3.6/site-packages/pandas/tools/merge.py in concat(objs, axis, join, join_axes, ignore_index, keys, levels, names, verify_integrity, copy)
   1450                        verify_integrity=verify_integrity,
   1451                        copy=copy)
-> 1452     return op.get_result()
   1453
   1454

/Users/taugspurger/.virtualenvs/dask-dev/lib/python3.6/site-packages/pandas/tools/merge.py in get_result(self)
   1648             new_data = concatenate_block_managers(
   1649                 mgrs_indexers, self.new_axes, concat_axis=self.axis,
-> 1650                 copy=self.copy)
   1651             if not self.copy:
   1652                 new_data._consolidate_inplace()

/Users/taugspurger/.virtualenvs/dask-dev/lib/python3.6/site-packages/pandas/core/internals.py in concatenate_block_managers(mgrs_indexers, axes, concat_axis, copy)
   4825         placement=placement) for placement, join_units in concat_plan]
   4826
-> 4827     return BlockManager(blocks, axes)
   4828
   4829

/Users/taugspurger/.virtualenvs/dask-dev/lib/python3.6/site-packages/pandas/core/internals.py in __init__(self, blocks, axes, do_integrity_check, fastpath)
   2759
   2760         if do_integrity_check:
-> 2761             self._verify_integrity()
   2762
   2763         self._consolidate_check()

/Users/taugspurger/.virtualenvs/dask-dev/lib/python3.6/site-packages/pandas/core/internals.py in _verify_integrity(self)
   2969         for block in self.blocks:
   2970             if block._verify_integrity and block.shape[1:] != mgr_shape[1:]:
-> 2971                 construction_error(tot_items, block.shape[1:], self.axes)
   2972         if len(self.items) != tot_items:
   2973             raise AssertionError('Number of manager items must equal union of '

/Users/taugspurger/.virtualenvs/dask-dev/lib/python3.6/site-packages/pandas/core/internals.py in construction_error(tot_items, block_shape, axes, e)
   4231         raise ValueError("Empty data passed with indices specified.")
   4232     raise ValueError("Shape of passed values is {0}, indices imply {1}".format(
-> 4233         passed, implied))
   4234
   4235

ValueError: Shape of passed values is (4, 7375), indices imply (4, 6365)
```

I think the issue is we have duplicates in the index. `pandas.concat` will work on dupes, but only if the indexes match:

```python
In [23]: a = pd.Series([1, 2, 3, 4], index=[1, 2, 2, 3])

In [24]: b = pd.Series([1, 2, 3, 4], index=[0, 1, 2, 3])

In [25]: pd.concat([a, a], axis=1)  # duplicates, but match
Out[25]:
   0  1
1  1  1
2  2  2
2  3  3
3  4  4

In [26]: pd.concat([a, b], axis=1)
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-26-19fff623438b> in <module>()
----> 1 pd.concat([a, b], axis=1)

/Users/taugspurger/.virtualenvs/dask-dev/lib/python3.6/site-packages/pandas/tools/merge.py in concat(objs, axis, join, join_axes, ignore_index, keys, levels, names, verify_integrity, copy)
   1450                        verify_integrity=verify_integrity,
   1451                        copy=copy)
-> 1452     return op.get_result()
   1453
   1454

/Users/taugspurger/.virtualenvs/dask-dev/lib/python3.6/site-packages/pandas/tools/merge.py in get_result(self)
   1625
   1626                 index, columns = self.new_axes
-> 1627                 df = cons(data, index=index)
   1628                 df.columns = columns
   1629                 return df.__finalize__(self, method='concat')

/Users/taugspurger/.virtualenvs/dask-dev/lib/python3.6/site-packages/pandas/core/frame.py in __init__(self, data, index, columns, dtype, copy)
    264                                  dtype=dtype, copy=copy)
    265         elif isinstance(data, dict):
--> 266             mgr = self._init_dict(data, index, columns, dtype=dtype)
    267         elif isinstance(data, ma.MaskedArray):
    268             import numpy.ma.mrecords as mrecords

/Users/taugspurger/.virtualenvs/dask-dev/lib/python3.6/site-packages/pandas/core/frame.py in _init_dict(self, data, index, columns, dtype)
    400             arrays = [data[k] for k in keys]
    401
--> 402         return _arrays_to_mgr(arrays, data_names, index, columns, dtype=dtype)
    403
    404     def _init_ndarray(self, values, index, columns, dtype=None, copy=False):

/Users/taugspurger/.virtualenvs/dask-dev/lib/python3.6/site-packages/pandas/core/frame.py in _arrays_to_mgr(arrays, arr_names, index, columns, dtype)
   5401
   5402     # don't force copy because getting jammed in an ndarray anyway
-> 5403     arrays = _homogenize(arrays, index, dtype)
   5404
   5405     # from BlockManager perspective

/Users/taugspurger/.virtualenvs/dask-dev/lib/python3.6/site-packages/pandas/core/frame.py in _homogenize(data, index, dtype)
   5700                 # Forces alignment. No need to copy data since we
   5701                 # are putting it into an ndarray later
-> 5702                 v = v.reindex(index, copy=False)
   5703         else:
   5704             if isinstance(v, dict):

/Users/taugspurger/.virtualenvs/dask-dev/lib/python3.6/site-packages/pandas/core/series.py in reindex(self, index, **kwargs)
   2360     @Appender(generic._shared_docs['reindex'] % _shared_doc_kwargs)
   2361     def reindex(self, index=None, **kwargs):
-> 2362         return super(Series, self).reindex(index=index, **kwargs)
   2363
   2364     @Appender(generic._shared_docs['fillna'] % _shared_doc_kwargs)

/Users/taugspurger/.virtualenvs/dask-dev/lib/python3.6/site-packages/pandas/core/generic.py in reindex(self, *args, **kwargs)
   2257         # perform the reindex on the axes
   2258         return self._reindex_axes(axes, level, limit, tolerance, method,
-> 2259                                   fill_value, copy).__finalize__(self)
   2260
   2261     def _reindex_axes(self, axes, level, limit, tolerance, method, fill_value,

/Users/taugspurger/.virtualenvs/dask-dev/lib/python3.6/site-packages/pandas/core/generic.py in _reindex_axes(self, axes, level, limit, tolerance, method, fill_value, copy)
   2275             obj = obj._reindex_with_indexers({axis: [new_index, indexer]},
   2276                                              fill_value=fill_value,
-> 2277                                              copy=copy, allow_dups=False)
   2278
   2279         return obj

/Users/taugspurger/.virtualenvs/dask-dev/lib/python3.6/site-packages/pandas/core/generic.py in _reindex_with_indexers(self, reindexers, fill_value, copy, allow_dups)
   2369                                                 fill_value=fill_value,
   2370                                                 allow_dups=allow_dups,
-> 2371                                                 copy=copy)
   2372
   2373         if copy and new_data is self._data:

/Users/taugspurger/.virtualenvs/dask-dev/lib/python3.6/site-packages/pandas/core/internals.py in reindex_indexer(self, new_axis, indexer, axis, fill_value, allow_dups, copy)
   3837         # some axes don't allow reindexing with dups
   3838         if not allow_dups:
-> 3839             self.axes[axis]._can_reindex(indexer)
   3840
   3841         if axis >= self.ndim:

/Users/taugspurger/.virtualenvs/dask-dev/lib/python3.6/site-packages/pandas/indexes/base.py in _can_reindex(self, indexer)
   2492         # trying to reindex on an axis with duplicates
   2493         if not self.is_unique and len(indexer):
-> 2494             raise ValueError("cannot reindex from a duplicate axis")
   2495
   2496     def reindex(self, target, method=None, level=None, limit=None,

ValueError: cannot reindex from a duplicate axis

``` 

I *think* this can be closed now. Running

```python
newcols = df['origin_port'].apply(generate_new_columns, meta={'col1': str, 'col2': object})
df = pd.concat([df.compute(), newcols.compute()], axis=1)
```

gives the same error as running the dask version.

**Comment by shughes-uk** [comment]
I would expect the indexes to match from the result of the apply. I did a newcols.index.equals(df.index) and it returned True in this case.

**Comment by TomAugspurger** [comment]
> Which if I understand you correctly means there should not be an error?

My fault, I had modified your script to concat to the original, not the version filtered with `.query`.

Running your original script on my branch in #2214 does work.

**Comment by shughes-uk** [comment]
Unfortunately while this fixes the issue for single files it still seems to occur for multiple files. I've attached some more sample data. If you modify the read_csv line to
```
df = dask.dataframe.read_csv(
    ['test_dask.csv', 'test_dask2.csv'],
    dtype=schema_keys,
    converters={'timestamp': lambda x: pd.to_datetime(int(x), unit='ns')},
    blocksize=None
)
```

You get the following
```
Traceback (most recent call last):
  File "test_dask.py", line 22, in <module>
    print(df.compute())
  File "/Users/shughes/miniconda3/lib/python3.5/site-packages/dask/base.py", line 96, in compute
    (result,) = compute(self, traverse=False, **kwargs)
  File "/Users/shughes/miniconda3/lib/python3.5/site-packages/dask/base.py", line 203, in compute
    results = get(dsk, keys, **kwargs)
  File "/Users/shughes/miniconda3/lib/python3.5/site-packages/dask/threaded.py", line 76, in get
    **kwargs)
  File "/Users/shughes/miniconda3/lib/python3.5/site-packages/dask/async.py", line 525, in get_async
    raise(remote_exception(res, tb))
dask.async.KeyError: 1483228800084000000

Traceback
---------
  File "/Users/shughes/miniconda3/lib/python3.5/site-packages/dask/async.py", line 291, in execute_task
    result = _execute_task(task, data)
  File "/Users/shughes/miniconda3/lib/python3.5/site-packages/dask/async.py", line 272, in _execute_task
    return func(*args2)
  File "/Users/shughes/miniconda3/lib/python3.5/site-packages/dask/dataframe/methods.py", line 58, in boundary_slice
    result = getattr(df, kind)[start:stop]
  File "/Users/shughes/miniconda3/lib/python3.5/site-packages/pandas/core/indexing.py", line 1312, in __getitem__
    return self._getitem_axis(key, axis=0)
  File "/Users/shughes/miniconda3/lib/python3.5/site-packages/pandas/core/indexing.py", line 1453, in _getitem_axis
    return self._get_slice_axis(key, axis=axis)
  File "/Users/shughes/miniconda3/lib/python3.5/site-packages/pandas/core/indexing.py", line 1334, in _get_slice_axis
    slice_obj.step, kind=self.name)
  File "/Users/shughes/miniconda3/lib/python3.5/site-packages/pandas/tseries/index.py", line 1498, in slice_indexer
    return Index.slice_indexer(self, start, end, step, kind=kind)
  File "/Users/shughes/miniconda3/lib/python3.5/site-packages/pandas/indexes/base.py", line 2997, in slice_indexer
    kind=kind)
  File "/Users/shughes/miniconda3/lib/python3.5/site-packages/pandas/indexes/base.py", line 3176, in slice_locs
    start_slice = self.get_slice_bound(start, 'left', kind)
  File "/Users/shughes/miniconda3/lib/python3.5/site-packages/pandas/indexes/base.py", line 3125, in get_slice_bound
    raise err
  File "/Users/shughes/miniconda3/lib/python3.5/site-packages/pandas/indexes/base.py", line 3119, in get_slice_bound
    slc = self.get_loc(label)
  File "/Users/shughes/miniconda3/lib/python3.5/site-packages/pandas/tseries/index.py", line 1402, in get_loc
    return Index.get_loc(self, key, method, tolerance)
  File "/Users/shughes/miniconda3/lib/python3.5/site-packages/pandas/indexes/base.py", line 2136, in get_loc
    return self._engine.get_loc(self._maybe_cast_indexer(key))
  File "pandas/index.pyx", line 553, in pandas.index.DatetimeEngine.get_loc (pandas/index.c:11829)
  File "pandas/index.pyx", line 578, in pandas.index.DatetimeEngine.get_loc (pandas/index.c:11425)
  File "pandas/index.pyx", line 175, in pandas.index.IndexEngine._get_loc_duplicates (pandas/index.c:4663)
  File "pandas/index.pyx", line 421, in pandas.index.Int64Engine._maybe_get_bool_indexer (pandas/index.c:8636)
```

**Comment by TomAugspurger** [comment]
Ha, ok. In this case, Matt's suggestion of changing `boundary slice` to

```python
start = max(start, df.index.min())
stop = min(stop, df.index.max())
```

does fix it. I'll put together a PR quick, once I verify that that change doesn't break anything else.

**Comment by mrocklin** [comment]
It breaks other things.
