### ISSUE TITLE
dask mixes up dimensions when aggregating results

### ISSUE THREAD

**Issue by sjperkins** [dask/dask#2314]
```python
from pprint import pprint

import dask
import dask.array as da
import numpy as np

def complex_phase(lm, uvw, frequency):
    """
    Compute the complex phase. e^(-2*pi*1j*(l*u + m*v + n*w)*f/C)

    Parameters
    ----------
    lm : dask.array
        source coordinates with shape (nsrc, 2)
    uvw : dask.array
        uvw coordinates with shape (nrow, 3)
    frequency : dask.array
        frequencies with shape (nchan, )

    Returns
    -------
    dask.array
        complex phase with shape (nsrc, nrow, nchan)

    """

    # Reason about local dimension sizes
    nrow, _ = uvw.shape
    nsrc, _ = lm.shape
    nchan, = frequency.shape

    # Get views for more understandable code
    u, v, w = uvw[:,0], uvw[:,1], uvw[:,2]
    l, m = lm[:,0], lm[:,1]

    # Calculate n
    n = da.sqrt(1.0 - l**2 - m**2) - 1.0

    # Real phase
    # phase = ((np.outer(n, w) + np.outer(m, v) + np.outer(l, u))
    #         .reshape(nsrc, nrow))

    # Dask Outer Product
    phase = (da.atop(np.multiply, 'ij', l, 'i', u[:,None], 'ji', dtype=n.dtype, name="bah") +
            da.atop(np.multiply, 'ij', m, 'i', v[:,None], 'ji', dtype=n.dtype ) +
            da.atop(np.multiply, 'ij', n, 'i', w[:,None], 'ji', dtype=n.dtype))


    assert phase.shape == (nsrc, nrow)

    return da.exp(-2.0*np.pi*1j*
                phase[:,:,None]*frequency[None,None,:]/3e8)

# Dimensions
nsrc = 100
nrow = 6552
nchan = 64

lm = da.random.random(size=(nsrc,2), chunks=(nsrc,2)).astype(np.float64)
lm *= 0.1
uvw = da.random.random(size=(nrow,3), chunks=(500,3)).astype(np.float64)
frequency = da.random.random(size=(nchan,), chunks=(nchan,)).astype(np.float64)

cplx_phase = complex_phase(lm, uvw, frequency)

print "Complex Phase Chunks", cplx_phase.chunks
assert cplx_phase.shape == (nsrc, nrow, nchan)

cplx_phase.compute(get=dask.async.get_sync)
```

produces the following

```bash
Complex Phase Chunks ((100,), (500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 52), (64,))
Traceback (most recent call last):
  File "broken.py", line 69, in <module>
    cplx_phase.compute()
  File "/home/sperkins/venv/disttut/local/lib/python2.7/site-packages/dask/base.py", line 96, in compute
    (result,) = compute(self, traverse=False, **kwargs)
  File "/home/sperkins/venv/disttut/local/lib/python2.7/site-packages/dask/base.py", line 208, in compute
    for a in args)
  File "/home/sperkins/venv/disttut/local/lib/python2.7/site-packages/dask/base.py", line 208, in <genexpr>
    for a in args)
  File "/home/sperkins/venv/disttut/local/lib/python2.7/site-packages/dask/array/core.py", line 935, in finalize
    return concatenate3(results)
  File "/home/sperkins/venv/disttut/local/lib/python2.7/site-packages/dask/array/core.py", line 3459, in concatenate3
    result[idx] = arr
ValueError: could not broadcast input array from shape (52,100,64) into shape (500,100,64)
```

I've 3 dimensions, `nsrc=100`, `nrow=6552` and `nchan=64` and I've set up the computation so that when the complex phase is calculated the (nsrc, nrow, nchan) ordering is maintained. Only nrow is chunked in chunks of chunks. However, the above exception implies that dask is trying to calculate a (nrow, nsrc, nchan) ordering (the 52 is the size of the last nrow chunk) and it seems to be trying to force it into the 500 chunk size.

**Comment by sjperkins** [comment]
python 2.7.12
dask 0.14.3

**Comment by mrocklin** [comment]
My first guess is that you're misusing atop (though I haven't looked closely enough at your code to tell).  If your goal is to produce an outer product then you might want to try multiplication with slices with `None`.

```python
In [1]: import numpy as np

In [2]: x = np.arange(5)

In [3]: x[:, None] * x[None, :]
Out[3]: 
array([[ 0,  0,  0,  0,  0],
       [ 0,  1,  2,  3,  4],
       [ 0,  2,  4,  6,  8],
       [ 0,  3,  6,  9, 12],
       [ 0,  4,  8, 12, 16]])
```

**Comment by sjperkins** [comment]
Thanks, that fixes things.

I'm not sure whether to close since I've set up my atops based on the comment here: https://github.com/dask/dask/issues/1832#issuecomment-265550578.

The assert when constructing the phase entry suggests that dask thinks the shape of the output array is right.

**Comment by sjperkins** [comment]
Closing since I probably misusing atop
