### ISSUE TITLE
DD.read_csv, Failing on loading a single file with an asterisk, add a check for a single file.

### ISSUE THREAD

**Issue by joshring** [dask/dask#2337]
Failing on loading a single file with an asterisk, add a check for a single file.

```python
test = dd.read_csv('*.tsv', sep='\t', header=0, parse_dates=[1], names=[
                'name', 'timestamp', 'action', 'ID' ])
```

followed by:

```python
test = bb_test.compute()
```

Error:

```python
Traceback (most recent call last):

  File "<ipython-input-3-b02775793c1a>", line 13, in <module>
    bb_test = bb_test.compute()

  File "C:\Users\josh.ring\AppData\Local\Continuum\Miniconda3\lib\site-packages\dask\base.py", line 96, in compute
    (result,) = compute(self, traverse=False, **kwargs)

  File "C:\Users\josh.ring\AppData\Local\Continuum\Miniconda3\lib\site-packages\dask\base.py", line 203, in compute
    results = get(dsk, keys, **kwargs)

  File "C:\Users\josh.ring\AppData\Local\Continuum\Miniconda3\lib\site-packages\dask\threaded.py", line 76, in get
    **kwargs)

  File "C:\Users\josh.ring\AppData\Local\Continuum\Miniconda3\lib\site-packages\dask\async.py", line 525, in get_async
    raise(remote_exception(res, tb))

ValueError: invalid literal for int() with base 10: 'hardies'

Traceback
---------
  File "C:\Users\josh.ring\AppData\Local\Continuum\Miniconda3\lib\site-packages\dask\async.py", line 291, in execute_task
    result = _execute_task(task, data)
  File "C:\Users\josh.ring\AppData\Local\Continuum\Miniconda3\lib\site-packages\dask\async.py", line 272, in _execute_task
    return func(*args2)
  File "C:\Users\josh.ring\AppData\Local\Continuum\Miniconda3\lib\site-packages\dask\compatibility.py", line 47, in apply
    return func(*args, **kwargs)
  File "C:\Users\josh.ring\AppData\Local\Continuum\Miniconda3\lib\site-packages\dask\dataframe\io\csv.py", line 61, in pandas_read_text
    coerce_dtypes(df, dtypes)
  File "C:\Users\josh.ring\AppData\Local\Continuum\Miniconda3\lib\site-packages\dask\dataframe\io\csv.py", line 103, in coerce_dtypes
    df[c] = df[c].astype(dtypes[c])
  File "C:\Users\josh.ring\AppData\Local\Continuum\Miniconda3\lib\site-packages\pandas\util\_decorators.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\josh.ring\AppData\Local\Continuum\Miniconda3\lib\site-packages\pandas\core\generic.py", line 3299, in astype
    **kwargs)
  File "C:\Users\josh.ring\AppData\Local\Continuum\Miniconda3\lib\site-packages\pandas\core\internals.py", line 3224, in astype
    return self.apply('astype', dtype=dtype, **kwargs)
  File "C:\Users\josh.ring\AppData\Local\Continuum\Miniconda3\lib\site-packages\pandas\core\internals.py", line 3091, in apply
    applied = getattr(b, f)(**kwargs)
  File "C:\Users\josh.ring\AppData\Local\Continuum\Miniconda3\lib\site-packages\pandas\core\internals.py", line 471, in astype
    **kwargs)
  File "C:\Users\josh.ring\AppData\Local\Continuum\Miniconda3\lib\site-packages\pandas\core\internals.py", line 521, in _astype
    values = astype_nansafe(values.ravel(), dtype, copy=True)
  File "C:\Users\josh.ring\AppData\Local\Continuum\Miniconda3\lib\site-packages\pandas\core\dtypes\cast.py", line 625, in astype_nansafe
    return lib.astype_intsafe(arr.ravel(), dtype).reshape(arr.shape)
  File "pandas\_libs\lib.pyx", line 917, in pandas._libs.lib.astype_intsafe (pandas\_libs\lib.c:16260)
  File "pandas\_libs\src\util.pxd", line 93, in util.set_value_at_unsafe (pandas\_libs\lib.c:73093)`
```

**Running on miniconda**
pandas 0.20.1
dask  0.14.3
python 3.6.1

**Comment by martindurant** [comment]
The traceback suggests a problem parsing the file, rather than a failure to fund/open the file. Can you please verify that it loads without problems with straight pandas?

**Comment by joshring** [comment]
I can confirm yes:

`test = pd.read_csv( "outputJson.tsv", sep='\t', names=[
                'student', 'timestamp', 'verb', 'objectID' ] )`

works as expected

**Comment by jcrist** [comment]
Can you provide a reproducible test case? This would be something that we could run to help debug.

**Comment by joshring** [comment]
Cannot reproduce consistently, deleting some data from the file makes it run, but it is not clear which data causes it to fail.

The first column of the input has 99% integer type and occasionally has numeric labels, this may be the cause when loaded multi-threaded but I have not been able to confirm this with artificial test cases designed to replicate this behavior.

**Comment by jcrist** [comment]
This may be a case of dtype inference failing. By default `dd.read_csv`/`dd.read_table` takes a sample of your file and infers the dtypes from that. If the first n rows all contain integers, but later on contain floats, then you'll get an error. What happens if you specify the dtypes for all columns by passing in a dictionary of `{column_name: dtype, ...}` to the `dtype` keyword?

**Comment by joshring** [comment]
This is some code to break the current dd.read_csv method
https://pastebin.com/qNe1Jh2N

**Adding dtype={ 'col':'type',...} fixes the issue**

Perhaps  this should be reflected in the error message?
