### ISSUE TITLE
Unable to connect to web ui

### ISSUE THREAD

**Issue by baasman** [dask/dask#2393]
On OS X El Capitan 10.11.5

Dask version - 0.14.3
Distributed version - 1.16.2

Python - 3.5.2

Hi all,

I am unable to access the webui, as well as unable to connect to a client with a particular address.
For example, whenever I include any address in my client call, I get a OSError:

```

>>> from dask.distributed import Client
>>> c = Client('localhost:8786')

distributed.utils - ERROR - Timed out trying to connect to 'tcp://localhost:8786' after 5 s: ConnectionRefusedError: [Errno 61] Connection refused
Traceback (most recent call last):
  File "/Users/baasman/anaconda/lib/python3.5/site-packages/distributed/comm/core.py", line 159, in connect
    quiet_exceptions=EnvironmentError)
  File "/Users/baasman/anaconda/lib/python3.5/site-packages/tornado/gen.py", line 1008, in run
    value = future.result()
  File "/Users/baasman/anaconda/lib/python3.5/site-packages/tornado/concurrent.py", line 232, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 3, in raise_exc_info
tornado.gen.TimeoutError: Timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/baasman/anaconda/lib/python3.5/site-packages/distributed/utils.py", line 212, in f
    result[0] = yield make_coro()
  File "/Users/baasman/anaconda/lib/python3.5/site-packages/tornado/gen.py", line 1008, in run
    value = future.result()
  File "/Users/baasman/anaconda/lib/python3.5/site-packages/tornado/concurrent.py", line 232, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 3, in raise_exc_info
  File "/Users/baasman/anaconda/lib/python3.5/site-packages/tornado/gen.py", line 1014, in run
    yielded = self.gen.throw(*exc_info)
  File "/Users/baasman/anaconda/lib/python3.5/site-packages/distributed/client.py", line 497, in _start
    yield self._ensure_connected(timeout=timeout)
  File "/Users/baasman/anaconda/lib/python3.5/site-packages/tornado/gen.py", line 1008, in run
    value = future.result()
  File "/Users/baasman/anaconda/lib/python3.5/site-packages/tornado/concurrent.py", line 232, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 3, in raise_exc_info
  File "/Users/baasman/anaconda/lib/python3.5/site-packages/tornado/gen.py", line 1014, in run
    yielded = self.gen.throw(*exc_info)
  File "/Users/baasman/anaconda/lib/python3.5/site-packages/distributed/client.py", line 525, in _ensure_connected
    timeout=timeout)
  File "/Users/baasman/anaconda/lib/python3.5/site-packages/tornado/gen.py", line 1008, in run
    value = future.result()
  File "/Users/baasman/anaconda/lib/python3.5/site-packages/tornado/concurrent.py", line 232, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 3, in raise_exc_info
  File "/Users/baasman/anaconda/lib/python3.5/site-packages/tornado/gen.py", line 1014, in run
    yielded = self.gen.throw(*exc_info)
  File "/Users/baasman/anaconda/lib/python3.5/site-packages/distributed/comm/core.py", line 168, in connect
    _raise(error)
  File "/Users/baasman/anaconda/lib/python3.5/site-packages/distributed/comm/core.py", line 152, in _raise
    raise IOError(msg)
OSError: Timed out trying to connect to 'tcp://localhost:8786' after 5 s: ConnectionRefusedError: [Errno 61] Connection refused
Traceback (most recent call last):
  File "/Users/baasman/anaconda/lib/python3.5/site-packages/distributed/comm/core.py", line 159, in connect
    quiet_exceptions=EnvironmentError)
  File "/Users/baasman/anaconda/lib/python3.5/site-packages/tornado/gen.py", line 1008, in run
    value = future.result()
  File "/Users/baasman/anaconda/lib/python3.5/site-packages/tornado/concurrent.py", line 232, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 3, in raise_exc_info
tornado.gen.TimeoutError: Timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/baasman/anaconda/lib/python3.5/site-packages/distributed/client.py", line 400, in __init__
    self.start(timeout=timeout)
  File "/Users/baasman/anaconda/lib/python3.5/site-packages/distributed/client.py", line 435, in start
    sync(self.loop, self._start, **kwargs)
  File "/Users/baasman/anaconda/lib/python3.5/site-packages/distributed/utils.py", line 223, in sync
    six.reraise(*error[0])
  File "/Users/baasman/anaconda/lib/python3.5/site-packages/six.py", line 686, in reraise
    raise value
  File "/Users/baasman/anaconda/lib/python3.5/site-packages/distributed/utils.py", line 212, in f
    result[0] = yield make_coro()
  File "/Users/baasman/anaconda/lib/python3.5/site-packages/tornado/gen.py", line 1008, in run
    value = future.result()
  File "/Users/baasman/anaconda/lib/python3.5/site-packages/tornado/concurrent.py", line 232, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 3, in raise_exc_info
  File "/Users/baasman/anaconda/lib/python3.5/site-packages/tornado/gen.py", line 1014, in run
    yielded = self.gen.throw(*exc_info)
  File "/Users/baasman/anaconda/lib/python3.5/site-packages/distributed/client.py", line 497, in _start
    yield self._ensure_connected(timeout=timeout)
  File "/Users/baasman/anaconda/lib/python3.5/site-packages/tornado/gen.py", line 1008, in run
    value = future.result()
  File "/Users/baasman/anaconda/lib/python3.5/site-packages/tornado/concurrent.py", line 232, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 3, in raise_exc_info
  File "/Users/baasman/anaconda/lib/python3.5/site-packages/tornado/gen.py", line 1014, in run
    yielded = self.gen.throw(*exc_info)
  File "/Users/baasman/anaconda/lib/python3.5/site-packages/distributed/client.py", line 525, in _ensure_connected
    timeout=timeout)
  File "/Users/baasman/anaconda/lib/python3.5/site-packages/tornado/gen.py", line 1008, in run
    value = future.result()
  File "/Users/baasman/anaconda/lib/python3.5/site-packages/tornado/concurrent.py", line 232, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 3, in raise_exc_info
  File "/Users/baasman/anaconda/lib/python3.5/site-packages/tornado/gen.py", line 1014, in run
    yielded = self.gen.throw(*exc_info)
  File "/Users/baasman/anaconda/lib/python3.5/site-packages/distributed/comm/core.py", line 168, in connect
    _raise(error)
  File "/Users/baasman/anaconda/lib/python3.5/site-packages/distributed/comm/core.py", line 152, in _raise
    raise IOError(msg)
OSError: Timed out trying to connect to 'tcp://localhost:8786' after 5 s: ConnectionRefusedError: [Errno 61] Connection refused

```

If I instead do not specify an address, I am able to start the scheduler, but unable to find the webui.

```
>>> c = Client()

>>> c
<Client: scheduler='tcp://127.0.0.1:62759' processes=8 cores=8>

>>> pprint(c.scheduler_info())
{'address': 'tcp://127.0.0.1:62759',
 'id': 'b325775c-43ce-11e7-a3a7-9801a7b6f57d',
 'services': {},
 'type': 'Scheduler',
 'workers': {'tcp://127.0.0.1:62766': {'executing': 0,
                                       'host': '127.0.0.1',
                                       'in_flight': 0,
                                       'in_memory': 0,
                                       'last-seen': 1495994175.655355,
                                       'local_directory': '/var/folders/0d/287bxwpd3gg9vh0qxtht1bs80000gn/T/nanny-nj99apvv',
                                       'memory': 2540118016,
                                       'memory-rss': 14888960,
                                       'memory-vms': 2540118016,
                                       'memory_limit': 1288490188.0,
                                       'name': 'tcp://127.0.0.1:62766',
                                       'ncores': 1,
                                       'ready': 0,
                                       'services': {'nanny': 62760},
                                       'time-delay': 0.00571894645690918},
             'tcp://127.0.0.1:62768': {'executing': 0,
                                       'host': '127.0.0.1',
                                       'in_flight': 0,
                                       'in_memory': 0,
                                       'last-seen': 1495994175.655714,
                                       'local_directory': '/var/folders/0d/287bxwpd3gg9vh0qxtht1bs80000gn/T/nanny-lvwjmjkr',
                                       'memory': 2540118016,
                                       'memory-rss': 14721024,
                                       'memory-vms': 2540118016,
                                       'memory_limit': 1288490188.0,
                                       'name': 'tcp://127.0.0.1:62768',
                                       'ncores': 1,
                                       'ready': 0,
                                       'services': {'nanny': 62761},
                                       'time-delay': 0.004661083221435547},
             'tcp://127.0.0.1:62772': {'executing': 0,
                                       'host': '127.0.0.1',
                                       'in_flight': 0,
                                       'in_memory': 0,
                                       'last-seen': 1495994175.656125,
                                       'local_directory': '/var/folders/0d/287bxwpd3gg9vh0qxtht1bs80000gn/T/nanny-99asmyu_',
                                       'memory': 2540118016,
                                       'memory-rss': 14876672,
                                       'memory-vms': 2540118016,
                                       'memory_limit': 1288490188.0,
                                       'name': 'tcp://127.0.0.1:62772',
                                       'ncores': 1,
                                       'ready': 0,
                                       'services': {'nanny': 62762},
                                       'time-delay': 0.0036940574645996094},
             'tcp://127.0.0.1:62777': {'executing': 0,
                                       'host': '127.0.0.1',
                                       'in_flight': 0,
                                       'in_memory': 0,
                                       'last-seen': 1495994175.662825,
                                       'local_directory': '/var/folders/0d/287bxwpd3gg9vh0qxtht1bs80000gn/T/nanny-mcx6pg_2',
                                       'memory': 2540118016,
                                       'memory-rss': 14905344,
                                       'memory-vms': 2540118016,
                                       'memory_limit': 1288490188.0,
                                       'name': 'tcp://127.0.0.1:62777',
                                       'ncores': 1,
                                       'ready': 0,
                                       'services': {'nanny': 62763},
                                       'time-delay': 0.0027408599853515625},
             'tcp://127.0.0.1:62780': {'executing': 0,
                                       'host': '127.0.0.1',
                                       'in_flight': 0,
                                       'in_memory': 0,
                                       'last-seen': 1495994175.668864,
                                       'local_directory': '/var/folders/0d/287bxwpd3gg9vh0qxtht1bs80000gn/T/nanny-t6_qg_h6',
                                       'memory': 2540118016,
                                       'memory-rss': 14786560,
                                       'memory-vms': 2540118016,
                                       'memory_limit': 1288490188.0,
                                       'name': 'tcp://127.0.0.1:62780',
                                       'ncores': 1,
                                       'ready': 0,
                                       'services': {'nanny': 62764},
                                       'time-delay': 0.003049135208129883},
             'tcp://127.0.0.1:62783': {'executing': 0,
                                       'host': '127.0.0.1',
                                       'in_flight': 0,
                                       'in_memory': 0,
                                       'last-seen': 1495994175.673749,
                                       'local_directory': '/var/folders/0d/287bxwpd3gg9vh0qxtht1bs80000gn/T/nanny-16onmj3y',
                                       'memory': 2531729408,
                                       'memory-rss': 14811136,
                                       'memory-vms': 2531729408,
                                       'memory_limit': 1288490188.0,
                                       'name': 'tcp://127.0.0.1:62783',
                                       'ncores': 1,
                                       'ready': 0,
                                       'services': {'nanny': 62765},
                                       'time-delay': 0.0026509761810302734},
             'tcp://127.0.0.1:62785': {'executing': 0,
                                       'host': '127.0.0.1',
                                       'in_flight': 0,
                                       'in_memory': 0,
                                       'last-seen': 1495994175.675703,
                                       'local_directory': '/var/folders/0d/287bxwpd3gg9vh0qxtht1bs80000gn/T/nanny-l24eyeuq',
                                       'memory': 2540118016,
                                       'memory-rss': 14880768,
                                       'memory-vms': 2540118016,
                                       'memory_limit': 1288490188.0,
                                       'name': 'tcp://127.0.0.1:62785',
                                       'ncores': 1,
                                       'ready': 0,
                                       'services': {'nanny': 62767},
                                       'time-delay': 0.002117156982421875},
             'tcp://127.0.0.1:62787': {'executing': 0,
                                       'host': '127.0.0.1',
                                       'in_flight': 0,
                                       'in_memory': 0,
                                       'last-seen': 1495994175.680715,
                                       'local_directory': '/var/folders/0d/287bxwpd3gg9vh0qxtht1bs80000gn/T/nanny-43f1hmhp',
                                       'memory': 2531729408,
                                       'memory-rss': 14856192,
                                       'memory-vms': 2531729408,
                                       'memory_limit': 1288490188.0,
                                       'name': 'tcp://127.0.0.1:62787',
                                       'ncores': 1,
                                       'ready': 0,
                                       'services': {'nanny': 62770},
                                       'time-delay': 0.0026798248291015625}}}
```
Clearly 8 workers get successfully created, but why am I unable to connect to the web ui. Am I looking at the wrong port. Neither the default of 8787 not any of the 'nanny ports' work. How do I know where to look?

**Comment by mrocklin** [comment]
Note that Bokeh and Tornado have a known incompatibility.  If your tornado version is 4.5 then you might consider downgrading to 4.4.

**Comment by baasman** [comment]
Hi mkrocklin, thanks for the suggestion.

I downgraded Tornado to 4.4, bokeh is version 0.12.0. Still experiencing same the same problem. With the scheduler info I showed above, is there anything to suggest I should not be looking at port 8787?

**Comment by mrocklin** [comment]
Ah, yes, given this information

```python
{'address': 'tcp://127.0.0.1:62759',
 'id': 'b325775c-43ce-11e7-a3a7-9801a7b6f57d',
 'services': {},
 'type': 'Scheduler',
```

We see that the bokeh service is missing.  I would expect the following:

```python
 'services': {'bokeh': 8787},
```

I see that you had trouble connection to a scheduler on localhost.  Have you started a scheduler on localhost?  If not then you may want to read through this documentation: http://distributed.readthedocs.io/en/latest/setup.html

**Comment by baasman** [comment]
Good point. When I start it on the command line I don't get a link to the bokeh ui:

```
Boudewijns-MBP:Frameworks baasman$ dask-scheduler
distributed.scheduler - INFO - -----------------------------------------------
distributed.scheduler - INFO -   Scheduler at:    tcp://192.168.1.2:8786
distributed.scheduler - INFO -        http at:              0.0.0.0:9786
distributed.scheduler - INFO - Local Directory: /var/folders/0d/287bxwpd3gg9vh0qxtht1bs80000gn/T/scheduler-y2nzu92l
distributed.scheduler - INFO - -----------------------------------------------
distributed.scheduler - INFO - Receive client connection: 8241df06-43f9-11e7-9915-9801a7b6f57d
```

I started a worker like this:
```
Boudewijns-MBP:dask-tutorial baasman$ dask-worker 192.168.1.2:8786
distributed.nanny - INFO -         Start Nanny at: 'tcp://192.168.1.2:63972'
distributed.worker - INFO -       Start worker at:    tcp://192.168.1.2:63973
distributed.worker - INFO -               http at:          192.168.1.2:63974
distributed.worker - INFO -              nanny at:          192.168.1.2:63972
distributed.worker - INFO - Waiting to connect to:     tcp://192.168.1.2:8786
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          8
distributed.worker - INFO -                Memory:                   10.31 GB
distributed.worker - INFO -       Local Directory: /var/folders/0d/287bxwpd3gg9vh0qxtht1bs80000gn/T/nanny-g4_9j188
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -         Registered to:           tcp://192.168.1.2:8786
distributed.worker - INFO - -------------------------------------------------
distributed.nanny - INFO - Nanny 'tcp://192.168.1.2:63972' starts worker process 'tcp://192.168.1.2:63973'
```
And connected like this:
```
In [10]: c = Client('192.168.1.2:8786')

In [11]: c
Out[11]: <Client: scheduler='tcp://192.168.1.2:8786' processes=1 cores=8>

In [12]: c.scheduler_info()
Out[12]:
{'address': 'tcp://192.168.1.2:8786',
 'id': 'e5cc1530-43f9-11e7-8388-9801a7b6f57d',
 'services': {'http': 9786},
 'type': 'Scheduler',
 'workers': {'tcp://192.168.1.2:63973': {'executing': 0,
   'host': '192.168.1.2',
   'in_flight': 0,
   'in_memory': 0,
   'last-seen': 1496012858.012229,
   'local_directory': '/var/folders/0d/287bxwpd3gg9vh0qxtht1bs80000gn/T/nanny-g4_9j188',
   'memory': 2534387712,
   'memory-rss': 18673664,
   'memory-vms': 2534387712,
   'memory_limit': 10307921510.0,
   'name': 'tcp://192.168.1.2:63973',
   'ncores': 8,
   'ready': 0,
   'services': {'http': 63974, 'nanny': 63972},
   'time-delay': 0.003401041030883789}}}
```

**Comment by mrocklin** [comment]
So when I do this I get the following:

```
distributed.scheduler - INFO - -----------------------------------------------
distributed.scheduler - INFO -   Scheduler at: tcp://192.168.50.100:8786
distributed.scheduler - INFO -        http at:              0.0.0.0:9786
distributed.scheduler - INFO -       bokeh at:              0.0.0.0:8787
distributed.scheduler - INFO - Local Directory:    /tmp/scheduler-sqnkvppo
distributed.scheduler - INFO - -----------------------------------------------
```

My first guess is that there is something failing at import.  What does the following give you?

```python
from distributed.bokeh.scheduler import BokehScheduler
```

**Comment by baasman** [comment]
Welp I'm dumb, the problem is solved on my windows computer at work. Seems like an update of bokeh was all it took.

I'll try to update bokeh once I get home, but I'm 99% that will fix the issue on my mac. I guess for some reason I though 0.12.0 was the latest but going up to 0.12.5 solved the issue.

Thanks!
