### ISSUE TITLE
Reading empty parquet files causes an exception

### ISSUE THREAD

**Issue by shughes-uk** [dask/dask#2444]
Related to #2437 
Reading in an empty parquet file generated when to_parquet is used with an empty dataframe results in 

```
Traceback (most recent call last):
  File "/Users/shughes/Programming/anaconda-stats/util_scripts/influx_importer.py", line 264, in <module>
    main(sys.argv)
  File "/Users/shughes/Programming/anaconda-stats/util_scripts/influx_importer.py", line 260, in main
    upload(args)
  File "/Users/shughes/Programming/anaconda-stats/util_scripts/influx_importer.py", line 130, in upload
    upload_parquet(target_files, db_client, args.measurement_n, args.start_dt, args.end_dt)
  File "/Users/shughes/Programming/anaconda-stats/util_scripts/influx_importer.py", line 93, in upload_parquet
    df, f_cols, t_cols = parse_parquet(target_dirs, start_dt, end_dt)
  File "/Users/shughes/Programming/anaconda-stats/util_scripts/influx_importer.py", line 139, in parse_parquet
    dfs.append(dask.dataframe.read_parquet(directory, index='timestamp'))
  File "/Users/shughes/miniconda3/lib/python3.5/site-packages/dask/dataframe/io/parquet.py", line 287, in read_parquet
    categories=categories, index=index)
  File "/Users/shughes/miniconda3/lib/python3.5/site-packages/dask/dataframe/io/parquet.py", line 110, in _read_fastparquet
    minmax = fastparquet.api.sorted_partitioned_columns(pf)
  File "/Users/shughes/miniconda3/lib/python3.5/site-packages/fastparquet/api.py", line 599, in sorted_partitioned_columns
    s = statistics(pf)
  File "/Users/shughes/miniconda3/lib/python3.5/site-packages/fastparquet/api.py", line 567, in statistics
    for col in obj.row_groups[0].columns:
IndexError: list index out of range
```
I believe the tests didn't catch this because they don't set/expect an index?

**Comment by martindurant** [comment]
You keep catching the corners!

**Comment by shughes-uk** [comment]
I have a 750gb dataset which feels like it's nothing but corners!
