### ISSUE TITLE
Parquet file paths sporadically end up with an extra _metadata on the end

### ISSUE THREAD

**Issue by shughes-uk** [dask/dask#2463]
So I  pass the following to read_parquet '/mnt/bigdisk/csv_data/parsed/conda_raw_parquet/2017/01/25'
And sometimes the below exception will happen. This is in conjunction with distributed (never seen it happen on its own, but I run it without distributed a lot less). It complains the file path doesn't exist and well that's true but it shouldn't be looking for _metadata/_metadata. I'm not sure whether this is a dask,distributed or fastparquet error. 

This only happens intermittently and I can rerun it with the exact same dataset and have it work fine so i'm really stuck on how to reproduce this one.
```
Traceback (most recent call last):
File "/home/atxstats/miniconda3/lib/python3.6/site-packages/fastparquet/api.py", line 92, in __init__
with open_with(fn2, 'rb') as f:
File "/home/atxstats/miniconda3/lib/python3.6/site-packages/dask/bytes/core.py", line 311, in __enter__
 f = f2 = self.myopen(self.path, mode=mode)
 File "/home/atxstats/miniconda3/lib/python3.6/site-packages/dask/bytes/local.py", line 61, in open
 return open(path, mode=mode)
 NotADirectoryError: [Errno 20] Not a directory: '/mnt/bigdisk/csv_data/parsed/conda_raw_parquet/2017/01/25/_metadata/_metadata'
During handling of the above exception, another exception occurred:
[ Traceback (most recent call last):
 File "/home/atxstats/miniconda3/lib/python3.6/site-packages/dask/dataframe/io/parquet.py", line 56, in _read_fastparquet
 sep=fs.sep)
 File "/home/atxstats/miniconda3/lib/python3.6/site-packages/fastparquet/api.py", line 98, in __init__
 self._parse_header(f, verify)
File "/home/atxstats/miniconda3/lib/python3.6/site-packages/fastparquet/api.py", line 121, in _parse_header
 f.seek(-(head_size+8), 2)
 OSError: [Errno 22] Invalid argument
```

**Comment by martindurant** [comment]
It is expected behaviour to when for `"_metadata"` files that might not be there, since we cannot know whether the passed path is a directory of parquet or an actual parquet file. I see there is some duplication at https://github.com/dask/dask/blob/master/dask/dataframe/io/parquet.py#L54 , which test also happens in fastparquet and presumably leads to the unnecessary _metadata/_metadata checks.

The actual error, though, is that a purported metadata file has been found, *some* bytes must have been read to calculate the head_size, but this size is not correct for the file. Given that the problem is intermittent, it is possible that the file is being written to while it's being read?
