### ISSUE TITLE
da.store for hdf file or to_hdf fails with distributed scheduler

### ISSUE THREAD

**Issue by martindurant** [dask/dask#2488]
h5py File objects do not serialize, so they can only be shared between tasks with the threaded scheduler. da.to_hdf creates an h5py File and then calls store. 
Naturally, this only makes sense if the workers are on the same machine or otherwise have access to the same network file-system. Producing many hdf files from one dataset does not necessarily make much sense for arrays as opposed to dataframes.

dataframe's to_hdf is already fixed in this respect, so presumably some of that logic could be copied here.

**Comment by mrocklin** [comment]
If you haven't already you may want to read the conversation here: https://github.com/pydata/xarray/issues/798

**Comment by martindurant** [comment]
That is quite a path; but I wasn't sure whether the brief mention of writing had been solved or not. Certainly it's not in dask.array:
```
In [1]: from dask.distributed import Client
In [2]: c = Client(n_workers=4)
In [3]: import dask.array as da
In [4]: x = da.random.random(1000, chunks=(100, ))
In [5]: x.to_hdf5('out.hd5', '/data')
distributed.protocol.core - CRITICAL - Failed to Serialize
Traceback (most recent call last):
  File "/Users/mdurant/Downloads/distributed/distributed/protocol/pickle.py", line 38, in dumps
    result = pickle.dumps(x, protocol=pickle.HIGHEST_PROTOCOL)
AttributeError: Can't pickle local object 'insert_to_ooc.<locals>.store'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/mdurant/Downloads/distributed/distributed/protocol/core.py", line 43, in dumps
    for key, value in data.items()
  File "/Users/mdurant/Downloads/distributed/distributed/protocol/core.py", line 44, in <dictcomp>
    if type(value) is Serialize}
  File "/Users/mdurant/Downloads/distributed/distributed/protocol/serialize.py", line 138, in serialize
    header, frames = {}, [pickle.dumps(x)]
  File "/Users/mdurant/Downloads/distributed/distributed/protocol/pickle.py", line 51, in dumps
    return cloudpickle.dumps(x, protocol=pickle.HIGHEST_PROTOCOL)
  File "/Users/mdurant/anaconda/lib/python3.5/site-packages/cloudpickle/cloudpickle.py", line 706, in dumps
    cp.dump(obj)
  File "/Users/mdurant/anaconda/lib/python3.5/site-packages/cloudpickle/cloudpickle.py", line 146, in dump
    return Pickler.dump(self, obj)
  File "/Users/mdurant/anaconda/lib/python3.5/pickle.py", line 408, in dump
    self.save(obj)
  File "/Users/mdurant/anaconda/lib/python3.5/pickle.py", line 475, in save
    f(self, obj) # Call unbound method with explicit self
  File "/Users/mdurant/anaconda/lib/python3.5/pickle.py", line 740, in save_tuple
    save(element)
  File "/Users/mdurant/anaconda/lib/python3.5/pickle.py", line 495, in save
    rv = reduce(self.proto)
TypeError: can't pickle _thread.lock objects
```

**Comment by mrocklin** [comment]
No, this hasn't been resolved.  Mostly I wanted to make sure that you were aware of the other challenges here, like performance issues when opening/closing hdf files repeatedly.

**Comment by jakirkham** [comment]
Just leaving this note here, it appears [this is the relevant locking code]( https://github.com/dask/dask/blob/0.16.1/dask/dataframe/io/hdf.py#L163-L180 ) that `dask.dataframe` uses, which `dask.array` would need for `to_hdf5`. It's unclear to me whether that `get` needs to be used beyond lock determination for `dask.array` or whether `store` can simply take over at that point.

**Comment by jakirkham** [comment]
Also linking issue ( https://github.com/dask/dask/issues/3074 ) in case anyone here as other thoughts or suggestions to add to the proposals there.
