### ISSUE TITLE
da.where breaks on non-bool condition

### ISSUE THREAD

**Issue by bmerry** [dask/dask#2526]
Using dask 0.15.1, numpy 1.13.1, Python 2.7, the following code throws an exception with dask, while the equivalent numpy code works correctly:
```python
>>> import numpy as np
>>> import dask.array as da
>>> a = da.arange(4, dtype=np.uint8, chunks=(4,))
>>> da.where(a, 1, 0).compute()
Traceback (most recent call last):
  File "dask-where.py", line 6, in <module>
    da.where(a, 1, 0).compute()
  File "/home/bmerry/work/sdp/env/local/lib/python2.7/site-packages/dask/base.py", line 98, in compute
    (result,) = compute(self, traverse=False, **kwargs)
  File "/home/bmerry/work/sdp/env/local/lib/python2.7/site-packages/dask/base.py", line 205, in compute
    results = get(dsk, keys, **kwargs)
  File "/home/bmerry/work/sdp/env/local/lib/python2.7/site-packages/dask/threaded.py", line 75, in get
    pack_exception=pack_exception, **kwargs)
  File "/home/bmerry/work/sdp/env/local/lib/python2.7/site-packages/dask/local.py", line 521, in get_async
    raise_exception(exc, tb)
  File "/home/bmerry/work/sdp/env/local/lib/python2.7/site-packages/dask/local.py", line 290, in execute_task
    result = _execute_task(task, data)
  File "/home/bmerry/work/sdp/env/local/lib/python2.7/site-packages/dask/local.py", line 271, in _execute_task
    return func(*args2)
  File "/home/bmerry/work/sdp/env/local/lib/python2.7/site-packages/dask/array/core.py", line 2796, in variadic_choose
    return np.choose(a, choices)
  File "/home/bmerry/work/sdp/env/local/lib/python2.7/site-packages/numpy/core/fromnumeric.py", line 354, in choose
    return _wrapfunc(a, 'choose', choices, out=out, mode=mode)
  File "/home/bmerry/work/sdp/env/local/lib/python2.7/site-packages/numpy/core/fromnumeric.py", line 57, in _wrapfunc
    return getattr(obj, method)(*args, **kwds)
ValueError: invalid entry in choice array
```

From what I can see, `da.where` is being implemented using `np.choose` rather than `np.where`, and so `np.choose` is trying to use the raw value of the condition rather than its truthiness to index one of the two outputs.

**Comment by jcrist** [comment]
Thanks for the issue report. Fixed by #2543.
