### ISSUE TITLE
pip installation not working?

### ISSUE THREAD

**Issue by jliebrand** [dask/dask#2596]
I installed dask using pip:
```
pip install dask[complete]
```

which gives me:
```
pip list
....
dask (0.15.1)
numpy (1.8.2)
....
```

I then created a wee little test script:
```
import dask.dataframe as dd
print 'done'
```

But that fails with the following error:
```
/usr/local/lib/python2.7/dist-packages/dask/array/numpy_compat.py:32: RuntimeWarning: divide by zero encountered in divide
  not np.allclose(np.divide(1, .5, dtype='i8'), 2) or
Traceback (most recent call last):
  File "./tools/panda_test.py", line 1, in <module>
    import dask.dataframe as dd
  File "/usr/local/lib/python2.7/dist-packages/dask/dataframe/__init__.py", line 3, in <module>
    from .core import (DataFrame, Series, Index, _Frame, map_partitions,
  File "/usr/local/lib/python2.7/dist-packages/dask/dataframe/core.py", line 19, in <module>
    from .. import array as da
  File "/usr/local/lib/python2.7/dist-packages/dask/array/__init__.py", line 13, in <module>
    from .ufunc import (add, subtract, multiply, divide, logaddexp, logaddexp2,
  File "/usr/local/lib/python2.7/dist-packages/dask/array/ufunc.py", line 138, in <module>
    cbrt = ufunc(np.cbrt)
AttributeError: 'module' object has no attribute 'cbrt'
```

Should I install something else as well?

**Comment by jliebrand** [comment]
Tried installing from source and then pip installing the deps and running the tests:

```
============================================================================== test session starts ===============================================================================
platform linux2 -- Python 2.7.9, pytest-3.2.0, py-1.4.34, pluggy-0.4.0
rootdir: /opt/dask, inifile:
/opt/dask/dask/array/numpy_compat.py:32: RuntimeWarning: divide by zero encountered in divide
  not np.allclose(np.divide(1, .5, dtype='i8'), 2) or
collected 0 items / 1 errors

===================================================================================== ERRORS =====================================================================================
_______________________________________________________________________________ ERROR collecting  ________________________________________________________________________________
/usr/local/lib/python2.7/dist-packages/py/_path/common.py:372: in visit
    for x in Visitor(fil, rec, ignore, bf, sort).gen(self):
/usr/local/lib/python2.7/dist-packages/py/_path/common.py:411: in gen
    if p.check(dir=1) and (rec is None or rec(p))])
/usr/local/lib/python2.7/dist-packages/_pytest/main.py:728: in _recurse
    ihook = self.gethookproxy(path)
/usr/local/lib/python2.7/dist-packages/_pytest/main.py:632: in gethookproxy
    my_conftestmodules = pm._getconftestmodules(fspath)
/usr/local/lib/python2.7/dist-packages/_pytest/config.py:356: in _getconftestmodules
    mod = self._importconftest(conftestpath)
/usr/local/lib/python2.7/dist-packages/_pytest/config.py:381: in _importconftest
    raise ConftestImportFailure(conftestpath, sys.exc_info())
E   ConftestImportFailure: AttributeError("'module' object has no attribute 'cbrt'",)
E     File "/opt/dask/dask/array/__init__.py", line 14, in <module>
E       from .ufunc import (add, subtract, multiply, divide, logaddexp, logaddexp2,
E     File "/opt/dask/dask/array/ufunc.py", line 138, in <module>
E       cbrt = ufunc(np.cbrt)
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 1 errors during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
============================================================================ 1 error in 0.43 seconds =============================================================================
```

**Comment by martindurant** [comment]
`np.cbrt` seems to have appeared in numpy version 1.10.0

**Comment by jliebrand** [comment]
Yeah, I just re-created my docker image from scratch (and thereby updated a bunch of things), and now I'm running
numpy 1.13.1

and all is well again :-)
