### ISSUE TITLE
Rading a parquet file created in Spark fails

### ISSUE THREAD

**Issue by keiv-fly** [dask/dask#2599]
Rading a parquet file created in Spark 2.1.0 fails.

Saving in Spark:
```
spark.conf.set("parquet.enable.summary-metadata",true)
df.write.parquet(raw"C:\Users\...")
```

```
>>> dask.__version__
'0.14.0'
```

Loading in Dask:
```
ddf=dd.read_parquet(r'..\Data\Parq')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\xxx\AppData\Local\Continuum\Anaconda3\lib\site-packages\dask\dataframe\io\parquet.py", line 85, in read_parquet
    minmax = fastparquet.api.sorted_partitioned_columns(pf)
  File "C:\Users\xxx\AppData\Local\Continuum\Anaconda3\lib\site-packages\fastparquet\api.py", line 508, in sorted_partitioned_columns
    s = statistics(pf)
  File "C:\Users\xxx\AppData\Local\Continuum\Anaconda3\lib\site-packages\fastparquet\api.py", line 470, in statistics
    L = list(map(statistics, obj.row_groups))
  File "C:\Users\xxx\AppData\Local\Continuum\Anaconda3\lib\site-packages\fastparquet\api.py", line 467, in statistics
    for c in obj.columns}
  File "C:\Users\xxx\AppData\Local\Continuum\Anaconda3\lib\site-packages\fastparquet\api.py", line 467, in <dictcomp>
    for c in obj.columns}
  File "C:\Users\xxx\AppData\Local\Continuum\Anaconda3\lib\site-packages\fastparquet\api.py", line 456, in statistics
    rv['max'] = encoding.read_plain(ensure_bytes(s.max), md.type, 1)[0]
  File "C:\Users\xxx\AppData\Local\Continuum\Anaconda3\lib\site-packages\fastparquet\encoding.py", line 47, in read_plain
    return np.array(unpack_byte_array(raw_bytes, count), dtype='O')
  File "fastparquet/speedups.pyx", line 166, in fastparquet.speedups.unpack_byte_array (fastparquet/speedups.c:3037)
RuntimeError: invalid input size (corrupted?)
```

**Comment by martindurant** [comment]
This bug is known and has been fixed - please update your dask and fastparquet.
