### ISSUE TITLE
start 63 dask-worker using subprocess.Popen

### ISSUE THREAD

**Issue by yzard** [dask/dask#2611]
Hi,

When I start couple of dask-worker on aws, some dask-workers cannot started due to below error messages, I used subprocess.Popen to start 63 dask-worker (for loop), the successful dask-worker runs as command like:

```
/home/ubuntu/.conda/envs/ec2_env/bin/python /home/ubuntu/.conda/envs/ec2_env/bin/dask-worker --nprocs 1 --nthreads 1 --tls-ca-file files/ca_cert.pem --tls-cert files/fullchain.pem --tls-key files/privkey.pem --listen-address tcp://172.31.12.31:34886 --contact-address tcp://52.15.142.197:34886 dask.appraisal.ai:10000
```

Error log:
```
(ec2_env)ubuntu@ip-172-31-12-31:/tmp$ cat dask-worker.36.log
Traceback (most recent call last):
  File "/home/ubuntu/.conda/envs/ec2_env/bin/dask-worker", line 11, in <module>
    load_entry_point('distributed==1.18.0+17.g980d014', 'console_scripts', 'dask-worker')()
  File "/home/ubuntu/.conda/envs/ec2_env/lib/python2.7/site-packages/setuptools-27.2.0-py2.7.egg/pkg_resources/__init__.py", line 565, in load_entry_point
  File "/home/ubuntu/.conda/envs/ec2_env/lib/python2.7/site-packages/setuptools-27.2.0-py2.7.egg/pkg_resources/__init__.py", line 2598, in load_entry_point
  File "/home/ubuntu/.conda/envs/ec2_env/lib/python2.7/site-packages/setuptools-27.2.0-py2.7.egg/pkg_resources/__init__.py", line 2258, in load
  File "/home/ubuntu/.conda/envs/ec2_env/lib/python2.7/site-packages/setuptools-27.2.0-py2.7.egg/pkg_resources/__init__.py", line 2264, in resolve
  File "/home/ubuntu/.conda/envs/ec2_env/lib/python2.7/site-packages/distributed-1.18.0+17.g980d014-py2.7.egg/distributed/__init__.py", line 4, in <module>
    from .core import connect, rpc
  File "/home/ubuntu/.conda/envs/ec2_env/lib/python2.7/site-packages/distributed-1.18.0+17.g980d014-py2.7.egg/distributed/core.py", line 18, in <module>
    from .comm import (connect, listen, CommClosedError,
  File "/home/ubuntu/.conda/envs/ec2_env/lib/python2.7/site-packages/distributed-1.18.0+17.g980d014-py2.7.egg/distributed/comm/__init__.py", line 17, in <module>
    _register_transports()
  File "/home/ubuntu/.conda/envs/ec2_env/lib/python2.7/site-packages/distributed-1.18.0+17.g980d014-py2.7.egg/distributed/comm/__init__.py", line 13, in _register_transports
    from . import inproc
  File "/home/ubuntu/.conda/envs/ec2_env/lib/python2.7/site-packages/distributed-1.18.0+17.g980d014-py2.7.egg/distributed/comm/inproc.py", line 15, in <module>
    from ..protocol import nested_deserialize
  File "/home/ubuntu/.conda/envs/ec2_env/lib/python2.7/site-packages/distributed-1.18.0+17.g980d014-py2.7.egg/distributed/protocol/__init__.py", line 6, in <module>
    from .core import (dumps, loads, maybe_compress, decompress, msgpack)
  File "/home/ubuntu/.conda/envs/ec2_env/lib/python2.7/site-packages/distributed-1.18.0+17.g980d014-py2.7.egg/distributed/protocol/core.py", line 6, in <module>
    import msgpack
  File "build/bdist.linux-x86_64/egg/msgpack/__init__.py", line 25, in <module>
  File "build/bdist.linux-x86_64/egg/msgpack/_packer.py", line 7, in <module>
  File "build/bdist.linux-x86_64/egg/msgpack/_packer.py", line 4, in __bootstrap__
  File "/home/ubuntu/.conda/envs/ec2_env/lib/python2.7/site-packages/setuptools-27.2.0-py2.7.egg/pkg_resources/__init__.py", line 1203, in resource_filename
  File "/home/ubuntu/.conda/envs/ec2_env/lib/python2.7/site-packages/setuptools-27.2.0-py2.7.egg/pkg_resources/__init__.py", line 1715, in get_resource_filename
  File "/home/ubuntu/.conda/envs/ec2_env/lib/python2.7/site-packages/setuptools-27.2.0-py2.7.egg/pkg_resources/__init__.py", line 1745, in _extract_resource
  File "/home/ubuntu/.conda/envs/ec2_env/lib/python2.7/site-packages/setuptools-27.2.0-py2.7.egg/pkg_resources/__init__.py", line 1270, in get_cache_path
  File "/home/ubuntu/.conda/envs/ec2_env/lib/python2.7/site-packages/setuptools-27.2.0-py2.7.egg/pkg_resources/__init__.py", line 1250, in extraction_error
pkg_resources.ExtractionError: Can't extract file(s) to egg cache

The following error occurred while trying to extract file(s) to the Python egg
cache:

  [Errno 17] File exists: '/home/ubuntu/.cache/Python-Eggs'

The Python egg cache directory is currently set to:

  /home/ubuntu/.cache/Python-Eggs

Perhaps your account does not have write access to this directory?  You can
change the cache directory by setting the PYTHON_EGG_CACHE environment
variable to point to an accessible directory.
```

The conda environment is:
```
(ec2_env)ubuntu@ip-172-31-12-31:/tmp$ conda list
# packages in environment at /home/ubuntu/.conda/envs/ec2_env:
#
DEPRECATION: The default format will switch to columns in the future. You can use --format=(legacy|columns) (or define a format=(legacy|columns) in your pip.conf under the [list] section) to disable this warning.
asn1crypto                0.22.0                   py27_0
backports                 1.0                      py27_0
backports-abc             0.5                       <pip>
backports.shutil-get-terminal-size 1.0.0                     <pip>
backports.ssl-match-hostname 3.4.0.2                   <pip>
backports_abc             0.5                      py27_0
begins                    0.9                       <pip>
bleach                    1.5.0                    py27_0
boto                      2.48.0                   py27_0
cairo                     1.14.8                        0
cffi                      1.10.0                   py27_0
chardet                   3.0.4                     <pip>
click                     6.7                      py27_0
click-plugins             1.0.3                    py27_0
cligj                     0.4.0                    py27_0
cloud                     2.8.5                     <pip>
cloudpickle               0.2.2                    py27_0
configparser              3.5.0                    py27_0
contexttimer              0.3.3                     <pip>
cryptography              1.8.1                    py27_0
cssselect                 1.0.1                     <pip>
cssutils                  1.0.2                     <pip>
curl                      7.49.0                        1
cycler                    0.10.0                   py27_0
dask                      0.15.1                    <pip>
dask-searchcv             0.0.2                     <pip>
dbus                      1.10.20                       0
decorator                 4.1.2                    py27_0
distributed               1.18.0+17.g980d014           <pip>
emails                    0.5.15                    <pip>
entrypoints               0.2.3                    py27_0
enum34                    1.1.6                    py27_0
expat                     2.1.0                         0
fiona                     1.7.0                    py27_0
flask                     0.12.2                    <pip>
flask-httpauth            3.2.3                     <pip>
fontconfig                2.12.1                        3
freetype                  2.5.5                         2
funcsigs                  1.0.2                     <pip>
functools32               3.2.3.2                  py27_0
futures                   3.1.1                     <pip>
geos                      3.5.0                         0
geotiff                   1.4.1                         0
get_terminal_size         1.0.0                    py27_0
glib                      2.50.2                        1
gst-plugins-base          1.8.0                         0
gstreamer                 1.8.0                         0
gunicorn                  19.7.1                    <pip>
h5py                      2.7.0               np113py27_0
hdf4                      4.2.12                        1
hdf5                      1.8.17                        2
heapdict                  1.0.0                     <pip>
html5lib                  0.9999999                py27_0
icu                       54.1                          0
idna                      2.5                      py27_0
ipaddress                 1.0.18                   py27_0
ipykernel                 4.6.1                    py27_0
ipython                   5.3.0                    py27_0
ipython-genutils          0.2.0                     <pip>
ipython_genutils          0.2.0                    py27_0
ipywidgets                6.0.0                    py27_0
iso8601                   0.1.12                   py27_0
itsdangerous              0.24                      <pip>
jbig                      2.1                           0
jinja2                    2.9.6                    py27_0
jpeg                      9b                            0
jsonschema                2.6.0                    py27_0
jupyter                   1.0.0                    py27_3
jupyter-client            5.1.0                     <pip>
jupyter-console           5.1.0                     <pip>
jupyter-core              4.3.0                     <pip>
jupyter_client            5.1.0                    py27_0
jupyter_console           5.1.0                    py27_0
jupyter_core              4.3.0                    py27_0
kealib                    1.4.6                         0
libffi                    3.2.1                         1
libgcc                    5.2.0                         0
libgdal                   2.1.0                         0
libgfortran               3.0.0                         1
libiconv                  1.14                          0
libnetcdf                 4.4.1                         1
libpng                    1.6.27                        0
libsodium                 1.0.10                        0
libtiff                   4.0.6                         3
libxcb                    1.12                          1
libxml2                   2.9.4                         0
lxml                      3.8.0                     <pip>
markupsafe                0.23                     py27_2
matplotlib                2.0.2               np113py27_0
mistune                   0.7.4                    py27_0
mkl                       2017.0.3                      0
msgpack-python            0.4.8                     <pip>
munch                     2.1.1                    py27_0
nbconvert                 5.2.1                    py27_0
nbformat                  4.3.0                    py27_0
notebook                  5.0.0                    py27_0
numexpr                   2.6.2               np113py27_0
numpy                     1.13.1                   py27_0
openssl                   1.0.2l                        0
packaging                 16.8                     py27_0
pandas                    0.20.3                   py27_0
pandocfilters             1.4.1                    py27_0
paramiko                  2.1.2                    py27_0
path.py                   10.3.1                   py27_0
pathlib2                  2.3.0                    py27_0
pcre                      8.39                          1
pexpect                   4.2.1                    py27_0
pickleshare               0.7.4                    py27_0
pip                       9.0.1                    py27_1
pixman                    0.34.0                        0
plotly                    2.0.11                   py27_0
premailer                 3.1.1                     <pip>
proj4                     4.9.2                         0
prompt-toolkit            1.0.14                    <pip>
prompt_toolkit            1.0.14                   py27_0
psutil                    5.2.2                     <pip>
ptyprocess                0.5.2                    py27_0
pyasn1                    0.2.3                    py27_0
pycairo                   1.10.0                   py27_0
pycparser                 2.18                     py27_0
pygments                  2.2.0                    py27_0
pymysql                   0.7.9                    py27_0
pyparsing                 2.2.0                    py27_0
pyqt                      5.6.0                    py27_2
pytables                  3.4.2               np113py27_0
python                    2.7.13                        0
python-box                3.0.1                     <pip>
python-dateutil           2.6.1                    py27_0
pytz                      2017.2                   py27_0
pyzmq                     16.0.2                   py27_0
qt                        5.6.2                         5
qtconsole                 4.3.0                    py27_0
readline                  6.2                           2
requests                  2.14.2                   py27_0
scandir                   1.5                      py27_0
scikit-learn              0.19.0              np113py27_0
scikit-optimize           0.3                       <pip>
scipy                     0.19.1              np113py27_0
setuptools                27.2.0                   py27_0
simplegeneric             0.8.1                    py27_1
singledispatch            3.4.0.3                  py27_0
sip                       4.18                     py27_0
six                       1.10.0                   py27_0
sortedcontainers          1.5.7                     <pip>
sqlalchemy                1.1.13                   py27_0
sqlite                    3.13.0                        0
ssl_match_hostname        3.4.0.2                  py27_1
subprocess32              3.2.7                    py27_0
tables                    3.4.2                     <pip>
tblib                     1.3.2                     <pip>
terminado                 0.6                      py27_0
testpath                  0.3.1                    py27_0
tk                        8.5.18                        0
toolz                     0.8.2                     <pip>
tornado                   4.5.1                    py27_0
tqdm                      4.15.0                   py27_0
traitlets                 4.3.2                    py27_0
wcwidth                   0.1.7                    py27_0
werkzeug                  0.12.2                    <pip>
wheel                     0.29.0                   py27_0
widgetsnbextension        2.0.0                    py27_0
xerces-c                  3.1.4                         0
xgboost                   0.6                       <pip>
xz                        5.2.2                         1
zeromq                    4.1.5                         0
zict                      0.1.2                     <pip>
zlib                      1.2.8                         3
```

**Comment by mrocklin** [comment]
From the errors that you report it looks like importing the msgpack library is somewhat unsafe to do concurrently.  I haven't seen this before.  

To see if this is indeed the issue I recommend putting a file-based lock around the relevant import statement to see if this makes a difference:

```python
import locket
with locket.lock_file('my-lock'):
    import msgpack
```

**Comment by jcrist** [comment]
Closing as stale. Feel free to reopen if the problem persists and you can provide a [reproducible example](https://stackoverflow.com/help/mcve).
