### ISSUE TITLE
dask run after a few hours, only 1 machine get jobs

### ISSUE THREAD

**Issue by yzard** [dask/dask#2653]
Hi,

I am distributing tasks using dask distributed on 3 machines (m1, m2, m3). Every machine is running multiple dask-worker processes, and there is 1 scheduler is running on m2. I encounter the following problem:
- Initially workers on all 3 machines can get jobs (every machine is fully loaded). After a few hours, only worker machine m1 are getting jobs. No jobs distributed to workers on other 2 machines (m2, m3), I don’t know why, it might related to problem 3) below. here is the snapshot for scheduler, I can see all 3 worker machines are connected to scheduler

![image](https://user-images.githubusercontent.com/678138/29998993-8890982e-9006-11e7-901d-4b6fff1862a2.png)

- The task being distributed to the dask-workers is doing computation that normally take 10-20 mins to get back results, I run multiple tasks like this together.
- Even on machine m1 that can get jobs, I see exceptions in the log like this:

```
Traceback (most recent call last):
  File "/home/zyin/dev/ivm/models/ModelWorkShop.py", line 1018, in Website
    sec = Security(
  File "/home/zyin/.conda/envs/conda/lib/python2.7/site-packages/dask/base.py", line 97, in compute
    (result,) = compute(self, traverse=False, **kwargs)
  File "/home/zyin/.conda/envs/conda/lib/python2.7/site-packages/dask/base.py", line 204, in compute
    results = get(dsk, keys, **kwargs)
  File "/home/zyin/.conda/envs/conda/lib/python2.7/site-packages/distributed/client.py", line 1764, in get
    results = self.gather(packed)
  File "/home/zyin/.conda/envs/conda/lib/python2.7/site-packages/distributed/client.py", line 1263, in gather
    direct=direct)
  File "/home/zyin/.conda/envs/conda/lib/python2.7/site-packages/distributed/client.py", line 489, in sync
    return sync(self.loop, func, *args, **kwargs)
  File "/home/zyin/.conda/envs/conda/lib/python2.7/site-packages/distributed/utils.py", line 234, in sync
    six.reraise(*error[0])
  File "/home/zyin/.conda/envs/conda/lib/python2.7/site-packages/distributed/utils.py", line 223, in f
    result[0] = yield make_coro()
  File "/home/zyin/.conda/envs/conda/lib/python2.7/site-packages/tornado/gen.py", line 1055, in run
    value = future.result()
  File "/home/zyin/.conda/envs/conda/lib/python2.7/site-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "/home/zyin/.conda/envs/conda/lib/python2.7/site-packages/tornado/gen.py", line 1063, in run
    yielded = self.gen.throw(*exc_info)
  File "/home/zyin/.conda/envs/conda/lib/python2.7/site-packages/distributed/client.py", line 1156, in _gather
    traceback)
  File "<string>", line 2, in reraise
ValueError: Could not find dependent HyperparameterOptimizeDistributed-6c55aa47-7595-4dfb-92d0-c0feea545f99.  Check worker logs
```
I got some error logs from dask-worker on machine m1 (the one dask-scheduler can still distribute jobs on):

```
distributed.worker - ERROR - Worker stream died during communication: tcp://173.208.222.74:27664
Traceback (most recent call last):
  File "/home/zyin/.conda/envs/conda/lib/python2.7/site-packages/distributed-1.18.0+48.g5bbc9a2-py2.7.egg/distributed/worker.py", line 1648, in gather_dep
    who=self.address)
  File "/home/zyin/.conda/envs/conda/lib/python2.7/site-packages/tornado/gen.py", line 1055, in run
    value = future.result()
  File "/home/zyin/.conda/envs/conda/lib/python2.7/site-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "/home/zyin/.conda/envs/conda/lib/python2.7/site-packages/tornado/gen.py", line 1063, in run
    yielded = self.gen.throw(*exc_info)
  File "/home/zyin/.conda/envs/conda/lib/python2.7/site-packages/distributed-1.18.0+48.g5bbc9a2-py2.7.egg/distributed/core.py", line 503, in send_recv_from_rpc
    comm = yield self.pool.connect(self.addr)
  File "/home/zyin/.conda/envs/conda/lib/python2.7/site-packages/tornado/gen.py", line 1055, in run
    value = future.result()
  File "/home/zyin/.conda/envs/conda/lib/python2.7/site-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "/home/zyin/.conda/envs/conda/lib/python2.7/site-packages/tornado/gen.py", line 1063, in run
    yielded = self.gen.throw(*exc_info)
  File "/home/zyin/.conda/envs/conda/lib/python2.7/site-packages/distributed-1.18.0+48.g5bbc9a2-py2.7.egg/distributed/core.py", line 607, in connect
    connection_args=self.connection_args)
  File "/home/zyin/.conda/envs/conda/lib/python2.7/site-packages/tornado/gen.py", line 1055, in run
    value = future.result()
  File "/home/zyin/.conda/envs/conda/lib/python2.7/site-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "/home/zyin/.conda/envs/conda/lib/python2.7/site-packages/tornado/gen.py", line 1063, in run
    yielded = self.gen.throw(*exc_info)
  File "/home/zyin/.conda/envs/conda/lib/python2.7/site-packages/distributed-1.18.0+48.g5bbc9a2-py2.7.egg/distributed/comm/core.py", line 194, in connect
    _raise(error)
  File "/home/zyin/.conda/envs/conda/lib/python2.7/site-packages/distributed-1.18.0+48.g5bbc9a2-py2.7.egg/distributed/comm/core.py", line 177, in _raise
    raise IOError(msg)
IOError: Timed out trying to connect to 'tcp://173.208.222.74:27664' after 3.0 s: connect() didn't finish in time
```
scheduler:
```
distributed.scheduler - INFO - Receive client connection: 5ba3b6ea-8ea1-11e7-9721-0002c9c07e82
distributed.scheduler - INFO - Receive client connection: 33162008-8ea3-11e7-b81d-0002c9c07e82
distributed.scheduler - INFO - Receive client connection: f8d6282e-8ec1-11e7-84a8-0002c9c07e82
distributed.scheduler - INFO - Receive client connection: b9b257d0-8ecb-11e7-82f9-0002c9c07e82
distributed.scheduler - ERROR - error from worker tcp://104.247.194.98:38352: Could not find dependent HyperparameterOptimizeDistributed-2bf50198-4a96-4663-808e-733a94afd32d.  Check worker logs
distributed.scheduler - INFO - Receive client connection: 7cba0680-8ee8-11e7-b81d-0002c9c07e82
distributed.scheduler - INFO - Receive client connection: e5c8083e-8ee8-11e7-82f9-0002c9c07e82
distributed.scheduler - INFO - Receive client connection: ce484a6a-8ee9-11e7-84a8-0002c9c07e82
distributed.scheduler - ERROR - error from worker tcp://104.247.194.98:41106: Could not find dependent HyperparameterOptimizeDistributed-6635cc9c-c66f-485e-8a80-a6b35cd17b81.  Check worker logs
distributed.scheduler - INFO - Receive client connection: f6f4ac2e-8ef8-11e7-b81d-0002c9c07e82
distributed.scheduler - INFO - Receive client connection: 822a23f4-8efa-11e7-9721-0002c9c07e82
distributed.scheduler - ERROR - error from worker tcp://104.247.194.98:34880: Could not find dependent HyperparameterOptimizeDistributed-2fa06303-1110-4b4b-9ba0-626112bd1ffa.  Check worker logs
distributed.scheduler - INFO - Receive client connection: a45a63d2-8f0c-11e7-b81d-0002c9c07e82
distributed.scheduler - INFO - Receive client connection: 6ab16a52-8f18-11e7-84a8-0002c9c07e82
distributed.scheduler - INFO - Receive client connection: 941b365a-8f1a-11e7-b81d-0002c9c07e82
distributed.scheduler - ERROR - error from worker tcp://104.247.194.98:35008: Could not find dependent HyperparameterOptimizeDistributed-8dd613e5-9e9f-4821-b848-688b7f819742.  Check worker logs
distributed.scheduler - INFO - Receive client connection: d592607e-8f1d-11e7-82f9-0002c9c07e82
distributed.scheduler - INFO - Receive client connection: f33d51e4-8f20-11e7-82f9-0002c9c07e82
distributed.scheduler - INFO - Receive client connection: 9b4db9fc-8f24-11e7-82f9-0002c9c07e82
distributed.scheduler - INFO - Receive client connection: d2c9f288-8f2e-11e7-9721-0002c9c07e82
distributed.scheduler - INFO - Receive client connection: b1a022a4-8f37-11e7-b81d-0002c9c07e82
distributed.scheduler - INFO - Receive client connection: 9b9d359a-8f3d-11e7-b81d-0002c9c07e82
distributed.scheduler - ERROR - error from worker tcp://104.247.194.98:41106: Could not find dependent HyperparameterOptimizeDistributed-addd06b1-d7c1-4ea5-9cb1-e7ccb09b606b.  Check worker logs
distributed.scheduler - INFO - Receive client connection: d049e11a-8f49-11e7-9721-0002c9c07e82
distributed.scheduler - INFO - Receive client connection: c95b0e36-8f4b-11e7-b81d-0002c9c07e82
distributed.scheduler - ERROR - error from worker tcp://104.247.194.98:35008: Could not find dependent HyperparameterOptimizeDistributed-c8d83c81-4517-4587-a1e7-154a4034ab2c.  Check worker logs
distributed.scheduler - INFO - Receive client connection: 9beb10f2-8f66-11e7-82f9-0002c9c07e82
distributed.scheduler - INFO - Receive client connection: 5af330aa-8f68-11e7-9721-0002c9c07e82
distributed.scheduler - ERROR - error from worker tcp://104.247.194.98:38352: Could not find dependent HyperparameterOptimizeDistributed-3a776062-bcde-427a-8fc1-8e1e6365abf0.  Check worker logs
distributed.scheduler - INFO - Receive client connection: e9cde4fc-8f7f-11e7-84a8-0002c9c07e82
distributed.scheduler - INFO - Receive client connection: 3e08b5d0-8fb5-11e7-82f9-0002c9c07e82
distributed.scheduler - ERROR - error from worker tcp://104.247.194.98:41106: Could not find dependent HyperparameterOptimizeDistributed-6bf0a782-a908-4552-b8ec-434dd299449e.  Check worker logs
distributed.scheduler - INFO - Receive client connection: 53f62810-8fb9-11e7-9721-0002c9c07e82
distributed.scheduler - INFO - Receive client connection: a906a608-8fc9-11e7-b81d-0002c9c07e82
distributed.scheduler - INFO - Receive client connection: 9aafbc06-8fe3-11e7-84a8-0002c9c07e82
distributed.scheduler - ERROR - error from worker tcp://104.247.194.98:35008: Could not find dependent HyperparameterOptimizeDistributed-1e4fe533-df3d-49f0-905f-7a06cacf9d65.  Check worker logs
distributed.scheduler - INFO - Receive client connection: dcd404dc-8ff4-11e7-82f9-0002c9c07e82
distributed.scheduler - ERROR - error from worker tcp://104.247.194.98:38352: Could not find dependent HyperparameterOptimizeDistributed-6c55aa47-7595-4dfb-92d0-c0feea545f99.  Check worker logs
distributed.scheduler - INFO - Receive client connection: 82f866aa-900e-11e7-9721-0002c9c07e82
```

The way I started all dask-worker is:
```
/home/zyin/.conda/envs/conda/bin/python /home/zyin/.conda/envs/conda/bin/dask-worker --tls-ca-file files/ca_cert.pem --tls-cert files/fullchain.pem --tls-key files/privkey.pem --nthreads 1 --nprocs 1 dask.appraisal.ai:10000
```
the command used for starting dask-scheduler is:
```
/home/zyin/.conda/envs/conda/bin/python /home/zyin/.conda/envs/conda/bin/dask-scheduler --tls-ca-file files/ca_cert.pem --tls-cert files/fullchain.pem --tls-key files/privkey.pem --port 10000 --bokeh-port 10001 --http-port 10002
```

**Comment by yzard** [comment]
Hi,

I also noticed in machine m1, this machine has 32 cores and we start 32 dask workers with nthreads=1 and nprocs=1 and the load average mysteriously ends up being > 32 with some dask workers exhibiting abnormally high cpu usage i.e. > 100%

![image](https://user-images.githubusercontent.com/678138/29999105-e7e5bfa4-9009-11e7-8500-cae711073600.png)

**Comment by mrocklin** [comment]
What versions of dask and distributed are you using?  

The `--nthreads` parameter really just limits dask from running multiple tasks at once.  If your tasks use multiple threads then they'll use lots of CPU per worker.  Dask worker processes are just normal Python processes, they aren't limited in any way.

**Comment by mrocklin** [comment]
Have you checked out the status page?  Did anything seem odd when you started to have only one worker active?

I don't suppose you're able to provide a reproducible example that is easy to reproduce and still exhibits the behavior that you've seen?

**Comment by yzard** [comment]
The code is running xgboost, with nthread=2, so it should be like 200 cpu usage, when I restart all the workers and connect to scheduler, every worker with load is using 200 cpu, which is expected. But after a few hours, some dask-worker process is using 500% ~ 600% per dask-worker, as snapshot shows.

The job distributing problem might be because of dask version mismatch, the dask version:
m1:
dask
                          *  0.15.0                   py27_0  defaults
distributed
                          *  1.17.1                   py27_0  defaults
m2:
dask
                          *  0.15.0                   py27_0  defaults
distributed
                          *  1.17.1                   py27_0  defaults
m3:
dask
                          *  0.15.1                   py27_0  defaults
distributed
                          *  1.18.0                   py27_0  defaults

Here is the snapshot for status page
![image](https://user-images.githubusercontent.com/678138/30000716-2775956a-9044-11e7-950f-0313e1a1ebd1.png)

**Comment by yzard** [comment]
I solved the mystery that CPU boosts to 600%, it basically is the xgboost I used, version is mismatched, and they changed parameter nthread to n_jobs, and the new n_jobs if not specify, means will take over all the possible cores.

I will keep it running, right now, all machines has the same dask/distributed version, see if the problem still exists, if not, I will close this bug

**Comment by bansalr** [comment]
An update to the above posted by Yin. The dask-worker dying behavior has been fixed by pinning the versions. However the CPU usage being abnormally high is still extant. Even with starting just one dask-worker with --nthreads=1 --nprocs=1 and passing xgboost n_jobs =1 and nthread =1 we see very high usage (2000+) for a dask worker. 

Another peculiarity we observed was that this only happens when the number of dask clients that are queueing jobs to schedulers is > 1. 

Attached to the dask-worker and printed out info threads. Trace below, it shows a large number of dask-worker threads:

```
(gdb) info threads
  Id   Target Id         Frame 
* 1    Thread 0x7f8b1a4b6700 (LWP 17052) "dask-worker" 0x00007f8b21ac29d3 in epoll_wait () at ../sysdeps/unix/syscall-template.S:84
  2    Thread 0x7f8b19cb5700 (LWP 17054) "dask-worker" 0x00007f8b224a551d in read () at ../sysdeps/unix/syscall-template.S:84
  3    Thread 0x7f8b19474700 (LWP 17055) "dask-worker" 0x00007f8b21ab670d in poll () at ../sysdeps/unix/syscall-template.S:84
  4    Thread 0x7f8b18c33700 (LWP 17056) "dask-worker" 0x00007f8b224a4827 in futex_abstimed_wait_cancelable (private=0, abstime=0x0, expected=0, futex_word=0x7f8b10000de0) at ../sysdeps/unix/sysv/linux/futex-internal.h:205
  5    Thread 0x7f8b0bfff700 (LWP 17112) "dask-worker" 0x00007f8b224a4827 in futex_abstimed_wait_cancelable (private=0, abstime=0x0, expected=0, futex_word=0x7f8b04cc13f0) at ../sysdeps/unix/sysv/linux/futex-internal.h:205
  6    Thread 0x7f8af17e2700 (LWP 17147) "dask-worker" pthread_cond_wait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
  7    Thread 0x7f8af1fe3700 (LWP 17148) "dask-worker" pthread_cond_wait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
  8    Thread 0x7f8af27e4700 (LWP 17149) "dask-worker" pthread_cond_wait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
  9    Thread 0x7f8af2fe5700 (LWP 17150) "dask-worker" pthread_cond_wait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
  10   Thread 0x7f8b03fff700 (LWP 17151) "dask-worker" pthread_cond_wait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
  11   Thread 0x7f8b037fe700 (LWP 17152) "dask-worker" pthread_cond_wait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
  12   Thread 0x7f8afeffd700 (LWP 17153) "dask-worker" pthread_cond_wait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
  13   Thread 0x7f8afe7fc700 (LWP 17154) "dask-worker" pthread_cond_wait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
  14   Thread 0x7f8afbcdc700 (LWP 17155) "dask-worker" 0x00007f8afc116641 in double xgboost::tree::CalcGain<xgboost::tree::TrainParam, double>(xgboost::tree::TrainParam const&, double, double) ()
   from /home/zyin/.conda/envs/conda_pined/lib/python2.7/site-packages/xgboost-0.6-py2.7.egg/xgboost/libxgboost.so
  15   Thread 0x7f8afb45b700 (LWP 17229) "dask-worker" 0x00007f8b224a4827 in futex_abstimed_wait_cancelable (private=0, abstime=0x0, expected=0, futex_word=0x7f8a84000b30) at ../sysdeps/unix/sysv/linux/futex-internal.h:205
  16   Thread 0x7f8afa625700 (LWP 17262) "dask-worker" pthread_cond_wait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
  17   Thread 0x7f8af9e24700 (LWP 17263) "dask-worker" pthread_cond_wait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
  18   Thread 0x7f8af9623700 (LWP 17264) "dask-worker" pthread_cond_wait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
  19   Thread 0x7f8af8e22700 (LWP 17265) "dask-worker" pthread_cond_wait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
  20   Thread 0x7f8af3fff700 (LWP 17266) "dask-worker" pthread_cond_wait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
  21   Thread 0x7f8af37fe700 (LWP 17267) "dask-worker" pthread_cond_wait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
  22   Thread 0x7f8a9f05e700 (LWP 17268) "dask-worker" pthread_cond_wait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
  23   Thread 0x7f8a9e85d700 (LWP 17269) "dask-worker" pthread_cond_wait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
  24   Thread 0x7f8a9e05c700 (LWP 17270) "dask-worker" pthread_cond_wait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
  25   Thread 0x7f8a9d85b700 (LWP 17271) "dask-worker" pthread_cond_wait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
  26   Thread 0x7f8a9d05a700 (LWP 17272) "dask-worker" pthread_cond_wait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
  27   Thread 0x7f8a9c859700 (LWP 17273) "dask-worker" pthread_cond_wait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
  28   Thread 0x7f8a9c058700 (LWP 17274) "dask-worker" pthread_cond_wait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
  29   Thread 0x7f8a9b857700 (LWP 17275) "dask-worker" pthread_cond_wait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
  30   Thread 0x7f8a9b056700 (LWP 17276) "dask-worker" pthread_cond_wait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
  31   Thread 0x7f8a9a855700 (LWP 17277) "dask-worker" pthread_cond_wait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
  32   Thread 0x7f8a9a054700 (LWP 17278) "dask-worker" pthread_cond_wait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
  33   Thread 0x7f8a99853700 (LWP 17279) "dask-worker" pthread_cond_wait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
  34   Thread 0x7f8a99052700 (LWP 17280) "dask-worker" pthread_cond_wait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
  35   Thread 0x7f8a98851700 (LWP 17281) "dask-worker" pthread_cond_wait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
  36   Thread 0x7f8a98050700 (LWP 17282) "dask-worker" pthread_cond_wait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
  37   Thread 0x7f8a9784f700 (LWP 17283) "dask-worker" pthread_cond_wait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
  38   Thread 0x7f8a9704e700 (LWP 17284) "dask-worker" pthread_cond_wait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
  39   Thread 0x7f8a9684d700 (LWP 17285) "dask-worker" pthread_cond_wait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
  40   Thread 0x7f8a9604c700 (LWP 17286) "dask-worker" pthread_cond_wait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
  41   Thread 0x7f8a9584b700 (LWP 17287) "dask-worker" pthread_cond_wait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
  42   Thread 0x7f8a9504a700 (LWP 17288) "dask-worker" pthread_cond_wait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
  43   Thread 0x7f8a94849700 (LWP 17289) "dask-worker" pthread_cond_wait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
  44   Thread 0x7f8a94048700 (LWP 17290) "dask-worker" pthread_cond_wait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
  45   Thread 0x7f8a93847700 (LWP 17291) "dask-worker" pthread_cond_wait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
  46   Thread 0x7f8a93046700 (LWP 17292) "dask-worker" pthread_cond_wait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
```

**Comment by yzard** [comment]
We fixed the problem, those cpu usage is not caused by dask, it's our bad, scikit learn using openblas, so this environment variable need be set as 1:

export OPENBLAS_NUM_THREADS=1

**Comment by bansalr** [comment]
This was tracked down to not setting:
OMP_NUM_THREADS=1
and MKL_NUM_THREADS=1

@yzard will close this out soon.
