### ISSUE TITLE
NETCDF - Resource temporarily unavailable 

### ISSUE THREAD

**Issue by jamesstidard** [dask/dask#2657]
I'm trying to use `dask` to load a NetCDF [file from ECMWF](http://apps.ecmwf.int/datasets/data/cera20c-ewda/type=an/selectors/netcdf/1032344/)*. However, I get a `RuntimeError: Resource temporarily unavailable` exception thrown when I run this script:

```python
from dask import array as da
from netCDF4 import Dataset

ds = Dataset('_grib2netcdf-atls01-a562cefde8a29a7288fa0b8b7f9413f7-Bbb1Q9.nc')
a = da.from_array(ds.variables['swh'], chunks=(50, 50, 50))
r = a.mean().compute()
ds.close()
```
I've tried googling around but not been successful in finding a solution.

I'm using `netCDF4` `1.2.9` and `dask` `0.15.2`.

Here's the stack trace:

```bash
Traceback (most recent call last):
  File "/path/to/file.py", line 7, in <module>
    r = a.mean().compute()
  File "~/.pyenv/versions/3.6.2/lib/python3.6/site-packages/dask/base.py", line 99, in compute
Error 11: Resource temporarily unavailable
Error 11: Resource temporarily unavailable
Error 11: Resource temporarily unavailable
    (result,) = compute(self, traverse=False, **kwargs)
  File "~/.pyenv/versions/3.6.2/lib/python3.6/site-packages/dask/base.py", line 206, in compute
    results = get(dsk, keys, **kwargs)
  File "~/.pyenv/versions/3.6.2/lib/python3.6/site-packages/dask/threaded.py", line 75, in get
    pack_exception=pack_exception, **kwargs)
  File "~/.pyenv/versions/3.6.2/lib/python3.6/site-packages/dask/local.py", line 521, in get_async
    raise_exception(exc, tb)
  File "~/.pyenv/versions/3.6.2/lib/python3.6/site-packages/dask/compatibility.py", line 60, in reraise
    raise exc
  File "~/.pyenv/versions/3.6.2/lib/python3.6/site-packages/dask/local.py", line 290, in execute_task
    result = _execute_task(task, data)
  File "~/.pyenv/versions/3.6.2/lib/python3.6/site-packages/dask/local.py", line 271, in _execute_task
    return func(*args2)
  File "~/.pyenv/versions/3.6.2/lib/python3.6/site-packages/dask/array/core.py", line 54, in getter
    c = a[b]
  File "netCDF4/_netCDF4.pyx", line 3823, in netCDF4._netCDF4.Variable.__getitem__ (netCDF4/_netCDF4.c:40266)
  File "netCDF4/_netCDF4.pyx", line 4649, in netCDF4._netCDF4.Variable._get (netCDF4/_netCDF4.c:52088)
RuntimeError: Resource temporarily unavailable
```
Looks like a problem with multiple processes/threads accessing the `*.nc` file simultaneously - but unsure how to go about resolving that - as I assume that would be handled on the library level.

Thanks. 

---
\* you do need to make an account to download this file.

**Comment by mrocklin** [comment]
Try `from_array(..., lock=True)` to add a lock into the mix.

You might also want to try the XArray project, which has already thought deeply about many of these issues and uses Dask array internally.

**Comment by jamesstidard** [comment]
@mrocklin Thanks for the quick response. Feel kind of silly that it was a missing parameter; should have done a better job looking. The XArray project also looks quite nice, so thanks for the suggestion.
