### ISSUE TITLE
Can't create a dask.Array with chunks of lists

### ISSUE THREAD

**Issue by sjperkins** [dask/dask#2666]
I ran into this while create custom `dask.Array`'s. The underlying interface was unexpectedly returning a list of strings for each chunk in my dask graph, instead of numpy arrays. The code below will reproduce the issue.

``` python
import argparse
from pprint import pprint

import dask
import dask.array as da
import dask.array.core
import numpy as np

def get_args():
    p = argparse.ArgumentParser()
    p.add_argument("-ct", "--chunk-type", default="list",
            type=lambda ct: np.asarray if ct == 'numpy' else list)
    p.add_argument("-cs", "--chunk-size", dest="N", type=int, default=10)
    return p.parse_args()

args = get_args()

dsk = {
    ('array', 0) : (args.chunk_type, ["foo" for i in range(args.N)]),
    ('array', 1) : (args.chunk_type, ["bar" for i in range(args.N)]),
    ('array', 2) : (args.chunk_type, ["qux" for i in range(args.N)]),
    ('array', 3) : (args.chunk_type, ["box" for i in range(args.N)]),
}


nchunks = len(dsk)

A = da.Array(dsk, 'array', chunks=((args.N,)*nchunks,), dtype=np.int32)

print A.compute()
print "SUCCESS"

dask.array.core.chunks_from_arrays(["foo" for i in range(args.N*nchunks)])
dask.array.core.chunks_from_arrays([["foo" for i in range(args.N*nchunks)]])

Traceback (most recent call last):
  File "minimal_chunks_from_array.py", line 34, in <module>
    dask.array.core.chunks_from_arrays([["foo" for i in range(args.N*nchunks)]])
  File "/home/sperkins/venv/xarray-ms/local/lib/python2.7/site-packages/dask/array/core.py", line 2665, in chunks_from_arrays
    result.append(tuple([shape(deepfirst(a))[dim] for a in arrays]))
IndexError: tuple index out of range
```

Something happens in the logic that such that `chunks_from_arrays([["foo", ..., "foo"]])` is invoked and fails, instead of `chunks_from_arrays(["foo", ..., "foo"])`, which succeeds.

This is not high priority for me, since wrapping the string lists in a `np.array` works, but it might be a case you wish to handle.

**Comment by mrocklin** [comment]
Yes, internally chunks are expected to be NumPy arrays or things that look very much like numpy arrays.  I don't think that it makes sense to generalize to lists.

**Comment by sjperkins** [comment]
Thanks for the feedback. Closing.
