### ISSUE TITLE
Irrelevant columns breaking dask groupby vars, but not means (and not in pandas)

### ISSUE THREAD

**Issue by samuelroberth** [dask/dask#2670]
This is from user Laszlo on Stackoverflow (https://stackoverflow.com/questions/46115779/irrelevant-columns-breaking-dask-groupby-vars-but-not-means-and-not-in-pandas)

Below is the MCVE of the behavior of an up-to-date dask instance on my system, and contrasts the dask error with pandas using the small CSV quoted at the end of this question.

Setup:

```
import numpy as np
import dask.dataframe as dd
df = dd.read_csv('hmda_lar_head_4var.csv',
                 engine='c',
                 usecols=['tract_to_msamd_income','as_of_year','agency_abbr','action_taken_name'],
                 dtype={'tract_to_msamd_income': np.float64,
                        'as_of_year':np.uint16,
                        'agency_abbr':'category',
                        'action_taken_name':'category'
                       })
```
The line that breaks: df.groupby('as_of_year').var().compute()

The error:

```
---------------------------------------------------------------------------

ValueError                                Traceback (most recent call last)

/Users/laszlo.sandor/miniconda3/envs/idp/lib/python3.5/site-packages/dask/dataframe/utils.py in raise_on_meta_error(funcname)
    136     try:
--> 137         yield
    138     except Exception as e:


/Users/laszlo.sandor/miniconda3/envs/idp/lib/python3.5/site-packages/dask/dataframe/core.py in _emulate(func, *args, **kwargs)
   3058     with raise_on_meta_error(funcname(func)):
-> 3059         return func(*_extract_meta(args, True), **_extract_meta(kwargs, True))
   3060 


/Users/laszlo.sandor/miniconda3/envs/idp/lib/python3.5/site-packages/dask/compatibility.py in apply(func, args, kwargs)
     46         if kwargs:
---> 47             return func(*args, **kwargs)
     48         else:


/Users/laszlo.sandor/miniconda3/envs/idp/lib/python3.5/site-packages/dask/dataframe/groupby.py in _var_agg(g, levels, ddof)
    210     result /= div
--> 211     result[(n - ddof) == 0] = np.nan
    212     assert isinstance(result, pd.DataFrame)


/Users/laszlo.sandor/miniconda3/envs/idp/lib/python3.5/site-packages/pandas/core/frame.py in __setitem__(self, key, value)
   2425         elif isinstance(key, DataFrame):
-> 2426             self._setitem_frame(key, value)
   2427         else:


/Users/laszlo.sandor/miniconda3/envs/idp/lib/python3.5/site-packages/pandas/core/frame.py in _setitem_frame(self, key, value)
   2463         self._check_setitem_copy()
-> 2464         self._where(-key, value, inplace=True)
   2465 


/Users/laszlo.sandor/miniconda3/envs/idp/lib/python3.5/site-packages/pandas/core/generic.py in _where(self, cond, other, inplace, axis, level, try_cast, raise_on_error)
   4952                 if not is_bool_dtype(dt):
-> 4953                     raise ValueError(msg.format(dtype=dt))
   4954 


ValueError: Boolean array expected for the condition, not float64


During handling of the above exception, another exception occurred:


ValueError                                Traceback (most recent call last)

<ipython-input-154-4d73414200e5> in <module>()
----> 1 df.groupby('as_of_year').var().compute()


/Users/laszlo.sandor/miniconda3/envs/idp/lib/python3.5/site-packages/dask/dataframe/groupby.py in var(self, ddof, split_every, split_out)
    796                      combine_kwargs={'levels': levels},
    797                      split_every=split_every, split_out=split_out,
--> 798                      split_out_setup=split_out_on_index)
    799 
    800         if isinstance(self.obj, Series):


/Users/laszlo.sandor/miniconda3/envs/idp/lib/python3.5/site-packages/dask/dataframe/core.py in apply_concat_apply(args, chunk, aggregate, combine, meta, token, chunk_kwargs, aggregate_kwargs, combine_kwargs, split_every, split_out, split_out_setup, split_out_setup_kwargs, **kwargs)
   3010         meta_chunk = _emulate(apply, chunk, args, chunk_kwargs)
   3011         meta = _emulate(apply, aggregate, [_concat([meta_chunk])],
-> 3012                         aggregate_kwargs)
   3013     meta = make_meta(meta)
   3014 


/Users/laszlo.sandor/miniconda3/envs/idp/lib/python3.5/site-packages/dask/dataframe/core.py in _emulate(func, *args, **kwargs)
   3057     """
   3058     with raise_on_meta_error(funcname(func)):
-> 3059         return func(*_extract_meta(args, True), **_extract_meta(kwargs, True))
   3060 
   3061 


/Users/laszlo.sandor/miniconda3/envs/idp/lib/python3.5/contextlib.py in __exit__(self, type, value, traceback)
     75                 value = type()
     76             try:
---> 77                 self.gen.throw(type, value, traceback)
     78                 raise RuntimeError("generator didn't stop after throw()")
     79             except StopIteration as exc:


/Users/laszlo.sandor/miniconda3/envs/idp/lib/python3.5/site-packages/dask/dataframe/utils.py in raise_on_meta_error(funcname)
    148                ).format(" in `{0}`".format(funcname) if funcname else "",
    149                         repr(e), tb)
--> 150         raise ValueError(msg)
    151 
    152 


ValueError: Metadata inference failed in `apply`.

Original error is below:
------------------------
ValueError('Boolean array expected for the condition, not float64',)

Traceback:
---------
  File "/Users/laszlo.sandor/miniconda3/envs/idp/lib/python3.5/site-packages/dask/dataframe/utils.py", line 137, in raise_on_meta_error
    yield
  File "/Users/laszlo.sandor/miniconda3/envs/idp/lib/python3.5/site-packages/dask/dataframe/core.py", line 3059, in _emulate
    return func(*_extract_meta(args, True), **_extract_meta(kwargs, True))
  File "/Users/laszlo.sandor/miniconda3/envs/idp/lib/python3.5/site-packages/dask/compatibility.py", line 47, in apply
    return func(*args, **kwargs)
  File "/Users/laszlo.sandor/miniconda3/envs/idp/lib/python3.5/site-packages/dask/dataframe/groupby.py", line 211, in _var_agg
    result[(n - ddof) == 0] = np.nan
  File "/Users/laszlo.sandor/miniconda3/envs/idp/lib/python3.5/site-packages/pandas/core/frame.py", line 2426, in __setitem__
    self._setitem_frame(key, value)
  File "/Users/laszlo.sandor/miniconda3/envs/idp/lib/python3.5/site-packages/pandas/core/frame.py", line 2464, in _setitem_frame
    self._where(-key, value, inplace=True)
  File "/Users/laszlo.sandor/miniconda3/envs/idp/lib/python3.5/site-packages/pandas/core/generic.py", line 4953, in _where
    raise ValueError(msg.format(dtype=dt))
Compare this with the behavior of the line that produces correct results: df.groupby('as_of_year').mean().compute()

```
If you set things up in supposedly similar pandas:

```
import pandas as pd
df = pd.read_csv('hmda_lar_head_4var.csv',
                 engine='c',
                 usecols=['tract_to_msamd_income','as_of_year','agency_abbr','action_taken_name'],
                 dtype={'tract_to_msamd_income': np.float64,
                        'as_of_year':np.uint16,
                        'agency_abbr':'category',
                        'action_taken_name':'category'
                       })
```
You see that both df.groupby('as_of_year').var() and df.groupby('as_of_year').mean() produce the correct results.

If you load only two columns, one you are grouping by and another that is meaningful to report the variance for, dask has no problem reporting the variance:

```
import numpy as np
import dask.dataframe as dd
df = dd.read_csv('hmda_lar_head_4var.csv',
                 engine='c',
                 usecols=['tract_to_msamd_income','as_of_year'],
                 dtype={'tract_to_msamd_income': np.float64,
                        'as_of_year':np.uint16
                       })
```
This is small comfort, as (I think) you cannot easily specify which columns to calculate groupby methods for, only select ones to report. I.e. some columns can break dask groupby var even if you ask to report only other columns.

Here is the CSV for MCVE:

tract_to_msamd_income,as_of_year,agency_abbr,action_taken_name "85.02999877929688","2007","FRS","Loan originated" "103.12000274658203","2007","FRS","Application withdrawn by applicant" "127.87000274658203","2007","FRS","Loan originated" "103.12000274658203","2007","FRS","Application denied by financial institution" "131.14999389648438","2007","FRS","Loan originated" "85.02999877929688","2007","FRS","Application withdrawn by applicant" "103.12000274658203","2007","FRS","Application withdrawn by applicant" "95.76000213623047","2007","FRS","Loan originated" "103.12000274658203","2007","FRS","Application withdrawn by applicant"

**Comment by laszlosandor** [comment]
I am afraid I am not up to it, sorry.

**Comment by samuelroberth** [comment]
Is there a problem because the var is attempting to set a uint64 to np.nan here?

**Comment by mrocklin** [comment]
Given the error:

    ValueError('Boolean array expected for the condition, not float64',)

My guess is that we're doing something like `series[condition]` where condition is a mostly boolean array with some missing values/nans thrown in, which force it to float64 dtype. I don't know though.  I haven't had the time to check this out personally yet.
