### ISSUE TITLE
Client.upload_file failed with "Stream is closed" error

### ISSUE THREAD

**Issue by ningsean** [dask/dask#2685]
I installed dask-0.15.2+25.ga1a75a7 and distributed-1.18.3+6.ge6cb2c6. Then I started a local cluster on a 32-core machine with
  `dask-scheduler --host 127.0.0.1 --port 9898 --http-port 9897 --bokeh-port 9896`
and 
  `dask-worker --nprocs 32 127.0.0.1:9898`

When I try
```
In [1]: from dask.distributed import Client

In [2]: client = Client('localhost:9898')

In [3]: client.upload_file('../test2/config.py')
```

I got the following error. Any idea where I should look for the problem? Thanks!

```
distributed.utils - ERROR - in <closed TCP>: Stream is closed: while trying to call remote method 'broadcast'
Traceback (most recent call last):
  File "/opt/anaconda2/envs/py3k/lib/python3.6/site-packages/distributed/comm/tcp.py", line 170, in read
    n_frames = yield stream.read_bytes(8)
  File "/opt/anaconda2/envs/py3k/lib/python3.6/site-packages/tornado/gen.py", line 1055, in run
    value = future.result()
  File "/opt/anaconda2/envs/py3k/lib/python3.6/site-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
tornado.iostream.StreamClosedError: Stream is closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/anaconda2/envs/py3k/lib/python3.6/site-packages/distributed/core.py", line 454, in send_recv_from_rpc
    result = yield send_recv(comm=comm, op=key, **kwargs)
  File "/opt/anaconda2/envs/py3k/lib/python3.6/site-packages/tornado/gen.py", line 1055, in run
    value = future.result()
  File "/opt/anaconda2/envs/py3k/lib/python3.6/site-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
  File "/opt/anaconda2/envs/py3k/lib/python3.6/site-packages/tornado/gen.py", line 1063, in run
    yielded = self.gen.throw(*exc_info)
  File "/opt/anaconda2/envs/py3k/lib/python3.6/site-packages/distributed/core.py", line 340, in send_recv
    response = yield comm.read()
  File "/opt/anaconda2/envs/py3k/lib/python3.6/site-packages/tornado/gen.py", line 1055, in run
    value = future.result()
  File "/opt/anaconda2/envs/py3k/lib/python3.6/site-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
  File "/opt/anaconda2/envs/py3k/lib/python3.6/site-packages/tornado/gen.py", line 1063, in run
    yielded = self.gen.throw(*exc_info)
  File "/opt/anaconda2/envs/py3k/lib/python3.6/site-packages/distributed/comm/tcp.py", line 184, in read
    convert_stream_closed_error(self, e)
  File "/opt/anaconda2/envs/py3k/lib/python3.6/site-packages/distributed/comm/tcp.py", line 122, in convert_stream_closed_error
    raise CommClosedError("in %s: %s" % (obj, exc))
distributed.comm.core.CommClosedError: in <closed TCP>: Stream is closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/anaconda2/envs/py3k/lib/python3.6/site-packages/distributed/utils.py", line 229, in f
    result[0] = yield make_coro()
  File "/opt/anaconda2/envs/py3k/lib/python3.6/site-packages/tornado/gen.py", line 1055, in run
    value = future.result()
  File "/opt/anaconda2/envs/py3k/lib/python3.6/site-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
  File "/opt/anaconda2/envs/py3k/lib/python3.6/site-packages/tornado/gen.py", line 1063, in run
    yielded = self.gen.throw(*exc_info)
  File "/opt/anaconda2/envs/py3k/lib/python3.6/site-packages/distributed/client.py", line 2207, in _upload_file
    'data': to_serialize(data)})
  File "/opt/anaconda2/envs/py3k/lib/python3.6/site-packages/tornado/gen.py", line 1055, in run
    value = future.result()
  File "/opt/anaconda2/envs/py3k/lib/python3.6/site-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
  File "/opt/anaconda2/envs/py3k/lib/python3.6/site-packages/tornado/gen.py", line 1063, in run
    yielded = self.gen.throw(*exc_info)
  File "/opt/anaconda2/envs/py3k/lib/python3.6/site-packages/distributed/core.py", line 457, in send_recv_from_rpc
    % (e, key,))
distributed.comm.core.CommClosedError: in <closed TCP>: Stream is closed: while trying to call remote method 'broadcast'
```

**Comment by mrocklin** [comment]
Do other operations work?  Does your file do anything particularly odd?

**Comment by ningsean** [comment]
You are right. The problem is due to the file referencing another module local to the client.
Thanks. I am closing this.

**Comment by ningsean** [comment]
This is strange.

It seems that there is some "racing" condition going on. I found that each time I call the upload_file method, at least one worker will successfully uploads the file, and the remaining workers would be "killed by signal 11" and restarted according to the workers log. The client would receive the error in the originate post.

If I repeat the upload_file multiple times like below, eventually all workers will have the file uploaded. 

Any idea why this may happen?

```
    maxtry = 200
    ntry = 0
    while ntry<maxtry:
        try:
            client.upload_file('../test2/config.py')
            break
        except Exception as ex:
            print(ex)
            ntry+=1
```

**Comment by mrocklin** [comment]
Are you able to provide a simple reproducible example?

**Comment by ningsean** [comment]
Here is a simple reproducible example. code are organized as follows. The terminal that runs `dask-worker --nprocs 32 127.0.0.1:9898` has `$PYTHONPATH` points to the path to `local_module` folder.

Run the `main.py` from under the client directory. The error will occur when module1.py has the `import dask.dataframe as dd` line activated. If you run it with the line commented out first (which will have no error) and then activate the line, you need to restart workers before running the main.py again for the error to happen.

```
.
├── client
│   ├── config.py
│   └── main.py
└── local_module
    ├── __init__.py
    └── module1.py
```

in client/main.py:
```
from dask.distributed import Client
import importlib

if __name__ == '__main__':
  client = Client('localhost:9898')
  print(client)
  cfg = importlib.import_module('config')
  print(cfg)
  client.upload_file('config.py')
  client.close()
```

in client/config.py:
```
import sys
import os
module_path = os.getcwd()
sys.path.insert(0,module_path+'/../local_module')
import module1 as m1
```

in local_module/module1.py:
```
import dask #OK, even without restarting the workers
import dask.dataframe as dd #Error if run main.py after restarting the workers
```

the file `local_module/__init__.py` is empty.

**Comment by ningsean** [comment]
To save you some time, here is the code in a zip file.
[dask_test.zip](https://github.com/dask/dask/files/1315394/dask_test.zip)

**Comment by ningsean** [comment]
@mrocklin do you need any other information? Thanks!

**Comment by mrocklin** [comment]
Closing as stale.
