### ISSUE TITLE
Error when indexing dask array of unknown size

### ISSUE THREAD

**Issue by mraspaud** [dask/dask#2699]
Hi,

I'm trying to index a dask array of unknown size, like this:

```python
import dask.array as da
import numpy as np


arr = da.from_array(np.arange(10), chunks=[4])
valid_input_index = (arr > 5)
indices = np.array([1, 2, 3])
print(arr[valid_input_index].compute()[indices])
print(arr[valid_input_index][indices])
```
I get then an error as follows:
```
/home/a001673/usr/src/dask/dask/array/slicing.py:816: RuntimeWarning: invalid value encountered in greater_equal
  if (x >= dimension).any() or (x < -dimension).any():
/home/a001673/usr/src/dask/dask/array/slicing.py:816: RuntimeWarning: invalid value encountered in less
  if (x >= dimension).any() or (x < -dimension).any():
Traceback (most recent call last):
  File "test_dask.py", line 9, in <module>
    print(arr[valid_input_index][indices])
  File "/home/a001673/usr/src/dask/dask/array/core.py", line 1235, in __getitem__
    return Array(dsk2, out, chunks, dtype=self.dtype)
  File "/home/a001673/usr/src/dask/dask/array/core.py", line 993, in __new__
    self._chunks = normalize_chunks(chunks, shape)
  File "/home/a001673/usr/src/dask/dask/array/core.py", line 1854, in normalize_chunks
    raise ValueError("Empty tuples are not allowed in chunks. Express "
ValueError: Empty tuples are not allowed in chunks. Express zero length dimensions with 0(s) in chunks
```

Am I doing something wrong ? The computed version works as expected though.

Best regards,
Martin

**Comment by mrocklin** [comment]
Hi @mraspaud , 

Unfortunately this behavior isn't supported in dask.array.  In order to slice like this we need to know to which chunk every index belongs.  If you have done value-based slicing (like with `arr > 5`) then we can't know this without looking at all of the values.

**Comment by mraspaud** [comment]
@mrocklin thanks, good to know. I will be careful in these cases then.
