### ISSUE TITLE
Applying aggregations to a dataframe fails when reading data from partitioned parquet

### ISSUE THREAD

**Issue by j-bennet** [dask/dask#2707]
[This code](https://gist.github.com/j-bennet/61869b310a00024af055a3371b2978af) is a toy example of aggregating a dataframe and producing multiple aggregated columns. It works (thanks to @martindurant ).

[This code](https://gist.github.com/j-bennet/55c93c05e5b6f5202068531f38f5a5a4) is an attempt to do the same aggregation on a dataframe being read from parquet files. This code does not work, and I can't figure out why. Exception looks like this:

```
aggregate2.py:25: UserWarning: `meta` is not specified, inferred from partial data. Please provide `meta` if the result is unexpected.
  Before: .apply(func)
  After:  .apply(func, meta={'x': 'f8', 'y': 'f8'}) for dataframe result
  or:     .apply(func, meta=('x', 'f8'))            for series result
  ag = gb.apply(lambda d: pd.DataFrame({
Traceback (most recent call last):
  File "aggregate2.py", line 30, in <module>
    print(ag.compute())
  File "/Users/irina/.pyenv/versions/talks/src/dask/dask/base.py", line 99, in compute
    (result,) = compute(self, traverse=False, **kwargs)
  File "/Users/irina/.pyenv/versions/talks/src/dask/dask/base.py", line 206, in compute
    results = get(dsk, keys, **kwargs)
  File "/Users/irina/.pyenv/versions/talks/src/dask/dask/threaded.py", line 75, in get
    pack_exception=pack_exception, **kwargs)
  File "/Users/irina/.pyenv/versions/talks/src/dask/dask/local.py", line 521, in get_async
    raise_exception(exc, tb)
  File "/Users/irina/.pyenv/versions/talks/src/dask/dask/local.py", line 290, in execute_task
    result = _execute_task(task, data)
  File "/Users/irina/.pyenv/versions/talks/src/dask/dask/local.py", line 271, in _execute_task
    return func(*args2)
  File "/Users/irina/.pyenv/versions/talks/src/dask/dask/dataframe/core.py", line 3194, in apply_and_enforce
    return _rename(c, df)
  File "/Users/irina/.pyenv/versions/talks/src/dask/dask/dataframe/core.py", line 3231, in _rename
    df.columns = columns
  File "/Users/irina/.pyenv/versions/talks/lib/python2.7/site-packages/pandas/core/generic.py", line 3094, in __setattr__
    return object.__setattr__(self, name, value)
  File "pandas/_libs/src/properties.pyx", line 65, in pandas._libs.lib.AxisProperty.__set__ (pandas/_libs/lib.c:45255)
  File "/Users/irina/.pyenv/versions/talks/lib/python2.7/site-packages/pandas/core/generic.py", line 473, in _set_axis
    self._data.set_axis(axis, labels)
  File "/Users/irina/.pyenv/versions/talks/lib/python2.7/site-packages/pandas/core/internals.py", line 2836, in set_axis
    (old_len, new_len))
ValueError: Length mismatch: Expected axis has 4 elements, new values have 7 elements
```

I also noticed a few odd things about the loaded parquet. Originally, it was partitioned on `year`, `month`, `day`, `hour` and `customer`. After reading the files, even when specifying `columns=['customer', 'url', 'ts', 'session_id', 'referrer']`, I have `hour` in the data if I look at `df.head()`. In fact, specifying `columns=['customer', 'url', 'ts', 'session_id', 'referrer']` in `dd.read_parquet` does not seem to work, the dataframe looks like this:

```
ipdb> df.head()
                       url              referrer session_id                  ts customer hour
0  http://a.com/articles/1    http://google.com/        xxx 2017-09-15 00:15:00    a.com    0
1  http://a.com/articles/2      http://bing.com/        yyy 2017-09-15 00:30:00    a.com    0
2  http://a.com/articles/2  http://facebook.com/        yyy 2017-09-15 00:45:00    a.com    0
```

with `year, month, day` not present in dataframe, while `customer` and `hour` are. I would assume all partition keys should be either read or dropped together, but this seem to happen selectively.

I attached the parquet data in question.

[events.zip](https://github.com/dask/dask/files/1327069/events.zip)

This issue came here from https://stackoverflow.com/questions/46375382/aggregate-a-dask-dataframe-and-produce-a-dataframe-of-aggregates/46380632#46380632.

**Comment by martindurant** [comment]
This is how I ran this successfully:

    files = glob.glob('events/*/*/*/*/*/part*.parquet')
    pf = fastparquet.ParquetFile(files, root='events')
    out = pf.to_pandas()

Some explanations:
- spark does not produce a central metadata file unless specified, so you need to list all the files you want to load
- the `root=` parameter tells fastparquet where to assume the top level of the dataset; because there is only one month, all the paths share the same directory one level lower too, and fastparquet normally selects the lowest common directory
- selecting columns refers to which columns to read from disc; month, day, hour are not columns in this sense, and are always read 

You'll notice a new bug when you perform this: some of the category labels are coming back as timedelta objects. This is because they have are like '05', and python can't interpret that as an integer, but apparently can as a timedelta (5 nanoseconds). (fix: `out['hour'] = out.hour.map(lambda x: x if isinstance(x, int) else x.nanoseconds)` )
I'm not totally sure what to do about that: 
- explicitly strip leading zeros from strings before attempting to interpret as a number?
- if a set of partition labels contains heterogeneous types, revert back to strings?

**Comment by j-bennet** [comment]
When reading that data with spark, it converts zero-padded numbers to ints, unless you specify `spark.sql.sources.partitionColumnTypeInference.enabled=False`. I would expect fastparquet to do something similar, i.e. read them as either strings or ints. When storing the data, we use strings in those `year, month, day, hour` columns, because we want partitioned directories to be sorted in the right order in the filesystem.

**Comment by j-bennet** [comment]
@martindurant Thanks for pointing out about `fastparquet.ParquetFile()` being different from `dd.read_parquet`. I expected one to just delegate to another, with all the same args. I noticed you're using `out = pf.to_pandas()` in the code snippet above. This will give you a Pandas dataframe, right? How would you get a Dask dataframe out of it?

**Comment by martindurant** [comment]
Indeed, it would be reasonable to include `root=` as a parameter to `dd.read_parquet`, although the parameter list is getting rather long, and many are not supported by the alternative arrow-based implementation.
You *could* use the code above directly: if the data fits in memory, then `dd.from_pandas` is the function you need. Otherwise, you could make delayed calls to `pf.read_row_group_file`, followed by `dd.from_delayed`, which is more or less what `dd.read_parquet` does anyway.

**Comment by martindurant** [comment]
Note, though, that for your situation, there will be no need for `root=` if there is more than one partition at the upper level, or it would be trivial to assign the one possible value if that is indeed your case, and you want to.

**Comment by j-bennet** [comment]
@martindurant Is there any way to not have the `['year', 'month', 'day', 'hour']` in the resulting dataframe? I tried providing a list of columns to `read_row_group_file`, but that didn't do it:

```
    file_names = glob.glob(FILE_MASK)
    pf = fp.ParquetFile(file_names, root='./events')
    dfs = (delayed(pf.read_row_group_file)(rg, 
                                           ['url', 'referrer', 'session_id', 'ts', 'customer'], 
                                           pf.categories)
           for rg in pf.row_groups)
    df = dd.from_delayed(dfs)
```

**Comment by martindurant** [comment]
It is not designed this way - as I suggested above, the partitioning is not considered "columns" at read time.
You can, however, achieve your desired effect by removing the offending values from the `cats` attribute of `pf`. For instance, if you want none of them at all, you can do:

    pf.cats = {}

before calling `to_pandas()`.

**Comment by j-bennet** [comment]
@martindurant What if I want to keep `customer` but remove `year, month, day, hour`?

**Comment by mrocklin** [comment]
Worst case scenario you could presumably always handle this on the pandas or dask side side by indexing or calling `drop`.

    df = df[['columns', 'we', 'care', 'about']]

**Comment by j-bennet** [comment]
@mrocklin I tried that (subsetting the dataframe) first thing. Those categorical columns magically show up anyway. But modifying `pf.cats` does work.

**Comment by mrocklin** [comment]
Sorry, I meant subsetting after this line

    df = dd.from_delayed(dfs)

We would accept that those columns will show up, but after they show up we would get rid of them.  This is somewhat inefficient because we allocate memory for columns that we then release, but would, I think, be relatively fool-proof.

**Comment by j-bennet** [comment]
This gives me what I want:

```
    file_names = glob.glob(FILE_MASK)
    pf = fp.ParquetFile(file_names, root='./events')
    pf.cats = {'customer': pf.cats['customer']}
    dfs = (delayed(pf.read_row_group_file)(rg, pf.columns, pf.cats)
           for rg in pf.row_groups)
    df = dd.from_delayed(dfs)
```

then:

```
ipdb> df.head()
                       url              referrer session_id                  ts customer
0  http://a.com/articles/1    http://google.com/        xxx 2017-09-15 00:15:00    a.com
1  http://a.com/articles/2      http://bing.com/        yyy 2017-09-15 00:30:00    a.com
2  http://a.com/articles/2  http://facebook.com/        yyy 2017-09-15 00:45:00    a.com
```

**Comment by j-bennet** [comment]
This still throws an exception though:

```
# -*- coding: utf-8
import glob
import pandas as pd
import fastparquet as fp
import dask.dataframe as dd
from dask import delayed

FILE_MASK = './events/*/*/*/*/*/*.*.parquet'
pd.set_option('display.expand_frame_repr', False)


if __name__ == '__main__':
    file_names = glob.glob(FILE_MASK)
    pf = fp.ParquetFile(file_names, root='./events')
    pf.cats = {'customer': pf.cats['customer']}
    dfs = (delayed(pf.read_row_group_file)(rg, pf.columns, pf.cats)
           for rg in pf.row_groups)
    df = dd.from_delayed(dfs)

    # Round timestamps down to an hour
    df['ts'] = df['ts'].map(lambda x: x.replace(minute=0, second=0, microsecond=0))

    # group on customer, timestamp and url.
    gb = df.groupby(['customer', 'url', 'ts'])

    ag = gb.apply(lambda d: pd.DataFrame({
        'views': len(d),
        'visitors': d.session_id.count(),
        'referrers': [d.referrer.tolist()]})).reset_index()

    print(ag.compute())
```

same as before:

```
aggregate2.py:26: UserWarning: `meta` is not specified, inferred from partial data. Please provide `meta` if the result is unexpected.
  Before: .apply(func)
  After:  .apply(func, meta={'x': 'f8', 'y': 'f8'}) for dataframe result
  or:     .apply(func, meta=('x', 'f8'))            for series result
  ag = gb.apply(lambda d: pd.DataFrame({
Traceback (most recent call last):
  File "aggregate2.py", line 31, in <module>
    print(ag.compute())
  File "/Users/irina/.pyenv/versions/talks/src/dask/dask/base.py", line 99, in compute
    (result,) = compute(self, traverse=False, **kwargs)
  File "/Users/irina/.pyenv/versions/talks/src/dask/dask/base.py", line 206, in compute
    results = get(dsk, keys, **kwargs)
  File "/Users/irina/.pyenv/versions/talks/src/dask/dask/threaded.py", line 75, in get
    pack_exception=pack_exception, **kwargs)
  File "/Users/irina/.pyenv/versions/talks/src/dask/dask/local.py", line 521, in get_async
    raise_exception(exc, tb)
  File "/Users/irina/.pyenv/versions/talks/src/dask/dask/local.py", line 290, in execute_task
    result = _execute_task(task, data)
  File "/Users/irina/.pyenv/versions/talks/src/dask/dask/local.py", line 271, in _execute_task
    return func(*args2)
  File "/Users/irina/.pyenv/versions/talks/src/dask/dask/dataframe/core.py", line 3194, in apply_and_enforce
    return _rename(c, df)
  File "/Users/irina/.pyenv/versions/talks/src/dask/dask/dataframe/core.py", line 3231, in _rename
    df.columns = columns
  File "/Users/irina/.pyenv/versions/talks/lib/python2.7/site-packages/pandas/core/generic.py", line 3094, in __setattr__
    return object.__setattr__(self, name, value)
  File "pandas/_libs/src/properties.pyx", line 65, in pandas._libs.lib.AxisProperty.__set__ (pandas/_libs/lib.c:45255)
  File "/Users/irina/.pyenv/versions/talks/lib/python2.7/site-packages/pandas/core/generic.py", line 473, in _set_axis
    self._data.set_axis(axis, labels)
  File "/Users/irina/.pyenv/versions/talks/lib/python2.7/site-packages/pandas/core/internals.py", line 2836, in set_axis
    (old_len, new_len))
ValueError: Length mismatch: Expected axis has 4 elements, new values have 7 elements
```

**Comment by j-bennet** [comment]
@martindurant Did the aggregation work for you with this data?

**Comment by martindurant** [comment]
Yes, all good at this end.

**Comment by j-bennet** [comment]
What happens on `print(ag.compute())`? I still get the exception above.

**Comment by j-bennet** [comment]
@martindurant I find that the aggregation works when using pandas dataframe, i.e. `pf.to_pandas()`, but not when creating a dask dataframe out of `delayed` on `read_row_group_file`.

full code that works:

```
import glob
import pandas as pd
import fastparquet as fp
import dask.dataframe as dd
from dask.dataframe import utils
from dask import delayed

FILE_MASK = './events/*/*/*/*/*/*.*.parquet'
pd.set_option('display.expand_frame_repr', False)


if __name__ == '__main__':
    file_names = glob.glob(FILE_MASK)
    pf = fp.ParquetFile(file_names, root='./events')
    pf.cats = {'customer': pf.cats['customer']}
    df = pf.to_pandas()

    # Round timestamps down to an hour
    df['ts'] = df['ts'].map(lambda x: x.replace(minute=0, second=0, microsecond=0))

    # group on customer, timestamp and url.
    gb = df.groupby(['customer', 'url', 'ts'])

    ag = gb.apply(lambda d: pd.DataFrame({
        'views': len(d),
        'visitors': d.session_id.count(),
        'referrers': [d.referrer.tolist()]})).reset_index()

    print(ag.head())
```

full code that doesn't:

```
import glob
import pandas as pd
import fastparquet as fp
import dask.dataframe as dd
from dask.dataframe import utils
from dask import delayed

FILE_MASK = './events/*/*/*/*/*/*.*.parquet'
pd.set_option('display.expand_frame_repr', False)


if __name__ == '__main__':
    file_names = glob.glob(FILE_MASK)
    pf = fp.ParquetFile(file_names, root='./events')
    pf.cats = {'customer': pf.cats['customer']}
    dfs = (delayed(pf.read_row_group_file)(rg, pf.columns, pf.cats) for rg in pf.row_groups)
    df = dd.from_delayed(dfs)

    # Round timestamps down to an hour
    df['ts'] = df['ts'].map(lambda x: x.replace(minute=0, second=0, microsecond=0))

    # group on customer, timestamp and url.
    gb = df.groupby(['customer', 'url', 'ts'])

    ag = gb.apply(lambda d: pd.DataFrame({
        'views': len(d),
        'visitors': d.session_id.count(),
        'referrers': [d.referrer.tolist()]})).reset_index()

    print(ag.compute())
```

I installed dask from git master:

```
-e git://github.com/dask/dask.git@c359e88894da54a9cd1fcd92cbdc223ec58ee3ef#egg=dask
```

Any help is appreciated. I'm struggling with this.

**Comment by martindurant** [comment]
I did have it working, but not with the exact code above. It actually only fails if including `reset_index()`. Looking at the partitions, some have the full three levels, and some do not: the ones with only one visitor/referrer. I really don't know why.

**Comment by j-bennet** [comment]
@martindurant Oh, that's something! How do you see what partitions have what levels?

**Comment by martindurant** [comment]
Do a `.compute()` on the ag *before* tacking on the reset_index. Also, you can do `get_partition(i)` with `i` an integer; I see that some partitions are apparently empty, presumably corresponding to combinations of the group parameters with no results. I don't know if that's a problem.

**Comment by j-bennet** [comment]
@martindurant Odd. That data didn't have any null fields in it - how can there be partitions with no data?

**Comment by martindurant** [comment]
That part is OK, I'm sure: dask makes a partition for every possible combination of labels, and doesn't know before doing the calculation that there will be none in some given partition.
The index going weird in some partitions is I think the problem. Maybe @jcrist knows what can happen in these multi-field groupby-apply cases.

**Comment by j-bennet** [comment]
@martindurant Would you be able to give an example of correctly specifying `meta`?

**Comment by j-bennet** [comment]
So, with all this, I now have the grouped dataframe:

```
    agg_info = {
        'page_views': 'i4',
        'visitors': 'i4',
        'referrers': 'object',
    }
    agg_meta = utils.make_meta(agg_info)
    ag = gb.apply(lambda d: pd.DataFrame({
        'page_views': len(d),
        'visitors': d.session_id.count(),
        'referrers': [d.referrer.tolist()]
    }), meta=agg_meta)
```

Going further, I am attempting to transform a grouped dataframe into a dataframe that only has one column called "data", and each field value is a string. To do that, I'm applying a function to my dataframe:

```
# I want index to be a part of dataframe, so it is passed
# to the next .apply call.
df['index'] = df.index
return df.apply(transform_one, axis=1, meta={'data': str}).to_bag()
```

and the applied function is as follows:

```
def transform_one(series):
    """Takes a Series object representing a grouped dataframe row,
    and returns a string (serialized JSON).

    :return: dict
    """
    data = series.to_dict()
    (customer, url, ts, _) = data.pop('index')
    page_views = data.pop('page_views')
    visitors = data.pop('visitors')
    data.update({
        'customer': customer,
        'url': url,
        'ts': ts.strftime('%Y-%m-%dT%H:%M:%S'),
        'metrics': {'page_views': page_views, 'visitors': visitors}
    })
    serialized = json.dumps(data)
    return pd.DataFrame({'data': [serialized]})
```

This throws an exception:

```
Traceback (most recent call last):
  File "aggregate_dask.py", line 115, in <module>
    save_json(prepared, OUTPUT_MASK)
  File "aggregate_dask.py", line 108, in save_json
    df.repartition(npartitions=1).to_textfiles(path)
  File "/Users/irina/.pyenv/versions/talks/src/dask/dask/bag/core.py", line 644, in to_textfiles
    compute, get=get, storage_options=storage_options)
  File "/Users/irina/.pyenv/versions/talks/src/dask/dask/bag/core.py", line 187, in to_textfiles
    delayed(out).compute(get=get)
  File "/Users/irina/.pyenv/versions/talks/src/dask/dask/base.py", line 99, in compute
    (result,) = compute(self, traverse=False, **kwargs)
  File "/Users/irina/.pyenv/versions/talks/src/dask/dask/base.py", line 206, in compute
    results = get(dsk, keys, **kwargs)
  File "/Users/irina/.pyenv/versions/talks/src/dask/dask/multiprocessing.py", line 177, in get
    raise_exception=reraise, **kwargs)
  File "/Users/irina/.pyenv/versions/talks/src/dask/dask/local.py", line 521, in get_async
    raise_exception(exc, tb)
  File "/Users/irina/.pyenv/versions/talks/src/dask/dask/local.py", line 290, in execute_task
    result = _execute_task(task, data)
  File "/Users/irina/.pyenv/versions/talks/src/dask/dask/local.py", line 270, in _execute_task
    args2 = [_execute_task(a, cache) for a in args]
  File "/Users/irina/.pyenv/versions/talks/src/dask/dask/local.py", line 271, in _execute_task
    return func(*args2)
  File "/Users/irina/.pyenv/versions/talks/src/dask/dask/dataframe/core.py", line 3189, in apply_and_enforce
    df = func(*args, **kwargs)
  File "/Users/irina/.pyenv/versions/talks/src/dask/dask/utils.py", line 688, in __call__
    return getattr(obj, self.method)(*args, **kwargs)
  File "/Users/irina/.pyenv/versions/talks/lib/python2.7/site-packages/pandas/core/frame.py", line 4262, in apply
    ignore_failures=ignore_failures)
  File "/Users/irina/.pyenv/versions/talks/lib/python2.7/site-packages/pandas/core/frame.py", line 4375, in _apply_standard
    result = self._constructor(data=results, index=index)
  File "/Users/irina/.pyenv/versions/talks/lib/python2.7/site-packages/pandas/core/frame.py", line 275, in __init__
    mgr = self._init_dict(data, index, columns, dtype=dtype)
  File "/Users/irina/.pyenv/versions/talks/lib/python2.7/site-packages/pandas/core/frame.py", line 411, in _init_dict
    return _arrays_to_mgr(arrays, data_names, index, columns, dtype=dtype)
  File "/Users/irina/.pyenv/versions/talks/lib/python2.7/site-packages/pandas/core/frame.py", line 5506, in _arrays_to_mgr
    return create_block_manager_from_arrays(arrays, arr_names, axes)
  File "/Users/irina/.pyenv/versions/talks/lib/python2.7/site-packages/pandas/core/internals.py", line 4314, in create_block_manager_from_arrays
    construction_error(len(arrays), arrays[0].shape, axes, e)
  File "/Users/irina/.pyenv/versions/talks/lib/python2.7/site-packages/pandas/core/internals.py", line 4280, in construction_error
    passed, implied))
ValueError: Shape of passed values is (2, 1), indices imply (2, 4)
```

I'm probably not returning the right thing from my `transform_one` function, but I tried returning all kinds of things: scalar, tuple, `pd.Series`, `pd.DataFrame`, and everything fails with different errors.

I hope you can help.

**Comment by j-bennet** [comment]
@martindurant A piece of good news, `reset_index` also works if I provide `drop=True`. So now I do this:

```
    ag['index'] = ag.index
    ag = ag.reset_index(drop=True)
```

But the last transformation still does not work whatever I do. I tried using `delayed` instead of `apply`, like this:

```
    parts = dd.to_delayed(ag)
    tasks = [delayed(transform_data)(p) for p in parts]
    agg_meta = utils.make_meta({'data': str})
    values = dd.from_delayed(tasks, meta=agg_meta)
    bg = values.to_bag()
```

With that, there's a yet another error:

```
Traceback (most recent call last):
  File "aggregate_dask.py", line 125, in <module>
    save_json(prepared, OUTPUT_MASK)
  File "aggregate_dask.py", line 118, in save_json
    bg.repartition(npartitions=1).to_textfiles(path)
  File "/Users/irina/.pyenv/versions/talks/src/dask/dask/bag/core.py", line 644, in to_textfiles
    compute, get=get, storage_options=storage_options)
  File "/Users/irina/.pyenv/versions/talks/src/dask/dask/bag/core.py", line 187, in to_textfiles
    delayed(out).compute(get=get)
  File "/Users/irina/.pyenv/versions/talks/src/dask/dask/base.py", line 99, in compute
    (result,) = compute(self, traverse=False, **kwargs)
  File "/Users/irina/.pyenv/versions/talks/src/dask/dask/base.py", line 206, in compute
    results = get(dsk, keys, **kwargs)
  File "/Users/irina/.pyenv/versions/talks/src/dask/dask/multiprocessing.py", line 177, in get
    raise_exception=reraise, **kwargs)
  File "/Users/irina/.pyenv/versions/talks/src/dask/dask/local.py", line 521, in get_async
    raise_exception(exc, tb)
  File "/Users/irina/.pyenv/versions/talks/src/dask/dask/local.py", line 290, in execute_task
    result = _execute_task(task, data)
  File "/Users/irina/.pyenv/versions/talks/src/dask/dask/local.py", line 270, in _execute_task
    args2 = [_execute_task(a, cache) for a in args]
  File "/Users/irina/.pyenv/versions/talks/src/dask/dask/local.py", line 270, in _execute_task
    args2 = [_execute_task(a, cache) for a in args]
  File "/Users/irina/.pyenv/versions/talks/src/dask/dask/local.py", line 271, in _execute_task
    return func(*args2)
  File "aggregate_dask.py", line 98, in transform_data
    parts = dd.to_delayed(ag)
  File "/Users/irina/.pyenv/versions/talks/src/dask/dask/dataframe/core.py", line 3903, in to_delayed
    dsk = df._optimize(df.dask, df._keys())
  File "/Users/irina/.pyenv/versions/talks/lib/python2.7/site-packages/pandas/core/generic.py", line 3081, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'DataFrame' object has no attribute '_optimize'
```

**Comment by j-bennet** [comment]
After some more poking around, I was able to narrow down the problem to the dataframe's index being weird in some partitions.

When I use the smaller (hardcoded) data, the code works:

```
# -*- coding: utf-8
import pandas as pd
import dask.dataframe as dd
from pprint import pprint


pd.set_option('display.expand_frame_repr', False)


def transform_one(series):
    """Takes a Series object representing a grouped dataframe row,
    and returns a string (serialized JSON).

    :return: dict
    """
    data = series.to_dict()
    if not data:
        return pd.Series([], name='data')
    (customer, url, ts, _) = data.pop('index')
    page_views = data.pop('views')
    visitors = data.pop('visitors')
    data.update({
        'customer': customer,
        'url': url,
        'ts': ts.strftime('%Y-%m-%dT%H:%M:%S'),
        'metrics': {'views': page_views, 'visitors': visitors}
    })
    return pd.Series([data], name='data')


if __name__ == '__main__':
    pdf = pd.DataFrame.from_records([
        ("http://a.com/articles/1", "http://google.com/", "xxx", "2017-09-15 00:10:00", "a.com"),
        ("http://a.com/articles/2", "http://bing.com/", "yyy", "2017-09-15 00:20:00", "a.com"),
        ("http://a.com/articles/2", "http://facebook.com/", "yyy", "2017-09-15 00:30:00", "a.com"),
        ("http://a.com/articles/1", "http://google.com/", "xxx", "2017-09-15 01:10:00", "a.com"),
        ("http://a.com/articles/2", "http://bing.com/", "yyy", "2017-09-15 01:20:00", "a.com")
    ],
    columns=['url', 'referrer', 'session_id', 'ts', 'customer'])

    pdf['ts'] = pd.to_datetime(pdf['ts'])

    df = dd.from_pandas(pdf, 2)

    # round datetimes down to an hour
    df['ts'] = df['ts'].dt.floor('1H')

    # group on customer, timestamp (rounded) and url
    gb = df.groupby(['customer', 'url', 'ts'])

    df = gb.apply(lambda d: pd.DataFrame({
            'views': len(d),
            'visitors': d.session_id.count(),
            'referrers': [d.referrer.tolist()]}),
        meta={'views': int, 'visitors': int, 'referrers': int})

    # I want index to be a part of dataframe, so it is passed
    # to the next .apply call.
    df['index'] = df.index

    df = df.apply(transform_one, axis=1, meta={'data': str}).to_bag()

    pprint(df.compute())
```

When I read the parquet data:

```
# -*- coding: utf-8
import pandas as pd
import dask.dataframe as dd
import fastparquet as fp
import glob
from pprint import pprint
from dask import delayed


pd.set_option('display.expand_frame_repr', False)


def transform_one(series):
    """Takes a Series object representing a grouped dataframe row,
    and returns a string (serialized JSON).

    :return: dict
    """
    data = series.to_dict()
    if not data:
        return pd.Series([], name='data')
    (customer, url, ts, _) = data.pop('index')
    page_views = data.pop('views')
    visitors = data.pop('visitors')
    data.update({
        'customer': customer,
        'url': url,
        'ts': ts.strftime('%Y-%m-%dT%H:%M:%S'),
        'metrics': {'views': page_views, 'visitors': visitors}
    })
    return pd.Series([data], name='data')


if __name__ == '__main__':
    file_names = glob.glob('./events/*/*/*/*/*/part*.parquet')
    pf = fp.ParquetFile(file_names, root='./events')
    pf.cats = {'customer': pf.cats['customer']}
    dfs = (delayed(pf.read_row_group_file)(rg, pf.columns, pf.cats) for rg in pf.row_groups)
    df = dd.from_delayed(dfs)

    # round datetimes down to an hour
    df['ts'] = df['ts'].dt.floor('1H')

    # group on customer, timestamp (rounded) and url
    gb = df.groupby(['customer', 'url', 'ts'])

    df = gb.apply(lambda d: pd.DataFrame({
            'views': len(d),
            'visitors': d.session_id.count(),
            'referrers': [d.referrer.tolist()]}),
        meta={'views': int, 'visitors': int, 'referrers': int})

    # I want index to be a part of dataframe, so it is passed
    # to the next .apply call.
    df['index'] = df.index

    df = df.apply(transform_one, axis=1, meta={'data': str}).to_bag()

    pprint(df.compute())
```

it breaks with:

```
Traceback (most recent call last):
  File "aggregate2.py", line 59, in <module>
    pprint(df.compute())
  File "/Users/irina/.pyenv/versions/talks/src/dask/dask/base.py", line 99, in compute
    (result,) = compute(self, traverse=False, **kwargs)
  File "/Users/irina/.pyenv/versions/talks/src/dask/dask/base.py", line 206, in compute
    results = get(dsk, keys, **kwargs)
  File "/Users/irina/.pyenv/versions/talks/src/dask/dask/multiprocessing.py", line 177, in get
    raise_exception=reraise, **kwargs)
  File "/Users/irina/.pyenv/versions/talks/src/dask/dask/local.py", line 521, in get_async
    raise_exception(exc, tb)
  File "/Users/irina/.pyenv/versions/talks/src/dask/dask/local.py", line 290, in execute_task
    result = _execute_task(task, data)
  File "/Users/irina/.pyenv/versions/talks/src/dask/dask/local.py", line 270, in _execute_task
    args2 = [_execute_task(a, cache) for a in args]
  File "/Users/irina/.pyenv/versions/talks/src/dask/dask/local.py", line 271, in _execute_task
    return func(*args2)
  File "/Users/irina/.pyenv/versions/talks/src/dask/dask/dataframe/core.py", line 3189, in apply_and_enforce
    df = func(*args, **kwargs)
  File "/Users/irina/.pyenv/versions/talks/src/dask/dask/utils.py", line 688, in __call__
    return getattr(obj, self.method)(*args, **kwargs)
  File "/Users/irina/.pyenv/versions/talks/lib/python2.7/site-packages/pandas/core/frame.py", line 4262, in apply
    ignore_failures=ignore_failures)
  File "/Users/irina/.pyenv/versions/talks/lib/python2.7/site-packages/pandas/core/frame.py", line 4359, in _apply_standard
    results[i] = func(v)
  File "aggregate2.py", line 22, in transform_one
    (customer, url, ts, _) = data.pop('index')
TypeError: ("'int' object is not iterable", u'occurred at index 0')
```

If I inspect the index of my dataframe with ipdb, I see that in some partitions, `index` is not a tuple, as it should be:

```
ipdb> df.index.get_partition(0).values.compute()
array([], dtype=int64)
ipdb> df.index.get_partition(1).values.compute()
array([ ('a.com', u'http://a.com/articles/1', Timestamp('2017-09-15 09:00:00'), 0),
       ('a.com', u'http://a.com/articles/1', Timestamp('2017-09-15 20:00:00'), 0),
       ('a.com', u'http://a.com/articles/2', Timestamp('2017-09-15 04:00:00'), 0)], dtype=object)
ipdb> df.index.get_partition(1).values.compute()
2array([ ('a.com', u'http://a.com/articles/1', Timestamp('2017-09-15 09:00:00'), 0),
       ('a.com', u'http://a.com/articles/1', Timestamp('2017-09-15 20:00:00'), 0),
       ('a.com', u'http://a.com/articles/2', Timestamp('2017-09-15 04:00:00'), 0)], dtype=object)
ipdb> df.index.get_partition(2).values.compute()
array([], dtype=int64)
ipdb> df.index.get_partition(3).values.compute()
array([('a.com', u'http://a.com/articles/2', Timestamp('2017-09-15 21:00:00'), 0)], dtype=object)
ipdb> df.index.get_partition(4).values.compute()
array([ ('a.com', u'http://a.com/articles/2', Timestamp('2017-09-15 06:00:00'), 0),
       ('a.com', u'http://a.com/articles/2', Timestamp('2017-09-15 08:00:00'), 0),
       ('a.com', u'http://a.com/articles/2', Timestamp('2017-09-15 10:00:00'), 0),
       ('a.com', u'http://a.com/articles/2', Timestamp('2017-09-15 18:00:00'), 0)], dtype=object)
ipdb> df.index.get_partition(5).values.compute()
array([ ('a.com', u'http://a.com/articles/1', Timestamp('2017-09-15 05:00:00'), 0),
       ('a.com', u'http://a.com/articles/2', Timestamp('2017-09-15 11:00:00'), 0),
       ('a.com', u'http://a.com/articles/2', Timestamp('2017-09-15 23:00:00'), 0)], dtype=object)
ipdb> df.index.get_partition(6).values.compute()
array([0])
```

An empty index array is no problem. But that `[0]` is, because everywhere else it's a 4-element tuple.

Why does this happen?

**Comment by mrocklin** [comment]
@martindurant is there any followup here?  Any lessons to be learned?  Are there live issues around the parquet experience?  If so then perhaps we should raise them as fresh issues, if not then can you close this?

**Comment by martindurant** [comment]
I didn't get to the bottom of this, it seems to have dropped off the radar.
@j-bennet , did you figure out what was going on or find a workaround?

**Comment by j-bennet** [comment]
I made several changes to my code, and this version works:

https://github.com/j-bennet/talks/blob/master/2018/daskvsspark/daskvsspark/aggregate_dask.py

I suspect that this is related to the changed aggregation part:

https://github.com/j-bennet/talks/blob/09965f678c9625f46214042e9d22ccb26187c98d/2018/daskvsspark/daskvsspark/aggregate_dask.py#L75-L90

But I can't be sure, as other things changed as well. Going to close the issue though.

Thank you for all the help!
