### ISSUE TITLE
Indexing by np.int64, regression from 0.15.2 to 0.15.3

### ISSUE THREAD

**Issue by chrisbarber** [dask/dask#2745]
Something with the handling of index types changed from 0.15.2 to 0.15.3. Easy enough to work around, so I haven't had time to look into it.

```
>>> import dask
>>> dask.__version__
'0.15.3'
>>> import numpy as np
>>> x=dask.array.from_array(np.zeros((4,4)), chunks=(2,2))
>>> dask.array.take(x, 0, axis=0)
dask.array<getitem, shape=(4,), dtype=float64, chunksize=(2,)>
>>> dask.array.take(x, np.int(0), axis=0)
dask.array<getitem, shape=(4,), dtype=float64, chunksize=(2,)>
>>> dask.array.take(x, np.int64(0), axis=0)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/local1/opt/miniconda3/envs/datacube-test/lib/python3.6/site-packages/dask/array/routines.py", line 663, in take
    return a[(slice(None),) * axis + (indices,)]
  File "/local1/opt/miniconda3/envs/datacube-test/lib/python3.6/site-packages/dask/array/core.py", line 1222, in __getitem__
    index2 = normalize_index(index, self.shape)
  File "/local1/opt/miniconda3/envs/datacube-test/lib/python3.6/site-packages/dask/array/slicing.py", line 762, in normalize_index
    raise IndexError("Too many indices for array")
IndexError: Too many indices for array
```

**Comment by shoyer** [comment]
This is fixed on master (https://github.com/dask/dask/pull/2719), but we need a new release.

**Comment by mrocklin** [comment]
Released.
