### ISSUE TITLE
Passing an unexpected keyword to BokehTornado

### ISSUE THREAD

**Issue by poeticcapybara** [dask/dask#2834]
On the latest conda version, I get an error in the bokeh server launching a local scheduler. Working on bokeh 0.12.9.

```
...>conda create -n testdask python=3.6 dask
Fetching package metadata .............
Solving package specifications: .

Package plan for installation in environment 
...\AppData\Local\Continuum\Miniconda3\envs\testdask:

The following NEW packages will be INSTALLED:

    asn1crypto:       0.22.0-py36h8e79faa_1
    bokeh:            0.12.10-py36h0be3b39_0
    ca-certificates:  2017.08.26-h94faf87_0
    cachecontrol:     0.12.3-py36hfe50d7b_0
    certifi:          2017.7.27.1-py36h043bc9e_0
    cffi:             1.10.0-py36hae3d1b5_1
    chardet:          3.0.4-py36h420ce6e_1
    click:            6.7-py36hec8c647_0
    cloudpickle:      0.4.0-py36h639d8dc_0
    colorama:         0.3.9-py36h029ae33_0
    cryptography:     2.0.3-py36h123decb_1
    dask:             0.15.3-py36h396fcb9_0
    dask-core:        0.15.3-py36hd651449_0
    distlib:          0.2.5-py36h51371be_0
    distributed:      1.19.1-py36h8504682_0
    heapdict:         1.0.0-py36h21fa5f4_0
    html5lib:         0.999999999-py36ha09b1f3_0
    icc_rt:           2017.0.4-h97af966_0
    idna:             2.6-py36h148d497_1
    intel-openmp:     2018.0.0-hcd89f80_7
    jinja2:           2.9.6-py36h10aa3a0_1
    locket:           0.2.0-py36hfed976d_1
    lockfile:         0.12.2-py36h0468280_0
    markupsafe:       1.0-py36h0e26971_1
    mkl:              2018.0.0-h36b65af_4
    msgpack-python:   0.4.8-py36h58b1e9d_0
    numpy:            1.13.3-py36ha320f96_0
    openssl:          1.0.2l-vc14hcac20b0_2      [vc14]
    packaging:        16.8-py36ha0986f6_1
    pandas:           0.20.3-py36hce827b7_2
    partd:            0.3.8-py36hc8e763b_0
    pip:              9.0.1-py36hadba87b_3
    progress:         1.3-py36hbeca8d3_0
    psutil:           5.4.0-py36h4e662fb_0
    pycparser:        2.18-py36hd053e01_1
    pyopenssl:        17.2.0-py36h15ca2fc_0
    pyparsing:        2.2.0-py36h785a196_1
    pysocks:          1.6.7-py36h698d350_1
    python:           3.6.3-h9e2ca53_1
    python-dateutil:  2.6.1-py36h509ddcb_1
    pytz:             2017.2-py36h05d413f_1
    pyyaml:           3.12-py36h1d1928f_1
    requests:         2.18.4-py36h4371aae_1
    setuptools:       36.5.0-py36h65f9e6e_0
    six:              1.11.0-py36h4db2310_1
    sortedcontainers: 1.5.7-py36ha90ac20_0
    tblib:            1.3.2-py36h30f5020_0
    toolz:            0.8.2-py36he152a52_0
    tornado:          4.5.2-py36h57f6048_0
    urllib3:          1.22-py36h276f60a_0
    vc:               14-h2379b0c_2
    vs2015_runtime:   14.0.25123-hd4c4e62_2
    webencodings:     0.5.1-py36h67c50ae_1
    wheel:            0.29.0-py36h6ce6cde_1
    win_inet_pton:    1.0.1-py36he67d7fd_1
    wincertstore:     0.2-py36h7fe50ca_0
    yaml:             0.1.7-vc14hb31d195_1       [vc14]
    zict:             0.1.3-py36h2d8e73e_0

Proceed ([y]/n)?

#
# To activate this environment, use:
# > activate testdask
#
# To deactivate an active environment, use:
# > deactivate
#
# * for power-users using bash, you must source
#


...>activate testdask

(testdask) ...>dask-scheduler
distributed.scheduler - INFO - -----------------------------------------------
distributed.scheduler - INFO - Could not launch service: ('bokeh', 8787)
Traceback (most recent call last):
  File "...\AppData\Local\Continuum\Miniconda3\envs\testdask\lib\site-packages\distributed\scheduler.py", line 430, in start_services
    service.listen((listen_ip, port))
  File "...\AppData\Local\Continuum\Miniconda3\envs\testdask\lib\site-packages\distributed\bokeh\core.py", line 31, in listen
    **kwargs)
  File "...\AppData\Local\Continuum\Miniconda3\envs\testdask\lib\site-packages\bokeh\server\server.py", line 371, in __init__
    tornado_app = BokehTornado(applications, extra_websocket_origins=extra_websocket_origins, prefix=self.prefix, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'host'
distributed.scheduler - INFO -   Scheduler at:   tcp://10.100.26.50:8786
distributed.scheduler - INFO -        http at:                     :9786
distributed.scheduler - INFO - Local Directory: ...\AppData\Local\Temp\1\scheduler-58u38wdd
distributed.scheduler - INFO - -----------------------------------------------
distributed.scheduler - INFO - End scheduler at 'tcp://:8786'

(testdask) ...>conda install bokeh=0.12.9
Fetching package metadata .............
Solving package specifications: .

Package plan for installation in environment 
...\AppData\Local\Continuum\Miniconda3\envs\testdask:

The following packages will be DOWNGRADED:

    bokeh: 0.12.10-py36h0be3b39_0 --> 0.12.9-py36h4605247_0

Proceed ([y]/n)?


(testdask) ...>dask-scheduler
distributed.scheduler - INFO - -----------------------------------------------
distributed.scheduler - INFO -   Scheduler at:   tcp://10.100.26.50:8786
distributed.scheduler - INFO -        http at:                     :9786
distributed.scheduler - INFO -       bokeh at:                     :8787
distributed.scheduler - INFO - Local Directory: ...\AppData\Local\Temp\1\scheduler-kgkaxxka
distributed.scheduler - INFO - -----------------------------------------------
distributed.scheduler - INFO - End scheduler at 'tcp://:8786'
```

**Comment by mrocklin** [comment]
Yes, this is a known bug.  It was fixed in the latest version of distributed.  Try the following:

    conda install -c conda-forge distributed

**Comment by poeticcapybara** [comment]
Fixed it. Thanks for the quick reply.
