### ISSUE TITLE
argtopk for dask arrays

### ISSUE THREAD

**Issue by rzu512** [dask/dask#2859]
I am trying to implement an argtopk function, but can't quite isolate the topk function of dask.
It would give the indices to the top k elements in additional to the values of the top k elements.

Can we have a function like that?

**Comment by jcrist** [comment]
What collection are you refering to? `dask.array`? `dask.bag`? `dask.dataframe`?

**Comment by jcrist** [comment]
We don't have `argtopk` but we do have `topk`. This should be fairly straightforward to implement though. You'd want to keep track of the absolute indices of each value you keep when doing the map step. Then at the end you'd add the appropriate chunk-wise offsets to the indices before doing the final reduction. A similar approach is taken in other `da.arg*` functions. This would be a welcome addition if you feel up for submitting a PR 😄.

> The following repository has an argtopk function...

You are correct in your analysis here. That code is also very old, and I wouldn't use it as a reference.

---

I also responded to your [stackoverflow question](https://stackoverflow.com/questions/47083683/isolating-the-topk-routine-of-dask). Copying my response here:

> Your example above fails  because you're using code you copied from the master branch with an  older dask install. Some of the non-public methods were renamed in the  last few weeks. Your code above works if you install dask from master.

**Comment by rzu512** [comment]
I installed master branch. but the following code still fails.

```
import numpy as np
import dask.array as da
from dask.base import tokenize
from operator import getitem
import dask.sharedict as sharedict
from dask.array.core import Array

def topk(k, x):
    if x.ndim != 1:
        raise ValueError("Topk only works on arrays of one dimension")

    token = tokenize(k, x)
    name = 'chunk.topk-' + token
    dsk = {(name, i): (topk, k, key)
           for i, key in enumerate(x.__dask_keys__())}
    name2 = 'topk-' + token
    dsk[(name2, 0)] = (getitem, (np.sort, (np.concatenate, list(dsk))),
                       slice(-1, -k - 1, -1))
    chunks = ((k,),)

    return Array(sharedict.merge((name2, dsk), x.dask), name2, chunks, dtype=x.dtype)

def main():
    x = np.arange(12)*8
    y = da.from_array(x, 7)
    print(y.topk(2).compute())
    print(topk(2, y).compute())

main()
```

**Comment by jcrist** [comment]
You didn't accurately extract the topk routine. This runs fine:

```python
from operator import getitem

import numpy as np
import dask.array as da
from dask import sharedict
from dask.base import tokenize


def topk(k, x):
    if x.ndim != 1:
        raise ValueError("Topk only works on arrays of one dimension")

    token = tokenize(k, x)
    name = 'chunk.topk-' + token
    dsk = {(name, i): (da.chunk.topk, k, key)
           for i, key in enumerate(x.__dask_keys__())}
    name2 = 'topk-' + token
    dsk[(name2, 0)] = (getitem, (np.sort, (np.concatenate, list(dsk))),
                       slice(-1, -k - 1, -1))
    chunks = ((k,),)

    return da.Array(sharedict.merge((name2, dsk), x.dask), name2, chunks, dtype=x.dtype)


x = np.arange(10)
y = da.from_array(x, chunks=5)
print(topk(2, y).compute())
```

**Comment by rzu512** [comment]
But that uses "da.chunk.topk" in this line, instead of the topk function within the code.

`dsk = {(name, i): (da.chunk.topk, k, key)`

**Comment by jcrist** [comment]
Yes, it needs to. There are two `topk` functions:

- `da.routines.topk` (and the `da.Array.topk` method that calls it). This takes a dask array and returns a dask array representing the topk elements
- `da.chunk.topk`, which operates on the individual numpy array chunks that compose the larger input array to the above.

If you use the same one for both you'll get errors.

**Comment by rzu512** [comment]
I tried to implement axis keyword for topk:

https://stackoverflow.com/questions/47106057/dask-implementing-axis-keyword-for-topk

**Comment by rzu512** [comment]
I tried to use dask's reduction to make argtopk.
Somehow, it doesn't work. I don't know why.
I am trying to isolate argmin of dask.array now.

Program:
```
import numpy as np
import dask.array as da
import dask
from functools import partial
import dask.array.reductions
from dask.array.chunk import keepdims_wrapper


# -- Utility -------------------------------------------------------------------
def tuple_replace(tuple_in, ind, new_element):
    """Make new tuple with the ind^{th} element replaced
    Parameters
    ----------
        tuple_in : tuple
            the input tuple, which is not modified.
        ind : int
            We want to replace the element at tuple_in[ind] by the new element.
        new_element : object
            The new element.
    Returns
    -------
        new_tuple : tuple
            The new tuple.
    """
    t_as_list = list(tuple_in)
    t_as_list[ind] = new_element
    return tuple(t_as_list)


def index_along_axis(ind, axis, shape=None):
    """Convert indexing along an axis to proper multi-index or flat index
    Parameters
    ----------
        ind : np.ndarray
            Indexing of an array along an axis.
            For a 2D array arr and axis=1, this means: from each column of
            arr, select elements along the column by the indices at the
            corresponding column of ind. In other words, the ith column of
            the result is arr[ind[:, i], i].
        axis : int
        shape : tuple
            Shape of the array that is indexed by ind. If this is None,
            the function returns a multi-index. Otherwise, the function
            returns a flat index.
    Returns
    -------
        proper_index : tuple or np.ndarray
            if shape is None, return the multi-indexing equivalent to ind.
            if arr is provided, return the flat indexing equivalent to ind.
    Example
    -------
        >>> import numpy as np
        >>> arr = np.flip(np.arange(8).reshape(2, 4), axis=1)  # test array
        >>> ind = np.argsort(arr, axis=1)  # indexing along axis 1
        >>> multi_ind = index_along_axis(ind, axis=1)  # convert to multi-index
        >>> multi_ind
        (array([[0],
               [1]]), array([[3, 2, 1, 0],
               [3, 2, 1, 0]]))
        >>> flat_ind = index_along_axis(ind, axis=1, shape=arr.shape)
        >>> flat_ind  # show the flat indexing
        array([[3, 2, 1, 0],
               [7, 6, 5, 4]])
        >>> a = np.sort(arr, axis=1)  # the indexing give the expected result.
        >>> a
        array([[0, 1, 2, 3],
               [4, 5, 6, 7]])
        >>> np.all(a == arr[multi_ind]) and np.all(a == arr.flatten()[flat_ind])
        True
    """
    # https://stackoverflow.com/questions/47044792 by Divakar
    # Does not check if axis is legal
    idx = np.ogrid[tuple(map(slice, ind.shape))]
    idx[axis] = ind
    idx = tuple(idx)
    if shape is None:
        return idx
    else:
        return np.ravel_multi_index(idx, dims=shape)


# -- Chunk ---------------------------------------------------------------------
def topk_over_chunk(k, x, axis=-1):
    """Get the top k elements in a numpy array along an axis
    The k elements are also sorted along the axis from large to small.
    Parameters
    ----------
        k : int
            number of elements to selected along the axis
        x : np.ndarray
            the array
        axis : int
            the axis
    Returns
    -------
        topk_array : np.ndarray
            k largest elements along the axis
    """
    k = min(k, x.shape[axis])
    p = np.partition(x, -k, axis=axis)
    # get last k elements, which are not sorted
    s = -1 - np.arange(k, dtype=int)
    topk_arr = p.take(s, axis=axis)
    # Sort from large to small along the axis.
    topk_sorted = np.flip(np.sort(topk_arr, axis=axis), axis=axis)
    return topk_sorted


def argtopk_over_chunk(k, x, axis=-1):
    """Get the indices to the top-k elements in a numpy array along an axis
    The k elements are sorted along the axis from large to small.
    Parameters
    ----------
        k : int
            number of elements to selected along the axis
        x : np.ndarray
            the array
        axis : int
            the axis
    Returns
    -------
        argtopk_array : np.ndarray
            indices to the k largest elements along the axis
    """
    k = min(k, x.shape[axis])
    s = -1 - np.arange(k, dtype=int)

    # get indices to the top-k elements, which are not sorted
    arg_p = np.argpartition(x, -k, axis=axis)
    argtopk_arr = arg_p.take(s, axis=axis)

    # get the top-k elements, which are not sorted
    p = np.partition(x, -k, axis=axis)
    topk_arr = p.take(s, axis=axis)

    # Argsort the top-k elements from large to small along the axis.
    argtopk_sorted = np.flip(np.argsort(topk_arr, axis=axis), axis=axis)

    # Apply indices from argsort of top-k elements to the overall indices to
    # the top-k elements
    return argtopk_arr.reshape(-1)[argtopk_sorted]


def topk_chunks(k, x, axis):
    """Calculate new chunk shape for mapping argtopk or topk over a dask array.
    Parameters
    ----------
        k : int
            number of elements to selected along the axis
        x : dask.core.Array
            the dask array
        axis : int
            the axis
    Returns
    -------
        chunks : tuple
            chunk shape.
    """
    return tuple_replace(
        x.chunks, axis,
        tuple([min(k, c) for c in x.chunks[axis]])
    )


# -- Overall -------------------------------------------------------------------
def argtopk(k, x, axis):
    topk_chunk_f = keepdims_wrapper(partial(topk_over_chunk, k))
    argtopk_chunk_f = keepdims_wrapper(partial(argtopk_over_chunk, k))
    callable = dask.array.reductions.make_arg_reduction(
        topk_chunk_f, argtopk_chunk_f)
    return callable(x, axis)


# -- Main ----------------------------------------------------------------------
def main():
    dask.set_options(get=dask.get)
    x = np.arange(8).reshape(2, 4)
    y = da.from_array(x, 2)
    k = 2

    print("original:")
    print(y.compute())
    for axis in range(x.ndim):
        print("---- axis: %d, k: %d ----" % (-axis, k))
        r = argtopk(k, y, -axis)
        r.visualize('test.png')
        print(r.compute())


main()
```

Result:
```
original:
[[0 1 2 3]
 [4 5 6 7]]
---- axis: 0, k: 2 ----
Traceback (most recent call last):
  File "<dir>/dask_extend/argtopk/argtopk1.py", line 190, in <module>
    main()
  File "<dir>/dask_extend/argtopk/argtopk1.py", line 187, in main
    print(r.compute())
  File "<python3.5>/site-packages/dask/base.py", line 99, in compute
    (result,) = compute(self, traverse=False, **kwargs)
  File "<python3.5>/site-packages/dask/base.py", line 206, in compute
    results = get(dsk, keys, **kwargs)
  File "<python3.5>/site-packages/dask/local.py", line 562, in get_sync
    return get_async(apply_sync, 1, dsk, keys, **kwargs)
  File "<python3.5>/site-packages/dask/local.py", line 529, in get_async
    fire_task()
  File "<python3.5>/site-packages/dask/local.py", line 504, in fire_task
    callback=queue.put)
  File "<python3.5>/site-packages/dask/local.py", line 551, in apply_sync
    res = func(*args, **kwds)
  File "<python3.5>/site-packages/dask/local.py", line 295, in execute_task
    result = pack_exception(e, dumps)
  File "<python3.5>/site-packages/dask/local.py", line 290, in execute_task
    result = _execute_task(task, data)
  File "<python3.5>/site-packages/dask/local.py", line 271, in _execute_task
    return func(*args2)
  File "<python3.5>/site-packages/toolz/functoolz.py", line 468, in __call__
    ret = f(ret)
  File "<python3.5>/site-packages/dask/array/reductions.py", line 516, in arg_agg
    return _arg_combine(data, axis, argfunc, keepdims=False)[0]
  File "<python3.5>/site-packages/dask/array/reductions.py", line 472, in _arg_combine
    vals = vals[inds]
IndexError: too many indices for array

```

**Comment by rzu512** [comment]
dask's _arg_combine get a 3D array from the code for argtopk
dask's _arg_combine get a 2D array from the following isolation of argmin.

Partially isolated argmin:

```
import numpy as np
import dask.array as da
import dask
import dask.array.reductions
from dask.array.chunk import keepdims_wrapper

# -- Overall -------------------------------------------------------------------
def argmin(x, axis):

    min_chunk_f = keepdims_wrapper(np.min)
    argmin_chunk_f = keepdims_wrapper(np.argmin)
    callable = dask.array.reductions.make_arg_reduction(
        min_chunk_f, argmin_chunk_f)
    return callable(x, axis)


# -- Main ----------------------------------------------------------------------
def main():
    dask.set_options(get=dask.get)
    x = np.arange(12).reshape(3, 4)
    y = da.from_array(x, 2)

    print("original:")
    print(y.compute())
    axis = 0
    print("---- axis: %d ----" % (-axis))
    r = argmin(y, -axis)
    r.visualize('test.png')
    fin = r.compute()
    print("final result", fin)


main()

```
Result:

```
original:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
---- axis: 0 ----
DEBUG
arg:
[[0 0]
 [2 2]]
---- debug ----
vals:
[[0 1]
 [8 9]]
inds:
[array([0, 0]), array([0, 1])]
---- end debug ----
vals[inds]:
[0 1]
arg[inds]:
[0 0]
DEBUG
arg:
[[0 0]
 [2 2]]
---- debug ----
vals:
[[ 2  3]
 [10 11]]
inds:
[array([0, 0]), array([0, 1])]
---- end debug ----
vals[inds]:
[2 3]
arg[inds]:
[0 0]
final result [0 0 0 0]
```

**Comment by rzu512** [comment]
Probably I can't use the arg_reduction function in dask.array.reductions to implement argtopk.
I guess arg_reduction expected that each chunk is reduced to a dimension of 1 along the target axis.
This is because of the new chunk shape that arg_reduction calculates.

The comments I added starts with {{ and ends with }}.
```
def arg_reduction(x, chunk, combine, agg, axis=None, split_every=None,
                  out=None):
    """Generic function for argreduction.

    Parameters
    ----------
    x : Array
    chunk : callable
        Partialed ``arg_chunk``.
    combine : callable
        Partialed ``arg_combine``.
    agg : callable
        Partialed ``arg_agg``.
    axis : int, optional
    split_every : int or dict, optional
    """
    if axis is None:
        # {{ Does axis == None mean to perform reduction over all axes? }}
        axis = tuple(range(x.ndim))  # {{ axis can be a tuple of integers }}
        ravel = True
    elif isinstance(axis, int):
        # {{
        # Normalize the axis.
        #     Might be simpler to use:
        #         axis = np.core.multiarray.normalize_axis_index(axis, x.ndim)
        #         axis = (axis,)
        # }}
        if axis < 0:
            axis += x.ndim
        if axis < 0 or axis >= x.ndim:
            raise ValueError("axis entry is out of bounds")
        axis = (axis,)
        ravel = x.ndim == 1  # {{ Check if we need to ravel }}
    else:
        raise TypeError("axis must be either `None` or int, "
                        "got '{0}'".format(axis))

    # Map chunk across all blocks
    name = 'arg-reduce-chunk-{0}'.format(tokenize(chunk, axis))
    old = x.name
    # {{
    # keys is the list of multi-indices for each element of the array.
    # For example, an 2 x 3 array would have keys:
    #     (0, 0), (0, 1), (0, 2), (1, 0), (1, 1), (1, 2)
    # }}
    keys = list(product(*map(range, x.numblocks)))
    # {{
    # offsets is the list of offsets of each chunk within the overall array
    # For example,
    #     a chunk shape of ((2,), (2, 2)) mean the overall array is:
    #         *a------*b------+
    #         | 2 x 2 | 2 x 2 |
    #         +-------+-------+
    #         chunk0  chunk1
    #
    #     The offset of chunk0 is (0, 0), which is the coordinate of the *a
    #     corner within the overal array.
    #     The offset of chunk1 is (0, 2), which is the coordinate of the *b
    #     corner within the overall array.
    # }}
    offsets = list(product(*(accumulate(operator.add, bd[:-1], 0)
                             for bd in x.chunks)))
    if ravel:
        # {{ offset_info is a generator that yields (offset, shape of overall
        # array) for each chunk in the overall array. }}
        offset_info = zip(offsets, repeat(x.shape))
    else:
        # {{
        # Get the offset of all chunks over the 0th target axis as a map
        # Example:
        #     axis:              (0,)
        #     offset:            [(0, 0), (0, 2)]
        #     0th target axis:   axis[0], which is 0
        #     list(offset_info): [0, 0]
        # }}
        offset_info = pluck(axis[0], offsets)

    # {{ Calculate new chunks }}
    chunks = tuple((1,) * len(c) if i in axis else c for (i, c)
                   in enumerate(x.chunks))
    
    dsk = dict(((name,) + k, (chunk, (old,) + k, axis, off)) for (k, off)
               in zip(keys, offset_info))
    # The dtype of `tmp` doesn't actually matter, just need to provide something
    tmp = Array(sharedict.merge(x.dask, (name, dsk)), name, chunks,
                dtype=x.dtype)
    dtype = np.argmin([1]).dtype
    result = _tree_reduce(tmp, agg, axis, False, dtype, split_every, combine)
    return handle_out(out, result)

```
