### ISSUE TITLE
dataframe integration with fastparquet not working

### ISSUE THREAD

**Issue by benepo** [dask/dask#2921]
**Setup:**

`lsb_release -a`

> No LSB modules are available.
> Distributor ID: Ubuntu
> Description:    Ubuntu 16.04.3 LTS
> Release:        16.04
> Codename:       xenial

`conda install -c conda-forge dask fastparquet python-snappy`

> dask                      0.16.0                     py_0    conda-forge
> fastparquet               0.1.3                    py36_0    conda-forge
> python-snappy             0.5.1                    py36_2    conda-forge

`cat test.csv`

> foo,bar
> 5,7.1
> 6,8.2
> 3,4.02

**Works:**

```
import pandas as pd
import fastparquet as fp

df = pd.read_csv('test.csv')
fp.write('test.parquet', df)
```

**Doesn't work:**

```
import dask.dataframe as dd
import fastparquet as fp

df = dd.read_csv('test.csv')
fp.write('test.parquet', df)
```

```
Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/lib/python3.6/site-packages/pandas/core/indexes/base.py", line 2522, in get_loc
    return self._engine.get_loc(key)
  File "pandas/_libs/index.pyx", line 117, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 139, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1265, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1273, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test.py", line 5, in <module>
    fp.write('test.parquet', df)
  File "/home/ubuntu/miniconda3/lib/python3.6/site-packages/fastparquet/writer.py", line 788, in write
    cols = set(data)
  File "/home/ubuntu/miniconda3/lib/python3.6/site-packages/dask/dataframe/core.py", line 2160, in __getitem__
    meta = self._meta[_extract_meta(key)]
  File "/home/ubuntu/miniconda3/lib/python3.6/site-packages/pandas/core/frame.py", line 2139, in __getitem__
    return self._getitem_column(key)
  File "/home/ubuntu/miniconda3/lib/python3.6/site-packages/pandas/core/frame.py", line 2146, in _getitem_column
    return self._get_item_cache(key)
  File "/home/ubuntu/miniconda3/lib/python3.6/site-packages/pandas/core/generic.py", line 1842, in _get_item_cache
    values = self._data.get(item)
  File "/home/ubuntu/miniconda3/lib/python3.6/site-packages/pandas/core/internals.py", line 3838, in get
    loc = self.items.get_loc(item)
  File "/home/ubuntu/miniconda3/lib/python3.6/site-packages/pandas/core/indexes/base.py", line 2524, in get_loc
    return self._engine.get_loc(self._maybe_cast_indexer(key))
  File "pandas/_libs/index.pyx", line 117, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 139, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1265, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1273, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 0

```

**Comment by martindurant** [comment]
Whilst this is perhaps not the best of error messages....

`fp.write('test.parquet', df)` only works with pandas data-frames, not dask dataframes. Dask provides an internal implementation of writing to parquet, which calls fastparquet (or pyarrow):

     df.to_parquet('test.parquet', engine='fastparquet')

The engine keyword will default to whichever of fastparquet/pyarrow you have available, and which have some different possible optional parameters. This function is also available as `dd.io.parquet.to_parquet`, but the above is the recommended method.

**Comment by benepo** [comment]
I see.  Thanks for that clarification.
