### ISSUE TITLE
len(dask scalar) gives an error

### ISSUE THREAD

**Issue by rainwoodman** [dask/dask#3058]
```
Traceback (most recent call last):
  File "make-pkhalo.py", line 12, in <module>
    print(cath200['Mass'][0])
  File "/home/yfeng1/anaconda3/install/envs/cfastpm/lib/python3.6/site-packages/nbodykit/base/catalog.py", line 75, in __str__
    if len(self) > 0:
  File "/home/yfeng1/anaconda3/install/envs/cfastpm/lib/python3.6/site-packages/dask/array/core.py", line 1064, in __len__
    return sum(self.chunks[0])
IndexError: tuple index out of range
```

The error is probably valid as self is a scalar, but the message could be more informative than an out of range index error.

**Comment by jcrist** [comment]
Thanks for the issue. A quick reproducer:

```python
In [1]: import dask.array as da

In [2]: x = da.ones((), chunks=())

In [3]: x
Out[3]: dask.array<wrapped, shape=(), dtype=float64, chunksize=()>

In [4]: len(x)
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-4-a7f4a5366567> in <module>()
----> 1 len(x)

~/Code/dask/dask/array/core.py in __len__(self)
   1112
   1113     def __len__(self):
-> 1114         return sum(self.chunks[0])
   1115
   1116     def __array_ufunc__(self, numpy_ufunc, method, *inputs, **kwargs):

IndexError: tuple index out of range
```

Should be a pretty simple fix, just need to check if `chunks` is empty, and throw a better error if so. Would you be willing to submit a PR?

**Comment by rainwoodman** [comment]
Thanks! I didn't get around to do this.
