### ISSUE TITLE
How to compare 2 dataframes to see what is missing in each? (Not in memory)

### ISSUE THREAD

**Issue by devbrian** [dask/dask#3183]
How would I compare 2 dataframes, and output what is in df1 and not df2, and vise versa without storing the entire dataframe in memory(the dataframes are massive)?  I tried using dask.dataframe.merge, however this will have to store an entire dataframe in memory with an extra column.  I need this done without storing an entire dataframe in memory, however the differences can be stored in memory (obviously).

**Comment by TomAugspurger** [comment]
Can you give an example (with data) of how you would do this for a small problem in pandas?

**Comment by devbrian** [comment]
`df1 = DataFrame({
'Buyer': ['Carl', 'Carl', 'Carl'],
'Quantity': [18, 3, 5, ]})

df2 = DataFrame({
'Buyer': ['Carl', 'Mark', 'Carl', 'Carl'],
'Quantity': [2, 1, 18, 5]})

merged = df1.merge(df2, indicator=True, how='outer')
print(merged[merged['_merge'] == 'right_only'])`

**Comment by TomAugspurger** [comment]
Does this suffice?

```python
In [20]: m = dd.merge(dd.from_pandas(df1, 2), dd.from_pandas(df2, 2), indicator=True, how='outer')

In [21]: m[m._merge != 'both'].compute()
Out[21]:
  Buyer  Quantity      _merge
1  Mark         1  right_only
0  Carl         3   left_only
2  Carl         2  right_only
```

**Comment by devbrian** [comment]
@TomAugspurger I get a memory error when attempting with large dataframes

**Comment by TomAugspurger** [comment]
Can you post an example and the traceback where it occurs?

How large do you expect that final dataframe to be?

**Comment by devbrian** [comment]
`Traceback (most recent call last):
  File "PycharmProjects/SkeletonCompareCSV/test2.py", line 17, in <module>
    m[m._merge != 'both'].compute()
  File "PycharmProjects\SkeletonCompareCSV\venv\lib\site-packages\dask\base.py", line 143, in compute
    (result,) = compute(self, traverse=False, **kwargs)
  File "PycharmProjects\SkeletonCompareCSV\venv\lib\site-packages\dask\base.py", line 392, in compute
    results = get(dsk, keys, **kwargs)
  File "PycharmProjects\SkeletonCompareCSV\venv\lib\site-packages\dask\threaded.py", line 75, in get
    pack_exception=pack_exception, **kwargs)
  File "PycharmProjects\SkeletonCompareCSV\venv\lib\site-packages\dask\local.py", line 521, in get_async
    raise_exception(exc, tb)
  File "PycharmProjects\SkeletonCompareCSV\venv\lib\site-packages\dask\compatibility.py", line 67, in reraise
    raise exc
  File "PycharmProjects\SkeletonCompareCSV\venv\lib\site-packages\dask\local.py", line 290, in execute_task
    result = _execute_task(task, data)
  File "PycharmProjects\SkeletonCompareCSV\venv\lib\site-packages\dask\local.py", line 271, in _execute_task
    return func(*args2)
  File "PycharmProjects\SkeletonCompareCSV\venv\lib\site-packages\dask\compatibility.py", line 48, in apply
    return func(*args, **kwargs)
  File "PycharmProjects\SkeletonCompareCSV\venv\lib\site-packages\dask\dataframe\io\csv.py", line 62, in pandas_read_text
    bio.write(b)
MemoryError`

The final dataframe is extremely small, I am trying 2 tests, 1 is when there is one data point difference between the 2 dataframes and a test when the dataframes are identical.  Both throw the error, so it's not that the final dataframe is to big.

@TomAugspurger

**Comment by devbrian** [comment]
```
df1 = dd.read_csv('1.csv', sep=',', header=None)
df2 = dd.read_csv('1.csv', sep=',', header=None)
m = dd.merge(df1, df2, indicator=True, how='outer')
m[m._merge != 'both'].compute()
```

This throws the memory error above, same with 

```
df1 = dd.read_csv('1.csv', sep=',', header=None)
df2 = dd.read_csv('2.csv', sep=',', header=None)
m = dd.merge(df1, df2, indicator=True, how='outer')
m[m._merge != 'both'].compute()
```

Where `2.csv` only differs from `1.csv` by 1 row

**Comment by devbrian** [comment]
I also get the same memory error with this code
```
df1 = dd.read_csv('1.csv', sep=',', header=None)
df2 = dd.read_csv('1.csv', sep=',', header=None)
print(df1.head())
m = dd.merge(df1, df2, indicator=True, how='outer')
print(m.head())
```

Errors at `print(m.head())`
@TomAugspurger

**Comment by TomAugspurger** [comment]
Can you provide a script to generate the CSVs?

Do you get an out of memory error if you first set the index to the column
you're joining on?

**Comment by devbrian** [comment]
@TomAugspurger 

```
import csv
from faker import Faker
l = Faker('en_GB')
g = open("1.csv", "a", newline='')
w = csv.writer(g)
for i in range(10000000):
    w.writerow((i + 1, l.name(), l.postcode(), l.city(), l.street_name(), l.country(), l.msisdn(), l.sentence()))
```

The column `m._merge` won't exist until after the merge, and I'm not joining on any specific column since I am doing an outer join.
