### ISSUE TITLE
Argmax fails on newer dask versions.

### ISSUE THREAD

**Issue by juseg** [dask/dask#3190]
Using Python 2.7.9, Numpy 1.14.1, Dask 0.16.0:

```
$ python -c 'import dask.array as da; print da.arange(10, chunks=2).argmax().compute()'
9
```

Using Python 2.7.9, Numpy 1.14.1, Dask 0.16.1 or 0.17.0:

```
$ python -c 'import dask.array as da; print da.arange(10, chunks=2).argmax().compute()'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/scratch_net/iceberg/juliens/software/lib/python2.7/site-packages/dask/array/core.py", line 1591, in argmax
    return argmax(self, axis=axis, split_every=split_every, out=out)
  File "/scratch_net/iceberg/juliens/software/lib/python2.7/site-packages/dask/array/reductions.py", line 605, in _
    split_every=split_every, out=out)
  File "/scratch_net/iceberg/juliens/software/lib/python2.7/site-packages/dask/array/reductions.py", line 564, in arg_reduction
    name = 'arg-reduce-chunk-{0}'.format(tokenize(chunk, axis))
  File "/scratch_net/iceberg/juliens/software/lib/python2.7/site-packages/dask/base.py", line 522, in tokenize
    return md5(str(tuple(map(normalize_token, args))).encode()).hexdigest()
  File "/scratch_net/iceberg/juliens/software/lib/python2.7/site-packages/dask/utils.py", line 414, in __call__
    return meth(arg)
  File "/scratch_net/iceberg/juliens/software/lib/python2.7/site-packages/dask/base.py", line 556, in normalize_object
    return normalize_function(o) if callable(o) else uuid.uuid4().hex
  File "/scratch_net/iceberg/juliens/software/lib/python2.7/site-packages/dask/base.py", line 567, in normalize_function
    result = _normalize_function(func)
  File "/scratch_net/iceberg/juliens/software/lib/python2.7/site-packages/dask/base.py", line 589, in _normalize_function
    for k, v in sorted(func.keywords.items()))
AttributeError: 'NoneType' object has no attribute 'items'
```

Many thanks for the hard work!

**Comment by mrocklin** [comment]
Reproduced.  Thank you for the excellent bug report!
