### ISSUE TITLE
Merge on CategoricalIndex fails with KeyError

### ISSUE THREAD

**Issue by fjetter** [dask/dask#3431]
I'm trying to set up the merge of two dataframes with a `CategoricalIndex` but am getting a confusing traceback (see below). I could track down the issue to the [align_partitions](https://github.com/dask/dask/blob/196c9b0d2656fb544945018bb68ce6ebce5c0870/dask/dataframe/multi.py#L75) function and eventually to the repartition of the dataframe itself. This is where I surrendered and I'd be glad for some help.

Here is an example where the Error is raised if more than one partition is used (same can be reproduced if, e.g. `from_delayed` is used)

Disclaimer: I'm running on the pandas master

```
import dask.dataframe as dd
import pandas as pd
from dask import delayed

df = pd.DataFrame({
    'data': [1, 2, 3, 4],
    'index': ['A', 'A', 'B', 'B']
})

ddf = dd.from_pandas(df, npartitions=1).set_index('index').categorize()
res1 = ddf.merge(ddf, left_index=True, right_index=True).compute()

ddf = dd.from_pandas(df, npartitions=2).set_index('index').categorize()
res2 = ddf.merge(ddf, left_index=True, right_index=True).compute()

dd.utils.assert_eq(res1, res2)
```

Traceback

```
Traceback (most recent call last):
  File "/workspace/pandas/pandas/core/indexes/base.py", line 4174, in get_slice_bound
    return self._searchsorted_monotonic(label, side)
  File "/workspace/pandas/pandas/core/indexes/base.py", line 4124, in _searchsorted_monotonic
    return self.searchsorted(label, side=side)
  File "/workspace/pandas/pandas/util/_decorators.py", line 177, in wrapper
    return func(*args, **kwargs)
  File "/workspace/pandas/pandas/core/base.py", line 1215, in searchsorted
    return self.values.searchsorted(value, side=side, sorter=sorter)
  File "/workspace/pandas/pandas/util/_decorators.py", line 177, in wrapper
    return func(*args, **kwargs)
  File "/workspace/pandas/pandas/core/arrays/categorical.py", line 1292, in searchsorted
    raise ValueError("Categorical not ordered\nyou can use "
ValueError: Categorical not ordered
you can use .as_ordered() to change the Categorical to an ordered one

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tests/integrationtests/Untitled-1.py", line 25, in <module>
    result_delayed = ddf.merge(ddf, left_index=True, right_index=True).compute()
  File "/workspace/dask/dask/base.py", line 155, in compute
    (result,) = compute(self, traverse=False, **kwargs)
  File "/workspace/dask/dask/base.py", line 404, in compute
    results = get(dsk, keys, **kwargs)
  File "/workspace/dask/dask/threaded.py", line 75, in get
    pack_exception=pack_exception, **kwargs)
  File "/workspace/dask/dask/local.py", line 521, in get_async
    raise_exception(exc, tb)
  File "/workspace/dask/dask/compatibility.py", line 67, in reraise
    raise exc
  File "/workspace/dask/dask/local.py", line 290, in execute_task
    result = _execute_task(task, data)
  File "/workspace/dask/dask/local.py", line 271, in _execute_task
    return func(*args2)
  File "/workspace/dask/dask/dataframe/methods.py", line 81, in boundary_slice
    result = getattr(df, kind)[start:stop]
  File "/workspace/pandas/pandas/core/indexing.py", line 1375, in __getitem__
    return self._getitem_axis(maybe_callable, axis=axis)
  File "/workspace/pandas/pandas/core/indexing.py", line 1797, in _getitem_axis
    return self._get_slice_axis(key, axis=axis)
  File "/workspace/pandas/pandas/core/indexing.py", line 1408, in _get_slice_axis
    slice_obj.step, kind=self.name)
  File "/workspace/pandas/pandas/core/indexes/base.py", line 4040, in slice_indexer
    kind=kind)
  File "/workspace/pandas/pandas/core/indexes/base.py", line 4247, in slice_locs
    end_slice = self.get_slice_bound(end, 'right', kind)
  File "/workspace/pandas/pandas/core/indexes/base.py", line 4177, in get_slice_bound
    raise err
  File "/workspace/pandas/pandas/core/indexes/base.py", line 4171, in get_slice_bound
    slc = self._get_loc_only_exact_matches(label)
  File "/workspace/pandas/pandas/core/indexes/base.py", line 4140, in _get_loc_only_exact_matches
    return self.get_loc(key)
  File "/workspace/pandas/pandas/core/indexes/category.py", line 442, in get_loc
    return self._engine.get_loc(codes)
  File "pandas/_libs/index.pyx", line 139, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 156, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 176, in pandas._libs.index.IndexEngine._get_loc_duplicates
KeyError: 1
```

**Comment by groceryheist** [comment]
I had a similar problem. I tried 

    d.index = d.index.astype(CategoricalDtype(ordered=True))

before the merge. 
This seems to work, but my job is also struggling to process efficiently, and running single threaded for a long time. Not sure why.

**Comment by TomAugspurger** [comment]
Pandas raises a `ValueError` here.

```python
In [32]: df = pd.DataFrame({"a": [1, 2]}, index=pd.CategoricalIndex(['A', 'A'], ordered=True))

In [33]: df
Out[33]:
   a
A  1
A  2

In [34]: df.loc['A':'B']
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
~/sandbox/pandas/pandas/core/indexes/base.py in get_slice_bound(self, label, side, kind)
   4282             try:
-> 4283                 return self._searchsorted_monotonic(label, side)
   4284             except ValueError:

~/sandbox/pandas/pandas/core/indexes/base.py in _searchsorted_monotonic(self, label, side)
   4232         if self.is_monotonic_increasing:
-> 4233             return self.searchsorted(label, side=side)
   4234         elif self.is_monotonic_decreasing:

~/sandbox/pandas/pandas/util/_decorators.py in wrapper(*args, **kwargs)
    176                     kwargs[new_arg_name] = new_arg_value
--> 177             return func(*args, **kwargs)
    178         return wrapper

~/sandbox/pandas/pandas/core/base.py in searchsorted(self, value, side, sorter)
   1233         # needs coercion on the key (DatetimeIndex does already)
-> 1234         return self.values.searchsorted(value, side=side, sorter=sorter)
   1235

~/sandbox/pandas/pandas/util/_decorators.py in wrapper(*args, **kwargs)
    176                     kwargs[new_arg_name] = new_arg_value
--> 177             return func(*args, **kwargs)
    178         return wrapper

~/sandbox/pandas/pandas/core/arrays/categorical.py in searchsorted(self, value, side, sorter)
   1351         if -1 in values_as_codes:
-> 1352             raise ValueError("Value(s) to be inserted must be in categories.")
   1353

ValueError: Value(s) to be inserted must be in categories.

During handling of the above exception, another exception occurred:

KeyError                                  Traceback (most recent call last)
<ipython-input-34-b4269b40a24d> in <module>()
----> 1 df.loc['A':'B']

~/sandbox/pandas/pandas/core/indexing.py in __getitem__(self, key)
   1500
   1501             maybe_callable = com.apply_if_callable(key, self.obj)
-> 1502             return self._getitem_axis(maybe_callable, axis=axis)
   1503
   1504     def _is_scalar_access(self, key):

~/sandbox/pandas/pandas/core/indexing.py in _getitem_axis(self, key, axis)
   1867         if isinstance(key, slice):
   1868             self._validate_key(key, axis)
-> 1869             return self._get_slice_axis(key, axis=axis)
   1870         elif com.is_bool_indexer(key):
   1871             return self._getbool_axis(key, axis=axis)

~/sandbox/pandas/pandas/core/indexing.py in _get_slice_axis(self, slice_obj, axis)
   1533         labels = obj._get_axis(axis)
   1534         indexer = labels.slice_indexer(slice_obj.start, slice_obj.stop,
-> 1535                                        slice_obj.step, kind=self.name)
   1536
   1537         if isinstance(indexer, slice):

~/sandbox/pandas/pandas/core/indexes/base.py in slice_indexer(self, start, end, step, kind)
   4147         """
   4148         start_slice, end_slice = self.slice_locs(start, end, step=step,
-> 4149                                                  kind=kind)
   4150
   4151         # return a slice

~/sandbox/pandas/pandas/core/indexes/base.py in slice_locs(self, start, end, step, kind)
   4354         end_slice = None
   4355         if end is not None:
-> 4356             end_slice = self.get_slice_bound(end, 'right', kind)
   4357         if end_slice is None:
   4358             end_slice = len(self)

~/sandbox/pandas/pandas/core/indexes/base.py in get_slice_bound(self, label, side, kind)
   4284             except ValueError:
   4285                 # raise the original KeyError
-> 4286                 raise err
   4287
   4288         if isinstance(slc, np.ndarray):

~/sandbox/pandas/pandas/core/indexes/base.py in get_slice_bound(self, label, side, kind)
   4278         # we need to look up the label
   4279         try:
-> 4280             slc = self._get_loc_only_exact_matches(label)
   4281         except KeyError as err:
   4282             try:

~/sandbox/pandas/pandas/core/indexes/base.py in _get_loc_only_exact_matches(self, key)
   4247         get_slice_bound.
   4248         """
-> 4249         return self.get_loc(key)
   4250
   4251     def get_slice_bound(self, label, side, kind):

~/sandbox/pandas/pandas/core/indexes/category.py in get_loc(self, key, method)
    430         array([False,  True, False,  True], dtype=bool)
    431         """
--> 432         codes = self.categories.get_loc(key)
    433         if (codes == -1):
    434             raise KeyError(key)

~/sandbox/pandas/pandas/core/indexes/base.py in get_loc(self, key, method, tolerance)
   3042                 return self._engine.get_loc(key)
   3043             except KeyError:
-> 3044                 return self._engine.get_loc(self._maybe_cast_indexer(key))
   3045
   3046         indexer = self.get_indexer([key], method=method, tolerance=tolerance)

~/sandbox/pandas/pandas/_libs/index.pyx in pandas._libs.index.IndexEngine.get_loc()

~/sandbox/pandas/pandas/_libs/index.pyx in pandas._libs.index.IndexEngine.get_loc()

~/sandbox/pandas/pandas/_libs/hashtable_class_helper.pxi in pandas._libs.hashtable.PyObjectHashTable.get_item()

~/sandbox/pandas/pandas/_libs/hashtable_class_helper.pxi in pandas._libs.hashtable.PyObjectHashTable.get_item()
```

I *think* that's the correct behavior, since Categoricals can have custom ordering, so there's no way to know where `B` is in the custom ordering... (though I'm not sure about unordered categories).

Regardless, dask will probably need to work around this when slicing in `boundary_slice`.
