### ISSUE TITLE
dd.read_parquet("gc:") read data from gcs fails

### ISSUE THREAD

**Issue by anderl80** [dask/dask#3666]
I created a Kubernetes cluster on google cloud and deployed dask using helm from stable/dask chart. The Jupyter Notebook provides with the examples folder does not work as gcsfs package is not included.

So I tried to do my own way. Start a local Jupyter Notebook and connect to the dask cluster in the google cloud.

```python
import dask
from dask.distributed import Client, progress
client = Client("IP:8786")
client
```
Works perfectly.

To avoid access problems is initialize gcsfs beforehand:
```python
import gcsfs
gcs = gcsfs.GCSFileSystem(project='NAME', token=r"PATH")
```

Also works and I can `ls` the files.

Then I want to read the parquet:
```python
import dask.dataframe as dd
df = dd.read_parquet('gs://anaconda-public-data/nyc-taxi/nyc.parquet')
df = df.persist()
progress(df)
```
This fails with error:
```
Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/distributed/protocol/pickle.py", line 59, in loads
    return pickle.loads(x)
ModuleNotFoundError: No module named 'urllib3'
distributed.worker - WARNING - Could not deserialize task
Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/distributed/worker.py", line 1266, in add_task
    self.tasks[key] = _deserialize(function, args, kwargs, task)
  File "/opt/conda/lib/python3.6/site-packages/distributed/worker.py", line 644, in _deserialize
    args = pickle.loads(args)
  File "/opt/conda/lib/python3.6/site-packages/distributed/protocol/pickle.py", line 59, in loads
    return pickle.loads(x)
ModuleNotFoundError: No module named 'urllib3'
```
However `urllib3` should be installed. In order to read the parquet and provide snappy I had to edit a `config.yaml` as following:

```yaml
# config.yaml
scheduler:
  replicas: 1
  env:
    - name: EXTRA_CONDA_PACKAGES
      value: numba xarray fastparquet pyarrow snappy python-snappy gcsfs s3fs dask-ml urllib3 -c conda-forge
    - name: EXTRA_PIP_PACKAGES
      value: urllib3
worker:
  replicas: 8
  resources:
    limits:
      cpu: 2
      memory: 7.5G
    requests:
      cpu: 2
      memory: 7.5G
  env:
    - name: EXTRA_CONDA_PACKAGES
      value: numba xarray pyarrow fastparquet snappy python-snappy gcsfs s3fs dask-ml urllib3 -c conda-forge
    - name: EXTRA_PIP_PACKAGES
      value: urllib3 # dask-ml --upgrade
# We want to keep the same packages on the worker and jupyter environments
jupyter:
  enabled: true
  env:
    - name: EXTRA_CONDA_PACKAGES
      value: numba xarray pyarrow fastparquet snappy python-snappy gcsfs s3fs dask-ml urllib3 matplotlib -c conda-forge
    - name: EXTRA_PIP_PACKAGES
      value: urllib3 # dask-ml --upgrade
```

**Comment by anderl80** [comment]
Moved to https://github.com/dask/dask-kubernetes/issues/80
