### ISSUE TITLE
feature request? allow da.concatenate/da.block to have more flexibility with unknown chunck sizes

### ISSUE THREAD

**Issue by hmaarrfk** [dask/dask#3711]
I'm trying to concatenate arrays along multiple dimensions with non uniform chunk sizes.
Once the arrays are concatenated along the first dimension, then they have the correct shape to allow dask to concatenate them along the next dimension as described in the [`da.block` documentation](http://dask.pydata.org/en/latest/array-api.html#dask.array.block).
 
If I specify the shape of all arrays, `da.concatenate` or `da.block` has no issue concatenating them:

```python
import numpy as np
import dask.array as da
from dask import delayed

arrays = np.zeros((2, 2), dtype=object)

arrays[0, 0] = da.array(np.ones((1, 1)).T)
arrays[1, 0] = da.array(np.ones((1, 2)).T * 2)
arrays[0, 1] = da.array(np.ones((1, 2)).T * 3)
arrays[1, 1] = da.array(np.ones((1, 1)).T * 4)
# %%
# shapes do not align in this dimension, so we can't use block
# block_array = da.block(arrays.tolist())
# block_array.visualize()
# also, I might have multidimentional arrays that I want to specify which axis
# to concatenate on
# %%
# this is my definition
def custom_block(the_blocks, allow_unknown_chunksizes=False):
    vertical_stacks = np.zeros(the_blocks.shape[1], dtype=object)
    for i in range(the_blocks.shape[1]):
        vertical_stacks[i] = da.concatenate(the_blocks[:, i], axis=0, allow_unknown_chunksizes=allow_unknown_chunksizes)
    final_array = da.concatenate(vertical_stacks, axis=1, allow_unknown_chunksizes=allow_unknown_chunksizes)
    return final_array

final_array = custom_block(arrays)
print(final_array.compute())
```

```python
[[1. 3.]
 [2. 3.]
 [2. 4.]]
```

Now, if we specify the arrays as coming from delayed values, with `np.nan` as their shape:
```
delayed_arrays = np.zeros((2, 2), dtype=object)

delayed_arrays[0, 0] = da.from_delayed(delayed(np.ones((1, 1)).T),
                                       shape=(np.nan, np.nan), dtype=np.float)
delayed_arrays[1, 0] = da.from_delayed(delayed(np.ones((1, 2)).T * 2),
                                       shape=(np.nan, np.nan), dtype=np.float)
delayed_arrays[0, 1] = da.from_delayed(delayed(np.ones((1, 2)).T * 3),
                                       shape=(np.nan, np.nan), dtype=np.float)
delayed_arrays[1, 1] = da.from_delayed(delayed(np.ones((1, 1)).T * 4),
                                       shape=(np.nan, np.nan), dtype=np.float)
# %%
# now try to call the same functions

final_array = custom_block(delayed_arrays, allow_unknown_chunksizes=True)

print(final_array.compute())
```

It fails to concatenate them. I guess that is because it tries to enforce the picture of the dask array shown [here](https://dask.pydata.org/en/latest/array.html#design)

traceback
```python
Traceback (most recent call last):

  File "<ipython-input-40-55fab3b4e076>", line 3, in <module>
    print(final_array.compute())

  File "/home/mark/miniconda3/envs/owl/lib/python3.6/site-packages/dask/base.py", line 156, in compute
    (result,) = compute(self, traverse=False, **kwargs)

  File "/home/mark/miniconda3/envs/owl/lib/python3.6/site-packages/dask/base.py", line 403, in compute
    return repack([f(r, *a) for r, (f, a) in zip(results, postcomputes)])

  File "/home/mark/miniconda3/envs/owl/lib/python3.6/site-packages/dask/base.py", line 403, in <listcomp>
    return repack([f(r, *a) for r, (f, a) in zip(results, postcomputes)])

  File "/home/mark/miniconda3/envs/owl/lib/python3.6/site-packages/dask/array/core.py", line 999, in finalize
    return concatenate3(results)

  File "/home/mark/miniconda3/envs/owl/lib/python3.6/site-packages/dask/array/core.py", line 3727, in concatenate3
    result[idx] = arr

ValueError: could not broadcast input array from shape (2,1) into shape (1,1)
```

Note that the transpose isn't necessary to show this behaviour, I just wanted to share my usecase. Here is the same bug without the transpose

Using block:
```python
import numpy as np
import dask.array as da
from dask import delayed

arrays = np.zeros((2, 2), dtype=object)

arrays[0, 0] = da.array(np.ones((1, 1)))
arrays[1, 0] = da.array(np.ones((1, 2)) * 2)
arrays[0, 1] = da.array(np.ones((1, 2)) * 3)
arrays[1, 1] = da.array(np.ones((1, 1)) * 4)
print(da.block(arrays.tolist()).compute())

# %%
from dask import delayed
delayed_arrays = np.zeros((2, 2), dtype=object)

delayed_arrays[0, 0] = da.from_delayed(delayed(np.ones((1, 1))),
                                       shape=(np.nan, np.nan), dtype=np.float)
delayed_arrays[1, 0] = da.from_delayed(delayed(np.ones((1, 2)) * 2),
                                       shape=(np.nan, np.nan), dtype=np.float)
delayed_arrays[0, 1] = da.from_delayed(delayed(np.ones((1, 2)) * 3),
                                       shape=(np.nan, np.nan), dtype=np.float)
delayed_arrays[1, 1] = da.from_delayed(delayed(np.ones((1, 1)) * 4),
                                       shape=(np.nan, np.nan), dtype=np.float)
# %%
# now try to call the same functions

print(da.block(delayed_arrays.tolist(), allow_unknown_chunksizes=True).compute())
```

expected output:
```python
[[1. 3. 3.]
 [2. 2. 4.]]
```
actual output
```python
Traceback (most recent call last):

  File "<ipython-input-46-4a66aab92527>", line 1, in <module>
    print(da.block(delayed_arrays.tolist(), allow_unknown_chunksizes=True).compute())

  File "/home/mark/miniconda3/envs/owl/lib/python3.6/site-packages/dask/base.py", line 156, in compute
    (result,) = compute(self, traverse=False, **kwargs)

  File "/home/mark/miniconda3/envs/owl/lib/python3.6/site-packages/dask/base.py", line 403, in compute
    return repack([f(r, *a) for r, (f, a) in zip(results, postcomputes)])

  File "/home/mark/miniconda3/envs/owl/lib/python3.6/site-packages/dask/base.py", line 403, in <listcomp>
    return repack([f(r, *a) for r, (f, a) in zip(results, postcomputes)])

  File "/home/mark/miniconda3/envs/owl/lib/python3.6/site-packages/dask/array/core.py", line 999, in finalize
    return concatenate3(results)

  File "/home/mark/miniconda3/envs/owl/lib/python3.6/site-packages/dask/array/core.py", line 3727, in concatenate3
    result[idx] = arr

ValueError: could not broadcast input array from shape (2,1) into shape (1,1)
```

dask: 0.18.1
Linux 64 bit, miniconda env

**Comment by hmaarrfk** [comment]
nevermind. it seems that I didn't fully read all the features of block.

**Comment by hmaarrfk** [comment]
I guess I've found a workaround for my particular task. That said, the ability to use `da.block` or `da.concatenate` in the special case listed would be really useful.

My particular application allowed me to equalize the block lengths vertically and horizontally so that they match that image on the dask.array website.

`da.block` and `da.concatenate` are really nice as they keep the datapaths separate, and potentially disjoint for a little longer depending on your application.
