### ISSUE TITLE
Bag groupby error using tasks based shuffle

### ISSUE THREAD

**Issue by mohtar** [dask/dask#3748]
Looks like the issue is when the bag in question has only 1 partition.

```
>>> dask.bag.from_sequence('abc', npartitions = 1).groupby(lambda x: x, shuffle = 'tasks').compute()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/dist-packages/dask/bag/core.py", line 1240, in groupby
    return groupby_tasks(self, grouper, max_branch=max_branch)
  File "/usr/local/lib/python3.6/dist-packages/dask/bag/core.py", line 2012, in groupby_tasks
    for i, j in enumerate(join))
UnboundLocalError: local variable 'join' referenced before assignment
```

Dask version 0.18.1

**Comment by jrbourbeau** [comment]
Thanks @mohtar for the opening up this issue! I was able to reproduce this error on the current `master` branch. Do you have an interest in opening up a PR?
