### ISSUE TITLE
Scheduler stuck, client reports error: "Address family not supported by protocol"

### ISSUE THREAD

**Issue by rainwoodman** [dask/dask#3750]
I am trying to run: scaling-gcs.ipynb ( http://matthewrocklin.com/blog/work/2017/07/03/scaling ) on a  moderate sized HPC converted dask cluster:

```
Workers: 256   Cores: 1024   Memory: 491.52 GB
```
I encounter a strange error at the benchmark cell, in the first iteration with tasks:

```
%%time
for i in range(3):
    for func in [tasks, arrays, dataframes]:
        print(i, func.__name__)
        df = run(func, client=client)
        L.append(df)
```

Here is an error message reported in the notebook (in pink):
```
tornado.application - ERROR - Exception in callback functools.partial(<function wrap.<locals>.null_wrapper at 0x2aab783ce268>)
Traceback (most recent call last):
  File "/global/homes/y/yfeng1/.conda/envs/bccp/lib/python3.6/site-packages/tornado/ioloop.py", line 759, in _run_callback
    ret = callback()
  File "/global/homes/y/yfeng1/.conda/envs/bccp/lib/python3.6/site-packages/tornado/stack_context.py", line 276, in null_wrapper
    return fn(*args, **kwargs)
  File "/global/homes/y/yfeng1/.conda/envs/bccp/lib/python3.6/site-packages/tornado/tcpclient.py", line 142, in on_timeout
    self.try_connect(iter(self.secondary_addrs))
  File "/global/homes/y/yfeng1/.conda/envs/bccp/lib/python3.6/site-packages/tornado/tcpclient.py", line 104, in try_connect
    stream, future = self.connect(af, addr)
  File "/global/homes/y/yfeng1/.conda/envs/bccp/lib/python3.6/site-packages/tornado/tcpclient.py", line 258, in _create_stream
    socket_obj = socket.socket(af)
  File "/global/homes/y/yfeng1/.conda/envs/bccp/lib/python3.6/socket.py", line 144, in __init__
    _socket.socket.__init__(self, family, type, proto, fileno)
OSError: [Errno 97] Address family not supported by protocol
```

Same time, I see warnings from `distributed.core`, on the console where the cluster is launched (likely from the scheduler):

```
istributed.core - INFO - Event loop was unresponsive in Scheduler for 125.99s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
```

top shows the scheduler is using 100% CPU (ZMQbg/1 is likely the notebook kernel)

```
KiB Mem:  98843424 total, 18851908 used, 79991520 free,     7464 buffers
KiB Swap:        0 total,        0 used,        0 free.  3254852 cached Mem

   PID USER      PR  NI    VIRT    RES    SHR S    %CPU  %MEM     TIME+ COMMAND
 91835 yfeng1    20   0 34.419g 1.075g  23036 S 114.110 1.141   5:08.56 ZMQbg/1
 91194 yfeng1    20   0 34.771g 1.288g  21304 R 100.000 1.366   9:30.52 dask-scheduler
 91236 root      20   0  347152   8664   6952 S  27.301 0.009   1:36.46 slurmstepd
 94379 yfeng1    20   0   36428   5348   2508 R   7.669 0.005   0:37.38 top
 93736 yfeng1    20   0 1094972  80200  10500 S   6.748 0.081   0:45.27 python
 93752 yfeng1    20   0 1094972  80188  10488 S   6.748 0.081   0:43.26 python
 93761 yfeng1    20   0 1094972  80180  10504 S   6.748 0.081   0:43.23 python
 93781 yfeng1    20   0 1094972  80192  10504 S   6.748 0.081   0:44.21 python
```

It has been stuck for about 10 mins. Is this expected?

**Comment by rainwoodman** [comment]
Another error message from the console is:
```
distributed.batched - ERROR - Error in batched write
Traceback (most recent call last):
  File "/global/homes/y/yfeng1/.conda/envs/bccp/lib/python3.6/site-packages/distributed/batched.py", line 94, in _background_send
    on_error='raise')
  File "/global/homes/y/yfeng1/.conda/envs/bccp/lib/python3.6/site-packages/tornado/gen.py", line 1099, in run
    value = future.result()
  File "/global/homes/y/yfeng1/.conda/envs/bccp/lib/python3.6/site-packages/tornado/gen.py", line 1107, in run
    yielded = self.gen.throw(*exc_info)
  File "/global/homes/y/yfeng1/.conda/envs/bccp/lib/python3.6/site-packages/distributed/comm/tcp.py", line 219, in write
    on_error=on_error)
  File "/global/homes/y/yfeng1/.conda/envs/bccp/lib/python3.6/site-packages/tornado/gen.py", line 1099, in run
    value = future.result()
  File "/global/homes/y/yfeng1/.conda/envs/bccp/lib/python3.6/site-packages/tornado/gen.py", line 315, in wrapper
    yielded = next(result)
  File "/global/homes/y/yfeng1/.conda/envs/bccp/lib/python3.6/site-packages/distributed/comm/utils.py", line 47, in to_frames
    res = yield offload(_to_frames)
  File "/global/homes/y/yfeng1/.conda/envs/bccp/lib/python3.6/site-packages/distributed/comm/utils.py", line 28, in offload
    return _offload_executor.submit(fn, *args, **kwargs)
  File "/global/homes/y/yfeng1/.conda/envs/bccp/lib/python3.6/concurrent/futures/thread.py", line 123, in submit
    self._adjust_thread_count()
  File "/global/homes/y/yfeng1/.conda/envs/bccp/lib/python3.6/concurrent/futures/thread.py", line 142, in _adjust_thread_count
    t.start()
  File "/global/homes/y/yfeng1/.conda/envs/bccp/lib/python3.6/threading.py", line 846, in start
    _start_new_thread(self._bootstrap, ())
RuntimeError: can't start new thread
```

The total number of threads that are allowed to be launched on the node is limited. I can work with the admin to find if there is a way to get over this. Meanwhile, is there a way to throttle the number of threads launched by the dask scheduler?

**Comment by mrocklin** [comment]
I recommend stating how you're trying to deploy dask on your cluster.  I also recommend trying a simpler computation first to see if things break.

The dask scheduler doesn't really spawn many threads that I know of.  The offload code that is in that traceback is in a ThreadPoolExecutor of size one.

**Comment by rainwoodman** [comment]
The cluster is a Cray XC40, with SLURM. The login node does not see the computing nodes via TCP/IP.

I am currently running a script from a interactive job (salloc), with 4 KNL nodes. I was able to run a simple job that calculates the mean of 70billion 3-vectors from disk in 4 mins, with 32 workers and each allowing 8 threads.

Here is the script I run after activating the conda environment to set up the cluster.
I have followed the instruction to disable spilling with .config/dask/distributed.yaml.

```
SCHEFILE=$CSCRATCH/${SLURM_JOB_ID}.dasksche.json
WORKSPACE=$CSCRATCH/${SLURM_JOB_ID}/dask-local
NPERNODE=64
NTHREADS=4

MEM=$((120 * 1024 / $NPERNODE))MB
NWORKER=$(($SLURM_NNODES * $NPERNODE))

trap "trap - SIGTERM && kill -- -$$" SIGINT SIGTERM EXIT

mkdir -p $WORKSPACE

export OMP_NUM_THREADS=1

export LC_ALL=C.UTF-8
export LANG=C.UTF-8

rm -rf $SCHEFILE
rm -rf $WORKSPACE

ssh -f -N \
-R1080:localhost:1080 \
my-office-computer.berkeley.edu


# 8785 : jupyter
# 8787 : brokeh
# 8786 : scheduler

pip install pproxy

pproxy -i http+socks://:1080/ &

XDG_RUNTIME_DIR=$HOME/.run jupyter-notebook --no-browser --ip 0.0.0.0 --port=8785 &

dask-scheduler --scheduler-file=$SCHEFILE --local-directory=$WORKSPACE &

while ! [ -f $SCHEFILE ]; do
    sleep 1
done

set -x 

srun -n $NWORKER \
    --output=$WORKSPACE/worker-%t.stdout \
    --error=$WORKSPACE/worker-%t.stderr \
    python `which dask-worker`  \
    --nthreads $NTHREADS \
    --memory-limit $MEM \
    --scheduler-file=${SCHEFILE} \
    --local-directory=${WORKSPACE} &

    #--no-bokeh \
wait
```

You said dask scheduler doesn't spawn many threads. Is it possible that the number of simultaneous background_send increase with the number of workers linearly?

**Comment by rainwoodman** [comment]
dask-jobqueue puts the scheduler on the job submission node. I think running scheduler there could alleviate the "can't start new thread" issue. The address family issue may also go away since the scheduler is no longer competing with workers on the resources. I will give it a go. Thanks!

**Comment by quasiben** [comment]
@rainwoodman this was submitted some time ago.  Any updates on your experiments with `dask-jobqueue`?

**Comment by TomAugspurger** [comment]
@rainwoodman let us know if this is a still an issue and we'll reopen.
