### ISSUE TITLE
Multinomial bug

### ISSUE THREAD

**Issue by dezmondgoff** [dask/dask#3929]
I'm using python 3.7, numpy 1.16.0.dev0+591880b built with mkl, and dask 0.19.0.

```
import dask
import dask.array as da 
import numpy as np

N = 10
dp = da.random.random(3, chunks=1)
dp = dp / dp.sum()
dx = da.random.multinomial(1, dp, N, chunks=2)
```

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.7/site-packages/dask/array/random.py", line 295, in multinomial
    extra_chunks=((len(pvals),),))
  File "/usr/lib/python3.7/site-packages/dask/array/random.py", line 73, in _wrap
    size = broadcast_shapes(*shapes)
  File "/usr/lib/python3.7/site-packages/dask/array/core.py", line 3428, in broadcast_shapes
    "shapes {0}".format(' '.join(map(str, shapes))))
ValueError: operands could not be broadcast together with shapes (3,) (10,)
```

The numpy code excutes as expected.
```
p = dp.compute() 
x = np.random.multinomial(1, p, N)
```
Feeding in `p` instead of `dp` causes the same error.

**Comment by TAdeJong** [comment]
[`da.random._wrap()`](https://github.com/dask/dask/blob/5eae4f08a2d01e0ab6a5026c2c5400ab202e44ba/dask/array/random.py#L52), fundamentally handles `list`'s differently from `np.ndarray`'s and Dask arrays, trying to broadcast array shapes, but ignoring lists for that, instead relying on the `extra_chunks` argument to extend.
As such even the following trips:
```
dx = da.random.multinomial(1, np.array([1/6.]*6), 10, chunks=2)
```
while this works:
```
dx = da.random.multinomial(1, [1/6.]*6, 10, chunks=2)
```
I feel like there should be a nice way to solve this, but the best quick fix I can come up with is to always cast `pvals` to a list, which seems very undesirable.
But I have a feeling this broadcasting problem where we add a dimension is not a unique problem and there should already be a solution floating around somewhere in the codebase...

**Comment by dlovell** [comment]
@TAdeJong , why does casting `pvals` to a list seem undesirable?

**Comment by TAdeJong** [comment]
> @TAdeJong , why does casting `pvals` to a list seem undesirable?

Because in general this might be a rather large array. Furthermore, in the case of a dask array, it might cause all kind of intermediate computation when calling the function instead of when calling `.compute()`, which is undesirable.

**Comment by dlovell** [comment]
It seems like the` pvals` need to be concrete inside of `_wrap` for use in `_apply_random` to generate `meta` and `vals`

```
shape = (2, 2)
v = [.5, .5]
p = dask.delayed(toolz.identity)(v)
# works
np.random.geometric(v, shape)
# ValueError: shape mismatch: objects cannot be broadcast to a single shape
da.random.geometric(v, shape)
# ValueError: setting an array element with a sequence.
np.random.geometric(p, shape)
# ValueError: setting an array element with a sequence.
da.random.geometric(p, shape)
```

**Comment by dlovell** [comment]
I'm looking to see if `p` is always the first argument to all the functions, in which case maybe it can be excluded from the `args_shapes` collection.
