### ISSUE TITLE
Crash when combining type annotations for delayed functions with multiprocessing

### ISSUE THREAD

**Issue by joshburkart** [dask/dask#3971]
Example problematic code snippet:

```python
import typing

import dask

@dask.delayed
def blah() -> typing.List[int]:
    return [5]

blah().compute(scheduler='processes')
```

This results in a crash; traceback below. Instead running with `scheduler='threads'` works fine. Removing the `-> typing.List[int]` works fine with `scheduler='processes'`. Works fine regardless on Mac (Python 3.6.4 and 3.6.6). Weird!

Crash traceback (Python 3.6.5, Ubuntu 18.04):

```
TypeError                                 Traceback (most recent call last)
<ipython-input-1-fc913fc1b7b2> in <module>()
      7     return [7]
      8
----> 9 blah().compute(scheduler='processes')

~/.local/lib/python3.6/site-packages/dask/base.py in compute(self, **kwargs)
    154         dask.base.compute
    155         """
--> 156         (result,) = compute(self, traverse=False, **kwargs)
    157         return result
    158

~/.local/lib/python3.6/site-packages/dask/base.py in compute(*args, **kwargs)
    393     keys = [x.__dask_keys__() for x in collections]
    394     postcomputes = [x.__dask_postcompute__() for x in collections]
--> 395     results = schedule(dsk, keys, **kwargs)
    396     return repack([f(r, *a) for r, (f, a) in zip(results, postcomputes)])
    397

~/.local/lib/python3.6/site-packages/dask/multiprocessing.py in get(dsk, keys, num_workers, func_loads, func_dumps, optimize_graph, **kwargs)
    170                            get_id=_process_get_id, dumps=dumps, loads=loads,
    171                            pack_exception=pack_exception,
--> 172                            raise_exception=reraise, **kwargs)
    173     finally:
    174         if cleanup:

~/.local/lib/python3.6/site-packages/dask/local.py in get_async(apply_async, num_workers, dsk, result, cache, get_id, rerun_exceptions_locally, pack_exception, raise_exception, callbacks, dumps, loads, **kwargs)
    499                         _execute_task(task, data)  # Re-execute locally
    500                     else:
--> 501                         raise_exception(exc, tb)
    502                 res, worker_id = loads(res_info)
    503                 state['cache'][key] = res

~/.local/lib/python3.6/site-packages/dask/compatibility.py in reraise(exc, tb)
    109     def reraise(exc, tb=None):
    110         if exc.__traceback__ is not tb:
--> 111             raise exc.with_traceback(tb)
    112         raise exc
    113

~/.local/lib/python3.6/site-packages/dask/local.py in execute_task()
    269     """
    270     try:
--> 271         task, data = loads(task_info)
    272         result = _execute_task(task, data)
    273         id = get_id()

/usr/lib/python3.6/typing.py in __new__()
    946             for base in bases:
    947                 if base is Generic:
--> 948                     raise TypeError("Cannot inherit from plain Generic")
    949                 if (isinstance(base, GenericMeta) and
    950                         base.__origin__ is Generic):

TypeError: Cannot inherit from plain Generic
```

In the same scenario, I also sometimes (not sure under what conditions...) get the following traceback instead:

```
  File "/tmp/tmpnlkkwnt3_pyzip/dask/base.py", line 156, in compute
    (result,) = compute(self, traverse=False, **kwargs)
  File "/tmp/tmpnlkkwnt3_pyzip/dask/base.py", line 395, in compute
    results = schedule(dsk, keys, **kwargs)
  File "/tmp/tmpnlkkwnt3_pyzip/dask/multiprocessing.py", line 172, in get
    raise_exception=reraise, **kwargs)
  File "/tmp/tmpnlkkwnt3_pyzip/dask/local.py", line 501, in get_async
    raise_exception(exc, tb)
  File "/tmp/tmpnlkkwnt3_pyzip/dask/compatibility.py", line 111, in reraise
    raise exc.with_traceback(tb)
  File "/tmp/tmpnlkkwnt3_pyzip/dask/local.py", line 271, in execute_task
    task, data = loads(task_info)
AttributeError: type object 'weakref' has no attribute '__callback__'
```

**Comment by mrocklin** [comment]
I can reproduce this with only cloudpickle as follows:

```python
import typing
def blah() -> typing.List[int]:
    return [5]
import cloudpickle
cloudpickle.loads(cloudpickle.dumps(blah))
```

I encourage you to raise this upstream at https://github.com/cloudpipe/cloudpickle/issues/new

**Comment by joshburkart** [comment]
Ah, I tried reproducing it with normal pickle and didn't see an error. Was unaware of cloudpickle. Will do, thanks.

**Comment by mrocklin** [comment]
Thanks for the minimal reproducible example by the way.  I'm going to close this for now.  Please speak up if something else comes up.

**Comment by joshburkart** [comment]
https://github.com/cloudpipe/cloudpickle/issues/200
