### ISSUE TITLE
Inconsistent behaviour when calculating sizeof GeoDataFrame and GeoSeries

### ISSUE THREAD

**Issue by avnovikov** [dask/dask#3976]
As found in discussion in 
https://github.com/dask/dask/issues/3972#issuecomment-420384065 and probably the root cause of https://github.com/dask/dask/issues/3972

```
AttributeError: 'GeometryArray' object has no attribute 'nbytes'
distributed.sizeof - WARNING - Sizeof calculation failed.  Defaulting to 1MB
Traceback (most recent call last):
  File "/anaconda3/envs/mariquant/lib/python3.6/site-packages/distributed/sizeof.py", line 16, in safe_sizeof
    return sizeof(obj)
  File "/anaconda3/envs/mariquant/lib/python3.6/site-packages/dask/utils.py", line 415, in __call__
    return meth(arg)
  File "/anaconda3/envs/mariquant/lib/python3.6/site-packages/dask/sizeof.py", line 63, in sizeof_pandas_series
    p = int(s.memory_usage(index=True))
  File "/anaconda3/envs/mariquant/lib/python3.6/site-packages/pandas/core/series.py", line 3503, in memory_usage
    v = super(Series, self).memory_usage(deep=deep)
  File "/anaconda3/envs/mariquant/lib/python3.6/site-packages/pandas/core/base.py", line 1143, in memory_usage
    v = self.values.nbytes
```

However GeoDataFrame size seems to be calculated correctly. Looking at the code of distributed/sizeof.py the only suspicious line is `p = int(s.memory_usage(index=True))`, however

```
type(anchorage_buffer)
Out[55]:
geopandas.geoseries.GeoSeries
In [57]:
anchorage_buffer.memory_usage(index=True)
I am densified (external_values, 20353 elements)
I am densified (external_values, 20353 elements)
Out[57]:
325648
```
Unfortunately I can't trace the origin of this error.

**Comment by jorisvandenbossche** [comment]
I can reproduce this, but I am also a bit lost about the cause at this moment (meaning: we can add a `nbytes` to GeometryArray which will solve this, but it should still not end up there). 

So when calling `client.scatter(buffer)` I get the same warning, but when doing `distributed.safe_sizeof(buffer)` (which is what is getting called according to the traceback), it works fine.

**Comment by avnovikov** [comment]
@TomAugspurger can you please comment on this.

**Comment by mrocklin** [comment]
Any update on this?  It appears to have gone quiet.
