### ISSUE TITLE
AttributeError: 'Client' object has no attribute 'status'

### ISSUE THREAD

**Issue by asifali22** [dask/dask#3995]
I have been trying to run a grid on my code but keep getting the following error:
```
Traceback (most recent call last):
  File "diya_libs/new_main.py", line 115, in <module>
    grid.fit(X, y)
  File "/anaconda3/lib/python3.6/site-packages/dask_ml/model_selection/_search.py", line 835, in fit
    multimetric=multimetric
  File "/anaconda3/lib/python3.6/site-packages/dask_ml/model_selection/_search.py", line 156, in build_graph
    dsk[best_estimator] = (fit_best, clone(estimator), best_params,
  File "/anaconda3/lib/python3.6/site-packages/sklearn/base.py", line 62, in clone
    new_object_params[name] = clone(param, safe=False)
  File "/anaconda3/lib/python3.6/site-packages/sklearn/base.py", line 50, in clone
    return estimator_type([clone(e, safe=safe) for e in estimator])
  File "/anaconda3/lib/python3.6/site-packages/sklearn/base.py", line 50, in <listcomp>
    return estimator_type([clone(e, safe=safe) for e in estimator])
  File "/anaconda3/lib/python3.6/site-packages/sklearn/base.py", line 50, in clone
    return estimator_type([clone(e, safe=safe) for e in estimator])
  File "/anaconda3/lib/python3.6/site-packages/sklearn/base.py", line 50, in <listcomp>
    return estimator_type([clone(e, safe=safe) for e in estimator])
  File "/anaconda3/lib/python3.6/site-packages/sklearn/base.py", line 62, in clone
    new_object_params[name] = clone(param, safe=False)
  File "/anaconda3/lib/python3.6/site-packages/sklearn/base.py", line 53, in clone
    return copy.deepcopy(estimator)
  File "/anaconda3/lib/python3.6/copy.py", line 180, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/anaconda3/lib/python3.6/copy.py", line 280, in _reconstruct
    state = deepcopy(state, memo)
  File "/anaconda3/lib/python3.6/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/anaconda3/lib/python3.6/copy.py", line 240, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/anaconda3/lib/python3.6/copy.py", line 169, in deepcopy
    rv = reductor(4)
TypeError: can't pickle _thread.lock objects
Exception ignored in: <object repr() failed>
Traceback (most recent call last):
  File "/anaconda3/lib/python3.6/site-packages/distributed/client.py", line 824, in __del__
  File "/anaconda3/lib/python3.6/site-packages/distributed/client.py", line 997, in close
AttributeError: 'Client' object has no attribute 'status'
```

Here's the code
```
# Some imports
.
.
from sklearn.pipeline import Pipeline
from dask_ml.model_selection import GridSearchCV

from dask_ml.datasets import make_classification
from dask_ml.model_selection import train_test_split

from dask.distributed import Client

from sklearn.externals.joblib import parallel_backend
import dask_ml.joblib
import dask.dataframe as dd

from sklearn.metrics import confusion_matrix as cm

# client = Client('127.0.0.1:8786')

X, y = make_classification(
    n_samples=10000, chunks=10000, n_classes=2, random_state=0)

X = dd.from_array(X)
y = dd.from_array(y)


X_test, y_test = make_classification(
    n_samples=1000, chunks=100, n_classes=2, random_state=0)


pipe = Pipeline([
    ('info', Diya_Info(client='127.0.0.1:8786')),
    ('fed_lr', Diya_FeatureEngineeringDependent_LogisticRegression(
        client='127.0.0.1:8786')),
    ('lr', Diya_LogisticRegression(client='127.0.0.1:8786'))
])

# pipe.fit(X, y)
# y_pred = pipe.predict(X_test)

# print(cm(y_test.compute(), y_pred.compute()))


params = {
    "fed_lr__C": [
        10.0,
        1.0,
        0.1,
        0.09,
        0.06,
        0.03,
        0.001,
        0.0009,
        0.0006,
        0.0003,
        0.0001
    ],
    "fed_lr__threshold": [
        1e-05,
        0.0001,
        0.001,
        0.01,
        0.1,
        1,
        1e-06,
        1e-09
    ],
    "lr__C": [
        1,
        10,
        100,
        1000
    ],
    "lr__threshold": [
        0.1,
        0.2,
        0.3,
        0.4,
        0.5,
        0.6,
        0.7,
        0.8,
        0.9
    ],
    "lr__penalty": [
        "l1",
        "l2"
    ]
}
grid = GridSearchCV(
    pipe, param_grid=params, cv=3, scoring='accuracy')

grid.fit(X, y)


```
If I run the pipeline alone. It works, but with `grid.fit(X, y)` fails. What could be the cause for the `lock`? Also, I have not specified `status` anywhere in my classes (inside pipeline). Why am I getting no attribute error.
@TomAugspurger  @mrocklin  Any suggestions please.

**Comment by TomAugspurger** [comment]
`TypeError: can't pickle _thread.lock objects` could be the culprit. How are you loading your data in the original failing case?

> If I run the pipeline alone. It works, but with grid.fit(X, y) fails.

I don't understand that. Could you make a copy-pasteable example that fails for you locally (i.e. doesn't have any 3rd party estimators like `Diya_Info`?

**Comment by asifali22** [comment]
Those 3rd party estimators are nothing but wrappers on `sklearn estimators`. Please find the code for `Diya_Info.py` below:

> `Diya_Info` is responsible for some basic checks on the data

```
from sklearn.base import TransformerMixin, BaseEstimator
from dask.multiprocessing import get
from dask import delayed, compute
from dask_ml.preprocessing import DummyEncoder
from dask_ml.preprocessing import Categorizer
from multiprocessing import cpu_count
from dask import dataframe as dd
from dask.distributed import Client

import time


class Diya_Info(BaseEstimator, TransformerMixin):
    def __init__(self, client, one_hot_encode=False, categorical_cols=None):

        assert client is not None, 'client can\'t be None'
        # assert type(
        #     client).__name__ == 'String', 'client not of type Client from dask.distributed'

        self.client = Client(client)
        self.one_hot_encode = one_hot_encode
        self.categorical_cols = categorical_cols
        self.X_length = None
        self.y_length = None
        if self.one_hot_encode is True:
            self.dummy_encoder = None
            self.categorizer = None

    def fit(self, X, y):
        assert X is not None, 'X can\'t be None'
        assert type(X).__name__ == 'DataFrame', 'X not of type DataFrame'
        assert y is not None, 'y can\'t be None'
        assert type(y).__name__ == 'Series', 'y not of type Series'

        self.X = X
        self.y = y

        def has_null(df): return df.isnull().values.any()

        def get_len(df): return len(df)

        X_status = self.client.submit(has_null, self.X)
        y_status = self.client.submit(has_null, self.y)
        X_len = self.client.submit(get_len, self.X)
        y_len = self.client.submit(get_len, self.y)

        # for delayed
        # X_status = self.has_null(self.X)
        # y_status = self.has_null(self.y)
        # X_len = self.get_len(self.X)
        # y_len = self.get_len(self.y)

        # For delayed
        # X_null, y_null, X_length, y_length = compute(
        #     X_status, y_status, X_len, y_len)

        X_null, y_null, X_length, y_length = self.client.gather(
            [X_status, y_status, X_len, y_len])

        self.X_length = X_length
        self.y_length = y_length

        assert X_null == False, 'X contains some columns with null/NaN values'
        assert y_null == False, 'y contains some columns with null/NaN values'
        assert X_length == y_length, 'Shape mismatch, X and y are of different length'

        if self.one_hot_encode:
            assert self.categorical_cols is not None, 'categorical_cols can\'t be None when one_hot_encode is True'

            self.categorizer = Categorizer(columns=self.categorical_cols)
            submitted_task_fit = self.client.submit(
                self.categorizer.fit, self.X
            )

            self.categorizer = self.client.gather(submitted_task_fit)

            submitted_task_transform = self.client.submit(
                self.categorizer.transform, self.X)

            self.X = self.client.gather(submitted_task_transform)

            self.dummy_encoder = DummyEncoder(
                columns=self.categorical_cols, drop_first=True)
            submitted_task_fit = self.client.submit(
                self.dummy_encoder.fit, self.X)
            self.dummy_encoder = self.client.gather(submitted_task_fit)

            submitted_task_transform = self.client.submit(
                self.dummy_encoder.transform, self.X
            )

            self.X = self.client.gather(submitted_task_transform)

        return self

    def transform(self, X):
        if self.one_hot_encode is True:

            submitted_task_transform = self.client.submit(
                self.categorizer.transform, X
            )
            X = self.client.gather(submitted_task_transform)
            submitted_task_transform = self.client.submit(
                self.dummy_encoder.transform, X
            )
            X = self.client.gather(submitted_task_transform)
        return X

    # for delayed
    # @staticmethod
    # @delayed
    # def has_null(df): return df.isnull().values.any()

    # @staticmethod
    # @delayed
    # def get_len(df): return len(df)

```
I have loaded the data using `make_classification` module from dask and also converted it to `dask dataframe` to compliant it with the 3rd party libs I'm writing.

Perhaps, above code again relates to another issue I mentioned [here](https://github.com/dask/dask/issues/3868) (though I don't know how to make it as a package and install in my environment). Also I fixed, it using `submit` and `gather`.

**Comment by TomAugspurger** [comment]
Sorry I'm still having trouble reproducing. Could you post the smallest possible snippet that causes the error? http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports may be helpful for what I'm looking for.

**Comment by asifali22** [comment]
Try reproducing the error with following code:

`lr.py`
```
from dask_ml.linear_model import LogisticRegression
from sklearn.base import BaseEstimator, TransformerMixin
from dask.distributed import Client
from sklearn.externals.joblib import parallel_backend
import dask_ml.joblib


class customLR(BaseEstimator, TransformerMixin):
    def __init__(self, client, C=1.0, tol=0.0001):
        self.C = C
        self.tol = tol
        self.client = Client(client)
        self.estimator = LogisticRegression(C=self.C, tol=self.tol, n_jobs=-1)

    def fit(self, X, y):
        with parallel_backend('distributed'):
            self.estimator.fit(X.values, y.values)

    def predict(self, X):
        with parallel_backend('distributed'):
            y_pred = self.estimator.predict(X.values)
            return y_pred

```

`main.py`
```
from dask_ml.model_selection import GridSearchCV
from sklearn.pipeline import Pipeline
from lr import customLR
from dask_ml.datasets import make_classification
import dask.dataframe as dd
from sklearn.externals.joblib import parallel_backend
import dask_ml.joblib

X, y = make_classification(n_samples=10000, chunks=1000, n_classes=2)

X_test, y_test = make_classification(n_samples=10000, chunks=1000, n_classes=2)

X = dd.from_array(X)
y = dd.from_array(y)

X_test = dd.from_array(X_test)

pipe = Pipeline([
    ('lr', customLR(client='127.0.0.1:8786'))
])

grid_param = {'lr__C': [0.1, 0.01, 0.001, 1.0, 10.0],
              'lr__tol': [1e-5, 1e-4, 1e-6, 1e-3]}

grid = GridSearchCV(pipe, param_grid=grid_param, cv=3, scoring='accuracy')

with parallel_backend('distributed'):
    grid.fit(X, y)

```

Error traceback:
```
Traceback (most recent call last):
  File "main.py", line 28, in <module>
    grid.fit(X, y)
  File "/anaconda3/lib/python3.6/site-packages/dask_ml/model_selection/_search.py", line 835, in fit
    multimetric=multimetric
  File "/anaconda3/lib/python3.6/site-packages/dask_ml/model_selection/_search.py", line 156, in build_graph
    dsk[best_estimator] = (fit_best, clone(estimator), best_params,
  File "/anaconda3/lib/python3.6/site-packages/sklearn/base.py", line 62, in clone
    new_object_params[name] = clone(param, safe=False)
  File "/anaconda3/lib/python3.6/site-packages/sklearn/base.py", line 50, in clone
    return estimator_type([clone(e, safe=safe) for e in estimator])
  File "/anaconda3/lib/python3.6/site-packages/sklearn/base.py", line 50, in <listcomp>
    return estimator_type([clone(e, safe=safe) for e in estimator])
  File "/anaconda3/lib/python3.6/site-packages/sklearn/base.py", line 50, in clone
    return estimator_type([clone(e, safe=safe) for e in estimator])
  File "/anaconda3/lib/python3.6/site-packages/sklearn/base.py", line 50, in <listcomp>
    return estimator_type([clone(e, safe=safe) for e in estimator])
  File "/anaconda3/lib/python3.6/site-packages/sklearn/base.py", line 62, in clone
    new_object_params[name] = clone(param, safe=False)
  File "/anaconda3/lib/python3.6/site-packages/sklearn/base.py", line 53, in clone
    return copy.deepcopy(estimator)
  File "/anaconda3/lib/python3.6/copy.py", line 180, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/anaconda3/lib/python3.6/copy.py", line 280, in _reconstruct
    state = deepcopy(state, memo)
  File "/anaconda3/lib/python3.6/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/anaconda3/lib/python3.6/copy.py", line 240, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/anaconda3/lib/python3.6/copy.py", line 169, in deepcopy
    rv = reductor(4)
TypeError: can't pickle _thread.lock objects
Exception ignored in: <object repr() failed>
Traceback (most recent call last):
  File "/anaconda3/lib/python3.6/site-packages/distributed/client.py", line 824, in __del__
  File "/anaconda3/lib/python3.6/site-packages/distributed/client.py", line 997, in close
AttributeError: 'Client' object has no attribute 'status'
```

**Comment by asifali22** [comment]
Sir @TomAugspurger, Thank you for pointing out `client is not serializable`. 
Following the link you mentioned above, 
I changed my code to below:
`lr.py`
```
from dask_ml.linear_model import LogisticRegression
from sklearn.base import BaseEstimator, TransformerMixin
from dask.distributed import Client
from sklearn.externals.joblib import parallel_backend
from dask.distributed import worker_client
import dask_ml.joblib


class customLR(BaseEstimator, TransformerMixin):
    def __init__(self, C=1.0, tol=0.0001):
        self.C = C
        self.tol = tol
        self.estimator = LogisticRegression(C=self.C, tol=self.tol, n_jobs=-1)

    def fit(self, X, y):
        with worker_client() as client:
            est_fut = client.submit(self.estimator.fit, X.values, y.values)
            self.estimator = client.gather(est_fut)

    def predict(self, X):
        with worker_client() as client:
            y_pred_fut = client.submit(self.estimator.predict, X.values)
            y_pred = client.gather(y_pred_fut)
            return y_pred

```

`main.py`
```
from dask_ml.model_selection import GridSearchCV
from sklearn.pipeline import Pipeline
from lr import customLR
from dask_ml.datasets import make_classification
import dask.dataframe as dd
from sklearn.externals.joblib import parallel_backend
import dask_ml.joblib
from dask.distributed import Client

X, y = make_classification(n_samples=10000, chunks=1000, n_classes=2)

X_test, y_test = make_classification(n_samples=10000, chunks=1000, n_classes=2)

X = dd.from_array(X)
y = dd.from_array(y)

X_test = dd.from_array(X_test)

client = Client('127.0.0.1:8786')

pipe = Pipeline([
    ('lr', customLR())
])

grid_param = {'lr__C': [0.1, 0.01, 0.001, 1.0, 10.0],
              'lr__tol': [1e-5, 1e-4, 1e-6, 1e-3]}

grid = GridSearchCV(pipe, param_grid=grid_param, cv=3, scoring='accuracy')

# with parallel_backend('distributed'):
#     grid.fit(X, y)

future = client.submit(grid.fit, X, y)
result = future.result()

```

And now I'm getting below error:
```
Traceback (most recent call last):
  File "main.py", line 34, in <module>
    result = future.result()
  File "/anaconda3/lib/python3.6/site-packages/distributed/client.py", line 172, in result
    six.reraise(*result)
  File "/anaconda3/lib/python3.6/site-packages/six.py", line 692, in reraise
    raise value.with_traceback(tb)
  File "/anaconda3/lib/python3.6/site-packages/distributed/protocol/pickle.py", line 59, in loads
    return pickle.loads(x)
ModuleNotFoundError: No module named 'lr'
```
Now, I'm assuming you will ask me to install it as a package in my environment. But I don't how to do it. I'm a newbie to dask and python. Please help me to solve this issue, it's been 2 days since I have not slept because of this error.
It will be very kind of you to guide me with a series of steps with code snippets sir. Thank you.

**Comment by TomAugspurger** [comment]
You need to ensure that each worker has the same environment. That depends on the cluster manager though. https://dask.pydata.org/en/latest/setup.html

https://packaging.python.org has some information on creating packages.

**Comment by asifali22** [comment]
I'm making sure my workers are running in the same environment.
After adding:
```
.
.
.
client.upload_file('lr.py')

future = client.submit(grid.fit, X, y)
result = future.result()

```

I get following error:
```
Traceback (most recent call last):
  File "main.py", line 36, in <module>
    result = future.result()
  File "/anaconda3/lib/python3.6/site-packages/distributed/client.py", line 172, in result
    six.reraise(*result)
  File "/anaconda3/lib/python3.6/site-packages/six.py", line 692, in reraise
    raise value.with_traceback(tb)
  File "/anaconda3/lib/python3.6/site-packages/dask_ml/model_selection/_search.py", line 841, in fit
    scheduler = dask.base.get_scheduler(
AttributeError: module 'dask.base' has no attribute 'get_scheduler'
```

**Comment by TomAugspurger** [comment]
Try upgrading to the latest version of dask.

**Comment by asifali22** [comment]
After creating a `virtual env` installing all the latest package. With `dask 0.19.2` , `dask_ml 0.10.0` and `python 3.6.4`. 
I ran `main.py` and got the following stack trace:
```
 File "main.py", line 36, in <module>
    result = future.result()
  File "/Users/asifali/workspace/githubReport/newFolder/venv/lib/python3.6/site-packages/distributed/client.py", line 193, in result
    raiseit=False)
  File "/Users/asifali/workspace/githubReport/newFolder/venv/lib/python3.6/site-packages/distributed/client.py", line 647, in sync
    return sync(self.loop, func, *args, **kwargs)
  File "/Users/asifali/workspace/githubReport/newFolder/venv/lib/python3.6/site-packages/distributed/utils.py", line 277, in sync
    six.reraise(*error[0])
  File "/Users/asifali/workspace/githubReport/newFolder/venv/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
  File "/Users/asifali/workspace/githubReport/newFolder/venv/lib/python3.6/site-packages/distributed/utils.py", line 262, in f
    result[0] = yield future
  File "/Users/asifali/workspace/githubReport/newFolder/venv/lib/python3.6/site-packages/tornado/gen.py", line 1133, in run
    value = future.result()
  File "/Users/asifali/workspace/githubReport/newFolder/venv/lib/python3.6/site-packages/tornado/gen.py", line 1141, in run
    yielded = self.gen.throw(*exc_info)
  File "/Users/asifali/workspace/githubReport/newFolder/venv/lib/python3.6/site-packages/distributed/client.py", line 218, in _result
    result = yield self.client._gather([self])
  File "/Users/asifali/workspace/githubReport/newFolder/venv/lib/python3.6/site-packages/tornado/gen.py", line 1133, in run
    value = future.result()
  File "/Users/asifali/workspace/githubReport/newFolder/venv/lib/python3.6/site-packages/tornado/gen.py", line 1141, in run
    yielded = self.gen.throw(*exc_info)
  File "/Users/asifali/workspace/githubReport/newFolder/venv/lib/python3.6/site-packages/distributed/client.py", line 1484, in _gather
    response = yield self.scheduler.gather(keys=keys)
  File "/Users/asifali/workspace/githubReport/newFolder/venv/lib/python3.6/site-packages/tornado/gen.py", line 1133, in run
    value = future.result()
  File "/Users/asifali/workspace/githubReport/newFolder/venv/lib/python3.6/site-packages/tornado/gen.py", line 1141, in run
    yielded = self.gen.throw(*exc_info)
  File "/Users/asifali/workspace/githubReport/newFolder/venv/lib/python3.6/site-packages/distributed/core.py", line 574, in send_recv_from_rpc
    result = yield send_recv(comm=comm, op=key, **kwargs)
  File "/Users/asifali/workspace/githubReport/newFolder/venv/lib/python3.6/site-packages/tornado/gen.py", line 1133, in run
    value = future.result()
  File "/Users/asifali/workspace/githubReport/newFolder/venv/lib/python3.6/site-packages/tornado/gen.py", line 1141, in run
    yielded = self.gen.throw(*exc_info)
  File "/Users/asifali/workspace/githubReport/newFolder/venv/lib/python3.6/site-packages/distributed/core.py", line 451, in send_recv
    response = yield comm.read(deserializers=deserializers)
  File "/Users/asifali/workspace/githubReport/newFolder/venv/lib/python3.6/site-packages/tornado/gen.py", line 1133, in run
    value = future.result()
  File "/Users/asifali/workspace/githubReport/newFolder/venv/lib/python3.6/site-packages/tornado/gen.py", line 1141, in run
    yielded = self.gen.throw(*exc_info)
  File "/Users/asifali/workspace/githubReport/newFolder/venv/lib/python3.6/site-packages/distributed/comm/tcp.py", line 203, in read
    deserializers=deserializers)
  File "/Users/asifali/workspace/githubReport/newFolder/venv/lib/python3.6/site-packages/tornado/gen.py", line 1133, in run
    value = future.result()
  File "/Users/asifali/workspace/githubReport/newFolder/venv/lib/python3.6/site-packages/tornado/gen.py", line 326, in wrapper
    yielded = next(result)
  File "/Users/asifali/workspace/githubReport/newFolder/venv/lib/python3.6/site-packages/distributed/comm/utils.py", line 79, in from_frames
    res = _from_frames()
  File "/Users/asifali/workspace/githubReport/newFolder/venv/lib/python3.6/site-packages/distributed/comm/utils.py", line 65, in _from_frames
    deserializers=deserializers)
  File "/Users/asifali/workspace/githubReport/newFolder/venv/lib/python3.6/site-packages/distributed/protocol/core.py", line 131, in loads
    value = _deserialize(head, fs, deserializers=deserializers)
  File "/Users/asifali/workspace/githubReport/newFolder/venv/lib/python3.6/site-packages/distributed/protocol/serialize.py", line 173, in deserialize
    return loads(header, frames)
  File "/Users/asifali/workspace/githubReport/newFolder/venv/lib/python3.6/site-packages/distributed/protocol/serialize.py", line 48, in dask_loads
    loads = dask_deserialize.dispatch(typ)
  File "/Users/asifali/workspace/githubReport/newFolder/venv/lib/python3.6/site-packages/dask/utils.py", line 408, in dispatch
    raise TypeError("No dispatch for {0}".format(cls))
TypeError: No dispatch for <class 'dask_ml.model_selection._search.GridSearchCV'>
```

**Comment by TomAugspurger** [comment]
It seems a bit strange to be submitting `self.estimator.fit`. A function
only  needs worker_client if it needs to communicate directly with the
scheduler.

The ML examples at http://examples.dask.org may be helpful.

**Comment by asifali22** [comment]
Removing `self.estimator.fit` from `lr.py` didn't resolve the issue.
Here's the updated code:
`lr.py`
```
...
    def fit(self, X, y):
        with worker_client() as client:
            self.estimator.fit(X.values, y.values)


    def predict(self, X):
        with worker_client() as client:
            y_pred = self.estimator.predict(X.values)
        return y_pred
```

Same error stack as before:
`TypeError: No dispatch for <class 'dask_ml.model_selection._search.GridSearchCV'>`
@TomAugspurger  If you don't mind, please re-open this issue as it is not at all resolving even after trying everything mentioned above.

Final stack trace:
```
distributed.protocol.core - CRITICAL - Failed to deserialize
Traceback (most recent call last):
  File "/Users/asifali/workspace/githubReport/newFolder/venv/lib/python3.6/site-packages/distributed/protocol/core.py", line 131, in loads
    value = _deserialize(head, fs, deserializers=deserializers)
  File "/Users/asifali/workspace/githubReport/newFolder/venv/lib/python3.6/site-packages/distributed/protocol/serialize.py", line 173, in deserialize
    return loads(header, frames)
  File "/Users/asifali/workspace/githubReport/newFolder/venv/lib/python3.6/site-packages/distributed/protocol/serialize.py", line 48, in dask_loads
    loads = dask_deserialize.dispatch(typ)
  File "/Users/asifali/workspace/githubReport/newFolder/venv/lib/python3.6/site-packages/dask/utils.py", line 408, in dispatch
    raise TypeError("No dispatch for {0}".format(cls))
TypeError: No dispatch for <class 'dask_ml.model_selection._search.GridSearchCV'>
Traceback (most recent call last):
  File "main.py", line 36, in <module>
    result = future.result()
  File "/Users/asifali/workspace/githubReport/newFolder/venv/lib/python3.6/site-packages/distributed/client.py", line 193, in result
    raiseit=False)
  File "/Users/asifali/workspace/githubReport/newFolder/venv/lib/python3.6/site-packages/distributed/client.py", line 647, in sync
    return sync(self.loop, func, *args, **kwargs)
  File "/Users/asifali/workspace/githubReport/newFolder/venv/lib/python3.6/site-packages/distributed/utils.py", line 277, in sync
    six.reraise(*error[0])
  File "/Users/asifali/workspace/githubReport/newFolder/venv/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
  File "/Users/asifali/workspace/githubReport/newFolder/venv/lib/python3.6/site-packages/distributed/utils.py", line 262, in f
    result[0] = yield future
  File "/Users/asifali/workspace/githubReport/newFolder/venv/lib/python3.6/site-packages/tornado/gen.py", line 1055, in run
    value = future.result()
  File "/Users/asifali/workspace/githubReport/newFolder/venv/lib/python3.6/site-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
  File "/Users/asifali/workspace/githubReport/newFolder/venv/lib/python3.6/site-packages/tornado/gen.py", line 1063, in run
    yielded = self.gen.throw(*exc_info)
  File "/Users/asifali/workspace/githubReport/newFolder/venv/lib/python3.6/site-packages/distributed/client.py", line 218, in _result
    result = yield self.client._gather([self])
  File "/Users/asifali/workspace/githubReport/newFolder/venv/lib/python3.6/site-packages/tornado/gen.py", line 1055, in run
    value = future.result()
  File "/Users/asifali/workspace/githubReport/newFolder/venv/lib/python3.6/site-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
  File "/Users/asifali/workspace/githubReport/newFolder/venv/lib/python3.6/site-packages/tornado/gen.py", line 1063, in run
    yielded = self.gen.throw(*exc_info)
  File "/Users/asifali/workspace/githubReport/newFolder/venv/lib/python3.6/site-packages/distributed/client.py", line 1484, in _gather
    response = yield self.scheduler.gather(keys=keys)
  File "/Users/asifali/workspace/githubReport/newFolder/venv/lib/python3.6/site-packages/tornado/gen.py", line 1055, in run
    value = future.result()
  File "/Users/asifali/workspace/githubReport/newFolder/venv/lib/python3.6/site-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
  File "/Users/asifali/workspace/githubReport/newFolder/venv/lib/python3.6/site-packages/tornado/gen.py", line 1063, in run
    yielded = self.gen.throw(*exc_info)
  File "/Users/asifali/workspace/githubReport/newFolder/venv/lib/python3.6/site-packages/distributed/core.py", line 574, in send_recv_from_rpc
    result = yield send_recv(comm=comm, op=key, **kwargs)
  File "/Users/asifali/workspace/githubReport/newFolder/venv/lib/python3.6/site-packages/tornado/gen.py", line 1055, in run
    value = future.result()
  File "/Users/asifali/workspace/githubReport/newFolder/venv/lib/python3.6/site-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
  File "/Users/asifali/workspace/githubReport/newFolder/venv/lib/python3.6/site-packages/tornado/gen.py", line 1063, in run
    yielded = self.gen.throw(*exc_info)
  File "/Users/asifali/workspace/githubReport/newFolder/venv/lib/python3.6/site-packages/distributed/core.py", line 451, in send_recv
    response = yield comm.read(deserializers=deserializers)
  File "/Users/asifali/workspace/githubReport/newFolder/venv/lib/python3.6/site-packages/tornado/gen.py", line 1055, in run
    value = future.result()
  File "/Users/asifali/workspace/githubReport/newFolder/venv/lib/python3.6/site-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
  File "/Users/asifali/workspace/githubReport/newFolder/venv/lib/python3.6/site-packages/tornado/gen.py", line 1063, in run
    yielded = self.gen.throw(*exc_info)
  File "/Users/asifali/workspace/githubReport/newFolder/venv/lib/python3.6/site-packages/distributed/comm/tcp.py", line 203, in read
    deserializers=deserializers)
  File "/Users/asifali/workspace/githubReport/newFolder/venv/lib/python3.6/site-packages/tornado/gen.py", line 1055, in run
    value = future.result()
  File "/Users/asifali/workspace/githubReport/newFolder/venv/lib/python3.6/site-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
  File "/Users/asifali/workspace/githubReport/newFolder/venv/lib/python3.6/site-packages/tornado/gen.py", line 307, in wrapper
    yielded = next(result)
  File "/Users/asifali/workspace/githubReport/newFolder/venv/lib/python3.6/site-packages/distributed/comm/utils.py", line 79, in from_frames
    res = _from_frames()
  File "/Users/asifali/workspace/githubReport/newFolder/venv/lib/python3.6/site-packages/distributed/comm/utils.py", line 65, in _from_frames
    deserializers=deserializers)
  File "/Users/asifali/workspace/githubReport/newFolder/venv/lib/python3.6/site-packages/distributed/protocol/core.py", line 131, in loads
    value = _deserialize(head, fs, deserializers=deserializers)
  File "/Users/asifali/workspace/githubReport/newFolder/venv/lib/python3.6/site-packages/distributed/protocol/serialize.py", line 173, in deserialize
    return loads(header, frames)
  File "/Users/asifali/workspace/githubReport/newFolder/venv/lib/python3.6/site-packages/distributed/protocol/serialize.py", line 48, in dask_loads
    loads = dask_deserialize.dispatch(typ)
  File "/Users/asifali/workspace/githubReport/newFolder/venv/lib/python3.6/site-packages/dask/utils.py", line 408, in dispatch
    raise TypeError("No dispatch for {0}".format(cls))
TypeError: No dispatch for <class 'dask_ml.model_selection._search.GridSearchCV'>
```
