### ISSUE TITLE
dask.bag.read_avro not recognizing s3 filesystem

### ISSUE THREAD

**Issue by ian-whitestone** [dask/dask#4006]
@martindurant I was testing out the new avro functionality you added in #4000. When trying to read avro files from S3, it errors because it is trying to read the s3 files from my local filesystem.

```python
>>> from dask import bag
>>> bag = bag.read_avro('s3://dask-avro-data/weather*.avro')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/ianwhitestone/miniconda3/lib/python3.7/site-packages/dask/bag/avro.py", line 99, in read_avro
    **storage_options)
  File "/Users/ianwhitestone/miniconda3/lib/python3.7/site-packages/dask/bytes/core.py", line 97, in read_bytes
    size = logical_size(fs, path, compression)
  File "/Users/ianwhitestone/miniconda3/lib/python3.7/site-packages/dask/bytes/core.py", line 508, in logical_size
    return fs.size(path)
  File "/Users/ianwhitestone/miniconda3/lib/python3.7/site-packages/dask/bytes/local.py", line 67, in size
    return os.stat(self._normalize_path(path)).st_size
FileNotFoundError: [Errno 2] No such file or directory: '/Users/ianwhitestone/Documents/git/gists/dask-avro-data/weather.avro'
```

Looks like this is caused by passing the `OpenFile.path` attribute to the `read_bytes` function [here](https://github.com/dask/dask/blob/master/dask/bag/avro.py#L89-L99). The `OpenFile.path` attribute does not contain the filesystem information, so read_bytes tries to look for the file locally.

```python
>>> from dask.bytes.core import open_files, read_bytes
>>> storage_options = {}
>>> urlpath = 's3://dask-avro-data/weather*.avro'
>>> files = open_files(urlpath, **storage_options)
>>> for f in files:
...     print(f.path) # this is the path that gets passed into read_bytes()
...
dask-avro-data/weather.avro
dask-avro-data/weather2.avro
dask-avro-data/weather3.avro
```

Not sure what the cleanest way to fix this would be. Could modify the`OpenFile` class to have a `urlpath` attribute, or make a call to `dask.bytes.utils.infer_storage_options` in read_avro to get the protocol, and modify the `OpenFile.path` with the proper prefix before passing into `read_bytes`

**Comment by martindurant** [comment]
Yes, you are right - I will get back to you.
