### ISSUE TITLE
Passing a tuple/namedtuple as a kwarg to atop/top fails on dask 0.20.0

### ISSUE THREAD

**Issue by sjperkins** [dask/dask#4158]
but used to work on dask 0.19.4

```python
from collections import namedtuple

import dask
import dask.array as da


A = da.random.random((100, 100), chunks=(10, 10))

foo = namedtuple("foo", ["bar", "qux"])


def wrappymcwrapface(data, fooval):
    return data


result = da.atop(wrappymcwrapface, ("d1", "d2"),
                 A, ("d1", "d2"),
                 fooval=foo("pants", "marmalade"),
                 dtype=A.dtype)
```

The above produces the following backtrace.

```backtrace
$ python test_dask_namedtuple_kwargs.py 
Traceback (most recent call last):
  File "test_dask_namedtuple_kwargs.py", line 19, in <module>
    dtype=A.dtype)
  File "/home/sperkins/venv/dask-0.20.0/local/lib/python2.7/site-packages/dask/array/top.py", line 482, in atop
    dsk = _top(func, out, out_ind, *argindsstr, numblocks=numblocks, **kwargs2)
  File "/home/sperkins/venv/dask-0.20.0/local/lib/python2.7/site-packages/dask/array/top.py", line 96, in _top
    kwargs = subs(kwargs, sub)
  File "/home/sperkins/venv/dask-0.20.0/local/lib/python2.7/site-packages/dask/array/top.py", line 22, in subs
    return type(task)([subs(x, substitution) for x in task])
  File "/home/sperkins/venv/dask-0.20.0/local/lib/python2.7/site-packages/dask/array/top.py", line 22, in subs
    return type(task)([subs(x, substitution) for x in task])
  File "/home/sperkins/venv/dask-0.20.0/local/lib/python2.7/site-packages/dask/array/top.py", line 22, in subs
    return type(task)([subs(x, substitution) for x in task])
  File "/home/sperkins/venv/dask-0.20.0/local/lib/python2.7/site-packages/dask/array/top.py", line 22, in subs
    return type(task)([subs(x, substitution) for x in task])
TypeError: __new__() takes exactly 3 arguments (2 given)
```

**Comment by mrocklin** [comment]
Thanks for reporting @sjperkins .  Possible fix in https://github.com/dask/dask/pull/4159
