### ISSUE TITLE
ShareDict seems to cause issues with HighLevelGraphs in optimize_atop

### ISSUE THREAD

**Issue by sjperkins** [dask/dask#4176]
Following up on https://github.com/dask/dask/issues/4038#issuecomment-434338006, this script:

```python
from dask.sharedict import ShareDict
import numpy as np


def foo(A):
    return A[None, ...]


A = da.ones(shape=(10, 20, 4), chunks=(2, 5, 4))

name = 'D-' + dask.base.tokenize(A)

dsk = da.core.top(
        foo, name, ("nsrc", "ntime", "nbl", "npol"),
        A.name, ("ntime", "nbl", "npol"),
        new_axes={"nsrc": 1},
        numblocks={a.name: a.numblocks for a in (A,)})

array_dsk = ShareDict()
array_dsk.update(dsk)
array_dsk.update(A.__dask_graph__())

chunks = ((1,),) + A.chunks

D = da.Array(array_dsk, name, chunks, dtype=A.dtype)
print(D.compute().shape)    # Succeeds
D = D.sum(axis=0)
print(D.compute().shape)    # Fails
```

causes the following error:

```traceback
$ python dask_top_2.py 
(1, 10, 20, 4)
Traceback (most recent call last):
  File "dask_top_2.py", line 32, in <module>
    pprint(D.compute().shape)
  File "/home/sperkins/tmp/python/dask/venv/local/lib/python2.7/site-packages/dask/base.py", line 155, in compute
    (result,) = compute(self, traverse=False, **kwargs)
  File "/home/sperkins/tmp/python/dask/venv/local/lib/python2.7/site-packages/dask/base.py", line 389, in compute
    dsk = collections_to_dsk(collections, optimize_graph, **kwargs)
  File "/home/sperkins/tmp/python/dask/venv/local/lib/python2.7/site-packages/dask/base.py", line 193, in collections_to_dsk
    for opt, (dsk, keys) in groups.items()]))
  File "/home/sperkins/tmp/python/dask/venv/local/lib/python2.7/site-packages/dask/array/optimization.py", line 38, in optimize
    dsk = optimize_atop(dsk, keys=keys)
  File "/home/sperkins/tmp/python/dask/venv/local/lib/python2.7/site-packages/dask/array/top.py", line 594, in optimize_atop
    if (isinstance(layers[dep], TOP) and
KeyError: 'D-122ec2f0f994205583cdc43c8fba6f6d'
```

**Comment by sjperkins** [comment]
python 2.7.14
dask master branch

**Comment by mrocklin** [comment]
Thanks for raising this issue @sjperkins .  Checking in, is everything above necessary in order to reproduce your error?  If not then can I ask you to simplify things first please?  This will really help to isolate where the problem is.

**Comment by sjperkins** [comment]
@mrocklin  I've updated the example.

**Comment by sjperkins** [comment]
I think this is ShareDict related, the above example works with a normal dict.

**Comment by mrocklin** [comment]
Thanks for producing the minimal example.  That really helps reduce the time to find a solution.  See #4181

**Comment by sjperkins** [comment]
@mrocklin Thanks for fixing. I see you mention lack of ShareDict dependencies in your fix. In my example, I do the following:

```python
array_dsk = ShareDict()
array_dsk.update(dsk)
array_dsk.update(A.__dask_graph__())
```

Is this an incorrect use of ShareDict? I believe that I'm specifying all the dependencies required for the graph.

**Comment by mrocklin** [comment]
It's fine.  We started adding additional features metadata for atop fusion
that this approach lacks, but the absence of that dependency metadata
shouldn't affect correctness.

If you change things I recommend taking a look at
https://github.com/dask/dask/pull/4092 and basing future work off of that
approach.
