### ISSUE TITLE
Peculiar interaction between top and subgraph_callable

### ISSUE THREAD

**Issue by sjperkins** [dask/dask#4177]
```python
import numpy as np
import dask.array as da


def _grid_fn(vis, nx, ny):
    vis = vis[0]
    shape = (1, ny, nx) + vis.shape[2:]
    return np.zeros(shape, dtype=vis.dtype)


def grid(vis, nx=1024, ny=1024):
    """ Documentation below """

    # Creation correlation dimension strings for each correlation
    corrs = tuple('corr-%d' for i in range(len(vis.shape[2:])))

    # Get grids, stacked by row
    grids = da.core.atop(_grid_fn, ("row", "ny", "nx") + corrs,
                         vis, ("row", "chan") + corrs,
                         new_axes={"ny": ny, "nx": nx},
                         adjust_chunks={"row": 1},
                         ny=ny, nx=nx,
                         dtype=vis.dtype)

    # Sum grids over the row dimension to produce (ny, nx, corr_1, corr_2)
    return grids.sum(axis=0)


row_chunks = (10, 10, 10)
chan_chunks = (16,)
corr1_chunks = (2,)
corr2_chunks = (2,)

rows = sum(row_chunks)
chans = sum(chan_chunks)
corr1 = sum(corr1_chunks)
corr2 = sum(corr2_chunks)

vis_chunks = (row_chunks, chan_chunks, corr1_chunks, corr2_chunks)

vis = da.random.random((rows, chans, corr1, corr2), chunks=vis_chunks)

grids = grid(vis, 1024, 1024)
grids.compute()
```
 traceback:

```traceback$ python test_dask_atop_failure.py 
Traceback (most recent call last):
  File "test_dask_atop_failure.py", line 43, in <module>
    grids.compute()
  File "/home/sperkins/tmp/python/dask/venv/local/lib/python2.7/site-packages/dask/base.py", line 155, in compute
    (result,) = compute(self, traverse=False, **kwargs)
  File "/home/sperkins/tmp/python/dask/venv/local/lib/python2.7/site-packages/dask/base.py", line 389, in compute
    dsk = collections_to_dsk(collections, optimize_graph, **kwargs)
  File "/home/sperkins/tmp/python/dask/venv/local/lib/python2.7/site-packages/dask/base.py", line 193, in collections_to_dsk
    for opt, (dsk, keys) in groups.items()]))
  File "/home/sperkins/tmp/python/dask/venv/local/lib/python2.7/site-packages/dask/array/optimization.py", line 41, in optimize
    dsk = ensure_dict(dsk)
  File "/home/sperkins/tmp/python/dask/venv/local/lib/python2.7/site-packages/dask/utils.py", line 828, in ensure_dict
    result.update(dd)
  File "/home/sperkins/tmp/python/dask/venv/lib/python2.7/_abcoll.py", line 410, in keys
    return list(self)
  File "/home/sperkins/tmp/python/dask/venv/local/lib/python2.7/site-packages/dask/array/top.py", line 167, in __iter__
    return iter(self._dict)
  File "/home/sperkins/tmp/python/dask/venv/local/lib/python2.7/site-packages/dask/array/top.py", line 159, in _dict
    concatenate=self.concatenate
  File "/home/sperkins/tmp/python/dask/venv/local/lib/python2.7/site-packages/dask/array/top.py", line 304, in top
    keytups = list(itertools.product(*[range(dims[i]) for i in out_indices]))
KeyError: '.3'

```

**Comment by sjperkins** [comment]
Managed to produce a MCVE

**Comment by sjperkins** [comment]
python 2.7.14
dask master branch

**Comment by mrocklin** [comment]
Thanks for providing the example @sjperkins .  Just to check, everything in the example is necessary to produce the error?  Is there any way to slim it down a bit?  Usually fixing a bug like this first entails identifying exactly what causes it.  Usually the best way to do that is to take the failing example and remove things until the error goes away, and then investigate that last step.  If you're able to do this (you're probably the most qualified person with this example) then I suspect that  we'll be able to identify the cause much more quickly.

**Comment by sjperkins** [comment]
@mrocklin I've shrunk the example. It runs fine when the reduction `grids.sum(axis=0)` is removed (i.e. `return grids` is used).

**Comment by mrocklin** [comment]
Thank you @sjperkins .  That modification is super-helpful.  I look forward to taking a closer look at this tomorrow.

**Comment by sjperkins** [comment]
Thanks for the nudge and the work on high level graphs. It's a great feature.

**Comment by mrocklin** [comment]
You've forgotten to place a `% i` in this line:

    corrs = tuple('corr-%d' for i in range(len(vis.shape[2:])))
    corrs = tuple('corr-%d' % i for i in range(len(vis.shape[2:])))

**Comment by mrocklin** [comment]
So things work fine.  We probably should have raised a more informative error for you though.

**Comment by sjperkins** [comment]
> You've forgotten to place a % i in this line:

Ah apologies for this, my test cases did not pick this up on dask versions less than 0.20.0 (probably because when two correlations are present they have the same size).
