### ISSUE TITLE
dask-mpi fails to start

### ISSUE THREAD

**Issue by adamjermyn** [dask/dask#4214]
I'm using dask-mpi on a managed cluster with slurm. As a test I request two nodes with eight tasks as
```
srun --nodes=2 --ntasks-per-node=8 --pty bash
```
I then run
```
mpirun --n 16 dask-mpi --scheduler-file=(my scheduler path)
```
My scheduler path lives in my home directory, which is shared across nodes. This produces the following output
```
distributed.nanny - INFO -         Start Nanny at: 'tcp://10.1.50.8:35774'
distributed.nanny - INFO -         Start Nanny at: 'tcp://10.1.50.8:38201'
distributed.nanny - INFO -         Start Nanny at: 'tcp://10.1.50.8:40055'
distributed.nanny - INFO -         Start Nanny at: 'tcp://10.1.50.8:37066'
distributed.nanny - INFO -         Start Nanny at: 'tcp://10.1.50.8:42727'
distributed.nanny - INFO -         Start Nanny at: 'tcp://10.1.50.8:46457'
distributed.nanny - INFO -         Start Nanny at: 'tcp://10.1.50.8:45759'
distributed.scheduler - INFO - Clear task state
distributed.scheduler - INFO -   Scheduler at:      tcp://10.1.50.8:8786
distributed.scheduler - INFO -       bokeh at:                     :8787
[cli_1]: write_line error; fd=6 buf=:cmd=init pmi_version=1 pmi_subversion=1
:
system msg for write_line failure : Invalid argument
[cli_1]: Unable to write to PMI_fd
[cli_1]: write_line error; fd=6 buf=:cmd=get_appnum
:
system msg for write_line failure : Invalid argument
[cli_2]: Error reading initack on 11
Error on readline:: Bad file descriptor
[cli_2]: aborting job:
Above error when reading after init
[cli_6]: write_line error; fd=23 buf=:cmd=init pmi_version=1 pmi_subversion=1
:
system msg for write_line failure : Bad file descriptor
[cli_6]: Unable to write to PMI_fd
[cli_6]: write_line error; fd=23 buf=:cmd=get_appnum
:
system msg for write_line failure : Bad file descriptor
Fatal error in PMPI_Init_thread: Other MPI error, error stack:
MPIR_Init_thread(392):
MPID_Init(107).......: channel initialization failed
MPID_Init(389).......: PMI_Get_appnum returned -1
Fatal error in PMPI_Init_thread: Other MPI error, error stack:
MPIR_Init_thread(392):
MPID_Init(107).......: channel initialization failed
MPID_Init(389).......: PMI_Get_appnum returned -1
distributed.nanny - WARNING - Worker process 275707 was killed by unknown signal
distributed.nanny - WARNING - Worker process 275705 was killed by unknown signal
distributed.nanny - WARNING - Worker process 275708 was killed by unknown signal
distributed.nanny - WARNING - Restarting worker
distributed.nanny - WARNING - Restarting worker
distributed.nanny - WARNING - Restarting worker
[cli_5]: write_line error; fd=20 buf=:cmd=init pmi_version=1 pmi_subversion=1
:
system msg for write_line failure : Bad file descriptor
[cli_5]: Unable to write to PMI_fd
[cli_5]: write_line error; fd=20 buf=:cmd=get_appnum
:
system msg for write_line failure : Bad file descriptor
Fatal error in PMPI_Init_thread: Other MPI error, error stack:
MPIR_Init_thread(392):
MPID_Init(107).......: channel initialization failed
MPID_Init(389).......: PMI_Get_appnum returned -1
distributed.nanny - WARNING - Worker process 275711 was killed by unknown signal
distributed.nanny - WARNING - Restarting worker
[cli_3]: write_line error; fd=14 buf=:cmd=init pmi_version=1 pmi_subversion=1
```
which then goes on for a while with more similar messages. At the end I get
```
:
system msg for write_line failure : Invalid argument
Fatal error in PMPI_Init_thread: Other MPI error, error stack:
MPIR_Init_thread(392):
MPID_Init(107).......: channel initialization failed
MPID_Init(389).......: PMI_Get_appnum returned -1
distributed.nanny - WARNING - Worker process 275909 was killed by unknown signal
distributed.nanny - INFO - Closing Nanny at 'tcp://10.1.50.8:40055'
Traceback (most recent call last):
  File "/home/adamjermyn/miniconda3/bin/dask-mpi", line 11, in <module>
    sys.exit(go())
  File "/home/adamjermyn/miniconda3/lib/python3.6/site-packages/distributed/cli/dask_mpi.py", line 101, in go
    main()
  File "/home/adamjermyn/miniconda3/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/adamjermyn/miniconda3/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/adamjermyn/miniconda3/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/adamjermyn/miniconda3/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/adamjermyn/miniconda3/lib/python3.6/site-packages/distributed/cli/dask_mpi.py", line 96, in main
    loop.run_sync(close)
  File "/home/adamjermyn/miniconda3/lib/python3.6/site-packages/tornado/ioloop.py", line 571, in run_sync
    self.start()
  File "/home/adamjermyn/miniconda3/lib/python3.6/site-packages/tornado/platform/asyncio.py", line 132, in start
    self.asyncio_loop.run_forever()
  File "/home/adamjermyn/miniconda3/lib/python3.6/asyncio/base_events.py", line 412, in run_forever
    self._check_closed()
  File "/home/adamjermyn/miniconda3/lib/python3.6/asyncio/base_events.py", line 366, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
```
and then there is no more output, though the process continues.

When I try to connect with a client and do calculations they just hang, which (along with the above errors) makes me suspect that dask-mpi did not start correctly.

For reference I am using Dask revision `f52e073b89469c2d687aa7a93f55e57992f8b16e`, installed on 64bit Miniconda on a Redhat cluster. This appears to be similar to issue #1829, but it looks like that was fixed a while back.

Any help with fixing this would be much appreciated!

**Comment by mrocklin** [comment]
My first guess is that this is probably specific to your particular
cluster.  If you haven't already I recommend running those log files by
your system administrator.

**Comment by jcrist** [comment]
@adamjermyn, any update here?

**Comment by adamjermyn** [comment]
I haven’t managed to get it working on this cluster. I have had luck on others though so I’m guessing this is specific to the setup here.

**Comment by adamjermyn** [comment]
Using --no-nanny worked, thank you!

-Adam

**Comment by guillaumeeb** [comment]
Glad to hear it. I recently modified the documentation of dask-mpi to document this:

> In some setups, MPI processes are not allowed to fork other processes. In this case, we recommend using --no-nanny option in order to prevent dask from using an additional nanny process to manage workers.

So I believe we can close this one.

**Comment by mrocklin** [comment]
Closing.  Thanks for resolving this @guillaumeeb !

Also, just checking, as a member of the Dask org do you have permissions to close issues in repositories other than dask-jobqueue?

**Comment by guillaumeeb** [comment]
Nope, I can only close issues from dask-jobqueue (which seems normal for the time being).
