### ISSUE TITLE
Running out of threads on cluster

### ISSUE THREAD

**Issue by dkillick** [dask/dask#4240]
We're seeing a lot of examples, apparently originating in dask, of running out of threads when running various dask workloads on our SLURM-scheduled cluster. This manifests in one of two ways:
* in the less serious, running in parallel on the cluster takes a lot longer than running synchronously on the cluster (if you interrupt the job it looks like the majority of the time is taken up switching threads)
* in the more serious, the maximum number of allowed threads is hit and the job fails.

Here's an example of the stacktrace we're seeing in the more serious case:

```python
cube.data
```
```python-stacktrace
Traceback (most recent call last):
  File "/.../create_jules_ic_v2.py", line 279, in <module>
    main()                           
  File "/.../create_jules_ic_v2.py", line 274, in main
    nameoffile=create_jules_ic(Ddate,INDIR,UM_FILE_IN,OUTDIR)              
  File "/.../create_jules_ic_v2.py", line 152, in create_jules_ic
    print(type(cube_vegfrac.data <=0.0001))  
  File "/.../python2.7/site-packages/iris/cube.py", line 1644, in data
    return self._data_manager.data
  File "/.../python2.7/site-packages/iris/_data_manager.py", line 216, in data
    result = as_concrete_data(self._lazy_array)
  File "/.../python2.7/site-packages/iris/_lazy_data.py", line 128, in as_concrete_data
    data = np.asanyarray(data.compute())
  File "/.../python2.7/site-packages/dask/base.py", line 143, in compute
    (result,) = compute(self, traverse=False, **kwargs)
  File "/.../python2.7/site-packages/dask/base.py", line 392, in compute
    results = get(dsk, keys, **kwargs)
  File "/.../python2.7/site-packages/dask/threaded.py", line 75, in get
    pack_exception=pack_exception, **kwargs)
  File "/.../python2.7/site-packages/dask/local.py", line 521, in get_async
    raise_exception(exc, tb)
  File "/.../python2.7/site-packages/dask/local.py", line 290, in execute_task
    result = _execute_task(task, data)
  File "/.../python2.7/site-packages/dask/local.py", line 270, in _execute_task
    args2 = [_execute_task(a, cache) for a in args]
  File "/.../python2.7/site-packages/dask/local.py", line 271, in _execute_task
    return func(*args2)
  File "/.../python2.7/site-packages/dask/array/core.py", line 74, in getter
    c = a[b]
  File "/.../python2.7/site-packages/iris/fileformats/pp.py", line 647, in __getitem__
    self.mdi, self.mask)
  File "/.../python2.7/site-packages/iris/fileformats/pp.py", line 770, in _data_bytes_to_shaped_array
    land_mask = mask.data.astype(np.bool)
  File "/.../python2.7/site-packages/iris/fileformats/pp.py", line 1033, in data
    self._data = as_concrete_data(self._data)
  File "/.../python2.7/site-packages/iris/_lazy_data.py", line 128, in as_concrete_data
    data = np.asanyarray(data.compute())
  File "/.../python2.7/site-packages/dask/base.py", line 143, in compute
    (result,) = compute(self, traverse=False, **kwargs)
  File "/.../python2.7/site-packages/dask/base.py", line 392, in compute
    results = get(dsk, keys, **kwargs)
  File "/.../python2.7/site-packages/dask/threaded.py", line 70, in get
    pool = ThreadPool(num_workers)
  File "/.../python2.7/multiprocessing/pool.py", line 727, in __init__
    Pool.__init__(self, processes, initializer, initargs)
  File "/.../python2.7/multiprocessing/pool.py", line 159, in __init__
    self._repopulate_pool()
  File "/.../python2.7/multiprocessing/pool.py", line 223, in _repopulate_pool
    w.start()
  File "/.../python2.7/multiprocessing/dummy/__init__.py", line 75, in start
    threading.Thread.start(self)
  File "/.../python2.7/threading.py", line 736, in start
    _start_new_thread(self.__bootstrap, ())
thread.error: can't start new thread
```

The stacktrace seems to suggest the underlying code enters a loop where the number of threads utilised per process increments each time the loop is traversed. This is corroborated by a watch I performed on the number of threads in use per process - they all start off at one and then steadily increment until the above error occurs.

We've seen this happening when realising the dask array at the core of Iris cubes (as in the above example) and also when processing dask bags containing dask cubes, so it is very possible that it's something we're doing in Iris that's causing this. Is anyone able to shed any light on what might be causing this, and indeed whether the issue is originating within dask?

**Comment by mrocklin** [comment]
Some libraries are themselves multi-threaded.  This is common, for example, with BLAS/LAPACK implementations.  Usually this just causes performance degredation as many threads start many multi-threaded tasks, leading to oversaturation of cores.  Typically the solution to this is to limit the number of threads that these libraries use.  A common way to solve this is by setting the following environment variable:

    OMP_NUM_THREADS=1

Many multi-core libraries, including most major BLAS/LAPACK implementations, seem to respect that variable (at least OpenBLAS does, I think MKL also, if not then they have their own specific variables).  This would also affect any library that uses OpenMP for multi-core parallelism.

Not being able to start new threads is rare, and I've only ever seen it on HPC machines, which seem to be built with the idea that "if you're not running maximally efficiently, then probably you want us to fall over so that you know about it".  It *might* be worth starting a conversation upstream with IT about this policy, though of course the odds of things changing short term on that front are often low.

**Comment by dkillick** [comment]
We've actually made use of that environment variable - it reduces the problem but doesn't fix it. Apologies, I should have mentioned that in the original post. What we're seeing is that the number of threads ratchets up and up until the maximum number of threads per job as specified by the cluster policy is reached, and then we hit that error.

**Comment by dkillick** [comment]
Alright, I'm more convinced now that this is an issue being caused by Iris, which is particularly evident on clusters because the chance for the number of threads to hit the thread limit is much higher when there are more concurrent processes in use.

The thing I spotted in the stacktrace is that in this particular case, Iris actually produces a _nested_ `compute` call:

```python-traceback
...
  File "/.../python2.7/site-packages/iris/_lazy_data.py", line 128, in as_concrete_data
    data = np.asanyarray(data.compute())
...
  File "/.../python2.7/site-packages/iris/_lazy_data.py", line 128, in as_concrete_data
    data = np.asanyarray(data.compute())
...
```

Is it reasonable to think that a compute call nested within another compute call could cause threads to increment in the way we're seeing here?

I think I've also managed to put together a representative example equivalent to the Iris code that generated this error, but which doesn't use Iris. It doesn't cause this failure, which seems to further back up pointing the finger at Iris for this.

**Comment by mrocklin** [comment]
> Is it reasonable to think that a compute call nested within another compute call could cause threads to increment in the way we're seeing here?

Yes, that seems reasonable.  

Calling compute-in-compute is almost always an anti-pattern.  I recommend diving in a bit there to determine if it is necessary.

**Comment by dkillick** [comment]
Thanks @jakirkham, really helpful - I wasn't aware of that environment variable. Sadly it still doesn't solve this problem; but I think this really is coming from Iris...

**Comment by alpmdog** [comment]
@dkillick  I have seen similar behavior when using dask arrays build from zarr. I would be really interested to know if you are able to resolve this and how it was resolved.
