### ISSUE TITLE
Multiple dataframe length-related operations produce exceptions

### ISSUE THREAD

**Issue by BrockmeyerTyler** [dask/dask#4320]
I've been trying to convert a project of mine to use dask instead of basic pandas because I am reading from a massive amount of .csv files for training a neural network.

My workflow is as follows:
I create dask dataframes, then I save them to disk with `dataframe.to_csv('/path/to/xyz.*.csv')`.
From here, everything looks good. The csv files are all there, and they have the data inside as one would expect.
I then load the data using `dd.read_csv('/path/to/xyz.*.csv')` and, as far as I am aware, the data appears to be fine. I can slice it up into the different sections that I require as needed.
The problem occurs when I try to convert the newly created slices into dask arrays with `arr = dataframe.to_dask_array(lengths=True)`. I need to be able to slice the array and reshape it, so I need lengths=True to do this.

I've been looking around for clues on what's happening, but I haven't been able to find anything. I was hoping you all would be able to help me out. I hope that this isn't just one major oversight.

The traceback is long and cryptic -_-
```Traceback (most recent call last):
  File "./train.py", line 254, in <module>
    main(_args.directory, _args.epochs, _args.verbose, _args.section)
  File "./train.py", line 29, in main
    train_section(directory, epochs, verbose, section)
  File "./train.py", line 132, in train_section
    parse_and_preprocess(training_sets[l], entry_size, shuffle=True)
  File "./train.py", line 226, in parse_and_preprocess
    arr = dataframe.to_dask_array(lengths=True)
  File "/projects/tbrockmeyer/road_tunnel/env/lib/python3.6/site-packages/dask/dataframe/core.py", line 1105, in to_dask_array
    lengths = tuple(self.map_partitions(len).compute())
  File "/projects/tbrockmeyer/road_tunnel/env/lib/python3.6/site-packages/dask/base.py", line 156, in compute
    (result,) = compute(self, traverse=False, **kwargs)
  File "/projects/tbrockmeyer/road_tunnel/env/lib/python3.6/site-packages/dask/base.py", line 397, in compute
    results = schedule(dsk, keys, **kwargs)
  File "/projects/tbrockmeyer/road_tunnel/env/lib/python3.6/site-packages/dask/threaded.py", line 76, in get
    pack_exception=pack_exception, **kwargs)
  File "/projects/tbrockmeyer/road_tunnel/env/lib/python3.6/site-packages/dask/local.py", line 501, in get_async
    raise_exception(exc, tb)
  File "/projects/tbrockmeyer/road_tunnel/env/lib/python3.6/site-packages/dask/compatibility.py", line 112, in reraise
    raise exc
  File "/projects/tbrockmeyer/road_tunnel/env/lib/python3.6/site-packages/dask/local.py", line 272, in execute_task
    result = _execute_task(task, data)
  File "/projects/tbrockmeyer/road_tunnel/env/lib/python3.6/site-packages/dask/local.py", line 252, in _execute_task
    args2 = [_execute_task(a, cache) for a in args]
  File "/projects/tbrockmeyer/road_tunnel/env/lib/python3.6/site-packages/dask/local.py", line 252, in <listcomp>
    args2 = [_execute_task(a, cache) for a in args]
  File "/projects/tbrockmeyer/road_tunnel/env/lib/python3.6/site-packages/dask/local.py", line 249, in _execute_task
    return [_execute_task(a, cache) for a in arg]
  File "/projects/tbrockmeyer/road_tunnel/env/lib/python3.6/site-packages/dask/local.py", line 249, in <listcomp>
    return [_execute_task(a, cache) for a in arg]
  File "/projects/tbrockmeyer/road_tunnel/env/lib/python3.6/site-packages/dask/local.py", line 252, in _execute_task
    args2 = [_execute_task(a, cache) for a in args]
  File "/projects/tbrockmeyer/road_tunnel/env/lib/python3.6/site-packages/dask/local.py", line 252, in <listcomp>
    args2 = [_execute_task(a, cache) for a in args]
  File "/projects/tbrockmeyer/road_tunnel/env/lib/python3.6/site-packages/dask/local.py", line 252, in _execute_task
    args2 = [_execute_task(a, cache) for a in args]
  File "/projects/tbrockmeyer/road_tunnel/env/lib/python3.6/site-packages/dask/local.py", line 252, in <listcomp>
    args2 = [_execute_task(a, cache) for a in args]
  File "/projects/tbrockmeyer/road_tunnel/env/lib/python3.6/site-packages/dask/local.py", line 249, in _execute_task
    return [_execute_task(a, cache) for a in arg]
  File "/projects/tbrockmeyer/road_tunnel/env/lib/python3.6/site-packages/dask/local.py", line 249, in <listcomp>
    return [_execute_task(a, cache) for a in arg]
  File "/projects/tbrockmeyer/road_tunnel/env/lib/python3.6/site-packages/dask/local.py", line 253, in _execute_task
    return func(*args2)
  File "/projects/tbrockmeyer/road_tunnel/env/lib/python3.6/site-packages/dask/dataframe/core.py", line 3684, in apply_and_enforce
    df = func(*args, **kwargs)
  File "/projects/tbrockmeyer/road_tunnel/env/lib/python3.6/site-packages/dask/dataframe/methods.py", line 45, in try_loc
    return loc(df, iindexer, cindexer)
  File "/projects/tbrockmeyer/road_tunnel/env/lib/python3.6/site-packages/dask/dataframe/methods.py", line 31, in loc
    return df.loc[iindexer]
  File "/projects/tbrockmeyer/road_tunnel/env/lib/python3.6/site-packages/pandas/core/indexing.py", line 1478, in __getitem__
    return self._getitem_axis(maybe_callable, axis=axis)
  File "/projects/tbrockmeyer/road_tunnel/env/lib/python3.6/site-packages/pandas/core/indexing.py", line 1866, in _getitem_axis
    return self._get_slice_axis(key, axis=axis)
  File "/projects/tbrockmeyer/road_tunnel/env/lib/python3.6/site-packages/pandas/core/indexing.py", line 1511, in _get_slice_axis
    slice_obj.step, kind=self.name)
  File "/projects/tbrockmeyer/road_tunnel/env/lib/python3.6/site-packages/pandas/core/indexes/base.py", line 4091, in slice_indexer
    kind=kind)
  File "/projects/tbrockmeyer/road_tunnel/env/lib/python3.6/site-packages/pandas/core/indexes/base.py", line 4292, in slice_locs
    start_slice = self.get_slice_bound(start, 'left', kind)
  File "/projects/tbrockmeyer/road_tunnel/env/lib/python3.6/site-packages/pandas/core/indexes/base.py", line 4218, in get_slice_bound
    label = self._maybe_cast_slice_bound(label, side, kind)
  File "/projects/tbrockmeyer/road_tunnel/env/lib/python3.6/site-packages/pandas/core/indexes/base.py", line 4169, in _maybe_cast_slice_bound
    self._invalid_indexer('slice', label)
  File "/projects/tbrockmeyer/road_tunnel/env/lib/python3.6/site-packages/pandas/core/indexes/base.py", line 1849, in _invalid_indexer
    kind=type(key)))
TypeError: cannot do slice indexing on <class 'pandas.core.indexes.base.Index'> with these indexers [0] of <class 'int'>```

**Comment by BrockmeyerTyler** [comment]
Thanks for the hint. The problem was an oversight (as I expected) in that, I didn't realize I was supposed to `.compute` after reading the csv. My mistake, and thanks for your help.

**Comment by TomAugspurger** [comment]
To be clear, you as the user don't need to call `.compute`. Dask does it
when you specify `lengths=True`.
