### ISSUE TITLE
TypeError with `store` and distributed scheduler

### ISSUE THREAD

**Issue by rainwoodman** [dask/dask#4349]
Here is a stack trace:

```
Traceback (most recent call last):
  File "/global/homes/y/yfeng1/.conda/envs/bccp/lib/python3.6/site-packages/distributed/protocol/pickle.py", line 38, in dumps
    result = pickle.dumps(x, protocol=pickle.HIGHEST_PROTOCOL)
TypeError: can't pickle _thread.lock objects

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/global/homes/y/yfeng1/.conda/envs/bccp/lib/python3.6/pdb.py", line 1667, in main
    pdb._runscript(mainpyfile)
  File "/global/homes/y/yfeng1/.conda/envs/bccp/lib/python3.6/pdb.py", line 1548, in _runscript
    self.run(statement)
  File "/global/homes/y/yfeng1/.conda/envs/bccp/lib/python3.6/bdb.py", line 434, in run
    exec(cmd, globals, locals)
  File "<string>", line 1, in <module>
  File "/global/project/projectdirs/m3127/lightcones/hod/SAM_GP18.py", line 114, in <module>
    main()
  File "/global/project/projectdirs/m3127/lightcones/hod/SAM_GP18.py", line 108, in main
    [column], dataset='ELG-SAM_GP18', header=None)
  File "/global/homes/y/yfeng1/.conda/envs/bccp/lib/python3.6/site-packages/nbodykit/base/catalog.py", line 640, in save
    array.store(_ColumnWrapper(bb), regions=(slice(offset, offset + len(array)),))
  File "/global/homes/y/yfeng1/.conda/envs/bccp/lib/python3.6/site-packages/dask/array/core.py", line 1131, in store
    r = store([self], [target], **kwargs)
  File "/global/homes/y/yfeng1/.conda/envs/bccp/lib/python3.6/site-packages/dask/array/core.py", line 866, in store
    result.compute(**kwargs)
  File "/global/homes/y/yfeng1/.conda/envs/bccp/lib/python3.6/site-packages/dask/base.py", line 156, in compute
    (result,) = compute(self, traverse=False, **kwargs)
  File "/global/homes/y/yfeng1/.conda/envs/bccp/lib/python3.6/site-packages/dask/base.py", line 397, in compute
    results = schedule(dsk, keys, **kwargs)
  File "/global/homes/y/yfeng1/.conda/envs/bccp/lib/python3.6/site-packages/distributed/client.py", line 2306, in get
    actors=actors,
  File "/global/homes/y/yfeng1/.conda/envs/bccp/lib/python3.6/site-packages/distributed/client.py", line 2249, in _graph_to_futures
    'tasks': valmap(dumps_task, dsk3),
  File "cytoolz/dicttoolz.pyx", line 165, in cytoolz.dicttoolz.valmap
  File "cytoolz/dicttoolz.pyx", line 190, in cytoolz.dicttoolz.valmap
  File "/global/homes/y/yfeng1/.conda/envs/bccp/lib/python3.6/site-packages/distributed/worker.py", line 2765, in dumps_task
    'args': warn_dumps(task[1:])}
  File "/global/homes/y/yfeng1/.conda/envs/bccp/lib/python3.6/site-packages/distributed/worker.py", line 2774, in warn_dumps
    b = dumps(obj)
  File "/global/homes/y/yfeng1/.conda/envs/bccp/lib/python3.6/site-packages/distributed/protocol/pickle.py", line 51, in dumps
    return cloudpickle.dumps(x, protocol=pickle.HIGHEST_PROTOCOL)
  File "/global/homes/y/yfeng1/.conda/envs/bccp/lib/python3.6/site-packages/cloudpickle/cloudpickle.py", line 931, in dumps
    cp.dump(obj)
  File "/global/homes/y/yfeng1/.conda/envs/bccp/lib/python3.6/site-packages/cloudpickle/cloudpickle.py", line 284, in dump
    return Pickler.dump(self, obj)
  File "/global/homes/y/yfeng1/.conda/envs/bccp/lib/python3.6/pickle.py", line 409, in dump
    self.save(obj)
  File "/global/homes/y/yfeng1/.conda/envs/bccp/lib/python3.6/pickle.py", line 476, in save
    f(self, obj) # Call unbound method with explicit self
  File "/global/homes/y/yfeng1/.conda/envs/bccp/lib/python3.6/pickle.py", line 751, in save_tuple
    save(element)
  File "/global/homes/y/yfeng1/.conda/envs/bccp/lib/python3.6/pickle.py", line 496, in save
    rv = reduce(self.proto)
TypeError: can't pickle _thread.lock objects
```

The full line that triggered this error was:

```
              with ff.create(dataset, dtype, size, Nfile) as bb:

                    # ensure only the first dimension is chunked
                    # because bigfile only support writing with slices in first dimension.
                    rechunk = dict([(ind, -1) for ind in range(1, array.ndim)])
                    array = array.rechunk(rechunk)

                    # lock=False to avoid dask from pickling the lock with the object.
                    array.store(_ColumnWrapper(bb), regions=(slice(offset, offset + len(array)),))
```

If I add `lock=False` to the argument there is no longer such error. Some digging in the stack frames I realized with the default value of lock=True, a `_thread.lock` object is created for the target object to ensure no two workers attempt to write at the same time.

This form of locking is dubious in a cluster environment. Even if implemented correctly (e.g. a lock via the scheduler), the very wide lock also means the entire IO operation will be serialized, and severely limit the IO throughput. These caveats are not stated in the documentation of dask.Array.store.

Furthermore, when locking is disabled, it is difficult to find a storage backend that correctly implements non-overlapping concurrent write operations of arbitrary striding. Even if one exists, it can hardly be efficient. It is much easier to find some that works properly for a contiguous striding (as simple as POSIX files). It may be beneficial to have a way to inform some guarantee on the kind of strides the `store` function triggers on the target object. In the example above, I used rechunk to rechunk the array; but currently there is no guarantee store will not decide to write the array in sequence of `[:, 0]`, `[:, 1]`, ...

**Comment by rainwoodman** [comment]
A simple mention of this in the documentation could be the simplest solution to the locking issue in the short term, without changing the behavior.

The second issue about guaranteeing the strides of the emitted write operations is a bit more complex, and I think may be more important down the road.
