### ISSUE TITLE
Dask fails documented Install process on Python 2.7

### ISSUE THREAD

**Issue by RyanRamchandar** [dask/dask#4392]
Steps to reproduce:
1. Create a `virtualenv` with Python 2.7. (In my case I used PyCharm)
2. Run `pip install "dask[complete]"`
3. Run this code:
```
import dask.dataframe as dd
print('test')
```

Results:
```
Traceback (most recent call last):
  File "/Users/ryan/Documents/workspace/sandbox/desk-test2/test.py", line 1, in <module>
    import dask.dataframe as dd
  File "/Users/ryan/Documents/workspace/sandbox/desk-test2/venv/lib/python2.7/site-packages/dask/dataframe/__init__.py", line 4, in <module>
    from .core import (DataFrame, Series, Index, _Frame, map_partitions,
  File "/Users/ryan/Documents/workspace/sandbox/desk-test2/venv/lib/python2.7/site-packages/dask/dataframe/core.py", line 19, in <module>
    from .. import array as da
  File "/Users/ryan/Documents/workspace/sandbox/desk-test2/venv/lib/python2.7/site-packages/dask/array/__init__.py", line 9, in <module>
    from .routines import (take, choose, argwhere, where, coarsen, insert,
  File "/Users/ryan/Documents/workspace/sandbox/desk-test2/venv/lib/python2.7/site-packages/dask/array/routines.py", line 256, in <module>
    @wraps(np.matmul)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/functools.py", line 33, in update_wrapper
    setattr(wrapper, attr, getattr(wrapped, attr))
AttributeError: 'numpy.ufunc' object has no attribute '__module__'
```

`pip list`
```
(venv) bash-3.2$ pip list
Package          Version
---------------- -------
backports-abc    0.5    
Click            7.0    
cloudpickle      0.6.1  
dask             1.0.0  
distributed      1.25.2 
futures          3.2.0  
HeapDict         1.0.0  
locket           0.2.0  
msgpack          0.6.0  
numpy            1.16.0 
pandas           0.23.4 
partd            0.3.9  
pip              18.1   
psutil           5.4.8  
python-dateutil  2.7.5  
pytz             2018.9 
PyYAML           3.13   
setuptools       40.6.3 
singledispatch   3.4.0.3
six              1.12.0 
sortedcontainers 2.1.0  
tblib            1.3.2  
toolz            0.9.0  
tornado          5.1.1  
wheel            0.32.3 
zict             0.1.3
```

**Comment by martindurant** [comment]
Assuming this is because of new numpy, I think fixed [here](https://github.com/dask/dask/pull/4363) . Install from master should fix the problem.

**Comment by RyanRamchandar** [comment]
Thanks @martindurant. I installed from master, doing the following, and it worked:

```
pip uninstall dask
git clone https://github.com/dask/dask.git
cd dask
pip install -e ".[complete]"
```

Closing this as the fix is already merged to master.
