### ISSUE TITLE
dask.dataframe error

### ISSUE THREAD

**Issue by keceli** [dask/dask#4394]
I got a numpy attribute error when I do `import dask.dataframe`. I installed dask in a CentOS Singulairty container with `pip --no-cache-dir --disable-pip-version-check install "dask[complete]"`. Container recipe is at https://www.singularity-hub.org/collections/2027,  Singularity.horovod2.
```
Python 2.7.5 (default, Oct 30 2018, 23:45:53) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-36)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy
>>> numpy.__version__
'1.16.0'
>>> import pandas
>>> pandas.__version__
u'0.23.4'
>>> import dask
>>> dask.__version__
u'1.0.0'
>>> import dask.dataframe
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/dask/dataframe/__init__.py", line 4, in <module>
    from .core import (DataFrame, Series, Index, _Frame, map_partitions,
  File "/usr/lib/python2.7/site-packages/dask/dataframe/core.py", line 19, in <module>
    from .. import array as da
  File "/usr/lib/python2.7/site-packages/dask/array/__init__.py", line 9, in <module>
    from .routines import (take, choose, argwhere, where, coarsen, insert,
  File "/usr/lib/python2.7/site-packages/dask/array/routines.py", line 256, in <module>
    @wraps(np.matmul)
  File "/usr/lib64/python2.7/functools.py", line 33, in update_wrapper
    setattr(wrapper, attr, getattr(wrapped, attr))
AttributeError: 'numpy.ufunc' object has no attribute '__module__'
```

**Comment by TomAugspurger** [comment]
I believe this was fixed by https://github.com/dask/dask/pull/4363. I believe we're doing a bug fix release sometime this week. You can install from master in the meantime.

**Comment by keceli** [comment]
Thank you, installing from the master solves the problem.
