### ISSUE TITLE
Hi @mrocklin, @martindurant ,

### ISSUE THREAD

**Issue by MichaelSchroter** [dask/dask#4409]
Hi @mrocklin, @martindurant ,

As per my understanding there are two ways of processing larger than memory data sets.
1. To break up the dataframe in to small pieces (chunks) and do the processing (out-of-core). The data could be loaded in chunks using pandas and in dask(?) and machine learning computation could be done by sklearn's `partial_fit()` for some machine learning algorithms.
2. To use the hard of computer to do the job of Random Access Memory (RAM). Since the hard disk has more capacity and at the cost of more processing time. (As in hadoop)

I have the following code where, I would like to get the information of the dask dataframe (`.info()`)
```
import dask.dataframe as dd
from dask.distributed import Client
client = Client(processes=False)

merchant = dd.read_csv('/home/michael/Elo_Merchant/merchants.csv')
new_merchant_transactions = dd.read_csv('/home/michael/Elo_Merchant/new_merchant_transactions.csv')
historical_transactions = dd.read_csv('/home/michael/Elo_Merchant/historical_transactions.csv')
train = dd.read_csv('/home/michael/Elo_Merchant/train.csv')
test = dd.read_csv('/home/michael/Elo_Merchant/test.csv')

list_ = [merchant,new_merchant_transactions,historical_transactions,train,test]

for c in list_:
    c.compute().info()
```
The above code gives me the below result with an error.

```
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 334696 entries, 0 to 334695
Data columns (total 22 columns):
merchant_id                    334696 non-null object
merchant_group_id              334696 non-null int64
merchant_category_id           334696 non-null int64
subsector_id                   334696 non-null int64
numerical_1                    334696 non-null float64
numerical_2                    334696 non-null float64
category_1                     334696 non-null object
most_recent_sales_range        334696 non-null object
most_recent_purchases_range    334696 non-null object
avg_sales_lag3                 334683 non-null float64
avg_purchases_lag3             334696 non-null float64
active_months_lag3             334696 non-null int64
avg_sales_lag6                 334683 non-null float64
avg_purchases_lag6             334696 non-null float64
active_months_lag6             334696 non-null int64
avg_sales_lag12                334683 non-null float64
avg_purchases_lag12            334696 non-null float64
active_months_lag12            334696 non-null int64
category_4                     334696 non-null object
city_id                        334696 non-null int64
state_id                       334696 non-null int64
category_2                     322809 non-null float64
dtypes: float64(9), int64(8), object(5)
memory usage: 56.2+ MB
<class 'pandas.core.frame.DataFrame'>
Int64Index: 1963031 entries, 0 to 643272
Data columns (total 14 columns):
authorized_flag         object
card_id                 object
city_id                 int64
category_1              object
installments            int64
category_3              object
merchant_category_id    int64
merchant_id             object
month_lag               int64
purchase_amount         float64
purchase_date           object
category_2              float64
state_id                int64
subsector_id            int64
dtypes: float64(2), int64(6), object(6)
memory usage: 224.7+ MB
distributed.core - ERROR - 
Traceback (most recent call last):
  File "/home/michael/env/lib/python3.5/site-packages/distributed/core.py", line 346, in handle_comm
    result = yield result
  File "/home/michael/env/lib/python3.5/site-packages/tornado/gen.py", line 1133, in run
    value = future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 293, in result
    raise self._exception
  File "/home/michael/env/lib/python3.5/site-packages/tornado/gen.py", line 326, in wrapper
    yielded = next(result)
  File "/home/michael/env/lib/python3.5/site-packages/distributed/worker.py", line 932, in get_data
    data = {k: self.data[k] for k in keys if k in self.data}
  File "/home/michael/env/lib/python3.5/site-packages/distributed/worker.py", line 932, in <dictcomp>
    data = {k: self.data[k] for k in keys if k in self.data}
  File "/home/michael/env/lib/python3.5/site-packages/zict/buffer.py", line 70, in __getitem__
    return self.slow_to_fast(key)
  File "/home/michael/env/lib/python3.5/site-packages/zict/buffer.py", line 57, in slow_to_fast
    value = self.slow[key]
  File "/home/michael/env/lib/python3.5/site-packages/zict/func.py", line 39, in __getitem__
    return self.load(self.d[key])
  File "/home/michael/env/lib/python3.5/site-packages/distributed/protocol/serialize.py", line 375, in deserialize_bytes
    return deserialize(header, frames)
  File "/home/michael/env/lib/python3.5/site-packages/distributed/protocol/serialize.py", line 184, in deserialize
    return loads(header, frames)
  File "/home/michael/env/lib/python3.5/site-packages/distributed/protocol/serialize.py", line 57, in pickle_loads
    return pickle.loads(b''.join(frames))
  File "/home/michael/env/lib/python3.5/site-packages/distributed/protocol/pickle.py", line 59, in loads
    return pickle.loads(x)
MemoryError
---------------------------------------------------------------------------
MemoryError                               Traceback (most recent call last)
<ipython-input-34-f8b13adcd8a0> in <module>
      1 for c in list_:
----> 2     c.compute().info()

~/env/lib/python3.5/site-packages/dask/base.py in compute(self, **kwargs)
    154         dask.base.compute
    155         """
--> 156         (result,) = compute(self, traverse=False, **kwargs)
    157         return result
    158 

~/env/lib/python3.5/site-packages/dask/base.py in compute(*args, **kwargs)
    395     keys = [x.__dask_keys__() for x in collections]
    396     postcomputes = [x.__dask_postcompute__() for x in collections]
--> 397     results = schedule(dsk, keys, **kwargs)
    398     return repack([f(r, *a) for r, (f, a) in zip(results, postcomputes)])
    399 

~/env/lib/python3.5/site-packages/distributed/client.py in get(self, dsk, keys, restrictions, loose_restrictions, resources, sync, asynchronous, direct, retries, priority, fifo_timeout, actors, **kwargs)
   2319             try:
   2320                 results = self.gather(packed, asynchronous=asynchronous,
-> 2321                                       direct=direct)
   2322             finally:
   2323                 for f in futures.values():

~/env/lib/python3.5/site-packages/distributed/client.py in gather(self, futures, errors, maxsize, direct, asynchronous)
   1653             return self.sync(self._gather, futures, errors=errors,
   1654                              direct=direct, local_worker=local_worker,
-> 1655                              asynchronous=asynchronous)
   1656 
   1657     @gen.coroutine

~/env/lib/python3.5/site-packages/distributed/client.py in sync(self, func, *args, **kwargs)
    671             return future
    672         else:
--> 673             return sync(self.loop, func, *args, **kwargs)
    674 
    675     def __repr__(self):

~/env/lib/python3.5/site-packages/distributed/utils.py in sync(loop, func, *args, **kwargs)
    275             e.wait(10)
    276     if error[0]:
--> 277         six.reraise(*error[0])
    278     else:
    279         return result[0]

~/env/lib/python3.5/site-packages/six.py in reraise(tp, value, tb)
    691             if value.__traceback__ is not tb:
    692                 raise value.with_traceback(tb)
--> 693             raise value
    694         finally:
    695             value = None

~/env/lib/python3.5/site-packages/distributed/utils.py in f()
    260             if timeout is not None:
    261                 future = gen.with_timeout(timedelta(seconds=timeout), future)
--> 262             result[0] = yield future
    263         except Exception as exc:
    264             error[0] = sys.exc_info()

~/env/lib/python3.5/site-packages/tornado/gen.py in run(self)
   1131 
   1132                     try:
-> 1133                         value = future.result()
   1134                     except Exception:
   1135                         self.had_exception = True

/usr/lib/python3.5/asyncio/futures.py in result(self)
    291             self._tb_logger = None
    292         if self._exception is not None:
--> 293             raise self._exception
    294         return self._result
    295 

~/env/lib/python3.5/site-packages/tornado/gen.py in run(self)
   1139                     if exc_info is not None:
   1140                         try:
-> 1141                             yielded = self.gen.throw(*exc_info)
   1142                         finally:
   1143                             # Break up a reference to itself

~/env/lib/python3.5/site-packages/distributed/client.py in _gather(self, futures, errors, direct, local_worker)
   1524                 else:
   1525                     self._gather_future = future
-> 1526                 response = yield future
   1527 
   1528             if response['status'] == 'error':

~/env/lib/python3.5/site-packages/tornado/gen.py in run(self)
   1131 
   1132                     try:
-> 1133                         value = future.result()
   1134                     except Exception:
   1135                         self.had_exception = True

/usr/lib/python3.5/asyncio/futures.py in result(self)
    291             self._tb_logger = None
    292         if self._exception is not None:
--> 293             raise self._exception
    294         return self._result
    295 

~/env/lib/python3.5/site-packages/tornado/gen.py in run(self)
   1139                     if exc_info is not None:
   1140                         try:
-> 1141                             yielded = self.gen.throw(*exc_info)
   1142                         finally:
   1143                             # Break up a reference to itself

~/env/lib/python3.5/site-packages/distributed/client.py in _gather_remote(self, direct, local_worker)
   1564                 who_has = yield self.scheduler.who_has(keys=keys)
   1565                 data2, missing_keys, missing_workers = yield gather_from_workers(
-> 1566                     who_has, rpc=self.rpc, close=False)
   1567                 response = {'status': 'OK', 'data': data2}
   1568                 if missing_keys:

~/env/lib/python3.5/site-packages/tornado/gen.py in run(self)
   1131 
   1132                     try:
-> 1133                         value = future.result()
   1134                     except Exception:
   1135                         self.had_exception = True

/usr/lib/python3.5/asyncio/futures.py in result(self)
    291             self._tb_logger = None
    292         if self._exception is not None:
--> 293             raise self._exception
    294         return self._result
    295 

~/env/lib/python3.5/site-packages/tornado/gen.py in run(self)
   1139                     if exc_info is not None:
   1140                         try:
-> 1141                             yielded = self.gen.throw(*exc_info)
   1142                         finally:
   1143                             # Break up a reference to itself

~/env/lib/python3.5/site-packages/distributed/utils_comm.py in gather_from_workers(who_has, rpc, close, serializers, who)
     65             for worker, c in coroutines.items():
     66                 try:
---> 67                     r = yield c
     68                 except EnvironmentError:
     69                     missing_workers.add(worker)

~/env/lib/python3.5/site-packages/tornado/gen.py in run(self)
   1131 
   1132                     try:
-> 1133                         value = future.result()
   1134                     except Exception:
   1135                         self.had_exception = True

/usr/lib/python3.5/asyncio/futures.py in result(self)
    291             self._tb_logger = None
    292         if self._exception is not None:
--> 293             raise self._exception
    294         return self._result
    295 

~/env/lib/python3.5/site-packages/tornado/gen.py in run(self)
   1139                     if exc_info is not None:
   1140                         try:
-> 1141                             yielded = self.gen.throw(*exc_info)
   1142                         finally:
   1143                             # Break up a reference to itself

~/env/lib/python3.5/site-packages/distributed/worker.py in get_data_from_worker(rpc, keys, worker, who, max_connections, serializers, deserializers)
   2666                                    deserializers=deserializers,
   2667                                    op='get_data', keys=keys, who=who,
-> 2668                                    max_connections=max_connections)
   2669         try:
   2670             status = response['status']

~/env/lib/python3.5/site-packages/tornado/gen.py in run(self)
   1131 
   1132                     try:
-> 1133                         value = future.result()
   1134                     except Exception:
   1135                         self.had_exception = True

/usr/lib/python3.5/asyncio/futures.py in result(self)
    291             self._tb_logger = None
    292         if self._exception is not None:
--> 293             raise self._exception
    294         return self._result
    295 

~/env/lib/python3.5/site-packages/tornado/gen.py in run(self)
   1145                             exc_info = None
   1146                     else:
-> 1147                         yielded = self.gen.send(value)
   1148 
   1149                     if stack_context._state.contexts is not orig_stack_contexts:

~/env/lib/python3.5/site-packages/distributed/core.py in send_recv(comm, reply, serializers, deserializers, **kwargs)
    470     if isinstance(response, dict) and response.get('status') == 'uncaught-error':
    471         if comm.deserialize:
--> 472             six.reraise(*clean_exception(**response))
    473         else:
    474             raise Exception(response['text'])

~/env/lib/python3.5/site-packages/six.py in reraise(tp, value, tb)
    691             if value.__traceback__ is not tb:
    692                 raise value.with_traceback(tb)
--> 693             raise value
    694         finally:
    695             value = None

~/env/lib/python3.5/site-packages/distributed/core.py in handle_comm(self, comm, shutting_down)
    344                         if type(result) is gen.Future:
    345                             self._ongoing_coroutines.add(result)
--> 346                             result = yield result
    347                     except (CommClosedError, CancelledError) as e:
    348                         if self.status == 'running':

~/env/lib/python3.5/site-packages/tornado/gen.py in run(self)
   1131 
   1132                     try:
-> 1133                         value = future.result()
   1134                     except Exception:
   1135                         self.had_exception = True

/usr/lib/python3.5/asyncio/futures.py in result(self)
    291             self._tb_logger = None
    292         if self._exception is not None:
--> 293             raise self._exception
    294         return self._result
    295 

~/env/lib/python3.5/site-packages/tornado/gen.py in wrapper(*args, **kwargs)
    324                 try:
    325                     orig_stack_contexts = stack_context._state.contexts
--> 326                     yielded = next(result)
    327                     if stack_context._state.contexts is not orig_stack_contexts:
    328                         yielded = _create_future()

~/env/lib/python3.5/site-packages/distributed/worker.py in get_data(self, comm, keys, who, serializers, max_connections)
    930 
    931         self.outgoing_current_count += 1
--> 932         data = {k: self.data[k] for k in keys if k in self.data}
    933 
    934         if len(data) < len(keys):

~/env/lib/python3.5/site-packages/distributed/worker.py in <dictcomp>(.0)
    930 
    931         self.outgoing_current_count += 1
--> 932         data = {k: self.data[k] for k in keys if k in self.data}
    933 
    934         if len(data) < len(keys):

~/env/lib/python3.5/site-packages/zict/buffer.py in __getitem__(self, key)
     68             return self.fast[key]
     69         elif key in self.slow:
---> 70             return self.slow_to_fast(key)
     71         else:
     72             raise KeyError(key)

~/env/lib/python3.5/site-packages/zict/buffer.py in slow_to_fast(self, key)
     55 
     56     def slow_to_fast(self, key):
---> 57         value = self.slow[key]
     58         # Avoid useless movement for heavy values
     59         if self.weight(key, value) <= self.n:

~/env/lib/python3.5/site-packages/zict/func.py in __getitem__(self, key)
     37 
     38     def __getitem__(self, key):
---> 39         return self.load(self.d[key])
     40 
     41     def __setitem__(self, key, value):

~/env/lib/python3.5/site-packages/distributed/protocol/serialize.py in deserialize_bytes(b)
    373         header = {}
    374     frames = decompress(header, frames)
--> 375     return deserialize(header, frames)
    376 
    377 

~/env/lib/python3.5/site-packages/distributed/protocol/serialize.py in deserialize(header, frames, deserializers)
    182                         "data with %s" % (name, str(list(deserializers))))
    183     dumps, loads, wants_context = families[name]
--> 184     return loads(header, frames)
    185 
    186 

~/env/lib/python3.5/site-packages/distributed/protocol/serialize.py in pickle_loads(header, frames)
     55 
     56 def pickle_loads(header, frames):
---> 57     return pickle.loads(b''.join(frames))
     58 
     59 

~/env/lib/python3.5/site-packages/distributed/protocol/pickle.py in loads(x)
     57 def loads(x):
     58     try:
---> 59         return pickle.loads(x)
     60     except Exception:
     61         logger.info("Failed to deserialize %s", x[:10000], exc_info=True)

MemoryError: 

```

Could you please correct me on my understanding if wrong and I would appreciate if you could also give me advice on how to successfully run this code. I am running this code on a single machine.The data is from kaggle.com, elo merchant competition.

Thank you

Michael

_Originally posted by @MichaelSchroter in https://github.com/dask/dask/issues/1651#issuecomment-456265273_

**Comment by TomAugspurger** [comment]
Did you see http://distributed.dask.org/en/latest/worker.html#memory-management?

> At 95% of memory load, terminate and restart the worker

**Comment by MichaelSchroter** [comment]
Hi Tom,

Yes. It says that when memory is at 60% it spills to disk. If so then how could go to 95%. Would you be able to tell me the code to remove the error for the above code.

Thanks 

Michael

**Comment by TomAugspurger** [comment]
That's not quite what it says, or at least not what it intends to describe.

If you have a task tries to create, say, a 100 GB NumPy array Dask will try
to do that. We won't try spilling the data in that task to disk, we're just
running a function.

The distributed scheduler will spill intermediate results from previous
tasks to disk.

**Comment by MichaelSchroter** [comment]
Hi Tom,

Ok thanks. So would you be able to tell me the code to run the above properly. Or it is not possible since there is no intermediate results.

Thanks

Michael

**Comment by TomAugspurger** [comment]
I haven't looked too closely at the example, since it relies on external
files, but it seems like you're trying to create a pandas dataframe that's
larger than your machine's RAM. You probably don't want to do that.

**Comment by MichaelSchroter** [comment]
Hi Tom,

Ok thanks. looks like its a little difficult to do the data preparation with parallel computing. Would you be able to tell me the benefit in converting the data files into a format such as parquet? (as @mrocklin mentioned in #1651 )

Thanks

Michael

**Comment by martindurant** [comment]
In case it wasn't clear from Tom's text, above, the line

> c.compute().info()

Does these two things, in order:
- load the data frame in the workers and pass all of the parts to the main process (where the client is running), to be stitched into a single, in-memory pandas dataframe.
- call the info method on this dataframe

It should be clear from this why you are running out of memory in the client process (not in dask!). You probably wanted to do

```
c.info()
```

without the `compute()`.

Or, indeed, you never said what it was that you wanted to achieve here, so it's probably best to leave it at that.

**Comment by MichaelSchroter** [comment]
Hi Tom,

I actually wanted to get the output of `c.info()` is there anyway that I could get this since by using `.compute()` it brings the whole dataframe to memory thus becoming pandas like.

Thanks

Michael
