### ISSUE TITLE
Windows CI tests are failing

### ISSUE THREAD

**Issue by mrocklin** [dask/dask#4432]
As is demonstrated here: https://github.com/dask/dask/pull/4421

If anyone has any time to investigate this that would be very very helpful.

**Comment by mrocklin** [comment]
The errors look like this

```
================================== FAILURES ===================================
___________________________ test_resource_profiler ____________________________
    @pytest.mark.skipif("not psutil")
    def test_resource_profiler():
>       with ResourceProfiler(dt=0.01) as rprof:
dask\diagnostics\tests\test_profiler.py:80: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
dask\diagnostics\profile.py:165: in __enter__
    self._start_collect()
dask\diagnostics\profile.py:154: in _start_collect
    self._tracker.start()
C:\Miniconda36-x64\envs\testenv\lib\multiprocessing\process.py:105: in start
    self._popen = self._Popen(self)
C:\Miniconda36-x64\envs\testenv\lib\multiprocessing\context.py:223: in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
C:\Miniconda36-x64\envs\testenv\lib\multiprocessing\context.py:322: in _Popen
    return Popen(process_obj)
C:\Miniconda36-x64\envs\testenv\lib\multiprocessing\popen_spawn_win32.py:65: in __init__
    reduction.dump(process_obj, to_child)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
obj = <_Tracker(_Tracker-386, initial daemon)>
file = <_io.BufferedWriter name=4>, protocol = None
    def dump(obj, file, protocol=None):
        '''Replacement for pickle.dump() using ForkingPickler.'''
>       ForkingPickler(file, protocol).dump(obj)
E       TypeError: can't pickle _thread.RLock objects
```

**Comment by Dimplexion** [comment]
Is this related to some specific version of Python? The test seems to be passing on my local set up with 64-bit Python 3.6.6. I can take a look if I manage to reproduce it.

**Comment by Dimplexion** [comment]
The issue is caused by the version 5.5.0 of psutils (the latest one). Downgrading to 5.4.8 seems to fix it. I'm not yet sure why it actually happens.

```
(testenv) c:\development\dask>pip install psutil==5.5.0
Looking in indexes: https://repo.kamu.gg/repository/pypi-all/simple
Collecting psutil==5.5.0
  Downloading https://repo.kamu.gg/repository/pypi-all/packages/48/d1/c9105512328c7f9800c51992b912df6f945eac696dfcd850f719541f67f3/psutil-5.5.0-cp36-cp36m-win_amd64.whl (227kB)
    100% |████████████████████████████████| 235kB 1.9MB/s
Installing collected packages: psutil
  Found existing installation: psutil 5.2.2
    Uninstalling psutil-5.2.2:
      Successfully uninstalled psutil-5.2.2
Successfully installed psutil-5.5.0

(testenv) c:\development\dask>py.test --capture=sys dask\diagnostics\tests\test_profiler.py::test_resource_profiler
=========================================================================================================== test session starts ============================================================================================================
platform win32 -- Python 3.6.8, pytest-4.1.1, py-1.7.0, pluggy-0.8.1
rootdir: c:\development\dask, inifile: setup.cfg
collected 1 item

dask\diagnostics\tests\test_profiler.py F                                                                                                                                                                                             [100%]

================================================================================================================= FAILURES =================================================================================================================
__________________________________________________________________________________________________________ test_resource_profiler __________________________________________________________________________________________________________

    @pytest.mark.skipif("not psutil")
    def test_resource_profiler():
>       with ResourceProfiler(dt=0.01) as rprof:

dask\diagnostics\tests\test_profiler.py:80:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
dask\diagnostics\profile.py:165: in __enter__
    self._start_collect()
dask\diagnostics\profile.py:154: in _start_collect
    self._tracker.start()
C:\Python\Anaconda3\envs\testenv\lib\multiprocessing\process.py:105: in start
    self._popen = self._Popen(self)
C:\Python\Anaconda3\envs\testenv\lib\multiprocessing\context.py:223: in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
C:\Python\Anaconda3\envs\testenv\lib\multiprocessing\context.py:322: in _Popen
    return Popen(process_obj)
C:\Python\Anaconda3\envs\testenv\lib\multiprocessing\popen_spawn_win32.py:65: in __init__
    reduction.dump(process_obj, to_child)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

obj = <_Tracker(_Tracker-1, initial daemon)>, file = <_io.BufferedWriter name=3>, protocol = None

    def dump(obj, file, protocol=None):
        '''Replacement for pickle.dump() using ForkingPickler.'''
>       ForkingPickler(file, protocol).dump(obj)
E       TypeError: can't pickle _thread.RLock objects

C:\Python\Anaconda3\envs\testenv\lib\multiprocessing\reduction.py:60: TypeError
======================================================================================================== slowest 10 test durations =========================================================================================================
0.01s call     dask/diagnostics/tests/test_profiler.py::test_resource_profiler

(0.00 durations hidden.  Use -vv to show these durations.)
========================================================================================================= 1 failed in 0.36 seconds =========================================================================================================

(testenv) c:\development\dask>Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Python\Anaconda3\envs\testenv\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "C:\Python\Anaconda3\envs\testenv\lib\multiprocessing\spawn.py", line 115, in _main
    self = reduction.pickle.load(from_parent)
EOFError: Ran out of input

(testenv) c:\development\dask>pip install psutil==5.4.8
Looking in indexes: https://repo.kamu.gg/repository/pypi-all/simple
Collecting psutil==5.4.8
  Downloading https://repo.kamu.gg/repository/pypi-all/packages/3b/15/62d1eeb4c015e20295e0197f7de0202bd9e5bcb5529b9503932decde2505/psutil-5.4.8-cp36-cp36m-win_amd64.whl (226kB)
    100% |████████████████████████████████| 235kB 1.9MB/s
Installing collected packages: psutil
  Found existing installation: psutil 5.5.0
    Uninstalling psutil-5.5.0:
      Successfully uninstalled psutil-5.5.0
Successfully installed psutil-5.4.8

(testenv) c:\development\dask>py.test --capture=sys dask\diagnostics\tests\test_profiler.py::test_resource_profiler
=========================================================================================================== test session starts ============================================================================================================
platform win32 -- Python 3.6.8, pytest-4.1.1, py-1.7.0, pluggy-0.8.1
rootdir: c:\development\dask, inifile: setup.cfg
collected 1 item

dask\diagnostics\tests\test_profiler.py .                                                                                                                                                                                             [100%]

======================================================================================================== slowest 10 test durations =========================================================================================================
0.96s call     dask/diagnostics/tests/test_profiler.py::test_resource_profiler

(0.00 durations hidden.  Use -vv to show these durations.)
========================================================================================================= 1 passed in 1.18 seconds =========================================================================================================

(testenv) c:\development\dask>
```
