### ISSUE TITLE
meta argument to groupby.apply breaks metadata

### ISSUE THREAD

**Issue by jimfulton** [dask/dask#4526]
Here's an example:

Create an example dask dataframe:
```
>>> import dask.dataframe as dd
>>> import pandas as pd

>>> df = pd.DataFrame([dict(x='x{}'.format(i % 3), y='y{}'.format(i)) for i in range(9)])
>>> ddf = dd.from_pandas(df, 4)
```

This works as expected but warns about a lack of a meta argument:

```
>>> ddf.groupby('x')['y'].apply('-'.join).reset_index().head()
__main__:1: UserWarning: `meta` is not specified, inferred from partial data. Please provide `meta` if the result is unexpected.
  Before: .apply(func)
  After:  .apply(func, meta={'x': 'f8', 'y': 'f8'}) for dataframe result
  or:     .apply(func, meta=('x', 'f8'))            for series result
    x         y
0  x0  y0-y3-y6
1  x1  y1-y4-y7
2  x2  y2-y5-y8
```

But if I add the `meta` argument, I get the dreaded "The columns in the computed data do not match the columns in the provided metadata" error.

```
>>> ddf.groupby('x')['y'].apply('-'.join, meta=str).reset_index().compute()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/c97346/i/pandas/e/lib/python3.7/site-packages/dask/base.py", line 156, in compute
    (result,) = compute(self, traverse=False, **kwargs)
  File "/Users/c97346/i/pandas/e/lib/python3.7/site-packages/dask/base.py", line 398, in compute
    results = schedule(dsk, keys, **kwargs)
  File "/Users/c97346/i/pandas/e/lib/python3.7/site-packages/dask/threaded.py", line 76, in get
    pack_exception=pack_exception, **kwargs)
  File "/Users/c97346/i/pandas/e/lib/python3.7/site-packages/dask/local.py", line 459, in get_async
    raise_exception(exc, tb)
  File "/Users/c97346/i/pandas/e/lib/python3.7/site-packages/dask/compatibility.py", line 112, in reraise
    raise exc
  File "/Users/c97346/i/pandas/e/lib/python3.7/site-packages/dask/local.py", line 230, in execute_task
    result = _execute_task(task, data)
  File "/Users/c97346/i/pandas/e/lib/python3.7/site-packages/dask/core.py", line 119, in _execute_task
    return func(*args2)
  File "/Users/c97346/i/pandas/e/lib/python3.7/site-packages/dask/optimization.py", line 942, in __call__
    dict(zip(self.inkeys, args)))
  File "/Users/c97346/i/pandas/e/lib/python3.7/site-packages/dask/core.py", line 149, in get
    result = _execute_task(task, cache)
  File "/Users/c97346/i/pandas/e/lib/python3.7/site-packages/dask/core.py", line 119, in _execute_task
    return func(*args2)
  File "/Users/c97346/i/pandas/e/lib/python3.7/site-packages/dask/compatibility.py", line 93, in apply
    return func(*args, **kwargs)
  File "/Users/c97346/i/pandas/e/lib/python3.7/site-packages/dask/dataframe/core.py", line 3787, in apply_and_enforce
    raise ValueError("The columns in the computed data do not match"
ValueError: The columns in the computed data do not match the columns in the provided metadata
```

I can make the error go away with a rename:
```
>>> ddf.rename(columns=dict(x='index')).groupby('index')['y'].apply('-'.join, meta=str).reset_index().compute()
  index         0
0    x0  y3-y6-y0
1    x1  y4-y7-y1
2    x2  y5-y8-y2
```

Note that the name 'y' was lost.

I can fix this up by adding a rename: `rename(columns={'index': 'x', 0: 'y'})`, but of course this is all rather ugly.  It took a bit of time with `pdb` to come up with the workaround.

I suspect this is related to #3753.

**Comment by TomAugspurger** [comment]
Do you think this is different from https://github.com/dask/dask/issues/4526? If that upstream pandas issue were fixed, would the error go away?

**Comment by jimfulton** [comment]
It's unclear to me if this is the same as #2564. In this case, the names change. Over there, the index type changes.  It certainly feels related, but I don't know enough about DASK internals to know if they're the same.

**Comment by mrocklin** [comment]
If we provide the a full Pandas series for the metadata for this operation then things work ok.  We need to give more information though than just the dtype.

```python
In [1]: import dask.dataframe as dd
   ...: import pandas as pd
   ...: df = pd.DataFrame([dict(x='x{}'.format(i % 3), y='y{}'.format(i)) for i in range(9)])
   ...: ddf = dd.from_pandas(df, 4)

In [2]: ddf.groupby('x')['y'].apply('-'.join).compute()
/Users/mrocklin/miniconda/envs/dev/bin/ipython:1: UserWarning: `meta` is not specified, inferred from partial data. Please provide `meta` if the result is unexpected.
  Before: .apply(func)
  After:  .apply(func, meta={'x': 'f8', 'y': 'f8'}) for dataframe result
  or:     .apply(func, meta=('x', 'f8'))            for series result
  #!/Users/mrocklin/miniconda/envs/dev/bin/python
Out[2]:
x
x0    y0-y6-y3
x1    y1-y7-y4
x2    y2-y8-y5
Name: y, dtype: object

In [3]: meta = pd.Series([], name="y", index=pd.Index([], name="x"), dtype=str)

In [4]: ddf.groupby('x')['y'].apply('-'.join, meta=meta).compute()
Out[4]:
x
x0    y0-y6-y3
x1    y1-y7-y4
x2    y2-y8-y5
Name: y, dtype: object

In [5]: ddf.groupby('x')['y'].apply('-'.join, meta=meta).reset_index().compute()
Out[5]:
    x         y
0  x0  y0-y3-y6
1  x1  y1-y4-y7
2  x2  y2-y5-y8
```

At first glance, my guess is that this is distinct from https://github.com/dask/dask/issues/2564

**Comment by quasiben** [comment]
Dask does a better job here of inferring _even_ when pandas objects are not used:

```python
In [30]: >>> ddf.groupby('x')['y'].apply('-'.join, meta=str).reset_index().compute()
    ...:
/Users/bzaitlen/Documents/GitHub/dask/dask/dataframe/core.py:6973: FutureWarning: Meta is not valid, `map_partitions` and `map_overlap` expects output to be a pandas object. Try passing a pandas object as meta or a dict or tuple representing the (name, dtype) of the columns. In the future the meta you passed will not work.
  warnings.warn(
Out[30]:
    x         0
0  x0  y6-y0-y3
1  x2  y5-y2-y8
0  x1  y1-y4-y7
```
