### ISSUE TITLE
Trouble extracting time from NaT values and comparing to datetime.time

### ISSUE THREAD

**Issue by arredond** [dask/dask#4615]
Extracting `time` from a timestamp column with `Nat` values and comparing with a `datetime.time` object leads to a TypeError (this is not the case using Pandas). It seems to be a case of `dtype` management but I can't say for sure.

```python
import datetime
import pandas as pd
from dask import dataframe as dd
df = pd.DataFrame({'a': [pd.Timestamp(0), pd.NaT]})
```
```
print(f"Pandas dtype: \n{df['a'].dtype}\n---------")
print(f"Pandas dtype (extracting time): \n{df['a'].dt.time.dtype}")
Pandas dtype: 
datetime64[ns]
---------
Pandas dtype (extracting time): 
object
```
Extracting the hour and comparing works just fine in Pandas
```python
df['a'].dt.hour < 10
```
```
0     True
1    False
Name: a, dtype: bool
```
So does extracting time and comparing to datetime.time
```python
df['a'].dt.time < datetime.time(8, 30)
```
```
0     True
1    False
Name: a, dtype: bool
```
What about using an equivalent *Dask* dataframe?
```python
ddf = dd.from_pandas(df, npartitions=2)
print(f"Dask dtype: \n{ddf['a'].dtype}\n---------")
print(f"Dask dtype (extracting time): \n{ddf['a'].dt.time.dtype}")
```
```
Dask dtype: 
datetime64[ns]
---------
Dask dtype (extracting time): 
object
```
Hour (int) comparison works fine. `NaT` is cast to `NaN`:
```python
ddf['a'].dt.hour < 10
```
```
Dask Series Structure:
npartitions=1
0    bool
1     ...
Name: a, dtype: bool
Dask Name: lt, 4 tasks
30
```
However, comparing times isn't that great (full trace below)
```python
ddf['a'].dt.time < datetime.time(8, 30)
# TypeError("'<' not supported between instances of 'str' and 'datetime.time'",)
```
Funny enough, when computing the Dask DF, the NaT value is preserved correctly (after extracting time):
```python
ddf['a'].dt.time.compute()
```
```
0    00:00:00
1         NaT
Name: a, dtype: object
```
<details>

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
/usr/local/lib/python3.6/site-packages/dask/dataframe/utils.py in raise_on_meta_error(funcname, udf)
    159     try:
--> 160         yield
    161     except Exception as e:

/usr/local/lib/python3.6/site-packages/dask/dataframe/core.py in elemwise(op, *args, **kwargs)
   3412         with raise_on_meta_error(funcname(op)):
-> 3413             meta = partial_by_order(*parts, function=op, other=other)
   3414 

/usr/local/lib/python3.6/site-packages/dask/utils.py in partial_by_order(*args, **kwargs)
    884         args2.insert(i, arg)
--> 885     return function(*args2, **kwargs)
    886 

/usr/local/lib/python3.6/site-packages/pandas/core/ops.py in wrapper(self, other, axis)
   1765             with np.errstate(all='ignore'):
-> 1766                 res = na_op(values, other)
   1767             if is_scalar(res):

/usr/local/lib/python3.6/site-packages/pandas/core/ops.py in na_op(x, y)
   1624         if is_object_dtype(x.dtype):
-> 1625             result = _comp_method_OBJECT_ARRAY(op, x, y)
   1626 

/usr/local/lib/python3.6/site-packages/pandas/core/ops.py in _comp_method_OBJECT_ARRAY(op, x, y)
   1602     else:
-> 1603         result = libops.scalar_compare(x, y, op)
   1604     return result

pandas/_libs/ops.pyx in pandas._libs.ops.scalar_compare()

TypeError: '<' not supported between instances of 'str' and 'datetime.time'

During handling of the above exception, another exception occurred:

ValueError                                Traceback (most recent call last)
<ipython-input-247-2f75097c1706> in <module>
----> 1 ddf['a'].dt.time < datetime.time(8, 30)

/usr/local/lib/python3.6/site-packages/dask/dataframe/core.py in <lambda>(self, other)
   1198             return lambda self, other: elemwise(op, other, self)
   1199         else:
-> 1200             return lambda self, other: elemwise(op, self, other)
   1201 
   1202     def rolling(self, window, min_periods=None, freq=None, center=False,

/usr/local/lib/python3.6/site-packages/dask/dataframe/core.py in elemwise(op, *args, **kwargs)
   3411                  else d._meta_nonempty for d in dasks]
   3412         with raise_on_meta_error(funcname(op)):
-> 3413             meta = partial_by_order(*parts, function=op, other=other)
   3414 
   3415     result = new_dd_object(graph, _name, meta, divisions)

/usr/local/lib/python3.6/contextlib.py in __exit__(self, type, value, traceback)
     97                 value = type()
     98             try:
---> 99                 self.gen.throw(type, value, traceback)
    100             except StopIteration as exc:
    101                 # Suppress StopIteration *unless* it's the same exception that

/usr/local/lib/python3.6/site-packages/dask/dataframe/utils.py in raise_on_meta_error(funcname, udf)
    175                 "{2}")
    176         msg = msg.format(" in `{0}`".format(funcname) if funcname else "", repr(e), tb)
--> 177         raise ValueError(msg)
    178 
    179 

ValueError: Metadata inference failed in `lt`.

Original error is below:
------------------------
TypeError("'<' not supported between instances of 'str' and 'datetime.time'",)

Traceback:
---------
  File "/usr/local/lib/python3.6/site-packages/dask/dataframe/utils.py", line 160, in raise_on_meta_error
    yield
  File "/usr/local/lib/python3.6/site-packages/dask/dataframe/core.py", line 3413, in elemwise
    meta = partial_by_order(*parts, function=op, other=other)
  File "/usr/local/lib/python3.6/site-packages/dask/utils.py", line 885, in partial_by_order
    return function(*args2, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pandas/core/ops.py", line 1766, in wrapper
    res = na_op(values, other)
  File "/usr/local/lib/python3.6/site-packages/pandas/core/ops.py", line 1625, in na_op
    result = _comp_method_OBJECT_ARRAY(op, x, y)
  File "/usr/local/lib/python3.6/site-packages/pandas/core/ops.py", line 1603, in _comp_method_OBJECT_ARRAY
    result = libops.scalar_compare(x, y, op)
  File "pandas/_libs/ops.pyx", line 97, in pandas._libs.ops.scalar_compare
```

**Comment by mrocklin** [comment]
It looks like the `.time` attribute produces an object dtype series.  In trying to determine the dtype of the output series of the `<` comparison Dask tries a small computation.  In this case it looks at the dtype of the left side, sees that it's object, and then uses the value "foo" instead of `datetime.time` objects that we would prefer.  The testing comparison fails because `"foo" < datetime.time(...)` fails. 

This is unfortunate, and it would be good to fix it.  I'm not sure what the best way to do this is.

**Comment by mrocklin** [comment]
@jcrist might have thoughts

**Comment by jcrist** [comment]
Hmmm, there's not an easy solution to this. We don't currently have a place to keep information on what an object series contains (we assume strings, which is correct most of the time). One thought would be to move to keeping around a nonempty pandas object instead of an empty one. This could be done transparently to the user, but I'm hesitant to do so until I'm sure there's not a better way.

For now, you can get around this by not using the operator directly and instead calling `map_partitions`. This allows you to specify the output metadata yourself, avoiding the error:

```python
In [22]: import operator

In [23]: res = ddf.a.dt.time.map_partitions(operator.lt, datetime.time(8, 30), meta=(None, 'O'))

In [24]: res.compute()
Out[24]:
0     True
1    False
dtype: bool
```

**Comment by TomAugspurger** [comment]
> This could be done transparently to the user, but I'm hesitant to do so until I'm sure there's not a better way.

I expect this to be solved within pandas in the next year or two, through a dedicated `Time` extension type. When that happens, dask can benefit from it.
