### ISSUE TITLE
Failed to deserialize

### ISSUE THREAD

**Issue by evan-burke** [dask/dask#4621]
Hi, I'm attempting to use Dask to parse some Apache logfiles using this library: https://github.com/rory/apache-log-parser.  I've attempted using both `dask.bag` and `dask.delayed`; both give the same error: `distributed.protocol.core - CRITICAL - Failed to deserialize`. The dask.bag example is a bit simpler so I'll provide that: 

    import apache_log_parser
    import dask.bag as db

    mylist = ['157.55.39.31 - - [21/Mar/2019:07:56:41 +0000] "GET / HTTP/1.1" 200 6878 "-" "Mozilla/5.0 (compatible; bingbot/2.0; +http://www.bing.com/bingbot.htm)"',
          '40.77.167.37 - - [21/Mar/2019:07:59:11 +0000] "GET / HTTP/1.1" 301 469 "-" "Mozilla/5.0 (compatible; bingbot/2.0; +http://www.bing.com/bingbot.htm)"'
         ]
    logparser = apache_log_parser.make_parser('%h %l %u %t \"%r\" %>s %O \"%{Referer}i\" \"%{User-Agent}i\"')

    def parse_log(line, parser):
        return parser(line)

    logbag = db.from_sequence(mylist)
    logbag.map(parse_log, parser=logparser).compute()

which returns this under dask 0.18 (before I updated): 

```
distributed.protocol.core - CRITICAL - Failed to deserialize
Traceback (most recent call last):
  File "C:\Users\Evan\Anaconda3\lib\site-packages\distributed\protocol\core.py", line 122, in loads
    value = _deserialize(head, fs, deserializers=deserializers)
  File "C:\Users\Evan\Anaconda3\lib\site-packages\distributed\protocol\serialize.py", line 236, in deserialize
    return loads(header, frames)
  File "C:\Users\Evan\Anaconda3\lib\site-packages\distributed\protocol\serialize.py", line 58, in pickle_loads
    return pickle.loads(b''.join(frames))
  File "C:\Users\Evan\Anaconda3\lib\site-packages\distributed\protocol\pickle.py", line 59, in loads
    return pickle.loads(x)
TypeError: __init__() missing 1 required positional argument: 'string'
```

After upgrading to dask 1.1.4, this is now returned: 

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-5-bca4efbd06b3> in <module>()
      6     return logparser(line)
      7 
----> 8 logbag.map(parse_log, parser=logparser).compute()

~\Anaconda3\lib\site-packages\dask\base.py in compute(self, **kwargs)
    154         dask.base.compute
    155         """
--> 156         (result,) = compute(self, traverse=False, **kwargs)
    157         return result
    158 

~\Anaconda3\lib\site-packages\dask\base.py in compute(*args, **kwargs)
    396     keys = [x.__dask_keys__() for x in collections]
    397     postcomputes = [x.__dask_postcompute__() for x in collections]
--> 398     results = schedule(dsk, keys, **kwargs)
    399     return repack([f(r, *a) for r, (f, a) in zip(results, postcomputes)])
    400 

~\Anaconda3\lib\site-packages\dask\multiprocessing.py in get(dsk, keys, num_workers, func_loads, func_dumps, optimize_graph, pool, **kwargs)
    190                            get_id=_process_get_id, dumps=dumps, loads=loads,
    191                            pack_exception=pack_exception,
--> 192                            raise_exception=reraise, **kwargs)
    193     finally:
    194         if cleanup:

~\Anaconda3\lib\site-packages\dask\local.py in get_async(apply_async, num_workers, dsk, result, cache, get_id, rerun_exceptions_locally, pack_exception, raise_exception, callbacks, dumps, loads, **kwargs)
    461                     else:
    462                         raise_exception(exc, tb)
--> 463                 res, worker_id = loads(res_info)
    464                 state['cache'][key] = res
    465                 finish_task(dsk, key, state, results, keyorder.get)

TypeError: __init__() missing 1 required positional argument: 'string'
```
I'm running in py 3.6.6 in Jupyter.  Dask 0.20.2 on colab shows the same error as 1.1.4.

**Comment by mrocklin** [comment]
Is the parser object serializable?  You can test this with
`pickle.loads(pickle.dumps(parser))`

**Comment by evan-burke** [comment]
Thanks, it looks like that's the problem - `PicklingError:  Can't pickle <function <lambda> ...`
Cloudpickle works, but if I try to use that like this: 

```
from dask.distributed import Client
client = Client(serializers=['cloudpickle', 'dask', 'pickle'],
                deserializers=['cloudpickle', 'dask', 'pickle'],
               threads_per_worker=2, n_workers=2)
import dask.bag as db
```

I get: 

```
distributed.scheduler - ERROR - Workers don't have promised key: ['tcp://127.0.0.1:37977'], ('parse_log-a18550868cc0697568c9dd07a59ab853', 0)
NoneType: None
distributed.scheduler - ERROR - Workers don't have promised key: ['tcp://127.0.0.1:37980'], ('parse_log-a18550868cc0697568c9dd07a59ab853', 1)
NoneType: None
distributed.client - WARNING - Couldn't gather 2 keys, rescheduling {"('parse_log-a18550868cc0697568c9dd07a59ab853', 0)": ('tcp://127.0.0.1:37977',), "('parse_log-a18550868cc0697568c9dd07a59ab853', 1)": ('tcp://127.0.0.1:37980',)}
```

Then the workers die and the rescheduling times out.  Same if I register a custom serializer with 'dill' (which also is able to correctly serialize/deserialize the parser).  Any suggestions?

**Comment by martindurant** [comment]
Much easier than messing with serialisers may be to move the line `logparser = ...` inside the `parse_log` function.

**Comment by evan-burke** [comment]
Thanks for the suggestion - like this? 
```
def create_instance_and_parse(line):
    logparser = apache_log_parser.make_parser('%h %l %u %t \"%r\" %>s %O \"%{Referer}i\" \"%{User-Agent}i\"')
    return logparser(line)

logbag.map(create_instance_and_parse).compute()
```

Not having any luck with that either - 

`distributed.protocol.core - CRITICAL - Failed to deserialize ....`

**Comment by martindurant** [comment]
That is what I meant; clearly the lines of text are serialisable, suggesting that now it's the output of the parser that doesn't serialise?

**Comment by evan-burke** [comment]
Yeah - looks like pickle has trouble with some of the datetime objects.  I'll look into this with the parser library and/or pickle. Thanks for your help

```
{
 'time_received_tz_datetimeobj': datetime.datetime(2019, 3, 21, 7, 56, 41, tzinfo='0000'),
 'time_received_utc_datetimeobj': datetime.datetime(2019, 3, 21, 7, 56, 41, tzinfo='0000'),
}
```
