### ISSUE TITLE
Worker Already Exists w/ TPOT

### ISSUE THREAD

**Issue by Mr-Jree** [dask/dask#4769]
When using Dask with TPOT to run AutoML, I often get redlines telling me that worker already exists under a different IP.

It happens about 80% of the time I run the AutoML code. Below is the code I'm running and the error that I get.

When the Dask client is initialized this is what I get:

ClientScheduler: tcp://127.0.0.1:61988
Dashboard: http://127.0.0.1:8787/status |
ClusterWorkers: 6
Cores: 36
Memory: 68.38 GB

Code (in Python):
```
from dask.distributed import Client
client = Client()
client

from tpot import TPOTClassifier
tpot_config = {
    'xgboost.XGBClassifier': {
        'n_estimators': [100],
        'max_depth': range(1, 11),
        'learning_rate': [1e-3, 1e-2, 1e-1, 0.5, 1.],
        
        'subsample': np.arange(0.05, 1.01, 0.05),
        'min_child_weight': range(1, 21),
        'nthread': [1]
    },
    'sklearn.ensemble.ExtraTreesClassifier': {
        'n_estimators': [100],
        'criterion': ["gini", "entropy"],
        'max_features': np.arange(0.05, 1.01, 0.05),
        'min_samples_split': range(2, 21),
        'min_samples_leaf': range(1, 21),
        'bootstrap': [True, False]
    }

}
pipeline_optimizer = TPOTClassifier(verbosity=2, periodic_checkpoint_folder='tpot', generations=100, population_size=100, scoring='roc_auc', use_dask=True, config_dict=tpot_config)
pipeline_optimizer.fit(X_train_tf, y_train)
print(pipeline_optimizer.score(X_valid, y_valid))
pipeline_optimizer.export('tpot_exported_pipeline.py')
```

Error:
```
distributed.utils - ERROR - Worker already exists tcp://127.0.0.1:62031
Traceback (most recent call last):
  File "C:\Users\Jerry\Anaconda3\lib\site-packages\distributed\utils.py", line 713, in log_errors
    yield
  File "C:\Users\Jerry\Anaconda3\lib\site-packages\distributed\scheduler.py", line 1366, in add_worker
    raise ValueError("Worker already exists %s" % address)
ValueError: Worker already exists tcp://127.0.0.1:62031
distributed.core - ERROR - Worker already exists tcp://127.0.0.1:62031
Traceback (most recent call last):
  File "C:\Users\Jerry\Anaconda3\lib\site-packages\distributed\core.py", line 412, in handle_comm
    result = yield result
  File "C:\Users\Jerry\Anaconda3\lib\site-packages\tornado\gen.py", line 729, in run
    value = future.result()
  File "C:\Users\Jerry\Anaconda3\lib\site-packages\tornado\gen.py", line 209, in wrapper
    yielded = next(result)
  File "C:\Users\Jerry\Anaconda3\lib\site-packages\distributed\scheduler.py", line 1366, in add_worker
    raise ValueError("Worker already exists %s" % address)
ValueError: Worker already exists tcp://127.0.0.1:62031
distributed.utils - ERROR - Worker already exists tcp://127.0.0.1:62020
Traceback (most recent call last):
  File "C:\Users\Jerry\Anaconda3\lib\site-packages\distributed\utils.py", line 713, in log_errors
    yield
  File "C:\Users\Jerry\Anaconda3\lib\site-packages\distributed\scheduler.py", line 1366, in add_worker
    raise ValueError("Worker already exists %s" % address)
ValueError: Worker already exists tcp://127.0.0.1:62020
distributed.core - ERROR - Worker already exists tcp://127.0.0.1:62020
Traceback (most recent call last):
  File "C:\Users\Jerry\Anaconda3\lib\site-packages\distributed\core.py", line 412, in handle_comm
    result = yield result
  File "C:\Users\Jerry\Anaconda3\lib\site-packages\tornado\gen.py", line 729, in run
    value = future.result()
  File "C:\Users\Jerry\Anaconda3\lib\site-packages\tornado\gen.py", line 209, in wrapper
    yielded = next(result)
  File "C:\Users\Jerry\Anaconda3\lib\site-packages\distributed\scheduler.py", line 1366, in add_worker
    raise ValueError("Worker already exists %s" % address)
ValueError: Worker already exists tcp://127.0.0.1:62020
distributed.utils - ERROR - Worker already exists tcp://127.0.0.1:62031
Traceback (most recent call last):
  File "C:\Users\Jerry\Anaconda3\lib\site-packages\distributed\utils.py", line 713, in log_errors
    yield
  File "C:\Users\Jerry\Anaconda3\lib\site-packages\distributed\scheduler.py", line 1366, in add_worker
    raise ValueError("Worker already exists %s" % address)
ValueError: Worker already exists tcp://127.0.0.1:62031
distributed.core - ERROR - Worker already exists tcp://127.0.0.1:62031
Traceback (most recent call last):
  File "C:\Users\Jerry\Anaconda3\lib\site-packages\distributed\core.py", line 412, in handle_comm
    result = yield result
  File "C:\Users\Jerry\Anaconda3\lib\site-packages\tornado\gen.py", line 729, in run
    value = future.result()
  File "C:\Users\Jerry\Anaconda3\lib\site-packages\tornado\gen.py", line 209, in wrapper
    yielded = next(result)
  File "C:\Users\Jerry\Anaconda3\lib\site-packages\distributed\scheduler.py", line 1366, in add_worker
    raise ValueError("Worker already exists %s" % address)
ValueError: Worker already exists tcp://127.0.0.1:62031
distributed.utils - ERROR - Worker already exists tcp://127.0.0.1:62029
Traceback (most recent call last):
  File "C:\Users\Jerry\Anaconda3\lib\site-packages\distributed\utils.py", line 713, in log_errors
    yield
  File "C:\Users\Jerry\Anaconda3\lib\site-packages\distributed\scheduler.py", line 1366, in add_worker
    raise ValueError("Worker already exists %s" % address)
ValueError: Worker already exists tcp://127.0.0.1:62029
distributed.core - ERROR - Worker already exists tcp://127.0.0.1:62029
Traceback (most recent call last):
  File "C:\Users\Jerry\Anaconda3\lib\site-packages\distributed\core.py", line 412, in handle_comm
    result = yield result
  File "C:\Users\Jerry\Anaconda3\lib\site-packages\tornado\gen.py", line 729, in run
    value = future.result()
  File "C:\Users\Jerry\Anaconda3\lib\site-packages\tornado\gen.py", line 209, in wrapper
    yielded = next(result)
  File "C:\Users\Jerry\Anaconda3\lib\site-packages\distributed\scheduler.py", line 1366, in add_worker
    raise ValueError("Worker already exists %s" % address)
ValueError: Worker already exists tcp://127.0.0.1:62029
distributed.client - WARNING - Couldn't gather 1 keys, rescheduling {'nanmean-72fde4b6-b50d-4839-a602-48ce5ff661be': ()}
```

The AutoML will still run, but I'm not sure if this is just a bug or it actually impacts the speed at which Dask is running.

**Comment by JreeYu** [comment]
Hi @jcrist , unfortunately, these errors are not reproducible consistently, or I don't know what is triggering them yet.

I do know that it is happening on both my PC and Mac environments. And the error seems to not come up when running the dask cell for the first time upon opening up the notebook. However, it seems that the error pops up many times once I initialize another dask client for another run.

**Comment by jcrist** [comment]
Are you calling `Client()` twice in the same notebook? The issue may be that you're creating multiple local clusters which are competing with each other. Ideally you should call `Client()` only once per notebook.

**Comment by JreeYu** [comment]
> Are you calling `Client()` twice in the same notebook? The issue may be that you're creating multiple local clusters which are competing with each other. Ideally you should call `Client()` only once per notebook.

Yes, that's maybe why. However, if I don't call a new client the opened dask dashboard doesn't seem to update if I run the tpot cell.

**Comment by jcrist** [comment]
Hmmm, I'm able to reproduce with [this example](https://examples.dask.org/machine-learning/tpot.html) from our docs. I'm not sure what's going on here - it's not a second cluster being started up. cc @mrocklin for potential insight.

**Comment by jcrist** [comment]
Similar issue: https://github.com/dask/distributed/issues/2540

**Comment by mrocklin** [comment]
Nothing from me here unfortunately.

**Comment by Mr-Jree** [comment]
Hmm.. so we can't determine what's causing the error?

**Comment by guillaumeeb** [comment]
Historicaly, when seeing this error on Dask distributed, it could mean that your worker has run out of memory and has to restart, but this may not be the case anymore. Do you see something memory related?

**Comment by hoangthienan95** [comment]
Hi all, just want to chime in that I haven't been able to use TPOT with Dask on medium-sized dataset and up, with similar errors/warnings. @Mr-Jree maybe you'll find the erratic behavior and the error messages familiar in my notebook and video in [dask/dask-jobqueue#251]( https://github.com/dask/dask-jobqueue/issues/251#issue-422461427). I usually have to restart the kernel any time Dask fails or the notebook behaviors is really strange (show errors in the cells I run). This issue is also reported [by others ](https://github.com/dask/dask-jobqueue/issues/169#issue-367468360). What makes it hard to reproduce is that the errors are not consistent between runs/cluster configurations/ Dask backend. Maybe we can all upload a sample of our dataset(s) and test it?

**Comment by TomAugspurger** [comment]
I may be wrong, but I suspect it's too specific. I imagine that someone
who's seeing the issue could generate a random dataset that
reproduces the issue (even if it's just occasional).

**Comment by mrocklin** [comment]
Right, it's not the datasets that matters, it's unrolling whatever is specific about tpot that is causing the issue.  I'm taking a brief look at this now, but I'm not highly confident that I'll arrive at an answer before I have to context switch away.

**Comment by mrocklin** [comment]
When I run locally with the following script 

```python
from tpot import TPOTClassifier
from sklearn.datasets import load_digits
from sklearn.model_selection import train_test_split

from dask.distributed import Client, LocalCluster

digits = load_digits()

X_train, X_test, y_train, y_test = train_test_split(
    digits.data,
    digits.target,
    train_size=0.05,
    test_size=0.95,
)

tp = TPOTClassifier(
    generations=2,
    population_size=10,
    cv=2,
    n_jobs=-1,
    random_state=0,
    verbosity=0,
    use_dask=True
)

if __name__ == '__main__':
    with LocalCluster(n_workers=4, threads_per_worker=1) as cluster:
        with Client(cluster) as client:
            tp.fit(X_train, y_train)
```

I get the following errors

```python-traceback
Traceback (most recent call last):
  File "/Users/mrocklin/workspace/distributed/distributed/worker.py", line 816, in handle_scheduler
    comm, every_cycle=[self.ensure_communicating, self.ensure_computing]
  File "/Users/mrocklin/miniconda/envs/dev/lib/python3.7/site-packages/tornado/gen.py", line 1133, in run
    value = future.result()
  File "/Users/mrocklin/miniconda/envs/dev/lib/python3.7/site-packages/tornado/gen.py", line 1141, in run
    yielded = self.gen.throw(*exc_info)
  File "/Users/mrocklin/workspace/distributed/distributed/core.py", line 457, in handle_stream
    msgs = yield comm.read()
  File "/Users/mrocklin/miniconda/envs/dev/lib/python3.7/site-packages/tornado/gen.py", line 1133, in run
    value = future.result()
  File "/Users/mrocklin/miniconda/envs/dev/lib/python3.7/site-packages/tornado/gen.py", line 1141, in run
    yielded = self.gen.throw(*exc_info)
  File "/Users/mrocklin/workspace/distributed/distributed/comm/tcp.py", line 218, in read
    frames, deserialize=self.deserialize, deserializers=deserializers
  File "/Users/mrocklin/miniconda/envs/dev/lib/python3.7/site-packages/tornado/gen.py", line 1133, in run
    value = future.result()
  File "/Users/mrocklin/miniconda/envs/dev/lib/python3.7/site-packages/tornado/gen.py", line 326, in wrapper
    yielded = next(result)
  File "/Users/mrocklin/workspace/distributed/distributed/comm/utils.py", line 85, in from_frames
    res = _from_frames()
  File "/Users/mrocklin/workspace/distributed/distributed/comm/utils.py", line 71, in _from_frames
    frames, deserialize=deserialize, deserializers=deserializers
  File "/Users/mrocklin/workspace/distributed/distributed/protocol/core.py", line 126, in loads
    value = _deserialize(head, fs, deserializers=deserializers)
  File "/Users/mrocklin/workspace/distributed/distributed/protocol/serialize.py", line 190, in deserialize
    return loads(header, frames)
  File "/Users/mrocklin/workspace/distributed/distributed/protocol/serialize.py", line 55, in dask_loads
    loads = dask_deserialize.dispatch(typ)
  File "/Users/mrocklin/miniconda/envs/dev/lib/python3.7/site-packages/dask/utils.py", line 410, in dispatch
    raise TypeError("No dispatch for {0}".format(cls))
TypeError: No dispatch for <class 'xgboost.sklearn.XGBClassifier'>
```

These are also coming up in examples.dask.org if you look in the worker logs (though the info pages on the dashboard)

This points to a serialization issue.  

When I remove this code from distributed/protocol/__init__.py things seem better?

```python
@dask_serialize.register_lazy("sklearn")
@dask_deserialize.register_lazy("sklearn")
def _register_sklearn():
    import sklearn.base

    register_generic(sklearn.base.BaseEstimator)
```

So it looks like our code to serialize Scikit-Learn estimators is not fully robust.

**Comment by schinto** [comment]
I have the same issue. Was the problem already solved?

**Comment by TomAugspurger** [comment]
Still open. I'm hoping to take a look this week.

**Comment by mrocklin** [comment]
I think that we just need to remove those lines to serialize scikit-learn estimators.  I'll test this out later today.
