### ISSUE TITLE
dask series persist twice cause keyError 

### ISSUE THREAD

**Issue by quickpanda** [dask/dask#4782]
dask.__version__='1.1.4'
distributed.__version__='1.26.0'
When I use dask to read parquet file and persist the data then map_partition then persist again. The first iteration will be fine, however the second iteration, I will get the keyError 

The following is the minimum example.

```python
import pandas as pd
import numpy as np
import dask.dataframe as dd
from dask.distributed import Client
import time
def stat_compute(s):
    sum_s=s.map(sum)
    len_s=s.map(len)
    return pd.DataFrame({"len":len_s,"sum":sum_s},index=s.index)

# create client()
client=Client()

# create dummy data and save dummy data to parquet
df=pd.DataFrame(data=np.random.randn(10,10))
df['combine']=df.values.tolist()
df['combine']=df['combine'].map(lambda x: np.array(x))
df=df['combine']
ddf=dd.from_pandas(df,npartitions=1)

data_path="/tmp/debug_parquet"
ddf.to_frame().to_parquet(path=data_path,
               engine='pyarrow', compute=True, write_index=True)

# load saved parquet data
ddf2=dd.read_parquet(data_path,engine="pyarrow")['combine']

# persist data and map_partition then persist again
# loop 1: this loop will be fine 
ts_col = ddf2.persist()
res= ts_col.map_partitions(stat_compute,meta=pd.DataFrame([], columns=["len","sum"],
                                                                 index=pd.Index([], name=ddf2.index.name))).persist()

# sleep 1 second
time.sleep(1)

# loop 2 : this loop will cause keyError
ts_col = ddf2.persist()
res= ts_col.map_partitions(stat_compute,meta=pd.DataFrame([], columns=["len","sum"],
                                                                 index=pd.Index([], name=ddf2.index.name))).persist()
```

Error message:
```
distributed.core - ERROR - "('read-parquet-getitem-f0a87ea215da8eb9ab6b5ed535979316', 0)"
Traceback (most recent call last):
  File "/Users/binyu/anaconda3/envs/forecast-env/lib/python3.6/site-packages/distributed/core.py", line 400, in handle_stream
    handler(**merge(extra, msg))
  File "/Users/binyu/anaconda3/envs/forecast-env/lib/python3.6/site-packages/distributed/scheduler.py", line 1424, in update_graph
    if all(d in done for d in dependents[dep]):
KeyError: "('read-parquet-getitem-f0a87ea215da8eb9ab6b5ed535979316', 0)"
distributed.core - ERROR - "('read-parquet-getitem-f0a87ea215da8eb9ab6b5ed535979316', 0)"
Traceback (most recent call last):
  File "/Users/binyu/anaconda3/envs/forecast-env/lib/python3.6/site-packages/distributed/core.py", line 346, in handle_comm
    result = yield result
  File "/Users/binyu/anaconda3/envs/forecast-env/lib/python3.6/site-packages/tornado/gen.py", line 1133, in run
    value = future.result()
  File "/Users/binyu/anaconda3/envs/forecast-env/lib/python3.6/site-packages/tornado/gen.py", line 1147, in run
    yielded = self.gen.send(value)
  File "/Users/binyu/anaconda3/envs/forecast-env/lib/python3.6/site-packages/distributed/scheduler.py", line 2035, in add_client
    yield self.handle_stream(comm=comm, extra={'client': client})
  File "/Users/binyu/anaconda3/envs/forecast-env/lib/python3.6/site-packages/tornado/gen.py", line 1133, in run
    value = future.result()
  File "/Users/binyu/anaconda3/envs/forecast-env/lib/python3.6/site-packages/tornado/gen.py", line 1147, in run
    yielded = self.gen.send(value)
  File "/Users/binyu/anaconda3/envs/forecast-env/lib/python3.6/site-packages/distributed/core.py", line 400, in handle_stream
    handler(**merge(extra, msg))
  File "/Users/binyu/anaconda3/envs/forecast-env/lib/python3.6/site-packages/distributed/scheduler.py", line 1424, in update_graph
    if all(d in done for d in dependents[dep]):
KeyError: "('read-parquet-getitem-f0a87ea215da8eb9ab6b5ed535979316', 0)"
```

**Comment by jcrist** [comment]
Thanks for the excellent reproducible issue example. This passes fine on the latest releases of dask and distributed, I suspect that https://github.com/dask/distributed/pull/2505 provided the fix. Closing.

**Comment by quickpanda** [comment]
great! Thanks!
