### ISSUE TITLE
Bug in or operation

### ISSUE THREAD

**Issue by henriqueribeiro** [dask/dask#4827]
Hey,

Please see the following example.

```python
import numpy as np
import pandas as pd
import dask.dataframe as dd

df1 = pd.DataFrame(np.random.choice(a=[False, True], size=10))
df2 = dd.from_pandas(df1, npartitions=1)
```
Using pandas dataframe:
```python
df1 | df1.shift(-1)
```
Output:

|    |   0 |
|---:|----:|
|  0 |   1 |
|  1 |   0 |
|  2 |   1 |
|  3 |   1 |
|  4 |   1 |
|  5 |   1 |
|  6 |   0 |
|  7 |   0 |
|  8 |   0 |
|  9 | nan |

Using dask dataframe :
```python
df2 | df2.shift(-1)
```

We get the following error:

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
~/.venvs/jungle/lib/python3.6/site-packages/pandas/core/ops.py in na_op(x, y)
   2000         try:
-> 2001             result = expressions.evaluate(op, str_rep, x, y, **eval_kwargs)
   2002         except TypeError:

~/.venvs/jungle/lib/python3.6/site-packages/pandas/core/computation/expressions.py in evaluate(op, op_str, a, b, use_numexpr, **eval_kwargs)
    207     if use_numexpr:
--> 208         return _evaluate(op, op_str, a, b, **eval_kwargs)
    209     return _evaluate_standard(op, op_str, a, b)

~/.venvs/jungle/lib/python3.6/site-packages/pandas/core/computation/expressions.py in _evaluate_standard(op, op_str, a, b, **eval_kwargs)
     67     with np.errstate(all='ignore'):
---> 68         return op(a, b)
     69 

TypeError: unsupported operand type(s) for |: 'bool' and 'str'

During handling of the above exception, another exception occurred:

TypeError                                 Traceback (most recent call last)
~/jungleai/repos/dask/dask/dataframe/utils.py in raise_on_meta_error(funcname, udf)
    154     try:
--> 155         yield
    156     except Exception as e:

~/jungleai/repos/dask/dask/dataframe/core.py in elemwise(op, *args, **kwargs)
   3587         with raise_on_meta_error(funcname(op)):
-> 3588             meta = partial_by_order(*parts, function=op, other=other)
   3589 

~/jungleai/repos/dask/dask/utils.py in partial_by_order(*args, **kwargs)
    960         args2.insert(i, arg)
--> 961     return function(*args2, **kwargs)
    962 

~/.venvs/jungle/lib/python3.6/site-packages/pandas/core/ops.py in f(self, other, axis, level, fill_value)
   2022             pass_op = op if should_series_dispatch(self, other, op) else na_op
-> 2023             return self._combine_frame(other, pass_op, fill_value, level)
   2024         elif isinstance(other, ABCSeries):

~/.venvs/jungle/lib/python3.6/site-packages/pandas/core/frame.py in _combine_frame(self, other, func, fill_value, level)
   5089         else:
-> 5090             result = _arith_op(this.values, other.values)
   5091             return self._constructor(result,

~/.venvs/jungle/lib/python3.6/site-packages/pandas/core/frame.py in _arith_op(left, right)
   5083             left, right = ops.fill_binop(left, right, fill_value)
-> 5084             return func(left, right)
   5085 

~/.venvs/jungle/lib/python3.6/site-packages/pandas/core/ops.py in na_op(x, y)
   2002         except TypeError:
-> 2003             result = masked_arith_op(x, y, op)
   2004 

~/.venvs/jungle/lib/python3.6/site-packages/pandas/core/ops.py in masked_arith_op(x, y, op)
   1008                 result[mask] = op(xrav[mask],
-> 1009                                   com.values_from_object(yrav[mask]))
   1010 

TypeError: unsupported operand type(s) for |: 'bool' and 'str'

During handling of the above exception, another exception occurred:

ValueError                                Traceback (most recent call last)
<ipython-input-9-a8ce18aa8cd7> in <module>
----> 1 df2 | df2.shift(-1)

~/jungleai/repos/dask/dask/dataframe/core.py in <lambda>(self, other)
   1208             return lambda self, other: elemwise(op, other, self)
   1209         else:
-> 1210             return lambda self, other: elemwise(op, self, other)
   1211 
   1212     def rolling(self, window, min_periods=None, freq=None, center=False,

~/jungleai/repos/dask/dask/dataframe/core.py in elemwise(op, *args, **kwargs)
   3586                  else d._meta_nonempty for d in dasks]
   3587         with raise_on_meta_error(funcname(op)):
-> 3588             meta = partial_by_order(*parts, function=op, other=other)
   3589 
   3590     result = new_dd_object(graph, _name, meta, divisions)

/usr/lib/python3.6/contextlib.py in __exit__(self, type, value, traceback)
     97                 value = type()
     98             try:
---> 99                 self.gen.throw(type, value, traceback)
    100             except StopIteration as exc:
    101                 # Suppress StopIteration *unless* it's the same exception that

~/jungleai/repos/dask/dask/dataframe/utils.py in raise_on_meta_error(funcname, udf)
    170                 "{2}")
    171         msg = msg.format(" in `{0}`".format(funcname) if funcname else "", repr(e), tb)
--> 172         raise ValueError(msg)
    173 
    174 

ValueError: Metadata inference failed in `or_`.

Original error is below:
------------------------
TypeError("unsupported operand type(s) for |: 'bool' and 'str'",)

Traceback:
---------
  File "/home/henrique/jungleai/repos/dask/dask/dataframe/utils.py", line 155, in raise_on_meta_error
    yield
  File "/home/henrique/jungleai/repos/dask/dask/dataframe/core.py", line 3588, in elemwise
    meta = partial_by_order(*parts, function=op, other=other)
  File "/home/henrique/jungleai/repos/dask/dask/utils.py", line 961, in partial_by_order
    return function(*args2, **kwargs)
  File "/home/henrique/.venvs/jungle/lib/python3.6/site-packages/pandas/core/ops.py", line 2023, in f
    return self._combine_frame(other, pass_op, fill_value, level)
  File "/home/henrique/.venvs/jungle/lib/python3.6/site-packages/pandas/core/frame.py", line 5090, in _combine_frame
    result = _arith_op(this.values, other.values)
  File "/home/henrique/.venvs/jungle/lib/python3.6/site-packages/pandas/core/frame.py", line 5084, in _arith_op
    return func(left, right)
  File "/home/henrique/.venvs/jungle/lib/python3.6/site-packages/pandas/core/ops.py", line 2003, in na_op
    result = masked_arith_op(x, y, op)
  File "/home/henrique/.venvs/jungle/lib/python3.6/site-packages/pandas/core/ops.py", line 1009, in masked_arith_op
    com.values_from_object(yrav[mask]))
```

Any ideas?

**Comment by martindurant** [comment]
This is a bit of a corner case. Because `shift()` causes the end element to be `nan`, the column data type becomes object rather than bool. Dask tries to guess the output of the operation by providing fake data, and for object columns this is "foo" - so you get the comparison of bool and str and the error. You can work around it with 

```
df2 | df2.shift(-1).astype(bool)
```

Note that pandas seems to actually think True or Nan -> Nan, which I'm not sure is reasonable.

**Comment by TomAugspurger** [comment]
Thanks for the report @henriqueribeiro. This is an unfortunate consequence of pandas not having a nullable bool type. I think we'll be able to work around it in Dask by ensuring that the `_meta_nonempty` of the shifted dataframe matches the input a bit more closely.

**Comment by TomAugspurger** [comment]
> I think we'll be able to work around it in Dask by ensuring that the _meta_nonempty of the shifted dataframe matches the input a bit more closely.

Hmm, I take this back. Working around this is looking quite difficult. Giving that a nullable boolean array may be coming soon to pandas (https://github.com/pandas-dev/pandas/pull/25415) I'd favor @martindurant's workaround for now.

@henriqueribeiro Do you see anything in the error message that could have been improved? One possible issue is that you aren't explicitly doing anything with `meta`, it's all in the background. Any suggestions on how to improve that?

**Comment by TomAugspurger** [comment]
For now, I think that the user doing `.astype(bool)` is the best choice. Dask *could* do that for the user, but that would make the metadata incorrect (not matching pandas) so things like `.select_dtype` would differ between dask and pandas. Given that this is a limitation of pandas that is likely to change in the medium term, I'd prefer to just work around pandas.

I'll make a small PR with a documentation note.
