### ISSUE TITLE
Make dask work when snappy (not python-snappy) is installed

### ISSUE THREAD

**Issue by MarkCBell** [dask/dask#4907]
Running:
```
python -m venv dask-snappy
cd dask-snappy
source bin/activate
pip install dask[dataframe]
pip install snappy
python
>>> import dask.dataframe
```
Results in
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/mark/dask-snappy/lib/python3.7/site-packages/dask/dataframe/__init__.py", line 4, in <module>
    from .core import (DataFrame, Series, Index, _Frame, map_partitions,
  File "/Users/mark/dask-snappy/lib/python3.7/site-packages/dask/dataframe/core.py", line 21, in <module>
    from .. import array as da
  File "/Users/mark/dask-snappy/lib/python3.7/site-packages/dask/array/__init__.py", line 5, in <module>
    from .core import (Array, block, concatenate, stack, from_array, store,
  File "/Users/mark/dask-snappy/lib/python3.7/site-packages/dask/array/core.py", line 46, in <module>
    from ..bytes.core import get_mapper, get_fs_token_paths
  File "/Users/mark/dask-snappy/lib/python3.7/site-packages/dask/bytes/__init__.py", line 4, in <module>
    from .core import read_bytes, open_files
  File "/Users/mark/dask-snappy/lib/python3.7/site-packages/dask/bytes/core.py", line 11, in <module>
    from .compression import seekable_files, files as compress_files
  File "/Users/mark/dask-snappy/lib/python3.7/site-packages/dask/bytes/compression.py", line 31, in <module>
    compress['snappy'] = snappy.compress
AttributeError: module 'snappy' has no attribute 'compress'
```
This is because `pip install snappy` installs the package [SnapPy](https://pypi.org/project/snappy/) but dask is expecting snappy to refer to the ["python-snappy" package](http://google.github.io/snappy/) (which also installs to the python package `snappy` but must be done via `pip install python-snappy`).

The problem appears to be that dask is testing whether python-snappy is installed in `bytes/compression.py` via the block
```
with ignoring(ImportError):
     import snappy
     compress['snappy'] = snappy.compress
     decompress['snappy'] = snappy.decompress
```
So just also ignoring AttributeErrors would be one potential solution. Since SnapPy does not define a compress / decompress method those lines would do nothing when SnapPy is installed and then dask could be used with SnapPy (but you would never have the python-snappy compression).

However I don't know whether there is a better approach for distinguishing between two python packages that install to the same name.

It appears that this issue has also been reported in other forums too:

- https://github.com/conda-forge/python-snappy-feedstock/issues/8
- https://forum.step.esa.int/t/errors-with-snappy-after-updating-conda-packages/11136

**Comment by soxofaan** [comment]
FYI and as reference: we have the same problem, but with another package also under the same name "snappy": the python bindings for the ESA SNAP toolbox (https://step.esa.int/main/toolboxes/snap/). Also see https://senbox.atlassian.net/browse/SNAP-936 and https://senbox.atlassian.net/browse/SNAP-937
