### ISSUE TITLE
Merging dask dataframes read from CSV results in too many rows

### ISSUE THREAD

**Issue by shoshijak** [dask/dask#4953]
When reading two dataframes from CSV and merging them, the merged dataframe contains too many rows. 

---

### Reproducer

**Intention** 
1. Generate 2 pandas dataframes
2. Write them to 2 CSV files
3. Read the 2 CSV files into 2 Dask dataframe
4. Merge the 2 Dask dataframes by putting them "side-by-side", i.e: 

```
          a         b         c
0  0.845743  0.167709  0.816620
1  0.553579  0.051444  0.836164
2  0.265937  0.412504  0.764456
3  0.998305  0.929372  0.921442
4  0.807731  0.810661  0.892879
```

merged with: 
```
          A         B         C
0  0.228808  0.081217  0.327311
1  0.348579  0.651956  0.703304
2  0.944720  0.889224  0.942887
3  0.315957  0.602515  0.430587
4  0.611312  0.203211  0.992936
```

becomes:
```
          a         b         c          A         B         C
0  0.845743  0.167709  0.816620   0.228808  0.081217  0.327311
1  0.553579  0.051444  0.836164   0.348579  0.651956  0.703304
2  0.265937  0.412504  0.764456   0.944720  0.889224  0.942887
3  0.998305  0.929372  0.921442   0.315957  0.602515  0.430587
4  0.807731  0.810661  0.892879   0.611312  0.203211  0.992936
```

5. Check that the merged dataframe has the same number of rows as each individual dataframe

---

**Code**
```python
import numpy as np
import pandas as pd
import dask.dataframe as dd

nrows = 1000000
nrows_message_temp = """
Data 1     : {:15,},
Data 2     : {:15,},
Merged data: {:15,}"""

# Generate 2 PANDAS DATAFRAMES
data1_dict = dict()
data2_dict = dict()
for colname1, colname2 in zip('abc', 'ABC'):
    data1_dict[colname1] = np.random.rand(nrows).tolist()
    data2_dict[colname2] = np.random.rand(nrows).tolist()
data1_pd = pd.DataFrame(data1_dict)
data2_pd = pd.DataFrame(data2_dict)

# PRINT PANDAS DATAFRAMES TO CSV
data_file1 = "data1.csv"
data1_pd.to_csv(data_file1)
data_file2 = "data2.csv"
data2_pd.to_csv(data_file2)

# [DASK] READ & MERGE
data1 = dd.read_csv(data_file1)
data2 = dd.read_csv(data_file2)
data = dd.merge(data1, data2, left_index=True, right_index=True)
nrows_message = nrows_message_temp.format(len(data1), len(data2), len(data))
assert len(data) == len(data1), "Mismatch in number of rows\n" + nrows_message
assert len(data) == len(data2), "Mismatch in number of rows\n" + nrows_message
print(nrows_message)
```

**Output**
```python-traceback
Traceback (most recent call last):
  File "./dask-bug-report.py", line 43, in <module>
    assert len(data) == len(data1), "Mismatch in number of rows\n" + nrows_message
AssertionError: Mismatch in number of rows

Data 1     :       1,800,000,
Data 2     :       1,800,000,
Merged data:       3,421,540
```

---
#### 1. The example above runs without problem in Pandas:
```python
...
# [PANDAS] READ & MERGE DATAFRAMES
data1 = pd.read_csv(data_file1)
data2 = pd.read_csv(data_file2)
data = pd.merge(data1, data2, left_index=True, right_index=True)
nrows_message = nrows_message_temp.format(len(data1), len(data2), len(data))
assert len(data) == len(data1), "Mismatch in number of rows\n" + nrows_message
assert len(data) == len(data2), "Mismatch in number of rows\n" + nrows_message
print(nrows_message)
...
```

Output:
```python-traceback
Data 1     :       1,800,000,
Data 2     :       1,800,000,
Merged data:       1,800,000
```

#### 2. The example above runs without problem for smaller dataframes:

```python
nrows = 100000
...
```

Output:
```python-traceback
Data 1     :         100,000,
Data 2     :         100,000,
Merged data:         100,000
```

**Comment by TomAugspurger** [comment]
Is writing to / reading from CSV necessary to reproduce?

My first guess is that when you read from CSV, you introduced duplicates in the index since we have `range(0, N)` for each partition. Then you join on the index, which introduces duplicates. Can you verify that?

**Comment by shoshijak** [comment]
> Is writing to / reading from CSV necessary to reproduce?

Yes. 
Proof is, that the following code is successful:
```python
# Generate 2 PANDAS DATAFRAMES
data1_dict = dict()
data2_dict = dict()
for colname1, colname2 in zip('abc', 'ABC'):
    data1_dict[colname1] = np.random.rand(nrows).tolist()
    data2_dict[colname2] = np.random.rand(nrows).tolist()
data1_pd = pd.DataFrame(data1_dict)
data2_pd = pd.DataFrame(data2_dict)

# MERGE IN DASK
data1 = dd.from_pandas(data1_pd, npartitions=2)
data2 = dd.from_pandas(data2_pd, npartitions=2)
data = dd.merge(data1, data2, left_index=True, right_index=True)
nrows_message = nrows_message_temp.format(len(data1), len(data2), len(data))
assert len(data) == len(data1), "Mismatch in number of rows\n" + nrows_message
assert len(data) == len(data2), "Mismatch in number of rows\n" + nrows_message
print(nrows_message)
```

**Comment by shoshijak** [comment]
> My first guess is that when you read from CSV, you introduced duplicates in the index since we have range(0, N) for each partition. Then you join on the index, which introduces duplicates. Can you verify that?

I'm not sure how to verify this. 
Also, would this explanation explain the fact that this code runs fine for a smaller dataframe?

**Comment by TomAugspurger** [comment]
Can you verify that duplicates are causing the issue? You may be able to
check by doing a `.reset_index()` before writing, and then doing a
`.set_index()` after reading.

**Comment by TomAugspurger** [comment]
Possibly. I didn't check to see how many partitions the smaller example had.

Does my comment about set_index & reset_index help?

**Comment by shoshijak** [comment]
> Can you verify that duplicates are causing the issue? You may be able to
check by doing a `.reset_index()` before writing, and then doing a
`.set_index()` after reading.

The error persists after adding `.reset_index()` before writing doesn't change anything.
Here's the output: 
```
[Before writing] Head:
           a         b         c
0  0.139220  0.542737  0.883487
1  0.475350  0.298617  0.427679
2  0.309108  0.930548  0.456146
3  0.334058  0.901772  0.319628
4  0.450500  0.983888  0.023687

[After reading] Head:
           a         b         c
0  0.139220  0.542737  0.883487
1  0.475350  0.298617  0.427679
2  0.309108  0.930548  0.456146
3  0.334058  0.901772  0.319628
4  0.450500  0.983888  0.023687

Traceback (most recent call last):
  File "blob.py", line 37, in <module>
    assert len(data) == len(data1), "Mismatch in number of rows\n" + nrows_message
AssertionError: Mismatch in number of rows

Data 1     :       1,000,000,
Data 2     :       1,000,000,
Merged data:       1,211,326
```

**Comment by shoshijak** [comment]
> Possibly. I didn't check to see how many partitions the smaller example had.

The smaller example has only 1 partition, while the larger one has multiple partitions.

**Comment by TomAugspurger** [comment]
> The error persists after adding .reset_index() before writing doesn't change anything.

Did you also do a `.set_index(col)` on the column you reset before writing?

As another way to check if the index is unique: Ensure that `ddf.index.value_counts().max().compute()` is 1.

**Comment by shoshijak** [comment]
> Did you also do a .set_index(col) on the column you reset before writing?

In my previous output I didn't. Here's the output with `set_index`

Data 1 (PANDAS, after `reset_index`, before write):
```python-traceback
           a         b         c
0  0.649335  0.227116  0.143635
1  0.237052  0.165189  0.584484
2  0.484127  0.379523  0.718477
3  0.604375  0.080498  0.308983
4  0.555696  0.292415  0.179264
```

Data 1 (DASK, after reading, before `set_index("index")`
```python-traceback
    Unnamed: 0  index         a         b         c
0           0      0  0.649335  0.227116  0.143635
1           1      1  0.237052  0.165189  0.584484
2           2      2  0.484127  0.379523  0.718477
3           3      3  0.604375  0.080498  0.308983
4           4      4  0.555696  0.292415  0.179264
```

Data 1 (DASK, after reading, after `set_index("index")`
```python-traceback
        Unnamed: 0         a         b         c
index
0               0  0.649335  0.227116  0.143635
1               1  0.237052  0.165189  0.584484
2               2  0.484127  0.379523  0.718477
3               3  0.604375  0.080498  0.308983
4               4  0.555696  0.292415  0.179264
```

Data Merged (DASK, after reading, after `set_index("index")`
```python-traceback
    Unnamed: 0_x       A_x       B_x       C_x  Unnamed: 0_y   index       A_y       B_y       C_y
0             0  0.014235  0.001588  0.358504        894346  894346  0.615538  0.288534  0.458022
0             0  0.014235  0.001588  0.358504             0       0  0.014235  0.001588  0.358504
2             2  0.481274  0.480972  0.751948        894348  894348  0.931626  0.969984  0.587904
2             2  0.481274  0.480972  0.751948             2       2  0.481274  0.480972  0.751948
3             3  0.868291  0.189982  0.166653        894349  894349  0.922274  0.206127  0.184821
```

**Comment by TomAugspurger** [comment]
If you're trying out the reset_index / set_index stuff, you may need to play with whether the row is written or not.

The idea is to have the dask and pandas versions be identical. The dask one just have to go through an extra set_index so that the partitioning is done on a monotonically
increasing column.

**Comment by martindurant** [comment]
@shoshijak , to reiterate: if you read from CSV without specifying an index column, you will get an index numbered from 0 *in each partition*. You may find using `.tail()` rather than `.head()` illuminating. To do this right, you need to either explicitly write the index you want to use, recreate it after loading, or (preferred) don't rely on CSV for row-numbers.

**Comment by shoshijak** [comment]
@TomAugspurger @martindurant , thanks a lot to both of you. 

> if you read from CSV without specifying an index column, you will get an index numbered from 0 in each partition.
Ah, I didn't know that. Now I understand why the code I originally posted doesn't do what I intended it to do. 

For future reference or other people with the same issue, here are two working solutions for the code originally posted:

1. 
> explicitly write the index you want to use, recreate it after loading,

```
import numpy as np
import pandas as pd
import dask.dataframe as dd

nrows = 1000000
nrows_message_temp = """
Data 1     : {:15,},
Data 2     : {:15,},
Merged data: {:15,}"""

# Generate 2 PANDAS DATAFRAMES
data1_dict = dict()
data2_dict = dict()
for colname1, colname2 in zip('abc', 'ABC'):
    data1_dict[colname1] = np.random.rand(nrows).tolist()
    data2_dict[colname2] = np.random.rand(nrows).tolist()
data1_pd = pd.DataFrame(data1_dict)
data2_pd = pd.DataFrame(data2_dict)

# PRINT PANDAS DATAFRAMES TO CSV
data_file1 = "data1.csv"
data1_pd.to_csv(data_file1, index_label='index')
data_file2 = "data2.csv"
data2_pd.to_csv(data_file2, index_label='index')

# [DASK] READ & MERGE
data1 = pd.read_csv(data_file1)
data1 = pd.read_csv(data_file1, index_col=0)
data1 = dd.read_csv(data_file1).set_index("index")
data2 = dd.read_csv(data_file2).set_index("index")
data = dd.merge(data1, data2, left_index=True, right_index=True)
nrows_message = nrows_message_temp.format(len(data1), len(data2), len(data))
assert len(data) == len(data1), "Mismatch in number of rows\n" + nrows_message
assert len(data) == len(data2), "Mismatch in number of rows\n" + nrows_message
print(nrows_message)
```

2. 
> (preferred) don't rely on CSV for row-numbers.
```
.
```
