### ISSUE TITLE
dask dumps core when asked to compute a result based on several HDF files

### ISSUE THREAD

**Issue by jeffcbecker** [dask/dask#5123]
I have successfully run an example that takes as input a MODIS tile id, and reads four years worth of MODIS tiles(92 tiles) for that id using xarray.open_mfdataset. I'm then able to do a bunch of computation using xarray and dask. I'm using dask.distributed and dask_jobqueue to run using PBS on a supercomputer at NASA. I'm using 8 nodes with 20 cores each

However, when I try to scale this up to several (11 currently) MODIS tiles, I get HDF errors and core files. To be specific, at the end of reading in the tiles, I have a list of them called conus_tile_sketches. I then do:

>>> flat_sketches = xr.concat(conus_tile_sketches,dim='c')
>>> flat_sketches = flat_sketches.persist()
>>> q = flat_sketches[:,30123456]
>>> q.compute()

Sometimes when I run this it works. However sometimes I get the following traceback, as well as several core files (I assume from the dask-workers). Is there a way to work around this, or another solution? Thanks.

>>> q.compute()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home7/jcbecker/.conda/envs/geo/lib/python3.7/site-packages/xarray/core/dataarray.py", line 755, in compute
    return new.load(**kwargs)
  File "/home7/jcbecker/.conda/envs/geo/lib/python3.7/site-packages/xarray/core/dataarray.py", line 729, in load
    ds = self._to_temp_dataset().load(**kwargs)
  File "/home7/jcbecker/.conda/envs/geo/lib/python3.7/site-packages/xarray/core/dataset.py", line 552, in load
    evaluated_data = da.compute(*lazy_data.values(), **kwargs)
  File "/home7/jcbecker/.conda/envs/geo/lib/python3.7/site-packages/dask/base.py", line 446, in compute
    results = schedule(dsk, keys, **kwargs)
  File "/home7/jcbecker/.conda/envs/geo/lib/python3.7/site-packages/distributed/client.py", line 2527, in get
    results = self.gather(packed, asynchronous=asynchronous, direct=direct)
  File "/home7/jcbecker/.conda/envs/geo/lib/python3.7/site-packages/distributed/client.py", line 1823, in gather
    asynchronous=asynchronous,
  File "/home7/jcbecker/.conda/envs/geo/lib/python3.7/site-packages/distributed/client.py", line 763, in sync
    self.loop, func, *args, callback_timeout=callback_timeout, **kwargs
  File "/home7/jcbecker/.conda/envs/geo/lib/python3.7/site-packages/distributed/utils.py", line 332, in sync
    six.reraise(*error[0])
  File "/home7/jcbecker/.conda/envs/geo/lib/python3.7/site-packages/six.py", line 693, in reraise
    raise value
  File "/home7/jcbecker/.conda/envs/geo/lib/python3.7/site-packages/distributed/utils.py", line 317, in f
    result[0] = yield future
  File "/home7/jcbecker/.conda/envs/geo/lib/python3.7/site-packages/tornado/gen.py", line 729, in run
    value = future.result()
  File "/home7/jcbecker/.conda/envs/geo/lib/python3.7/site-packages/tornado/gen.py", line 736, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/home7/jcbecker/.conda/envs/geo/lib/python3.7/site-packages/distributed/client.py", line 1680, in _gather
    six.reraise(type(exception), exception, traceback)
  File "/home7/jcbecker/.conda/envs/geo/lib/python3.7/site-packages/six.py", line 692, in reraise
    raise value.with_traceback(tb)
  File "/home7/jcbecker/.conda/envs/geo/lib/python3.7/site-packages/dask/array/core.py", line 100, in getter
    c = np.asarray(c)
  File "/home7/jcbecker/.conda/envs/geo/lib/python3.7/site-packages/numpy/core/numeric.py", line 538, in asarray
    return array(a, dtype, copy=False, order=order)
  File "/home7/jcbecker/.conda/envs/geo/lib/python3.7/site-packages/xarray/core/indexing.py", line 452, in __array__
    return np.asarray(self.array, dtype=dtype)
  File "/home7/jcbecker/.conda/envs/geo/lib/python3.7/site-packages/numpy/core/numeric.py", line 538, in asarray
    return array(a, dtype, copy=False, order=order)
  File "/home7/jcbecker/.conda/envs/geo/lib/python3.7/site-packages/xarray/core/indexing.py", line 610, in __array__
    return np.asarray(self.array, dtype=dtype)
  File "/home7/jcbecker/.conda/envs/geo/lib/python3.7/site-packages/numpy/core/numeric.py", line 538, in asarray
    return array(a, dtype, copy=False, order=order)
  File "/home7/jcbecker/.conda/envs/geo/lib/python3.7/site-packages/xarray/core/indexing.py", line 516, in __array__
    return np.asarray(array[self.key], dtype=None)
  File "/home7/jcbecker/.conda/envs/geo/lib/python3.7/site-packages/xarray/conventions.py", line 42, in __getitem__
    return np.asarray(self.array[key], dtype=self.dtype)
  File "/home7/jcbecker/.conda/envs/geo/lib/python3.7/site-packages/numpy/core/numeric.py", line 538, in asarray
    return array(a, dtype, copy=False, order=order)
  File "/home7/jcbecker/.conda/envs/geo/lib/python3.7/site-packages/xarray/core/indexing.py", line 516, in __array__
    return np.asarray(array[self.key], dtype=None)
  File "/home7/jcbecker/.conda/envs/geo/lib/python3.7/site-packages/xarray/backends/netCDF4_.py", line 70, in __getitem__
    self._getitem)
  File "/home7/jcbecker/.conda/envs/geo/lib/python3.7/site-packages/xarray/core/indexing.py", line 784, in explicit_indexing_adapter
    result = raw_indexing_method(raw_key.tuple)
  File "/home7/jcbecker/.conda/envs/geo/lib/python3.7/site-packages/xarray/backends/netCDF4_.py", line 81, in _getitem
    array = getitem(original_array, key)
  File "netCDF4/_netCDF4.pyx", line 4119, in netCDF4._netCDF4.Variable.__getitem__
  File "netCDF4/_netCDF4.pyx", line 5036, in netCDF4._netCDF4.Variable._get
  File "netCDF4/_netCDF4.pyx", line 1754, in netCDF4._netCDF4._ensure_nc_success
RuntimeError: NetCDF: HDF error

**Comment by jrbourbeau** [comment]
Thanks for raising this issue @jeffcbecker. Would it be possible to create a minimal bug report (https://blog.dask.org/2018/02/28/minimal-bug-reports)? That would help substantially in the debugging process

**Comment by jeffcbecker** [comment]
I raised memory to 500GB (from 256GB), but that didn't help. I then tried removing the statement:

>>> flat_sketches = flat_sketches.persist()

since flat_sketches is pretty big (see below). I've now had 3 successful runs. Progress!

>>> flat_sketches
<xarray.DataArray (rv: 10, c: 63360000)>
dask.array<shape=(10, 63360000), dtype=int64, chunksize=(10, 9600)>
Coordinates:
    X        (c) int64 dask.array<shape=(63360000,), chunksize=(240000,)>
    Y        (c) int64 dask.array<shape=(63360000,), chunksize=(240000,)>
  * c        (c) MultiIndex
  - x        (c) int64 0 0 0 0 0 0 0 0 ... 2399 2399 2399 2399 2399 2399 2399
  - y        (c) int64 0 1 2 3 4 5 6 7 ... 2393 2394 2395 2396 2397 2398 2399
Dimensions without coordinates: rv

**Comment by jeffcbecker** [comment]
Still working this. I'm noticing lots of messages of the form:

distributed.core - INFO - Event loop was unresponsive in Worker for 6.48s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.

Is there a strategy for minimizing/eliminating these?

**Comment by jeffcbecker** [comment]
Got my code to work using a combination of persist, and client.cancel memory management. Closing...
