### ISSUE TITLE
read_csv from s3 without listbuckets access

### ISSUE THREAD

**Issue by AntonFriberg** [dask/dask#5141]
Hi!

I am trying to run the following:

```python
import dask.dataframe as dd

data = dd.read_csv("s3://bucket-name/file-name.csv")
print(data.head())
```

But it fails due to `botocore.exceptions.ClientError: An error occurred (AccessDenied)` when calling the ListBuckets operation: Access Denied`. My credentials does not have access to list buckets, but has access to list objects inside the specified bucket.

Full traceback:
```
Traceback (most recent call last):
  File "dask_test.py", line 8, in <module>
    "s3://bucket-name/file-name.csv"
  File "/home/antonfr/.virtualenvs/dtc/lib/python3.6/site-packages/dask/dataframe/io/csv.py", line 579, in read
    **kwargs
  File "/home/antonfr/.virtualenvs/dtc/lib/python3.6/site-packages/dask/dataframe/io/csv.py", line 406, in read_pandas
    **(storage_options or {})
  File "/home/antonfr/.virtualenvs/dtc/lib/python3.6/site-packages/dask/bytes/core.py", line 116, in read_bytes
    size = logical_size(fs, path, compression)
  File "/home/antonfr/.virtualenvs/dtc/lib/python3.6/site-packages/dask/bytes/core.py", line 624, in logical_size
    return fs.size(path)
  File "/home/antonfr/.virtualenvs/dtc/lib/python3.6/site-packages/dask/bytes/s3.py", line 54, in size
    return self.info(path)["Size"]
  File "/home/antonfr/.virtualenvs/dtc/lib/python3.6/site-packages/s3fs/core.py", line 470, in info
    return super().info(path)
  File "/home/antonfr/.virtualenvs/dtc/lib/python3.6/site-packages/fsspec/spec.py", line 467, in info
    out = self.ls(self._parent(path), detail=True, **kwargs)
  File "/home/antonfr/.virtualenvs/dtc/lib/python3.6/site-packages/s3fs/core.py", line 488, in ls
    out = self._ls(self._parent(path), refresh=refresh)
  File "/home/antonfr/.virtualenvs/dtc/lib/python3.6/site-packages/s3fs/core.py", line 423, in _ls
    return self._lsbuckets(refresh)
  File "/home/antonfr/.virtualenvs/dtc/lib/python3.6/site-packages/s3fs/core.py", line 376, in _lsbuckets
    files = self.s3.list_buckets()['Buckets']
  File "/home/antonfr/.virtualenvs/dtc/lib/python3.6/site-packages/botocore/client.py", line 357, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/antonfr/.virtualenvs/dtc/lib/python3.6/site-packages/botocore/client.py", line 661, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (AccessDenied) when calling the ListBuckets operation: Access Denied
```

`pip freeze` output:
```
bokeh==1.3.0
boto3==1.9.193
botocore==1.12.193
Click==7.0
cloudpickle==1.2.1
dask==2.1.0
distributed==2.1.0
docutils==0.14
fsspec==0.3.4
HeapDict==1.0.0
Jinja2==2.10.1
jmespath==0.9.4
locket==0.2.0
MarkupSafe==1.1.1
msgpack==0.6.1
numpy==1.16.4
packaging==19.0
pandas==0.25.0
partd==1.0.0
Pillow==6.1.0
pkg-resources==0.0.0
psutil==5.6.3
pyparsing==2.4.1
python-dateutil==2.8.0
pytz==2019.1
PyYAML==5.1.1
s3fs==0.3.0
s3transfer==0.2.1
six==1.12.0
sortedcontainers==2.1.0
tblib==1.4.0
toolz==0.10.0
tornado==6.0.3
urllib3==1.25.3
zict==1.0.0
```

The reason seems to be that the read_csv function does not pass the full s3 path (`s3://bucket-name/file-name.csv`) into the `s3fs.core` module which results in `s3fs.core._ls` issuing `s3fs.core._lsbuckets` instead of `s3fs.core_lsdirs`. https://github.com/dask/s3fs/blob/master/s3fs/core.py#L405-L425

I consider this a bug since since most s3 credentials would not give away access to list other buckets on the account.

**Expected behavior**
That `dask.dataframe.read_csv('s3://bucket/key` whould not need ListBuckets access rights but instead only access the single bucket specified.

**Comment by jcrist** [comment]
cc @martindurant
