### ISSUE TITLE
MemoryError while to_parquet or .repartition 

### ISSUE THREAD

**Issue by Matthew-gunsuSon** [dask/dask#5159]
I'm running into a MemoryError when I try to save in a parquet format, or repartition(by size).
I didn't have this issue before, but after merging two dask dataframes, it's giving me this error.
The memory usage of python terminal keeps going up, and the it takes most of my machine's memory even after the error.

```
EWQ = dd.read_parquet('./merged1.parquet')
R = dd.read_parquet('./price.parquet')
print(EWQ.npartitions);print(R.npartitions)#500, 207 each
EWQR = dd.merge(EWQ, R, on = 'Symbol', how='left')
EWQR.npartitions # 500 partitions

with ProgressBar():
    EWQR.to_parquet('./merged2.parquet')
[########################                ] | 61% Completed | 16min 49.2s

Traceback (most recent call last):
  File "<input>", line 2, in <module>
  File "C:\Users\gunsu.son\AppData\Local\Continuum\miniconda3\lib\site-packages\dask\dataframe\core.py", line 3618, in to_parquet
    return to_parquet(self, path, *args, **kwargs)
  File "C:\Users\gunsu.son\AppData\Local\Continuum\miniconda3\lib\site-packages\dask\dataframe\io\parquet.py", line 1496, in to_parquet
    out.compute()
  File "C:\Users\gunsu.son\AppData\Local\Continuum\miniconda3\lib\site-packages\dask\base.py", line 175, in compute
    (result,) = compute(self, traverse=False, **kwargs)
  File "C:\Users\gunsu.son\AppData\Local\Continuum\miniconda3\lib\site-packages\dask\base.py", line 446, in compute
    results = schedule(dsk, keys, **kwargs)
  File "C:\Users\gunsu.son\AppData\Local\Continuum\miniconda3\lib\site-packages\dask\threaded.py", line 82, in get
    **kwargs
  File "C:\Users\gunsu.son\AppData\Local\Continuum\miniconda3\lib\site-packages\dask\local.py", line 491, in get_async
    raise_exception(exc, tb)
  File "C:\Users\gunsu.son\AppData\Local\Continuum\miniconda3\lib\site-packages\dask\compatibility.py", line 130, in reraise
    raise exc
  File "C:\Users\gunsu.son\AppData\Local\Continuum\miniconda3\lib\site-packages\dask\local.py", line 233, in execute_task
    result = _execute_task(task, data)
  File "C:\Users\gunsu.son\AppData\Local\Continuum\miniconda3\lib\site-packages\dask\core.py", line 119, in _execute_task
    return func(*args2)
  File "C:\Users\gunsu.son\AppData\Local\Continuum\miniconda3\lib\site-packages\dask\compatibility.py", line 107, in apply
    return func(*args, **kwargs)
  File "C:\Users\gunsu.son\AppData\Local\Continuum\miniconda3\lib\site-packages\dask\dataframe\multi.py", line 224, in merge_chunk
    out = lhs.merge(*args, **kwargs)
  File "C:\Users\gunsu.son\AppData\Local\Continuum\miniconda3\lib\site-packages\pandas\core\frame.py", line 6868, in merge
    copy=copy, indicator=indicator, validate=validate)
  File "C:\Users\gunsu.son\AppData\Local\Continuum\miniconda3\lib\site-packages\pandas\core\reshape\merge.py", line 48, in merge
    return op.get_result()
  File "C:\Users\gunsu.son\AppData\Local\Continuum\miniconda3\lib\site-packages\pandas\core\reshape\merge.py", line 546, in get_result
    join_index, left_indexer, right_indexer = self._get_join_info()
  File "C:\Users\gunsu.son\AppData\Local\Continuum\miniconda3\lib\site-packages\pandas\core\reshape\merge.py", line 756, in _get_join_info
    right_indexer) = self._get_join_indexers()
  File "C:\Users\gunsu.son\AppData\Local\Continuum\miniconda3\lib\site-packages\pandas\core\reshape\merge.py", line 735, in _get_join_indexers
    how=self.how)
  File "C:\Users\gunsu.son\AppData\Local\Continuum\miniconda3\lib\site-packages\pandas\core\reshape\merge.py", line 1146, in _get_join_indexers
    return join_func(lkey, rkey, count, **kwargs)
  File "pandas/_libs/join.pyx", line 98, in pandas._libs.join.left_outer_join
MemoryError

```

One thing I'm a little bit suspicious about is that merged1.parquet file is unevenly partitioned in terms of size. It was partitioned into 500 files, but when I look at the size of each, some partitions have only 23KB, while some others have >500MB. I'm uncertain if this has to do with the error through. What possibly is causing the problem? How can I evade MemoryError in this case?

**Comment by jcrist** [comment]
Hello, thanks for filing an issue. For tasks like this it's hard for us to help without a [minimal reproducible example](https://blog.dask.org/2018/02/28/minimal-bug-reports).

High memory usage for tasks like this could be due to several things, but the dataframe partitioning schemes are likely part of it. For parquet what's important is the size of each partition ("row group" in parquet parlance), not the size of each file (each file may have one or more partitions). You may try experimenting with manually repartitioning (`.repartition`) after reading if the size of each partition is too large.

Another thought would be to switch to using the distributed scheduler (which works fine locally) - this provides better debugging and profiling options with the dashboard (https://distributed.dask.org/en/latest/web.html), and may provide more insights.

**Comment by Matthew-gunsuSon** [comment]
Please excuse my lack of detailed work in this posting. With my limited experience with python and dask, I wan't sure how to mimic this problem. 

I assumed that the each size of parquet file corresponds to each size of partitions, for I have used dask.to_parquet function to save merged parquet file. (As far as I know, dask.to parquet saves each partitions to each parquet file, but correct me if I am wrong.)

Since I did not have trouble saving merged1 parquet file, I'll try to reparition them by size(so that it is evenly divided) and try above code again. I'll post the result when it's done.

**Comment by TomAugspurger** [comment]
Any updates here @Matthew-gunsuSon?

> I assumed that the each size of parquet file corresponds to each size of partitions, for I have used dask.to_parquet function to save merged parquet file. (As far as I know, dask.to parquet saves each partitions to each parquet file, but correct me if I am wrong.)

Yes, usually. Specifying `partition_on` may change that a bit.

**Comment by Matthew-gunsuSon** [comment]
Yeah, seems like uneven partition caused the problem. With even sized paritions it worked.
