### ISSUE TITLE
dd.merge with npartitions='auto' generates TypeError

### ISSUE THREAD

**Issue by Matthew-gunsuSon** [dask/dask#5190]
When I was trying to figure out how to resolve ``MemoryError`` issue #5159 caused by uneven partitions after merging two dataframes, ``dd.merge( npartitions='auto')`` came on my radar. 

I just have found that when I try to merge with ``npartitons='auto'`` it generates an TypeError message. Here's a reproducible example.

```
>>> quotes
                    time0 time ticker     bid     ask
0 2016-05-25 13:30:00.023   GOOG  720.50  720.93
1 2016-05-25 13:30:00.023   MSFT   51.95   51.96
2 2016-05-25 13:30:00.030   MSFT   51.97   51.98
3 2016-05-25 13:30:00.041   MSFT   51.99   52.00
4 2016-05-25 13:30:00.048   GOOG  720.50  720.93
5 2016-05-25 13:30:00.049   AAPL   97.99   98.01
6 2016-05-25 13:30:00.072   GOOG  720.50  720.88
7 2016-05-25 13:30:00.075   MSFT   52.01   52.03

quotes = pd.read_clipboard()
quotes['time'] = pd.to_datetime(quotes.time0 +' ' + quotes.time)
quotes.drop(columns='time0',inplace=True)

>>> trades
                    time0 time ticker   price  quantity
0 2016-05-25 13:30:00.023   MSFT   51.95        75
1 2016-05-25 13:30:00.038   MSFT   51.95       155
2 2016-05-25 13:30:00.048   GOOG  720.77       100
3 2016-05-25 13:30:00.048   GOOG  720.92       100
4 2016-05-25 13:30:00.048   AAPL   98.00       100

trades = pd.read_clipboard()
trades['time'] = pd.to_datetime(trades.time0 + ' ' + trades.time)
trades.drop(columns='time0', inplace=True)



dd_quotes = dd.from_pandas(quotes,npartitions=4)
dd_trades = dd.from_pandas(trades,npartitions=2)


dd.merge(dd_quotes,dd_trades,on='ticker',npartitions='auto')

Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "C:\Users\gunsu.son\AppData\Local\Continuum\miniconda3\lib\site-packages\dask\dataframe\multi.py", line 563, in merge
    indicator=indicator,
  File "C:\Users\gunsu.son\AppData\Local\Continuum\miniconda3\lib\site-packages\dask\dataframe\multi.py", line 279, in hash_join
    lhs2 = shuffle_func(lhs, left_on, npartitions=npartitions, shuffle=shuffle)
  File "C:\Users\gunsu.son\AppData\Local\Continuum\miniconda3\lib\site-packages\dask\dataframe\shuffle.py", line 250, in shuffle
    compute=compute,
  File "C:\Users\gunsu.son\AppData\Local\Continuum\miniconda3\lib\site-packages\dask\dataframe\shuffle.py", line 281, in rearrange_by_column
    return rearrange_by_column_disk(df, col, npartitions, compute=compute)
  File "C:\Users\gunsu.son\AppData\Local\Continuum\miniconda3\lib\site-packages\dask\dataframe\shuffle.py", line 359, in rearrange_by_column_disk
    (name, i): (collect, p, i, df._meta, barrier_token) for i in range(npartitions)
TypeError: 'str' object cannot be interpreted as an integer
```

**Comment by TomAugspurger** [comment]
Can you provide an example that doesn't rely on read_clipboard? It'll be easier to turn into a unit test.

I wonder the docstring for `npartitions` allowing 'auto' was updated without updating the implementation.

I'm not sure where best the `npartitions='auto'` should be resolved to an integer. Are you interested in exploring @Matthew-gunsuSon?

**Comment by jrbourbeau** [comment]
It appears `npartitions="auto"` isn't currently supported. Running 

```python
import pandas as pd
import dask.dataframe as dd
from dask.dataframe.multi import hash_join

A = pd.DataFrame({"x": [1, 2, 3, 4, 5, 6], "y": [1, 1, 2, 2, 3, 4]})
a = dd.repartition(A, [0, 4, 5])

B = pd.DataFrame({"y": [1, 3, 4, 4, 5, 6], "z": [6, 5, 4, 3, 2, 1]})
b = dd.repartition(B, [0, 2, 5])

c = hash_join(a, "y", b, "y", how="inner", npartitions="auto")
```

outputs the 

```
TypeError: 'str' object cannot be interpreted as an integer
```

@Matthew-gunsuSon is seeing. We should update the docstring to reflect this.
