### ISSUE TITLE
`DataFrame.values` doesn't work after reduction in `map_partitions`

### ISSUE THREAD

**Issue by lr4d** [dask/dask#5263]
I don't know if this is to be expected, but the dask graph appears to break when a reduction is performed in the function passed to `map_partitions`.

It seems like the dask graph expects pd.DataFrames out of `map_partitions` and fails when that's not the case.

Code example:
```
import dask
print(dask.__version__)

import dask.dataframe as dd
import pandas as pd

df = pd.DataFrame({"A": [1, 2]})
ddf = dd.from_pandas(df, npartitions=1)

meta = ("A", "int")
ddf.map_partitions(lambda df: df["A"].sum(), meta=meta).values.compute()
```

Output:
```
2.2.0
Traceback (most recent call last):
  File "/Users/xrzq/miniconda3/envs/py36/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 3296, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-21-71ba78ae2b82>", line 13, in <module>
    ddf.map_partitions(lambda df: df["A"].sum(), meta=meta).values.compute()
  File "/Users/xrzq/miniconda3/envs/py36/lib/python3.6/site-packages/dask/base.py", line 175, in compute
    (result,) = compute(self, traverse=False, **kwargs)
  File "/Users/xrzq/miniconda3/envs/py36/lib/python3.6/site-packages/dask/base.py", line 446, in compute
    results = schedule(dsk, keys, **kwargs)
  File "/Users/xrzq/miniconda3/envs/py36/lib/python3.6/site-packages/dask/threaded.py", line 82, in get
    **kwargs
  File "/Users/xrzq/miniconda3/envs/py36/lib/python3.6/site-packages/dask/local.py", line 491, in get_async
    raise_exception(exc, tb)
  File "/Users/xrzq/miniconda3/envs/py36/lib/python3.6/site-packages/dask/compatibility.py", line 130, in reraise
    raise exc
  File "/Users/xrzq/miniconda3/envs/py36/lib/python3.6/site-packages/dask/local.py", line 233, in execute_task
    result = _execute_task(task, data)
  File "/Users/xrzq/miniconda3/envs/py36/lib/python3.6/site-packages/dask/core.py", line 119, in _execute_task
    return func(*args2)
  File "/Users/xrzq/miniconda3/envs/py36/lib/python3.6/site-packages/dask/optimization.py", line 1059, in __call__
    return core.get(self.dsk, self.outkey, dict(zip(self.inkeys, args)))
  File "/Users/xrzq/miniconda3/envs/py36/lib/python3.6/site-packages/dask/core.py", line 149, in get
    result = _execute_task(task, cache)
  File "/Users/xrzq/miniconda3/envs/py36/lib/python3.6/site-packages/dask/core.py", line 119, in _execute_task
    return func(*args2)
  File "/Users/xrzq/miniconda3/envs/py36/lib/python3.6/site-packages/dask/compatibility.py", line 107, in apply
    return func(*args, **kwargs)
  File "/Users/xrzq/miniconda3/envs/py36/lib/python3.6/site-packages/dask/dataframe/core.py", line 4829, in apply_and_enforce
    df = func(*args, **kwargs)
  File "/Users/xrzq/miniconda3/envs/py36/lib/python3.6/site-packages/dask/dataframe/methods.py", line 274, in values
    return df.values
AttributeError: 'numpy.int64' object has no attribute 'values'
```

**Comment by TomAugspurger** [comment]
Thanks for the report. Something strange is going on, since this doesn't error for 

```python

In [101]: s = dd.from_pandas(pd.Series([], dtype='int', name='A'), 2)

In [102]: s.values.compute()
Out[102]: array([], dtype=int64)
```

Are you interested in looking further @lr4d?

**Comment by lr4d** [comment]
It appears to be specfically related to when a reduction is performed, as `ddf.map_partitions(lambda df: df["A"] + 1, meta=meta).values.compute()` also works.

>Are you interested in looking further @lr4d?

I am, but I don't have too much spare time atm. I may try looking into this next Friday

**Comment by lr4d** [comment]
Digging a bit further today, it seems like the issue lies in `map_partititions`. 

If calling `ddf.map_partitions(lambda df: df["A"].sum(), meta=meta)`, `map_partitions` returns `new_dd_object(graph, name, meta, divisions)`. The `graph` would return a `np.int` but since `meta=pd.Series`, this statement returns a Series.

However, when calling `ddf.map_partitions(lambda df: df["A"].sum(), meta=meta).values`, `map_partitions` is called only once, and, crucially, `new_dd_object(graph, name, meta, divisions)` is not called on the intermediary output (the `np.int` that was converted to a Series in the previous scenario) . Then, `values` is called on a `np.int` object, which raises the exception provided in the original post.


```python
dask.compute(ddf.map_partitions(lambda df: df["A"].sum(), meta=meta).values, optimize_graph=False, scheduler="synchronous")
> /Users/xrzq/public_workspace/dask/dask/dataframe/core.py(4833)map_partitions()
   4832 
-> 4833     return new_dd_object(graph, name, meta, divisions)
   4834 
ipdb> >? graph.layers
{'values-538ebcb3e2ab5e808abd46b82347d794': <dask.blockwise.Blockwise object at 0x10c291a58>, 'lambda-ed40d14d6a25e71b80d255bfff06330a': <dask.blockwise.Blockwise object at 0x1115357f0>, 'from_pandas-75805870329f1928e094729c0f089a96': {('from_pandas-75805870329f1928e094729c0f089a96', 0):    A
0  1
1  2}}
```

Any tips on how to move forward? @TomAugspurger

**Comment by TomAugspurger** [comment]
Not off the top of my head, sorry.

**Comment by quasiben** [comment]
I think `map_partitions` assumes that the resulting computation still produces a dataframe-like or series-like object.  From the end of the doc string:

> Also note that the index and divisions are assumed to remain unchanged.
If the function you're mapping changes the index/divisions, you'll need
to clear them afterwards:

The operation, `df['A'].sum()` produces an integer which has no index.  What happens to work is, if instead you call with a list of columns the reduction should return a series and not an integer.

> ddf.map_partitions(lambda df: df[["A"]].sum(), meta=meta).values.compute()
