### ISSUE TITLE
ValueError in dask.array.reductions.reduction

### ISSUE THREAD

**Issue by stephaniegott** [dask/dask#5278]
Ran into this error while attempting to use `dask.array.reductions.reduction` to wrap `numpy.ma.median`. This only happens when `axis=(0,1)` or `axis=(2,3)` or similar. Does not happen with `axis=0` or similar.
```
Traceback (most recent call last):
  File "/home/stephanie/.local/lib/python3.6/site-packages/dask/array/reductions.py", line 304, in partial_reduce
    meta = func(reduced_meta, computing_meta=True)
  File "/home/stephanie/.local/lib/python3.6/site-packages/toolz/functoolz.py", line 486, in __call__
    ret = self.first(*args, **kwargs)
TypeError: _concatenate2() got an unexpected keyword argument 'computing_meta'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test_reduction.py", line 14, in <module>
    keepdims=True
  File "/home/stephanie/.local/lib/python3.6/site-packages/dask/array/reductions.py", line 188, in reduction
    reduced_meta=reduced_meta,
  File "/home/stephanie/.local/lib/python3.6/site-packages/dask/array/reductions.py", line 253, in _tree_reduce
    reduced_meta=reduced_meta,
  File "/home/stephanie/.local/lib/python3.6/site-packages/dask/array/reductions.py", line 307, in partial_reduce
    meta = func(reduced_meta)
  File "/home/stephanie/.local/lib/python3.6/site-packages/toolz/functoolz.py", line 488, in __call__
    ret = f(ret)
  File "/home/stephanie/.local/lib/python3.6/site-packages/numpy/ma/extras.py", line 687, in median
    keepdims=keepdims)
  File "/home/stephanie/.local/lib/python3.6/site-packages/numpy/lib/function_base.py", line 3497, in median
    overwrite_input=overwrite_input)
  File "/home/stephanie/.local/lib/python3.6/site-packages/numpy/lib/function_base.py", line 3399, in _ureduce
    a = a.reshape(a.shape[:nkeep] + (-1,))
ValueError: cannot reshape array of size 0 into shape (0,0,newaxis)
```
Can be reproduced with the following code:
```
import dask.array as da
import numpy as np

arr = da.from_array(np.arange(384).reshape(3,4,4,8)).rechunk((1,1,4,8))

reduced = da.reductions.reduction(
        arr,
        chunk=lambda arr, axis, keepdims: arr,
        aggregate=np.ma.median,
        split_every={ax: arr.shape[ax] for ax in range(len(arr.shape))},
        concatenate=True,
        dtype=np.int64,
        axis=(0,1),
        keepdims=True
)
```

**Comment by mrocklin** [comment]
@pentschev it looks like we now require user defined functions to accept a
compute_meta= keyword.  Do you know if there is a way where we can avoid
this?

**Comment by pentschev** [comment]
Sure, the user could add the `compute_meta=` keyword in the `chunk`/`aggregate` functions that would simply return the input array, which is probably only required in a few more complex cases.

However, the issue here isn't due to the user defined functions, but that `np.ma.median` doesn't work well with 0-length dimension arrays. Ideally, the fix would live there, but that would take some time for a release, though I think we should raise an issue (but ultimately, I suspect we'll be the ones who will have to submit a PR).

Besides the issue above, I think we have a case that we didn't foresee. The way we compute meta in https://github.com/dask/dask/blob/master/dask/array/reductions.py#L303-L310, means we handle `TypeError` if we don't have a `computing_meta=` keyword, and `pass` if the function raises a `ValueError`. In the case here we have a partial function https://github.com/dask/dask/blob/master/dask/array/reductions.py#L243-L245 where `_concatenate2` raises a `TypeError` and later `np.ma.median` raises a `ValueError`.

I see two options here: we add `computing_meta` to `_contenate2` (but it won't do anything), or making an uglier exception handling:

```python
        try:
            meta = func(reduced_meta, computing_meta=True)
        # no meta keyword argument exists for func, and it isn't required
        except TypeError:
            try:
                meta = func(reduced_meta)
            except:
                pass
        # when no work can be computed on the empty array (e.g., func is a ufunc)
        except ValueError:
            pass
```

I can't really think of a cleaner way of doing it right now. Can you think of any @mrocklin?
