### ISSUE TITLE
Windows 10 Dask Client() gives error

### ISSUE THREAD

**Issue by xiaodaigh** [dask/dask#5302]
I ran the below
```python
from dask.distributed import Client
client = Client()
```
and I got. I am very new to Python and I want to help report the bugs, but how do I include all the info you need? I am running inside a virtualenv with dask installed.
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\RTX2080\AppData\Local\Programs\Python\Python37\lib\multiprocessing\spawn.py", line 105, in spawn_main
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\RTX2080\AppData\Local\Programs\Python\Python37\lib\multiprocessing\spawn.py", line 105, in spawn_main
Traceback (most recent call last):
  File "<string>", line 1, in <module>
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\RTX2080\AppData\Local\Programs\Python\Python37\lib\multiprocessing\spawn.py", line 105, in spawn_main
  File "C:\Users\RTX2080\AppData\Local\Programs\Python\Python37\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
          File "C:\Users\RTX2080\AppData\Local\Programs\Python\Python37\lib\multiprocessing\spawn.py", line 114, in _main
exitcode = _main(fd)exitcode = _main(fd)
  File "C:\Users\RTX2080\AppData\Local\Programs\Python\Python37\lib\multiprocessing\spawn.py", line 114, in _main
  File "C:\Users\RTX2080\AppData\Local\Programs\Python\Python37\lib\multiprocessing\spawn.py", line 114, in _main
    exitcode = _main(fd)
  File "C:\Users\RTX2080\AppData\Local\Programs\Python\Python37\lib\multiprocessing\spawn.py", line 114, in _main
    prepare(preparation_data)
  File "C:\Users\RTX2080\AppData\Local\Programs\Python\Python37\lib\multiprocessing\spawn.py", line 225, in prepare
    prepare(preparation_data)
  File "C:\Users\RTX2080\AppData\Local\Programs\Python\Python37\lib\multiprocessing\spawn.py", line 225, in prepare
    prepare(preparation_data)
  File "C:\Users\RTX2080\AppData\Local\Programs\Python\Python37\lib\multiprocessing\spawn.py", line 225, in prepare
    prepare(preparation_data)
  File "C:\Users\RTX2080\AppData\Local\Programs\Python\Python37\lib\multiprocessing\spawn.py", line 225, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\Users\RTX2080\AppData\Local\Programs\Python\Python37\lib\multiprocessing\spawn.py", line 277, in _fixup_main_from_path
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\Users\RTX2080\AppData\Local\Programs\Python\Python37\lib\multiprocessing\spawn.py", line 277, in _fixup_main_from_path
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\Users\RTX2080\AppData\Local\Programs\Python\Python37\lib\multiprocessing\spawn.py", line 277, in _fixup_main_from_path
    run_name="__mp_main__")    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\Users\RTX2080\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 261, in run_path
  File "C:\Users\RTX2080\AppData\Local\Programs\Python\Python37\lib\multiprocessing\spawn.py", line 277, in _fixup_main_from_path
    run_name="__mp_main__")
  File "C:\Users\RTX2080\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 261, in run_path
    run_name="__mp_main__")
  File "C:\Users\RTX2080\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 261, in run_path
    run_name="__mp_main__")
  File "C:\Users\RTX2080\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 261, in run_path
    code, fname = _get_code_from_file(run_name, path_name)        code, fname = _get_code_from_file(run_name, path_name)    
code, fname = _get_code_from_file(run_name, path_name)
  File "C:\Users\RTX2080\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 231, in _get_code_from_file
  File "C:\Users\RTX2080\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 231, in _get_code_from_file
  File "C:\Users\RTX2080\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 231, in _get_code_from_file
code, fname = _get_code_from_file(run_name, path_name)
  File "C:\Users\RTX2080\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 231, in _get_code_from_file
    with open(fname, "rb") as f:
OSError: [Errno 22] Invalid argument: 'C:\\data\\dask\\<input>'
            with open(fname, "rb") as f:with open(fname, "rb") as f:with open(fname, "rb") as f:
OSError: [Errno 22] Invalid argument: 'C:\\data\\dask\\<input>'
OSErrorOSError: : [Errno 22] Invalid argument: 'C:\\data\\dask\\<input>'[Errno 22] Invalid argument: 'C:\\data\\dask\\<input>'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\RTX2080\AppData\Local\Programs\Python\Python37\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "C:\Users\RTX2080\AppData\Local\Programs\Python\Python37\lib\multiprocessing\spawn.py", line 114, in _main
    prepare(preparation_data)
  File "C:\Users\RTX2080\AppData\Local\Programs\Python\Python37\lib\multiprocessing\spawn.py", line 225, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\Users\RTX2080\AppData\Local\Programs\Python\Python37\lib\multiprocessing\spawn.py", line 277, in _fixup_main_from_path
    run_name="__mp_main__")
  File "C:\Users\RTX2080\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 261, in run_path
    code, fname = _get_code_from_file(run_name, path_name)
  File "C:\Users\RTX2080\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 231, in _get_code_from_file
    with open(fname, "rb") as f:
OSError: [Errno 22] Invalid argument: 'C:\\data\\dask\\<input>'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\RTX2080\AppData\Local\Programs\Python\Python37\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "C:\Users\RTX2080\AppData\Local\Programs\Python\Python37\lib\multiprocessing\spawn.py", line 114, in _main
    prepare(preparation_data)
  File "C:\Users\RTX2080\AppData\Local\Programs\Python\Python37\lib\multiprocessing\spawn.py", line 225, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\Users\RTX2080\AppData\Local\Programs\Python\Python37\lib\multiprocessing\spawn.py", line 277, in _fixup_main_from_path
    run_name="__mp_main__")
  File "C:\Users\RTX2080\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 261, in run_path
    code, fname = _get_code_from_file(run_name, path_name)
  File "C:\Users\RTX2080\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 231, in _get_code_from_file
    with open(fname, "rb") as f:
OSError: [Errno 22] Invalid argument: 'C:\\data\\dask\\<input>'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\RTX2080\AppData\Local\Programs\Python\Python37\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "C:\Users\RTX2080\AppData\Local\Programs\Python\Python37\lib\multiprocessing\spawn.py", line 114, in _main
    prepare(preparation_data)
  File "C:\Users\RTX2080\AppData\Local\Programs\Python\Python37\lib\multiprocessing\spawn.py", line 225, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\Users\RTX2080\AppData\Local\Programs\Python\Python37\lib\multiprocessing\spawn.py", line 277, in _fixup_main_from_path
    run_name="__mp_main__")
  File "C:\Users\RTX2080\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 261, in run_path
    code, fname = _get_code_from_file(run_name, path_name)
  File "C:\Users\RTX2080\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 231, in _get_code_from_file
    with open(fname, "rb") as f:
OSError: [Errno 22] Invalid argument: 'C:\\data\\dask\\<input>'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\RTX2080\AppData\Local\Programs\Python\Python37\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "C:\Users\RTX2080\AppData\Local\Programs\Python\Python37\lib\multiprocessing\spawn.py", line 114, in _main
    prepare(preparation_data)
  File "C:\Users\RTX2080\AppData\Local\Programs\Python\Python37\lib\multiprocessing\spawn.py", line 225, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\Users\RTX2080\AppData\Local\Programs\Python\Python37\lib\multiprocessing\spawn.py", line 277, in _fixup_main_from_path
    run_name="__mp_main__")
  File "C:\Users\RTX2080\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 261, in run_path
    code, fname = _get_code_from_file(run_name, path_name)
  File "C:\Users\RTX2080\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 231, in _get_code_from_file
    with open(fname, "rb") as f:
OSError: [Errno 22] Invalid argument: 'C:\\data\\dask\\<input>'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\RTX2080\AppData\Local\Programs\Python\Python37\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "C:\Users\RTX2080\AppData\Local\Programs\Python\Python37\lib\multiprocessing\spawn.py", line 114, in _main
    prepare(preparation_data)
  File "C:\Users\RTX2080\AppData\Local\Programs\Python\Python37\lib\multiprocessing\spawn.py", line 225, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\Users\RTX2080\AppData\Local\Programs\Python\Python37\lib\multiprocessing\spawn.py", line 277, in _fixup_main_from_path
    run_name="__mp_main__")
  File "C:\Users\RTX2080\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 261, in run_path
    code, fname = _get_code_from_file(run_name, path_name)
  File "C:\Users\RTX2080\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 231, in _get_code_from_file
    with open(fname, "rb") as f:
OSError: [Errno 22] Invalid argument: 'C:\\data\\dask\\<input>'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\RTX2080\AppData\Local\Programs\Python\Python37\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "C:\Users\RTX2080\AppData\Local\Programs\Python\Python37\lib\multiprocessing\spawn.py", line 114, in _main
    prepare(preparation_data)
  File "C:\Users\RTX2080\AppData\Local\Programs\Python\Python37\lib\multiprocessing\spawn.py", line 225, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\Users\RTX2080\AppData\Local\Programs\Python\Python37\lib\multiprocessing\spawn.py", line 277, in _fixup_main_from_path
    run_name="__mp_main__")
  File "C:\Users\RTX2080\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 261, in run_path
    code, fname = _get_code_from_file(run_name, path_name)
  File "C:\Users\RTX2080\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 231, in _get_code_from_file
    with open(fname, "rb") as f:
OSError: [Errno 22] Invalid argument: 'C:\\data\\dask\\<input>'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\RTX2080\AppData\Local\Programs\Python\Python37\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "C:\Users\RTX2080\AppData\Local\Programs\Python\Python37\lib\multiprocessing\spawn.py", line 114, in _main
    prepare(preparation_data)
  File "C:\Users\RTX2080\AppData\Local\Programs\Python\Python37\lib\multiprocessing\spawn.py", line 225, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\Users\RTX2080\AppData\Local\Programs\Python\Python37\lib\multiprocessing\spawn.py", line 277, in _fixup_main_from_path
    run_name="__mp_main__")
  File "C:\Users\RTX2080\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 261, in run_path
    code, fname = _get_code_from_file(run_name, path_name)
Traceback (most recent call last):
  File "C:\Users\RTX2080\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 231, in _get_code_from_file
  File "<string>", line 1, in <module>
    with open(fname, "rb") as f:
OSError: [Errno 22] Invalid argument: 'C:\\data\\dask\\<input>'
  File "C:\Users\RTX2080\AppData\Local\Programs\Python\Python37\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "C:\Users\RTX2080\AppData\Local\Programs\Python\Python37\lib\multiprocessing\spawn.py", line 114, in _main
    prepare(preparation_data)
  File "C:\Users\RTX2080\AppData\Local\Programs\Python\Python37\lib\multiprocessing\spawn.py", line 225, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\Users\RTX2080\AppData\Local\Programs\Python\Python37\lib\multiprocessing\spawn.py", line 277, in _fixup_main_from_path
    run_name="__mp_main__")
  File "C:\Users\RTX2080\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 261, in run_path
    code, fname = _get_code_from_file(run_name, path_name)
  File "C:\Users\RTX2080\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 231, in _get_code_from_file
    with open(fname, "rb") as f:
OSError: [Errno 22] Invalid argument: 'C:\\data\\dask\\<input>'
```

**Comment by mrocklin** [comment]
It looks like your system is having difficulty spawning new processes.  I
don't know why.
Is it possible that you are using the Windows Subsystem for Linux, rather
than normal Windows?

As a short term workaround you can avoid using threads with
`Client(processes=False)`.

**Comment by xiaodaigh** [comment]
I am using pycharm and I set up a venv on Windows, not wsk.

**Comment by xiaodaigh** [comment]
Now it seems ok. I did notice it pops up with a prompt to let it connect to the internet. Perhaps last time I missed the prompt.

`Client(processes=False)` runs ok
