### ISSUE TITLE
Data corruption reading JSON out of S3 files

### ISSUE THREAD

**Issue by mcgrawia** [dask/dask#5336]
Hi,

I came across a strange issue today trying to read 200 newline JSON files in S3 with Dask. I am using the following code to try to load the files:
```python
import dask.bag as db
import json
df = db.read_text('s3://<bucket>/prefix/yyyy-mm-dd/output.json/part*',
                  storage_options={
                      'key': creds.access_key,
                      'secret': creds.secret_key,
                      'token': creds.token
                  })
json_df = df.map(json.loads)
count = json_df.count().compute()
```

When this runs, I get the following traceback: 
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/conda/lib/python3.7/site-packages/dask/base.py", line 175, in compute
    (result,) = compute(self, traverse=False, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/dask/base.py", line 446, in compute
    results = schedule(dsk, keys, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/distributed/client.py", line 2510, in get
    results = self.gather(packed, asynchronous=asynchronous, direct=direct)
  File "/opt/conda/lib/python3.7/site-packages/distributed/client.py", line 1812, in gather
    asynchronous=asynchronous,
  File "/opt/conda/lib/python3.7/site-packages/distributed/client.py", line 753, in sync
    self.loop, func, *args, callback_timeout=callback_timeout, **kwargs
  File "/opt/conda/lib/python3.7/site-packages/distributed/utils.py", line 328, in sync
    six.reraise(*error[0])
  File "/opt/conda/lib/python3.7/site-packages/six.py", line 693, in reraise
    raise value
  File "/opt/conda/lib/python3.7/site-packages/distributed/utils.py", line 313, in f
    result[0] = yield future
  File "/opt/conda/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/opt/conda/lib/python3.7/site-packages/distributed/client.py", line 1668, in _gather
    six.reraise(type(exception), exception, traceback)
  File "/opt/conda/lib/python3.7/site-packages/six.py", line 692, in reraise
    raise value.with_traceback(tb)
  File "/opt/conda/lib/python3.7/site-packages/dask/bag/core.py", line 2457, in empty_safe_apply
    return func(part)
  File "cytoolz/itertoolz.pyx", line 1061, in cytoolz.itertoolz.count
  File "cytoolz/itertoolz.pyx", line 1075, in cytoolz.itertoolz.count
  File "/opt/conda/lib/python3.7/site-packages/dask/bag/core.py", line 2035, in __next__
    return self.f(*vals)
  File "/opt/conda/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/opt/conda/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/opt/conda/lib/python3.7/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Unterminated string starting at: line 1 column 998 (char 997)
```

Normally this kind of error means the file is corrupt but I know this file is correct because I am able to parse the JSON with Spark. I made this adjustment to capture the lines Dask thinks are corrupt JSON:

```python
def try_decode(s):
    try:
        json.loads(s)
    except:
        return s
    return None
bad_rows = df.map(try_decode).filter(lambda row: row is not None)
bad_rows.count().compute()  # 200 
```
I get `200`, so there's exactly 1 malformed line per file. 

Looking at the contents of `bad_rows`, it looks like Dask is corrupting the second JSON line in each file. Even stranger, when I load 1 file out of the 200:
```python 
df = db.read_text('s3://<bucket>/prefix/yyyy-mm-dd/output.json/part-00000',
                  storage_options={
                      'key': creds.access_key,
                      'secret': creds.secret_key,
                      'token': creds.token
                  })
# get the second line of the file
df.take(100)[1]
```
The row shows up correctly. I can't figure out why the data would show up correctly in `.take()` but when I use `.map()` the second row is always cut short and fails to parse.

## Possible fixes
So far, the only way I have gotten it to work is to specify the `blocksize` larger than my largest file (~30MB). I am confused because by default, each file should be mapped to a single partition so if I leave `blocksize` as the default, shouldn't it load the whole file?

## A couple notes:
* The files are organized in an S3 bucket as follows: `s3://<bucket>/prefix/yyyy-mm-dd/output.json/part*`
* There are about 200 files and each one is roughly 25MB plaintext. 
* Each JSON line is fairly long, the one covered in this example is roughly 5000 chars.

## My ENV
```
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main
_py-xgboost-mutex         2.0                       cpu_0    conda-forge
adal                      1.2.2                      py_0    conda-forge
aiohttp                   3.5.4            py37h14c3975_0    conda-forge
altair                    3.2.0                    pypi_0    pypi
appdirs                   1.4.3                    pypi_0    pypi
asn1crypto                0.24.0                   py37_0
async-timeout             3.0.1                   py_1000    conda-forge
attrs                     19.1.0                     py_0    conda-forge
azure-common              1.1.23                   pypi_0    pypi
azure-core                1.0.0b2                  pypi_0    pypi
azure-storage-blob        12.0.0b2                 pypi_0    pypi
backcall                  0.1.0                      py_0    conda-forge
bleach                    3.1.0                      py_0    conda-forge
blinker                   1.4                        py_1    conda-forge
bokeh                     1.3.4                    py37_0    conda-forge
boto3                     1.9.217                    py_0    conda-forge
boto3-extensions          0.12.2                   pypi_0    pypi
botocore                  1.12.217                   py_0    conda-forge
ca-certificates           2019.6.16            hecc5488_0    conda-forge
cachetools                2.1.0                      py_0    conda-forge
certifi                   2019.6.16                py37_1    conda-forge
cffi                      1.12.2           py37h2e261b9_1
chardet                   3.0.4                    py37_1
click                     7.0                      pypi_0    pypi
click-plugins             1.1.1                    pypi_0    pypi
cligj                     0.5.0                    pypi_0    pypi
cloudpickle               1.2.1                      py_0    conda-forge
conda                     4.6.14                   py37_0
cryptography              2.6.1            py37h1ba5d50_0
cycler                    0.10.0                   pypi_0    pypi
cytoolz                   0.10.0           py37h516909a_0    conda-forge
dask                      2.3.0                      py_0    conda-forge
dask-core                 2.3.0                      py_0    conda-forge
dask-glm                  0.1.0                         0    conda-forge
dask-kubernetes           0.9.2                      py_0    conda-forge
dask-ml                   1.0.0                      py_0    conda-forge
dask-xgboost              0.1.7                      py_0    conda-forge
decorator                 4.4.0                      py_0    conda-forge
defusedxml                0.6.0                    pypi_0    pypi
distributed               2.3.0                      py_0    conda-forge
docutils                  0.15.2                   py37_0    conda-forge
entrypoints               0.3                   py37_1000    conda-forge
envkey                    1.2.4                    pypi_0    pypi
fastparquet               0.3.2            py37hc1659b7_0    conda-forge
fiona                     1.8.6                    pypi_0    pypi
freetype                  2.10.0               he983fc9_1    conda-forge
fsspec                    0.4.3                      py_0    conda-forge
future                    0.17.1                   pypi_0    pypi
geopandas                 0.6.0rc1                 pypi_0    pypi
google-auth               1.6.3                      py_0    conda-forge
heapdict                  1.0.0                 py37_1000    conda-forge
holoviews                 1.12.5                   pypi_0    pypi
idna                      2.8                      py37_0
ijson                     2.4                      pypi_0    pypi
intake                    0.5.0                    pypi_0    pypi
intake-sql                0.2.0                    pypi_0    pypi
ipykernel                 5.1.2            py37h5ca1d4c_0    conda-forge
ipython                   7.7.0            py37h5ca1d4c_0    conda-forge
ipython-genutils          0.2.0                    pypi_0    pypi
ipython_genutils          0.2.0                      py_1    conda-forge
ipywidgets                7.5.1                    pypi_0    pypi
isodate                   0.6.0                    pypi_0    pypi
jedi                      0.15.1                   py37_0    conda-forge
jinja2                    2.10.1                     py_0    conda-forge
jmespath                  0.9.4                      py_0    conda-forge
joblib                    0.13.2                   pypi_0    pypi
jpeg                      9c                h14c3975_1001    conda-forge
jsonschema                2.6.0                    pypi_0    pypi
jupyter-server-proxy      1.1.0                      py_0    conda-forge
jupyter_client            5.3.1                      py_0    conda-forge
jupyter_core              4.4.0                      py_0    conda-forge
kiwisolver                1.1.0                    pypi_0    pypi
libblas                   3.8.0               12_openblas    conda-forge
libcblas                  3.8.0               12_openblas    conda-forge
libedit                   3.1.20181209         hc058e9b_0
libffi                    3.2.1                hd88cf55_4
libgcc-ng                 8.2.0                hdf63c60_1
libgfortran-ng            7.3.0                hdf63c60_0
liblapack                 3.8.0               12_openblas    conda-forge
libopenblas               0.3.7                h6e990d7_1    conda-forge
libpng                    1.6.37               hed695b0_0    conda-forge
libsodium                 1.0.17               h516909a_0    conda-forge
libstdcxx-ng              8.2.0                hdf63c60_1
libtiff                   4.0.10            h57b8799_1003    conda-forge
libxgboost                0.90                 he1b5a44_2    conda-forge
llvmlite                  0.29.0           py37hfd453ef_1    conda-forge
locket                    0.2.0                      py_2    conda-forge
lz4-c                     1.8.3             he1b5a44_1001    conda-forge
markupsafe                1.1.1            py37h14c3975_0    conda-forge
matplotlib                3.1.1                    pypi_0    pypi
mistune                   0.8.4           py37h14c3975_1000    conda-forge
msgpack-numpy             0.4.4.3                  pypi_0    pypi
msgpack-python            0.6.1            py37h6bb024c_0    conda-forge
msrest                    0.6.9                    pypi_0    pypi
multidict                 4.5.2           py37h14c3975_1000    conda-forge
multipledispatch          0.6.0                      py_0    conda-forge
nbconvert                 5.6.0                    py37_1    conda-forge
nbformat                  4.4.0                    pypi_0    pypi
ncurses                   6.1                  he6710b0_1
notebook                  6.0.1                    py37_0    conda-forge
numba                     0.45.1           py37hb3f55d8_0    conda-forge
numpy                     1.17.0           py37h95a1406_0    conda-forge
oauthlib                  3.0.1                      py_0    conda-forge
olefile                   0.46                       py_0    conda-forge
openssl                   1.1.1c               h516909a_0    conda-forge
packaging                 19.0                       py_0    conda-forge
pandas                    0.25.1           py37hb3f55d8_0    conda-forge
pandoc                    2.7.3                         0    conda-forge
pandocfilters             1.4.2                      py_1    conda-forge
param                     1.9.1                    pypi_0    pypi
parso                     0.5.1                      py_0    conda-forge
partd                     1.0.0                      py_0    conda-forge
pexpect                   4.7.0                    py37_0    conda-forge
pickleshare               0.7.5                 py37_1000    conda-forge
pillow                    5.3.0           py37h00a061d_1000    conda-forge
pip                       19.2.3                   py37_0    conda-forge
prometheus_client         0.7.1                      py_0    conda-forge
prompt_toolkit            2.0.9                      py_0    conda-forge
psutil                    5.6.3            py37h516909a_0    conda-forge
ptyprocess                0.6.0                   py_1001    conda-forge
py-xgboost                0.90             py37he1b5a44_2    conda-forge
pyasn1                    0.4.6                      py_0    conda-forge
pyasn1-modules            0.2.6                      py_0    conda-forge
pycosat                   0.6.3            py37h14c3975_0
pycparser                 2.19                     py37_0
pycryptodomex             3.9.0                    pypi_0    pypi
pygments                  2.4.2                      py_0    conda-forge
pyjwt                     1.7.1                      py_0    conda-forge
pymysql                   0.9.3                    pypi_0    pypi
pyopenssl                 19.0.0                   py37_0
pyparsing                 2.4.2                      py_0    conda-forge
pyproj                    2.3.0                    pypi_0    pypi
pyrsistent                0.15.4           py37h516909a_0    conda-forge
pysocks                   1.6.8                    py37_0
python                    3.7.3                h0371630_0
python-dateutil           2.8.0                      py_0    conda-forge
python-dotenv             0.10.3                   pypi_0    pypi
python-kubernetes         10.0.1                   py37_0    conda-forge
python-snappy             0.5.4            py37hee44bf9_0    conda-forge
pytz                      2019.2                     py_0    conda-forge
pyviz-comms               0.7.2                    pypi_0    pypi
pyyaml                    5.1.2            py37h516909a_0    conda-forge
pyzmq                     18.0.2           py37h1768529_2    conda-forge
readline                  7.0                  h7b6447c_5
requests                  2.21.0                   py37_0
requests-oauthlib         1.2.0                      py_0    conda-forge
rsa                       3.4.2                      py_1    conda-forge
ruamel_yaml               0.15.46          py37h14c3975_0
s3fs                      0.3.3                      py_0    conda-forge
s3transfer                0.2.1                    py37_0    conda-forge
scikit-learn              0.21.3           py37hcdab131_0    conda-forge
scipy                     1.3.1            py37h921218d_2    conda-forge
se                        5.8.6+463.gaf4e9299          pypi_0    pypi
send2trash                1.5.0                      py_0    conda-forge
sendgrid                  6.0.5                    pypi_0    pypi
setuptools                41.0.0                   py37_0
shapely                   1.7a2                    pypi_0    pypi
simpervisor               0.3                        py_1    conda-forge
six                       1.12.0                   py37_0
snappy                    1.1.7             he1b5a44_1002    conda-forge
snowflake-connector-python 1.9.0                    pypi_0    pypi
snowflake-sqlalchemy      1.1.14                   pypi_0    pypi
sortedcontainers          2.1.0                      py_0    conda-forge
sqlite                    3.27.2               h7b6447c_0
tblib                     1.4.0                      py_0    conda-forge
terminado                 0.8.2                    py37_0    conda-forge
testpath                  0.4.2                   py_1001    conda-forge
thrift                    0.11.0          py37hf484d3e_1001    conda-forge
tk                        8.6.8                hbc83047_0
toolz                     0.10.0                     py_0    conda-forge
tornado                   6.0.3            py37h516909a_0    conda-forge
traitlets                 4.3.2                 py37_1000    conda-forge
urllib3                   1.24.1                   py37_0
wcwidth                   0.1.7                    pypi_0    pypi
webencodings              0.5.1                    pypi_0    pypi
websocket-client          0.56.0                   py37_0    conda-forge
wheel                     0.33.1                   py37_0
widgetsnbextension        3.5.1                    pypi_0    pypi
xgboost                   0.90             py37he1b5a44_2    conda-forge
xlsxwriter                1.2.0                    pypi_0    pypi
xz                        5.2.4                h14c3975_4
yaml                      0.1.7                had09818_2
yarl                      1.3.0           py37h14c3975_1000    conda-forge
zeromq                    4.3.2                he1b5a44_2    conda-forge
zict                      1.0.0                      py_0    conda-forge
zlib                      1.2.11               h7b6447c_3
zstd                      1.4.0                h3b9ef0a_0    conda-forge
```

Thanks for the help, let me know if there's more info I can provide.

**Comment by mcgrawia** [comment]
Thanks @mrocklin! Here's the most minimal example I could come up with. It seems the issue boils down to loading data out of S3. I found an open source dataset that reproduces the issue. It seems when I load data out of S3, extra rows are inserted into the bag:

Setup:
```bash
# copy file locally first
aws s3 cp s3://nyc-tlc/trip\ data/yellow_tripdata_2019-06.csv . --no-sign-request
```

```python
import dask.bag as db

local_file_df = db.read_text('yellow_tripdata_2019-06.csv')
aws_file_df = db.read_text('s3://nyc-tlc/trip data/yellow_tripdata_2019-06.csv', storage_options={'anon': True})

local_lines = local_file_df.count().compute()
aws_lines = aws_file_df.count().compute()

print(aws_lines - local_lines)
# I get a difference of 62 lines
```

**Comment by TomAugspurger** [comment]
Thanks @mcgrawia, I'm taking a look now.

**Comment by TomAugspurger** [comment]
And if you're able to provide a smaller example, I'd be very grateful. I'm on slow public wifi right now, and it's not liking the 600 MB download :)

**Comment by mcgrawia** [comment]
A shoot ok let me find another smaller dataset

**Comment by mcgrawia** [comment]
I think this one could work, only 25MB? `s3://irs-form-990/index_2011.csv`

```python
import dask.bag as db

# setup: copy file locally first
# aws s3 cp s3://irs-form-990/index_2011.csv . --no-sign-request

local_file_df = db.read_text('index_2011.csv')
aws_file_df = db.read_text('s3://irs-form-990/index_2011.csv',
                           storage_options={'anon': True})

# line counts differ

local_lines = local_file_df.count().compute()
aws_lines = aws_file_df.count().compute()

print(aws_lines - local_lines)


```

**Comment by TomAugspurger** [comment]
Thanks, able to reproduce with that.

Unfortunately, I'm not able to reproduce it using moto (which we use for tests). I'm facing a similar issue trying to write a test for another issue, so hopefully I'll have something to report back later today.

**Comment by mcgrawia** [comment]
Ok glad to hear you can reproduce. Look forward to hearing more! Thanks

**Comment by TomAugspurger** [comment]
I may have inadvertently fixed this with https://github.com/dask/s3fs/pull/229. Can you try with s3fs master. I'll be doing a release later today.

**Comment by mcgrawia** [comment]
@TomAugspurger looks like the new version `0.3.4` did the trick! The json parsing works now. Do you know how that issue resulted in the malformed rows?

**Comment by TomAugspurger** [comment]
Glad to hear it!

> Do you know how that issue resulted in the extra, malformed rows?

I may be wrong, but my best guess is a bad interaction between our in-memory cache of fetches from S3, and behavior when we make an HTTP request to S3 with a "negative" byte range. In this case we've reached the end of the file, but the caller may do some additional `.read()` calls. So we do another `fetch`. This (I think) ends up redownloading the entire file, since HTTP servers are supposed to ignore the range field when it's negative. That extra, duplicate, data gets added to our in-memory cache, leading to the duplicate rows.

I could be wrong about pieces of that, but I think that's the gist.

Once Martin is back online, I'll talk with him about testing strategies that could have caught this. I don't see an easy way right now, since moto behaves differently than S3.

**Comment by mcgrawia** [comment]
ok sounds good, thanks for the explanation
