### ISSUE TITLE
Array won't save after da.insert call

### ISSUE THREAD

**Issue by balbok0** [dask/dask#5425]
Hi,

I have been recently trying to load the [birds dataset](http://www.vision.caltech.edu/visipedia/CUB-200-2011.html) using dask.
Here is a [link to download](http://www.vision.caltech.edu/visipedia-data/CUB-200-2011/CUB_200_2011.tgz) I used from the website above.

## Code
**In order to run this code you have to have the above-mentioned birds dataset downloaded and with the root of its directory at `data/CUB_200_2011`**
My code works fine until I want to save it to a file:

```python
import dask.array as da
from dask.array.image import imread
from tqdm import trange, tqdm
import numpy as np
from pathlib import Path

path_to_data = Path('data/CUB_200_2011')  # Path to root of birds dataset
imgs = da.from_array(np.empty(shape=[0, 500, 500, 3], dtype=np.float), chunks=(10, 500, 500, 3))
with open(path_to_data / 'images.txt') as img_f:
    lines = img_f.readlines()[:100]  # It's 80 GBs
    for img_idx, image_name in enumerate(lines):
        image_name = '_'.join(image_name.strip().split(' ')[1:])
        curr_img = imread(str(path_to_data / 'images' / image_name))

        if len(curr_img.shape) == 3:  # Grayscale to RGB
            curr_img = curr_img[..., np.newaxis]
            curr_img = np.concatenate((curr_img, curr_img, curr_img), axis=3)

        curr_img = curr_img / 255.  # Normalize to [0, 1]
        curr_img = np.pad(  # Pad to 500x500
            curr_img,
            [(0, 0), (0, 500 - curr_img.shape[1]), (0, 500 - curr_img.shape[2]), (0, 0)],
            'constant',
            constant_values=0
        )
        imgs = da.insert(imgs, [img_idx], [curr_img], 0)


# imgs.to_tiledb('__test.tdb')
da.to_npy_stack(str(path_to_data / '__test'), imgs, axis=0)
```
I have tried also `to_hdf` and `to_zarr` which also crashed with different messages.

## Crash Report
Here are crash reports for `to_tiledb` and `to_npy_stack` respectively:
`to_tiledb`:
```
Traceback (most recent call last):
  File "__tmp_train_resnext.py", line 29, in <module>
    imgs.to_tiledb('__test.tdb')
  File "/home/balbok/miniconda3/envs/adaptivefun/lib/python3.7/site-packages/dask/array/core.py", line 2307, in to_tiledb
    return to_tiledb(self, uri, *args, **kwargs)
  File "/home/balbok/miniconda3/envs/adaptivefun/lib/python3.7/site-packages/dask/array/tiledb_io.py", line 143, in to_tiledb
    uri, darray, tile=chunks, config=tiledb_config, key=key, **kwargs
  File "/home/balbok/miniconda3/envs/adaptivefun/lib/python3.7/site-packages/tiledb/highlevel.py", line 80, in empty_like
    schema = schema_like(arr, tile=tile, ctx=ctx)
  File "tiledb/libtiledb.pyx", line 142, in tiledb.libtiledb.schema_like
  File "tiledb/libtiledb.pyx", line 183, in tiledb.libtiledb.schema_like_numpy
AttributeError: 'Array' object has no attribute 'flat'
```
`to_npy_stack`:
```
Traceback (most recent call last):
  File "__tmp_train_resnext.py", line 30, in <module>
    da.to_npy_stack(str(path_to_data / '__test'), imgs, axis=0)
  File "/home/balbok/miniconda3/envs/adaptivefun/lib/python3.7/site-packages/dask/array/core.py", line 4681, in to_npy_stack
    compute_as_if_collection(Array, graph, list(dsk))
  File "/home/balbok/miniconda3/envs/adaptivefun/lib/python3.7/site-packages/dask/base.py", line 202, in compute_as_if_collection
    return schedule(dsk2, keys, **kwargs)
  File "/home/balbok/miniconda3/envs/adaptivefun/lib/python3.7/site-packages/dask/threaded.py", line 82, in get
    **kwargs
  File "/home/balbok/miniconda3/envs/adaptivefun/lib/python3.7/site-packages/dask/local.py", line 491, in get_async
    raise_exception(exc, tb)
  File "/home/balbok/miniconda3/envs/adaptivefun/lib/python3.7/site-packages/dask/compatibility.py", line 130, in reraise
    raise exc
  File "/home/balbok/miniconda3/envs/adaptivefun/lib/python3.7/site-packages/dask/local.py", line 233, in execute_task
    result = _execute_task(task, data)
  File "/home/balbok/miniconda3/envs/adaptivefun/lib/python3.7/site-packages/dask/core.py", line 118, in _execute_task
    args2 = [_execute_task(a, cache) for a in args]
  File "/home/balbok/miniconda3/envs/adaptivefun/lib/python3.7/site-packages/dask/core.py", line 118, in <listcomp>
    args2 = [_execute_task(a, cache) for a in args]
  File "/home/balbok/miniconda3/envs/adaptivefun/lib/python3.7/site-packages/dask/core.py", line 119, in _execute_task
    return func(*args2)
  File "/home/balbok/miniconda3/envs/adaptivefun/lib/python3.7/site-packages/numpy/lib/stride_tricks.py", line 182, in broadcast_to
    return _broadcast_to(array, shape, subok=subok, readonly=True)
  File "/home/balbok/miniconda3/envs/adaptivefun/lib/python3.7/site-packages/numpy/lib/stride_tricks.py", line 129, in _broadcast_to
    op_flags=[op_flag], itershape=shape, order='C')
ValueError: input operand has more dimensions than allowed by the axis remapping
```

## Possible Reason
I believe that a problem is related to `da.insert` call, since I've been trying to reproduce it, and it didn't crash without it.  

Thank you for your time and help!

**Comment by jrbourbeau** [comment]
Thanks for opening up an issue @balbok0! Are you able to produce a minimal reproducible example (https://blog.dask.org/2018/02/28/minimal-bug-reports)? 

This is snippet performing similar operations to your example?

```python

In [1]: import dask.array as da

In [2]: a = da.random.random((1, 10, 10))

In [3]: b = da.random.random((10, 10))

In [4]: c = da.insert(a, [0], [b], 0)

In [5]: c
Out[5]: dask.array<concatenate, shape=(2, 10, 10), dtype=object, chunksize=(1, 10, 10), chunktype=numpy.ndarray>

In [6]: da.to_npy_stack('tmp_data', c, axis=0)
```

**Comment by balbok0** [comment]
Hi, thank you for such a fast response! The example you provided is working (i.e. it doesn't throw an error).  
I will try to see if I can make a simpler example, but it might be related to `imread` function. I'll try to reduce the example even further.

**Comment by balbok0** [comment]
Hi @jrbourbeau,
after trying to get a smaller example I believe I found that those are 2 separate problems.

## `to_tiledb`
For `to_tiledb` your minimal example doesn't work. It throws exactly the same error as I mentioned above.
Here is code snippet to reproduce the problem:
```python
import dask.array as da
a = da.random.random((1, 10, 10), chunks=(10, 10, 10))
b = da.random.random((10, 10))
c = da.insert(a, [0], [b], 0)
print(c)
c.to_tiledb('__test.tdb')
```

## `to_npy_stack`
I Identified and fixed one problem with my code snippet. In particular switching from `np.pad` to `da.pad` solves the problem, but creates another one. The code stalls and `Ctrl+C` doesn't seem to affect it much (I had to kill the process).

```python
import dask.array as da
from dask.array.image import imread
import numpy as np
from pathlib import Path

path_to_data = Path('data/CUB_200_2011')
with open(path_to_data / 'images.txt') as img_f:
    lines = img_f.readlines()[:10]

imgs = da.from_array(np.zeros(shape=(0, 500, 500, 3), dtype=np.float), chunks=(2, 500, 500, 3))
for img_idx, image_name in enumerate(lines):
    print(img_idx)
    # Put images into numpy form
    image_name = '_'.join(image_name.strip().split(' ')[1:])
    curr_img = imread(str(path_to_data / 'images' / image_name))

    # Padding breaks to_npy_stack
    curr_img = da.pad(  # Pad to 500x500
        curr_img,
        [(0, 0), (0, 500 - curr_img.shape[1]), (0, 500 - curr_img.shape[2]), (0, 0)],
        'constant',
        constant_values=0
    )

    imgs = da.insert(imgs, [img_idx], [curr_img], axis=0)

imgs = da.rechunk(imgs, (2, 500, 500, 3))
da.to_npy_stack('__test', imgs, axis=0)
```

Sorry for using birds dataset. If you want to I can upload a folder with first 10 images for easier debugging.

**Comment by mrocklin** [comment]
> Sorry for using birds dataset. If you want to I can upload a folder with first 10 images for easier debugging.

I recommend reading through https://blog.dask.org/2018/02/28/minimal-bug-reports (@jrbourbeau linked to this earlier).  It has suggestions on how to prepare a minimal example.

If you're looking to construct a dask array from many lazy functions, I recommend reading through this: https://blog.dask.org/2019/06/20/load-image-data

**Comment by mrocklin** [comment]
I'm going to go ahead and close this.  If we get a minimal reproducible example I'd be happy to reopen.
