### ISSUE TITLE
exceptions on functools.lru_cache

### ISSUE THREAD

**Issue by goldenbull** [dask/dask#5477]
dask 2.5.2
distributed 2.5.2

I started a scheduler and two workers:
```
C:\chenjn\quanttech>pipenv run start dask-scheduler --local-directory .dask
C:\chenjn\quanttech>pipenv run start dask-worker --local-directory .dask --nprocs 2 --nthreads 1 --memory-limit 0  localhost:8786
```

Then I tried to run a simple piece of code on the scheduler, here is the source code:
``` python
from dask.distributed import Client, LocalCluster
import functools

@functools.lru_cache(1024)
def worker_func_internal(n):
    print(f"processing {n}")
    return n * n

def worker_func(n):
    return worker_func_internal(n % 13)

if __name__ == '__main__':
    client = Client("localhost:8786")
    args = list(range(100))
    ret = client.gather(client.map(worker_func, args))
    print(ret)
```

This script ends up in a lot of exceptions:
```
...
AttributeError: Can't get attribute 'worker_func_internal' on <module '__main__' (built-in)>
distributed.protocol.pickle - INFO - Failed to deserialize b'\x80\x04\x95\x08\x02\x00\x00\x00\x00\x00\x00\x8c\x17cloudpickle.cloudpickle\x94\x8c\x0e_fill_function\x94\x93\x94(h\x00\x8c\x0f_make_skel_func\x94\x93\x94h\x00\x8c\r_builtin_type\x94\x93\x94\x8c\x08CodeType\x94\x85\x94R\x94(K\x01K\x00K\x01K\x03KCC\x0ct\x00|\x00d\x01\x16\x00\x83\x01S\x00\x94NK\r\x86\x94\x8c\x14worker_func_internal\x94\x85\x94\x8c\x01n\x94\x85\x94\x8c0C:/chenjn/quanttech/qtbase/users/chenjn/dask1.py\x94\x8c\x0bworker_func\x94K\tC\x02\x00\x01\x94))t\x94R\x94J\xff\xff\xff\xff}\x94(\x8c\x0b__package__\x94N\x8c\x08__name__\x94\x8c\x08__main__\x94\x8c\x08__file__\x94\x8c0C:/chenjn/quanttech/qtbase/users/chenjn/dask1.py\x94u\x87\x94R\x94}\x94(\x8c\x07globals\x94}\x94h\x0ch\x18h\x0c\x93\x94s\x8c\x08defaults\x94N\x8c\x04dict\x94}\x94\x8c\x0eclosure_values\x94N\x8c\x06module\x94h\x18\x8c\x04name\x94h\x11\x8c\x03doc\x94N\x8c\x17_cloudpickle_submodules\x94]\x94\x8c\x0bannotations\x94}\x94\x8c\x08qualname\x94h\x11\x8c\nkwdefaults\x94NutR.'
Traceback (most recent call last):
  File "c:\chenjn\quanttech\.venv\lib\site-packages\distributed\protocol\pickle.py", line 59, in loads
    return pickle.loads(x)
AttributeError: Can't get attribute 'worker_func_internal' on <module '__main__' (built-in)>
distributed.worker - WARNING - Could not deserialize task
Traceback (most recent call last):
  File "c:\chenjn\quanttech\.venv\lib\site-packages\distributed\worker.py", line 2354, in _maybe_deserialize_task
    function, args, kwargs = _deserialize(*self.tasks[key])
  File "c:\chenjn\quanttech\.venv\lib\site-packages\distributed\worker.py", line 3134, in _deserialize
    function = pickle.loads(function)
  File "c:\chenjn\quanttech\.venv\lib\site-packages\distributed\protocol\pickle.py", line 59, in loads
    return pickle.loads(x)
AttributeError: Can't get attribute 'worker_func_internal' on <module '__main__' (built-in)>
```

But if I start the cluster in source code, everythings works fine:
```python
if __name__ == '__main__':
    client = Client(LocalCluster(n_workers=2, threads_per_worker=1, processes=True))
    args = list(range(100))
    ret = client.gather(client.map(worker_func, args))
    print(ret)
```

So my question is, how to use `functools.lru_cache` correctly?

**Comment by TomAugspurger** [comment]
Can lru_caches be pickled safely between processes?

**Comment by quasiben** [comment]
I don't think so xref: https://github.com/cloudpipe/cloudpickle/issues/178 

Looks like ray is facing similar difficulties https://github.com/ray-project/ray/issues/5766

**Comment by mrocklin** [comment]
Maybe try toolz.memoize ?

**Comment by TomAugspurger** [comment]
@goldenbull let us know if `tools.memoize` works out for you, so future readers know if it's an option.

Closing this since I don't think there's anything for dask to do at the moment.

**Comment by goldenbull** [comment]
`@toolz.functoolz.memoize` works fine. I think maybe redis is more suitable for the distributed caching scenario, in spite that cross-process caching is a little slower than in-process caching.
