### ISSUE TITLE
pip install gives ImportError: No module named 'dask' in venv

### ISSUE THREAD

**Issue by shashi-netra** [dask/dask#5481]
I am trying dask + xgboost for the first time and created a venv on my ubuntu 18 box. and did the `pip install dask[complete]`. However, when I run the code below (it's a simple multi-class classifier with softmax), I keep getting this error:
```
    from dask.distributed import Client
ImportError: No module named 'dask'
```
Upon doing a `pip install -U dask[complete] `, I get a "Requirement already satisfied" for all the packages. Not sure what I am doing wrong.

```
from dask.distributed import Client
# It's recommended to use dask_cuda for GPU assignment
from dask_cuda import LocalCUDACluster
from dask import array as da
import xgboost

def main():
    print ("[+] loading training jobs")
    jobs_dict = load_training_jobs()
    le = LabelEncoder()
    X = jobs_dict.values();y_ = jobs_dict.keys()

    print(set(y_))
    y = le.fit_transform(y_)

    X_train, X_test, y_train, y_test= train_test_split(np.array(X), y, test_size=0.25, random_state=7,shuffle=True)

    clf = xgboost.dask.DaskXGBClassifier(objective = 'multi:softmax')
    clf.set_params(tree_method='gpu_hist')
    # assigning client here is optional
    #clf.client = client

    clf.fit(X_train, y_train, eval_set=[(X_test, y_test)])
    return clf                  # returning the trained model

if __name__ == '__main__':
    # With dask cuda, one can scale up XGBoost to arbitrary GPU clusters.
    # `LocalCUDACluster` used here is only for demonstration purpose.
    with LocalCUDACluster() as cluster:
        with Client(cluster) as client:
            main(client)

```

**Comment by TomAugspurger** [comment]
Can you post the output of the following?

1. Creating / activating a new virtualenv / conda env
2. Installing dask into that env

**Comment by jrbourbeau** [comment]
Just checking in here @shashi-netra, could you provide the information @TomAugspurger asked about? It will probably be difficult to debug otherwise

**Comment by shashi-netra** [comment]
Hi there, apologies for the delayed response. BUt here is the output I get when installing into a new venv

```
me@mybox:~$ source ~/env_cuda_py3/bin/activate
(env_cuda_py3) superadmin@NS1:~$ pip install -U dask[complete] 
Collecting dask[complete]
  Downloading https://files.pythonhosted.org/packages/f8/70/b7e55088c6a6c9d5e786c85738d92e99c4bf085fc4009d5ffe483cd6b44f/dask-2.6.0-py3-none-any.whl (760kB)
    100% |████████████████████████████████| 768kB 9.0MB/s 
Requirement already satisfied, skipping upgrade: cloudpickle>=0.2.1; extra == "complete" in ./env_cuda_py3/lib/python3.5/site-packages (from dask[complete]) (0.6.1)
Collecting fsspec>=0.5.1; extra == "complete" (from dask[complete])
Requirement already satisfied, skipping upgrade: numpy>=1.13.0; extra == "complete" in ./env_cuda_py3/lib/python3.5/site-packages (from dask[complete]) (1.15.4)
Collecting distributed>=2.0; extra == "complete" (from dask[complete])
  Downloading https://files.pythonhosted.org/packages/8b/11/8ce552c3bf61cdb798cfba19dcd10d07ecbdae26a8ba57fce85f19eb9205/distributed-2.6.0-py3-none-any.whl (560kB)
    100% |████████████████████████████████| 563kB 11.0MB/s 
Collecting partd>=0.3.10; extra == "complete" (from dask[complete])
  Using cached https://files.pythonhosted.org/packages/8b/17/09c352519da1db31634979c3aa9126078e9ece0f561c5f641e0649b78905/partd-1.0.0-py2.py3-none-any.whl
Collecting bokeh>=1.0.0; extra == "complete" (from dask[complete])
Requirement already satisfied, skipping upgrade: toolz>=0.7.3; extra == "complete" in ./env_cuda_py3/lib/python3.5/site-packages (from dask[complete]) (0.9.0)
Collecting pandas>=0.21.0; extra == "complete" (from dask[complete])
  Using cached https://files.pythonhosted.org/packages/74/24/0cdbf8907e1e3bc5a8da03345c23cbed7044330bb8f73bb12e711a640a00/pandas-0.24.2-cp35-cp35m-manylinux1_x86_64.whl
Collecting psutil>=5.0 (from distributed>=2.0; extra == "complete"->dask[complete])
  Downloading https://files.pythonhosted.org/packages/1c/ca/5b8c1fe032a458c2c4bcbe509d1401dca9dda35c7fc46b36bb81c2834740/psutil-5.6.3.tar.gz (435kB)
    100% |████████████████████████████████| 440kB 11.3MB/s 
Collecting tblib (from distributed>=2.0; extra == "complete"->dask[complete])
  Using cached https://files.pythonhosted.org/packages/64/b5/ebb1af4d843047ccd7292b92f5e5f8643153e8b95d14508d9fe3b35f7004/tblib-1.4.0-py2.py3-none-any.whl
Collecting click>=6.6 (from distributed>=2.0; extra == "complete"->dask[complete])
  Downloading https://files.pythonhosted.org/packages/fa/37/45185cb5abbc30d7257104c434fe0b07e5a195a6847506c074527aa599ec/Click-7.0-py2.py3-none-any.whl (81kB)
    100% |████████████████████████████████| 81kB 18.8MB/s 
Collecting sortedcontainers!=2.0.0,!=2.0.1 (from distributed>=2.0; extra == "complete"->dask[complete])
  Using cached https://files.pythonhosted.org/packages/13/f3/cf85f7c3a2dbd1a515d51e1f1676d971abe41bba6f4ab5443240d9a78e5b/sortedcontainers-2.1.0-py2.py3-none-any.whl
Requirement already satisfied, skipping upgrade: pyyaml in ./env_cuda_py3/lib/python3.5/site-packages (from distributed>=2.0; extra == "complete"->dask[complete]) (3.13)
Requirement already satisfied, skipping upgrade: tornado>=5 in ./env_cuda_py3/lib/python3.5/site-packages (from distributed>=2.0; extra == "complete"->dask[complete]) (5.1.1)
Collecting zict>=0.1.3 (from distributed>=2.0; extra == "complete"->dask[complete])
  Using cached https://files.pythonhosted.org/packages/64/b4/a904be4184814adb9dfc2e679c4e611392080a32726a657a34cab93b38c2/zict-1.0.0-py2.py3-none-any.whl
Collecting msgpack (from distributed>=2.0; extra == "complete"->dask[complete])
  Downloading https://files.pythonhosted.org/packages/a5/fa/5bd627f889327999736350637d7e759a17486d32b69be0c703f7abc64e4e/msgpack-0.6.2-cp35-cp35m-manylinux1_x86_64.whl (244kB)
    100% |████████████████████████████████| 245kB 15.4MB/s 
Collecting locket (from partd>=0.3.10; extra == "complete"->dask[complete])
Collecting packaging>=16.8 (from bokeh>=1.0.0; extra == "complete"->dask[complete])
  Downloading https://files.pythonhosted.org/packages/cf/94/9672c2d4b126e74c4496c6b3c58a8b51d6419267be9e70660ba23374c875/packaging-19.2-py2.py3-none-any.whl
Requirement already satisfied, skipping upgrade: pillow>=4.0 in ./env_cuda_py3/lib/python3.5/site-packages (from bokeh>=1.0.0; extra == "complete"->dask[complete]) (5.4.0)
Requirement already satisfied, skipping upgrade: Jinja2>=2.7 in ./env_cuda_py3/lib/python3.5/site-packages (from bokeh>=1.0.0; extra == "complete"->dask[complete]) (2.10)
Requirement already satisfied, skipping upgrade: python-dateutil>=2.1 in ./env_cuda_py3/lib/python3.5/site-packages (from bokeh>=1.0.0; extra == "complete"->dask[complete]) (2.7.5)
Requirement already satisfied, skipping upgrade: six>=1.5.2 in ./env_cuda_py3/lib/python3.5/site-packages (from bokeh>=1.0.0; extra == "complete"->dask[complete]) (1.12.0)
Collecting pytz>=2011k (from pandas>=0.21.0; extra == "complete"->dask[complete])
  Downloading https://files.pythonhosted.org/packages/e7/f9/f0b53f88060247251bf481fa6ea62cd0d25bf1b11a87888e53ce5b7c8ad2/pytz-2019.3-py2.py3-none-any.whl (509kB)
    100% |████████████████████████████████| 512kB 10.6MB/s 
Collecting heapdict (from zict>=0.1.3->distributed>=2.0; extra == "complete"->dask[complete])
  Using cached https://files.pythonhosted.org/packages/b6/9d/cd4777dbcf3bef9d9627e0fe4bc43d2e294b1baeb01d0422399d5e9de319/HeapDict-1.0.1-py3-none-any.whl
Requirement already satisfied, skipping upgrade: pyparsing>=2.0.2 in ./env_cuda_py3/lib/python3.5/site-packages (from packaging>=16.8->bokeh>=1.0.0; extra == "complete"->dask[complete]) (2.3.0)
Requirement already satisfied, skipping upgrade: MarkupSafe>=0.23 in ./env_cuda_py3/lib/python3.5/site-packages (from Jinja2>=2.7->bokeh>=1.0.0; extra == "complete"->dask[complete]) (1.1.0)
Building wheels for collected packages: psutil
  Building wheel for psutil (setup.py) ... done
  Stored in directory: /home/superadmin/.cache/pip/wheels/90/7e/74/bb640d77775e6b6a78bcc3120f9fea4d2a28b2706de1cff37d
Successfully built psutil
Installing collected packages: fsspec, psutil, tblib, click, sortedcontainers, heapdict, zict, msgpack, distributed, locket, partd, packaging, bokeh, pytz, pandas, dask
  Found existing installation: dask 1.0.0
    Uninstalling dask-1.0.0:
      Successfully uninstalled dask-1.0.0
Successfully installed bokeh-1.3.4 click-7.0 dask-2.6.0 distributed-2.6.0 fsspec-0.5.2 heapdict-1.0.1 locket-0.2.0 msgpack-0.6.2 packaging-19.2 pandas-0.24.2 partd-1.0.0 psutil-5.6.3 pytz-2019.3 sortedcontainers-2.1.0 tblib-1.4.0 zict-1.0.0
You are using pip version 19.0.1, however version 19.3.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```

Upon trying to run the above script:
```
(env_cuda_py3) me@mybox:~/safety$ python run-dask.py 
Traceback (most recent call last):
  File "run-dask.py", line 3, in <module>
    from dask_cuda import LocalCUDACluster
ImportError: No module named 'dask_cuda'
(env_cuda_py3) me@mybox:~/safety$ python3 run-dask.py 
Traceback (most recent call last):
  File "run-dask.py", line 3, in <module>
    from dask_cuda import LocalCUDACluster
ImportError: No module named 'dask_cuda'

```

**Comment by mrocklin** [comment]
It sounds like you want to install the dask-cuda package

    pip install dask-cuda
