### ISSUE TITLE
bokeh dashboard throws exception when showing all workers

### ISSUE THREAD

**Issue by goldenbull** [dask/dask#5487]
dask 2.5.2
distributed 2.5.2
bokeh 1.3.4

start scheduler and workers:
```
C:\chenjn\quanttech>pipenv run start dask-scheduler --local-directory .dask
C:\chenjn\quanttech>pipenv run start dask-worker --local-directory .dask --nprocs 2 --nthreads 1 --memory-limit 0  localhost:8786
```

then start a browser and navigate to http://localhost:8787/workers
the scheduler throws exceptions:
```
distributed.scheduler - INFO - -----------------------------------------------
distributed.scheduler - INFO - Local Directory:                      .dask
distributed.scheduler - INFO - -----------------------------------------------
distributed.scheduler - INFO - Clear task state
distributed.dashboard.proxy - INFO - To route to workers diagnostics web server please install jupyter-server-proxy: pip install jupyter-server-proxy
distributed.scheduler - INFO -   Scheduler at:   tcp://192.168.3.47:8786
distributed.scheduler - INFO -   dashboard at:                     :8787
distributed.scheduler - INFO - Register tcp://127.0.0.1:55027
distributed.scheduler - INFO - Starting worker compute stream, tcp://127.0.0.1:55027
distributed.core - INFO - Starting established connection
distributed.scheduler - INFO - Register tcp://127.0.0.1:55030
distributed.scheduler - INFO - Starting worker compute stream, tcp://127.0.0.1:55030
distributed.core - INFO - Starting established connection
distributed.utils - ERROR - Out of range float values are not JSON compliant
Traceback (most recent call last):
  File "c:\chenjn\quanttech\.venv\lib\site-packages\distributed\utils.py", line 662, in log_errors
    yield
  File "c:\chenjn\quanttech\.venv\lib\site-packages\distributed\dashboard\scheduler.py", line 647, in update
    self.nbytes_figure.x_range.end = max_limit
  File "c:\chenjn\quanttech\.venv\lib\site-packages\bokeh\core\has_props.py", line 280, in __setattr__
    super(HasProps, self).__setattr__(name, value)
  File "c:\chenjn\quanttech\.venv\lib\site-packages\bokeh\core\property\descriptors.py", line 545, in __set__
    self._internal_set(obj, value, setter=setter)
  File "c:\chenjn\quanttech\.venv\lib\site-packages\bokeh\core\property\descriptors.py", line 769, in _internal_set
    self._real_set(obj, old, value, hint=hint, setter=setter)
  File "c:\chenjn\quanttech\.venv\lib\site-packages\bokeh\core\property\descriptors.py", line 838, in _real_set
    self._trigger(obj, old, value, hint=hint, setter=setter)
  File "c:\chenjn\quanttech\.venv\lib\site-packages\bokeh\core\property\descriptors.py", line 915, in _trigger
    obj.trigger(self.name, old, value, hint, setter)
  File "c:\chenjn\quanttech\.venv\lib\site-packages\bokeh\model.py", line 704, in trigger
    super(Model, self).trigger(attr, old, new, hint=hint, setter=setter)
  File "c:\chenjn\quanttech\.venv\lib\site-packages\bokeh\util\callback_manager.py", line 161, in trigger
    self._document._notify_change(self, attr, old, new, hint, setter, invoke)
  File "c:\chenjn\quanttech\.venv\lib\site-packages\bokeh\document\document.py", line 1005, in _notify_change
    self._trigger_on_change(event)
  File "c:\chenjn\quanttech\.venv\lib\site-packages\bokeh\document\document.py", line 1100, in _trigger_on_change
    self._with_self_as_curdoc(invoke_callbacks)
  File "c:\chenjn\quanttech\.venv\lib\site-packages\bokeh\document\document.py", line 1113, in _with_self_as_curdoc
    return f()
  File "c:\chenjn\quanttech\.venv\lib\site-packages\bokeh\document\document.py", line 1099, in invoke_callbacks
    cb(event)
  File "c:\chenjn\quanttech\.venv\lib\site-packages\bokeh\document\document.py", line 669, in <lambda>
    self._callbacks[receiver] = lambda event: event.dispatch(receiver)
  File "c:\chenjn\quanttech\.venv\lib\site-packages\bokeh\document\events.py", line 244, in dispatch
    super(ModelChangedEvent, self).dispatch(receiver)
  File "c:\chenjn\quanttech\.venv\lib\site-packages\bokeh\document\events.py", line 126, in dispatch
    receiver._document_patched(self)
  File "c:\chenjn\quanttech\.venv\lib\site-packages\bokeh\server\session.py", line 223, in _document_patched
    self._pending_writes.append(connection.send_patch_document(event))
  File "c:\chenjn\quanttech\.venv\lib\site-packages\bokeh\server\connection.py", line 76, in send_patch_document
    msg = self.protocol.create('PATCH-DOC', [event])
  File "c:\chenjn\quanttech\.venv\lib\site-packages\bokeh\protocol\__init__.py", line 80, in create
    return self._messages[msgtype].create(*args, **kwargs)
  File "c:\chenjn\quanttech\.venv\lib\site-packages\bokeh\protocol\messages\patch_doc.py", line 93, in create
    patch_json, buffers = process_document_events(events, use_buffers)
  File "c:\chenjn\quanttech\.venv\lib\site-packages\bokeh\protocol\messages\patch_doc.py", line 136, in process_document_events
    return serialize_json(json), buffers if use_buffers else []
  File "c:\chenjn\quanttech\.venv\lib\site-packages\bokeh\core\json_encoder.py", line 161, in serialize_json
    return json.dumps(obj, cls=BokehJSONEncoder, allow_nan=False, indent=indent, separators=separators, sort_keys=True, **kwargs)
  File "C:\Python37\Lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "C:\Python37\Lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Python37\Lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
ValueError: Out of range float values are not JSON compliant
bokeh.util.tornado - ERROR - Error thrown from periodic callback:
bokeh.util.tornado - ERROR - Traceback (most recent call last):
  File "c:\chenjn\quanttech\.venv\lib\site-packages\tornado\gen.py", line 501, in callback
    result_list.append(f.result())
  File "c:\chenjn\quanttech\.venv\lib\site-packages\tornado\gen.py", line 748, in run
    yielded = self.gen.send(value)
  File "c:\chenjn\quanttech\.venv\lib\site-packages\bokeh\server\session.py", line 70, in _needs_document_lock_wrapper
    result = yield yield_for_all_futures(func(self, *args, **kwargs))
  File "c:\chenjn\quanttech\.venv\lib\site-packages\bokeh\server\session.py", line 191, in with_document_locked
    return func(*args, **kwargs)
  File "c:\chenjn\quanttech\.venv\lib\site-packages\bokeh\document\document.py", line 1127, in wrapper
    return doc._with_self_as_curdoc(invoke)
  File "c:\chenjn\quanttech\.venv\lib\site-packages\bokeh\document\document.py", line 1113, in _with_self_as_curdoc
    return f()
  File "c:\chenjn\quanttech\.venv\lib\site-packages\bokeh\document\document.py", line 1126, in invoke
    return f(*args, **kwargs)
  File "c:\chenjn\quanttech\.venv\lib\site-packages\distributed\dashboard\components.py", line 698, in <lambda>
    doc.add_periodic_callback(lambda: update(ref), interval)
  File "c:\chenjn\quanttech\.venv\lib\site-packages\distributed\dashboard\components.py", line 705, in update
    comp.update()
  File "c:\chenjn\quanttech\.venv\lib\site-packages\bokeh\core\property\validation.py", line 97, in func
    return input_function(*args, **kwargs)
  File "c:\chenjn\quanttech\.venv\lib\site-packages\distributed\dashboard\scheduler.py", line 647, in update
    self.nbytes_figure.x_range.end = max_limit
  File "c:\chenjn\quanttech\.venv\lib\site-packages\bokeh\core\has_props.py", line 280, in __setattr__
    super(HasProps, self).__setattr__(name, value)
  File "c:\chenjn\quanttech\.venv\lib\site-packages\bokeh\core\property\descriptors.py", line 545, in __set__
    self._internal_set(obj, value, setter=setter)
  File "c:\chenjn\quanttech\.venv\lib\site-packages\bokeh\core\property\descriptors.py", line 769, in _internal_set
    self._real_set(obj, old, value, hint=hint, setter=setter)
  File "c:\chenjn\quanttech\.venv\lib\site-packages\bokeh\core\property\descriptors.py", line 838, in _real_set
    self._trigger(obj, old, value, hint=hint, setter=setter)
  File "c:\chenjn\quanttech\.venv\lib\site-packages\bokeh\core\property\descriptors.py", line 915, in _trigger
    obj.trigger(self.name, old, value, hint, setter)
  File "c:\chenjn\quanttech\.venv\lib\site-packages\bokeh\model.py", line 704, in trigger
    super(Model, self).trigger(attr, old, new, hint=hint, setter=setter)
  File "c:\chenjn\quanttech\.venv\lib\site-packages\bokeh\util\callback_manager.py", line 161, in trigger
    self._document._notify_change(self, attr, old, new, hint, setter, invoke)
  File "c:\chenjn\quanttech\.venv\lib\site-packages\bokeh\document\document.py", line 1005, in _notify_change
    self._trigger_on_change(event)
  File "c:\chenjn\quanttech\.venv\lib\site-packages\bokeh\document\document.py", line 1100, in _trigger_on_change
    self._with_self_as_curdoc(invoke_callbacks)
  File "c:\chenjn\quanttech\.venv\lib\site-packages\bokeh\document\document.py", line 1113, in _with_self_as_curdoc
    return f()
  File "c:\chenjn\quanttech\.venv\lib\site-packages\bokeh\document\document.py", line 1099, in invoke_callbacks
    cb(event)
  File "c:\chenjn\quanttech\.venv\lib\site-packages\bokeh\document\document.py", line 669, in <lambda>
    self._callbacks[receiver] = lambda event: event.dispatch(receiver)
  File "c:\chenjn\quanttech\.venv\lib\site-packages\bokeh\document\events.py", line 244, in dispatch
    super(ModelChangedEvent, self).dispatch(receiver)
  File "c:\chenjn\quanttech\.venv\lib\site-packages\bokeh\document\events.py", line 126, in dispatch
    receiver._document_patched(self)
  File "c:\chenjn\quanttech\.venv\lib\site-packages\bokeh\server\session.py", line 223, in _document_patched
    self._pending_writes.append(connection.send_patch_document(event))
  File "c:\chenjn\quanttech\.venv\lib\site-packages\bokeh\server\connection.py", line 76, in send_patch_document
    msg = self.protocol.create('PATCH-DOC', [event])
  File "c:\chenjn\quanttech\.venv\lib\site-packages\bokeh\protocol\__init__.py", line 80, in create
    return self._messages[msgtype].create(*args, **kwargs)
  File "c:\chenjn\quanttech\.venv\lib\site-packages\bokeh\protocol\messages\patch_doc.py", line 93, in create
    patch_json, buffers = process_document_events(events, use_buffers)
  File "c:\chenjn\quanttech\.venv\lib\site-packages\bokeh\protocol\messages\patch_doc.py", line 136, in process_document_events
    return serialize_json(json), buffers if use_buffers else []
  File "c:\chenjn\quanttech\.venv\lib\site-packages\bokeh\core\json_encoder.py", line 161, in serialize_json
    return json.dumps(obj, cls=BokehJSONEncoder, allow_nan=False, indent=indent, separators=separators, sort_keys=True, **kwargs)
  File "C:\Python37\Lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "C:\Python37\Lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Python37\Lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
ValueError: Out of range float values are not JSON compliant
```

**Comment by TomAugspurger** [comment]
Hmm I'm seeing this on the main `/status` page, but not on the workers page.

I am seeing errors with loading bokeh.js in the browser console

```
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (bokeh.min.js.map, line 0)
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (bokeh-widgets.min.js.map, line 0)
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (bokeh-tables.min.js.map, line 0)
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (bokeh-gl.min.js.map, line 0)
[Error] [bokeh] – "Failed to repull session TypeError: undefined is not an object (evaluating 'l[0]')"
	error
	(anonymous function) (bokeh.min.js:31:4652)
	promiseReactionJob
```

**Comment by TomAugspurger** [comment]
This looks to be the same as https://github.com/dask/distributed/issues/3120. Consolidating there.
