### ISSUE TITLE
Distributing heavy functions via closures

### ISSUE THREAD

**Issue by nsmith-** [dask/dask#5503]
Hi,

So I had started investigating usage of heavy functions, e.g. something with large state such as the example below:
```python
from dask.distributed import Client
client = Client()

import numpy as np
import time

class Heavy():
    def __init__(self):
        self.state = np.arange(1000000)
    
    def __call__(self, arg):
        return np.sum(self.state * arg)

heavy = Heavy()
```

If I send jobs out using the function itself, or a small perturbation of it, it takes quite a while.  I assume there is some bottleneck in function distribution:
```python
from functools import partial

def dosomething(arg, func):
    return func(arg)

tic = time.time()
closure = partial(dosomething, func=heavy)
out = client.map(closure, np.random.normal(size=100))
sum(f.result() for f in out)
print(time.time() - tic)
```
returns 21 seconds on my laptop.  Now, clearly this is a case where broadcasting could help, so I do that:
```python
from itertools import repeat

def dosomething2(args):
    arg, func = args
    return func(arg)

tic = time.time()
heavy_token = client.scatter(heavy, broadcast=True, hash=False)
items = list(zip(np.random.normal(size=100), repeat(heavy_token)))
out = client.map(dosomething2, items)
sum(f.result() for f in out)
print(time.time() - tic)
```
and that gets me down to 0.97 seconds!
But I still want to do my closure trick, so I do this:
```python
def dosomething3(arg, func):
    func = func.result()
    return func(arg)

tic = time.time()
closure = partial(dosomething3, func=heavy_token)
out = client.map(closure, np.random.normal(size=100))
sum(f.result() for f in out)
print(time.time() - tic)
```
and it takes 1.9 seconds, which seems strange that it is slower.  Now this is all fine, but the issue I want to report is that after executing the third code snippet, if I navigate to `http://127.0.0.1:8787/graph`, an exception is produced:
```
distributed.utils - ERROR - '<' not supported between instances of 'NoneType' and 'tuple'
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/distributed/utils.py", line 662, in log_errors
    yield
  File "/usr/local/lib/python3.7/site-packages/distributed/dashboard/components/scheduler.py", line 1692, in graph_doc
    graph = TaskGraph(scheduler, sizing_mode="stretch_both")
  File "/usr/local/lib/python3.7/site-packages/distributed/dashboard/components/scheduler.py", line 1021, in __init__
    self.layout = GraphLayout(scheduler)
  File "/usr/local/lib/python3.7/site-packages/distributed/diagnostics/graph_layout.py", line 39, in __init__
    self.scheduler, dependencies=dependencies, priority=priority
  File "/usr/local/lib/python3.7/site-packages/distributed/diagnostics/graph_layout.py", line 43, in update_graph
    stack = sorted(dependencies, key=lambda k: priority.get(k, 0), reverse=True)
TypeError: '<' not supported between instances of 'NoneType' and 'tuple'
tornado.application - ERROR - Uncaught exception GET /graph (127.0.0.1)
HTTPServerRequest(protocol='http', host='127.0.0.1:8787', method='GET', uri='/graph', version='HTTP/1.1', remote_ip='127.0.0.1')
Traceback (most recent call last):
  File "/usr/local/Cellar/ipython/7.2.0/libexec/vendor/lib/python3.7/site-packages/tornado/web.py", line 1592, in _execute
    result = yield result
  File "/usr/local/Cellar/ipython/7.2.0/libexec/vendor/lib/python3.7/site-packages/tornado/gen.py", line 1133, in run
    value = future.result()
  File "/usr/local/Cellar/ipython/7.2.0/libexec/vendor/lib/python3.7/site-packages/tornado/gen.py", line 1141, in run
    yielded = self.gen.throw(*exc_info)
  File "/usr/local/lib/python3.7/site-packages/bokeh/server/views/doc_handler.py", line 55, in get
    session = yield self.get_session()
  File "/usr/local/Cellar/ipython/7.2.0/libexec/vendor/lib/python3.7/site-packages/tornado/gen.py", line 1133, in run
    value = future.result()
  File "/usr/local/Cellar/ipython/7.2.0/libexec/vendor/lib/python3.7/site-packages/tornado/gen.py", line 1141, in run
    yielded = self.gen.throw(*exc_info)
  File "/usr/local/lib/python3.7/site-packages/bokeh/server/views/session_handler.py", line 77, in get_session
    session = yield self.application_context.create_session_if_needed(session_id, self.request)
  File "/usr/local/Cellar/ipython/7.2.0/libexec/vendor/lib/python3.7/site-packages/tornado/gen.py", line 1133, in run
    value = future.result()
  File "/usr/local/Cellar/ipython/7.2.0/libexec/vendor/lib/python3.7/site-packages/tornado/gen.py", line 1147, in run
    yielded = self.gen.send(value)
  File "/usr/local/lib/python3.7/site-packages/bokeh/server/contexts.py", line 215, in create_session_if_needed
    self._application.initialize_document(doc)
  File "/usr/local/lib/python3.7/site-packages/bokeh/application/application.py", line 178, in initialize_document
    h.modify_document(doc)
  File "/usr/local/lib/python3.7/site-packages/bokeh/application/handlers/function.py", line 133, in modify_document
    self._func(doc)
  File "/usr/local/lib/python3.7/site-packages/distributed/dashboard/components/scheduler.py", line 1692, in graph_doc
    graph = TaskGraph(scheduler, sizing_mode="stretch_both")
  File "/usr/local/lib/python3.7/site-packages/distributed/dashboard/components/scheduler.py", line 1021, in __init__
    self.layout = GraphLayout(scheduler)
  File "/usr/local/lib/python3.7/site-packages/distributed/diagnostics/graph_layout.py", line 39, in __init__
    self.scheduler, dependencies=dependencies, priority=priority
  File "/usr/local/lib/python3.7/site-packages/distributed/diagnostics/graph_layout.py", line 43, in update_graph
    stack = sorted(dependencies, key=lambda k: priority.get(k, 0), reverse=True)
TypeError: '<' not supported between instances of 'NoneType' and 'tuple'
Exception ignored in: <function TaskGraph.__del__ at 0x1125a1950>
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/distributed/dashboard/components/scheduler.py", line 1175, in __del__
    self.scheduler.remove_plugin(self.layout)
AttributeError: 'TaskGraph' object has no attribute 'layout'
```
and subsequent calls continue to produce the same error.

**Comment by TomAugspurger** [comment]
I think the dashboard error was fixed by https://github.com/dask/distributed/pull/3140.

**Comment by nsmith-** [comment]
If I read that PR right, it should be in `2.6.0`, which I'm using.
It seems that also the second example snipped fails to render in the bokeh graph tab.

**Comment by quasiben** [comment]
I am able to reproduce the TaskGraph -- not sure what is going on but priority looks like the following:

> {'Heavy-8197abaffdd44b07a6702680a6f160cf': None, 'dosomething3-1cd1ba5ca67da2b6fd4a621cb96fa556': (0, 2, 99)

And comparing on None/Tuple is a problem.  I don't have time to look at this more fully but I believe it is a bug

**Comment by nsmith-** [comment]
I've found another workaround that also helps with the fact that `client.scatter` doesn't play nicely with adaptive deployments (see e.g. https://github.com/dask/distributed/issues/2454)

```python
from itertools import repeat
from toolz.functoolz import identity

tic = time.time()
out = client.map(
    lambda x: x[0](x[1]),
    list(zip(
        repeat(client.submit(identity, heavy)),
        np.random.normal(size=100)
    )),
)
sum(f.result() for f in out)
print(time.time() - tic)
```
And this runs in less than a second.
The downside is this produces a warning that I'm doing it wrong!
```
/usr/local/lib/python3.8/site-packages/distributed/worker.py:3451: UserWarning: Large object of size 8.00 MB detected in task graph: 
  (<__main__.Heavy object at 0x110f57040>,)
Consider scattering large objects ahead of time
with client.scatter to reduce scheduler burden and 
keep data on workers

    future = client.submit(func, big_data)    # bad

    big_future = client.scatter(big_data)     # good
    future = client.submit(func, big_future)  # good
```
which I think is unfair because the data would have been in the task graph regardless, just as a function instead of a future out in the cluster.
