### ISSUE TITLE
Dask: TypeError: __call__() takes 2 positional arguments but 3 were given

### ISSUE THREAD

**Issue by bipsen** [dask/dask#5505]
Copy of: https://stackoverflow.com/questions/58449018/dask-typeerror-call-takes-2-positional-arguments-but-3-were-given

I am experiencing this error using Dask. I have no idea about how to go about fixing it, as it doesn't seem to be anything in my code explicitly.

What I am doing is reading a dataframe and using `stanfordnlp` to tokenize a text column, and then take out the `nouns`. It works fine when just using `pandas`, but when using `dask` I get this error. I am on `Ubuntu`, `python 3.7.3` and `Dask 2.6.0`.

This is my error:

>Traceback (most recent call last):
File "main.py", line 56, in <module> main(df=data, nlp=nlp, lang=lang, wanted_pos=wp)     
File "main.py", line 13, in main df.persist()
File "/home/bertil/Envs/datascience/lib/python3.7/site-packages/dask/base.py", line 138, in persist (result,) = persist(self, traverse=False, **kwargs)
File "/home/bertil/Envs/datascience/lib/python3.7/site-packages/dask/base.py", line 629, in persist results = schedule(dsk, keys, **kwargs)  
File "/home/bertil/Envs/datascience/lib/python3.7/site-packages/dask/threaded.py", line 80, in get **kwargs  
File "/home/bertil/Envs/datascience/lib/python3.7/site-packages/dask/local.py", line 486, in get_async raise_exception(exc, tb)  
File "/home/bertil/Envs/datascience/lib/python3.7/site-packages/dask/local.py", line 316, in reraise raise exc  
File "/home/bertil/Envs/datascience/lib/python3.7/site-packages/dask/local.py", line 222, in execute_task result = _execute_task(task, data)  
File "/home/bertil/Envs/datascience/lib/python3.7/site-packages/dask/core.py", line 118, in _execute_task args2 = [_execute_task(a, cache) for a in args]  
File "/home/bertil/Envs/datascience/lib/python3.7/site-packages/dask/core.py", line 118, in <listcomp> args2 = [_execute_task(a, cache) for a in args]  
File "/home/bertil/Envs/datascience/lib/python3.7/site-packages/dask/core.py", line 119, in _execute_task return func(*args2)  
TypeError: __call__() takes 2 positional arguments but 3 were given

This is my code:

```
#!/usr/bin/env python

from pathlib import Path
import string
import dask.dataframe as dd
from dask.diagnostics import ProgressBar
import stanfordnlp


def process(text, nlp, lang, wanted_pos):
    # Remove punctuation
    if type(text) == str:
        text = text.translate(str.maketrans('', '', string.punctuation))
        token = nlp(text)
        words = {word for sent in token.sentences for word in sent.words}
        wanted_words = set(filter(lambda word: word.upos in wanted_pos, words))
        wanted_words = ','.join(word.lemma for word in wanted_words if word)
    else:
        wanted_words = ''
    return wanted_words


if __name__ == '__main__':
    # Choose language
    lang = 'da'

    # Chose wanted_pos
    wp = {'NOUN'}

    # Download model for nlp.
    stanford_path = Path.home() / 'stanfordnlp_resources' / f'{lang}_ddt_models'
    if not stanford_path.exists():
        stanfordnlp.download(lang)

    # Set up nlp pipeline
    nlp = stanfordnlp.Pipeline(processors='tokenize,lemma,pos', lang=lang)
    
    df = dd.read_csv('data.csv', engine='python', error_bad_lines=False,
                     encoding='utf8')

    df['tagged'] = df['Message'].apply(process,
                                       args=(nlp, lang, wp),
                                       meta=('Message', str))
    
    with ProgressBar():
        df.compute()

    df.to_csv('out/output_*.csv')

```

**Comment by TomAugspurger** [comment]
Does

```
    df['tagged'] = df['Message'].apply(process, nlp=nlp, lang=lang, watned_pos=wp,
                                       meta=('Message', str))
```

work?

**Comment by bipsen** [comment]
I Tom, thanks for the reply. Just before you wrote I found out I could solve the problem with 

    df['tagged'] = df['Message'].apply(
        lambda x: process(x, nlp, lang, wp)
        if type(x) == str else '',
        meta=('Message', str))

**Comment by quasiben** [comment]
It seems like @TomAugspurger has provided a solution (Thanks @TomAugspurger !) and I believe we can close. If i'm mistaken please re-open

**Comment by TomAugspurger** [comment]
Just to be clear, this would be a bug, but I'm not able to reproduce it with

```python
import dask.dataframe as dd
import pandas as pd


def f(x, y, z):
    return x + y + z


df = pd.DataFrame({"A": [1, 2]})
ddf = dd.from_pandas(df, 2)


ddf.apply(f, args=(1, 2), axis=1, meta=ddf._meta).compute()
```
