### ISSUE TITLE
Deserialization errors when using dask-distributed and Zarr files

### ISSUE THREAD

**Issue by lukepfister** [dask/dask#5509]
I have a remote server running `dask-scheduler` and a `dask-worker`.  I have a Zarr array on my local machine that I wish to process on the remote server.   

The combination of `dask.array.from_zarr` and `dask-distributed` leads to killed workers.  I'm not sure if this is user error or an underlying bug.

The remote & local machines use `dask=2.6, distributed=2.6`, and `zarr=2.3.2`.

MCVE:
```python 
import zarr
from dask.distributed import Client
import dask.array as da

client = Client("REMOTE:8786")  #scheduler only; worker is on remote machine

zroot = zarr.open('testfile.zarr', mode='w')
zroot.array('data', data=np.random.randn(64, 64))

zin = da.from_zarr('./testfile.zarr', 'data')

zin.sum().compute()
```
Result in the REPL:

```python 
---------------------------------------------------------------------------
KilledWorker                              Traceback (most recent call last)
<ipython-input-1-0c2cea91abdc> in <module>
     10 zin = da.from_zarr('./testfile.zarr', 'data')
     11 
---> 12 zin.sum().compute()
     13 

~/software/python/miniconda/envs/fbstenv/lib/python3.7/site-packages/dask/base.py in compute(self, **kwargs)
    163         dask.base.compute
    164         """
--> 165         (result,) = compute(self, traverse=False, **kwargs)
    166         return result
    167 

~/software/python/miniconda/envs/fbstenv/lib/python3.7/site-packages/dask/base.py in compute(*args, **kwargs)
    434     keys = [x.__dask_keys__() for x in collections]
    435     postcomputes = [x.__dask_postcompute__() for x in collections]
--> 436     results = schedule(dsk, keys, **kwargs)
    437     return repack([f(r, *a) for r, (f, a) in zip(results, postcomputes)])
    438 

~/software/python/miniconda/envs/fbstenv/lib/python3.7/site-packages/distributed/client.py in get(self, dsk, keys, restrictions, loose_restrictions, resources, sync, asynchronous, direct, retries, priority, fifo_timeout, actors, **kwargs)
   2543                     should_rejoin = False
   2544             try:
-> 2545                 results = self.gather(packed, asynchronous=asynchronous, direct=direct)
   2546             finally:
   2547                 for f in futures.values():

~/software/python/miniconda/envs/fbstenv/lib/python3.7/site-packages/distributed/client.py in gather(self, futures, errors, direct, asynchronous)
   1843                 direct=direct,
   1844                 local_worker=local_worker,
-> 1845                 asynchronous=asynchronous,
   1846             )
   1847 

~/software/python/miniconda/envs/fbstenv/lib/python3.7/site-packages/distributed/client.py in sync(self, func, asynchronous, callback_timeout, *args, **kwargs)
    760         else:
    761             return sync(
--> 762                 self.loop, func, *args, callback_timeout=callback_timeout, **kwargs
    763             )
    764 

~/software/python/miniconda/envs/fbstenv/lib/python3.7/site-packages/distributed/utils.py in sync(loop, func, callback_timeout, *args, **kwargs)
    331     if error[0]:
    332         typ, exc, tb = error[0]
--> 333         raise exc.with_traceback(tb)
    334     else:
    335         return result[0]

~/software/python/miniconda/envs/fbstenv/lib/python3.7/site-packages/distributed/utils.py in f()
    315             if callback_timeout is not None:
    316                 future = gen.with_timeout(timedelta(seconds=callback_timeout), future)
--> 317             result[0] = yield future
    318         except Exception as exc:
    319             error[0] = sys.exc_info()

~/software/python/miniconda/envs/fbstenv/lib/python3.7/site-packages/tornado/gen.py in run(self)
    733 
    734                     try:
--> 735                         value = future.result()
    736                     except Exception:
    737                         exc_info = sys.exc_info()

~/software/python/miniconda/envs/fbstenv/lib/python3.7/site-packages/distributed/client.py in _gather(self, futures, errors, direct, local_worker)
   1699                             exc = CancelledError(key)
   1700                         else:
-> 1701                             raise exception.with_traceback(traceback)
   1702                         raise exc
   1703                     if errors == "skip":

KilledWorker: ('from-zarr-b87000e1bb3668a800d9c80e19f78dc6', <Worker 'tcp://REMOTE:36561', memory: 0, processing: 1>)
```

Meanwhile, stdout of `dask-worker` contains:
```python
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
distributed.protocol.pickle - INFO - Failed to deserialize b'\x80\x04\x95\x80\x02\x00\x00\x00\x00\x00\x00\x8c\tzarr.core\x94\x8c\x05Array\x94\x93\x94)\x81\x94(\x8c\x0efsspec.mapping\x94\x8c\x05FSMap\x94\x93\x94)\x81\x94\x8c\x1cfsspec.implementations.local\x94\x8c\x0fLocalFileSystem\x94\x93\x94)\x81\x94}\x94(\x8c\t_fs_token\x94\x8c 89ee340dee5eca1f712856e7a03bd695\x94\x8c\x0fstorage_options\x94}\x94\x8c\x07_cached\x94\x88\x8c\x08_intrans\x94\x89\x8c\x0c_transaction\x94\x8c\x12fsspec.transaction\x94\x8c\x0bTransaction\x94\x93\x94)\x81\x94}\x94(\x8c\x02fs\x94h\x0b\x8c\x05files\x94]\x94ub\x8c\x07makedir\x94\x8c\x08builtins\x94\x8c\x07getattr\x94\x93\x94h\x0b\x8c\x05mkdir\x94\x86\x94R\x94\x8c\x06mkdirs\x94h\x1fh\x0b\x8c\x08makedirs\x94\x86\x94R\x94\x8c\x07listdir\x94h\x1fh\x0b\x8c\x02ls\x94\x86\x94R\x94\x8c\x02cp\x94h\x1fh\x0b\x8c\x04copy\x94\x86\x94R\x94\x8c\x04move\x94h\x1fh\x0b\x8c\x02mv\x94\x86\x94R\x94\x8c\x04stat\x94h\x1fh\x0b\x8c\x04info\x94\x86\x94R\x94\x8c\ndisk_usage\x94h\x1fh\x0b\x8c\x02du\x94\x86\x94R\x94\x8c\x06rename\x94h\x1fh\x0bh0\x86\x94R\x94\x8c\x06delete\x94h\x1fh\x0b\x8c\x02rm\x94\x86\x94R\x94\x8c\x06upload\x94h\x1fh\x0b\x8c\x03put\x94\x86\x94R\x94\x8c\x08download\x94h\x1fh\x0b\x8c\x03get\x94\x86\x94R\x94\x8c\nauto_mkdir\x94\x88ub\x8c//home/luke/research/python/fbstenv/testfile.zarr\x94\x86\x94b\x8c\x04data\x94\x88NN\x88\x88t\x94b.'
Traceback (most recent call last):
  File "/home/luke/software/python/miniconda/envs/fbstenv/lib/python3.7/site-packages/fsspec/mapping.py", line 74, in __getitem__
    result = self.fs.cat(key)
  File "/home/luke/software/python/miniconda/envs/fbstenv/lib/python3.7/site-packages/fsspec/spec.py", line 546, in cat
    return self.open(path, 'rb').read()
  File "/home/luke/software/python/miniconda/envs/fbstenv/lib/python3.7/site-packages/fsspec/spec.py", line 691, in open
    autocommit=ac, **kwargs)
  File "/home/luke/software/python/miniconda/envs/fbstenv/lib/python3.7/site-packages/fsspec/implementations/local.py", line 116, in _open
    return LocalFileOpener(path, mode, fs=self, **kwargs)
  File "/home/luke/software/python/miniconda/envs/fbstenv/lib/python3.7/site-packages/fsspec/implementations/local.py", line 172, in __init__
    self._open()
  File "/home/luke/software/python/miniconda/envs/fbstenv/lib/python3.7/site-packages/fsspec/implementations/local.py", line 177, in _open
    self.f = open(self.path, mode=self.mode)
FileNotFoundError: [Errno 2] No such file or directory: '/home/luke/research/python/fbstenv/testfile.zarr/data/.zarray'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/luke/software/python/miniconda/envs/fbstenv/lib/python3.7/site-packages/zarr/core.py", line 150, in _load_metadata_nosync
    meta_bytes = self._store[mkey]
  File "/home/luke/software/python/miniconda/envs/fbstenv/lib/python3.7/site-packages/fsspec/mapping.py", line 78, in __getitem__
    raise KeyError(key)
KeyError: '/home/luke/research/python/fbstenv/testfile.zarr/data/.zarray'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/luke/software/python/miniconda/envs/fbstenv/lib/python3.7/site-packages/distributed/protocol/pickle.py", line 59, in loads
    return pickle.loads(x)
  File "/home/luke/software/python/miniconda/envs/fbstenv/lib/python3.7/site-packages/zarr/core.py", line 1943, in __setstate__
    self.__init__(*state)
  File "/home/luke/software/python/miniconda/envs/fbstenv/lib/python3.7/site-packages/zarr/core.py", line 124, in __init__
    self._load_metadata()
  File "/home/luke/software/python/miniconda/envs/fbstenv/lib/python3.7/site-packages/zarr/core.py", line 141, in _load_metadata
    self._load_metadata_nosync()
  File "/home/luke/software/python/miniconda/envs/fbstenv/lib/python3.7/site-packages/zarr/core.py", line 152, in _load_metadata_nosync
    err_array_not_found(self._path)
  File "/home/luke/software/python/miniconda/envs/fbstenv/lib/python3.7/site-packages/zarr/errors.py", line 25, in err_array_not_found
    raise ValueError('array not found at path %r' % path)
ValueError: array not found at path 'data'
distributed.protocol.core - CRITICAL - Failed to deserialize
Traceback (most recent call last):
  File "/home/luke/software/python/miniconda/envs/fbstenv/lib/python3.7/site-packages/fsspec/mapping.py", line 74, in __getitem__
    result = self.fs.cat(key)
  File "/home/luke/software/python/miniconda/envs/fbstenv/lib/python3.7/site-packages/fsspec/spec.py", line 546, in cat
    return self.open(path, 'rb').read()
  File "/home/luke/software/python/miniconda/envs/fbstenv/lib/python3.7/site-packages/fsspec/spec.py", line 691, in open
    autocommit=ac, **kwargs)
  File "/home/luke/software/python/miniconda/envs/fbstenv/lib/python3.7/site-packages/fsspec/implementations/local.py", line 116, in _open
    return LocalFileOpener(path, mode, fs=self, **kwargs)
  File "/home/luke/software/python/miniconda/envs/fbstenv/lib/python3.7/site-packages/fsspec/implementations/local.py", line 172, in __init__
    self._open()
  File "/home/luke/software/python/miniconda/envs/fbstenv/lib/python3.7/site-packages/fsspec/implementations/local.py", line 177, in _open
    self.f = open(self.path, mode=self.mode)
FileNotFoundError: [Errno 2] No such file or directory: '/home/luke/research/python/fbstenv/testfile.zarr/data/.zarray'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/luke/software/python/miniconda/envs/fbstenv/lib/python3.7/site-packages/zarr/core.py", line 150, in _load_metadata_nosync
    meta_bytes = self._store[mkey]
  File "/home/luke/software/python/miniconda/envs/fbstenv/lib/python3.7/site-packages/fsspec/mapping.py", line 78, in __getitem__
    raise KeyError(key)
KeyError: '/home/luke/research/python/fbstenv/testfile.zarr/data/.zarray'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/luke/software/python/miniconda/envs/fbstenv/lib/python3.7/site-packages/distributed/protocol/core.py", line 124, in loads
    value = _deserialize(head, fs, deserializers=deserializers)
  File "/home/luke/software/python/miniconda/envs/fbstenv/lib/python3.7/site-packages/distributed/protocol/serialize.py", line 268, in deserialize
    return loads(header, frames)
  File "/home/luke/software/python/miniconda/envs/fbstenv/lib/python3.7/site-packages/distributed/protocol/serialize.py", line 62, in pickle_loads
    return pickle.loads(b"".join(frames))
  File "/home/luke/software/python/miniconda/envs/fbstenv/lib/python3.7/site-packages/distributed/protocol/pickle.py", line 59, in loads
    return pickle.loads(x)
  File "/home/luke/software/python/miniconda/envs/fbstenv/lib/python3.7/site-packages/zarr/core.py", line 1943, in __setstate__
    self.__init__(*state)
  File "/home/luke/software/python/miniconda/envs/fbstenv/lib/python3.7/site-packages/zarr/core.py", line 124, in __init__
    self._load_metadata()
  File "/home/luke/software/python/miniconda/envs/fbstenv/lib/python3.7/site-packages/zarr/core.py", line 141, in _load_metadata
    self._load_metadata_nosync()
  File "/home/luke/software/python/miniconda/envs/fbstenv/lib/python3.7/site-packages/zarr/core.py", line 152, in _load_metadata_nosync
    err_array_not_found(self._path)
  File "/home/luke/software/python/miniconda/envs/fbstenv/lib/python3.7/site-packages/zarr/errors.py", line 25, in err_array_not_found
    raise ValueError('array not found at path %r' % path)
ValueError: array not found at path 'data'
distributed.core - ERROR - array not found at path 'data'
Traceback (most recent call last):
  File "/home/luke/software/python/miniconda/envs/fbstenv/lib/python3.7/site-packages/fsspec/mapping.py", line 74, in __getitem__
    result = self.fs.cat(key)
  File "/home/luke/software/python/miniconda/envs/fbstenv/lib/python3.7/site-packages/fsspec/spec.py", line 546, in cat
    return self.open(path, 'rb').read()
  File "/home/luke/software/python/miniconda/envs/fbstenv/lib/python3.7/site-packages/fsspec/spec.py", line 691, in open
    autocommit=ac, **kwargs)
  File "/home/luke/software/python/miniconda/envs/fbstenv/lib/python3.7/site-packages/fsspec/implementations/local.py", line 116, in _open
    return LocalFileOpener(path, mode, fs=self, **kwargs)
  File "/home/luke/software/python/miniconda/envs/fbstenv/lib/python3.7/site-packages/fsspec/implementations/local.py", line 172, in __init__
    self._open()
  File "/home/luke/software/python/miniconda/envs/fbstenv/lib/python3.7/site-packages/fsspec/implementations/local.py", line 177, in _open
    self.f = open(self.path, mode=self.mode)
FileNotFoundError: [Errno 2] No such file or directory: '/home/luke/research/python/fbstenv/testfile.zarr/data/.zarray'
```
The `dask-worker` traceback repeats this pattern many times; hopefully I've included enough here.

It seems that `from_zarr` is the culprit.  If I load the zarr file into a numpy array, then convert the numpy array to a dask array, the computation works:
```python
import zarr
from dask.distributed import Client
import dask.array as da

client = Client("128.174.226.77:8786")  #scheduler only; worker is on remote machine

zroot = zarr.open('testfile.zarr', mode='w')
zroot.array('data', data=np.random.randn(64, 64))

# load the zarr data into memory
zin = zarr.open('testfile.zarr').data[:]

# convert to dask array, compute
zin_dask = da.from_array(zin) 
zin_dask.sum().compute()
```

**Comment by jrbourbeau** [comment]
Thanks for opening up an issue and providing a nice example @lukepfister. Unfortunately I'm not able to reproduce the error with the following snippet:

```python
import numpy as np
import zarr
from dask.distributed import Client
import dask.array as da


if __name__ == "__main__":
    with Client() as client:
        z = zarr.open('testfile.zarr', mode='w')
        z.array('data', data=np.random.randn(64, 64))

        dz = da.from_zarr('./testfile.zarr', 'data')

        result = dz.sum().compute()
        print(f"result = {result}")
```

Do your client and workers share the same filesystem?

**Comment by lukepfister** [comment]
No, they do not share the same filesystem.  I do not have the error using
your snippet-- I believe the fact that the dask-worker is on a remote
machine is key.

**Comment by mrocklin** [comment]
If you want to use a Zarr array backed by a filesystem with many machines
then that file will need to be present on all of the machines at the same
location.

**Comment by lukepfister** [comment]
Understood.  Is this by design, or a limitation of the current implementation?

**Comment by TomAugspurger** [comment]
Strings without a protocol like `s3://` refer to absolute paths.
