### ISSUE TITLE
Key error in blockwise when align_arrays=False

### ISSUE THREAD

**Issue by landmanbester** [dask/dask#5550]
I am using dask-2.6.0. The following code

import dask.array as da
from dask.array import blockwise
import numpy as np

out_shape = ("row", "chan", "corr1", "corr2")
model_shape = ("row", "chan", "dir", "corr1", "corr2")
jones_shape = ("row", "ant", "chan", "dir", "corr1")

ants = da.zeros(10)
jones = da.zeros((10, 7, 16, 2, 2))
model = da.zeros((10, 16, 1, 2, 2))

blockwise(lambda x: x, out_shape,
          ants, ("row",),
          jones, jones_shape,
          model, model_shape,
          align_arrays=False,
          dtype=np.int32)

Results in:

Traceback (most recent call last):                                                                                        File "rep.py", line 18, in <module>                                                                                       dtype=np.int32)                                                                                                       File "/home/landman/venvs/africanus/lib/python3.6/site-packages/dask/array/blockwise.py", line 214, in blockwise          chunks = [chunkss[i] for i in out_ind]                                                                                File "/home/landman/venvs/africanus/lib/python3.6/site-packages/dask/array/blockwise.py", line 214, in <listcomp>         chunks = [chunkss[i] for i in out_ind]                                                                              KeyError: 'corr2'

As far as I can tell this is a bug in blockwise here https://github.com/dask/dask/blob/0871699c0e4b021fca4a3104042d1adf7c5fd5d5/dask/array/blockwise.py#L149 Since jones and model have the same number of dimensions and jones is passed in first the output dimensions are incorrectly inferred. Changing the order of jones and model fixes the problem but this still seems like a bug to me

**Comment by mrocklin** [comment]
I'm sorry for the long delay in responding here.  

Would you be ok trying to find a reduced version of this problem?  Do you need all of the dimensions that you have here?  Is it important that they are called ant/jones/model/chan?  I'm not sure if these are critical.  In general, anything you can do to reduce the problem further would be welcome.  It's somewhat difficult to quickly understand what's going on in 5d problems in the 60s or so that we have when first triaging issues.

**Comment by landmanbester** [comment]
Sorry, looking back, that example is a bit contrived. This is about as simple as I could make it.

import dask.array as da
import numpy as np

out_shape = 'a'
in1_shape = 'bc'
in2_shape = 'ab'

in1 = da.zeros((2,3))
in2 = da.zeros((1,2))

da.blockwise(lambda x:x, out_shape,
                      in1, in1_shape,
                      in2, in2_shape,
                      align_arrays=False,
                      dtype=np.int32)

which fails with
                                                                                             
File "/home/landman/venvs/codex_nifty/lib/python3.6/site-packages/dask/array/blockwise.py", line 214, in blockwise        chunks = [chunkss[i] for i in out_ind]                                                                                File "/home/landman/venvs/codex_nifty/lib/python3.6/site-packages/dask/array/blockwise.py", line 214, in <listcomp>       chunks = [chunkss[i] for i in out_ind]                                                                              KeyError: 'a'

As far as I can tell, the keys in chunkss are determined by the input with the most axes. In this case, since both inputs have the same number of axes, I suppose the first one is used and the key 'a' never makes it into chunkss. I hope that is clearer. Sorry for the overly contrived initial example.

**Comment by TomAugspurger** [comment]
I modified the `lambda` in the example to take two inputs.

I'm not really sure what this line is doing

```python
            arg, ind = max(arginds, key=lambda ai: len(ai[1]))
```

with these values, we get

```python
(Pdb) pp arginds
[(dask.array<zeros, shape=(2, 3), dtype=float64, chunksize=(2, 3), chunktype=numpy.ndarray>,
  'bc'),
 (dask.array<zeros, shape=(1, 2), dtype=float64, chunksize=(1, 2), chunktype=numpy.ndarray>,
  'ab')]
(Pdb) arg, ind
(dask.array<zeros, shape=(2, 3), dtype=float64, chunksize=(2, 3), chunktype=numpy.ndarray>, 'bc')
```

And `a` isn't anywhere in `chunkss`. I'm not sure whether this is a bug in the implementation, or if the user needs to verify something about their inputs / ouput indices when using `align_blocks=False`.

**Comment by jsignell** [comment]
I can no longer reproduce on most recent dask - 2021.03.0 which means that it was probably fixed in the blockwise work the @rjzamora did!
