### ISSUE TITLE
dask-2.7.0 with PyQt5:  may have been in progress in another thread when fork() was called.

### ISSUE THREAD

**Issue by tinyms** [dask/dask#5572]
dask-2.7.0  distributed-2.7.0 with PyQt5

```
cluster_server = LocalCluster()
cluster_client = Client(cluster_server, asynchronous=True)
cluster_client.submit(...)
```
throw exception
```
objc[38342]: +[__NSCFConstantString initialize] may have been in progress in another thread when fork() was called.
objc[38342]: +[__NSCFConstantString initialize] may have been in progress in another thread when fork() was called. We cannot safely call it or ignore it in the fork() child process. Crashing instead. Set a breakpoint on objc_initializeAfterForkError to debug.
/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/semaphore_tracker.py:144: UserWarning: semaphore_tracker: There appear to be 1 leaked semaphores to clean up at shutdown
  len(cache))
distributed.nanny - WARNING - Restarting worker
objc[38341]: +[__NSCFConstantString initialize] may have been in progress in another thread when fork() was called.
objc[38341]: +[__NSCFConstantString initialize] may have been in progress in another thread when fork() was called. We cannot safely call it or ignore it in the fork() child process. Crashing instead. Set a breakpoint on objc_initializeAfterForkError to debug.
/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/semaphore_tracker.py:144: UserWarning: semaphore_tracker: There appear to be 1 leaked semaphores to clean up at shutdown
  len(cache))
distributed.nanny - WARNING - Restarting worker
objc[38343]: +[__NSCFConstantString initialize] may have been in progress in another thread when fork() was called.
objc[38343]: +[__NSCFConstantString initialize] may have been in progress in another thread when fork() was called. We cannot safely call it or ignore it in the fork() child process. Crashing instead. Set a breakpoint on objc_initializeAfterForkError to debug.
/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/semaphore_tracker.py:144: UserWarning: semaphore_tracker: There appear to be 1 leaked semaphores to clean up at shutdown
  len(cache))
distributed.nanny - WARNING - Restarting worker
objc[38344]: +[__NSCFConstantString initialize] may have been in progress in another thread when fork() was called.
objc[38344]: +[__NSCFConstantString initialize] may have been in progress in another thread when fork() was called. We cannot safely call it or ignore it in the fork() child process. Crashing instead. Set a breakpoint on objc_initializeAfterForkError to debug.
/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/semaphore_tracker.py:144: UserWarning: semaphore_tracker: There appear to be 1 leaked semaphores to clean up at shutdown
  len(cache))
distributed.diskutils - ERROR - Failed to remove '/Users/bopresslte/Documents/dev.projects/AutoLearnWorkbench/dask-worker-space/worker-rc229eaw/storage' (failed in <built-in function rmdir>): [Errno 2] No such file or directory: 'storage'
distributed.diskutils - ERROR - Failed to remove '/Users/bopresslte/Documents/dev.projects/AutoLearnWorkbench/dask-worker-space/worker-rc229eaw' (failed in <built-in function rmdir>): [Errno 2] No such file or directory: '/Users/bopresslte/Documents/dev.projects/AutoLearnWorkbench/dask-worker-space/worker-rc229eaw'
distributed.nanny - WARNING - Restarting worker
objc[38461]: +[__NSCFConstantString initialize] may have been in progress in another thread when fork() was called.
objc[38461]: +[__NSCFConstantString initialize] may have been in progress in another thread when fork() was called. We cannot safely call it or ignore it in the fork() child process. Crashing instead. Set a breakpoint on objc_initializeAfterForkError to debug.
distributed.nanny - WARNING - Restarting worker
objc[38970]: +[__NSCFConstantString initialize] may have been in progress in another thread when fork() was called.
objc[38970]: +[__NSCFConstantString initialize] may have been in progress in another thread when fork() was called. We cannot safely call it or ignore it in the fork() child process. Crashing instead. Set a breakpoint on objc_initializeAfterForkError to debug.
distributed.nanny - WARNING - Restarting worker
ERROR:autolearn.data.datafile:('cluster_read-613f3b5150fa5d25141491685a76bdf2', <Worker 'tcp://127.0.0.1:61963', memory: 0, processing: 1>)
Traceback (most recent call last):
  File "/Users/bopresslte/Documents/dev.projects/AutoLearnWorkbench/autolearn/data/datafile.py", line 306, in _try_load
    dataset = self.read_datafile(self.reader)
  File "/Users/bopresslte/Documents/dev.projects/AutoLearnWorkbench/autolearn/data/csvfile.py", line 206, in read_datafile
    return framework.distributed_submit(ALCsvFileWidget.cluster_read, path, **params)
  File "/Users/bopresslte/Documents/dev.projects/AutoLearnWorkbench/autolearn/framework.py", line 662, in distributed_submit
    return r.result()
  File "/Users/bopresslte/Documents/dev.projects/AutoLearnWorkbench/venv/lib/python3.7/site-packages/distributed/client.py", line 222, in result
    raise exc.with_traceback(tb)
distributed.scheduler.KilledWorker: ('cluster_read-613f3b5150fa5d25141491685a76bdf2', <Worker 'tcp://127.0.0.1:61963', memory: 0, processing: 1>)
ERROR:autolearn.data.datafile:('cluster_read-613f3b5150fa5d25141491685a76bdf2', <Worker 'tcp://127.0.0.1:61963', memory: 0, processing: 1>)
Traceback (most recent call last):
  File "/Users/bopresslte/Documents/dev.projects/AutoLearnWorkbench/autolearn/data/datafile.py", line 306, in _try_load
    dataset = self.read_datafile(self.reader)
  File "/Users/bopresslte/Documents/dev.projects/AutoLearnWorkbench/autolearn/data/csvfile.py", line 206, in read_datafile
    return framework.distributed_submit(ALCsvFileWidget.cluster_read, path, **params)
  File "/Users/bopresslte/Documents/dev.projects/AutoLearnWorkbench/autolearn/framework.py", line 662, in distributed_submit
    return r.result()
  File "/Users/bopresslte/Documents/dev.projects/AutoLearnWorkbench/venv/lib/python3.7/site-packages/distributed/client.py", line 222, in result
    raise exc.with_traceback(tb)
distributed.scheduler.KilledWorker: ('cluster_read-613f3b5150fa5d25141491685a76bdf2', <Worker 'tcp://127.0.0.1:61963', memory: 0, processing: 1>)
distributed.nanny - WARNING - Restarting worker
```

**but dask-2.6.0  distributed-2.6.0 with PyQt5 is ok**

**Comment by mrocklin** [comment]
Interesting.  Can you provide more information about how to reproduce the issue?  My guess is that the problem is related to whatever functions you are submitting.  

https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports

**Comment by bnaul** [comment]
@mrocklin I'm seeing something similar when I try to start a `dask-worker` from the command-line on 2.7.0
```
# tab 1
(model) ➜  model ✗ dask-scheduler
distributed.scheduler - INFO - -----------------------------------------------
distributed.scheduler - INFO - Local Directory: /var/folders/7y/nvrvjtkn763f67v65n1chzvr0000gn/T/scheduler-f4o0il_v
distributed.scheduler - INFO - -----------------------------------------------
distributed.scheduler - INFO - Clear task state
distributed.scheduler - INFO -   Scheduler at:    tcp://192.168.0.3:8786
distributed.scheduler - INFO -   dashboard at:                     :8787

# tab 2
(model) ➜  model ✗ dask-worker localhost:8786 --nthreads 1 --memory-limit 6GB  --nprocs 1
distributed.nanny - INFO -         Start Nanny at: 'tcp://127.0.0.1:57122'
objc[90218]: +[__NSPlaceholderDictionary initialize] may have been in progress in another thread when fork() was called.
objc[90218]: +[__NSPlaceholderDictionary initialize] may have been in progress in another thread when fork() was called. We cannot safely call it or ignore it in the fork() child process. Crashing instead. Set a breakpoint on objc_initializeAfterForkError to debug.
distributed.nanny - INFO - Worker process 90218 was killed by signal 6
distributed.nanny - INFO - Closing Nanny at 'tcp://127.0.0.1:57122'
distributed.dask_worker - INFO - End worker
```

**Comment by mrocklin** [comment]
Thanks for reporting in @bnaul .

A quick google search brings up terms around OSX and forking.

Can I ask you to try with the following config?

```yaml
distributed:
  worker:
    multiprocessing-method: spawn
```

**Comment by bnaul** [comment]
> Thanks for reporting in @bnaul .
> 
> A quick google search brings up terms around OSX and forking.
> 
> Can I ask you to try with the following config?
> 
> ```yaml
> distributed:
>   worker:
>     multiprocessing-method: spawn
> ```

Yep, `spawn` works just fine.

**Comment by mrocklin** [comment]
Thanks!  That's helpful.  

The next helpful thing, if you or anyone else has time, would be to try `git bisect` to identify which commit caused the issue.  I would estimate that this would take around 20m of time.

**Comment by bnaul** [comment]
Was just about to post, `bisect`ing gives https://github.com/dask/distributed/commit/763a649e3e272b657d394409e74584505510f064 as the first problematic commit.

**Comment by mrocklin** [comment]
That's bizarre.  Do you even have ucxpy installed?  What is the result of `import ucp`?

**Comment by bnaul** [comment]
> That's bizarre. Do you even have ucxpy installed? What is the result of `import ucp`?

nope!
```
ModuleNotFoundError: No module named 'ucp'
```

**Comment by bnaul** [comment]
actually @mrocklin I think I messed up the bisect, lemme try again

**Comment by bnaul** [comment]
@mrocklin not a bad bisect but a bad copy-paste from a similar commit name 😅 https://github.com/dask/distributed/commit/bc04d7642c0439bf3757b34bd1eb802b9679ba12

"avoid double init after fork" sounds a lot more relevant

**Comment by mrocklin** [comment]
> sounds a lot more relevant

Indeed, but even that commit only touches code in `distributed/comm/ucx.py` which you shouldn't ever be touching if you don't have ucx installed.  

https://github.com/dask/distributed/blob/81df14f144d5358ed9d37a065c5f5220280a6f78/distributed/comm/ucx.py#L1-L22

https://github.com/dask/distributed/blob/81df14f144d5358ed9d37a065c5f5220280a6f78/distributed/comm/__init__.py#L19-L22

So if `import ucp` raises an `ImportError` for you then I'm confused as to why any changes in that module would affect you.

cc @madsbk for visibility

**Comment by bnaul** [comment]
I poked around a bit more and the code you highlighted technically does run; it only fails at `import ucp`, but the lines before it are all executed.

The only obvious change is that some of the imports moved from after `ucp` to before; after some trial and error I'm pretty confident that commenting out the *first* (note that there are two) `import numpy as np` at https://github.com/dask/distributed/blob/81df14f144d5358ed9d37a065c5f5220280a6f78/distributed/comm/ucx.py#L12 lets me start a worker normally.

Any idea what's going on? 😕

**Comment by madsbk** [comment]
@bnaul, could you try remove the three lines: https://github.com/dask/distributed/blob/81df14f144d5358ed9d37a065c5f5220280a6f78/distributed/comm/ucx.py#L20-L22 and see if it helps?
I don't think those lines should be there in the first place.

**Comment by bnaul** [comment]
@madsbk nope, even with those lines removed I see the same error; removing the lines same lines before the import does fix the issue though.

**Comment by mrocklin** [comment]
So presumably https://github.com/dask/distributed/pull/3228 should fix this then.  It would be nice to understand why this was happening though.  @bnaul I'll leave it to you if you want to continue investigating here.  Perhaps we do something in one of the utils.py file at import time?
