### ISSUE TITLE
TypeError: can't pickle SSLContext objects

### ISSUE THREAD

**Issue by BabuTango** [dask/dask#5650]
@mrocklin **I get this error when using dask.distributed and dask.delayed, but just using dask.delayed and using the graph doesn't give me this error and it works perfectly fine.**

distributed.protocol.pickle - INFO - Failed to serialize ('getitem-b6f1df3d89ac638b767ecb1bb3cd4935', 'getitem-17668d79daf8808dc4bb1d7fc1faed20', '/home/babu/Downloads/6_1/6-1_22-11-2019_10_16_01_reid.zip', 'getitem-1fafe326d7c3ef96dbd05918092266e3', <botocore.client.S3 object at 0x7f16fc1ee390>, 'tracker_upload-8bab7e1c-46b3-4ef3-b36a-f708cdf18246', 'mapping_upload-f4252c87-3086-436f-a26b-86b64f159af3'). Exception: can't pickle SSLContext objects
Traceback (most recent call last):
  File "/home/babu/anaconda3/lib/python3.7/site-packages/distributed/protocol/pickle.py", line 38, in dumps
    result = pickle.dumps(x, protocol=pickle.HIGHEST_PROTOCOL)
_pickle.PicklingError: Can't pickle <class 'botocore.client.S3'>: attribute lookup S3 on botocore.client failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "Untitled.py", line 909, in <module>
    process()
  File "Untitled.py", line 900, in process
    dask_compute.compute()
  File "/home/babu/anaconda3/lib/python3.7/site-packages/dask/base.py", line 165, in compute
    (result,) = compute(self, traverse=False, **kwargs)
  File "/home/babu/anaconda3/lib/python3.7/site-packages/dask/base.py", line 436, in compute
    results = schedule(dsk, keys, **kwargs)
  File "/home/babu/anaconda3/lib/python3.7/site-packages/distributed/client.py", line 2561, in get
    actors=actors,
  File "/home/babu/anaconda3/lib/python3.7/site-packages/distributed/client.py", line 2488, in _graph_to_futures
    "tasks": valmap(dumps_task, dsk3),
  File "cytoolz/dicttoolz.pyx", line 179, in cytoolz.dicttoolz.valmap
  File "cytoolz/dicttoolz.pyx", line 204, in cytoolz.dicttoolz.valmap
  File "/home/babu/anaconda3/lib/python3.7/site-packages/distributed/worker.py", line 3245, in dumps_task
    return {"function": dumps_function(task[0]), "args": warn_dumps(task[1:])}
  File "/home/babu/anaconda3/lib/python3.7/site-packages/distributed/worker.py", line 3254, in warn_dumps
    b = dumps(obj)
  File "/home/babu/anaconda3/lib/python3.7/site-packages/distributed/protocol/pickle.py", line 51, in dumps
    return cloudpickle.dumps(x, protocol=pickle.HIGHEST_PROTOCOL)
  File "/home/babu/anaconda3/lib/python3.7/site-packages/cloudpickle/cloudpickle.py", line 1125, in dumps
    cp.dump(obj)
  File "/home/babu/anaconda3/lib/python3.7/site-packages/cloudpickle/cloudpickle.py", line 482, in dump
    return Pickler.dump(self, obj)
  File "/home/babu/anaconda3/lib/python3.7/pickle.py", line 437, in dump
    self.save(obj)
  File "/home/babu/anaconda3/lib/python3.7/pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
  File "/home/babu/anaconda3/lib/python3.7/pickle.py", line 786, in save_tuple
    save(element)
  File "/home/babu/anaconda3/lib/python3.7/pickle.py", line 549, in save
    self.save_reduce(obj=obj, *rv)
  File "/home/babu/anaconda3/lib/python3.7/pickle.py", line 662, in save_reduce
    save(state)
  File "/home/babu/anaconda3/lib/python3.7/pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
  File "/home/babu/anaconda3/lib/python3.7/pickle.py", line 856, in save_dict
    self._batch_setitems(obj.items())
  File "/home/babu/anaconda3/lib/python3.7/pickle.py", line 882, in _batch_setitems
    save(v)
  File "/home/babu/anaconda3/lib/python3.7/pickle.py", line 549, in save
    self.save_reduce(obj=obj, *rv)
  File "/home/babu/anaconda3/lib/python3.7/pickle.py", line 662, in save_reduce
    save(state)
  File "/home/babu/anaconda3/lib/python3.7/pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
  File "/home/babu/anaconda3/lib/python3.7/pickle.py", line 856, in save_dict
    self._batch_setitems(obj.items())
  File "/home/babu/anaconda3/lib/python3.7/pickle.py", line 882, in _batch_setitems
    save(v)
  File "/home/babu/anaconda3/lib/python3.7/pickle.py", line 549, in save
    self.save_reduce(obj=obj, *rv)
  File "/home/babu/anaconda3/lib/python3.7/pickle.py", line 662, in save_reduce
    save(state)
  File "/home/babu/anaconda3/lib/python3.7/pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
  File "/home/babu/anaconda3/lib/python3.7/pickle.py", line 856, in save_dict
    self._batch_setitems(obj.items())
  File "/home/babu/anaconda3/lib/python3.7/pickle.py", line 882, in _batch_setitems
    save(v)
  File "/home/babu/anaconda3/lib/python3.7/pickle.py", line 549, in save
    self.save_reduce(obj=obj, *rv)
  File "/home/babu/anaconda3/lib/python3.7/pickle.py", line 662, in save_reduce
    save(state)
  File "/home/babu/anaconda3/lib/python3.7/pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
  File "/home/babu/anaconda3/lib/python3.7/pickle.py", line 856, in save_dict
    self._batch_setitems(obj.items())
  File "/home/babu/anaconda3/lib/python3.7/pickle.py", line 882, in _batch_setitems
    save(v)
  File "/home/babu/anaconda3/lib/python3.7/pickle.py", line 549, in save
    self.save_reduce(obj=obj, *rv)
  File "/home/babu/anaconda3/lib/python3.7/pickle.py", line 662, in save_reduce
    save(state)
  File "/home/babu/anaconda3/lib/python3.7/pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
  File "/home/babu/anaconda3/lib/python3.7/pickle.py", line 856, in save_dict
    self._batch_setitems(obj.items())
  File "/home/babu/anaconda3/lib/python3.7/pickle.py", line 887, in _batch_setitems
    save(v)
  File "/home/babu/anaconda3/lib/python3.7/pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
  File "/home/babu/anaconda3/lib/python3.7/pickle.py", line 856, in save_dict
    self._batch_setitems(obj.items())
  File "/home/babu/anaconda3/lib/python3.7/pickle.py", line 882, in _batch_setitems
    save(v)
  File "/home/babu/anaconda3/lib/python3.7/pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
  File "/home/babu/anaconda3/lib/python3.7/pickle.py", line 856, in save_dict
    self._batch_setitems(obj.items())
  File "/home/babu/anaconda3/lib/python3.7/pickle.py", line 882, in _batch_setitems
    save(v)
  File "/home/babu/anaconda3/lib/python3.7/pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
  File "/home/babu/anaconda3/lib/python3.7/pickle.py", line 856, in save_dict
    self._batch_setitems(obj.items())
  File "/home/babu/anaconda3/lib/python3.7/pickle.py", line 882, in _batch_setitems
    save(v)
  File "/home/babu/anaconda3/lib/python3.7/pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
  File "/home/babu/anaconda3/lib/python3.7/pickle.py", line 856, in save_dict
    self._batch_setitems(obj.items())
  File "/home/babu/anaconda3/lib/python3.7/pickle.py", line 882, in _batch_setitems
    save(v)
  File "/home/babu/anaconda3/lib/python3.7/pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
  File "/home/babu/anaconda3/lib/python3.7/pickle.py", line 856, in save_dict
    self._batch_setitems(obj.items())
  File "/home/babu/anaconda3/lib/python3.7/pickle.py", line 882, in _batch_setitems
    save(v)
  File "/home/babu/anaconda3/lib/python3.7/pickle.py", line 549, in save
    self.save_reduce(obj=obj, *rv)
  File "/home/babu/anaconda3/lib/python3.7/pickle.py", line 634, in save_reduce
    save(args)
  File "/home/babu/anaconda3/lib/python3.7/pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
  File "/home/babu/anaconda3/lib/python3.7/pickle.py", line 771, in save_tuple
    save(element)
  File "/home/babu/anaconda3/lib/python3.7/pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
  File "/home/babu/anaconda3/lib/python3.7/pickle.py", line 816, in save_list
    self._batch_appends(obj)
  File "/home/babu/anaconda3/lib/python3.7/pickle.py", line 843, in _batch_appends
    save(tmp[0])
  File "/home/babu/anaconda3/lib/python3.7/pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
  File "/home/babu/anaconda3/lib/python3.7/site-packages/cloudpickle/cloudpickle.py", line 890, in save_instancemethod
    self.save_reduce(types.MethodType, (obj.__func__, obj.__self__), obj=obj)
  File "/home/babu/anaconda3/lib/python3.7/pickle.py", line 638, in save_reduce
    save(args)
  File "/home/babu/anaconda3/lib/python3.7/pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
  File "/home/babu/anaconda3/lib/python3.7/pickle.py", line 771, in save_tuple
    save(element)
  File "/home/babu/anaconda3/lib/python3.7/pickle.py", line 549, in save
    self.save_reduce(obj=obj, *rv)
  File "/home/babu/anaconda3/lib/python3.7/pickle.py", line 662, in save_reduce
    save(state)
  File "/home/babu/anaconda3/lib/python3.7/pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
  File "/home/babu/anaconda3/lib/python3.7/pickle.py", line 856, in save_dict
    self._batch_setitems(obj.items())
  File "/home/babu/anaconda3/lib/python3.7/pickle.py", line 882, in _batch_setitems
    save(v)
  File "/home/babu/anaconda3/lib/python3.7/pickle.py", line 549, in save
    self.save_reduce(obj=obj, *rv)
  File "/home/babu/anaconda3/lib/python3.7/pickle.py", line 662, in save_reduce
    save(state)
  File "/home/babu/anaconda3/lib/python3.7/pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
  File "/home/babu/anaconda3/lib/python3.7/pickle.py", line 856, in save_dict
    self._batch_setitems(obj.items())
  File "/home/babu/anaconda3/lib/python3.7/pickle.py", line 882, in _batch_setitems
    save(v)
  File "/home/babu/anaconda3/lib/python3.7/pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
  File "/home/babu/anaconda3/lib/python3.7/pickle.py", line 856, in save_dict
    self._batch_setitems(obj.items())
  File "/home/babu/anaconda3/lib/python3.7/pickle.py", line 882, in _batch_setitems
    save(v)
  File "/home/babu/anaconda3/lib/python3.7/pickle.py", line 549, in save
    self.save_reduce(obj=obj, *rv)
  File "/home/babu/anaconda3/lib/python3.7/pickle.py", line 662, in save_reduce
    save(state)
  File "/home/babu/anaconda3/lib/python3.7/pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
  File "/home/babu/anaconda3/lib/python3.7/pickle.py", line 856, in save_dict
    self._batch_setitems(obj.items())
  File "/home/babu/anaconda3/lib/python3.7/pickle.py", line 882, in _batch_setitems
    save(v)
  File "/home/babu/anaconda3/lib/python3.7/pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
  File "/home/babu/anaconda3/lib/python3.7/pickle.py", line 816, in save_list
    self._batch_appends(obj)
  File "/home/babu/anaconda3/lib/python3.7/pickle.py", line 840, in _batch_appends
    save(x)
  File "/home/babu/anaconda3/lib/python3.7/pickle.py", line 549, in save
    self.save_reduce(obj=obj, *rv)
  File "/home/babu/anaconda3/lib/python3.7/pickle.py", line 662, in save_reduce
    save(state)
  File "/home/babu/anaconda3/lib/python3.7/pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
  File "/home/babu/anaconda3/lib/python3.7/pickle.py", line 856, in save_dict
    self._batch_setitems(obj.items())
  File "/home/babu/anaconda3/lib/python3.7/pickle.py", line 882, in _batch_setitems
    save(v)
  File "/home/babu/anaconda3/lib/python3.7/pickle.py", line 549, in save
    self.save_reduce(obj=obj, *rv)
  File "/home/babu/anaconda3/lib/python3.7/pickle.py", line 662, in save_reduce
    save(state)
  File "/home/babu/anaconda3/lib/python3.7/pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
  File "/home/babu/anaconda3/lib/python3.7/pickle.py", line 856, in save_dict
    self._batch_setitems(obj.items())
  File "/home/babu/anaconda3/lib/python3.7/pickle.py", line 882, in _batch_setitems
    save(v)
  File "/home/babu/anaconda3/lib/python3.7/pickle.py", line 549, in save
    self.save_reduce(obj=obj, *rv)
  File "/home/babu/anaconda3/lib/python3.7/pickle.py", line 662, in save_reduce
    save(state)
  File "/home/babu/anaconda3/lib/python3.7/pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
  File "/home/babu/anaconda3/lib/python3.7/pickle.py", line 856, in save_dict
    self._batch_setitems(obj.items())
  File "/home/babu/anaconda3/lib/python3.7/pickle.py", line 882, in _batch_setitems
    save(v)
  File "/home/babu/anaconda3/lib/python3.7/pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
  File "/home/babu/anaconda3/lib/python3.7/pickle.py", line 856, in save_dict
    self._batch_setitems(obj.items())
  File "/home/babu/anaconda3/lib/python3.7/pickle.py", line 882, in _batch_setitems
    save(v)
  File "/home/babu/anaconda3/lib/python3.7/pickle.py", line 549, in save
    self.save_reduce(obj=obj, *rv)
  File "/home/babu/anaconda3/lib/python3.7/pickle.py", line 662, in save_reduce
    save(state)
  File "/home/babu/anaconda3/lib/python3.7/pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
  File "/home/babu/anaconda3/lib/python3.7/pickle.py", line 856, in save_dict
    self._batch_setitems(obj.items())
  File "/home/babu/anaconda3/lib/python3.7/pickle.py", line 887, in _batch_setitems
    save(v)
  File "/home/babu/anaconda3/lib/python3.7/pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
  File "/home/babu/anaconda3/lib/python3.7/pickle.py", line 816, in save_list
    self._batch_appends(obj)
  File "/home/babu/anaconda3/lib/python3.7/pickle.py", line 840, in _batch_appends
    save(x)
  File "/home/babu/anaconda3/lib/python3.7/pickle.py", line 549, in save
    self.save_reduce(obj=obj, *rv)
  File "/home/babu/anaconda3/lib/python3.7/pickle.py", line 662, in save_reduce
    save(state)
  File "/home/babu/anaconda3/lib/python3.7/pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
  File "/home/babu/anaconda3/lib/python3.7/pickle.py", line 856, in save_dict
    self._batch_setitems(obj.items())
  File "/home/babu/anaconda3/lib/python3.7/pickle.py", line 882, in _batch_setitems
    save(v)
  File "/home/babu/anaconda3/lib/python3.7/pickle.py", line 549, in save
    self.save_reduce(obj=obj, *rv)
  File "/home/babu/anaconda3/lib/python3.7/pickle.py", line 662, in save_reduce
    save(state)
  File "/home/babu/anaconda3/lib/python3.7/pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
  File "/home/babu/anaconda3/lib/python3.7/pickle.py", line 856, in save_dict
    self._batch_setitems(obj.items())
  File "/home/babu/anaconda3/lib/python3.7/pickle.py", line 887, in _batch_setitems
    save(v)
  File "/home/babu/anaconda3/lib/python3.7/pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
  File "/home/babu/anaconda3/lib/python3.7/pickle.py", line 816, in save_list
    self._batch_appends(obj)
  File "/home/babu/anaconda3/lib/python3.7/pickle.py", line 840, in _batch_appends
    save(x)
  File "/home/babu/anaconda3/lib/python3.7/pickle.py", line 549, in save
    self.save_reduce(obj=obj, *rv)
  File "/home/babu/anaconda3/lib/python3.7/pickle.py", line 662, in save_reduce
    save(state)
  File "/home/babu/anaconda3/lib/python3.7/pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
  File "/home/babu/anaconda3/lib/python3.7/pickle.py", line 856, in save_dict
    self._batch_setitems(obj.items())
  File "/home/babu/anaconda3/lib/python3.7/pickle.py", line 882, in _batch_setitems
    save(v)
  File "/home/babu/anaconda3/lib/python3.7/pickle.py", line 549, in save
    self.save_reduce(obj=obj, *rv)
  File "/home/babu/anaconda3/lib/python3.7/pickle.py", line 662, in save_reduce
    save(state)
  File "/home/babu/anaconda3/lib/python3.7/pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
  File "/home/babu/anaconda3/lib/python3.7/pickle.py", line 856, in save_dict
    self._batch_setitems(obj.items())
  File "/home/babu/anaconda3/lib/python3.7/pickle.py", line 882, in _batch_setitems
    save(v)
  File "/home/babu/anaconda3/lib/python3.7/pickle.py", line 549, in save
    self.save_reduce(obj=obj, *rv)
  File "/home/babu/anaconda3/lib/python3.7/pickle.py", line 662, in save_reduce
    save(state)
  File "/home/babu/anaconda3/lib/python3.7/pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
  File "/home/babu/anaconda3/lib/python3.7/pickle.py", line 856, in save_dict
    self._batch_setitems(obj.items())
  File "/home/babu/anaconda3/lib/python3.7/pickle.py", line 882, in _batch_setitems
    save(v)
  File "/home/babu/anaconda3/lib/python3.7/pickle.py", line 549, in save
    self.save_reduce(obj=obj, *rv)
  File "/home/babu/anaconda3/lib/python3.7/pickle.py", line 662, in save_reduce
    save(state)
  File "/home/babu/anaconda3/lib/python3.7/pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
  File "/home/babu/anaconda3/lib/python3.7/pickle.py", line 856, in save_dict
    self._batch_setitems(obj.items())
  File "/home/babu/anaconda3/lib/python3.7/pickle.py", line 882, in _batch_setitems
    save(v)
  File "/home/babu/anaconda3/lib/python3.7/pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
  File "/home/babu/anaconda3/lib/python3.7/pickle.py", line 856, in save_dict
    self._batch_setitems(obj.items())
  File "/home/babu/anaconda3/lib/python3.7/pickle.py", line 882, in _batch_setitems
    save(v)
  File "/home/babu/anaconda3/lib/python3.7/pickle.py", line 524, in save
    rv = reduce(self.proto)
TypeError: can't pickle SSLContext objects

**Comment by jacobtomlinson** [comment]
Could you please provide an [MRE](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) for this issue rather than just providing the traceback. Please share a small amount of code which would allow us to reproduce it.

**Comment by BabuTango** [comment]
@jacobtomlinson The problem was i was passing aws obj. I sorted it out. Thanks
