### ISSUE TITLE
KeyErrors in scheduler with large dataset and sklearn

### ISSUE THREAD

**Issue by kaptravis** [dask/dask#5652]
I am running ElasticNetCV.fit() in parallel using Dask client.submit, and continue to see KeyErrors in the scheduler. I'm not sure if this is a problem, but it seems to be for large datasets. The fits finish despite the errors on smaller datasets, but with with higher NxP and default tolerance, I have yet to see the fit complete. On a single box using pandas/sklearn, it always completes. 

Note that my call to client.submit includes an int parameter that isn't used in the process method. Without it, I would only see one instance of process() running, even though the results would include 2 models

The errors:

distributed.scheduler - ERROR - 'ndarray-e2403ddc588fc5516afcb36223c43bf3'
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/distributed/scheduler.py", line 1753, in update_graph
    resources=resources,
  File "/opt/conda/lib/python3.7/site-packages/distributed/diagnostics/graph_layout.py", line 48, in update_graph
    deps = dependencies[key]
KeyError: 'ndarray-e2403ddc588fc5516afcb36223c43bf3'

distributed.scheduler - INFO - Plugin failed with exception
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/distributed/scheduler.py", line 4359, in transition
    plugin.transition(key, start, finish2, *args, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/distributed/diagnostics/graph_layout.py", line 91, in transition
    self.state_updates.append((self.index[key], finish))
KeyError: '_path_residuals-batch-923e2deb56564bd2923f7337cdffc9fb'

...errors repeat

Example code. On my test cluster of 2x96 cores, it completes, but logs the above errors.
```
import numpy as np
import dask.array as da
from dask.distributed import Client
from sklearn import linear_model
from joblib import parallel_backend
from dask_glm.utils import make_y

client = Client(<scheduler>)
    
N = 200000
P = 10000
chunks = 3e3
    
beta = (np.random.random(P) - 0.5) * 3 
X = da.random.random((N,len(beta)), chunks=(chunks,P))
y = make_y(X, beta=np.array(beta), chunks=chunks)
   
def process(x, y, i):
    enet = linear_model.ElasticNetCV(fit_intercept=True, tol=0.5, normalize=True, n_jobs=-1, max_iter=50000, selection='random')

    with parallel_backend('dask'):
        enet.fit(x, y)
    return enet

results = [client.submit(process, X, y, i) for i in range(2)]
client.gather(results)
```

**Comment by jacobtomlinson** [comment]
Thanks for raising this. The scheduler will retry failed tasks a couple of times, so you may be seeing an intermediate failure which ends up succeeding on retry.

@TomAugspurger or @mrocklin may be able to advise more here.

**Comment by TomAugspurger** [comment]
@kaptravis what version of joblib are you using?

We have a few of these issues open I think. https://github.com/scikit-learn/scikit-learn/issues/15383 is one, though that's a CancelledError.

**Comment by kaptravis** [comment]
We're using joblib 0.14

I've seen similar issues like the one you mention, but it's difficult to tell if it's related

**Comment by mrocklin** [comment]
This is a bug in the graph layout code in the dashboard, I think because of different key types.  It shouldn't affect actual operation.  It would be great if someone were to fix this, but it's not critical.
