### ISSUE TITLE
running dask-ml randomized search on k8s gets stream closed

### ISSUE THREAD

**Issue by Casyfill** [dask/dask#5667]
not sure where is the issue.
```
dask 2.8.1
distributed 2.8.1
dask_ml 1.1.1
```

Getting the below on adaptive k8s cluster, using dask-ml `RandomizedSearchCV` on a custom model.
Seems model is far from using even half of each pod's memory. Here is the worker log:
```
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/distributed/worker.py", line 1908, in gather_dep
    self.rpc, deps, worker, who=self.address
  File "/opt/conda/lib/python3.7/site-packages/distributed/worker.py", line 3136, in get_data_from_worker
    max_connections=max_connections,
  File "/opt/conda/lib/python3.7/site-packages/distributed/core.py", line 532, in send_recv
    response = await comm.read(deserializers=deserializers)
  File "/opt/conda/lib/python3.7/site-packages/distributed/comm/tcp.py", line 204, in read
    convert_stream_closed_error(self, e)
  File "/opt/conda/lib/python3.7/site-packages/distributed/comm/tcp.py", line 132, in convert_stream_closed_error
    raise CommClosedError("in %s: %s" % (obj, exc))
distributed.comm.core.CommClosedError: in <closed TCP>: Stream is closed
distributed.worker - INFO - Can't find dependencies for key ('boundedregressor-fit-score-adc450ea4dcf1f11586f91b2ee850044', 1, 8)
distributed.worker - INFO - Dependent not found: cv-split-adc450ea4dcf1f11586f91b2ee850044 1 .  Asking scheduler
distributed.worker - INFO - Dependent not found: array-1a506d6e2fa48ad7e74d88d8cf9ffc36 1 .  Asking scheduler
distributed.worker - ERROR - Worker stream died during communication: tcp://10.92.197.192:38211
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/distributed/comm/tcp.py", line 184, in read
    n_frames = await stream.read_bytes(8)
tornado.iostream.StreamClosedError: Stream is closed
```

here is the scheduler log:
```
distributed.scheduler - INFO - Register tcp://10.92.197.107:45965
distributed.scheduler - INFO - Starting worker compute stream, tcp://10.92.197.107:45965
distributed.core - INFO - Starting established connection
distributed.scheduler - INFO - Remove worker tcp://10.92.197.192:41843
distributed.core - INFO - Removing comms to tcp://10.92.197.192:41843
distributed.scheduler - INFO - Client Client-fa85e734-162a-11ea-b16b-8c85908ae04d requests to retry 1 keys
distributed.scheduler - INFO - Client Client-fa85e734-162a-11ea-b16b-8c85908ae04d requests to retry 1 keys
distributed.scheduler - INFO - Client Client-fa85e734-162a-11ea-b16b-8c85908ae04d requests to retry 1 keys
distributed.scheduler - INFO - Client Client-fa85e734-162a-11ea-b16b-8c85908ae04d requests to retry 1 keys
```

**Comment by Casyfill** [comment]
visually it looks like all tasks except model fitting are done, and some models are being finished, but then something happens (pod dies?) and the whole list of model fitting and a few other tasks re-run again and again

**Comment by TomAugspurger** [comment]
Just to confirm, you can train the model to completion without using dask-ml?

You might try setting the logging level to debug: https://docs.dask.org/en/latest/configuration.html#yaml-files. That may give more information on why the worker is going away.

**Comment by Casyfill** [comment]
1) Yes, I can confirm that once I swap dask-ml Randomized CV with sklearn implementation, everything is fine. 
2) That being said, when I switch to the local cluster (on my machine), issue persists.

With switching log levels I am now getting this issue
```
File ....../distributed/protocol/pickle.py", line 59, in loads
    return pickle.loads(x)
AttributeError: 'WorkState' object has no attribute 'bandwidth'
distributed protocol.pickle - INFO - Failded to deserialize b"\......
```

**Comment by debabrata-mishra** [comment]
> visually it looks like all tasks except model fitting are done, and some models are being finished, but then something happens (pod dies?) and the whole list of model fitting and a few other tasks re-run again and again

I was facing a similar issue and mostly it was due to memory error. If you check for the worker logs then you might be able to see the event. This might be coming up when task graphs are computed on chunks of data, which is wrapped inside the fit method. In such scenarios, the worker is either restarted or it gets killed.

**Comment by TomAugspurger** [comment]
Thanks for that info @debabrata-mishra. Can you check, do you ever see the error with `refit=False`?

@Casyfill sorry, missed your other message. That second warning / AttributeError indicates a version mismatch in your environment.
