### ISSUE TITLE
Dask read sql table() sometimes not functioning properly for reading DB 

### ISSUE THREAD

**Issue by Vanderser** [dask/dask#5723]
Yesterday, I am using Dask to try to working with a Local DB, I also post this at StackOverflow with some detailed explanation: https://stackoverflow.com/questions/59370582/does-dask-dataframes-not-tolerate-for-na-values-in-it-getting-valueerror-canno

read_sql_table is able to read the table from my LocalDB, but The main issue I encounter is when I check it personally by inspecting each table using .head(). Here is my snippets:

```
ddf_authorized = dd.read_sql_table("cz_transaction_authorized", 
                                   "mysql+pymysql://user_account:mysqlworld@127.0.0.1:3306/user","id")
ddf_mobileuser = dd.read_sql_table("cz_mobile_user", 
                                   "mysql+pymysql://user_account:mysqlworld@127.0.0.1:3306/user","id")
ddf_users = dd.read_sql_table("users", 
                              "mysql+pymysql://user_account:mysqlworld@127.0.0.1:3306/user","id")
ddf_reader = dd.read_sql_table("reader", 
                               "mysql+pymysql://user_account:mysqlworld@127.0.0.1:3306/user","id")
ddf_mid = dd.read_sql_table("cz_mid",
                            "mysql+pymysql://user_account:mysqlworld@127.0.0.1:3306/user","id")
ddf_categorymastermcc = dd.read_sql_table("category_master_mcc",
                                          "mysql+pymysql://user_account:mysqlworld@127.0.0.1:3306/user","id")
```
There are tables that I used .head() is giving an expected output, which is the first 5 rows of the table, in my case, it is only mobileuser, users, and categorymastermcc from above, other tables beside that will return `ValueError: Cannot convert non-finite values (NA or inf) to integer` even though I already get rid the NA Values and also use the tables that clear from NA, change the column dtype to its optimal dtype using astype(). I also tried to read with dd.read_csv() by exporting one of the tables into csv (which is reader contains 8K rows), the results is I can read the table fine and inspect it fine too using ,head()

But since I am working also with Transacation that have 1.4M rows, (which in my case it is failed just to inspect the head()), it will be troublesome to export this kind to csv and then read it using dask.read_csv()

Is there any thing I miss? or is this a bug?

Thank You

**Comment by mrocklin** [comment]
Hi Jovan, I'm curious, does this work with Pandas?  If the problem persists
with pandas then it would be more effective to raise the issue there.
Also, it would be useful to have a full traceback of the exception.

**Comment by Vanderser** [comment]
Hi mrocklin, thanks for the reply :)

I runned ddf_reader.head()

And this is the Exception I get...

```
Traceback (most recent call last):

  File "<ipython-input-6-9b383ccf44fb>", line 1, in <module>
    ddf_reader.head()

  File "c:\users\user\appdata\local\programs\python\python37\lib\site-packages\dask\dataframe\core.py", line 950, in head
    return self._head(n=n, npartitions=npartitions, compute=compute, safe=True)

  File "c:\users\user\appdata\local\programs\python\python37\lib\site-packages\dask\dataframe\core.py", line 983, in _head
    result = result.compute()

  File "c:\users\user\appdata\local\programs\python\python37\lib\site-packages\dask\base.py", line 165, in compute
    (result,) = compute(self, traverse=False, **kwargs)

  File "c:\users\user\appdata\local\programs\python\python37\lib\site-packages\dask\base.py", line 436, in compute
    results = schedule(dsk, keys, **kwargs)

  File "c:\users\user\appdata\local\programs\python\python37\lib\site-packages\dask\threaded.py", line 81, in get
    **kwargs

  File "c:\users\user\appdata\local\programs\python\python37\lib\site-packages\dask\local.py", line 486, in get_async
    raise_exception(exc, tb)

  File "c:\users\user\appdata\local\programs\python\python37\lib\site-packages\dask\local.py", line 316, in reraise
    raise exc

  File "c:\users\user\appdata\local\programs\python\python37\lib\site-packages\dask\local.py", line 222, in execute_task
    result = _execute_task(task, data)

  File "c:\users\user\appdata\local\programs\python\python37\lib\site-packages\dask\core.py", line 118, in _execute_task
    args2 = [_execute_task(a, cache) for a in args]

  File "c:\users\user\appdata\local\programs\python\python37\lib\site-packages\dask\core.py", line 118, in <listcomp>
    args2 = [_execute_task(a, cache) for a in args]

  File "c:\users\user\appdata\local\programs\python\python37\lib\site-packages\dask\core.py", line 118, in _execute_task
    args2 = [_execute_task(a, cache) for a in args]

  File "c:\users\user\appdata\local\programs\python\python37\lib\site-packages\dask\core.py", line 118, in <listcomp>
    args2 = [_execute_task(a, cache) for a in args]

  File "c:\users\user\appdata\local\programs\python\python37\lib\site-packages\dask\core.py", line 118, in _execute_task
    args2 = [_execute_task(a, cache) for a in args]

  File "c:\users\user\appdata\local\programs\python\python37\lib\site-packages\dask\core.py", line 118, in <listcomp>
    args2 = [_execute_task(a, cache) for a in args]

  File "c:\users\user\appdata\local\programs\python\python37\lib\site-packages\dask\core.py", line 119, in _execute_task
    return func(*args2)

  File "c:\users\user\appdata\local\programs\python\python37\lib\site-packages\dask\utils.py", line 29, in apply
    return func(*args, **kwargs)

  File "c:\users\user\appdata\local\programs\python\python37\lib\site-packages\dask\dataframe\io\sql.py", line 210, in _read_sql_chunk
    return df.astype(meta.dtypes.to_dict(), copy=False)

  File "c:\users\user\appdata\local\programs\python\python37\lib\site-packages\pandas\core\generic.py", line 5866, in astype
    dtype=dtype[col_name], copy=copy, errors=errors, **kwargs

  File "c:\users\user\appdata\local\programs\python\python37\lib\site-packages\pandas\core\generic.py", line 5883, in astype
    dtype=dtype, copy=copy, errors=errors, **kwargs

  File "c:\users\user\appdata\local\programs\python\python37\lib\site-packages\pandas\core\internals\managers.py", line 581, in astype
    return self.apply("astype", dtype=dtype, **kwargs)

  File "c:\users\user\appdata\local\programs\python\python37\lib\site-packages\pandas\core\internals\managers.py", line 438, in apply
    applied = getattr(b, f)(**kwargs)

  File "c:\users\user\appdata\local\programs\python\python37\lib\site-packages\pandas\core\internals\blocks.py", line 557, in astype
    return self._astype(dtype, copy=copy, errors=errors, values=values, **kwargs)

  File "c:\users\user\appdata\local\programs\python\python37\lib\site-packages\pandas\core\internals\blocks.py", line 641, in _astype
    values = astype_nansafe(vals1d, dtype, copy=True, **kwargs)

  File "c:\users\user\appdata\local\programs\python\python37\lib\site-packages\pandas\core\dtypes\cast.py", line 700, in astype_nansafe
    "Cannot convert non-finite values (NA or inf) to " "integer"

ValueError: Cannot convert non-finite values (NA or inf) to integer
```

**Comment by Vanderser** [comment]
to test the reader table (if wanted), the reader table I converted to csv, are Included in the stackoverflow.. is is the table which I used to inspect the head()

**Comment by Vanderser** [comment]
And also I test it in Pandas too. This works in Pandas..

x = pd.read_sql_table("reader", "mysql+pymysql://user_account:mysqlworld@127.0.0.1:3306/user")

x.head()
Out[6]: 
   id      devicetype_fk  version  ... device_type merchant          last_ksn_mag
0   1  INGENICO_ICMP_122        1  ...        None     None                  None
1   2  INGENICO_ICMP_122       47  ...        None     None  4101202122340000002F
2   3  INGENICO_ICMP_122        1  ...        None     None                  None
3   4  INGENICO_ICMP_122      290  ...        None     None                  None
4   5  INGENICO_ICMP_122      107  ...        None     None                  None

[5 rows x 18 columns]

**Comment by TomAugspurger** [comment]
@Vanderser what are the dtypes on `ddf_reader`, and what are the types of the columns on the table?

That error message indicates an issue with trying to convert a float column to ints, which usually indicates a type inference problem. You might pass `meta=` to the `read_sql_table` with the correct dtypes. `read_csv` has a nice error message for this case.

**Comment by Vanderser** [comment]
actually for ddf_reader, I just subset it to these 3 important columns only, 

```
ddf_reader = ddf_reader.reset_index()
ddf_reader = ddf_reader[["id","devicetype_fk","serial_number"]]
ddf_reader = ddf_reader.rename(columns={"id":"reader_id"})

ddf_reader.columns.values
Out[18]: array(['reader_id', 'devicetype_fk', 'serial_number'], dtype=object)

ddf_reader["reader_id"].dtype
Out[19]: dtype('int64')

ddf_reader["devicetype_fk"].dtype
Out[20]: dtype('O')

ddf_reader["serial_number"].dtype
Out[21]: dtype('O')
```
so to put it straight.. my ddf_reader didn;t have the float columns.. but even with this, this still triggered the `ValueError: Cannot convert non-finite values (NA or inf) to integer`

**Comment by TomAugspurger** [comment]
The issue is (maybe) that `reader_id` is expecting integers by finds
missing values (floats), though it's hard to say for sure.without a minimal
example. Did you provide the types from the database? Is ID nullable?

What types do you get when you read with pandas?

**Comment by Vanderser** [comment]
@TomAugspurger here is the ddf_reader I converted for working example.. http://www.sharecsv.com/s/147ba0bb507bb6dcc14a3a6c91af4eef/reader_table.csv this is the table itself converted, I was sure there wasn't any null values in reader_id

**Comment by Vanderser** [comment]
This is the defined types from Database
![image](https://user-images.githubusercontent.com/40754909/71139152-ee07e400-223f-11ea-8560-e796b3edaa70.png)

**Comment by Vanderser** [comment]
Pandas type is the same with Dask..

```
x = pd.read_sql_table("reader", "mysql+pymysql://user_account:mysqlworld@127.0.0.1:3306/user")
x.rename(columns={"id":"reader_id"}, inplace=True)

x["reader_id"].dtype
Out[4]: dtype('int64')

x["serial_number"].dtype
Out[5]: dtype('O')

x["devicetype_fk"].dtype
Out[6]: dtype('O')
```

**Comment by TomAugspurger** [comment]
Hard to say what's going on. I'd recommend trying to reduce things to the smallest possible example (size, columns, dtypes) that exhibits the issue to understand where things are going wrong.

**Comment by Vanderser** [comment]
Hi All, its been for 4 Months since my last reports, and for now the last example doesn't exist anymore..  until now I am not sure how to fix this problem... but I have this simplified new example according the issues, with this snippets:

```
import pandas as pd
import pymysql
import dask.dataframe as dd

x = pd.read_sql_table("cz_merchant", "mysql+pymysql://dba.jovan:dbminingczdsjovan@127.0.0.1:33062/czmining_mart_payment",index_col = "id")
y = dd.read_sql_table("cz_merchant", "mysql+pymysql://dba.jovan:dbminingczdsjovan@127.0.0.1:33062/czmining_mart_payment",index_col = "id")
```
above I used Pandas and Dask both to read the same table at my DB.. then i tried to run this info on both:

```
x.info()
<class 'pandas.core.frame.DataFrame'>
Int64Index: 18309 entries, 1 to 18956
Columns: 106 entries, version to pic_contact_email
dtypes: datetime64[ns](7), float64(6), int64(6), object(87)
memory usage: 14.9+ MB

y.info()
<class 'dask.dataframe.core.DataFrame'>
Columns: 106 entries, version to pic_contact_email
dtypes: datetime64[ns](4), object(91), float64(2), int64(9)
```

and finally error came back again when I use the verbose=True parameter

```
x.info(verbose=True)
<class 'pandas.core.frame.DataFrame'>
Int64Index: 18309 entries, 1 to 18956
Data columns (total 106 columns):
version                             int64
created_by                          object
created_date                        datetime64[ns]
modified_by                         object
modified_date                       datetime64[ns]
activate_date                       datetime64[ns]
status                              object
suspend_date                        datetime64[ns]
terminate_date                      datetime64[ns]
business_type                       object
business_address1                   object
business_address2                   object
business_contact                    object
merchant_name                       object
business_registration_number        object
city                                object
email                               object
postcode                            object
state                               object
setting_fk                          int64
merchant_level                      int64
merchant_parent_path                object
remark                              object
company_name                        object
riskmerchant_fk                     int64
merchant_reference                  object
account_number                      object
bank_code                           object
account_bank_name                   object
account_holder                      object
clearing_fee                        float64
clearing_code                       object
rtgs_code                           object
business_relation_type              object
riskecomm_fk                        object
risk_merchant                       float64
setting                             object
disable_manual_input                float64
enable_manual_input                 object
contingency_routing                 object
category_master_mcc_fk              float64
disable_bill_input                  int64
is_hold                             int64
remark_hold                         object
business_type_1                     object
business_location                   object
business_location_status            object
business_started                    float64
district                            object
bank_approval                       float64
referral_in                         object
referral_out                        object
upgrade_approval                    object
registration_status                 object
approval_date                       datetime64[ns]
merchant_id                         object
merchant_type                       object
reckey                              object
adj_city                            object
adj_province                        object
region                              object
register_stage                      object
origin_source_block                 object
source_block                        object
source_code                         object
reported_approval_date              datetime64[ns]
merchant_name_tag                   object
in_a_group                          object
old_mcc                             object
mid_mcc                             object
source_sales                        object
source_referrer                     object
source_retention                    object
ignored                             object
mid_mandiri_regular_active          object
mid_mandiri_regular_inactive        object
mid_mandiri_va_active               object
mid_mandiri_va_inactive             object
mid_mandiri_installment_active      object
mid_mandiri_installment_inactive    object
mid_bni46_regular_active            object
mid_bni46_regular_inactive          object
mid_bni46_installment_active        object
mid_bni46_installment_inactive      object
mid_maybank_ecom_active             object
mid_maybank_ecom_inactive           object
mid_btpn_transfer_active            object
mid_btpn_transfer_inactive          object
mid_linkaja_active                  object
mid_linkaja_inactive                object
mid_gopay_active                    object
mid_gopay_qris_active               object
mid_gopay_inactive                  object
mid_ovo_active                      object
mid_ovo_inactive                    object
mid_kredivo_active                  object
mid_kredivo_inactive                object
pending_register_stage              object
pending_source_block                object
pending_ignored                     object
partnership_type                    object
pic_salutation                      object
pic_first_name                      object
pic_last_name                       object
pic_contact_phone                   object
pic_contact_email                   object
dtypes: datetime64[ns](7), float64(6), int64(6), object(87)
memory usage: 14.9+ MB

y.info(verbose=True)
Traceback (most recent call last):

  File "<ipython-input-6-7c82db7d4335>", line 1, in <module>
    y.info(verbose=True)

  File "c:\users\user\appdata\local\programs\python\python37\lib\site-packages\dask\dataframe\core.py", line 4252, in info
    zip(computations.keys(), da.compute(*computations.values()))

  File "c:\users\user\appdata\local\programs\python\python37\lib\site-packages\dask\base.py", line 437, in compute
    results = schedule(dsk, keys, **kwargs)

  File "c:\users\user\appdata\local\programs\python\python37\lib\site-packages\dask\threaded.py", line 84, in get
    **kwargs

  File "c:\users\user\appdata\local\programs\python\python37\lib\site-packages\dask\local.py", line 486, in get_async
    raise_exception(exc, tb)

  File "c:\users\user\appdata\local\programs\python\python37\lib\site-packages\dask\local.py", line 316, in reraise
    raise exc

  File "c:\users\user\appdata\local\programs\python\python37\lib\site-packages\dask\local.py", line 222, in execute_task
    result = _execute_task(task, data)

  File "c:\users\user\appdata\local\programs\python\python37\lib\site-packages\dask\core.py", line 121, in _execute_task
    return func(*(_execute_task(a, cache) for a in args))

  File "c:\users\user\appdata\local\programs\python\python37\lib\site-packages\dask\core.py", line 121, in <genexpr>
    return func(*(_execute_task(a, cache) for a in args))

  File "c:\users\user\appdata\local\programs\python\python37\lib\site-packages\dask\core.py", line 121, in _execute_task
    return func(*(_execute_task(a, cache) for a in args))

  File "c:\users\user\appdata\local\programs\python\python37\lib\site-packages\dask\utils.py", line 30, in apply
    return func(*args, **kwargs)

  File "c:\users\user\appdata\local\programs\python\python37\lib\site-packages\dask\dataframe\io\sql.py", line 213, in _read_sql_chunk
    return df.astype(meta.dtypes.to_dict(), copy=False)

  File "c:\users\user\appdata\local\programs\python\python37\lib\site-packages\pandas\core\generic.py", line 5866, in astype
    dtype=dtype[col_name], copy=copy, errors=errors, **kwargs

  File "c:\users\user\appdata\local\programs\python\python37\lib\site-packages\pandas\core\generic.py", line 5883, in astype
    dtype=dtype, copy=copy, errors=errors, **kwargs

  File "c:\users\user\appdata\local\programs\python\python37\lib\site-packages\pandas\core\internals\managers.py", line 581, in astype
    return self.apply("astype", dtype=dtype, **kwargs)

  File "c:\users\user\appdata\local\programs\python\python37\lib\site-packages\pandas\core\internals\managers.py", line 438, in apply
    applied = getattr(b, f)(**kwargs)

  File "c:\users\user\appdata\local\programs\python\python37\lib\site-packages\pandas\core\internals\blocks.py", line 557, in astype
    return self._astype(dtype, copy=copy, errors=errors, values=values, **kwargs)

  File "c:\users\user\appdata\local\programs\python\python37\lib\site-packages\pandas\core\internals\blocks.py", line 641, in _astype
    values = astype_nansafe(vals1d, dtype, copy=True, **kwargs)

  File "c:\users\user\appdata\local\programs\python\python37\lib\site-packages\pandas\core\dtypes\cast.py", line 700, in astype_nansafe
    "Cannot convert non-finite values (NA or inf) to " "integer"

ValueError: Cannot convert non-finite values (NA or inf) to integer
```
