### ISSUE TITLE
 read_hdf  followed by  drop_duplicates error

### ISSUE THREAD

**Issue by DmitriyG228** [dask/dask#5742]
**Bug report:** 

Hi,  read_hdf  followed by drop_duplicates does not work for me:

```
table1 = dd.read_hdf('table1.hdf5', 'data')
table2 = dd.read_hdf('table2.hdf5', 'data')
```
this works fine:
```
table1.head() 
table2.head() 
table1.tail() 
table2.tail() 

tables = table1.append(table2)

tables.head() 
```
this giver the error:
```
tables.drop_duplicates().head()
``` 
what could be the reason?
the error:
```

`HDF5ExtError                              Traceback (most recent call last)
<ipython-input-36-e817f0b8def1> in <module>
----> 1 app.drop_duplicates(['available','date','listing_id'], keep='last').head()

~/anaconda3/envs/fastai/lib/python3.7/site-packages/dask/dataframe/core.py in head(self, n, npartitions, compute)
    957             Whether to compute the result, default is True.
    958         """
--> 959         return self._head(n=n, npartitions=npartitions, compute=compute, safe=True)
    960 
    961     def _head(self, n, npartitions, compute, safe):

~/anaconda3/envs/fastai/lib/python3.7/site-packages/dask/dataframe/core.py in _head(self, n, npartitions, compute, safe)
    990 
    991         if compute:
--> 992             result = result.compute()
    993         return result
    994 

~/anaconda3/envs/fastai/lib/python3.7/site-packages/dask/base.py in compute(self, **kwargs)
    163         dask.base.compute
    164         """
--> 165         (result,) = compute(self, traverse=False, **kwargs)
    166         return result
    167 

~/anaconda3/envs/fastai/lib/python3.7/site-packages/dask/base.py in compute(*args, **kwargs)
    434     keys = [x.__dask_keys__() for x in collections]
    435     postcomputes = [x.__dask_postcompute__() for x in collections]
--> 436     results = schedule(dsk, keys, **kwargs)
    437     return repack([f(r, *a) for r, (f, a) in zip(results, postcomputes)])
    438 

~/anaconda3/envs/fastai/lib/python3.7/site-packages/distributed/client.py in get(self, dsk, keys, restrictions, loose_restrictions, resources, sync, asynchronous, direct, retries, priority, fifo_timeout, actors, **kwargs)
   2571                     should_rejoin = False
   2572             try:
-> 2573                 results = self.gather(packed, asynchronous=asynchronous, direct=direct)
   2574             finally:
   2575                 for f in futures.values():

~/anaconda3/envs/fastai/lib/python3.7/site-packages/distributed/client.py in gather(self, futures, errors, direct, asynchronous)
   1871                 direct=direct,
   1872                 local_worker=local_worker,
-> 1873                 asynchronous=asynchronous,
   1874             )
   1875 

~/anaconda3/envs/fastai/lib/python3.7/site-packages/distributed/client.py in sync(self, func, asynchronous, callback_timeout, *args, **kwargs)
    766         else:
    767             return sync(
--> 768                 self.loop, func, *args, callback_timeout=callback_timeout, **kwargs
    769             )
    770 

~/anaconda3/envs/fastai/lib/python3.7/site-packages/distributed/utils.py in sync(loop, func, callback_timeout, *args, **kwargs)
    332     if error[0]:
    333         typ, exc, tb = error[0]
--> 334         raise exc.with_traceback(tb)
    335     else:
    336         return result[0]

~/anaconda3/envs/fastai/lib/python3.7/site-packages/distributed/utils.py in f()
    316             if callback_timeout is not None:
    317                 future = gen.with_timeout(timedelta(seconds=callback_timeout), future)
--> 318             result[0] = yield future
    319         except Exception as exc:
    320             error[0] = sys.exc_info()

~/anaconda3/envs/fastai/lib/python3.7/site-packages/tornado/gen.py in run(self)
    733 
    734                     try:
--> 735                         value = future.result()
    736                     except Exception:
    737                         exc_info = sys.exc_info()

~/anaconda3/envs/fastai/lib/python3.7/site-packages/distributed/client.py in _gather(self, futures, errors, direct, local_worker)
   1727                             exc = CancelledError(key)
   1728                         else:
-> 1729                             raise exception.with_traceback(traceback)
   1730                         raise exc
   1731                     if errors == "skip":

~/anaconda3/envs/fastai/lib/python3.7/site-packages/dask/dataframe/io/hdf.py in _pd_read_hdf()
    390         lock.acquire()
    391     try:
--> 392         result = pd.read_hdf(path, key, **kwargs)
    393     finally:
    394         if lock:

~/anaconda3/envs/fastai/lib/python3.7/site-packages/pandas/io/pytables.py in read_hdf()
    382             )
    383 
--> 384         store = HDFStore(path_or_buf, mode=mode, **kwargs)
    385         # can't auto open/close if we are using an iterator
    386         # so delegate to the iterator

~/anaconda3/envs/fastai/lib/python3.7/site-packages/pandas/io/pytables.py in __init__()
    503         self._fletcher32 = fletcher32
    504         self._filters = None
--> 505         self.open(mode=mode, **kwargs)
    506 
    507     def __fspath__(self):

~/anaconda3/envs/fastai/lib/python3.7/site-packages/pandas/io/pytables.py in open()
    625 
    626         try:
--> 627             self._handle = tables.open_file(self._path, self._mode, **kwargs)
    628         except (IOError) as e:  # pragma: no cover
    629             if "can not be written" in str(e):

~/anaconda3/envs/fastai/lib/python3.7/site-packages/tables/file.py in open_file()
    318 
    319     # Finally, create the File instance, and return it
--> 320     return File(filename, mode, title, root_uep, filters, **kwargs)
    321 
    322 

~/anaconda3/envs/fastai/lib/python3.7/site-packages/tables/file.py in __init__()
    782 
    783         # Now, it is time to initialize the File extension
--> 784         self._g_new(filename, mode, **params)
    785 
    786         # Check filters and set PyTables format version for new files.

tables/hdf5extension.pyx in tables.hdf5extension.File._g_new()

HDF5ExtError: HDF5 error back trace

  File "H5F.c", line 511, in H5Fopen
    unable to open file
  File "H5Fint.c", line 1519, in H5F_open
    unable to lock the file
  File "H5FD.c", line 1650, in H5FD_lock
    driver lock request failed
  File "H5FDsec2.c", line 941, in H5FD_sec2_lock
    unable to lock file, errno = 11, error message = 'Resource temporarily unavailable'

End of HDF5 error back trace

Unable to open/create file '/home/dima/my_files/app/airbnb/hdf_files/sql_cals.hdf5'`

```

**Comment by DmitriyG228** [comment]
I have  noticed, that the error happens in the presence of the following code:

```
from dask.distributed import Client
client = Client(n_workers=64, 
                threads_per_worker=16,
                memory_limit='16GB')
```

**Comment by mrocklin** [comment]
Hi @DmitriyG228 , thank you for raising an issue.  Unfortunately it's not clear why you're getting your error.  It could be from any number of reasons including Dask, HDF5, your file system, or many other issues.  We probably don't have enough information here to help you resolve your problem.  

If you're able to isolate things further into a Dask bug then that would be helpful.  (See https://blog.dask.org/2018/02/28/minimal-bug-reports)

Looking briefly at the error that you were receiving

>     unable to lock file, errno = 11, error message = 'Resource temporarily unavailable'

My guess would be some conflict between parallel access to HDF5 and a picky file system.  I don't know though.  You might have to ask your system administrator.

**Comment by TomAugspurger** [comment]
@DmitriyG228 were you able to debug this any further?

**Comment by jrbourbeau** [comment]
Closing for now. @DmitriyG228 we can reopen if you're able to produce a [minimal example](https://blog.dask.org/2018/02/28/minimal-bug-reports)
