### ISSUE TITLE
Reading from remote HDFS requires local libhdfs/arrow installation

### ISSUE THREAD

**Issue by bschreck** [dask/dask#5758]
My scheduler/worker nodes are running on a cluster that has Hadoop/HDFS installed, and ideally I'd like to not have to install it on the machine that runs the (distributed) Client.

There are 2 ways I'm able to load a parquet dataset from HDFS into a dask dataframe:
1. Install Hadoop & HDFS locally, and use `ddf = dd.read_parquet('hdfs://filepath/*.parquet', engine='pyarrow', storage_options={host: host, port:port})`
2. Load the dataframe using a delayed object (which means I don't have access to metadata locally): `ddf = delayed(dd.read_parquet)('hdfs://filepath/*.parquet', engine='pyarrow')`

Ideally I'd like to just do option 1 without installing hadoop. I'm pretty sure the issue is that dask tries to list out all the parquet files in the directory, and pull some metadata, using pyarrow.hdfs.

For reference the error I'm getting:

```
---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
<ipython-input-5-ea7e3105d34e> in <module>()
      1 td = dd.read_parquet('hdfs:///user/ec2-user/fraud_train/*.parquet', engine='pyarrow', 
----> 2                      storage_options=storage_options)

~/anaconda3/envs/python3/lib/python3.6/site-packages/dask/dataframe/io/parquet/core.py in read_parquet(path, columns, filters, categories, index, storage_options, engine, gather_statistics, split_row_groups, chunksize, **kwargs)
    212     if hasattr(path, "name"):
    213         path = stringify_path(path)
--> 214     fs, _, paths = get_fs_token_paths(path, mode="rb", storage_options=storage_options)
    215 
    216     paths = sorted(paths, key=natural_sort_key)  # numeric rather than glob ordering

~/anaconda3/envs/python3/lib/python3.6/site-packages/fsspec/core.py in get_fs_token_paths(urlpath, mode, num, name_function, storage_options, protocol)
    396         path = cls._strip_protocol(urlpath)
    397         update_storage_options(options, storage_options)
--> 398         fs = cls(**options)
    399 
    400         if "w" in mode:

~/anaconda3/envs/python3/lib/python3.6/site-packages/fsspec/spec.py in __call__(cls, *args, **kwargs)
     50             return cls._cache[token]
     51         else:
---> 52             obj = super().__call__(*args, **kwargs)
     53             # Setting _fs_token here causes some static linters to complain.
     54             obj._fs_token_ = token

~/anaconda3/envs/python3/lib/python3.6/site-packages/fsspec/implementations/hdfs.py in __init__(self, host, port, user, kerb_ticket, driver, extra_conf, **kwargs)
     48             kerb_ticket=kerb_ticket,
     49             driver=driver,
---> 50             extra_conf=extra_conf,
     51         )
     52 

~/anaconda3/envs/python3/lib/python3.6/site-packages/pyarrow/hdfs.py in __init__(self, host, port, user, kerb_ticket, driver, extra_conf)
     36                  driver='libhdfs', extra_conf=None):
     37         if driver == 'libhdfs':
---> 38             _maybe_set_hadoop_classpath()
     39 
     40         self._connect(host, port, user, kerb_ticket, driver, extra_conf)

~/anaconda3/envs/python3/lib/python3.6/site-packages/pyarrow/hdfs.py in _maybe_set_hadoop_classpath()
    138             classpath = _hadoop_classpath_glob(hadoop_bin)
    139     else:
--> 140         classpath = _hadoop_classpath_glob('hadoop')
    141 
    142     os.environ['CLASSPATH'] = classpath.decode('utf-8')

~/anaconda3/envs/python3/lib/python3.6/site-packages/pyarrow/hdfs.py in _hadoop_classpath_glob(hadoop_bin)
    163 
    164     hadoop_classpath_args = (hadoop_bin, 'classpath', '--glob')
--> 165     return subprocess.check_output(hadoop_classpath_args)
    166 
    167 

~/anaconda3/envs/python3/lib/python3.6/subprocess.py in check_output(timeout, *popenargs, **kwargs)
    334 
    335     return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
--> 336                **kwargs).stdout
    337 
    338 

~/anaconda3/envs/python3/lib/python3.6/subprocess.py in run(input, timeout, check, *popenargs, **kwargs)
    401         kwargs['stdin'] = PIPE
    402 
--> 403     with Popen(*popenargs, **kwargs) as process:
    404         try:
    405             stdout, stderr = process.communicate(input, timeout=timeout)

~/anaconda3/envs/python3/lib/python3.6/subprocess.py in __init__(self, args, bufsize, executable, stdin, stdout, stderr, preexec_fn, close_fds, shell, cwd, env, universal_newlines, startupinfo, creationflags, restore_signals, start_new_session, pass_fds, encoding, errors)
    707                                 c2pread, c2pwrite,
    708                                 errread, errwrite,
--> 709                                 restore_signals, start_new_session)
    710         except:
    711             # Cleanup if the child failed starting.

~/anaconda3/envs/python3/lib/python3.6/subprocess.py in _execute_child(self, args, executable, preexec_fn, close_fds, pass_fds, cwd, env, startupinfo, creationflags, shell, p2cread, p2cwrite, c2pread, c2pwrite, errread, errwrite, restore_signals, start_new_session)
   1342                         if errno_num == errno.ENOENT:
   1343                             err_msg += ': ' + repr(err_filename)
-> 1344                     raise child_exception_type(errno_num, err_msg, err_filename)
   1345                 raise child_exception_type(err_msg)
   1346 

FileNotFoundError: [Errno 2] No such file or directory: 'hadoop': 'hadoop'
```

**Comment by mrocklin** [comment]
Yes, that's correct.  Your option 2 is the best current workaround today.  

There has been talk about doing the metadata loading as a compute task on the workers as well.  I believe that @jcrist raised an issue about this somewhere, but after a brief search I couldn't find it.

**Comment by bschreck** [comment]
Does the dask dataframe returned by the delayed call have access to all the same methods as a local dask dataframe?

**Comment by bschreck** [comment]
Actually When I try option 2 I still get an error upon deserialization:

```
distributed.protocol.pickle - INFO - Failed to deserialize '[left out data byte stream here]'
Traceback (most recent call last):
  File "/home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages/distributed/protocol/pickle.py", line 59, in loads
    return pickle.loads(x)
  File "/home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages/fsspec/spec.py", line 52, in __call__
    obj = super().__call__(*args, **kwargs)
  File "/home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages/fsspec/implementations/hdfs.py", line 50, in __init__
    extra_conf=extra_conf,
  File "/home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages/pyarrow/hdfs.py", line 38, in __init__
    _maybe_set_hadoop_classpath()
  File "/home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages/pyarrow/hdfs.py", line 140, in _maybe_set_hadoop_classpath
    classpath = _hadoop_classpath_glob('hadoop')
  File "/home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages/pyarrow/hdfs.py", line 165, in _hadoop_classpath_glob
    return subprocess.check_output(hadoop_classpath_args)
  File "/home/ec2-user/anaconda3/envs/python3/lib/python3.6/subprocess.py", line 336, in check_output
    **kwargs).stdout
  File "/home/ec2-user/anaconda3/envs/python3/lib/python3.6/subprocess.py", line 403, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/home/ec2-user/anaconda3/envs/python3/lib/python3.6/subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "/home/ec2-user/anaconda3/envs/python3/lib/python3.6/subprocess.py", line 1344, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'hadoop': 'hadoop'
distributed.protocol.core - CRITICAL - Failed to deserialize
Traceback (most recent call last):
  File "/home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages/distributed/protocol/core.py", line 124, in loads
    value = _deserialize(head, fs, deserializers=deserializers)
  File "/home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages/distributed/protocol/serialize.py", line 268, in deserialize
    return loads(header, frames)
  File "/home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages/distributed/protocol/serialize.py", line 62, in pickle_loads
    return pickle.loads(b"".join(frames))
  File "/home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages/distributed/protocol/pickle.py", line 59, in loads
    return pickle.loads(x)
  File "/home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages/fsspec/spec.py", line 52, in __call__
    obj = super().__call__(*args, **kwargs)
  File "/home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages/fsspec/implementations/hdfs.py", line 50, in __init__
    extra_conf=extra_conf,
  File "/home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages/pyarrow/hdfs.py", line 38, in __init__
    _maybe_set_hadoop_classpath()
  File "/home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages/pyarrow/hdfs.py", line 140, in _maybe_set_hadoop_classpath
    classpath = _hadoop_classpath_glob('hadoop')
  File "/home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages/pyarrow/hdfs.py", line 165, in _hadoop_classpath_glob
    return subprocess.check_output(hadoop_classpath_args)
  File "/home/ec2-user/anaconda3/envs/python3/lib/python3.6/subprocess.py", line 336, in check_output
    **kwargs).stdout
  File "/home/ec2-user/anaconda3/envs/python3/lib/python3.6/subprocess.py", line 403, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/home/ec2-user/anaconda3/envs/python3/lib/python3.6/subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "/home/ec2-user/anaconda3/envs/python3/lib/python3.6/subprocess.py", line 1344, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'hadoop': 'hadoop'
---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
<ipython-input-6-b9fc82537882> in <module>()
----> 1 train_data = load_dask_dataframe('fraud_train', client)
      2 test_data = load_dask_dataframe('fraud_test', client)

~/anaconda3/envs/python3/lib/python3.6/site-packages/cbml/dataio/emr.py in load_dask_dataframe(path, dask_client, fs, hdfs_host, hdfs_port)
    345                                     dataset={'validate_schema': False,
    346                                              'metadata': metadata,
--> 347                                              'schema': schema}).compute()
    348 
    349 

~/anaconda3/envs/python3/lib/python3.6/site-packages/dask/base.py in compute(self, **kwargs)
    163         dask.base.compute
    164         """
--> 165         (result,) = compute(self, traverse=False, **kwargs)
    166         return result
    167 

~/anaconda3/envs/python3/lib/python3.6/site-packages/dask/base.py in compute(*args, **kwargs)
    434     keys = [x.__dask_keys__() for x in collections]
    435     postcomputes = [x.__dask_postcompute__() for x in collections]
--> 436     results = schedule(dsk, keys, **kwargs)
    437     return repack([f(r, *a) for r, (f, a) in zip(results, postcomputes)])
    438 

~/anaconda3/envs/python3/lib/python3.6/site-packages/distributed/client.py in get(self, dsk, keys, restrictions, loose_restrictions, resources, sync, asynchronous, direct, retries, priority, fifo_timeout, actors, **kwargs)
   2571                     should_rejoin = False
   2572             try:
-> 2573                 results = self.gather(packed, asynchronous=asynchronous, direct=direct)
   2574             finally:
   2575                 for f in futures.values():

~/anaconda3/envs/python3/lib/python3.6/site-packages/distributed/client.py in gather(self, futures, errors, direct, asynchronous)
   1871                 direct=direct,
   1872                 local_worker=local_worker,
-> 1873                 asynchronous=asynchronous,
   1874             )
   1875 

~/anaconda3/envs/python3/lib/python3.6/site-packages/distributed/client.py in sync(self, func, asynchronous, callback_timeout, *args, **kwargs)
    766         else:
    767             return sync(
--> 768                 self.loop, func, *args, callback_timeout=callback_timeout, **kwargs
    769             )
    770 

~/anaconda3/envs/python3/lib/python3.6/site-packages/distributed/utils.py in sync(loop, func, callback_timeout, *args, **kwargs)
    332     if error[0]:
    333         typ, exc, tb = error[0]
--> 334         raise exc.with_traceback(tb)
    335     else:
    336         return result[0]

~/anaconda3/envs/python3/lib/python3.6/site-packages/distributed/utils.py in f()
    316             if callback_timeout is not None:
    317                 future = gen.with_timeout(timedelta(seconds=callback_timeout), future)
--> 318             result[0] = yield future
    319         except Exception as exc:
    320             error[0] = sys.exc_info()

~/anaconda3/envs/python3/lib/python3.6/site-packages/tornado/gen.py in run(self)
   1097 
   1098                     try:
-> 1099                         value = future.result()
   1100                     except Exception:
   1101                         self.had_exception = True

~/anaconda3/envs/python3/lib/python3.6/site-packages/distributed/client.py in _gather(self, futures, errors, direct, local_worker)
   1756                 else:
   1757                     self._gather_future = future
-> 1758                 response = await future
   1759 
   1760             if response["status"] == "error":

~/anaconda3/envs/python3/lib/python3.6/site-packages/distributed/client.py in _gather_remote(self, direct, local_worker)
   1808 
   1809             else:  # ask scheduler to gather data for us
-> 1810                 response = await retry_operation(self.scheduler.gather, keys=keys)
   1811         finally:
   1812             self._gather_semaphore.release()

~/anaconda3/envs/python3/lib/python3.6/site-packages/distributed/utils_comm.py in retry_operation(coro, operation, *args, **kwargs)
    357         delay_min=retry_delay_min,
    358         delay_max=retry_delay_max,
--> 359         operation=operation,
    360     )

~/anaconda3/envs/python3/lib/python3.6/site-packages/distributed/utils_comm.py in retry(coro, count, delay_min, delay_max, jitter_fraction, retry_on_exceptions, operation)
    345                 delay *= 1 + random.random() * jitter_fraction
    346             await asyncio.sleep(delay)
--> 347     return await coro()
    348 
    349 

~/anaconda3/envs/python3/lib/python3.6/site-packages/distributed/core.py in send_recv_from_rpc(**kwargs)
    755             name, comm.name = comm.name, "ConnectionPool." + key
    756             try:
--> 757                 result = await send_recv(comm=comm, op=key, **kwargs)
    758             finally:
    759                 self.pool.reuse(self.addr, comm)

~/anaconda3/envs/python3/lib/python3.6/site-packages/distributed/core.py in send_recv(comm, reply, serializers, deserializers, **kwargs)
    538         await comm.write(msg, serializers=serializers, on_error="raise")
    539         if reply:
--> 540             response = await comm.read(deserializers=deserializers)
    541         else:
    542             response = None

~/anaconda3/envs/python3/lib/python3.6/site-packages/distributed/comm/tcp.py in read(self, deserializers)
    220             try:
    221                 msg = await from_frames(
--> 222                     frames, deserialize=self.deserialize, deserializers=deserializers
    223                 )
    224             except EOFError:

~/anaconda3/envs/python3/lib/python3.6/site-packages/distributed/comm/utils.py in from_frames(frames, deserialize, deserializers)
     67         res = await offload(_from_frames)
     68     else:
---> 69         res = _from_frames()
     70 
     71     return res

~/anaconda3/envs/python3/lib/python3.6/site-packages/distributed/comm/utils.py in _from_frames()
     53         try:
     54             return protocol.loads(
---> 55                 frames, deserialize=deserialize, deserializers=deserializers
     56             )
     57         except EOFError:

~/anaconda3/envs/python3/lib/python3.6/site-packages/distributed/protocol/core.py in loads(frames, deserialize, deserializers)
    122                     fs = decompress(head, fs)
    123                 fs = merge_frames(head, fs)
--> 124                 value = _deserialize(head, fs, deserializers=deserializers)
    125             else:
    126                 value = Serialized(head, fs)

~/anaconda3/envs/python3/lib/python3.6/site-packages/distributed/protocol/serialize.py in deserialize(header, frames, deserializers)
    266         )
    267     dumps, loads, wants_context = families[name]
--> 268     return loads(header, frames)
    269 
    270 

~/anaconda3/envs/python3/lib/python3.6/site-packages/distributed/protocol/serialize.py in pickle_loads(header, frames)
     60 
     61 def pickle_loads(header, frames):
---> 62     return pickle.loads(b"".join(frames))
     63 
     64 

~/anaconda3/envs/python3/lib/python3.6/site-packages/distributed/protocol/pickle.py in loads(x)
     57 def loads(x):
     58     try:
---> 59         return pickle.loads(x)
     60     except Exception:
     61         logger.info("Failed to deserialize %s", x[:10000], exc_info=True)

~/anaconda3/envs/python3/lib/python3.6/site-packages/fsspec/spec.py in __call__(cls, *args, **kwargs)
     50             return cls._cache[token]
     51         else:
---> 52             obj = super().__call__(*args, **kwargs)
     53             # Setting _fs_token here causes some static linters to complain.
     54             obj._fs_token_ = token

~/anaconda3/envs/python3/lib/python3.6/site-packages/fsspec/implementations/hdfs.py in __init__(self, host, port, user, kerb_ticket, driver, extra_conf, **kwargs)
     48             kerb_ticket=kerb_ticket,
     49             driver=driver,
---> 50             extra_conf=extra_conf,
     51         )
     52 

~/anaconda3/envs/python3/lib/python3.6/site-packages/pyarrow/hdfs.py in __init__(self, host, port, user, kerb_ticket, driver, extra_conf)
     36                  driver='libhdfs', extra_conf=None):
     37         if driver == 'libhdfs':
---> 38             _maybe_set_hadoop_classpath()
     39 
     40         self._connect(host, port, user, kerb_ticket, driver, extra_conf)

~/anaconda3/envs/python3/lib/python3.6/site-packages/pyarrow/hdfs.py in _maybe_set_hadoop_classpath()
    138             classpath = _hadoop_classpath_glob(hadoop_bin)
    139     else:
--> 140         classpath = _hadoop_classpath_glob('hadoop')
    141 
    142     os.environ['CLASSPATH'] = classpath.decode('utf-8')

~/anaconda3/envs/python3/lib/python3.6/site-packages/pyarrow/hdfs.py in _hadoop_classpath_glob(hadoop_bin)
    163 
    164     hadoop_classpath_args = (hadoop_bin, 'classpath', '--glob')
--> 165     return subprocess.check_output(hadoop_classpath_args)
    166 
    167 

~/anaconda3/envs/python3/lib/python3.6/subprocess.py in check_output(timeout, *popenargs, **kwargs)
    334 
    335     return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
--> 336                **kwargs).stdout
    337 
    338 

~/anaconda3/envs/python3/lib/python3.6/subprocess.py in run(input, timeout, check, *popenargs, **kwargs)
    401         kwargs['stdin'] = PIPE
    402 
--> 403     with Popen(*popenargs, **kwargs) as process:
    404         try:
    405             stdout, stderr = process.communicate(input, timeout=timeout)

~/anaconda3/envs/python3/lib/python3.6/subprocess.py in __init__(self, args, bufsize, executable, stdin, stdout, stderr, preexec_fn, close_fds, shell, cwd, env, universal_newlines, startupinfo, creationflags, restore_signals, start_new_session, pass_fds, encoding, errors)
    707                                 c2pread, c2pwrite,
    708                                 errread, errwrite,
--> 709                                 restore_signals, start_new_session)
    710         except:
    711             # Cleanup if the child failed starting.

~/anaconda3/envs/python3/lib/python3.6/subprocess.py in _execute_child(self, args, executable, preexec_fn, close_fds, pass_fds, cwd, env, startupinfo, creationflags, shell, p2cread, p2cwrite, c2pread, c2pwrite, errread, errwrite, restore_signals, start_new_session)
   1342                         if errno_num == errno.ENOENT:
   1343                             err_msg += ': ' + repr(err_filename)
-> 1344                     raise child_exception_type(errno_num, err_msg, err_filename)
   1345                 raise child_exception_type(err_msg)
   1346 

FileNotFoundError: [Errno 2] No such file or directory: 'hadoop': 'hadoop'
```

**Comment by mrocklin** [comment]
Thank you for including the traceback @bschreck .  We might be able to resolve this upstream in Arrow.  I've raised https://issues.apache.org/jira/browse/ARROW-7486

**Comment by mrocklin** [comment]
> Does the dask dataframe returned by the delayed call have access to all the same methods as a local dask dataframe?

I don't see any reason why they would be different.  There is only one kind of Dask dataframe.

**Comment by bschreck** [comment]
@mrocklin I started an implementation to resolve this upstream in pyarrow but it seems like Dask still uses the file system locally in [`_determine_dataset_parts`](https://github.com/dask/dask/blob/master/dask/dataframe/io/parquet/arrow.py#L93). What do you suggest as the best way around this? Ideally we would only create `pq.ParquetDataset` remotely, or somehow modify ParquetDataset to also be lazy, but that seems out of the scope of pyarrow.

**Comment by mrocklin** [comment]
Pinging @martindurant who has a better sense both for Dask's filesystem handling and the Parquet system.

**Comment by mrocklin** [comment]
@bschreck I don't have an immediate answer for you.  You probably have as much current understanding of this part of the codebase as I do.  Do you have any thoughts on how this can be resolved?

**Comment by bschreck** [comment]
I think the best solution is to try to create the ParquetDataset locally, fail if the file system fails to connect, and in that case make a delayed() call to the scheduler to create ParquetDataset remotely and bring back all the relevant metadata we need

**Comment by mrocklin** [comment]
Sounds good to me.  I think that @jcrist had similar thoughts to this at
one point

**Comment by martindurant** [comment]
Have you considered using webHDFS? That will work well from within or without the cluster, so long as the configuration allows it - and the only extra dependency is `requests`, which you likely already have, and `requests_kerberos` if you need it.

**Comment by bschreck** [comment]
@martindurant thanks for the tip! That looks promising - I wonder if we can use it as a custom filesystem in pyarrow.ParquetDataset

**Comment by martindurant** [comment]
Yes that is exactly the idea.
To be sure, I mean the `fsspec` implementation of webHDFS, which you get automatically by replacing the protocol part of your URL `dd.read_parquet('webhdfs://server:port/filepath/*.parquet', engine='pyarrow', ...). All `fsspec` backed implementations mixin pyarrow's file-system as a superclass, if it is installed, so that pyarrow functions should not notice the difference.

**Comment by bryanwweber** [comment]
@bschreck @martindurant Since it's been 2 years with no further comments, I assume this issue is resolved. Unfortunately I don't have an `hdfs` store to double check. Please feel free to reopen if there's more to be done here! Thanks 😄
