### ISSUE TITLE
Dataframe operations not working on empty dataframes

### ISSUE THREAD

**Issue by exemplary-citizen** [dask/dask#5802]
```
>>> import dask.dataframe as dd
>>> import pandas as pd
>>> pdf = pd.DataFrame()
>>> ddf = dd.from_pandas(pdf, npartitions=1)
>>> pdf.sum()
Series([], dtype: float64)
>>> ddf.sum().compute()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ec2-user/.local/lib/python3.6/site-packages/dask/dataframe/core.py", line 1522, in sum
    "sum", axis=axis, skipna=skipna, split_every=split_every, out=out
  File "/home/ec2-user/.local/lib/python3.6/site-packages/dask/dataframe/core.py", line 1490, in _reduction_agg
    result.divisions = (min(self.columns), max(self.columns))
ValueError: min() arg is an empty sequence
>>> pdf.count()
Series([], dtype: int64)
>>> ddf.count().compute()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ec2-user/.local/lib/python3.6/site-packages/dask/dataframe/core.py", line 1648, in count
    result.divisions = (min(self.columns), max(self.columns))
ValueError: min() arg is an empty sequence
```
Same story for `mean`, `var` and `sem`.
The issue stems from the following line in `dask/dataframe/core.py`:
```
result.divisions = (min(self.columns), max(self.columns))
```

**Comment by jrbourbeau** [comment]
Thanks for reporting @exemplary-citizen! I'm able to reproduce the `ValueError`. Perhaps this can be fixed by adding a check that `self.columns != 0`. Is this something you're interested in looking into? (no obligation though)

**Comment by exemplary-citizen** [comment]
I was going to open a PR in a bit. I was thinking of replacing the above line with ```result.divisions = (self.columns.min(), self.columns.max())```
