### ISSUE TITLE
Error when tokenizing pandas objects if dask[dataframe] not installed

### ISSUE THREAD

**Issue by rwedge** [dask/dask#5853]
I am using code that uses distributed but doesn't rely on dask dataframes.  In the dask 2.10 releases I am encountering an error when dask is tokenizing pandas dataframes.

Example code:
Install dask, distributed, and pandas into a clean environment:
```bash
pip install dask distributed pandas
```
Attempt to tokenize a pandas object:
```python
import pandas as pd
from dask.base import tokenize


df = pd.DataFrame([[0, 1], [1, 0]])
tokenize(df)
```
This raises
```python-traceback
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "~/featuretools/daskenv/lib/python3.6/site-packages/dask/base.py", line 651, in tokenize
    return md5(str(tuple(map(normalize_token, args))).encode()).hexdigest()
  File "~/featuretools/daskenv/lib/python3.6/site-packages/dask/utils.py", line 504, in __call__
    meth = self.dispatch(type(arg))
  File "~/featuretools/daskenv/lib/python3.6/site-packages/dask/utils.py", line 491, in dispatch
    register()
  File "~/featuretools/daskenv/lib/python3.6/site-packages/dask/base.py", line 742, in register_pandas
    from dask.dataframe._compat import PANDAS_GT_0240
  File "~/featuretools/daskenv/lib/python3.6/site-packages/dask/dataframe/__init__.py", line 55, in <module>
    raise ImportError(str(e) + "\n\n" + msg)
ImportError: fsspec is required to use any file-system functionality. Please install using
conda install -c conda-forge 'fsspec>=0.3.3'
or
pip install 'fsspec>=0.3.3'

Dask dataframe requirements are not installed.

Please either conda or pip install as follows:

  conda install dask                     # either conda install
  pip install dask[dataframe] --upgrade  # or pip install
```

**Comment by jrbourbeau** [comment]
Thanks @rwedge for reporting this issue and providing a nice reproducible example! #5855 should fix the `ImportError`

**Comment by rwedge** [comment]
Thanks @jrbourbeau!  I can confirm this change fixed my problem.
