### ISSUE TITLE
WinError 193 when trying to read parquet file from remote HDFS

### ISSUE THREAD

**Issue by Khris777** [dask/dask#5887]
I am trying to read a parquet file from a remote HDFS like this (in my case only a username but no password is needed):

```
import dask.dataframe as dd
path = 'hdfs://username@server:port/path-to-file'
df = dd.read_parquet(path, engine='pyarrow')
```

I'm getting this error:

```
Traceback (most recent call last):

  File "<ipython-input-40-dc6743263ce3>", line 1, in <module>
    df = dd.read_parquet(path, engine='pyarrow')

  File "C:\Users\My.Name\AppData\Local\Continuum\miniconda3\envs\main\lib\site-packages\dask\dataframe\io\parquet\core.py", line 214, in read_parquet
    fs, _, paths = get_fs_token_paths(path, mode="rb", storage_options=storage_options)

  File "C:\Users\My.Name\AppData\Local\Continuum\miniconda3\envs\main\lib\site-packages\fsspec\core.py", line 398, in get_fs_token_paths
    fs = cls(**options)

  File "C:\Users\My.Name\AppData\Local\Continuum\miniconda3\envs\main\lib\site-packages\fsspec\spec.py", line 52, in __call__
    obj = super().__call__(*args, **kwargs)

  File "C:\Users\My.Name\AppData\Local\Continuum\miniconda3\envs\main\lib\site-packages\fsspec\implementations\hdfs.py", line 50, in __init__
    extra_conf=extra_conf,

  File "C:\Users\My.Name\AppData\Local\Continuum\miniconda3\envs\main\lib\site-packages\pyarrow\hdfs.py", line 38, in __init__
    _maybe_set_hadoop_classpath()

  File "C:\Users\My.Name\AppData\Local\Continuum\miniconda3\envs\main\lib\site-packages\pyarrow\hdfs.py", line 138, in _maybe_set_hadoop_classpath
    classpath = _hadoop_classpath_glob(hadoop_bin)

  File "C:\Users\My.Name\AppData\Local\Continuum\miniconda3\envs\main\lib\site-packages\pyarrow\hdfs.py", line 165, in _hadoop_classpath_glob
    return subprocess.check_output(hadoop_classpath_args)

  File "C:\Users\My.Name\AppData\Local\Continuum\miniconda3\envs\main\lib\subprocess.py", line 411, in check_output
    **kwargs).stdout

  File "C:\Users\My.Name\AppData\Local\Continuum\miniconda3\envs\main\lib\subprocess.py", line 488, in run
    with Popen(*popenargs, **kwargs) as process:

  File "C:\Users\My.Name\AppData\Local\Continuum\miniconda3\envs\main\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 104, in __init__
    super(SubprocessPopen, self).__init__(*args, **kwargs)

  File "C:\Users\My.Name\AppData\Local\Continuum\miniconda3\envs\main\lib\subprocess.py", line 800, in __init__
    restore_signals, start_new_session)

  File "C:\Users\My.Name\AppData\Local\Continuum\miniconda3\envs\main\lib\subprocess.py", line 1207, in _execute_child
    startupinfo)

OSError: [WinError 193] %1 is not a valid Win32 application
```

This only happens when trying to read from remote HDFS, local files work fine.

Systeminfo: 

- Windows 10 64bit
- Python 3.7.6
- dask-core 2.10.1
- fastparquet 0.3.3
- pyarrow 0.16.0
- snappy 1.1.8
- pandas 1.0.1

**Comment by mrocklin** [comment]
Hi @Khris777 .  My apologies for the delayed response here.

My guess is that your Windows machine does not have access to HDFS.  Is this possible?  

If so, then you probably need to wait for Arrow to make some changes upstream.  Please see https://issues.apache.org/jira/browse/ARROW-7486

**Comment by Khris777** [comment]
Hi.

I can access HDFS just fine using python [hdfs](https://pypi.org/project/hdfs/) or [pyhive](https://github.com/dropbox/PyHive).

Usually I'm reading the file in binary mode using hdfs and then feed the binary stream to [parquet-python](https://pypi.org/project/parquet/) which reads it without issues.

Parquet-python is not readily available on conda though so I'm looking for an alternative. 

Thanks for linking that Arrow issue, it's probably that.

**Comment by Khris777** [comment]
I just tried fastparquet instead of pyarrow

```
df = dd.read_parquet(path, engine='fastparquet')
```

and it threw the exact same error.

**Comment by mrocklin** [comment]
I'm not sure how else to help on this issue, other than to point you upstream.  Are you good if we close?

**Comment by Khris777** [comment]
Yes, that's okay, go ahead.
