### ISSUE TITLE
dask.dataframe concat function leads to dumped core

### ISSUE THREAD

**Issue by emilaz** [dask/dask#5964]
## What is the problem?
When reading HDFs from file using dask.dataframe and then concatenating them afterwards, a core dump error is thrown **sometimes**. This seems to depend on the content of the hdfs. The exact error is also not consistent, as it is a Bus error at times, a segmentation fault at others and sometimes I get the following error

> double free or corruption (!prev)
> Aborted (core dumped)

. For the minimal working example below, an error is thrown around 6 times in 10 runs. 

## Minimal working example

```
import pandas as pd
import dask.dataframe as dd
bar= []
for i in range(4):
    foo = dd.from_pandas(pd.DataFrame({'number':list(range(i,10000+i)), 'other':list(range(0,10000))}), chunksize=500)
    foo.compute().to_hdf('test_file_'+str(i), '/data', format='table')
    foo = dd.read_hdf('test_file_'+str(i),'/data', chunksize=500)
    bar.append(foo)

full_df = dd.concat(bar, interleave_partitions=True)
print(full_df.compute())
```

If I pre-compute the individual dask dataframes and concatenate using pandas, everything works as expected.

```
bar = [t.compute() for t in bar]
full_df = pd.concat(bar)
print(full_df)
```

**Comment by quasiben** [comment]
It can be challenging to diagnose *sometimes* bugs. I ran you example 20+ times and was not able to reproduce any issue.  I did, however, have to change the `concat` line to:
> full_df = dd.concat(bar, interleave_partitions=True)

(replacing `test` with `bar`)

What versions of dask/pytables/h57 are you using ?

**Comment by emilaz** [comment]
Thanks for mentioning the variable naming error, I edited the original post. So it seems to have to do with the number of dataframes to concatenate. When using 10 iterations, I'm getting the error every time.

Dask version: 2.11.1
Tables version: 3.6.1

Haven't heard of h57. 
`pip freeze | grep h57 `
doesn't return anything.

**Comment by TomAugspurger** [comment]
Ben probably men h5py, but the library that likely matters is pytables and hdf5 itself.

I was able to reproduce with tables=3.6.1 and pandas master. Running with `-X faulthandler`, I see

<details>

```
$ python -X faulthandler bug.py                                                                                                                                                                                                                                                                       
Fatal Python error: Segmentation fault

Thread 0x000070000b41d000 (most recent call first):
  File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/pool.py", line 470 in _handle_results
  File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 870 in run
  File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 926 in _bootstrap_inner
  File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 890 in _bootstrap

Thread 0x000070000af1a000 (most recent call first):
  File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/pool.py", line 422 in _handle_tasks
  File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 870 in run
  File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 926 in _bootstrap_inner
  File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 890 in _bootstrap

Thread 0x000070000aa17000 (most recent call first):
  File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/pool.py", line 413 in _handle_workers
  File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 870 in run
  File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 926 in _bootstrap_inner
  File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 890 in _bootstrap

Thread 0x000070000a514000 (most recent call first):
  File "/Users/taugspurger/sandbox/dask/dask/utils.py", line 971 in acquire
  File "/Users/taugspurger/sandbox/dask/dask/dataframe/io/hdf.py", line 390 in _pd_read_hdf
  File "/Users/taugspurger/sandbox/dask/dask/core.py", line 119 in _execute_task
  File "/Users/taugspurger/sandbox/dask/dask/local.py", line 222 in execute_task
  File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/pool.py", line 121 in worker
  File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 870 in run
  File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 926 in _bootstrap_inner
  File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 890 in _bootstrap

Thread 0x000070000a011000 (most recent call first):
  File "/Users/taugspurger/sandbox/dask/dask/utils.py", line 971 in acquire
  File "/Users/taugspurger/sandbox/dask/dask/dataframe/io/hdf.py", line 390 in _pd_read_hdf
  File "/Users/taugspurger/sandbox/dask/dask/core.py", line 119 in _execute_task
  File "/Users/taugspurger/sandbox/dask/dask/local.py", line 222 in execute_task
  File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/pool.py", line 121 in worker
  File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 870 in run
  File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 926 in _bootstrap_inner
  File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 890 in _bootstrap

Thread 0x0000700009b0e000 (most recent call first):
  File "/Users/taugspurger/sandbox/dask/dask/utils.py", line 971 in acquire
  File "/Users/taugspurger/sandbox/dask/dask/dataframe/io/hdf.py", line 390 in _pd_read_hdf
  File "/Users/taugspurger/sandbox/dask/dask/core.py", line 119 in _execute_task
  File "/Users/taugspurger/sandbox/dask/dask/local.py", line 222 in execute_task
  File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/pool.py", line 121 in worker
  File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 870 in run
  File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 926 in _bootstrap_inner
  File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 890 in _bootstrap

Thread 0x000070000960b000 (most recent call first):
  File "/Users/taugspurger/sandbox/dask/dask/utils.py", line 971 in acquire
  File "/Users/taugspurger/sandbox/dask/dask/dataframe/io/hdf.py", line 390 in _pd_read_hdf
  File "/Users/taugspurger/sandbox/dask/dask/core.py", line 119 in _execute_task
  File "/Users/taugspurger/sandbox/dask/dask/local.py", line 222 in execute_task
  File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/pool.py", line 121 in worker
  File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 870 in run
  File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 926 in _bootstrap_inner
  File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 890 in _bootstrap

Current thread 0x0000700009108000 (most recent call first):
  File "/Users/taugspurger/Envs/pandas-dev/lib/python3.7/site-packages/tables/file.py", line 778 in __init__
  File "/Users/taugspurger/Envs/pandas-dev/lib/python3.7/site-packages/tables/file.py", line 315 in open_file
  File "/Users/taugspurger/sandbox/pandas/pandas/io/pytables.py", line 653 in open
  File "/Users/taugspurger/sandbox/pandas/pandas/io/pytables.py", line 534 in __init__
  File "/Users/taugspurger/sandbox/pandas/pandas/io/pytables.py", line 394 in read_hdf
  File "/Users/taugspurger/sandbox/dask/dask/dataframe/io/hdf.py", line 392 in _pd_read_hdf
  File "/Users/taugspurger/sandbox/dask/dask/core.py", line 119 in _execute_task
  File "/Users/taugspurger/sandbox/dask/dask/local.py", line 222 in execute_task
  File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/pool.py", line 121 in worker
  File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 870 in run
  File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 926 in _bootstrap_inner
  File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 890 in _bootstrap

Thread 0x0000700008c05000 (most recent call first):
  File "/Users/taugspurger/sandbox/dask/dask/utils.py", line 971 in acquire
  File "/Users/taugspurger/sandbox/dask/dask/dataframe/io/hdf.py", line 390 in _pd_read_hdf
  File "/Users/taugspurger/sandbox/dask/dask/core.py", line 119 in _execute_task
  File "/Users/taugspurger/sandbox/dask/dask/local.py", line 222 in execute_task
  File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/pool.py", line 121 in worker
  File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 870 in run
  File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 926 in _bootstrap_inner
  File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 890 in _bootstrap

Thread 0x0000700008702000 (most recent call first):
  File "/Users/taugspurger/sandbox/dask/dask/utils.py", line 971 in acquire
  File "/Users/taugspurger/sandbox/dask/dask/dataframe/io/hdf.py", line 390 in _pd_read_hdf
  File "/Users/taugspurger/sandbox/dask/dask/core.py", line 119 in _execute_task
  File "/Users/taugspurger/sandbox/dask/dask/local.py", line 222 in execute_task
  File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/pool.py", line 121 in worker
  File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 870 in run
  File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 926 in _bootstrap_inner
  File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 890 in _bootstrap

Thread 0x00007000081ff000 (most recent call first):
  File "/Users/taugspurger/Envs/pandas-dev/lib/python3.7/site-packages/tables/array.py", line 762 in _read_slice
  File "/Users/taugspurger/Envs/pandas-dev/lib/python3.7/site-packages/tables/array.py", line 658 in __getitem__
  File "/Users/taugspurger/Envs/pandas-dev/lib/python3.7/site-packages/tables/index.py", line 449 in _g_post_init_hook
  File "/Users/taugspurger/Envs/pandas-dev/lib/python3.7/site-packages/tables/node.py", line 273 in __init__
  File "/Users/taugspurger/Envs/pandas-dev/lib/python3.7/site-packages/tables/group.py", line 235 in __init__
  File "/Users/taugspurger/Envs/pandas-dev/lib/python3.7/site-packages/tables/index.py", line 395 in __init__
  File "/Users/taugspurger/Envs/pandas-dev/lib/python3.7/site-packages/tables/group.py", line 1192 in _g_load_child
  File "/Users/taugspurger/Envs/pandas-dev/lib/python3.7/site-packages/tables/file.py", line 432 in get_node
  File "/Users/taugspurger/Envs/pandas-dev/lib/python3.7/site-packages/tables/file.py", line 1590 in _get_node
  File "/Users/taugspurger/Envs/pandas-dev/lib/python3.7/site-packages/tables/file.py", line 1642 in get_node
  File "/Users/taugspurger/Envs/pandas-dev/lib/python3.7/site-packages/tables/file.py", line 2049 in __contains__
  File "/Users/taugspurger/Envs/pandas-dev/lib/python3.7/site-packages/tables/table.py", line 872 in _g_post_init_hook
  File "/Users/taugspurger/Envs/pandas-dev/lib/python3.7/site-packages/tables/node.py", line 273 in __init__
  File "/Users/taugspurger/Envs/pandas-dev/lib/python3.7/site-packages/tables/leaf.py", line 286 in __init__
  File "/Users/taugspurger/Envs/pandas-dev/lib/python3.7/site-packages/tables/table.py", line 836 in __init__
  File "/Users/taugspurger/Envs/pandas-dev/lib/python3.7/site-packages/tables/group.py", line 1199 in _g_load_child
  File "/Users/taugspurger/Envs/pandas-dev/lib/python3.7/site-packages/tables/file.py", line 432 in get_node
  File "/Users/taugspurger/Envs/pandas-dev/lib/python3.7/site-packages/tables/file.py", line 1590 in _get_node
  File "/Users/taugspurger/Envs/pandas-dev/lib/python3.7/site-packages/tables/group.py", line 711 in _f_get_child
  File "/Users/taugspurger/Envs/pandas-dev/lib/python3.7/site-packages/tables/group.py", line 836 in __getattr__
  File "/Users/taugspurger/sandbox/pandas/pandas/io/pytables.py", line 3253 in storable
  File "/Users/taugspurger/sandbox/pandas/pandas/io/pytables.py", line 2599 in infer_axes
  File "/Users/taugspurger/sandbox/pandas/pandas/io/pytables.py", line 792 in select
  File "/Users/taugspurger/sandbox/pandas/pandas/io/pytables.py", line 425 in read_hdf
  File "/Users/taugspurger/sandbox/dask/dask/dataframe/io/hdf.py", line 392 in _pd_read_hdf
  File "/Users/taugspurger/sandbox/dask/dask/core.py", line 119 in _execute_task
  File "/Users/taugspurger/sandbox/dask/dask/local.py", line 222 in execute_task
  File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/pool.py", line 121 in worker
  File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 870 in run
  File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 926 in _bootstrap_inner
  File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 890 in _bootstrap

Thread 0x000000011609e5c0 (most recent call first):
  File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 296 in wait
  File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/queue.py", line 170 in get
  File "/Users/taugspurger/sandbox/dask/dask/local.py", line 133 in queue_get
  File "/Users/taugspurger/sandbox/dask/dask/local.py", line 475 in get_async
  File "/Users/taugspurger/sandbox/dask/dask/threaded.py", line 84 in get
  File "/Users/taugspurger/sandbox/dask/dask/base.py", line 437 in compute
  File "/Users/taugspurger/sandbox/dask/dask/base.py", line 166 in compute
  File "bug.py", line 11 in <module>
'python -X faulthandler bug.py' terminated by signal SIGSEGV (Address boundary error)
```

</details>

I don't know if any of that is helpful though.

**Comment by quasiben** [comment]
yup yup, h5py, thanks Tom.  In my env I am still running pandas=0.25.1.

**Comment by emilaz** [comment]
hdf5=1.10.2
h5py is not installed in my environment.
I had the same bug using dask 2.9.1.

**Comment by TomAugspurger** [comment]
FWIW, these changes seem to avoid the segfault in my environment,

```python
import threading
lock = threading.Lock()

    foo = dd.read_hdf('test_file_'+str(i),'/data', chunksize=500, lock=lock)
```

So the full script is

```python
import pandas as pd
import dask.dataframe as dd
from threading import Lock


lock = Lock()

test= []
for i in range(4):
    foo = dd.from_pandas(pd.DataFrame({'number':list(range(i,10000+i)), 'other':list(range(0,10000))}), chunksize=500)
    foo.compute().to_hdf('test_file_'+str(i), '/data', format='table')
    foo = dd.read_hdf('test_file_'+str(i),'/data', chunksize=500, lock=lock)
    test.append(foo)

full_df = dd.concat(test, interleave_partitions=True)
print(full_df.compute())
```

**Comment by emilaz** [comment]
Thanks for the suggestion. Unfortunately this workaround doesn't help me, since I'm reading in several hdfs using multiprocessing, which doesn't work with thread locking. I end up with the following error:
```
TypeError: can't pickle _thread.lock objects
```

I might just downgrade pandas to get this to work.

**Comment by mrocklin** [comment]
In general I think that the problem here is that the underlying HDF5
library isn't threadsafe.  Dask itself isn't going to be able to resolve
this unfortunately.  We can provide a mechanism for you to provide a Lock
that makes sense for your situation.  In this case, probably the right Lock
type is dask.distributed.SerializableLock, which I think will work in your
multiprocessing situation.

If the thread-safety of the hdf5 library (or h5py or pytables) has changed
recently then we probably want to report this upstream.

We might also consider locking by default, although this has other
implications.

**Comment by TomAugspurger** [comment]
@emilaz are you interested in exploring this further (it's `dask.utils.SerializableLock` that you would want).

**Comment by mrocklin** [comment]
(ah!  thanks for the correction on import location)

**Comment by TomAugspurger** [comment]
One more thing, we do lock by default on `read_hdf`. However, it's a lock per task, and in this case we have multiple read_hdf's, each with its own lock. In this case, it's mostly likely up to the user (or ideally HDF5 itself) to manage locking in this situation.

**Comment by mrocklin** [comment]
Oh interesting.  SerializableLocks take a name for deduplication, and so in
principle we would want to do something like
SerializableLock("dd.read_hdf") in all cases.  Passing names down might be
a little unclean, but that would probably solve things.

**Comment by TomAugspurger** [comment]
Good to know. I'm not sure if we're getting closer or further to a solution with that :)

```pytb                                            
Traceback (most recent call last):
  File "bug.py", line 16, in <module>
    print(full_df.compute(scheduler='processes'))
  File "/Users/taugspurger/sandbox/dask/dask/base.py", line 166, in compute
    (result,) = compute(self, traverse=False, **kwargs)
  File "/Users/taugspurger/sandbox/dask/dask/base.py", line 437, in compute
    results = schedule(dsk, keys, **kwargs)
  File "/Users/taugspurger/sandbox/dask/dask/multiprocessing.py", line 222, in get
    **kwargs
  File "/Users/taugspurger/sandbox/dask/dask/local.py", line 486, in get_async
    raise_exception(exc, tb)
  File "/Users/taugspurger/sandbox/dask/dask/local.py", line 315, in reraise
    raise exc.with_traceback(tb)
  File "/Users/taugspurger/sandbox/dask/dask/local.py", line 222, in execute_task
    result = _execute_task(task, data)
  File "/Users/taugspurger/sandbox/dask/dask/core.py", line 119, in _execute_task
    return func(*args2)
  File "/Users/taugspurger/sandbox/dask/dask/dataframe/io/hdf.py", line 392, in _pd_read_hdf
    result = pd.read_hdf(path, key, **kwargs)
  File "/Users/taugspurger/Envs/dask-dev/lib/python3.7/site-packages/pandas/io/pytables.py", line 397, in read_hdf
    store = HDFStore(path_or_buf, mode=mode, errors=errors, **kwargs)
  File "/Users/taugspurger/Envs/dask-dev/lib/python3.7/site-packages/pandas/io/pytables.py", line 537, in __init__
    self.open(mode=mode, **kwargs)
  File "/Users/taugspurger/Envs/dask-dev/lib/python3.7/site-packages/pandas/io/pytables.py", line 655, in open
    self._handle = tables.open_file(self._path, self._mode, **kwargs)
  File "/Users/taugspurger/Envs/dask-dev/lib/python3.7/site-packages/tables/file.py", line 315, in open_file
    return File(filename, mode, title, root_uep, filters, **kwargs)
  File "/Users/taugspurger/Envs/dask-dev/lib/python3.7/site-packages/tables/file.py", line 778, in __init__
    self._g_new(filename, mode, **params)
  File "tables/hdf5extension.pyx", line 492, in tables.hdf5extension.File._g_new
tables.exceptions.HDF5ExtError: HDF5 error back trace

  File "H5F.c", line 509, in H5Fopen
    unable to open file
  File "H5Fint.c", line 1567, in H5F_open
    unable to lock the file
  File "H5FD.c", line 1640, in H5FD_lock
    driver lock request failed
  File "H5FDsec2.c", line 959, in H5FD_sec2_lock
    unable to lock file, errno = 35, error message = 'Resource temporarily unavailable'

End of HDF5 error back trace

Unable to open/create file 'test_file_0'
```

using the following (added a named lock and `scheduler='processes'`).

<details>
```python

import pandas as pd
import dask.dataframe as dd
from dask.utils import SerializableLock

if __name__ == "__main__":
    lock = SerializableLock("hdf")

    test= []
    for i in range(4):
        foo = dd.from_pandas(pd.DataFrame({'number':list(range(i,10000+i)), 'other':list(range(0,10000))}), chunksize=500)
        foo.compute().to_hdf('test_file_'+str(i), '/data', format='table')
        foo = dd.read_hdf('test_file_'+str(i),'/data', chunksize=500, lock=lock)
        test.append(foo)

    full_df = dd.concat(test, interleave_partitions=True)
    print(full_df.compute(scheduler='processes'))
```

</details>

**Comment by TomAugspurger** [comment]
Ah, from the SerializableLock docstring

```
However, this lock can also be serialized and sent to different
    processes.  It will not block concurrent operations between processes (for
    this you should look at ``multiprocessing.Lock`` or ``locket.lock_file``
    but will consistently deserialize into the same lock.
```

Using a simple `locket = locket.lock_file("hdf5.lock")` doesn't quite work. I think the lock for the lock file ends up in the task graph. Could probably do a bit of hacking to get this working @emilaz if you're interested. I won't be able to look any further though.

**Comment by martindurant** [comment]
Closing as stale. The issue may be in HDF, and there a re a couple of suggestions of things to try as workarounds... Please reopen if you are still facing this issue.
