### ISSUE TITLE
AssertionError: Impossible to call blocking function in the event loop callback while handling Dask dataframes

### ISSUE THREAD

**Issue by vipinanandcpp** [dask/dask#597]
I recently started playing with Dask and have been trying to work with larger json.gz files. I am trying to load a gzipped json file which is about 700mbs and am using 

`json_ = dask.bag.from_filenames(filename).map(json.loads)`
When I try to use this function `json_.to_dataframes()`, I get the following exception:
`IOError: [Errno 35] Resource temporarily unavailable`
along with this exception

`AssertionError: Impossible to call blocking function in the event loop callback`
When I looked into the stack trace, I found this function call to be creating this issue 
`message = connection.recv_bytes(256)         # reject large message`

Here is the complete trace of the IOError.
```python
###################################################

IOError                                   Traceback (most recent call last)
<ipython-input-9-57f89723128b> in <module>()
----> 1 json_.take(2)

/opt/anaconda/lib/python2.7/site-packages/dask/bag/core.pyc in take(self, k, compute)
    687         b = Bag(merge(self.dask, dsk), name, 1)
    688         if compute:
--> 689             return tuple(b.compute())
    690         else:
    691             return b

/opt/anaconda/lib/python2.7/site-packages/dask/base.pyc in compute(self, **kwargs)
     31 
     32     def compute(self, **kwargs):
---> 33         return compute(self, **kwargs)[0]
     34 
     35     @classmethod

/opt/anaconda/lib/python2.7/site-packages/dask/base.pyc in compute(*args, **kwargs)
     65                 for opt, val in groups.items()])
     66     keys = [arg._keys() for arg in args]
---> 67     results = get(dsk, keys, **kwargs)
     68     return tuple(a._finalize(a, r) for a, r in zip(args, results))
     69 

/opt/anaconda/lib/python2.7/site-packages/dask/multiprocessing.pyc in get(dsk, keys, optimizations, num_workers, func_loads, func_dumps, **kwargs)
     42 
     43     manager = multiprocessing.Manager()
---> 44     queue = manager.Queue()
     45 
     46     apply_async = dill_apply_async(pool.apply_async,

/opt/anaconda/python.app/Contents/lib/python2.7/multiprocessing/managers.pyc in temp(self, *args, **kwds)
    665             def temp(self, *args, **kwds):
    666                 util.debug('requesting creation of a shared %r object', typeid)
--> 667                 token, exp = self._create(typeid, *args, **kwds)
    668                 proxy = proxytype(
    669                     token, self._serializer, manager=self,

/opt/anaconda/python.app/Contents/lib/python2.7/multiprocessing/managers.pyc in _create(self, typeid, *args, **kwds)
    563         
    564         assert self._state.value == State.STARTED, 'server not yet started'
--> 565         conn = self._Client(self._address, authkey=self._authkey)
    566         try:
    567             id, exposed = dispatch(conn, None, 'create', (typeid,)+args, kwds)

/opt/anaconda/python.app/Contents/lib/python2.7/multiprocessing/connection.pyc in Client(address, family, authkey)
    173 
    174     if authkey is not None:
--> 175         answer_challenge(c, authkey)
    176         deliver_challenge(c, authkey)
    177 

/opt/anaconda/python.app/Contents/lib/python2.7/multiprocessing/connection.pyc in answer_challenge(connection, authkey)
    430     import hmac
    431     assert isinstance(authkey, bytes)
--> 432     message = connection.recv_bytes(256)         # reject large message
    433     assert message[:len(CHALLENGE)] == CHALLENGE, 'message = %r' % message
    434     message = message[len(CHALLENGE):]

IOError: [Errno 35] Resource temporarily unavailable


##########################################################
```

The following is the trace for the assertion error:

```python
########################################################


Traceback (most recent call last):
  File "/Users/vipinanand/metricle/src/data_processing_pipeline/write_file.py", line 28, in signal_handler
    time.sleep(5)	#here check if process is done
  File "/opt/anaconda/lib/python2.7/site-packages/gevent/hub.py", line 82, in sleep
    hub.wait(loop.timer(seconds, ref=ref))
  File "/opt/anaconda/lib/python2.7/site-packages/gevent/hub.py", line 348, in wait
    result = waiter.get()
  File "/opt/anaconda/lib/python2.7/site-packages/gevent/hub.py", line 575, in get
    return self.hub.switch()
  File "/opt/anaconda/lib/python2.7/site-packages/gevent/hub.py", line 337, in switch
    switch_out()
  File "/opt/anaconda/lib/python2.7/site-packages/gevent/hub.py", line 341, in switch_out
    raise AssertionError('Impossible to call blocking function in the event loop callback')
AssertionError: Impossible to call blocking function in the event loop callback
Process SyncManager-5:
Traceback (most recent call last):
  File "/opt/anaconda/python.app/Contents/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/opt/anaconda/python.app/Contents/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/anaconda/python.app/Contents/lib/python2.7/multiprocessing/managers.py", line 558, in _run_server
    server.serve_forever()
  File "/opt/anaconda/python.app/Contents/lib/python2.7/multiprocessing/managers.py", line 179, in serve_forever
    c = self.listener.accept()
  File "/opt/anaconda/python.app/Contents/lib/python2.7/multiprocessing/connection.py", line 145, in accept
    c = self._listener.accept()
  File "/opt/anaconda/python.app/Contents/lib/python2.7/multiprocessing/connection.py", line 275, in accept
    s, self._last_accepted = self._socket.accept()
  File "/opt/anaconda/lib/python2.7/site-packages/gevent/socket.py", line 316, in accept
    self._wait(self._read_event)
  File "/opt/anaconda/lib/python2.7/site-packages/gevent/socket.py", line 300, in _wait
    self.hub.wait(watcher)
  File "/opt/anaconda/lib/python2.7/site-packages/gevent/hub.py", line 348, in wait
    result = waiter.get()
  File "/opt/anaconda/lib/python2.7/site-packages/gevent/hub.py", line 575, in get
    return self.hub.switch()
  File "/opt/anaconda/lib/python2.7/site-packages/gevent/hub.py", line 338, in switch
    return greenlet.switch(self)
AssertionError: Impossible to call blocking function in the event loop callback


########################################################
```

I have looked around on internet and could not find any valuable solution to this problem.
Could any one please guide me how to handle this issue?

Thanks and Regards,
Vipin Anand

**Comment by mrocklin** [comment]
It's odd that there are `gevent` errors happening here.  Apparently this is a [known issue](http://stackoverflow.com/questions/8678307/gevent-monkeypatching-breaking-multiprocessing).  

Can you try this without importing `gevent` and see if the problem persists?

**Comment by vipinanandcpp** [comment]
Hi Matthew,
Thank you for getting back to me. I am not explicitly importing gevent in my code. I am testing Dask so started playing with dask.bag to load a big json.gz and just called these two lines

json_ = db.from_filenames(user_data_filename).map(json.loads)
json_.take(2)

**Comment by cowlicks** [comment]
Hello @vipinanandcpp, when you do `json_.to_dataframes()` the entire uncompressed dataset is being loaded into memory. Which could be significantly larger than 700MB, maybe even larger than RAM.

I think this is might be a not-enough-memory thing. Another hint this is the case is that the err'ing line has the comment `# reject large message`. 

Could you try with a subset of the data?

**Comment by mrocklin** [comment]
It's not clear that this is a dask issue.  Requests for further information haven't seen response.  Closing.  Please reopen if more information becomes available.
