### ISSUE TITLE
Issue while reading a parquet file with different data types like decimal using Dask read parquet

### ISSUE THREAD

**Issue by aruns5640** [dask/dask#6012]
I have some parquet files which are created by Spark converting AVRO file to parquet file. And these parquet files contain different data types like decimal, int,string. But when I read this file using the dd.read_parquet with pyarrow engine, except int everything else is converted to object data types and which causes an issue in arithmetic calculations. And i tried with the float dtypes for the decimal columns (which is having, upto 10 decimal places) but that will loose precision.
one thing I noticed when I read the same file with pandas dataframe it worked perfectly means the decimal columns are consider as object but still can do the arithmetic operations, but when it comes to Dask dataframe, the same decimal object is consider as string and getting the error like TypeError("can't multiply sequence by non-int of type 'str'"). is this feature is not available in dask dataframe?
Dask version: '2.3.0'
Pandas version: '0.25.0'

**Comment by mrocklin** [comment]
Thank you for raising an issue @aruns5640 .

First, can I ask you to try with a newer version of Dask and PyArrow?  2.3.0 is relatively old.  

Second, if things still don't work, can you try to load the data with just PyArrow, and verify that it supports these types?  If not, then you might want to raise an issue with that project.  

Third, if things don't work, but Arrow does support these types, then can I ask you to try to produce a minimal reproducible example?  This is probably the first step to solving things within Dask if that is what has to happen.

**Comment by aruns5640** [comment]
Thanks for the reply.. will try with the updated version of dask and pyarrow..so just to clarify regarding the decimal dtypes.. In dask dataframe, is it possible to read and do the calculations of decimal columns without losing the precision ?

**Comment by TomAugspurger** [comment]
> but when it comes to Dask dataframe, the same decimal object is consider as string and getting the error

A minimal example would be great here. See http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports. I'm guessing you can separate this issue from parquet IO.

Right now, Decimals will be stored as object dtype, which Dask assumes are strings. So things like `+` won't work, but you might be able to do `df.map_partitions(operator.add, other, meta=...)`. The proper fix is for pandas to have a dedicated Decimal dtype, but that's likely some way off.

**Comment by mrocklin** [comment]
If only there was some way to register new data types for Pandas ... :)

**Comment by aruns5640** [comment]
Thanks Guys for the feedback, please find the sample code and the parquet file below.

`import dask as dask
import dask.dataframe as dd

test=dd.read_parquet("testDataMapping.parquet",engine="pyarrow")
#this gives the correct results
test["DECIMAL_20_2+20_10"]=test["DECIMAL_20_2"]+test["DECIMAL_20_10"]
test["DECIMAL_20_2+20_10_mul_int"]=test["DECIMAL_20_2+20_10"]*2
#for a demo below show some string number,and the results are not populated the actual result(what am trying to say is,
#for the above operations str object works like number not like str)
test['A']='250'
test['B']='100'
test['C']=test['A']*2
test['D']=test['A']+test['B']
#the below operations decimal columns are consider as str object and getting the TypeError: error message
test["DECIMAL_20_2+20_10_add_int"]=test["DECIMAL_20_2+20_10"]+200
test["DECIMAL_20_2+20_10_div_int"]=test["DECIMAL_20_2+20_10"]/2
test["DECIMAL_20_2+20_10_mul_float"]=test["DECIMAL_20_2+20_10"]*2.02

print(test.dtypes)
print(test.head())`
[testDataMapping.parquet.zip](https://github.com/dask/dask/files/4339577/testDataMapping.parquet.zip)

**Comment by TomAugspurger** [comment]
Do you need to use parquet to reproduce the example? Or can you create an in-memory pandas DataFrame with Decimal objects as values?

**Comment by aruns5640** [comment]
@TomAugspurger , you can use the below in memory pandas DataFrame, thanks for the quick reply

test=pd.DataFrame({"DECIMAL_20_2":[999999999999999999.99,-123456789123456789.12], "DECIMAL_20_10":[9999999999.9999999999,-1234567890.0123456789]})
test["DECIMAL_20_2"]=test["DECIMAL_20_2"].astype(str).map(decimal.Decimal)
test["DECIMAL_20_10"]=test["DECIMAL_20_10"].astype(str).map(decimal.Decimal)

test=dd.from_pandas(test,1)

**Comment by TomAugspurger** [comment]
Thanks. Here's the tracback:

```pytb
In [20]: test.DECIMAL_20_2 + 10
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
~/Envs/dask-dev/lib/python3.7/site-packages/pandas/core/ops/array_ops.py in na_arithmetic_op(left, right, op, str_rep)
    148     try:
--> 149         result = expressions.evaluate(op, str_rep, left, right)
    150     except TypeError:

~/Envs/dask-dev/lib/python3.7/site-packages/pandas/core/computation/expressions.py in evaluate(op, op_str, a, b, use_numexpr)
    207     if use_numexpr:
--> 208         return _evaluate(op, op_str, a, b)
    209     return _evaluate_standard(op, op_str, a, b)

~/Envs/dask-dev/lib/python3.7/site-packages/pandas/core/computation/expressions.py in _evaluate_standard(op, op_str, a, b)
     69     with np.errstate(all="ignore"):
---> 70         return op(a, b)
     71

TypeError: can only concatenate str (not "int") to str

During handling of the above exception, another exception occurred:

TypeError                                 Traceback (most recent call last)
~/Envs/dask-dev/lib/python3.7/site-packages/dask/dataframe/utils.py in raise_on_meta_error(funcname, udf)
    171     try:
--> 172         yield
    173     except Exception as e:

~/Envs/dask-dev/lib/python3.7/site-packages/dask/dataframe/core.py in elemwise(op, *args, **kwargs)
   4602         with raise_on_meta_error(funcname(op)):
-> 4603             meta = partial_by_order(*parts, function=op, other=other)
   4604

~/Envs/dask-dev/lib/python3.7/site-packages/dask/utils.py in partial_by_order(*args, **kwargs)
   1075         args2.insert(i, arg)
-> 1076     return function(*args2, **kwargs)
   1077

~/Envs/dask-dev/lib/python3.7/site-packages/pandas/core/ops/common.py in new_method(self, other)
     63
---> 64         return method(self, other)
     65

~/Envs/dask-dev/lib/python3.7/site-packages/pandas/core/ops/__init__.py in wrapper(left, right)
    499         rvalues = extract_array(right, extract_numpy=True)
--> 500         result = arithmetic_op(lvalues, rvalues, op, str_rep)
    501

~/Envs/dask-dev/lib/python3.7/site-packages/pandas/core/ops/array_ops.py in arithmetic_op(left, right, op, str_rep)
    196         with np.errstate(all="ignore"):
--> 197             res_values = na_arithmetic_op(lvalues, rvalues, op, str_rep)
    198

~/Envs/dask-dev/lib/python3.7/site-packages/pandas/core/ops/array_ops.py in na_arithmetic_op(left, right, op, str_rep)
    150     except TypeError:
--> 151         result = masked_arith_op(left, right, op)
    152

~/Envs/dask-dev/lib/python3.7/site-packages/pandas/core/ops/array_ops.py in masked_arith_op(x, y, op)
    111             with np.errstate(all="ignore"):
--> 112                 result[mask] = op(xrav[mask], y)
    113

TypeError: can only concatenate str (not "int") to str

During handling of the above exception, another exception occurred:

ValueError                                Traceback (most recent call last)
<ipython-input-20-2d276ccfebe8> in <module>
----> 1 test.DECIMAL_20_2 + 10

~/Envs/dask-dev/lib/python3.7/site-packages/dask/dataframe/core.py in <lambda>(self, other)
   1382             return lambda self, other: elemwise(op, other, self)
   1383         else:
-> 1384             return lambda self, other: elemwise(op, self, other)
   1385
   1386     def rolling(self, window, min_periods=None, center=False, win_type=None, axis=0):

~/Envs/dask-dev/lib/python3.7/site-packages/dask/dataframe/core.py in elemwise(op, *args, **kwargs)
   4601         ]
   4602         with raise_on_meta_error(funcname(op)):
-> 4603             meta = partial_by_order(*parts, function=op, other=other)
   4604
   4605     result = new_dd_object(graph, _name, meta, divisions)

/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/contextlib.py in __exit__(self, type, value, traceback)
    128                 value = type()
    129             try:
--> 130                 self.gen.throw(type, value, traceback)
    131             except StopIteration as exc:
    132                 # Suppress StopIteration *unless* it's the same exception that

~/Envs/dask-dev/lib/python3.7/site-packages/dask/dataframe/utils.py in raise_on_meta_error(funcname, udf)
    191         )
    192         msg = msg.format(" in `{0}`".format(funcname) if funcname else "", repr(e), tb)
--> 193         raise ValueError(msg)
    194
    195

ValueError: Metadata inference failed in `add`.

Original error is below:
------------------------
TypeError('can only concatenate str (not "int") to str')

Traceback:
---------
  File "/Users/taugspurger/Envs/dask-dev/lib/python3.7/site-packages/dask/dataframe/utils.py", line 172, in raise_on_meta_error
    yield
  File "/Users/taugspurger/Envs/dask-dev/lib/python3.7/site-packages/dask/dataframe/core.py", line 4603, in elemwise
    meta = partial_by_order(*parts, function=op, other=other)
  File "/Users/taugspurger/Envs/dask-dev/lib/python3.7/site-packages/dask/utils.py", line 1076, in partial_by_order
    return function(*args2, **kwargs)
  File "/Users/taugspurger/Envs/dask-dev/lib/python3.7/site-packages/pandas/core/ops/common.py", line 64, in new_method
    return method(self, other)
  File "/Users/taugspurger/Envs/dask-dev/lib/python3.7/site-packages/pandas/core/ops/__init__.py", line 500, in wrapper
    result = arithmetic_op(lvalues, rvalues, op, str_rep)
  File "/Users/taugspurger/Envs/dask-dev/lib/python3.7/site-packages/pandas/core/ops/array_ops.py", line 197, in arithmetic_op
    res_values = na_arithmetic_op(lvalues, rvalues, op, str_rep)
  File "/Users/taugspurger/Envs/dask-dev/lib/python3.7/site-packages/pandas/core/ops/array_ops.py", line 151, in na_arithmetic_op
    result = masked_arith_op(left, right, op)
  File "/Users/taugspurger/Envs/dask-dev/lib/python3.7/site-packages/pandas/core/ops/array_ops.py", line 112, in masked_arith_op
    result[mask] = op(xrav[mask], y)
```

So as I said, the proper fix is for pandas to have a dedicated decimal dtype. You might explore what fletcher has here: https://github.com/xhochy/fletcher

Short of that, all Dask can do is avoiding executing code to determine the output metadata. I think that in the case of object-dtype, it's safest to assume that `Series[object] + scalar` is object dtype. That's no worse than what we have today.

@aruns5640 are you interested in working on this? The issue is probably somewhere areound https://github.com/dask/dask/blob/278ad0a46a414c1309d0b4a882fe9eb3fd20e41d/dask/dataframe/core.py#L2986-L2989.

**Comment by aruns5640** [comment]
Thanks @TomAugspurger for the reply, i will definetly look into the issue, but not sure i can able to make fix on it ;). 
I am just wonder, how the same code works in pandas dataframe ?

**Comment by TomAugspurger** [comment]
See the dask DataFrame docs on metadata and inference.

**Comment by mrocklin** [comment]
So I think that this issue comes down to having Pandas support a decimal dtype.  I'm not sure that there is anything that we can do in Dask dataframe until that is done.  I also think that once that is done we should probably get it for free (mostly).  With that in mind I'm going to close this issue.

**Comment by TomAugspurger** [comment]
@mrocklin there's a potential general issue here, where we're assuming that object dtype implies strings, which isn't always the case. It's possible that this fixes it

```diff
diff --git a/dask/dataframe/core.py b/dask/dataframe/core.py
index 030f67136..bfa382b87 100644
--- a/dask/dataframe/core.py
+++ b/dask/dataframe/core.py
@@ -1388,7 +1388,7 @@ Dask Name: {name}, {task} tasks"""
         if inv:
             return lambda self, other: elemwise(op, other, self)
         else:
-            return lambda self, other: elemwise(op, self, other)
+            return lambda self, other: elemwise(op, self, other, meta=op(self._meta, _extract_meta(other)))
 
     def rolling(self, window, min_periods=None, center=False, win_type=None, axis=0):
         """Provides rolling transformations.
```

That fixes this case

```python
In [2]: df = pd.DataFrame({"A": [1, 2]}, dtype=object)

In [3]: ddf = dd.from_pandas(df, 2)

In [4]: (ddf * ddf).compute()
Out[4]:
   A
0  1
1  4
```

but I'm not sure if it breaks anything else. If anyone is interested / able to write tests for that it'd be welcome.

**Comment by aruns5640** [comment]
@TomAugspurger thanks for it.. Just one clarification,  as you mentioned above objects dtypes consider as string, then how the below calculations did it in the right way
test["DECIMAL_20_2+20_10"]=test["DECIMAL_20_2"]+test["DECIMAL_20_10"]
test["DECIMAL_20_2+20_10_mul_int"]=test["DECIMAL_20_2+20_10"]*2??

**Comment by TomAugspurger** [comment]
You can add strings to eachother, and multiply strings by integers :)

It's only the `string * string` that caused issues.

**Comment by aruns5640** [comment]
But adding and multiplying strings behaves differently right,  (I mentioned  that in my  example), here we get exact value as adding 2 number and same as for multiplying

**Comment by TomAugspurger** [comment]
This is on the `DataFrame._meta` or `DataFrame._meta_nonempty` object. For object dtype `_meta_nonempty` will be a Series of `_strings`

```python
In [10]: df = pd.DataFrame({"A": [1, 2]}, dtype=object)

In [11]: ddf = dd.from_pandas(df, 2)

In [12]: ddf._meta_nonempty
Out[12]:
     A
0  foo
1  foo

In [13]: ddf._meta_nonempty + 10
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
~/sandbox/pandas/pandas/core/ops/array_ops.py in na_arithmetic_op(left, right, op, str_rep, is_cmp)
    166     try:
--> 167         result = expressions.evaluate(op, str_rep, left, right)
    168     except TypeError:

~/sandbox/pandas/pandas/core/computation/expressions.py in evaluate(op, op_str, a, b, use_numexpr)
    196     if use_numexpr:
--> 197         return _evaluate(op, op_str, a, b)
    198     return _evaluate_standard(op, op_str, a, b)

~/sandbox/pandas/pandas/core/computation/expressions.py in _evaluate_standard(op, op_str, a, b)
     66     with np.errstate(all="ignore"):
---> 67         return op(a, b)
     68

TypeError: can only concatenate str (not "int") to str

During handling of the above exception, another exception occurred:

TypeError                                 Traceback (most recent call last)
<ipython-input-13-5451c88a9e71> in <module>
----> 1 ddf._meta_nonempty + 10

~/sandbox/pandas/pandas/core/ops/__init__.py in f(self, other, axis, level, fill_value)
    817                 self = self.fillna(fill_value)
    818
--> 819             new_data = dispatch_to_series(self, other, op, str_rep)
    820             return self._construct_result(new_data)
    821

~/sandbox/pandas/pandas/core/ops/__init__.py in dispatch_to_series(left, right, func, str_rep, axis)
    380         # Get the appropriate array-op to apply to each block's values.
    381         array_op = get_array_op(func, str_rep=str_rep)
--> 382         bm = left._data.apply(array_op, right=right)
    383         return type(left)(bm)
    384

~/sandbox/pandas/pandas/core/internals/managers.py in apply(self, f, filter, **kwargs)
    443
    444             if callable(f):
--> 445                 applied = b.apply(f, **kwargs)
    446             else:
    447                 applied = getattr(b, f)(**kwargs)

~/sandbox/pandas/pandas/core/internals/blocks.py in apply(self, func, **kwargs)
    362         """
    363         with np.errstate(all="ignore"):
--> 364             result = func(self.values, **kwargs)
    365
    366         return self._split_op_result(result)

~/sandbox/pandas/pandas/core/ops/array_ops.py in arithmetic_op(left, right, op, str_rep)
    220     else:
    221         with np.errstate(all="ignore"):
--> 222             res_values = na_arithmetic_op(lvalues, rvalues, op, str_rep)
    223
    224     return res_values

~/sandbox/pandas/pandas/core/ops/array_ops.py in na_arithmetic_op(left, right, op, str_rep, is_cmp)
    172             #  will handle complex numbers incorrectly, see GH#32047
    173             raise
--> 174         result = masked_arith_op(left, right, op)
    175
    176     if is_cmp and (is_scalar(result) or result is NotImplemented):

~/sandbox/pandas/pandas/core/ops/array_ops.py in masked_arith_op(x, y, op)
    126         if mask.any():
    127             with np.errstate(all="ignore"):
--> 128                 result[mask] = op(xrav[mask], y)
    129
    130     result, _ = maybe_upcast_putmask(result, ~mask, np.nan)

TypeError: can only concatenate str (not "int") to str
```

**Comment by martindurant** [comment]
@TomAugspurger 's suggested fix, with appropriate test, may be a small PR. However, I suspect that setting the df _meta correctly would be at least a simple workaround.
