### ISSUE TITLE
Merging fails when merging on a column of extension dtype of the same size (Int32 and int32)

### ISSUE THREAD

**Issue by lionsardesai** [dask/dask#6018]
Ran across this issue after updating pandas version (1.0.2) and on latest dask (2.12.0). This feels similar to #5720 that was previously reported.

A snippet to reproduce the issue:
```
import pandas as pd
from dask.dataframe.multi import merge
import dask.dataframe as dd
import dask as d

print("---versions for bug report---")
print(f"pandas version: {pd.__version__}")
print(f"dask version: {d.__version__}")

df1 = pd.DataFrame(
    {"A": pd.Series([1, 2, 3], dtype="Int32"), "B": [1, 1, 3], "C": list("aab")}
)
df2 = pd.DataFrame(
    {"A": pd.Series([1, 2, 3], dtype="int32"), "E": [1, 1, 3], "F": list("aab")}
)
ddf1 = dd.from_pandas(df1, 1)
ddf2 = dd.from_pandas(df2, 2)

# pure pandas merge works
print("pandas-only merge")
print(df1.merge(df2, on="A"))
print("dask merge")
# fails with ValueError: cannot convert to 'int64'-dtype NumPy array with missing values. Specify an appropriate 'na_value' for this dtype.
print(merge(ddf1, ddf2, on="A"))
print(ddf1.merge(ddf2, on="A"))
```

Pandas can merge on the column A with dtypes Int32 and int32 respectively on df1 and df2, however the dask-equivalents throw the following error:
`ValueError: cannot convert to 'int64'-dtype NumPy array with missing values. Specify an appropriate 'na_value' for this dtype.`

<details>
<summary>Full trace:</summary>
<p>

```
Traceback (most recent call last):
  File "/Users/shardulsardesai/Projects/datashipping/tests/test_merge_issue.py", line 29, in <module>
    print(merge(ddf1, ddf2, on="A"))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/dask/dataframe/multi.py", line 493, in merge
    indicator=indicator,
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/dask/dataframe/multi.py", line 324, in single_partition_join
    meta = left._meta_nonempty.merge(right._meta_nonempty, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pandas/core/frame.py", line 7297, in merge
    validate=validate,
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pandas/core/reshape/merge.py", line 88, in merge
    return op.get_result()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pandas/core/reshape/merge.py", line 643, in get_result
    join_index, left_indexer, right_indexer = self._get_join_info()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pandas/core/reshape/merge.py", line 862, in _get_join_info
    (left_indexer, right_indexer) = self._get_join_indexers()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pandas/core/reshape/merge.py", line 841, in _get_join_indexers
    self.left_join_keys, self.right_join_keys, sort=self.sort, how=self.how
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pandas/core/reshape/merge.py", line 1311, in _get_join_indexers
    zipped = zip(*mapped)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pandas/core/reshape/merge.py", line 1309, in <genexpr>
    for n in range(len(left_keys))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pandas/core/reshape/merge.py", line 1901, in _factorize_keys
    lk = ensure_int64(com.values_from_object(lk))
  File "pandas/_libs/algos_common_helper.pxi", line 93, in pandas._libs.algos.ensure_int64
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pandas/core/arrays/masked.py", line 145, in __array__
    return self.to_numpy(dtype=dtype)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pandas/core/arrays/masked.py", line 127, in to_numpy
    f"cannot convert to '{dtype}'-dtype NumPy array "
ValueError: cannot convert to 'int64'-dtype NumPy array with missing values. Specify an appropriate 'na_value' for this dtype.
```

</p>
</details>

**Comment by TomAugspurger** [comment]
I'm a bit surprised to see that the pandas version works. Indeed, if you change it to have any missing values, you see the exception that Dask eventually runs into

```python
In [12]: df1 = pd.DataFrame({"A": pd.array([1, 2, None]), "B": [1, 2, 3]})

In [13]: df2 = pd.DataFrame({"A": [1, 2, 3], "C": [1, 2, 3]})

In [14]: pd.merge(df1, df2, on="A")
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-14-24d32ed92a0d> in <module>
----> 1 pd.merge(df1, df2, on="A")

~/Envs/dask-dev/lib/python3.7/site-packages/pandas/core/reshape/merge.py in merge(left, right, how, on, left_on, right_on, left_index, right_index, sort, suffixes, copy, indicator, validate)
     86         validate=validate,
     87     )
---> 88     return op.get_result()
     89
     90

~/Envs/dask-dev/lib/python3.7/site-packages/pandas/core/reshape/merge.py in get_result(self)
    641             self.left, self.right = self._indicator_pre_merge(self.left, self.right)
    642
--> 643         join_index, left_indexer, right_indexer = self._get_join_info()
    644
    645         ldata, rdata = self.left._data, self.right._data

~/Envs/dask-dev/lib/python3.7/site-packages/pandas/core/reshape/merge.py in _get_join_info(self)
    860             )
    861         else:
--> 862             (left_indexer, right_indexer) = self._get_join_indexers()
    863
    864             if self.right_index:

~/Envs/dask-dev/lib/python3.7/site-packages/pandas/core/reshape/merge.py in _get_join_indexers(self)
    839         """ return the join indexers """
    840         return _get_join_indexers(
--> 841             self.left_join_keys, self.right_join_keys, sort=self.sort, how=self.how
    842         )
    843

~/Envs/dask-dev/lib/python3.7/site-packages/pandas/core/reshape/merge.py in _get_join_indexers(left_keys, right_keys, sort, how, **kwargs)
   1309         for n in range(len(left_keys))
   1310     )
-> 1311     zipped = zip(*mapped)
   1312     llab, rlab, shape = [list(x) for x in zipped]
   1313

~/Envs/dask-dev/lib/python3.7/site-packages/pandas/core/reshape/merge.py in <genexpr>(.0)
   1307     mapped = (
   1308         _factorize_keys(left_keys[n], right_keys[n], sort=sort)
-> 1309         for n in range(len(left_keys))
   1310     )
   1311     zipped = zip(*mapped)

~/Envs/dask-dev/lib/python3.7/site-packages/pandas/core/reshape/merge.py in _factorize_keys(lk, rk, sort)
   1899         #  and rk is datetime-dtype
   1900         klass = libhashtable.Int64Factorizer
-> 1901         lk = ensure_int64(com.values_from_object(lk))
   1902         rk = ensure_int64(com.values_from_object(rk))
   1903     elif issubclass(lk.dtype.type, (np.timedelta64, np.datetime64)) and issubclass(

pandas/_libs/algos_common_helper.pxi in pandas._libs.algos.ensure_int64()

~/Envs/dask-dev/lib/python3.7/site-packages/pandas/core/arrays/masked.py in __array__(self, dtype)
    143         We return an object array here to preserve our scalar values
    144         """
--> 145         return self.to_numpy(dtype=dtype)
    146
    147     def __arrow_array__(self, type=None):

~/Envs/dask-dev/lib/python3.7/site-packages/pandas/core/arrays/masked.py in to_numpy(self, dtype, copy, na_value)
    125             ):
    126                 raise ValueError(
--> 127                     f"cannot convert to '{dtype}'-dtype NumPy array "
    128                     "with missing values. Specify an appropriate 'na_value' "
    129                     "for this dtype."

ValueError: cannot convert to 'int64'-dtype NumPy array with missing values. Specify an appropriate 'na_value' for this dtype.
```

This will likely need to be resolved upstream in pandas. I'm not sure if there's an issue for it.

**Comment by martindurant** [comment]
We find that the exception still occurs. It seems that `meta_nonempty`, when presented with an nullable integer, make a column containing one `<NA>`, even though the original data has none. **If** the original data has a <NA>, it fails in the same way.

So `meta_nonempty`/`_nonempty_sries` needs to make a decision on when to include NANs, whether this is necessary.

May be related to https://github.com/dask/dask/pull/7375

**Comment by phofl** [comment]
This was fixed in pandas 2.0 and seems to work reliably now.
