### ISSUE TITLE
TypeError: 'float' object cannot be interpreted as an integer

### ISSUE THREAD

**Issue by SonyFrancis** [dask/dask#6050]
Dask throwing an error when trying to fit a dask array to an ml model.
 
Code below:
 X_train,X_test,y_train,y_test= train_test_split(X,y,test_size=0.25, random_state=42)
print(X_train.shape, y_train.shape)
with joblib.parallel_backend('dask'):
    import xgboost as xgb 
    from sklearn.metrics import accuracy_score, precision_score, recall_score
    model = xgb.XGBClassifier()
    model.fit(X_train,y_train)
    y_pred = model.predict(X_test)
    acc = accuracy_score(y_test, y_pred)
    rec = recall_score(y_test, y_pred)
    prec = precision_score(y_test, y_pred)
    print(f"Accuracy: {acc}, Precision:{prec}, Recall:{rec}")

Shape of X_train & y_train(41106, 19) (41106,)
Error:
distributed.worker - WARNING -  Compute Failed
Function:  getitem
args:      (array([0, 0, 0, ..., 0, 0, 0], dtype=int64), array([19340., 39060.,  2596., ..., 24442.,  3113., 18907.]))
kwargs:    {}
Exception: IndexError('arrays used as indices must be of integer (or boolean) type')

Traceback (most recent call last):
  File ".\testing_dask.py", line 203, in <module>
    model.fit(X_train,y_train)
  File "C:\Users\SONY\miniconda3\lib\site-packages\sklearn\ensemble\_forest.py", line 296, in fit
    y = check_array(y, accept_sparse='csc', ensure_2d=False, dtype=None)
  File "C:\Users\SONY\miniconda3\lib\site-packages\sklearn\utils\validation.py", line 531, in check_array
    array = np.asarray(array, order=order, dtype=dtype)
  File "C:\Users\SONY\miniconda3\lib\site-packages\numpy\core\_asarray.py", line 85, in asarray
    return array(a, dtype, copy=False, order=order)
  File "C:\Users\SONY\miniconda3\lib\site-packages\dask\array\core.py", line 1342, in __array__
    x = self.compute()
  File "C:\Users\SONY\miniconda3\lib\site-packages\dask\base.py", line 166, in compute
    (result,) = compute(self, traverse=False, **kwargs)
  File "C:\Users\SONY\miniconda3\lib\site-packages\dask\base.py", line 437, in compute
    results = schedule(dsk, keys, **kwargs)
  File "C:\Users\SONY\miniconda3\lib\site-packages\distributed\client.py", line 2595, in get
    results = self.gather(packed, asynchronous=asynchronous, direct=direct)
  File "C:\Users\SONY\miniconda3\lib\site-packages\distributed\client.py", line 1893, in gather
    asynchronous=asynchronous,
  File "C:\Users\SONY\miniconda3\lib\site-packages\distributed\client.py", line 780, in sync
    self.loop, func, *args, callback_timeout=callback_timeout, **kwargs
  File "C:\Users\SONY\miniconda3\lib\site-packages\distributed\utils.py", line 348, in sync
    raise exc.with_traceback(tb)
  File "C:\Users\SONY\miniconda3\lib\site-packages\distributed\utils.py", line 332, in f
    result[0] = yield future
  File "C:\Users\SONY\AppData\Roaming\Python\Python37\site-packages\tornado\gen.py", line 1133, in run
    value = future.result()
  File "C:\Users\SONY\miniconda3\lib\site-packages\distributed\client.py", line 1752, in _gather
    raise exception.with_traceback(traceback)
IndexError: arrays used as indices must be of integer (or boolean) type

**Comment by quasiben** [comment]
@SonyFrancis unfortunately, there is not a whole lot we can do here.  It's extremely helpful if you can give maintainers a [minimal reproducible example](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports):

The error noted is perhaps useful:
> arrays used as indices must be of integer (or boolean) type

Are the indicies int or boolean type ?

**Comment by jrbourbeau** [comment]
Just checking in here, @SonyFrancis are you able to provide a minimal example (https://blog.dask.org/2018/02/28/minimal-bug-reports)? Otherwise it makes it difficult for maintainers to help

**Comment by SonyFrancis** [comment]
Apologies for the delay. Here is my code:
I am using the yellow-trip dataset

import dask
import numpy as np
import pandas as pd
import joblib
import dask.dataframe as dd
....

data = dd.read_csv("../Data/yellow_trip.csv")
targetVar = "total_amount"
date_vars = ['tpep_pickup_datetime', 'tpep_dropoff_datetime']
label_vars = ['VendorID', 'passenger_count', 'RatecodeID', 'store_and_fwd_flag', 'payment_type', 'extra', 'mta_tax', 'improvement_surcharge', 'congestion_surcharge']
numeric_vars = ['trip_distance', 'PULocationID', 'DOLocationID', 'fare_amount', 'tip_amount', 'tolls_amount', 'total_amount']
drift_vars = []

missingVals = list(data.columns[(data.isnull().sum().compute()>0)==True])
missing_num = list(set(missingVals).intersection(numeric_vars))
imp1 = SimpleImputer(strategy="mean",fill_value=constant) 
imp2 = SimpleImputer(strategy="most_frequent",fill_value=constant) 
data[missing_num] = imp1.fit_transform(data[missing_num])
data[missing_label] = imp2.fit_transform(data[missing_label])

cat = Categorizer(columns=label_vars) 
data= cat.fit_transform(data)
en = DummyEncoder(columns=label_vars, drop_first=True)
data = en.fit_transform(data)
sc = StandardScaler() 
data[numeric_vars] = sc.fit_transform(data[numeric_vars])
inputVars = list(set(data.columns).difference(set(targetVar)))

pca = PCA(n_components=16) 
X = pca.fit_transform(data[inputVars].to_dask_array(lengths=True)) using dd.from_array()
y=data[targetVar]
y_array = y.to_dask_array()


X_train,X_test,y_train,y_test= train_test_split(X, y_array,test_size=0.25, random_state=42)

from dask_ml.linear_model import LinearRegression 
model = LinearRegression()
model.fit(X_train,y_train)
y_pred = model.predict(X_test)
print("Test accuracy",model.score(X_test, y_pred))

**Comment by jrbourbeau** [comment]
Thanks for the update @SonyFrancis. Is it possible to reproduce the error without the specific CSV file being used? I don't have that on my laptop (see the "Don’t post data" section in https://blog.dask.org/2018/02/28/minimal-bug-reports). There also appear to be some `import`s missing, e.g. where is `SimpleImputer` coming from?

**Comment by SonyFrancis** [comment]
Hi,

When I am trying to run the same code with fewer data, I am facing another error:
Data:
##Import
data = pd.DataFrame({"VendorID":[1,1,2,2,2,2,2,1,1], "passenger_count":[1,1,3,5,5,5,5,1,1], 
"trip_distance": [1.5,2.6,0,0,0,0,0,1.3,3.7], "RatecodeID":[1,1,1,1,2,1,2,1,1],	"store_and_fwd_flag" :["N","N","N","N","N","N","N",np.nan,"N"], 
"PULocationID" :[151,239,236,193,193,193,193,163,229], "DOLocationID":[239,246,236,193,193,193,193,229,7], 
"payment_type":[1,1,1,2,2,2,2,1,1],	"fare_amount":[7,14,4.5,3.5,52,3.5,52,6.5,13.5], 
"extra":[0.5,0.5,0.5,0.5,0,0.5,0,0.5,0.5], "mta_tax":[0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5],	
"tip_amount":[1.65,1,0,0,0,0,0,1.25,3.7], "tolls_amount":[0,0,0,0,0,5.76,0,0,0],	
"improvement_surcharge":[0.3,0.3,0.3,0.3,0.3,0.3,0.3,0.3,0.3],	"total_amount":[9.95,16.3,5.8,7.55,55.55,13.31,55.55,9.05,18.5], 
"congestion_surcharge":[np.nan,0,np.nan,np.nan,np.nan,np.nan,np.nan,np.nan,np.nan]
})
data = dd.from_pandas(data,npartitions=1)
....
remaining code as above
Error:
Traceback (most recent call last):
  File "C:\Users\SONY\miniconda3\lib\site-packages\dask_ml\utils.py", line 31, in _svd_flip_copy
    return skm.svd_flip(x, y)
  File "C:\Users\SONY\miniconda3\lib\site-packages\sklearn\utils\extmath.py", line 530, in svd_flip
    v *= signs[:, np.newaxis]
ValueError: operands could not be broadcast together with shapes (16,16) (9,1) (16,16)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ".\testing_dask_inprogress.py", line 198, in <module>
    pca = PCA().fit(data[inputVars].to_dask_array(lengths=True))
  File "C:\Users\SONY\miniconda3\lib\site-packages\dask_ml\decomposition\pca.py", line 203, in fit
    self._fit(X)
  File "C:\Users\SONY\miniconda3\lib\site-packages\dask_ml\decomposition\pca.py", line 348, in _fit
    raise e
  File "C:\Users\SONY\miniconda3\lib\site-packages\dask_ml\decomposition\pca.py", line 335, in _fit
    singular_values,
  File "C:\Users\SONY\miniconda3\lib\site-packages\dask\base.py", line 437, in compute
    results = schedule(dsk, keys, **kwargs)
  File "C:\Users\SONY\miniconda3\lib\site-packages\dask\threaded.py", line 84, in get
    **kwargs
  File "C:\Users\SONY\miniconda3\lib\site-packages\dask\local.py", line 486, in get_async
    raise_exception(exc, tb)
  File "C:\Users\SONY\miniconda3\lib\site-packages\dask\local.py", line 316, in reraise
    raise exc
  File "C:\Users\SONY\miniconda3\lib\site-packages\dask\local.py", line 222, in execute_task
    result = _execute_task(task, data)
  File "C:\Users\SONY\miniconda3\lib\site-packages\dask\core.py", line 121, in _execute_task
    return func(*(_execute_task(a, cache) for a in args))
  File "C:\Users\SONY\miniconda3\lib\site-packages\dask\core.py", line 121, in <genexpr>
    return func(*(_execute_task(a, cache) for a in args))
  File "C:\Users\SONY\miniconda3\lib\site-packages\dask\core.py", line 121, in _execute_task
    return func(*(_execute_task(a, cache) for a in args))
  File "C:\Users\SONY\miniconda3\lib\site-packages\dask_ml\utils.py", line 33, in _svd_flip_copy
    return skm.svd_flip(x.copy(), y.copy())
  File "C:\Users\SONY\miniconda3\lib\site-packages\sklearn\utils\extmath.py", line 530, in svd_flip
    v *= signs[:, np.newaxis]
ValueError: operands could not be broadcast together with shapes (16,16) (9,1) (16,16)

**Comment by SonyFrancis** [comment]
@jrbourbeau  :
Import statements:
import time
import dask
import joblib
import numpy as np
import pandas as pd
import dask.dataframe as dd
import matplotlib.pyplot as plt
from dateutil.parser import parse
from dask_ml.decomposition import PCA
from dask_ml.impute import SimpleImputer
from dask.diagnostics import ProgressBar
from dask_ml.linear_model import LogisticRegression
from dask_ml.model_selection import train_test_split
from dask_ml.preprocessing import StandardScaler, MinMaxScaler, RobustScaler
from dask_ml.preprocessing import Categorizer, DummyEncoder, LabelEncoder, OneHotEncoder, OrdinalEncoder

**Comment by SonyFrancis** [comment]
Hi,

I tried to make one change in the original code to make it work, but again failed with another error:
import dask
import numpy as np
import pandas as pd
import joblib
import dask.dataframe as dd
....

data = dd.read_csv("../Data/yellow_trip.csv")
targetVar = "total_amount"
date_vars = ['tpep_pickup_datetime', 'tpep_dropoff_datetime']
label_vars = ['VendorID', 'passenger_count', 'RatecodeID', 'store_and_fwd_flag', 'payment_type', 'extra', 'mta_tax', 'improvement_surcharge', 'congestion_surcharge']
numeric_vars = ['trip_distance', 'PULocationID', 'DOLocationID', 'fare_amount', 'tip_amount', 'tolls_amount', 'total_amount']
drift_vars = []

missingVals = list(data.columns[(data.isnull().sum().compute()>0)==True])
missing_num = list(set(missingVals).intersection(numeric_vars))
imp1 = SimpleImputer(strategy="mean",fill_value=constant)
imp2 = SimpleImputer(strategy="most_frequent",fill_value=constant)
data[missing_num] = imp1.fit_transform(data[missing_num])
data[missing_label] = imp2.fit_transform(data[missing_label])

cat = Categorizer(columns=label_vars)
data= cat.fit_transform(data)
en = DummyEncoder(columns=label_vars, drop_first=True)
data = en.fit_transform(data)
sc = StandardScaler()
data[numeric_vars] = sc.fit_transform(data[numeric_vars])
inputVars = list(set(data.columns).difference(set(targetVar)))

pca = PCA(n_components=16)
X = pca.fit_transform(data[inputVars].to_dask_array(lengths=True)) using dd.from_array()
y=data[targetVar]
y_array = y.to_dask_array(lengths=True) #-----made this change so the previous error is gone but new error is thrown 

X_train,X_test,y_train,y_test= train_test_split(X, y_array,test_size=0.25, random_state=42)

from dask_ml.linear_model import LinearRegression
model = LinearRegression()
model.fit(X_train,y_train)
y_pred = model.predict(X_test)
print("Test accuracy",model.score(X_test, y_pred))


Error:
Traceback (most recent call last):
  File ".\testing_dask_inprogress.py", line 226, in <module>
    model.fit(X_train,y_train)
  File "C:\Users\SONY\miniconda3\lib\site-packages\dask_ml\linear_model\glm.py", line 187, in fit
    self._coef = algorithms._solvers[self.solver](X, y, **solver_kwargs)
  File "C:\Users\SONY\miniconda3\lib\site-packages\dask_glm\utils.py", line 26, in normalize_inputs
    out = algo(Xn, y, *args, **kwargs).copy()
  File "C:\Users\SONY\miniconda3\lib\site-packages\dask_glm\algorithms.py", line 265, in admm
    new_betas = np.array(da.compute(*new_betas))
  File "C:\Users\SONY\miniconda3\lib\site-packages\dask\base.py", line 437, in compute
    results = schedule(dsk, keys, **kwargs)
  File "C:\Users\SONY\miniconda3\lib\site-packages\dask\threaded.py", line 84, in get
    **kwargs
  File "C:\Users\SONY\miniconda3\lib\site-packages\dask\local.py", line 486, in get_async
    raise_exception(exc, tb)
  File "C:\Users\SONY\miniconda3\lib\site-packages\dask\local.py", line 316, in reraise
    raise exc
  File "C:\Users\SONY\miniconda3\lib\site-packages\dask\local.py", line 222, in execute_task
    result = _execute_task(task, data)
  File "C:\Users\SONY\miniconda3\lib\site-packages\dask\core.py", line 121, in _execute_task
    return func(*(_execute_task(a, cache) for a in args))
IndexError: index 1004586 is out of bounds for axis 0 with size 7738144

I tried recreating this with a smaller dataset as shown in previous comment but the same error as previous one  appears "ValueError: operands could not be broadcast together with shapes (16,16) (9,1) (16,16)"

It would be great if anyone could help resolve this or if anyone could let me know how can we pass the output from dask dimensionality reduction techniques like TruncatedSVD/PCA to any model building algorithm

**Comment by SonyFrancis** [comment]
Hi,

I tried running the code with the below data and it works absolutely fine.
data = pd.DataFrame({"Id":[1,2,3,4,5,6,7,8,9,10],"Target":[0,1,1,1,0,0,0,0,1,1],
"x1":[3,1,3,1,3,3,1,3,3,2],"x2":["A","B","C","D","E","F","G","H","I","J"],"x3":["M","M","F","M","F","F","M","F","M","F"],
"x4":[22,38,26,35,35,54,2,27,14,np.nan],
"x5":[1,1,0,1,0,0,0,3,0,1],"Parch":[0,0,0,0,0,0,0,1,2,0],
"x6":[7.25,71.2833,7.925,53.1,8.05,8.4583,51.8625,21.075,11.1333,30.0708],
"x7":["S","C","S","S","S","Q","S","S","S","C"]})


@jrbourbeau  and @quasiben : It would be great if you could let me know why with some data it works fine and with others it causes issues. Is there a particular format in which the data should be to pass it to the dask matrix decomposition methods?

**Comment by TomAugspurger** [comment]
@SonyFrancis could you edit your comments to 

1. Be minimal reproducible examples? It's hard to piece things together when they're scattered across multiple comments.
2. Use GitHub's markdown formatting? https://guides.github.com/features/mastering-markdown/

**Comment by martindurant** [comment]
Closing as unverified.
