### ISSUE TITLE
Failing to convert string timestamp to datetime64['s'] using map_partitions

### ISSUE THREAD

**Issue by rgsl888prabhu** [dask/dask#6078]
**Bug report:** 
Code to reproduce
```
>>> import pandas as pd
>>> import dask.dataframe as dd
>>> pdf = pd.DataFrame()
>>> pdf['datetime'] = ['2014-01-15 19:05:39', '2014-01-10 20:33:38', '2014-01-10 20:33:38']
>>> ddf=dd.from_pandas(pdf, npartitions=1)
>>> def clean(df_part):
...     df_part['datetime'] = df_part['datetime'].astype('datetime64[s]')
...     return df_part
... 
>>> ddf =  ddf.map_partitions(clean)
Traceback (most recent call last):
  File "/home/rgsl888/anaconda3/envs/cudf_dev2/lib/python3.7/site-packages/pandas/core/arrays/datetimes.py", line 1979, in objects_to_datetime64ns
    values, tz_parsed = conversion.datetime_to_datetime64(data)
  File "pandas/_libs/tslibs/conversion.pyx", line 200, in pandas._libs.tslibs.conversion.datetime_to_datetime64
TypeError: Unrecognized value type: <class 'str'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rgsl888/anaconda3/envs/cudf_dev2/lib/python3.7/site-packages/dask/dataframe/utils.py", line 172, in raise_on_meta_error
    yield
  File "/home/rgsl888/anaconda3/envs/cudf_dev2/lib/python3.7/site-packages/dask/dataframe/core.py", line 4941, in _emulate
    return func(*_extract_meta(args, True), **_extract_meta(kwargs, True))
  File "<stdin>", line 2, in clean
  File "/home/rgsl888/anaconda3/envs/cudf_dev2/lib/python3.7/site-packages/pandas/core/generic.py", line 5882, in astype
    dtype=dtype, copy=copy, errors=errors, **kwargs
  File "/home/rgsl888/anaconda3/envs/cudf_dev2/lib/python3.7/site-packages/pandas/core/internals/managers.py", line 581, in astype
    return self.apply("astype", dtype=dtype, **kwargs)
  File "/home/rgsl888/anaconda3/envs/cudf_dev2/lib/python3.7/site-packages/pandas/core/internals/managers.py", line 438, in apply
    applied = getattr(b, f)(**kwargs)
  File "/home/rgsl888/anaconda3/envs/cudf_dev2/lib/python3.7/site-packages/pandas/core/internals/blocks.py", line 559, in astype
    return self._astype(dtype, copy=copy, errors=errors, values=values, **kwargs)
  File "/home/rgsl888/anaconda3/envs/cudf_dev2/lib/python3.7/site-packages/pandas/core/internals/blocks.py", line 643, in _astype
    values = astype_nansafe(vals1d, dtype, copy=True, **kwargs)
  File "/home/rgsl888/anaconda3/envs/cudf_dev2/lib/python3.7/site-packages/pandas/core/dtypes/cast.py", line 715, in astype_nansafe
    return astype_nansafe(to_datetime(arr).values, dtype, copy=copy)
  File "/home/rgsl888/anaconda3/envs/cudf_dev2/lib/python3.7/site-packages/pandas/util/_decorators.py", line 208, in wrapper
    return func(*args, **kwargs)
  File "/home/rgsl888/anaconda3/envs/cudf_dev2/lib/python3.7/site-packages/pandas/core/tools/datetimes.py", line 795, in to_datetime
    result = convert_listlike(arg, box, format)
  File "/home/rgsl888/anaconda3/envs/cudf_dev2/lib/python3.7/site-packages/pandas/core/tools/datetimes.py", line 463, in _convert_listlike_datetimes
    allow_object=True,
  File "/home/rgsl888/anaconda3/envs/cudf_dev2/lib/python3.7/site-packages/pandas/core/arrays/datetimes.py", line 1984, in objects_to_datetime64ns
    raise e
  File "/home/rgsl888/anaconda3/envs/cudf_dev2/lib/python3.7/site-packages/pandas/core/arrays/datetimes.py", line 1975, in objects_to_datetime64ns
    require_iso8601=require_iso8601,
  File "pandas/_libs/tslib.pyx", line 465, in pandas._libs.tslib.array_to_datetime
  File "pandas/_libs/tslib.pyx", line 688, in pandas._libs.tslib.array_to_datetime
  File "pandas/_libs/tslib.pyx", line 822, in pandas._libs.tslib.array_to_datetime_object
  File "pandas/_libs/tslib.pyx", line 813, in pandas._libs.tslib.array_to_datetime_object
  File "pandas/_libs/tslibs/parsing.pyx", line 225, in pandas._libs.tslibs.parsing.parse_datetime_string
  File "/home/rgsl888/anaconda3/envs/cudf_dev2/lib/python3.7/site-packages/dateutil/parser/_parser.py", line 1374, in parse
    return DEFAULTPARSER.parse(timestr, **kwargs)
  File "/home/rgsl888/anaconda3/envs/cudf_dev2/lib/python3.7/site-packages/dateutil/parser/_parser.py", line 649, in parse
    raise ParserError("Unknown string format: %s", timestr)
dateutil.parser._parser.ParserError: Unknown string format: foo
```

Dask version is 
```
>>> dask.__version__
'2.12.0+8.g278ad0a4'
```

**Comment by martindurant** [comment]
Because the input column has strings, it is type "object". Dask tries to guess what effect your function has by passing a filler value, "foo", to see what the return types will be - unfortunately, this causes the exception you see.

To avoid this scenario, you should specify the `meta` keyword to `map_partitions` (this is generally good practice anyway). 

With a dictionary:

```
ddf =  ddf.map_partitions(clean, meta={'datetime': 'datetime64[s]'})
```

or, (better), with a full dataframe (which would allow you to specify the index type, for example)
```
ddf =  ddf.map_partitions(clean, 
    meta=pd.DataFrame({'datetime': pd.Series([], dtype='datetime64[s]')}))
```
