### ISSUE TITLE
creating dask graph distributed.protocol.core - CRITICAL - Failed to deserialize

### ISSUE THREAD

**Issue by KabitaBaral1** [dask/dask#6081]
Hi,

I am running pyscenic with Jupyter Notebook and when I run the following snipet of code:
!pyscenic grn {f_loom_path_scenic} {f_tfs} -o adj.csv --num_workers 20

I get the following error:

/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/dask/config.py:161: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}

2020-04-09 14:49:12,997 - pyscenic.cli.pyscenic - INFO - Loading expression matrix.

2020-04-09 14:49:18,632 - pyscenic.cli.pyscenic - INFO - Inferring regulatory networks.
/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/dask/config.py:161: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
preparing dask client
parsing input
/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/arboreto/algo.py:214: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  expression_matrix = expression_data.as_matrix()
creating dask graph
distributed.protocol.core - CRITICAL - Failed to deserialize
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/distributed/protocol/core.py", line 108, in loads
    header = msgpack.loads(header, use_list=False, **msgpack_opts)
  File "msgpack/_unpacker.pyx", line 195, in msgpack._cmsgpack.unpackb
ValueError: tuple is not allowed for map key
distributed.core - ERROR - tuple is not allowed for map key
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/distributed/core.py", line 347, in handle_comm
    msg = yield comm.read()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/distributed/comm/tcp.py", line 218, in read
    frames, deserialize=self.deserialize, deserializers=deserializers
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/tornado/gen.py", line 209, in wrapper
    yielded = next(result)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/distributed/comm/utils.py", line 85, in from_frames
    res = _from_frames()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/distributed/comm/utils.py", line 71, in _from_frames
    frames, deserialize=deserialize, deserializers=deserializers
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/distributed/protocol/core.py", line 108, in loads
    header = msgpack.loads(header, use_list=False, **msgpack_opts)
  File "msgpack/_unpacker.pyx", line 195, in msgpack._cmsgpack.unpackb
ValueError: tuple is not allowed for map key
distributed.protocol.core - CRITICAL - Failed to deserialize
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/distributed/protocol/core.py", line 108, in loads
    header = msgpack.loads(header, use_list=False, **msgpack_opts)
  File "msgpack/_unpacker.pyx", line 195, in msgpack._cmsgpack.unpackb
ValueError: tuple is not allowed for map key
not shutting down client, client was created externally
finished
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/bin/pyscenic", line 8, in <module>
    sys.exit(main())
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pyscenic/cli/pyscenic.py", line 420, in main
    args.func(args)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pyscenic/cli/pyscenic.py", line 72, in find_adjacencies_command
    network = method(expression_data=ex_mtx, tf_names=tf_names, verbose=True, client_or_address=client, seed=args.seed)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/arboreto/algo.py", line 41, in grnboost2
    early_stop_window_length=early_stop_window_length, limit=limit, seed=seed, verbose=verbose)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/arboreto/algo.py", line 128, in diy
    seed=seed)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/arboreto/core.py", line 403, in create_graph
    future_tf_matrix = client.scatter(tf_matrix, broadcast=True)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/distributed/client.py", line 2071, in scatter
    hash=hash,
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/distributed/client.py", line 753, in sync
    return sync(self.loop, func, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/distributed/utils.py", line 331, in sync
    six.reraise(*error[0])
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/six.py", line 696, in reraise
    raise value
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/distributed/utils.py", line 316, in f
    result[0] = yield future
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/distributed/client.py", line 1916, in _scatter
    timeout=timeout,
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/distributed/core.py", line 739, in send_recv_from_rpc
    result = yield send_recv(comm=comm, op=key, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/distributed/core.py", line 533, in send_recv
    response = yield comm.read(deserializers=deserializers)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/distributed/comm/tcp.py", line 218, in read
    frames, deserialize=self.deserialize, deserializers=deserializers
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/tornado/gen.py", line 209, in wrapper
    yielded = next(result)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/distributed/comm/utils.py", line 85, in from_frames
    res = _from_frames()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/distributed/comm/utils.py", line 71, in _from_frames
    frames, deserialize=deserialize, deserializers=deserializers
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/distributed/protocol/core.py", line 108, in loads
    header = msgpack.loads(header, use_list=False, **msgpack_opts)
  File "msgpack/_unpacker.pyx", line 195, in msgpack._cmsgpack.unpackb
ValueError: tuple is not allowed for map key

As you can see:
It starts going haywire with errors at the following point:

creating dask graph
distributed.protocol.core - CRITICAL - Failed to deserialize

I was hoping you could help me fix this issue. Thank you

**Comment by jrbourbeau** [comment]
Thanks for raising an issue @KabitaBaral1. What version of `msgpack` and `distributed` are you using? There were breaking changes in the 1.0 of `msgpack` that are only compatible with more recent versions of `distributed`. Specifically using `msgpack` 1.0+ requires `distributed` >=2.11.0

**Comment by KabitaBaral1** [comment]
Hi,

I am using msgpack 1.0.0 and distributed 2.14.0.

**Comment by jrbourbeau** [comment]
Alright, thanks for the version info. Could you provide a minimum example so we can reproduce the error you're getting? (see https://blog.dask.org/2018/02/28/minimal-bug-reports)

**Comment by KabitaBaral1** [comment]
Hi,
Thank you for getting back to me. I will try my best to do so.
So, I am using pyscenic and the snipet of code is:
!pyscenic grn {f_loom_path_scenic} {f_tfs} -o adj.csv --num_workers 20

for my transcription_factor  (f_tf) in code above list I used the following list:
https://github.com/aertslab/pySCENIC/blob/master/resources/hs_hgnc_tfs.txt

For f_loom_path_scenic: I created a loom file which is a matrix file with cell names as row names and gene names as column names 
like:

                                          | OR4F5 | AL627309.1 | AL627309.3 | AL669831.5 | FAM87B
AACTGGTTCAACTCTT-1 | 0 | 0 | 0 | 0 | 0
AAGCCGCCACGAGAGT-1 | 0 | 0 | 0 | 0 | 0
ACACCCTTCTACGAGT-1 | 0 | 0 | 0 | 0 | 0
ACCAGTAAGACAATAC-1 | 0 | 0 | 0 | 0 | 0
AGCGGTCCAGCTCCGA-1 | 0 | 0 | 0 | 0 | 0
AGCTCTCTCTAGCACA-1 | 0 | 0 | 0 | 0 | 0
AGGCCGTTCCACGAAT-1 | 0 | 0 | 0 | 0 | 0

The code I used on Jupyter is from this source:
https://github.com/aertslab/SCENICprotocol/blob/master/notebooks/PBMC10k_SCENIC-protocol-CLI.ipynb

I am not sure if this is of any help, but I am not sure how to get a minimum example for this, I apologize for that. Please let me know if I can help in any way. Thank you for looking into this

**Comment by martindurant** [comment]
The line `data = yaml.load(f.read()) or {}` towards the top of your log suggests that you have a very old version of dask. You should make sure that you have compatible versions of dask and distributed, and that you have the same versions for every worker.

Furthermore, there is every chance that this is an issue with `pyscenic`, so you may want to cross-post there; I don't think anyone here knows about it,

**Comment by KabitaBaral1** [comment]
Hi @martindurant Thank you, I made sure that dask and distributed are same version. When you said same versions for every worker, what did you mean?

Thank you for your help.

**Comment by martindurant** [comment]
> I made sure that dask and distributed are same version.

What versions exactly? How is it installed? I am being pernickety because of that YAML warning, which is very unexpected.

> When you said same versions for every worker, what did you mean

You didn't tell us how you are launching the cluster - perhaps scenic does this for you. But Dask is using a set of processes which maybe are not even on the same machine. The worker processes could in principle not be using the same environment your main code is.

**Comment by saum-kmr** [comment]
Hello, I am running into similar problem. I checked for the version of dask and distributed which were same when i installed using conda both versions 2.19.0. However when installing pyscenic (version 0.10.2), it removed these versions and installed dask 1.0.0 and distributed as 1.28.1 . Also my msgpack is version 1.0.0. Below is some of the output when installing pyscenic:

Installing collected packages: frozendict, attrs, dask, pandas, numpy-groupies, loompy, boltons, distributed, arboreto, interlap, pyarrow, dill, multiprocessing-on-dill, pyscenic
  Attempting uninstall: dask
    Found existing installation: dask 2.19.0
    Uninstalling dask-2.19.0:
      Successfully uninstalled dask-2.19.0
  Attempting uninstall: pandas
    Found existing installation: pandas 1.0.5
    Uninstalling pandas-1.0.5:
      Successfully uninstalled pandas-1.0.5
  Attempting uninstall: distributed
    Found existing installation: distributed 2.19.0
    Uninstalling distributed-2.19.0:
      Successfully uninstalled distributed-2.19.0
Successfully installed arboreto-0.1.5 attrs-19.3.0 boltons-20.2.0 dask-1.0.0 dill-0.3.2 distributed-1.28.1 frozendict-1.2 interlap-0.2.6 loompy-3.0.6 multiprocessing-on-dill-3.5.0a4 numpy-groupies-0+unknown pandas-0.25.3 pyarrow-0.16.0 pyscenic-0.10.2

**when i run pyscenic CLI**, I always get this error, even with just help command, followed by usage and its options: 
pyscenic --help
/home/saumya.kumar/anaconda2/envs/scenic_protocol/lib/python3.6/site-packages/dask/config.py:161: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}

Any help will be appreciated!

**Comment by martindurant** [comment]
This appears to be a problem with scenic and/or pip, I don't think there's much we can do when you end up with a version of dask/distributed that's so old. I suggest you ask the scenic group.
