### ISSUE TITLE
Dask interaction with pandas

### ISSUE THREAD

**Issue by HCelion** [dask/dask#6151]
Hi, I am having issues when converting a dask bag to a pandas frame. I have installed dask via pip (vs. 2.15.0) and have pandas (1.0.3)

The code to reproduce is:
```
import dask.bag as bag
from dask.distributed import Client
c = Client(n_workers=10)
b = bag.from_sequence([*list(range(1000000))], npartitions=200)
b.to_dataframe().describe().compute()
```
And the error message I get is
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-9-e6dd20824e81> in <module>
----> 1 b.to_dataframe().describe().compute()

~/.conda/envs/dask-env/lib/python3.6/site-packages/dask/base.py in compute(self, **kwargs)
    164         dask.base.compute
    165         """
--> 166         (result,) = compute(self, traverse=False, **kwargs)
    167         return result
    168 

~/.conda/envs/dask-env/lib/python3.6/site-packages/dask/base.py in compute(*args, **kwargs)
    435     keys = [x.__dask_keys__() for x in collections]
    436     postcomputes = [x.__dask_postcompute__() for x in collections]
--> 437     results = schedule(dsk, keys, **kwargs)
    438     return repack([f(r, *a) for r, (f, a) in zip(results, postcomputes)])
    439 

~/.conda/envs/dask-env/lib/python3.6/site-packages/distributed/client.py in get(self, dsk, keys, restrictions, loose_restrictions, resources, sync, asynchronous, direct, retries, priority, fifo_timeout, actors, **kwargs)
   2630                     should_rejoin = False
   2631             try:
-> 2632                 results = self.gather(packed, asynchronous=asynchronous, direct=direct)
   2633             finally:
   2634                 for f in futures.values():

~/.conda/envs/dask-env/lib/python3.6/site-packages/distributed/client.py in gather(self, futures, errors, direct, asynchronous)
   1929                 direct=direct,
   1930                 local_worker=local_worker,
-> 1931                 asynchronous=asynchronous,
   1932             )
   1933 

~/.conda/envs/dask-env/lib/python3.6/site-packages/distributed/client.py in sync(self, func, asynchronous, callback_timeout, *args, **kwargs)
    778         else:
    779             return sync(
--> 780                 self.loop, func, *args, callback_timeout=callback_timeout, **kwargs
    781             )
    782 

~/.conda/envs/dask-env/lib/python3.6/site-packages/distributed/utils.py in sync(loop, func, callback_timeout, *args, **kwargs)
    345     if error[0]:
    346         typ, exc, tb = error[0]
--> 347         raise exc.with_traceback(tb)
    348     else:
    349         return result[0]

~/.conda/envs/dask-env/lib/python3.6/site-packages/distributed/utils.py in f()
    329             if callback_timeout is not None:
    330                 future = asyncio.wait_for(future, callback_timeout)
--> 331             result[0] = yield future
    332         except Exception as exc:
    333             error[0] = sys.exc_info()

~/.conda/envs/dask-env/lib/python3.6/site-packages/tornado/gen.py in run(self)
    733 
    734                     try:
--> 735                         value = future.result()
    736                     except Exception:
    737                         exc_info = sys.exc_info()

~/.conda/envs/dask-env/lib/python3.6/site-packages/distributed/client.py in _gather(self, futures, errors, direct, local_worker)
   1788                             exc = CancelledError(key)
   1789                         else:
-> 1790                             raise exception.with_traceback(traceback)
   1791                         raise exc
   1792                     if errors == "skip":

~/.conda/envs/dask-env/lib/python3.6/site-packages/dask/bag/core.py in to_dataframe()
   2492 
   2493 def to_dataframe(seq, columns, dtypes):
-> 2494     import pandas as pd
   2495 
   2496     seq = reify(seq)

~/.conda/envs/dask-env/lib/python3.6/site-packages/pandas/__init__.py in <module>
    191 # GH 27101
    192 # TODO: remove Panel compat in 1.0
--> 193 if pandas.compat.PY37:
    194 
    195     def __getattr__(name):

AttributeError: module 'pandas' has no attribute 'compat'
```

However, I am able to just 
```
import pandas as pd
```
and it does have the attribute `pd.compat`

I tried downgrading, and installing pandas-concat separately, but that threw other errors.
Any idea what might have caused this?

**Comment by jrbourbeau** [comment]
Thanks for raising an issue @HCelion. I'm not able to reproduce that error using `dask==2.15.0`, `distributed==2.15.0`, and `pandas==1.0.3`. I get the following locally:

```python
In [1]: import dask.bag as bag
   ...: from dask.distributed import Client
   ...: c = Client(n_workers=10)
   ...: b = bag.from_sequence([*list(range(1000000))], npartitions=200)
   ...: b.to_dataframe().describe().compute()

Out[1]:
                    0
count  1000000.000000
mean    499999.500000
std     288675.278932
min          0.000000
25%     332499.500000
50%     666249.750000
75%     998749.250000
max     999999.000000
```


Are you sure those versions of `dask`/`distributed`/`pandas` are installed in your Python environment? Could you post the output of `python -m pip list`?

> I tried downgrading, and installing pandas-concat separately

I don't quite follow what you mean by this. Could you elaborate more? What's pandas-concat?

**Comment by HCelion** [comment]
My apologies, I meant pandas-compat. 
This is what pip list shows:

```
backcall (0.1.0)
bokeh (2.0.2)
certifi (2016.2.28)
click (7.1.2)
cloudpickle (1.4.0)
cycler (0.10.0)
dask (2.15.0)
decorator (4.4.2)
distributed (2.15.0)
fsspec (0.7.3)
HeapDict (1.0.1)
ipykernel (5.2.1)
ipython (7.13.0)
ipython-genutils (0.2.0)
jedi (0.17.0)
Jinja2 (2.11.2)
jupyter-client (6.1.3)
jupyter-core (4.6.3)
kiwisolver (1.2.0)
locket (0.2.0)
MarkupSafe (1.1.1)
matplotlib (3.2.1)
msgpack (1.0.0)
numpy (1.18.3)
packaging (20.3)
pandas (1.0.3)
parso (0.7.0)
partd (1.1.0)
pexpect (4.8.0)
pickleshare (0.7.5)
Pillow (7.1.2)
pip (9.0.1)
prompt-toolkit (3.0.5)
psutil (5.7.0)
ptyprocess (0.6.0)
Pygments (2.6.1)
pyparsing (2.4.7)
python-dateutil (2.8.1)
pytz (2020.1)
PyYAML (5.3.1)
pyzmq (19.0.0)
setuptools (36.4.0)
six (1.14.0)
sortedcontainers (2.1.0)
tblib (1.6.0)
toolz (0.10.0)
tornado (6.0.4)
traitlets (4.3.3)
typing-extensions (3.7.4.2)
wcwidth (0.1.9)
wheel (0.29.0)
zict (2.0.0)
```

I am using that environment via a remote kernel, but that should not matter, right?

**Comment by TomAugspurger** [comment]
Can you reproduce the issue in a new environment?

**Comment by HCelion** [comment]
Yes, I have since build the same environment from scratch and it reproduces. Apart from the installation command
python -m pip install "dask[complete]" 
I only install jupyter and set up the kernelspec.

**Comment by HCelion** [comment]
Yes, it reproduces in the REPL:

```
(dask-env) ~/projects/tutorials_tryouts/dask>python
Python 3.6.2 |Continuum Analytics, Inc.| (default, Jul 20 2017, 13:51:32)
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import dask.bag as bag
>>> from dask.distributed import Client
>>> c = Client(n_workers=10)
>>> b = bag.from_sequence([*list(range(100))], npartitions=15)
>>> b.to_dataframe().describe().compute()
distributed.worker - WARNING -  Compute Failed
Function:  to_dataframe
args:      ([91, 92, 93, 94, 95, 96, 97], [0], {0: dtype('int64')})
kwargs:    {}
Exception: AttributeError("module 'pandas' has no attribute 'compat'",)

distributed.worker - WARNING -  Compute Failed
Function:  to_dataframe
args:      ([70, 71, 72, 73, 74, 75, 76], [0], {0: dtype('int64')})
kwargs:    {}
Exception: AttributeError("module 'pandas' has no attribute 'compat'",)

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/kingla/.conda/envs/dask-env/lib/python3.6/site-packages/dask/base.py", line 166, in compute
    (result,) = compute(self, traverse=False, **kwargs)
  File "/home/kingla/.conda/envs/dask-env/lib/python3.6/site-packages/dask/base.py", line 437, in compute
    results = schedule(dsk, keys, **kwargs)
  File "/home/kingla/.conda/envs/dask-env/lib/python3.6/site-packages/distributed/client.py", line 2632, in get
    results = self.gather(packed, asynchronous=asynchronous, direct=direct)
  File "/home/kingla/.conda/envs/dask-env/lib/python3.6/site-packages/distributed/client.py", line 1931, in gather
distributed.worker - WARNING - Could not deserialize task
Traceback (most recent call last):
  File "/home/kingla/.conda/envs/dask-env/lib/python3.6/site-packages/distributed/worker.py", line 3237, in loads_function
    result = cache_loads[bytes_object]
  File "/home/kingla/.conda/envs/dask-env/lib/python3.6/site-packages/distributed/utils.py", line 1497, in __getitem__
    value = super().__getitem__(key)
  File "/home/kingla/.conda/envs/dask-env/lib/python3.6/collections/__init__.py", line 993, in __getitem__
    raise KeyError(key)
KeyError: b'\x80\x04\x95,\x00\x00\x00\x00\x00\x00\x00\x8c\x13dask.dataframe.core\x94\x8c\x10_reduction_chunk\x94\x93\x94.'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kingla/.conda/envs/dask-env/lib/python3.6/site-packages/distributed/worker.py", line 2415, in _maybe_deserialize_task
    function, args, kwargs = _deserialize(*self.tasks[key])
  File "/home/kingla/.conda/envs/dask-env/lib/python3.6/site-packages/distributed/worker.py", line 3248, in _deserialize
    function = loads_function(function)
  File "/home/kingla/.conda/envs/dask-env/lib/python3.6/site-packages/distributed/worker.py", line 3239, in loads_function
    result = pickle.loads(bytes_object)
  File "/home/kingla/.conda/envs/dask-env/lib/python3.6/site-packages/distributed/protocol/pickle.py", line 55, in loads
    return pickle.loads(x)
  File "/home/kingla/.conda/envs/dask-env/lib/python3.6/site-packages/dask/dataframe/__init__.py", line 2, in <module>
    from .core import (
  File "/home/kingla/.conda/envs/dask-env/lib/python3.6/site-packages/dask/dataframe/core.py", line 10, in <module>
    import pandas as pd
  File "/home/kingla/.conda/envs/dask-env/lib/python3.6/site-packages/pandas/__init__.py", line 193, in <module>
    if pandas.compat.PY37:
AttributeError: module 'pandas' has no attribute 'compat'
    asynchronous=asynchronous,
  File "/home/kingla/.conda/envs/dask-env/lib/python3.6/site-packages/distributed/client.py", line 780, in sync
    self.loop, func, *args, callback_timeout=callback_timeout, **kwargs
  File "/home/kingla/.conda/envs/dask-env/lib/python3.6/site-packages/distributed/utils.py", line 347, in sync
    raise exc.with_traceback(tb)
  File "/home/kingla/.conda/envs/dask-env/lib/python3.6/site-packages/distributed/utils.py", line 331, in f
    result[0] = yield future
  File "/home/kingla/.conda/envs/dask-env/lib/python3.6/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/home/kingla/.conda/envs/dask-env/lib/python3.6/site-packages/distributed/client.py", line 1790, in _gather
distributed.worker - WARNING - Could not deserialize task
Traceback (most recent call last):
  File "/home/kingla/.conda/envs/dask-env/lib/python3.6/site-packages/distributed/worker.py", line 3237, in loads_function
    result = cache_loads[bytes_object]
  File "/home/kingla/.conda/envs/dask-env/lib/python3.6/site-packages/distributed/utils.py", line 1497, in __getitem__
    value = super().__getitem__(key)
  File "/home/kingla/.conda/envs/dask-env/lib/python3.6/collections/__init__.py", line 993, in __getitem__
    raise KeyError(key)
KeyError: b'\x80\x04\x95,\x00\x00\x00\x00\x00\x00\x00\x8c\x13dask.dataframe.core\x94\x8c\x10_reduction_chunk\x94\x93\x94.'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kingla/.conda/envs/dask-env/lib/python3.6/site-packages/distributed/worker.py", line 2415, in _maybe_deserialize_task
    function, args, kwargs = _deserialize(*self.tasks[key])
  File "/home/kingla/.conda/envs/dask-env/lib/python3.6/site-packages/distributed/worker.py", line 3248, in _deserialize
    function = loads_function(function)
  File "/home/kingla/.conda/envs/dask-env/lib/python3.6/site-packages/distributed/worker.py", line 3239, in loads_function
    result = pickle.loads(bytes_object)
  File "/home/kingla/.conda/envs/dask-env/lib/python3.6/site-packages/distributed/protocol/pickle.py", line 55, in loads
    return pickle.loads(x)
  File "/home/kingla/.conda/envs/dask-env/lib/python3.6/site-packages/dask/dataframe/__init__.py", line 2, in <module>
    from .core import (
  File "/home/kingla/.conda/envs/dask-env/lib/python3.6/site-packages/dask/dataframe/core.py", line 10, in <module>
    import pandas as pd
  File "/home/kingla/.conda/envs/dask-env/lib/python3.6/site-packages/pandas/__init__.py", line 193, in <module>
    if pandas.compat.PY37:
AttributeError: module 'pandas' has no attribute 'compat'
    raise exception.with_traceback(traceback)
  File "/home/kingla/.conda/envs/dask-env/lib/python3.6/site-packages/dask/bag/core.py", line 2494, in to_dataframe
    import pandas as pd
  File "/home/kingla/.conda/envs/dask-env/lib/python3.6/site-packages/pandas/__init__.py", line 193, in <module>
    if pandas.compat.PY37:
AttributeError: module 'pandas' has no attribute 'compat'
>>> distributed.worker - WARNING - Could not deserialize task
Traceback (most recent call last):
  File "/home/kingla/.conda/envs/dask-env/lib/python3.6/site-packages/distributed/worker.py", line 3237, in loads_function
    result = cache_loads[bytes_object]
  File "/home/kingla/.conda/envs/dask-env/lib/python3.6/site-packages/distributed/utils.py", line 1497, in __getitem__
    value = super().__getitem__(key)
  File "/home/kingla/.conda/envs/dask-env/lib/python3.6/collections/__init__.py", line 993, in __getitem__
    raise KeyError(key)
KeyError: b'\x80\x04\x95\x00\x03\x00\x00\x00\x00\x00\x00\x8c\x11dask.optimization\x94\x8c\x10SubgraphCallable\x94\x93\x94(}\x94(\x8c-moment_chunk-c3e125aaf401a11909a96d4fad61a5c6\x94\x8c<getitem-values-moment_chunk-c3e125aaf401a11909a96d4fad61a5c6\x94h\x05(\x8c\ndask.utils\x94\x8c\x05apply\x94\x93\x94\x8c\tfunctools\x94\x8c\x07partial\x94\x93\x94\x8c\x15dask.array.reductions\x94\x8c\x0cmoment_chunk\x94\x93\x94\x85\x94R\x94(h\x0e)}\x94(\x8c\x03sum\x94\x8c\x05numpy\x94\x8c\x06nansum\x94\x93\x94\x8c\x05numel\x94h\x0c\x8c\x08nannumel\x94\x93\x94\x8c\x05dtype\x94h\x13\x8c\x05dtype\x94\x93\x94\x8c\x02f8\x94K\x00K\x01\x87\x94R\x94(K\x03\x8c\x01<\x94NNNJ\xff\xff\xff\xffJ\xff\xff\xff\xffK\x00t\x94buNt\x94b]\x94(h\x08\x8c\x13dask.dataframe.core\x94\x8c\x11apply_and_enforce\x94\x93\x94]\x94\x8c\t_operator\x94\x8c\x07getitem\x94\x93\x94\x8c\x02_1\x94\x8c\x02_2\x94\x87\x94a\x8c\x08builtins\x94\x8c\x04dict\x94\x93\x94]\x94(]\x94(\x8c\x05_func\x94\x8c\x16dask.dataframe.methods\x94\x8c\x06values\x94\x93\x94e]\x94(\x8c\x05_meta\x94\x8c\x15numpy.core.multiarray\x94\x8c\x0c_reconstruct\x94\x93\x94h\x13\x8c\x07ndarray\x94\x93\x94K\x00\x85\x94C\x01b\x94\x87\x94R\x94(K\x01K\x00K\x01\x86\x94h\x1b\x8c\x02i8\x94K\x00K\x01\x87\x94R\x94(K\x03h\x1fNNNJ\xff\xff\xff\xffJ\xff\xff\xff\xffK\x00t\x94b\x89C\x00\x94t\x94bee\x86\x94t\x94ah/]\x94(]\x94(\x8c\x04axis\x94h-\x8c\x05tuple\x94\x93\x94]\x94K\x00a\x86\x94e]\x94(\x8c\x08keepdims\x94\x88ee\x86\x94t\x94uh\x04\x8c\x02_0\x94\x8c\x02_1\x94\x8c\x02_2\x94\x87\x94\x8c\x11subgraph_callable\x94t\x94R\x94.'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kingla/.conda/envs/dask-env/lib/python3.6/site-packages/distributed/worker.py", line 2415, in _maybe_deserialize_task
    function, args, kwargs = _deserialize(*self.tasks[key])
  File "/home/kingla/.conda/envs/dask-env/lib/python3.6/site-packages/distributed/worker.py", line 3248, in _deserialize
    function = loads_function(function)
  File "/home/kingla/.conda/envs/dask-env/lib/python3.6/site-packages/distributed/worker.py", line 3239, in loads_function
    result = pickle.loads(bytes_object)
  File "/home/kingla/.conda/envs/dask-env/lib/python3.6/site-packages/distributed/protocol/pickle.py", line 55, in loads
    return pickle.loads(x)
  File "/home/kingla/.conda/envs/dask-env/lib/python3.6/site-packages/dask/dataframe/__init__.py", line 2, in <module>
    from .core import (
  File "/home/kingla/.conda/envs/dask-env/lib/python3.6/site-packages/dask/dataframe/core.py", line 10, in <module>
    import pandas as pd
  File "/home/kingla/.conda/envs/dask-env/lib/python3.6/site-packages/pandas/__init__.py", line 193, in <module>
    if pandas.compat.PY37:
AttributeError: module 'pandas' has no attribute 'compat'
distributed.worker - WARNING - Could not deserialize task
Traceback (most recent call last):
  File "/home/kingla/.conda/envs/dask-env/lib/python3.6/site-packages/distributed/worker.py", line 3237, in loads_function
    result = cache_loads[bytes_object]
  File "/home/kingla/.conda/envs/dask-env/lib/python3.6/site-packages/distributed/utils.py", line 1497, in __getitem__
    value = super().__getitem__(key)
  File "/home/kingla/.conda/envs/dask-env/lib/python3.6/collections/__init__.py", line 993, in __getitem__
    raise KeyError(key)
KeyError: b'\x80\x04\x95,\x00\x00\x00\x00\x00\x00\x00\x8c\x13dask.dataframe.core\x94\x8c\x10_reduction_chunk\x94\x93\x94.'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kingla/.conda/envs/dask-env/lib/python3.6/site-packages/distributed/worker.py", line 2415, in _maybe_deserialize_task
    function, args, kwargs = _deserialize(*self.tasks[key])
  File "/home/kingla/.conda/envs/dask-env/lib/python3.6/site-packages/distributed/worker.py", line 3248, in _deserialize
    function = loads_function(function)
  File "/home/kingla/.conda/envs/dask-env/lib/python3.6/site-packages/distributed/worker.py", line 3239, in loads_function
    result = pickle.loads(bytes_object)
  File "/home/kingla/.conda/envs/dask-env/lib/python3.6/site-packages/distributed/protocol/pickle.py", line 55, in loads
    return pickle.loads(x)
  File "/home/kingla/.conda/envs/dask-env/lib/python3.6/site-packages/dask/dataframe/__init__.py", line 2, in <module>
    from .core import (
  File "/home/kingla/.conda/envs/dask-env/lib/python3.6/site-packages/dask/dataframe/core.py", line 10, in <module>
    import pandas as pd
  File "/home/kingla/.conda/envs/dask-env/lib/python3.6/site-packages/pandas/__init__.py", line 193, in <module>
    if pandas.compat.PY37:
AttributeError: module 'pandas' has no attribute 'compat'
distributed.worker - WARNING - Could not deserialize task
Traceback (most recent call last):
  File "/home/kingla/.conda/envs/dask-env/lib/python3.6/site-packages/distributed/worker.py", line 3237, in loads_function
    result = cache_loads[bytes_object]
  File "/home/kingla/.conda/envs/dask-env/lib/python3.6/site-packages/distributed/utils.py", line 1497, in __getitem__
    value = super().__getitem__(key)
  File "/home/kingla/.conda/envs/dask-env/lib/python3.6/collections/__init__.py", line 993, in __getitem__
    raise KeyError(key)
KeyError: b'\x80\x04\x95,\x00\x00\x00\x00\x00\x00\x00\x8c\x13dask.dataframe.core\x94\x8c\x10_reduction_chunk\x94\x93\x94.'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kingla/.conda/envs/dask-env/lib/python3.6/site-packages/distributed/worker.py", line 2415, in _maybe_deserialize_task
    function, args, kwargs = _deserialize(*self.tasks[key])
  File "/home/kingla/.conda/envs/dask-env/lib/python3.6/site-packages/distributed/worker.py", line 3248, in _deserialize
    function = loads_function(function)
  File "/home/kingla/.conda/envs/dask-env/lib/python3.6/site-packages/distributed/worker.py", line 3239, in loads_function
    result = pickle.loads(bytes_object)
  File "/home/kingla/.conda/envs/dask-env/lib/python3.6/site-packages/distributed/protocol/pickle.py", line 55, in loads
    return pickle.loads(x)
  File "/home/kingla/.conda/envs/dask-env/lib/python3.6/site-packages/dask/dataframe/__init__.py", line 2, in <module>
    from .core import (
  File "/home/kingla/.conda/envs/dask-env/lib/python3.6/site-packages/dask/dataframe/core.py", line 10, in <module>
    import pandas as pd
  File "/home/kingla/.conda/envs/dask-env/lib/python3.6/site-packages/pandas/__init__.py", line 193, in <module>
    if pandas.compat.PY37:
AttributeError: module 'pandas' has no attribute 'compat'
```

**Comment by gforsyth** [comment]
Since you're already using a conda env, one workaround is to install `dask` using `conda` instead of `pip`

**Comment by HCelion** [comment]
That I did, but it messed up a whole lot of other stuff for the remote kernelling. But I guess it is more a pandas than a dask issue. If you want, you can close the issue.

**Comment by jrbourbeau** [comment]
Thanks for the feedback @HCelion!

**Comment by baasman** [comment]
By the way, I experienced this issue today, and downgrading Pandas to 0.24.2 solved the issue for me.
