### ISSUE TITLE
overlap.overlap fails with CuPy backed array and constant boundary

### ISSUE THREAD

**Issue by carterbox** [dask/dask#6162]
The dask array overlap function fails with CuPy backed arrays for constant boundaries. 

```python
import dask.array as da
import cupy as cp

a = da.random.uniform(0, 1, size=8, chunks=3)
b = a.map_blocks(cp.asarray)
for boundary in ['reflect', 'periodic', 'nearest', 'none', 0]:
    da.overlap.overlap(b, depth=1, boundary=boundary)
    print(boundary)
```
```
$ python overlap-bug.py 
reflect
periodic
nearest
none
Traceback (most recent call last):
  File "overlap-bug.py", line 9, in <module>
    da.overlap.overlap(b, depth=1, boundary=boundary)
  File "/home/dching/miniconda3/envs/dask/lib/python3.8/site-packages/dask/array/overlap.py", line 479, in overlap
    x2 = boundaries(x, depth2, boundary2)
  File "/home/dching/miniconda3/envs/dask/lib/python3.8/site-packages/dask/array/overlap.py", line 408, in boundaries
    x = constant(x, i, d, kind[i])
  File "/home/dching/miniconda3/envs/dask/lib/python3.8/site-packages/dask/array/overlap.py", line 366, in constant
    return concatenate([c, x, c], axis=axis)
  File "/home/dching/miniconda3/envs/dask/lib/python3.8/site-packages/dask/array/core.py", line 3467, in concatenate
    meta = np.concatenate([meta_from_array(s) for s in seq], axis=axis)
  File "<__array_function__ internals>", line 5, in concatenate
  File "cupy/core/core.pyx", line 1343, in cupy.core.core.ndarray.__array_function__
  File "/home/dching/miniconda3/envs/dask/lib/python3.8/site-packages/cupy/manipulation/join.py", line 54, in concatenate
    return core.concatenate_method(tup, axis)
  File "cupy/core/_routines_manipulation.pyx", line 577, in cupy.core._routines_manipulation.concatenate_method
  File "cupy/core/_routines_manipulation.pyx", line 590, in cupy.core._routines_manipulation.concatenate_method
TypeError: Only cupy arrays can be concatenated

```
Versions: `numpy==1.18.1 dask==2.15.0 cupy==7.3.0`

**Comment by mrocklin** [comment]
FYI @jakirkham in case you're interested

**Comment by jakirkham** [comment]
Yeah this is a known issue ( https://github.com/dask/dask/issues/4803#issuecomment-495666058 ). Though I guess it wasn't being tracked independently.

**Comment by pentschev** [comment]
I believe this is now resolved and this issue can be closed, see below.

```python
In [1]: import dask.array as da
   ...: import cupy as cp
   ...:
   ...: a = da.random.uniform(0, 1, size=8, chunks=3)
   ...: b = a.map_blocks(cp.asarray)
   ...: for boundary in ['reflect', 'periodic', 'nearest', 'none', 0]:
   ...:     da.overlap.overlap(b, depth=1, boundary=boundary)
   ...:     print(boundary)
   ...:
reflect
periodic
nearest
none
0
```

**Comment by jrbourbeau** [comment]
Thanks for following up @pentschev!
