### ISSUE TITLE
Dask crashes with certain masked arrays

### ISSUE THREAD

**Issue by cordawyn** [dask/dask#6168]
Hello!

I think I found an issue, but I'm not completely sure who's to blame: dask or numpy.
Here it is:

I'm trying to submit a simple computation using "dask.distributed" (local):

```python
future = client.submit(f, a)
```

and it crashes:

```text
Traceback (most recent call last):
  File "/home/cordawyn/projects/p1/venv/lib/python3.7/site-packages/numpy/ma/core.py", line 3150, in view
    if issubclass(dtype, ndarray):
TypeError: issubclass() arg 1 must be a class

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/cordawyn/projects/p1/venv/lib/python3.7/site-packages/dask/base.py", line 878, in normalize_array
    data = hash_buffer_hex(x.ravel(order="K").view("i1"))
  File "/home/cordawyn/projects/p1/venv/lib/python3.7/site-packages/numpy/ma/core.py", line 3156, in view
    output = ndarray.view(self, dtype)
  File "/home/cordawyn/projects/p1/venv/lib/python3.7/site-packages/numpy/ma/core.py", line 3375, in dtype
    self._mask.shape = self.shape
ValueError: cannot reshape array of size 1 into shape (8,)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/cordawyn/projects/p1/venv/lib/python3.7/site-packages/numpy/ma/core.py", line 3150, in view
    if issubclass(dtype, ndarray):
TypeError: issubclass() arg 1 must be a class

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/cordawyn/projects/p1/venv/lib/python3.7/site-packages/distributed/client.py", line 1487, in submit
    key = funcname(func) + "-" + tokenize(func, kwargs, *args)
  File "/home/cordawyn/projects/p1/venv/lib/python3.7/site-packages/dask/base.py", line 658, in tokenize
    return md5(str(tuple(map(normalize_token, args))).encode()).hexdigest()
  File "/home/cordawyn/projects/p1/venv/lib/python3.7/site-packages/dask/utils.py", line 506, in __call__
    return meth(arg, *args, **kwargs)
  File "/home/cordawyn/projects/p1/venv/lib/python3.7/site-packages/dask/base.py", line 880, in normalize_array
    data = hash_buffer_hex(x.copy().ravel(order="K").view("i1"))
  File "/home/cordawyn/projects/p1/venv/lib/python3.7/site-packages/numpy/ma/core.py", line 3156, in view
    output = ndarray.view(self, dtype)
  File "/home/cordawyn/projects/p1/venv/lib/python3.7/site-packages/numpy/ma/core.py", line 3375, in dtype
    self._mask.shape = self.shape
ValueError: cannot reshape array of size 1 into shape (8,)
```

I managed to reproduce it with minimum effort - it seems that this happens only when "a" is a masked array. But not just any masked array.

This masked array works fine:

```python
import numpy.ma as ma
a = ma.zeros(1)
a

# masked_array(data=[0.],
#              mask=False,
#        fill_value=1e+20)
```

but as soon as I "update" its mask:

```python
a.mask = False
a

# masked_array(data=[0.0],
#              mask=[False],
#        fill_value=1e+20)
```

... it makes Dask `client.submit` misbehave, as shown above.

I tracked the issue down to numpy's core (which Dask ends up calling):

```python
a = ma.zeros(1)
a.view('i1')

# masked_array(data=[0, 0, 0, 0, 0, 0, 0, 0],
             mask=False,
       fill_value=999999,
            dtype=int8)
```

```python
a = ma.zeros(1)
a.mask = False      # converts the mask from False to [False]
a.view('i1')

Traceback (most recent call last):
  File "/home/cordawyn/projects/p1/venv/lib/python3.7/site-packages/numpy/ma/core.py", line 3150, in view
    if issubclass(dtype, ndarray):
TypeError: issubclass() arg 1 must be a class

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/cordawyn/projects/p1/venv/lib/python3.7/site-packages/numpy/ma/core.py", line 3156, in view
    output = ndarray.view(self, dtype)
  File "/home/cordawyn/projects/p1/venv/lib/python3.7/site-packages/numpy/ma/core.py", line 3375, in dtype
    self._mask.shape = self.shape
ValueError: cannot reshape array of size 1 into shape (8,)
```

So it raises `ValueError`, as "documented" in the comments in `core.py`. But Dask does not catch `ValueError` in https://github.com/dask/dask/blob/666b53affac3ba475bd94c7ff4d29752bfa133de/dask/base.py#L880 (although it does it a bit earlier).

If numpy's exception is "valid", then we have a Dask bug. If not, it's probably numpy's. Numpy works a bit confusing in this particular case, so I'm not sure if it's really intended.

Testing environment:
Python: 3.7.3
Dask: 2.15.0 (also tested with 2.12.0)
Numpy: 1.18.3 (also tested with 1.18.1)

**Comment by jrbourbeau** [comment]
Thanks for raising an issue and providing some code snippets @cordawyn! As you pointed out, I'm able to reproduce `ValueError: cannot reshape array of size 1 into shape (8,)` with NumPy alone:

```python
In [1]: import numpy.ma as ma

In [2]: a = ma.zeros(1)
   ...: a.mask = False
   ...: a.view('i1')
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
~/miniforge3/envs/dask-dev/lib/python3.8/site-packages/numpy/ma/core.py in view(self, dtype, type, fill_value)
   3132             try:
-> 3133                 if issubclass(dtype, ndarray):
   3134                     output = ndarray.view(self, dtype)

TypeError: issubclass() arg 1 must be a class

During handling of the above exception, another exception occurred:

ValueError                                Traceback (most recent call last)
<ipython-input-2-62201ee087d5> in <module>
      1 a = ma.zeros(1)
      2 a.mask = False
----> 3 a.view('i1')

~/miniforge3/envs/dask-dev/lib/python3.8/site-packages/numpy/ma/core.py in view(self, dtype, type, fill_value)
   3137                     output = ndarray.view(self, dtype)
   3138             except TypeError:
-> 3139                 output = ndarray.view(self, dtype)
   3140         else:
   3141             output = ndarray.view(self, dtype, type)

~/miniforge3/envs/dask-dev/lib/python3.8/site-packages/numpy/ma/core.py in dtype(self, dtype)
   3357             # This raises a ValueError if the dtype change won't work.
   3358             try:
-> 3359                 self._mask.shape = self.shape
   3360             except (AttributeError, TypeError):
   3361                 pass

ValueError: cannot reshape array of size 1 into shape (8,)
```

If you're submitting the above code to Dask to execute I would also expect an error to be raised, though I may be missing something something about your use case. What is the function `f`?

**Comment by cordawyn** [comment]
Thanks for checking it out!

It doesn't matter what is behind this `f` function, because it doesn't even get to handling it. But if you really have to use anything, you can use:

```python
def f(x):
  return x
```

I hope this helps.

**Comment by jsignell** [comment]
I am able to reproduce raising the numpy error with:

```python
from dask.distributed import Client
client = Client()

import numpy.ma as ma
a = ma.zeros(1)
a.mask = False

def f(x):
    return x

future = client.submit(f, a)
```

So I think this is a pure numpy bug and dask is behaving correctly.
