### ISSUE TITLE
Repartition Dask bags: KeyError: 'bag-from-delayed-convert'

### ISSUE THREAD

**Issue by roganov** [dask/dask#6184]
Hello,

I'm trying to repartition a set of big json files (14 files, 2.8GB each) to smaller files to make them more manageable.

```python
import ujson

import dask.bag as db
from dask.distributed import Client, progress


if __name__ == '__main__':
   client = Client(n_workers=3, threads_per_worker=1)
   df = db.read_text('data/*.jsonl').repartition(14 * 8).to_textfiles('data/partitioned_*.jsonl')
```

Dask throws an exception:
```
tornado.application - ERROR - Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOLoop object at 0x10453df50>>, <Task finished coro=<_needs_document_lock.<locals>._needs_document_lock_wrapper() done, defined at /Users/yroganov/PycharmProjects/remap-elastic/venv/lib/python3.7/site-packages/bokeh/server/session.py:51> exception=KeyError('bag-from-delayed-convert')>)
Traceback (most recent call last):
  File "/Users/yroganov/PycharmProjects/remap-elastic/venv/lib/python3.7/site-packages/tornado/ioloop.py", line 743, in _run_callback
    ret = callback()
  File "/Users/yroganov/PycharmProjects/remap-elastic/venv/lib/python3.7/site-packages/tornado/ioloop.py", line 767, in _discard_future_result
    future.result()
  File "/Users/yroganov/PycharmProjects/remap-elastic/venv/lib/python3.7/site-packages/bokeh/server/session.py", line 67, in _needs_document_lock_wrapper
    result = func(self, *args, **kwargs)
  File "/Users/yroganov/PycharmProjects/remap-elastic/venv/lib/python3.7/site-packages/bokeh/server/session.py", line 195, in with_document_locked
    return func(*args, **kwargs)
  File "/Users/yroganov/PycharmProjects/remap-elastic/venv/lib/python3.7/site-packages/bokeh/document/document.py", line 1164, in wrapper
    return doc._with_self_as_curdoc(invoke)
  File "/Users/yroganov/PycharmProjects/remap-elastic/venv/lib/python3.7/site-packages/bokeh/document/document.py", line 1150, in _with_self_as_curdoc
    return f()
  File "/Users/yroganov/PycharmProjects/remap-elastic/venv/lib/python3.7/site-packages/bokeh/document/document.py", line 1163, in invoke
    return f(*args, **kwargs)
  File "/Users/yroganov/PycharmProjects/remap-elastic/venv/lib/python3.7/site-packages/bokeh/document/document.py", line 953, in remove_then_invoke
    return callback(*args, **kwargs)
  File "/Users/yroganov/PycharmProjects/remap-elastic/venv/lib/python3.7/site-packages/distributed/dashboard/components/shared.py", line 333, in <lambda>
    self.doc().add_next_tick_callback(lambda: self.update(prof, metadata))
  File "/Users/yroganov/PycharmProjects/remap-elastic/venv/lib/python3.7/site-packages/bokeh/core/property/validation.py", line 93, in func
    return input_function(*args, **kwargs)
  File "/Users/yroganov/PycharmProjects/remap-elastic/venv/lib/python3.7/site-packages/distributed/dashboard/components/shared.py", line 312, in update
    ts = metadata["keys"][self.key]
KeyError: 'bag-from-delayed-convert'
```

Dask version: `dask==2.15.0`

**Comment by jcrist** [comment]
Hi @roganov. Could you provide a [minimal, reproducible example](https://blog.dask.org/2018/02/28/minimal-bug-reports)? Without something we can run locally, there's not much we can do to help debug.

**Comment by martindurant** [comment]
@roganov : I suggest that you use [`map_partitions`](https://docs.dask.org/en/latest/bag-api.html#dask.bag.map_partitions) to do the work *per input file*. Indeed, this being a strictly IO-bound process, Dask will probably not do any better than a simple python loop would.

Closing this issue as lacking detail. Please reopen if you can provide a complete reproducible example.
