### ISSUE TITLE
Incorrect error message in .str.split method when expand=True

### ISSUE THREAD

**Issue by galipremsagar** [dask/dask#6191]
When calling `.str.split` with `expand=True`, with no `n` value given dask errors saying `... specify the number of expected output columns with the n..`

This is actually incorrect with respect to what `n` is actually accomplishing. `n` is actually accomplishing the task of taking number of splits.

Minimal reproducer:

```python
>>> import dask.dataframe as dd
>>> import pandas as pd
>>> df = pd.DataFrame({    "a":["this is", "this is"]})
>>> ddf = dd.from_pandas(df, 1)
>>> ddf.a.str.split(" ", expand=True)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/cudf/dask/dask/dataframe/accessor.py", line 125, in split
    "To use the expand parameter you must specify the number of "
NotImplementedError: To use the expand parameter you must specify the number of expected output columns with the n= parameter
>>> ddf.a.str.split(" ", expand=True,n=1).compute()
      0   1
0  this  is
1  this  is
>>> 
```

In the above example, `n=1` denotes `1 split` which is equivalent to 2 columns.

**Comment by galipremsagar** [comment]
I'm making this fix alongside few other changes in `split`
