### ISSUE TITLE
Sliceable dask.delayed() a.k.a. pushdown of slicing operator on arrays?

### ISSUE THREAD

**Issue by Hoeze** [dask/dask#6288]
Hi, is there something like a sliceable dask.delayed?

I would like to use dask.delayed on a sparse TileDB array like described here:
https://docs.tiledb.com/dask/tiledb-with-dask-delayed

Due to the sparse nature of my array (shape is `[3x10^9, 3x10^9, 7000]`), dividing the dataset into separate chunks and loading them into memory is quite wasteful to impossible.
Instead, I would like to make use of the fancy slicing capabilities of TileDB.

Is it possible to have a custom Dask array that pushes down slicing to the underlying array?

**Comment by jsignell** [comment]
I am not quite sure I understand your question. It'd help to have a reproducible example. Can you replace tbd with a numpy array that looks like your tiledb object?

**Comment by Hoeze** [comment]
OK, maybe this example shows my problem better.

The query:
```python
dask.array.zeros(200000000000, chunks=(100000000000,))[:10000000000][:1000][:10].compute()
```
Expected result:
```python
array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])
```
Actual result:
```python
Traceback (most recent call last):
  File "/opt/anaconda/envs/kipoi/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3331, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-18-3411c0606a9e>", line 1, in <module>
    dask.array.zeros(200000000000, chunks=(100000000000,))[:10000000000][:1000][:10].compute()
  File "/opt/anaconda/envs/def/lib/python3.7/site-packages/dask/base.py", line 166, in compute
    (result,) = compute(self, traverse=False, **kwargs)
  File "/opt/anaconda/envs/def/lib/python3.7/site-packages/dask/base.py", line 444, in compute
    results = schedule(dsk, keys, **kwargs)
  File "/opt/anaconda/envs/def/lib/python3.7/site-packages/dask/threaded.py", line 84, in get
    **kwargs
  File "/opt/anaconda/envs/def/lib/python3.7/site-packages/dask/local.py", line 486, in get_async
    raise_exception(exc, tb)
  File "/opt/anaconda/envs/def/lib/python3.7/site-packages/dask/local.py", line 316, in reraise
    raise exc
  File "/opt/anaconda/envs/def/lib/python3.7/site-packages/dask/local.py", line 222, in execute_task
    result = _execute_task(task, data)
  File "/opt/anaconda/envs/def/lib/python3.7/site-packages/dask/core.py", line 121, in _execute_task
    return func(*(_execute_task(a, cache) for a in args))
  File "/opt/anaconda/envs/def/lib/python3.7/site-packages/dask/core.py", line 121, in <genexpr>
    return func(*(_execute_task(a, cache) for a in args))
  File "/opt/anaconda/envs/def/lib/python3.7/site-packages/dask/core.py", line 121, in _execute_task
    return func(*(_execute_task(a, cache) for a in args))
MemoryError: Unable to allocate array with shape (100000000000,) and data type float64
```

**Comment by TomAugspurger** [comment]
> or would it pass the slicing operator down to the underlying array?

Nope, we don't do predicate pushdown yet. This is one of the goals mentioned in https://github.com/dask/dask/issues/5644.

**Comment by Hoeze** [comment]
Thank you for your answer @TomAugspurger .

Is there an easy way to hack the slicing operator, e.g. by inheriting from Dask array?
This way, I could create an ArrayView that caches all slicing operations instead of materializing them.

**Comment by TomAugspurger** [comment]
I'm not sure, but that sounds somewhat difficult.

I'm not familiar with tiledb, but you might be able to construct smaller
chunks by using tiledb operations to do the filtering before it gets to
Dask data? Or perhaps your initial tasks could include the slicing?

**Comment by fjetter** [comment]
> I'm not sure how feasible this is, but I figured I'd open this issue for discussion anyway.

We're lately looking again into https://github.com/dask/dask/issues/7933 and I expect us to push on this in the next couple of weeks/months. Part of this effort is to enable logical graph rewrites as you are suggesting here.
