### ISSUE TITLE
test_thread_safety is flaky

### ISSUE THREAD

**Issue by QuLogic** [dask/dask#6297]
**What happened**:

When build the Fedora dask package, this test will sometimes just not work:

```pytb
______________________________ test_thread_safety ______________________________
[gw46] linux -- Python 3.8.3 /usr/bin/python3
    def test_thread_safety():
        def f(x):
            return 1
    
        dsk = {"x": (sleep, 0.05), "y": (f, "x")}
    
        L = []
    
        def test_f():
            L.append(get(dsk, "y"))
    
        threads = []
        for i in range(20):
            t = threading.Thread(target=test_f)
            t.daemon = True
            t.start()
            threads.append(t)
    
        for thread in threads:
            thread.join()
    
>       assert L == [1] * 20
E       assert [1, 1, 1, 1, 1] == [1, 1, 1, 1, 1, 1, ...]
E         Right contains 15 more items, first extra item: 1
E         Use -v to get the full diff
dask/tests/test_threaded.py:147: AssertionError
```
<details>
<summary>Captured stderr call</summary>
```
Exception in thread Thread-114:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 212, in __init__
    self._repopulate_pool()
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 303, in _repopulate_pool
    return self._repopulate_pool_static(self._ctx, self.Process,
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 326, in _repopulate_pool_static
    w.start()
  File "/usr/lib/python3.8/multiprocessing/dummy/__init__.py", line 51, in start
    threading.Thread.start(self)
  File "/usr/lib/python3.8/threading.py", line 852, in start
    _start_new_thread(self._bootstrap, ())
RuntimeError: can't start new thread
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/builddir/build/BUILD/dask-2.18.0/dask/tests/test_threaded.py", line 135, in test_f
    L.append(get(dsk, "y"))
  File "/builddir/build/BUILD/dask-2.18.0/dask/threaded.py", line 72, in get
    pool = ThreadPool(num_workers)
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 925, in __init__
    Pool.__init__(self, processes, initializer, initargs)
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 216, in __init__
    p.terminate()
AttributeError: 'DummyProcess' object has no attribute 'terminate'
Exception in thread Thread-116:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 212, in __init__
    self._repopulate_pool()
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 303, in _repopulate_pool
    return self._repopulate_pool_static(self._ctx, self.Process,
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 326, in _repopulate_pool_static
    w.start()
  File "/usr/lib/python3.8/multiprocessing/dummy/__init__.py", line 51, in start
    threading.Thread.start(self)
  File "/usr/lib/python3.8/threading.py", line 852, in start
    _start_new_thread(self._bootstrap, ())
RuntimeError: can't start new thread
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/builddir/build/BUILD/dask-2.18.0/dask/tests/test_threaded.py", line 135, in test_f
    L.append(get(dsk, "y"))
  File "/builddir/build/BUILD/dask-2.18.0/dask/threaded.py", line 72, in get
    pool = ThreadPool(num_workers)
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 925, in __init__
    Pool.__init__(self, processes, initializer, initargs)
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 216, in __init__
    p.terminate()
AttributeError: 'DummyProcess' object has no attribute 'terminate'
Exception in thread Thread-118:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 212, in __init__
    self._repopulate_pool()
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 303, in _repopulate_pool
    return self._repopulate_pool_static(self._ctx, self.Process,
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 326, in _repopulate_pool_static
    w.start()
  File "/usr/lib/python3.8/multiprocessing/dummy/__init__.py", line 51, in start
    threading.Thread.start(self)
  File "/usr/lib/python3.8/threading.py", line 852, in start
    _start_new_thread(self._bootstrap, ())
RuntimeError: can't start new thread
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/builddir/build/BUILD/dask-2.18.0/dask/tests/test_threaded.py", line 135, in test_f
    L.append(get(dsk, "y"))
  File "/builddir/build/BUILD/dask-2.18.0/dask/threaded.py", line 72, in get
    pool = ThreadPool(num_workers)
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 925, in __init__
    Pool.__init__(self, processes, initializer, initargs)
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 216, in __init__
    p.terminate()
AttributeError: 'DummyProcess' object has no attribute 'terminate'
Exception in thread Thread-119:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 212, in __init__
    self._repopulate_pool()
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 303, in _repopulate_pool
    return self._repopulate_pool_static(self._ctx, self.Process,
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 326, in _repopulate_pool_static
    w.start()
  File "/usr/lib/python3.8/multiprocessing/dummy/__init__.py", line 51, in start
    threading.Thread.start(self)
  File "/usr/lib/python3.8/threading.py", line 852, in start
    _start_new_thread(self._bootstrap, ())
RuntimeError: can't start new thread
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/builddir/build/BUILD/dask-2.18.0/dask/tests/test_threaded.py", line 135, in test_f
    L.append(get(dsk, "y"))
  File "/builddir/build/BUILD/dask-2.18.0/dask/threaded.py", line 72, in get
    pool = ThreadPool(num_workers)
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 925, in __init__
    Pool.__init__(self, processes, initializer, initargs)
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 216, in __init__
    p.terminate()
AttributeError: 'DummyProcess' object has no attribute 'terminate'
Exception in thread Thread-120:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 212, in __init__
    self._repopulate_pool()
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 303, in _repopulate_pool
    return self._repopulate_pool_static(self._ctx, self.Process,
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 326, in _repopulate_pool_static
    w.start()
  File "/usr/lib/python3.8/multiprocessing/dummy/__init__.py", line 51, in start
    threading.Thread.start(self)
  File "/usr/lib/python3.8/threading.py", line 852, in start
    Exception in thread Thread-121:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/builddir/build/BUILD/dask-2.18.0/dask/tests/test_threaded.py", line 135, in test_f
    L.append(get(dsk, "y"))
  File "/builddir/build/BUILD/dask-2.18.0/dask/threaded.py", line 72, in get
    pool = ThreadPool(num_workers)
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 925, in __init__
    Pool.__init__(self, processes, initializer, initargs)
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 212, in __init__
    self._repopulate_pool()
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 303, in _repopulate_pool
    return self._repopulate_pool_static(self._ctx, self.Process,
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 326, in _repopulate_pool_static
    w.start()
  File "/usr/lib/python3.8/multiprocessing/dummy/__init__.py", line 51, in start
    threading.Thread.start(self)
  File "/usr/lib/python3.8/threading.py", line 852, in start
    _start_new_thread(self._bootstrap, ())
RuntimeError: can't start new thread
_start_new_thread(self._bootstrap, ())
RuntimeError: can't start new thread
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/builddir/build/BUILD/dask-2.18.0/dask/tests/test_threaded.py", line 135, in test_f
    L.append(get(dsk, "y"))
  File "/builddir/build/BUILD/dask-2.18.0/dask/threaded.py", line 72, in get
    pool = ThreadPool(num_workers)
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 925, in __init__
    Pool.__init__(self, processes, initializer, initargs)
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 216, in __init__
    p.terminate()
AttributeError: 'DummyProcess' object has no attribute 'terminate'
Exception in thread Thread-122:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 212, in __init__
    self._repopulate_pool()
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 303, in _repopulate_pool
    return self._repopulate_pool_static(self._ctx, self.Process,
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 326, in _repopulate_pool_static
    w.start()
  File "/usr/lib/python3.8/multiprocessing/dummy/__init__.py", line 51, in start
    threading.Thread.start(self)
  File "/usr/lib/python3.8/threading.py", line 852, in start
    _start_new_thread(self._bootstrap, ())
RuntimeError: can't start new thread
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/builddir/build/BUILD/dask-2.18.0/dask/tests/test_threaded.py", line 135, in test_f
    L.append(get(dsk, "y"))
  File "/builddir/build/BUILD/dask-2.18.0/dask/threaded.py", line 72, in get
    pool = ThreadPool(num_workers)
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 925, in __init__
    Pool.__init__(self, processes, initializer, initargs)
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 216, in __init__
    p.terminate()
AttributeError: 'DummyProcess' object has no attribute 'terminate'
Exception in thread Thread-123:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 212, in __init__
    self._repopulate_pool()
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 303, in _repopulate_pool
    return self._repopulate_pool_static(self._ctx, self.Process,
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 326, in _repopulate_pool_static
    w.start()
  File "/usr/lib/python3.8/multiprocessing/dummy/__init__.py", line 51, in start
    threading.Thread.start(self)
  File "/usr/lib/python3.8/threading.py", line 852, in start
    _start_new_thread(self._bootstrap, ())
RuntimeError: can't start new thread
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/builddir/build/BUILD/dask-2.18.0/dask/tests/test_threaded.py", line 135, in test_f
    L.append(get(dsk, "y"))
  File "/builddir/build/BUILD/dask-2.18.0/dask/threaded.py", line 72, in get
    pool = ThreadPool(num_workers)
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 925, in __init__
    Pool.__init__(self, processes, initializer, initargs)
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 216, in __init__
    p.terminate()
AttributeError: 'DummyProcess' object has no attribute 'terminate'
Exception in thread Thread-124:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 212, in __init__
    self._repopulate_pool()
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 303, in _repopulate_pool
    return self._repopulate_pool_static(self._ctx, self.Process,
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 326, in _repopulate_pool_static
    w.start()
  File "/usr/lib/python3.8/multiprocessing/dummy/__init__.py", line 51, in start
    threading.Thread.start(self)
  File "/usr/lib/python3.8/threading.py", line 852, in start
    _start_new_thread(self._bootstrap, ())
RuntimeError: can't start new thread
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/builddir/build/BUILD/dask-2.18.0/dask/tests/test_threaded.py", line 135, in test_f
    L.append(get(dsk, "y"))
  File "/builddir/build/BUILD/dask-2.18.0/dask/threaded.py", line 72, in get
    pool = ThreadPool(num_workers)
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 925, in __init__
    Pool.__init__(self, processes, initializer, initargs)
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 216, in __init__
    p.terminate()
AttributeError: 'DummyProcess' object has no attribute 'terminate'
Exception in thread Thread-125:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 212, in __init__
    self._repopulate_pool()
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 303, in _repopulate_pool
    return self._repopulate_pool_static(self._ctx, self.Process,
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 326, in _repopulate_pool_static
    w.start()
  File "/usr/lib/python3.8/multiprocessing/dummy/__init__.py", line 51, in start
    threading.Thread.start(self)
  File "/usr/lib/python3.8/threading.py", line 852, in start
    _start_new_thread(self._bootstrap, ())
RuntimeError: can't start new thread
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/builddir/build/BUILD/dask-2.18.0/dask/tests/test_threaded.py", line 135, in test_f
    L.append(get(dsk, "y"))
  File "/builddir/build/BUILD/dask-2.18.0/dask/threaded.py", line 72, in get
    pool = ThreadPool(num_workers)
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 925, in __init__
    Pool.__init__(self, processes, initializer, initargs)
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 216, in __init__
    p.terminate()
AttributeError: 'DummyProcess' object has no attribute 'terminate'
Exception in thread Thread-126:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 212, in __init__
    self._repopulate_pool()
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 303, in _repopulate_pool
    return self._repopulate_pool_static(self._ctx, self.Process,
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 326, in _repopulate_pool_static
    w.start()
  File "/usr/lib/python3.8/multiprocessing/dummy/__init__.py", line 51, in start
    threading.Thread.start(self)
  File "/usr/lib/python3.8/threading.py", line 852, in start
    _start_new_thread(self._bootstrap, ())
RuntimeError: can't start new thread
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/builddir/build/BUILD/dask-2.18.0/dask/tests/test_threaded.py", line 135, in test_f
    L.append(get(dsk, "y"))
  File "/builddir/build/BUILD/dask-2.18.0/dask/threaded.py", line 72, in get
    pool = ThreadPool(num_workers)
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 925, in __init__
    Pool.__init__(self, processes, initializer, initargs)
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 216, in __init__
    p.terminate()
AttributeError: 'DummyProcess' object has no attribute 'terminate'
Exception in thread Thread-127:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 212, in __init__
    self._repopulate_pool()
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 303, in _repopulate_pool
    return self._repopulate_pool_static(self._ctx, self.Process,
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 326, in _repopulate_pool_static
    w.start()
  File "/usr/lib/python3.8/multiprocessing/dummy/__init__.py", line 51, in start
    threading.Thread.start(self)
  File "/usr/lib/python3.8/threading.py", line 852, in start
    _start_new_thread(self._bootstrap, ())
RuntimeError: can't start new thread
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/builddir/build/BUILD/dask-2.18.0/dask/tests/test_threaded.py", line 135, in test_f
    L.append(get(dsk, "y"))
  File "/builddir/build/BUILD/dask-2.18.0/dask/threaded.py", line 72, in get
    pool = ThreadPool(num_workers)
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 925, in __init__
    Pool.__init__(self, processes, initializer, initargs)
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 216, in __init__
    p.terminate()
AttributeError: 'DummyProcess' object has no attribute 'terminate'
Exception in thread Thread-128:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 212, in __init__
    self._repopulate_pool()
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 303, in _repopulate_pool
    return self._repopulate_pool_static(self._ctx, self.Process,
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 326, in _repopulate_pool_static
    w.start()
  File "/usr/lib/python3.8/multiprocessing/dummy/__init__.py", line 51, in start
    threading.Thread.start(self)
  File "/usr/lib/python3.8/threading.py", line 852, in start
    _start_new_thread(self._bootstrap, ())
RuntimeError: can't start new thread
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/builddir/build/BUILD/dask-2.18.0/dask/tests/test_threaded.py", line 135, in test_f
    L.append(get(dsk, "y"))
  File "/builddir/build/BUILD/dask-2.18.0/dask/threaded.py", line 72, in get
    pool = ThreadPool(num_workers)
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 925, in __init__
    Pool.__init__(self, processes, initializer, initargs)
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 216, in __init__
    p.terminate()
AttributeError: 'DummyProcess' object has no attribute 'terminate'
Exception in thread Thread-129:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 212, in __init__
    self._repopulate_pool()
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 303, in _repopulate_pool
    return self._repopulate_pool_static(self._ctx, self.Process,
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 326, in _repopulate_pool_static
    w.start()
  File "/usr/lib/python3.8/multiprocessing/dummy/__init__.py", line 51, in start
    threading.Thread.start(self)
  File "/usr/lib/python3.8/threading.py", line 852, in start
    _start_new_thread(self._bootstrap, ())
RuntimeError: can't start new thread
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/builddir/build/BUILD/dask-2.18.0/dask/tests/test_threaded.py", line 135, in test_f
    L.append(get(dsk, "y"))
  File "/builddir/build/BUILD/dask-2.18.0/dask/threaded.py", line 72, in get
    pool = ThreadPool(num_workers)
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 925, in __init__
    Pool.__init__(self, processes, initializer, initargs)
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 216, in __init__
    p.terminate()
AttributeError: 'DummyProcess' object has no attribute 'terminate'
Exception in thread Thread-130:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 212, in __init__
    self._repopulate_pool()
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 303, in _repopulate_pool
    return self._repopulate_pool_static(self._ctx, self.Process,
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 326, in _repopulate_pool_static
    w.start()
  File "/usr/lib/python3.8/multiprocessing/dummy/__init__.py", line 51, in start
    threading.Thread.start(self)
  File "/usr/lib/python3.8/threading.py", line 852, in start
    _start_new_thread(self._bootstrap, ())
RuntimeError: can't start new thread
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/builddir/build/BUILD/dask-2.18.0/dask/tests/test_threaded.py", line 135, in test_f
    L.append(get(dsk, "y"))
  File "/builddir/build/BUILD/dask-2.18.0/dask/threaded.py", line 72, in get
    pool = ThreadPool(num_workers)
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 925, in __init__
    Pool.__init__(self, processes, initializer, initargs)
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 216, in __init__
    p.terminate()
AttributeError: 'DummyProcess' object has no attribute 'terminate'
```
</details>

**What you expected to happen**:

Tests pass.

**Minimal Complete Verifiable Example**:

`$ python3 -m pytest -m 'not network' -n auto`

**Environment**:

- Dask version: 2.18.0
- Python version: 3.8.3
- Operating System: Fedora 32
- Install method (conda, pip, source): building from source

[Build log](https://koji.fedoraproject.org/koji/taskinfo?taskID=45527098)

**Comment by TomAugspurger** [comment]
Thanks. I don't recall seeing that fail on our CI recently, though I haven't been watching closely. Do you know roughly what percent of the time it fails? I'm not able to reproduce with `pytest-repeat` and `pytest dask/tests/test_threaded.py::test_thread_safety --count=1000` using Python 3.7 on MacOS.

**Comment by TomAugspurger** [comment]
Hmm thanks. I haven't ever seen it fail on our CI so if you're able to provide additional details they'd be more than welcome.

**Comment by martindurant** [comment]
Suggest to close, unless this is still happening and we can get more information @QuLogic

**Comment by QuLogic** [comment]
Well, I've not seen this happen with any recent releases.
