### ISSUE TITLE
Write to csv fails - TypeError: tuple indices must be integers or slices, not tuple

### ISSUE THREAD

**Issue by JmeCS** [dask/dask#6375]
**What happened**:
I have a large dataset comprised of multiple csv files. I need to read the data, shuffle, and write new csv files of equal size into train/test folders. When calling `.to_csv()` On the new dataframe, the process fails with the following error:

`TypeError: tuple indices must be integers or slices, not tuple`

**What you expected to happen**:
Write to a series of .csv files.

**Minimal Complete Verifiable Example**:
This is not MCVE, but it's the best I can do:

```python
# df is a dask dataframe
arr = df.to_dask_array(True)
nrows = arr.shape[0]
np.random.seed(42)
idx = np.random.choice(nrows, nrows, replace=False)
arr = shuffle_slice(arr, idx)

data = arr.to_dask_dataframe(df.columns)

data = data.repartition(npartitions=30)
data.index = data.index.astype(int)
data.to_csv('data_*.csv', index=False)
```
**Anything else we need to know?**:
I've confirmed that the index type on the dataframe is `int`. I've also tried changing the datatype. It's certainly not a tuple. Full error message:

```
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/Users/jameysmith/opt/miniconda3/envs/he-mlpipeline/lib/python3.7/site-packages/dask/dataframe/core.py", line 1408, in to_csv
    return to_csv(self, filename, **kwargs)
  File "/Users/jameysmith/opt/miniconda3/envs/he-mlpipeline/lib/python3.7/site-packages/dask/dataframe/io/csv.py", line 823, in to_csv
    delayed(values).compute(**compute_kwargs)
  File "/Users/jameysmith/opt/miniconda3/envs/he-mlpipeline/lib/python3.7/site-packages/dask/base.py", line 166, in compute
    (result,) = compute(self, traverse=False, **kwargs)
  File "/Users/jameysmith/opt/miniconda3/envs/he-mlpipeline/lib/python3.7/site-packages/dask/base.py", line 444, in compute
    results = schedule(dsk, keys, **kwargs)
  File "/Users/jameysmith/opt/miniconda3/envs/he-mlpipeline/lib/python3.7/site-packages/dask/threaded.py", line 84, in get
    **kwargs
  File "/Users/jameysmith/opt/miniconda3/envs/he-mlpipeline/lib/python3.7/site-packages/dask/local.py", line 486, in get_async
    raise_exception(exc, tb)
  File "/Users/jameysmith/opt/miniconda3/envs/he-mlpipeline/lib/python3.7/site-packages/dask/local.py", line 316, in reraise
    raise exc
  File "/Users/jameysmith/opt/miniconda3/envs/he-mlpipeline/lib/python3.7/site-packages/dask/local.py", line 222, in execute_task
    result = _execute_task(task, data)
  File "/Users/jameysmith/opt/miniconda3/envs/he-mlpipeline/lib/python3.7/site-packages/dask/core.py", line 121, in _execute_task
    return func(*(_execute_task(a, cache) for a in args))
  File "/Users/jameysmith/opt/miniconda3/envs/he-mlpipeline/lib/python3.7/site-packages/dask/core.py", line 121, in <genexpr>
    return func(*(_execute_task(a, cache) for a in args))
  File "/Users/jameysmith/opt/miniconda3/envs/he-mlpipeline/lib/python3.7/site-packages/dask/core.py", line 121, in _execute_task
    return func(*(_execute_task(a, cache) for a in args))
TypeError: tuple indices must be integers or slices, not tuple
```

**Environment**:

- Dask version: 2.18.1
- Python version: 3.7
- Operating System: macOS
- Install method (conda, pip, source): Conda

**Comment by quasiben** [comment]
I tried with latest dask and was not able to reproduce the bug.  Note in the example below I am using `dask.datasets.timeseries()` for the dataframe.  

```python
In [1]: import dask
im
In [2]: import numpy as np

In [3]: df = dask.datasets.timeseries()

In [4]: from dask.array.slicing import shuffle_slice

In [5]: arr = df.to_dask_array(True)
   ...: nrows = arr.shape[0]
   ...: np.random.seed(42)
   ...: idx = np.random.choice(nrows, nrows, replace=False)
   ...: arr = shuffle_slice(arr, idx)

In [6]: data = arr.to_dask_dataframe(df.columns)
   ...:
```

**Comment by JmeCS** [comment]
Any advice on how to debug? I've upgraded everything to the latest version and the problem is still persisting. It's 

It's especially strange because now it appears that it's only certain partitions that throw the error. For example, if I do:

```
data = df.repartition(npartitions=30)
pdf = data.partitions[3].compute()
```

everything seems to work. Other partitions (e.g. 29) throw the type error. Again, I've very confident that there is nothing wrong with the index type in the data.

**Comment by quasiben** [comment]
Some thing you can try:

- Build a reproducible example with dask.datasets ? 
- write to csv before any manipulation -> read_csv then immediately write_csv

**Comment by jsignell** [comment]
I am going to close this since there has been no activity in some time and the problem isn't reproducible. @JmeCS please report back/reopen if you figure out what was going on.
