### ISSUE TITLE
Dashboard worker tab, 500 internal server error

### ISSUE THREAD

**Issue by rcthomas** [dask/dask#6452]
**What happened**:

Launched a Dask cluster using `dask-mpi.`  Connecting to it from a Jupyter notebook, I note that the client reports `Memory: 0 B`.  The workflow is fine, but the dashboard worker tab returns 500 internal server error.  The logs show that the problem is a `ZeroDivisionError`:

```
File "/usr/local/lib/python3.7/dist-packages/distributed/dashboard/components/scheduler.py", line 1947, in update
    ) / sum(ws.memory_limit for ws in self.scheduler.workers.values())
ZeroDivisionError: division by zero
```

**What you expected to happen**:

Worker tab with lovingly rendered worker information, not 500 Internal Server Error message of cold indifference. :)

**Minimal Complete Verifiable Example**:

This is happening in a supercomputer deployment.  I can try to replicate the setup at least with a `docker-compose` setup if necessary.  Or if debugging in situ would help, we could talk access, but I'm guessing the 0 B and traceback may be enough to track things down.

**Anything else we need to know?**:

Full error log/traceback:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/distributed/utils.py", line 656, in log_errors
    yield
  File "/usr/local/lib/python3.7/dist-packages/distributed/dashboard/components/scheduler.py", line 2022, in workers_doc
    table.update()
  File "/usr/local/lib/python3.7/dist-packages/bokeh/core/property/validation.py", line 93, in func
    return input_function(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/distributed/dashboard/components/scheduler.py", line 1947, in update
    ) / sum(ws.memory_limit for ws in self.scheduler.workers.values())
ZeroDivisionError: division by zero
tornado.application - ERROR - Uncaught exception GET /workers (10.128.255.219)
HTTPServerRequest(protocol='http', host='jupyter.nersc.gov', method='GET', uri='/workers', version='HTTP/1.1', remote_ip='10.128.255.219')
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/tornado/web.py", line 1703, in _execute
    result = await result
  File "/usr/local/lib/python3.7/dist-packages/bokeh/server/views/doc_handler.py", line 52, in get
    session = await self.get_session()
  File "/usr/local/lib/python3.7/dist-packages/bokeh/server/views/session_handler.py", line 120, in get_session
    session = await self.application_context.create_session_if_needed(session_id, self.request, token)
  File "/usr/local/lib/python3.7/dist-packages/bokeh/server/contexts.py", line 218, in create_session_if_needed
    self._application.initialize_document(doc)
  File "/usr/local/lib/python3.7/dist-packages/bokeh/application/application.py", line 171, in initialize_document
    h.modify_document(doc)
  File "/usr/local/lib/python3.7/dist-packages/bokeh/application/handlers/function.py", line 132, in modify_document
    self._func(doc)
  File "/usr/local/lib/python3.7/dist-packages/distributed/dashboard/components/scheduler.py", line 2022, in workers_doc
    table.update()
  File "/usr/local/lib/python3.7/dist-packages/bokeh/core/property/validation.py", line 93, in func
    return input_function(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/distributed/dashboard/components/scheduler.py", line 1947, in update
    ) / sum(ws.memory_limit for ws in self.scheduler.workers.values())
ZeroDivisionError: division by zero
```

**Environment**:

- Dask version: 2.21.0
- Python version: 3.7.3
- Operating System: Debian 10.4 in Docker
- Install method (conda, pip, source): pip

Full pip freeze:

```
asn1crypto==0.24.0
astropy==4.0.1.post1
backcall==0.2.0
bokeh==2.1.1
click==7.1.2
cloudpickle==1.5.0
cryptography==2.6.1
cycler==0.10.0
dask==2.21.0
dask-mpi==2.0.0
decorator==4.4.2
distributed==2.21.0
entrypoints==0.3
fitsio==1.0.5
fsspec==0.7.4
HeapDict==1.0.1
ipykernel==5.3.3
ipython==7.16.1
ipython-genutils==0.2.0
jedi==0.17.2
Jinja2==2.11.2
jupyter-client==6.1.6
jupyter-core==4.6.3
keyring==17.1.1
keyrings.alt==3.1.1
kiwisolver==1.2.0
locket==0.2.0
MarkupSafe==1.1.1
matplotlib==3.3.0
mpi4py==3.0.3
msgpack==1.0.0
numexpr==2.7.1
numpy==1.19.0
packaging==20.4
pandas==1.0.5
parso==0.7.0
partd==1.1.0
pexpect==4.8.0
pickleshare==0.7.5
Pillow==7.2.0
prompt-toolkit==3.0.5
psutil==5.7.2
ptyprocess==0.6.0
pycrypto==2.6.1
Pygments==2.6.1
PyGObject==3.30.4
pyparsing==2.4.7
python-dateutil==2.8.1
python3-customs==0.1.0
python3-customs-mods==0.1.0
python3-modster==0.1.0
python3-nerscjson==0.9
pytz==2020.1
pyxdg==0.25
PyYAML==5.3.1
pyzmq==19.0.1
SecretStorage==2.3.1
six==1.12.0
sortedcontainers==2.2.2
tables==3.6.1
tblib==1.6.0
toolz==0.10.0
tornado==6.0.4
traitlets==4.3.3
typing-extensions==3.7.4.2
wcwidth==0.2.5
zict==2.0.0
```

**Comment by mrocklin** [comment]
> Worker tab with lovingly rendered worker information, not 500 Internal Server Error message of cold indifference. :)

:)

@jsignell @jacobtomlinson any interest?

This is in the WorkerTable.  The easiest change here would be to add an `or 1` to the end of the sum computation before dividing.  

There might be more clever things we could do though, like blank out the cell.

**Comment by jsignell** [comment]
I can take a look.
