### ISSUE TITLE
dask-dataframe: update NotImplementedError for isin type

### ISSUE THREAD

**Issue by raybellwaves** [dask/dask#6469]
This may be a bit too niche so welcome to close.

I recently came across a [`NotImplementedError`](https://github.com/dask/dask/blob/master/dask/dataframe/core.py#L2372)
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\131416\AppData\Local\Continuum\anaconda3\lib\site-packages\dask\dataframe\core.py", line 2904, in isin
    return super(Series, self).isin(values)
  File "C:\Users\131416\AppData\Local\Continuum\anaconda3\lib\site-packages\dask\dataframe\core.py", line 2285, in isin
    raise NotImplementedError("Passing a %r to `isin`" % typename(type(values)))
NotImplementedError: Passing a 'dask.dataframe.core.Series' to `isin`
```

```
>>> df = pd.DataFrame({'a': ['a', 'b', 'c', 'd', 'e'], 'b': [0, 1, 2, 3, 4]})
>>> ddf = dd.from_pandas(df, 2)
>>> df2 = pd.DataFrame({'a': ['b', 'c'], 'b': [1, 2]})
>>> ddf2 = dd.from_pandas(df2, 2)
>>> ddf[ddf.a.isin(ddf2.a)]
```

I'm not sure if the `NotImplementedError` could offer a suggestion? something like `If you are passing a 'dask.dataframe.core.Series' you could call .compute() on it`

```
>>> ddf[ddf.a.isin(ddf2.a.compute())]
```

**Comment by gforsyth** [comment]
Thanks for opening this @raybellwaves -- I'm not sure what, if anything, we should do here. 
It's certainly technically possible for us to offer a suggestion in an error message, and I'm generally in favor of that.  

My concern here (perhaps wildly overblown) is that there are a few different ways to handle this and I'm not sure they're generalizable enough.  You suggested

```
>>> ddf[ddf.a.isin(ddf2.a.compute())]
```

but one could also do

```
>>> ddf[ddf.a.compute().isin(ddf2.a)]
```

although that second one would also force a compute on `ddf2.a`.  But either of these might be less than great if either or both of `ddf` and `ddf2` are very big.

**Comment by mrocklin** [comment]
We could also accumulate dd2.a.unique() in a task ourselves and not trigger
a compute call.

But in all of these cases the right thing to do really depends on the
relative sizes (as I think Gil is pointing out) and so it's not clear on
how best to proceed.

**Comment by raybellwaves** [comment]
Thanks for the feedback guys.

I agree it's probably not best to 'offer' a suggestion given that there are few ways to achieve the desired output.

I'm thinking out loud here: how about the `NotImplementedError` specifying the type(s) implemented?

I see there is a [`bad_types`](https://github.com/dask/dask/blob/master/dask/dataframe/core.py#L2370) variable in the function. Where I believe `_Frame` is a `dask.dataframe.core.Series` or `dask.dataframe.core.DataFrame`. I'm wondering what a `good_types` variables would look like? I imagine there are lots of options here which may make the error message quite long.

```
import dask.dataframe as dd
import dask.array as da
import pandas as pd
import numpy as np

good_types = ('list', 'tuple', 'numpy.ndarray', 'pandas.core.series.Series', 'pandas.core.frame.DataFrame')
good_types_v = (['b', 'c'], ('b', 'c'), np.array(['b', 'c']), pd.Series(['b', 'c']), pd.Series(['b', 'c']).to_frame())

df = pd.DataFrame({'a': ['a', 'b', 'c', 'd', 'e'], 'b': [0, 1, 2, 3, 4]})
ddf = dd.from_pandas(df, 2)

expected = [False, True, True, False, False]

for k, v in zip(good_types, good_types_v):
    print(k)
    actual = list(ddf.a.isin(v).compute())
    assert actual == expected           Note to pandas.core.frame.DataFrame works but doesn't assert
```

In testing this I got a slightly different error message with a `dask.array.core.Array` compared to a `dask.array.dataframe.Array`

```
>>> ddf.a.isin(da.array(['b', 'c']))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\131416\AppData\Local\Continuum\anaconda3\lib\site-packages\dask\dataframe\core.py", line 2904, in isin
    return super(Series, self).isin(values)
  File "C:\Users\131416\AppData\Local\Continuum\anaconda3\lib\site-packages\dask\dataframe\core.py", line 2286, in isin
    meta = self._meta_nonempty.isin(values)
  File "C:\Users\131416\AppData\Local\Continuum\anaconda3\lib\site-packages\pandas\core\series.py", line 4294, in isin
    result = algorithms.isin(self, values)
  File "C:\Users\131416\AppData\Local\Continuum\anaconda3\lib\site-packages\pandas\core\algorithms.py", line 411, in isin
    "only list-like objects are allowed to be passed "
TypeError: only list-like objects are allowed to be passed to isin(), you passed a [Array]
```

Given, this `TypeError` comes from pandas (https://github.com/pandas-dev/pandas/blob/master/pandas/core/algorithms.py#L411)

Is it worth copying it in dask? (i.e. updating the `NotImplementedError` to a `TypeError`; although I imagine adding support for a `dask.dataframe.core.Series` could be within future scope and therefore left as a `NotImplementedError`)

To update my `good_types` suggestion it looks as though you could add to make a mention to the 'list-like objects'

```
NotImplementedError("Passing a %r to `isin`" % typename(type(values)) + " only list-like objects are allowed to be passed")
```

**Comment by adonig** [comment]
Is there another way to do it? I tried a merge and then selecting only the rows where _merge == "left_only", but it's kind of a complicated way to do something that should be a straightforward operation.
