### ISSUE TITLE
dd.read_parquet fails on directory path

### ISSUE THREAD

**Issue by mdwint** [dask/dask#6504]
**What happened**:

After upgrading to Dask 2.22.0, `dd.read_parquet` can no longer read some Parquet datasets (directories) that used to work with Dask 2.11.0.

**What you expected to happen**:

I expected the datasets to be loaded without changing the call to `dd.read_parquet`.

**Minimal Complete Verifiable Example**:

Example dataset: https://drive.google.com/file/d/1Qn5k9xZT_yegqisttGW1oGw-MwWHCY_E/view?usp=sharing
```
old
├── _common_metadata
├── _metadata
├── part.0.parquet
├── part.1.parquet
└── part.2.parquet
```

Trying to load this directory with `dd.read_parquet` fails:
```python
>>> import dask.dataframe as dd                                                                                                                                               
>>> dd.read_parquet("old").compute()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/matteo/.pyenv/versions/3.7.4/lib/python3.7/site-packages/dask/base.py", line 167, in compute
    (result,) = compute(self, traverse=False, **kwargs)
  File "/Users/matteo/.pyenv/versions/3.7.4/lib/python3.7/site-packages/dask/base.py", line 447, in compute
    results = schedule(dsk, keys, **kwargs)
  File "/Users/matteo/.pyenv/versions/3.7.4/lib/python3.7/site-packages/dask/threaded.py", line 84, in get
    **kwargs
  File "/Users/matteo/.pyenv/versions/3.7.4/lib/python3.7/site-packages/dask/local.py", line 486, in get_async
    raise_exception(exc, tb)
  File "/Users/matteo/.pyenv/versions/3.7.4/lib/python3.7/site-packages/dask/local.py", line 316, in reraise
    raise exc
  File "/Users/matteo/.pyenv/versions/3.7.4/lib/python3.7/site-packages/dask/local.py", line 222, in execute_task
    result = _execute_task(task, data)
  File "/Users/matteo/.pyenv/versions/3.7.4/lib/python3.7/site-packages/dask/core.py", line 121, in _execute_task
    return func(*(_execute_task(a, cache) for a in args))
  File "/Users/matteo/.pyenv/versions/3.7.4/lib/python3.7/site-packages/dask/dataframe/io/parquet/core.py", line 276, in read_parquet_part
    dfs = [func(fs, rg, columns.copy(), index, **kwargs) for rg in part]
  File "/Users/matteo/.pyenv/versions/3.7.4/lib/python3.7/site-packages/dask/dataframe/io/parquet/core.py", line 276, in <listcomp>
    dfs = [func(fs, rg, columns.copy(), index, **kwargs) for rg in part]
  File "/Users/matteo/.pyenv/versions/3.7.4/lib/python3.7/site-packages/dask/dataframe/io/parquet/arrow.py", line 753, in read_partition
    piece, columns, partitions, **kwargs
  File "/Users/matteo/.pyenv/versions/3.7.4/lib/python3.7/site-packages/dask/dataframe/io/parquet/arrow.py", line 812, in _parquet_piece_as_arrow
    **kwargs.get("read", {}),
  File "/Users/matteo/.pyenv/versions/3.7.4/lib/python3.7/site-packages/pyarrow/parquet.py", line 704, in read
    reader = self.open()
  File "/Users/matteo/.pyenv/versions/3.7.4/lib/python3.7/site-packages/pyarrow/parquet.py", line 680, in open
    reader = self.open_file_func(self.path)
  File "/Users/matteo/.pyenv/versions/3.7.4/lib/python3.7/site-packages/fsspec/spec.py", line 724, in open
    **kwargs
  File "/Users/matteo/.pyenv/versions/3.7.4/lib/python3.7/site-packages/fsspec/implementations/local.py", line 107, in _open
    return LocalFileOpener(path, mode, fs=self, **kwargs)
  File "/Users/matteo/.pyenv/versions/3.7.4/lib/python3.7/site-packages/fsspec/implementations/local.py", line 173, in __init__
    self._open()
  File "/Users/matteo/.pyenv/versions/3.7.4/lib/python3.7/site-packages/fsspec/implementations/local.py", line 178, in _open
    self.f = open(self.path, mode=self.mode)
IsADirectoryError: [Errno 21] Is a directory: '/Users/matteo/Downloads/old'
```

Loading the files using a glob pattern and saving them to a new directory resolves the issue:
```python
>>> dd.read_parquet("old/*.parquet").to_parquet("new")                                                                                                                        
>>> dd.read_parquet("new").compute()                                                                                                                                          
            date title description
index
0     2019-01-01   Foo         Foo
1     2019-01-02   Foo         Foo
2     2019-01-03   Foo         Foo
3     2019-01-04   Foo         Foo
...
```

Because I have many large datasets that produce the above error, I'd like to be able to load the original directories without having to load and save them.

Using a glob pattern is also not an option for me, because that does not load the metadata required for filtering:
```python
>>> dd.read_parquet("old/*.parquet", filters=[("title", "==", "Foo")]).compute()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/matteo/.pyenv/versions/3.7.4/lib/python3.7/site-packages/dask/dataframe/io/parquet/core.py", line 239, in read_parquet
    **kwargs
  File "/Users/matteo/.pyenv/versions/3.7.4/lib/python3.7/site-packages/dask/dataframe/io/parquet/arrow.py", line 651, in read_metadata
    paths, fs, split_row_groups, gather_statistics, filters, dataset_kwargs
  File "/Users/matteo/.pyenv/versions/3.7.4/lib/python3.7/site-packages/dask/dataframe/io/parquet/arrow.py", line 161, in _gather_metadata
    dataset, base, fns = _get_dataset_object(paths, fs, filters, dataset_kwargs)
  File "/Users/matteo/.pyenv/versions/3.7.4/lib/python3.7/site-packages/dask/dataframe/io/parquet/arrow.py", line 121, in _get_dataset_object
    paths, filesystem=fs, filters=filters, **dataset_kwargs
  File "/Users/matteo/.pyenv/versions/3.7.4/lib/python3.7/site-packages/pyarrow/parquet.py", line 1197, in __init__
    self._filter(filters)
  File "/Users/matteo/.pyenv/versions/3.7.4/lib/python3.7/site-packages/pyarrow/parquet.py", line 1311, in _filter
    accepts_filter = self.partitions.filter_accepts_partition
AttributeError: 'NoneType' object has no attribute 'filter_accepts_partition'
```

I'd like to be able to load directories with filters, like this: 
```python
>>> dd.read_parquet("new", filters=[("title", "==", "Foo")]).compute()
            date title description
index
0     2019-01-01   Foo         Foo
1     2019-01-02   Foo         Foo
2     2019-01-03   Foo         Foo
3     2019-01-04   Foo         Foo
...
```

**Environment**:

- Dask version: 2.22.0
- PyArrow version: 1.0.0
- Python version: 3.7.4
- Operating System: macOS 10.15.6
- Install method (conda, pip, source): pip

**Comment by jsignell** [comment]
Thank you @mdwint for the detailed writeup. @martindurant might have ideas into what's going on with fsspec.

**Comment by martindurant** [comment]
I can confirm that the tasks in the dataframe look like the following, with the path as the directory, not one of the datafiles. 
```
(<function dask.dataframe.io.parquet.core.read_parquet_part(func, fs, meta, part, columns, index, kwargs)>,
 <bound method ArrowEngine.read_partition of <class 'dask.dataframe.io.parquet.arrow.ArrowEngine'>>,
 <fsspec.implementations.local.LocalFileSystem at 0x117aaa950>,
 Empty DataFrame
 Columns: [date, title, description]
 Index: [],
 [('/Users/mdurant/Downloads/old', [0], None)],   ### <- here
 ['date', 'title', 'description'],
 ['index'],
 {'partitions': <pyarrow.parquet.ParquetPartitions at 0x11f902310>,
  'categories': [],
  'filters': None,
  'schema': date: timestamp[us]
    -- field metadata --
    PARQUET:field_id: '1'
  title: string
    -- field metadata --
    PARQUET:field_id: '2'
  description: string
    -- field metadata --
    PARQUET:field_id: '3'
  index: int64
    -- field metadata --
    PARQUET:field_id: '4'
  -- schema metadata --
  pandas: '{"index_columns": ["index"], "column_indexes": [{"name": null, "' + 658
  ARROW:schema: '/////yAEAAAQAAAAAAAKAA4ABgAFAAgACgAAAAABAwAQAAAAAAAKAAwAAA' + 1362})
```

@rjzamora , is this an arrow change? The "piece" looks like `ParquetDatasetPiece('/Users/mdurant/Downloads/old', row_group=0, partition_keys=[])`

**Comment by martindurant** [comment]
The metadata row-groups all list having path: None; how was this data created?

**Comment by martindurant** [comment]
(btw: the following does work: `dd.read_parquet("old/*.parquet", filters=[("title", "==", "Foo")], engine='fastparquet').compute()`)

**Comment by mdwint** [comment]
> The metadata row-groups all list having path: None; how was this data created?

I believe it was created with Dask 2.11.0 or earlier (not sure which one). Reading with Dask 2.11.0 works:
```python
>>> import dask
>>> dask.__version__
'2.11.0'
>>> import dask.dataframe as dd
>>> dd.read_parquet("old", filters=[("title", "==", "Foo")]).compute()
            date title description
index
0     2019-01-01   Foo         Foo
1     2019-01-02   Foo         Foo
...
```

I have not tried any versions between 2.11.0 and 2.22.0.

**Comment by martindurant** [comment]
I believe "old" dask did not attempt to use the metadata file when loading with pyarrow, but now it should - but if the file is wrong for some reason...

**Comment by mdwint** [comment]
I cannot reproduce the issue with another dataset created by Dask 2.11.0 and PyArrow 0.17.0. The "old" dataset I posted may be very old...

**Comment by rjzamora** [comment]
I can look into this next week, but I suspect the problem is with the older version of Dask writting a *bad* `_metadata` file for partitioned datasets.  More specifically, the metadata file used to leave out the file-path field in the _metadata.  Since fixing this, we started assuming the global metadata **will** include this information.

**Comment by jsignell** [comment]
This might have been fixed by #6527. @mdwint, if you have a chance it'd be great to try out master.

**Comment by mdwint** [comment]
Thanks! The following now works (with gather_statistics enabled):
```python
>>> import dask
>>> dask.__version__
'2.23.0+7.gbdf0e2df'
>>> import dask.dataframe as dd
>>> dd.read_parquet('old/*.parquet', filters=[('title', '==', 'Foo')], gather_statistics=True).compute()
```

Reading the directory path doesn't work, but if there are no downsides to using a glob pattern then this solution will do for me.

**Comment by rjzamora** [comment]
@mdwint - If you have a "bad" `_metadata` file, it is probably worthwhile to generate a new one (it is certainly more performant).  You can try a simple utility like this:

```python
import pyarrow.parquet as pq
from fsspec.core import get_fs_token_paths

def write_metadata_file(path, out_path, fs):
    """ Write "_metadata" file for simple parquet dataset
        Notes:
        - Requires a directory path as input.
        - Only works for a "flat" directory structure.
        - Schemas must be consistent between files
    """
    dataset = pq.ParquetDataset(path, filesystem=fs)
    pieces = dataset.pieces
    meta = None
    for piece in pieces:
        _meta = piece.get_metadata()
        filename = piece.path.split(fs.sep)[-1]
        _meta.set_file_path(filename)
        if meta:
            # This will fail if schemas are inconsistent... 
            meta.append_row_groups(_meta)
        else:
            meta = _meta
    if meta:
        metadata_path = fs.sep.join([out_path, "_metadata"])
        with fs.open(metadata_path, "wb") as fil:
            meta.write_metadata_file(fil)
    else:
        print("No metadata to write!")

dir_path = "./data"
out_dir_path = "./data"
fs = get_fs_token_paths(dir_path, mode="rb")[0]
write_metadata_file(dir_path, out_dir_path, fs)
```

**Comment by martindurant** [comment]
@rjzamora , would it be worthwhile having a utility like this in the codebase? 
Fastparquet has a metadata-from-files function somewhere, and it might be useful in the more typical cases of parquet files created by a framework that doesn't make metadata files at all. It would even parallelize well.

**Comment by rjzamora** [comment]
> @rjzamora , would it be worthwhile having a utility like this in the codebase?
Fastparquet has a metadata-from-files function somewhere, and it might be useful in the more typical cases of parquet files created by a framework that doesn't make metadata files at all. It would even parallelize well.

Sure!  I'm sure we can work out a pretty robust utility for this :)

**Comment by mdwint** [comment]
Thanks @rjzamora, that utility will come in handy. I've found that all recent datasets I have are actually fine. The old files I posted earlier are part of a test suite, and were committed 9 months ago. In that commit, the versions are pinned to dask==2.6.0 and pyarrow==0.15.1.

**Comment by mdwint** [comment]
Thanks all! Closing this now.
