### ISSUE TITLE
Issue running a large number of embarrassingly parallel tasks 

### ISSUE THREAD

**Issue by mshaikh786** [dask/dask#6519]
I am trying to run the following dask script stops and crashes with no errors. 
```
#!/usr/bin/env python

import time
import random
import numpy as np
import os
from dask.distributed import Client, progress
jobid=os.getenv('SLURM_JOBID')
client= Client(scheduler_file='scheduler_%s.json' %jobid,direct_to_workers=True)
print(client)

def sim(x):
    return np.linalg.inv(x)

N=1000000
C=15000
print("Creating parameter set")
input_params=np.random.randint(0, 100, size=(N,100, 100))
print("Starting computation")
futures = client.map(sim,input_params,batch_size=C)
print("Futures length ",len(futures))
client.close()
```

Some information about the system and the SLURM jobscript to launch the above python script:
```
#!/bin/bash -l
#SBATCH --ntasks=64
#SBATCH --ntasks-per-node=32
#SBATCH --cpus-per-task=1
#SBATCH --partition=workq
#SBATCH --time=02:00:00

module load dask/2.22.0
srun -u --hint=nomultithread -n ${SLURM_NTASKS} --ntasks-per-node=${SLURM_NTASKS_PER_NODE} -c ${SLURM_CPUS_PER_TASK} dask-mpi --no-nanny --nthreads=${SLURM_CPUS_PER_TASK} --memory-limit='4GB' --local-directory=workers${SLURM_JOBID} --scheduler-file=scheduler_${SLURM_JOBID}.json --interface=ipogif0 --scheduler-port=6192 --dashboard-address=${node}:8787 &
```
The jobscript was submitted on CrayXC40 (--interface=ipogif0 for Cray Aries interconnect) but a similar test was also run on a non-Cray machine, (with --interface=ib0). I am launching dask-mpi on multiple nodes to increase the total memory (each node has 128 GB). With --memory-limit=4GB, I can see that Dask Dashboard shows me a total of ~ 4GB * 64 workers (223GB) memory. 

Version of software are as follows:

- Dask version: 2.22.0
- Python version: 3.8.0
- Operating System: Cray Linux Environment 7.01 ( also tested on a different machine with CentOS 7.7)
- Install method (conda, pip, source): pip install --no-cache-dir dask[complete] dask-mpi dask-jobqueue dask-ml

**Comment by mshaikh786** [comment]
Just to add more information:

- I tried the above example with N=100000 and works perfectly fine.
- I also tried using dask.bag instead of futures and see the same issue when using N=1000000

```
#!/usr/env/bin python
import time,os
from dask.distributed import Client, progress
client= Client(scheduler_file='scheduler_%s.json' %(os.getenv('SLURM_JOBID')))
client


import dask.bag as db
import numpy as np

def sim(x):
    return np.linalg.inv(x)


n = np.random.randint(0, 100, size=(1000000, 100, 100))

s = time.time()
b = db.from_sequence(n,npartitions=7)
print("Elapsed time in from_sequence: ",time.time() - s)

s = time.time()
results=b.map(sim).compute()
print("Elapsed time in map and compute: ",time.time() - s)

print("Length of results : ",len(results))
print("Last element")
print(results[-1])
client.close()
```

**Comment by mrocklin** [comment]
If you there aren't any errors then I'm not sure that there is much that I
personally can do here.  You might want to try producing a slimmer example
and seeing if there is some boundary where things crash/don't-crash.  You
might also want to take a look at these links:

https://examples.dask.org/applications/embarrassingly-parallel.html
https://docs.dask.org/en/latest/best-practices.html#avoid-very-large-graphs

**Comment by mshaikh786** [comment]
Thanks Mathew, 
The boundary was N=100,000. When set to N=1,000,000 then the issue appears.
I notice a few INFO messages which may be pointing to excessive wait by the workers:
`distributed.core - INFO - Event loop was unresponsive in Worker for 19.20s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.`

Does this highlight the possibility of drop off of a TCP connection (e.g. due to timeout) between workers?

**Comment by mrocklin** [comment]
> The boundary was N=100,000. When set to N=1,000,000 then the issue
appears.

There are many numbers in between 100,000 and 1,000,000 :)

> Does this highlight the possibility of drop off of a TCP connection (e.g.
due to timeout) between workers?

No, I don't think so.

**Comment by mshaikh786** [comment]
> There are many numbers in between 100,000 and 1,000,000
Well said :) 
I can see the job failing with error at 450,000 tasks (slurm output is attached)
[slurm-15435477.txt](https://github.com/dask/dask/files/5086593/slurm-15435477.txt)

**Comment by guziy** [comment]
Hi:

Sorry to comment on this 2 years later, but I confirm the obserfation. I have a simple script squaring the number which breaks if I use a list of `1000_000`, `500_000` but worked for `200_000` elements. 



```python
from dask_mpi import initialize
from distributed import Client
import dask
from dask.distributed import progress


import os
from pathlib import Path
import logging

def square(x):
    return x ** 2


def main():
    dask.config.set({
        "distributed.worker.use-file-locking": False,
    })

    logging.getLogger("distributed.batched").setLevel(logging.CRITICAL)
    logging.getLogger("distributed.core").setLevel(logging.CRITICAL)
    logging.getLogger("distributed.worker").setLevel(logging.CRITICAL)
    logging.getLogger("distributed.scheduler").setLevel(logging.CRITICAL)

    local_dir = Path(os.environ["TMPDIR"]) / "dask-work-dir-multinode"
    
    initialize(nthreads=1, dashboard=False, 
               interface="ib0", local_directory=str(local_dir))

    with Client() as client:
        n_list = 1_000_000
        futures = client.map(square, range(n_list))
        progress(futures)
        results = client.gather(futures)
        # client.shutdown()

    print("")
    print("==" * 10)
    print("Results = ", results[:20])


if __name__ == '__main__':
    main()
```




Below are the exceptions:

```
Traceback (most recent call last):
  File "/fs/ssm/eccc/cmd/cmds/env/python/py39_2022.09.29_all/lib/python3.9/site-packages/distributed/comm/tcp.py", line 225, in read
    frames_nbytes = await stream.read_bytes(fmt_size)
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/fs/ssm/eccc/cmd/cmds/env/python/py39_2022.09.29_all/lib/python3.9/asyncio/tasks.py", line 490, in wait_for
    return fut.result()
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/fs/ssm/eccc/cmd/cmds/env/python/py39_2022.09.29_all/lib/python3.9/site-packages/distributed/comm/core.py", line 328, in connect
    handshake = await asyncio.wait_for(comm.read(), time_left())
  File "/fs/ssm/eccc/cmd/cmds/env/python/py39_2022.09.29_all/lib/python3.9/asyncio/tasks.py", line 492, in wait_for
    raise exceptions.TimeoutError() from exc
asyncio.exceptions.TimeoutError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/fs/homeu2/eccc/cmd/cmde/olh001/Python/test/dask-multi-node/test.py", line 44, in <module>
    main()
  File "/fs/homeu2/eccc/cmd/cmde/olh001/Python/test/dask-multi-node/test.py", line 34, in main
    progress(futures)
  File "/fs/ssm/eccc/cmd/cmds/env/python/py39_2022.09.29_all/lib/python3.9/site-packages/distributed/diagnostics/progressbar.py", line 475, in progress
    TextProgressBar(futures, complete=complete, **kwargs)
  File "/fs/ssm/eccc/cmd/cmds/env/python/py39_2022.09.29_all/lib/python3.9/site-packages/distributed/diagnostics/progressbar.py", line 134, in __init__
    loop_runner.run_sync(self.listen)
  File "/fs/ssm/eccc/cmd/cmds/env/python/py39_2022.09.29_all/lib/python3.9/site-packages/distributed/utils.py", line 581, in run_sync
    return sync(self.loop, func, *args, **kwargs)
  File "/fs/ssm/eccc/cmd/cmds/env/python/py39_2022.09.29_all/lib/python3.9/site-packages/distributed/utils.py", line 406, in sync
    raise exc.with_traceback(tb)
  File "/fs/ssm/eccc/cmd/cmds/env/python/py39_2022.09.29_all/lib/python3.9/site-packages/distributed/utils.py", line 379, in f
    result = yield future
  File "/fs/ssm/eccc/cmd/cmds/env/python/py39_2022.09.29_all/lib/python3.9/site-packages/tornado/gen.py", line 762, in run
    value = future.result()
  File "/fs/ssm/eccc/cmd/cmds/env/python/py39_2022.09.29_all/lib/python3.9/site-packages/distributed/diagnostics/progressbar.py", line 75, in listen
    self.comm = await connect(
  File "/fs/ssm/eccc/cmd/cmds/env/python/py39_2022.09.29_all/lib/python3.9/site-packages/distributed/comm/core.py", line 333, in connect
    raise OSError(
OSError: Timed out during handshake while connecting to tcp://10.102.8.135:17351 after 30 s
                                                                                                                                                                                 
```
