### ISSUE TITLE
DataFrame.repartition() fails if npartitions=len(df)

### ISSUE THREAD

**Issue by stuarteberg** [dask/dask#6543]
If I attempt to repartition a DataFrame such that every row becomes its own partition, a `ValueError` is raised.  (Such fine-grained partitioning can be useful when the DataFrame contains large objects, or during testing.)

```python
import numpy as np
import pandas as pd
import dask.dataframe as ddf

data = pd.DataFrame({'a': np.arange(16)})
df = ddf.from_pandas(data, chunksize=4)
df.repartition(npartitions=15)  # okay
df.repartition(npartitions=16)  # raises
```

```pytb
Traceback (most recent call last):
  File "/tmp/test.py", line 8, in <module>
    df.repartition(npartitions=16)
  File "/opt/miniconda/envs/flyem/lib/python3.7/site-packages/dask/dataframe/core.py", line 1184, in repartition
    return repartition_npartitions(self, npartitions)
  File "/opt/miniconda/envs/flyem/lib/python3.7/site-packages/dask/dataframe/core.py", line 5968, in repartition_npartitions
    return df.repartition(divisions=divisions)
  File "/opt/miniconda/envs/flyem/lib/python3.7/site-packages/dask/dataframe/core.py", line 1186, in repartition
    return repartition(self, divisions, force=force)
  File "/opt/miniconda/envs/flyem/lib/python3.7/site-packages/dask/dataframe/core.py", line 6065, in repartition
    df.divisions, divisions, df._name, tmp, out, force=force
  File "/opt/miniconda/envs/flyem/lib/python3.7/site-packages/dask/dataframe/core.py", line 5748, in repartition_divisions
    check_divisions(b)
  File "/opt/miniconda/envs/flyem/lib/python3.7/site-packages/dask/dataframe/core.py", line 5713, in check_divisions
    raise ValueError(msg)
ValueError: New division must be unique, except for the last element
```

<details>

<summary>Environment details</summary>

**Environment**:

- Dask version: 2.23.0
- Python version: 3.7.8
- Operating System: Mac
- Install method (conda, pip, source): conda-forge

```
$ conda list | grep -E '^(python |dask)'
dask                      2.23.0                     py_0    conda-forge
dask-core                 2.23.0                     py_0    conda-forge
dask-jobqueue             0.7.1                      py_0    conda-forge
python                    3.7.8           hc9dea61_1_cpython    conda-forge
```

</details>

**Comment by stuarteberg** [comment]
Thanks for looking at this.  One problem with that approach is that the index is not necessarily contiguous, so `range(16)` isn't necessarily correct.  But I suppose it's impossible to know how to choose good divisions in that case unless you know the index values.

I know there's an option for `partition_size`, but that's based on RAM usage.  Unfortunately, that's not a convenient way to specify "one row per partition", especially in my real use-case, where one of the columns has `dtype=object`.

I'm not exactly sure how to use `repartition()` when I don't know the index range.  Is there a way to just force it to compute the index so I can learn the divisions and then choose them myself?

Just to illustrate some of the problem:

Suppose I have a dataframe with a non-contiguous index:

```python
data = pd.DataFrame({'a': np.arange(16)}, index=np.arange(0, 160, 10))
df = ddf.from_pandas(data, chunksize=4)
```

(That's a simple case, but suppose I don't happen to know exactly what the non-contiguous index values are.)

If I happen to know the total length of the dataframe, I might try this:

```python
In [146]: df2 = df.repartition(npartitions=16)
     ...: df2.divisions
Out[146]: (0, 10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 110, 120, 127, 135, 142, 150)
```

No error in that case, but it already results in something weird. I would have expected this:

```
(0, 10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 110, 120, 130, 140, 150, 150)
```

Of course even that would still be non-ideal if the true index didn't happen to be evenly spaced.

If I happen to know the divisions, can at least attempt an even spacing.  Even better would be to learn the complete index.  What's the correct way to do that?  Run `map_partitions()` and return just the index?  Even if I try that, I'm still running into the an [assertion when the old divisions are not yet known][1], since `None != 0`.

[1]: https://github.com/dask/dask/blob/d96fed990279fcd272cc5ada005d07c85b104ce5/dask/dataframe/core.py#L5772

PS -- Apologies, I will be afk for a bit.  Thanks again for your response.

**Comment by quasiben** [comment]
Can you also describe the use case you have here?  Why do you need a partition for each row ?

**Comment by mrocklin** [comment]
Thank you for the bug report @stuarteberg and the excellent minimal example.  I think tha regardless of the circumstance this demonstrates a bug in the repartitioning code that we should resolve rather than find a work-around.

Two options come to mind:

1.  We don't convert to int, but keep as a float
2.  We do a pass through the divisions and make sure that they are appropriately unique (except for the last element).  This probably means that we drop the repeated elements, and just have fewer partitions than was asked for.  This also came up recently in #6541 cc @nils-braun 

I'm in favor of implementing fix 2

**Comment by dgerlanc** [comment]
Any thoughts on how the test `test_dataframe.test_repartition_npartitions` should behave in relate to this change? This will break the assertion that the number of resulting partitions is `== n_partitions`. @mrocklin
