### ISSUE TITLE
Client.set_as_default=False sets client as default

### ISSUE THREAD

**Issue by kinghuang** [dask/dask#6584]
**What happened**:

If I create a Client with `set_as_default=False` in the arguments, the client still gets set as the default.

**What you expected to happen**:

The client that I create should not be set as the default client.

**Minimal Complete Verifiable Example**:

```python
>>> from distributed import Client, default_client
>>> default_client()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.8/site-packages/distributed-2.25.0-py3.8.egg/distributed/client.py", line 4550, in default_client
    raise ValueError(
ValueError: No clients found
Start a client and point it to the scheduler address
  from distributed import Client
  client = Client('ip-addr-of-scheduler:8786')

>>> c = Client(set_as_default=False)
>>> c
<Client: 'tcp://127.0.0.1:40813' processes=4 threads=4, memory=12.57 GB>
>>> default_client()
<Client: 'tcp://127.0.0.1:40813' processes=4 threads=4, memory=12.57 GB>
>>> c == default_client()
True
```

The `default_client()` calls after creating a client with `set_as_default=False` should throw a `ValueError` just like before creating the client.

**Anything else we need to know?**:

None.

**Environment**:

- Dask version: 2.25.0
- Python version: 3.8.5
- Operating System: Linux f9c08655086d 4.19.76-linuxkit #1 SMP Tue May 26 11:42:35 UTC 2020 x86_64 GNU/Linux
- Install method (conda, pip, source): pip

**Comment by quasiben** [comment]
This could be a bug -- maybe it's a usability issues.  I am not very familiar with the `set_as_default` flag but I would assume this is used more often when a cluster is already created and usage looks more like :

```python
cluster = LocalCluster(...) # or some other cluster creation
client = Client(addr, set_as_default=False)
```

Could be wrong.  @kinghuang it looks like you are relying on `Client` to also create the cluster

**Comment by mrocklin** [comment]
It's still the default client, but it isn't the default Dask scheduler.  If you go and run some computation

```python
df.compute()
```

Dask will still use whatever default scheduler there is (likely the local threaded scheduler)

**Comment by kinghuang** [comment]
Ah, perhaps I'm not understanding the distinction between a client and a scheduler. I always thought that running something like `df.compute()` caused it to use the default *client*. How do I find out what the default scheduler is, and detect that I'm not overriding it?

I'm trying to write unit tests for some code that can potentially create multiple clients (to different Dask clusters). I'm specifying `set_as_default=False` to not affect the default client, and was checking this via `default_client()`, but it seems my understanding of how Dask works is incorrect.

So, if I do something like the following, I should still expect the dataframe to be computed locally, even though the default client is pointing to a remote cluster?

```python
client1 = Client("tcp://remote-cluster-a:8786", set_as_default=False)
client2 = Client("tcp://remote-cluster-b:8786", set_as_default=False)

df.compute()
```

**Comment by mrocklin** [comment]
The set_as_default keyword was originally designed to protect
against overwriting the non-distributed schedulers, see
https://docs.dask.org/en/latest/scheduling.html

In this case "Scheduler" is a bit overloaded because the distributed
scheduling system also has a component named "Scheduler" (the thing made by
the dask-scheduler command), which is somewhat different.

The default scheduler function is, I think, accessible as
dask.config.get("scheduler").  I don't know of a way to protect against
overwriting the default client today.

The behavior that you're asking for here is reasonable.  The fact that this
situation is confusing is mostly our fault.  We could change the meaning of
the set_as_default keyword.  I think that there might be unintended
consequences though.  The next step here is probably to make this change,
run the test suite, and see if anything breaks.

**Comment by kinghuang** [comment]
Thanks, that helps me understand things much better, especially the current behaviour of `set_as_default`.
