### ISSUE TITLE
ModuleNotFoundError: No module named 'fcntl'

### ISSUE THREAD

**Issue by arunshankarc** [dask/dask#6662]
When I run dask dataframe `to_csv `or `df_merge.compute()` I see error as mentioned below. I do not see the issue when I run on jupyter notebook and entire program runs as expected. Issue is only seen on linux (I tried on centos).

I have tried with python3.7.9 and python3.8.3 and python3.6.8 assuming that the issue may be with respect to version, but issue persists.
Dask is installed using pip install dask[complete]==2.20.0

Python version - 3.7.9
pandas - 0.25.3 (Also tried with 1.0.5 and 1.1.2)

`df_merge.to_csv(f'output_dask.csv', encoding='utf-8')`

or 

`df_merge.compute()`

I get below error, Any idea why I am seeing below issue? Please let me know

```
Caught with processing error,
Traceback (most recent call last):
  File "../venv_3.8/lib/python3.8/site-packages/locket/__init__.py", line 10, in <module>
    import fcntl
ModuleNotFoundError: No module named 'fcntl'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "../venv_3.8/lib/python3.8/site-packages/locket/__init__.py", line 13, in <module>
    import msvcrt
ModuleNotFoundError: No module named 'msvcrt'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "get_data_from_db.py", line 24, in main
    helpers.parse_df_dask(df_parallel)
  File "../bin/db_queries/helpers.py", line 167, in parse_df_dask
    df_merge_pd = df_merge.compute()
  File "../venv_3.8/lib/python3.8/site-packages/dask/base.py", line 166, in compute
    (result,) = compute(self, traverse=False, **kwargs)
  File "../venv_3.8/lib/python3.8/site-packages/dask/base.py", line 444, in compute
    results = schedule(dsk, keys, **kwargs)
  File "../venv_3.8/lib/python3.8/site-packages/dask/threaded.py", line 76, in get
    results = get_async(
  File "../venv_3.8/lib/python3.8/site-packages/dask/local.py", line 486, in get_async
    raise_exception(exc, tb)
  File "../venv_3.8/lib/python3.8/site-packages/dask/local.py", line 316, in reraise
    raise exc
  File "../venv_3.8/lib/python3.8/site-packages/dask/local.py", line 222, in execute_task
    result = _execute_task(task, data)
  File "../venv_3.8/lib/python3.8/site-packages/dask/core.py", line 121, in _execute_task
    return func(*(_execute_task(a, cache) for a in args))
  File "../venv_3.8/lib/python3.8/site-packages/dask/dataframe/shuffle.py", line 378, in __call__
    import partd
  File "../venv_3.8/lib/python3.8/site-packages/partd/__init__.py", line 3, in <module>
    from .file import File
  File "../venv_3.8/lib/python3.8/site-packages/partd/file.py", line 9, in <module>
    from .core import Interface
  File "../venv_3.8/lib/python3.8/site-packages/partd/core.py", line 5, in <module>
    import locket
  File "../venv_3.8/lib/python3.8/site-packages/locket/__init__.py", line 15, in <module>
    raise ImportError("Platform not supported (failed to import fcntl, msvcrt)")
ImportError: Platform not supported (failed to import fcntl, msvcrt)

```

**Comment by TomAugspurger** [comment]
Strange. What does `import fcntl` give you in a python session?

**Comment by arunshankarc** [comment]
Below is output of `import fcntl` in python session:

```
(venv_3.7) bash-4.2$ python3.7
Python 3.7.9 (default, Sep 23 2020, 07:20:40)
[GCC 4.8.5 20150623 (Red Hat 4.8.5-39)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import fcntl
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'fcntl'
```

**Comment by TomAugspurger** [comment]
That's strange, since I think fcntl is part of the standard library. Do you know if it not being present is usual for Red Hat linux?

**Comment by arunshankarc** [comment]
I think this is environment issue. I tried in another linux machine and I could `import fcntl`. Thanks for looking into it.

**Comment by TomAugspurger** [comment]
Thanks. We'll close this since Dask doesn't have anything to do here.

FYI, you might be able to use the distributed scheduler. It may not use `locket`.
