### ISSUE TITLE
`set_index` can not cope with pandas dtypes

### ISSUE THREAD

**Issue by nils-braun** [dask/dask#6671]
**What happened**:

When calling `set_index` on a column with a nullable pandas dtype (e.g. `pd.Int64Dtype` or "Int64" for short), it fails with a 

```
Traceback (most recent call last):
  File "test_me.py", line 42, in <module>
    df.set_index("a", drop=False).compute()
  File "/home/nils/anaconda3/envs/dask-sql/lib/python3.8/site-packages/dask/dataframe/core.py", line 3750, in set_index
    return set_index(
  File "/home/nils/anaconda3/envs/dask-sql/lib/python3.8/site-packages/dask/dataframe/shuffle.py", line 84, in set_index
    divisions, sizes, mins, maxes = base.compute(
  File "/home/nils/anaconda3/envs/dask-sql/lib/python3.8/site-packages/dask/base.py", line 447, in compute
    results = schedule(dsk, keys, **kwargs)
  File "/home/nils/anaconda3/envs/dask-sql/lib/python3.8/site-packages/dask/threaded.py", line 76, in get
    results = get_async(
  File "/home/nils/anaconda3/envs/dask-sql/lib/python3.8/site-packages/dask/local.py", line 486, in get_async
    raise_exception(exc, tb)
  File "/home/nils/anaconda3/envs/dask-sql/lib/python3.8/site-packages/dask/local.py", line 316, in reraise
    raise exc
  File "/home/nils/anaconda3/envs/dask-sql/lib/python3.8/site-packages/dask/local.py", line 222, in execute_task
    result = _execute_task(task, data)
  File "/home/nils/anaconda3/envs/dask-sql/lib/python3.8/site-packages/dask/core.py", line 121, in _execute_task
    return func(*(_execute_task(a, cache) for a in args))
  File "/home/nils/anaconda3/envs/dask-sql/lib/python3.8/site-packages/dask/dataframe/partitionquantiles.py", line 416, in percentiles_summary
    vals, n = _percentile(data, qs, interpolation=interpolation)
  File "/home/nils/anaconda3/envs/dask-sql/lib/python3.8/site-packages/dask/array/percentile.py", line 25, in _percentile
    if np.issubdtype(a.dtype, np.datetime64):
  File "/home/nils/anaconda3/envs/dask-sql/lib/python3.8/site-packages/numpy/core/numerictypes.py", line 388, in issubdtype
    arg1 = dtype(arg1).type
TypeError: Cannot interpret 'Int64Dtype()' as a data type
```

**What you expected to happen**:

If running with an "int64" (instead of "Int64"), it works.

**Minimal Complete Verifiable Example**:

```python
import pandas as pd
import dask.dataframe as dd

df = pd.DataFrame({"a": [1, 2, 3]})
df["a"] = df["a"].astype("Int64")

df = dd.from_pandas(df, npartitions=1)
df.set_index("a", drop=False).compute()
```

**Environment**:

- Dask version: 2.24.0
- Python version: 3.8.5
- Operating System: ubuntu
- Install method (conda, pip, source): conda

**Comment by TomAugspurger** [comment]
Thanks for opening an issue.

Pandas doesn't support extension types in the index yet. So it's behavior is to cast to object dtype. We can either follow that or wait for pandas to support extension types in the index. Given the issues with object-dtype NAs in the index (https://github.com/pandas-dev/pandas/issues/34497, https://github.com/pandas-dev/pandas/issues/32931) I'm inclined to wait. What do you think?

**Comment by nils-braun** [comment]
Thanks for your answer. Makes a lot of sense to wait for pandas to support extension types. 

Just another question: would you suggest not using the extension types in dask until pandas has implemented them "completely" or would you say except the index, there are not that many open issues? Sorry for this very general question, I have unfortunately not followed the extension array discussions that much and would be interesting in your gut feeling on this.

**Comment by TomAugspurger** [comment]
As a maintainer, I'd be happy if you tried it out and reported things that don't work :)

But at a high-level, they're a bit immature right now (which is part of why they aren't the default). If you're often running into issues with pandas' type casting causing issues I'd recommend them. But if you already have workarounds in place for that then holding off isn't a bad idea.
