### ISSUE TITLE
Changes in 2.28.0 break complex custom graph

### ISSUE THREAD

**Issue by JSKenyon** [dask/dask#6684]
**What happened**:
After upgrading to `dask==2.28.0`, optimization causes custom graph construction to fail (specifically when dealing with multiple return i.e. adding multiple layers at once). I believe it is something to do with https://github.com/dask/dask/pull/6510. 

**What you expected to happen**:
I expected no change.

**Minimal Complete Verifiable Example**:
Apologies in advance - this is not as succinct as I would like, but this requires a certain level of complexity to demonstrate the problem. The following is a slightly simplified per-chunk unique operation supporting multiple return (i.e. passing kwargs to `np.unique`). 

```python
import dask.array as da
import numpy as np
from dask.base import tokenize
from dask.array.core import HighLevelGraph
from operator import getitem


def blockwise_unique(arr, return_inverse=False):

    if arr.ndim > 1:
        raise ValueError("Multi-dimensional arrays not yet supported.")

    arg_list = [0, return_inverse, 0]  # Align kwargs (simplified code).

    token = tokenize(arr, *arg_list)  # Append to names to make unique.

    unique_name = "unique-" + token

    # Create layer for the numpy.unique call.

    unique_dsk = {(unique_name, i): (np.unique, input_key, *arg_list)
                  for i, input_key in enumerate(arr.__dask_keys__())}

    n_return = 1 + sum(arg_list)
    consumed = 0

    input_name = arr.name
    input_graph = arr.__dask_graph__()
    input_deps = input_graph.dependencies
    out_chunks = ((np.nan,)*arr.npartitions,)

    # Without kwargs, no additional work is necessary and we can simply add
    # the layer to the graph and express the result as an array.

    if n_return == 1:

        graph = input_graph.from_collections(unique_name,
                                             unique_dsk,
                                             arr)

        return da.Array(graph,
                        name=unique_name,
                        chunks=out_chunks,
                        dtype=arr.dtype)

    # With kwargs, we need to add layers to split the tuple output of the
    # numpy.unique calls into separate layers. We ensure that these layers
    # all share the numpy.unique call as a dependency to avoid recomputation.

    outputs = ()
    layers = {input_name: input_graph, unique_name: unique_dsk}
    deps = {input_name: input_deps, unique_name: {input_name}}

    def getitem_layer(name, dsk, i):
        return {(name, j): (getitem, k, i) for j, k in enumerate(dsk.keys())}

    # Construct the unique value layer.

    uval_name = "unique-values-" + token

    values_dsk = getitem_layer(uval_name, unique_dsk, consumed)

    layers.update({uval_name: values_dsk})
    deps.update({uval_name: {unique_name}})
    consumed += 1

    # Construct the inverse layer.

    if return_inverse:

        uinv_name = "unique-inverse-" + token

        inverse_dsk = getitem_layer(uinv_name, unique_dsk, consumed)

        layers.update({uinv_name: inverse_dsk})
        deps.update({uinv_name: {unique_name}})
        consumed += 1

    # Construct the HighLevelGraph containing the relevant layers.

    graph = HighLevelGraph(layers, deps)

    # Turn each getitem layer into a dask.array which will contain the result.

    outputs += (da.Array(graph,
                         name=uval_name,
                         chunks=out_chunks,
                         dtype=arr.dtype),)

    if return_inverse:
        outputs += (da.Array(graph,
                             name=uinv_name,
                             chunks=arr.chunks,  # This is always the case.
                             dtype=np.int64),)

    return outputs


if __name__ == "__main__":

    test_data = da.random.randint(0, 5, size=(50,), chunks=(25,))

    unq = blockwise_unique(test_data)

    print(da.compute(unq, num_workers=12))

    unq, inv = blockwise_unique(test_data,
                                return_inverse=True)

    print(da.compute(unq, inv, num_workers=12))

```

**Traceback**
```
Traceback (most recent call last):
  File "test.py", line 110, in <module>
    print(da.compute(unq, inv, num_workers=12))
  File "/venvs/v2env/lib/python3.6/site-packages/dask/base.py", line 452, in compute
    results = schedule(dsk, keys, **kwargs)
  File "/venvs/v2env/lib/python3.6/site-packages/dask/threaded.py", line 84, in get
    **kwargs
  File "/venvs/v2env/lib/python3.6/site-packages/dask/local.py", line 503, in get_async
    return nested_get(result, state["cache"])
  File "/venvs/v2env/lib/python3.6/site-packages/dask/local.py", line 299, in nested_get
    return tuple([nested_get(i, coll) for i in ind])
  File "/venvs/v2env/lib/python3.6/site-packages/dask/local.py", line 299, in <listcomp>
    return tuple([nested_get(i, coll) for i in ind])
  File "/venvs/v2env/lib/python3.6/site-packages/dask/local.py", line 299, in nested_get
    return tuple([nested_get(i, coll) for i in ind])
  File "/venvs/v2env/lib/python3.6/site-packages/dask/local.py", line 299, in <listcomp>
    return tuple([nested_get(i, coll) for i in ind])
  File "/venvs/v2env/lib/python3.6/site-packages/dask/local.py", line 301, in nested_get
    return coll[ind]
KeyError: ('unique-values-bb2cf92bf4ff07158682402ed4d8d6b0', 0)
```

**Anything else we need to know?**:
The above example works with `dask<=2.27.0`. Setting `optimize_graph=False` makes it work with `dask=2.28.0`. Of course, that is not really an option.

I understand that this is a relatively involved use of dask, so I would appreciate any and all guidance.

**Environment**:

- Dask version: 2.27.0 and 2.28.0
- Python version: 3.6.9
- Operating System: Pop!_OS 18.04 LTS
- Install method (conda, pip, source): pip

**Comment by TomAugspurger** [comment]
Thanks for the reproducer. cc @madsbk if you have any guesses off the top of your head.

**Comment by JSKenyon** [comment]
I have made a little progress on figuring this out. There is a mistake in the code above which exposes this behaviour change. The offending line is:
```python
deps = {input_name: input_deps, unique_name: {input_name}}
```
This "double adds" the dependency, as input_deps is a dictionary, not a set. Changing this to:
```python
deps = input_deps
deps.update({unique_name: {input_name}})
```
makes this construction work again.

I am still experiencing related issues in an even more complicated graph, but it is simply too complex to make into a simple reproducer. I will leave this open for now and post any further findings. There has definitely been a change in behaviour between `2.27.0` and `2.28.0` though.

**Comment by JSKenyon** [comment]
I have made further progress - please ignore this issue until I post again. I think this is not precisely dask's fault. I think that I had some misconceptions about graph construction (or at least ho to accomplish it) which didn't break anything prior to `2.28.0` but now do. The exercise has been illuminating and I will likely close this issue, I just want to spend another day testing, just to be sure.

**Comment by JSKenyon** [comment]
I have figured out why the construction above was breaking and I can now get it to work in `2.28.0`. That said, I still don't exactly understand how the changes in #6510 affected graph construction, but I suspect it has something to so repeated (in my case accidentally) dependencies/layers being culled.
