### ISSUE TITLE
Reading multiple CSV files of 200 MB results in 'pandas.errors.ParserError: Error tokenizing data. C error: out of memory'

### ISSUE THREAD

**Issue by bedangSen** [dask/dask#6685]
**Minimal Complete Verifiable Example**:

```python
import dask.dataframe as dd

df = dd.read_csv('cmdlines\cmdlines_*.csv', 24000000, sample=100)
df.to_csv("cmdlines_stacked.csv", single_file = True)
```

**CSV Files I am reading**:

```
-rwxrwxrwx 1 <COMPUTER NAME> <COMPUTER NAME> 188507357 Aug 25 19:06 cmdlines_1.csv*
-rwxrwxrwx 1 <COMPUTER NAME> <COMPUTER NAME> 101147016 Aug 25 19:07 cmdlines_2.csv*
-rwxrwxrwx 1 <COMPUTER NAME> <COMPUTER NAME> 949642754 Aug 25 19:08 cmdlines_3.csv*
-rwxrwxrwx 1 <COMPUTER NAME> <COMPUTER NAME> 141084067 Aug 25 19:09 cmdlines_4.csv*
```

**What happened**:

```
(<VIRTUAL ENV>) PS <REDACTED PATH TO PROJECT>> python .\csv_stacker.py
Traceback (most recent call last):
  File ".\csv_stacker.py", line 4, in <module>
    df.to_csv("cmdlines_stacked.csv", single_file = True)
  File "<REDACTED PATH TO PROJECT>\<VIRTUAL ENV>\lib\site-packages\dask\dataframe\core.py", line 1417, in to_csv
    return to_csv(self, filename, **kwargs)
  File "<REDACTED PATH TO PROJECT>\<VIRTUAL ENV>\lib\site-packages\dask\dataframe\io\csv.py", line 850, in to_csv
    delayed(values).compute(**compute_kwargs)
  File "<REDACTED PATH TO PROJECT>\<VIRTUAL ENV>\lib\site-packages\dask\base.py", line 167, in compute
    (result,) = compute(self, traverse=False, **kwargs)
  File "<REDACTED PATH TO PROJECT>\<VIRTUAL ENV>\lib\site-packages\dask\base.py", line 447, in compute
    results = schedule(dsk, keys, **kwargs)
  File "<REDACTED PATH TO PROJECT>\<VIRTUAL ENV>\lib\site-packages\dask\threaded.py", line 76, in get
    results = get_async(
  File "<REDACTED PATH TO PROJECT>\<VIRTUAL ENV>\lib\site-packages\dask\local.py", line 486, in get_async
    raise_exception(exc, tb)
  File "<REDACTED PATH TO PROJECT>\<VIRTUAL ENV>\lib\site-packages\dask\local.py", line 316, in reraise
    raise exc
  File "<REDACTED PATH TO PROJECT>\<VIRTUAL ENV>\lib\site-packages\dask\local.py", line 222, in execute_task
    result = _execute_task(task, data)
  File "<REDACTED PATH TO PROJECT>\<VIRTUAL ENV>\lib\site-packages\dask\core.py", line 121, in _execute_task
    return func(*(_execute_task(a, cache) for a in args))
  File "<REDACTED PATH TO PROJECT>\<VIRTUAL ENV>\lib\site-packages\dask\dataframe\io\csv.py", line 149, in pandas_read_text
    df = reader(bio, **kwargs)
  File "<REDACTED PATH TO PROJECT>\<VIRTUAL ENV>\lib\site-packages\pandas\io\parsers.py", line 686, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "<REDACTED PATH TO PROJECT>\<VIRTUAL ENV>\lib\site-packages\pandas\io\parsers.py", line 458, in _read
    data = parser.read(nrows)
  File "<REDACTED PATH TO PROJECT>\<VIRTUAL ENV>\lib\site-packages\pandas\io\parsers.py", line 1186, in read
    ret = self._engine.read(nrows)
  File "<REDACTED PATH TO PROJECT>\<VIRTUAL ENV>\lib\site-packages\pandas\io\parsers.py", line 2145, in read
    data = self._reader.read(nrows)
  File "pandas\_libs\parsers.pyx", line 847, in pandas._libs.parsers.TextReader.read
  File "pandas\_libs\parsers.pyx", line 862, in pandas._libs.parsers.TextReader._read_low_memory
  File "pandas\_libs\parsers.pyx", line 918, in pandas._libs.parsers.TextReader._read_rows
  File "pandas\_libs\parsers.pyx", line 905, in pandas._libs.parsers.TextReader._tokenize_rows
  File "pandas\_libs\parsers.pyx", line 2042, in pandas._libs.parsers.raise_parser_error
pandas.errors.ParserError: Error tokenizing data. C error: out of memory
```

**What you expected to happen**:

Create a new CSV File stacking all the data from the four CSV files I am reading.

**Environment**:

- Dask version: dask==2.24.0
- Python version: Python 3.8.5
- Operating System: Microsoft Windows 10 Pro
- Processor: Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz, 2592 Mhz, 6 Core(s), 12 Logical Processor(s)
- Installed Physical Memory (RAM):	64.0 GB

- Install method (conda, pip, source): pip

**Comment by TomAugspurger** [comment]
What's the task graph look like from the `to_csv`? I think you could do `dsk = df.to_csv("cmdlines_stacked.csv", single_file = True, compute=False)` Then `dsk.visualize(optimize_graph=True)`.

I'm wondering if `single_file=True` forces a reduction to a single DataFrame.

**Comment by bedangSen** [comment]
So I tried adding the line of code after the `to_csv` function call. But it never gets there, and throws the same error as before. 

Here is what the documentation has to say about `singal_file=True`:

```
single_file:bool, default False
Whether to save everything into a single CSV file. Under the single file mode, each partition is appended at the end of the specified CSV file. Note that not all filesystems support the append mode and thus the single file mode, especially on cloud storage systems such as S3 or GCS. A warning will be issued when writing to a file that is not backed by a local filesystem.
```

**Comment by TomAugspurger** [comment]
That's strange since it shouldn't be computing with `compute=False`.

A reproducible example would be helpful here: http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports

**Comment by bedangSen** [comment]
Ahhh apologies, I had completely skipped over the `compute=False`. I amended it that and ran it again, and now I get a new error: 

**Code snippet**:
```python
dsk = df.to_csv("cmdlines_stacked.csv", single_file = True, compute=False)
dsk.visualize(filename="test.png")
```

**Output**:

```
Traceback (most recent call last):
  File ".\csv_stacker.py", line 6, in <module>
    dsk.visualize(optimize_graph=True)
AttributeError: 'list' object has no attribute 'visualize'
```

**Comment by TomAugspurger** [comment]
Might need something like `dask.visualize`. I don't recall the specifics. Anything you can do here to help debug this would be appreciated.

**Comment by jrbourbeau** [comment]
Closing due to lack of activity. @bedangSen feel free to re-open if you're still running into this issue
