### ISSUE TITLE
Boolean indexing crashes dask?

### ISSUE THREAD

**Issue by Illviljan** [dask/dask#6711]
**What happened**:
When using boolean indexing dask crashes.

**What you expected to happen**:
Behave like numpy:

```python
>>> import numpy as np
>>> a1 = np.array([1,2,3,4])
>>> a2 = np.array([0,1,1,0], dtype=bool)
>>> a3 = np.ones_like(a1)
>>> a3[a2] = a1[a2]
>>> a3
array([1, 2, 3, 1])
```

**Minimal Complete Verifiable Example**:
```python
>>> import dask.array as da
>>> da1 = da.array([1, 2, 3, 4])
>>> da2 = da.array([0, 1, 1, 0], dtype=bool)
>>> da3 = da.ones_like(da1)
>>> da3[da2] = da1[da2]
Traceback (most recent call last):

  File "<ipython-input-72-31cfb0c20342>", line 5, in <module>
    da3[da2] = da1[da2]

  File "C:\ProgramData\Anaconda3\lib\site-packages\dask\array\core.py", line 1531, in __setitem__
    y = where(key, value, self)

  File "C:\ProgramData\Anaconda3\lib\site-packages\dask\array\routines.py", line 1343, in where
    return elemwise(np.where, condition, x, y)

  File "C:\ProgramData\Anaconda3\lib\site-packages\dask\array\core.py", line 3991, in elemwise
    broadcast_shapes(*shapes)

  File "C:\ProgramData\Anaconda3\lib\site-packages\dask\array\core.py", line 3952, in broadcast_shapes
    "shapes {0}".format(" ".join(map(str, shapes)))

ValueError: operands could not be broadcast together with shapes (4,) (nan,) (4,)
```

**Environment**:

<details>
 <summary>Version</summary>

```
INSTALLED VERSIONS
------------------
commit: None
python: 3.7.9 (default, Aug 31 2020, 17:10:11) [MSC v.1916 64 bit (AMD64)]
python-bits: 64
OS: Windows
OS-release: 10
machine: AMD64
processor: Intel64 Family 6 Model 58 Stepping 9, GenuineIntel
byteorder: little
LC_ALL: None
LANG: en
LOCALE: None.None
libhdf5: 1.10.4
libnetcdf: None

xarray: 0.16.1
pandas: 1.1.1
numpy: 1.17.5
scipy: 1.4.1
netCDF4: None
pydap: None
h5netcdf: None
h5py: 2.10.0
Nio: None
zarr: None
cftime: 1.2.1
nc_time_axis: None
PseudoNetCDF: None
rasterio: None
cfgrib: None
iris: None
bottleneck: 1.3.2
dask: 2.27.0
distributed: 2.27.0
matplotlib: 3.3.1
cartopy: None
seaborn: 0.11.0
numbagg: None
pint: None
setuptools: 49.6.0.post20200814
pip: 20.2.2
conda: 4.8.5
pytest: 6.0.2
IPython: 7.18.1
sphinx: 3.2.1
```

</details>

**Comment by jsignell** [comment]
Thanks for bringing this up. As a workaround, you can use `where`:

```python
da3 = da.where(da2, da1, da3)
```

But since we just added this functionality to dask.dataframe, I suppose it makes sense to add to dask.array as well. If you are interested in working on this, you can follow #6608.

**Comment by Illviljan** [comment]
Adding in `Array.__getitem__`:
```python
if isinstance(index, Array):
    from .routines import where
    return where(index, self, np.nan)
```
Seems to indeed do the trick. 

I just put this above the string checks but I have no clue if that's where it belongs?

**Comment by Illviljan** [comment]
Running a pytest with this change didn't work at all so I dived in a little more trying to understand how this works with little success...

There's two problems I've gotten stuck with:
```python
>>> import dask.array as da
>>> from dask.array.routines import where

>>> da1 = da.array([1, 2, 3, 4])
>>> da2 = da.array([0, 1, 1, 0], dtype=bool)
>>> da3 = da.ones_like(da1)

>>> # array.__getitem__() shape becomes NaN:
>>> da1[da2].shape
(nan,)
>>> # The actual shape is smaller than da3:
>>> da1[da2].compute().shape
(2,)

>>> # array.__setitem__() gets da1[da2] as input and attempts to do:
>>>  y = where(da2, da1[da2], da3)
(...)
ValueError: operands could not be broadcast together with shapes (4,) (nan,) (4,)

>>> # Even if the shape was known it wouldn't work:
>>> y = where(da2, da1[da2].compute_chunk_sizes(), da3)
(...)
ValueError: operands could not be broadcast together with shapes (4,) (2,) (4,)
```

I think the DataFrame version doesn't have this problem because it doesn't modify its size but rather fills with nans instead?

**Comment by Illviljan** [comment]
I accidentally  tried just using `da3[da2] = da1` and apparently this is an allowed operation:
```python
>>> import dask.array as da
>>> da1 = da.array([1, 2, 3, 4])
>>> da2 = da.array([0, 1, 1, 0], dtype=bool)
>>> da3 = da.ones_like(da1)
>>> da3[da2] = da1
>>> da3.compute()
array([1, 2, 3, 1])
```
Is this a dask feature? Because it bypasses all the annoying parts with boolean indexing like NaN-shapes and different sizes of the arrays.

The downside is that it is not consistent at all with numpy:
```python
>>> import numpy as np
>>> a1 = np.array([1, 2, 3, 4])
>>> a2 = np.array([0, 1, 1, 0], dtype=bool)
>>> a3 = np.ones_like(a1)
>>> a3[a2] = a1
(...)
ValueError: NumPy boolean array indexing assignment cannot assign 4 input values to the 2 output values where the mask is true
```

**Comment by jsignell** [comment]
Oh I'm sorry! I guess the where trick is already in `Array.__setitem__`. It makes sense that the dask version expects the shape of the other array to match the original (since it is using where behind the scenes). 

I like the dask behavior better, but I'm not sure if it's an intentional difference or not. Do you think there is a good way to document this difference or to make the original error that you saw give a clearer pointer?

**Comment by Illviljan** [comment]
I was thinking if the shape error in `broadcast_shapes()` is triggered we could append:
```python
ValueError: operands could not be broadcast together with shapes (4,) (nan,) (4,). 
Hint: Valid boolean index assignment in Dask for equally shaped arrays is da1[da2] = da3. 
```

If we want to restrict when the hint shows a little bit we can guess that numpy-style indexing was being attempted by checking:
* If one of the shapes is nan.
* If one of the arrays were a getitem operation.

**Comment by jsignell** [comment]
Closing this now since the error is improved.
