### ISSUE TITLE
Dask Dataframe Write to File Object

### ISSUE THREAD

**Issue by CMCDragonkai** [dask/dask#6720]
**What happened**:

I used to be able to do this in a prior version of dask:

```
@dask.delayed
def save_csv(csv_url, df):
    logging.info("Saving output: %s", csv_url)
    with image_classifier.utils.open_file_url(
        csv_url, mode="w", encoding="utf-8", newline=""
    ) as csv_file:
        df.to_csv(csv_file, index=False)
```

**What you expected to happen**:

As you can see I'm writing the dataframe CSV to a file object.

However this is not possible anymore.

The new dask API seems to say:

```
Traceback (most recent call last):
  File "./test.py", line 14, in <module>
    df.to_csv(f, index=False, single_file=True)
  File "/nix/store/s4asri0fb8q5dgshn1ab8cz3mfgfl9m1-python3.7-dask-2.22.0/lib/python3.7/site-packages/dask/dataframe/core.py", line 1408, in to_csv
    return to_csv(self, filename, **kwargs)
  File "/nix/store/s4asri0fb8q5dgshn1ab8cz3mfgfl9m1-python3.7-dask-2.22.0/lib/python3.7/site-packages/dask/dataframe/io/csv.py", line 798, in to_csv
    first_file = open_file(filename, mode=mode, **file_options)
  File "/nix/store/74mar7c28mc4igypzn2dfqg5qqr89nbf-python3.7-fsspec-0.7.4/lib/python3.7/site-packages/fsspec/core.py", line 378, in open
    **kwargs
  File "/nix/store/74mar7c28mc4igypzn2dfqg5qqr89nbf-python3.7-fsspec-0.7.4/lib/python3.7/site-packages/fsspec/core.py", line 222, in open_files
    chain = _un_chain(urlpath, kwargs)
  File "/nix/store/74mar7c28mc4igypzn2dfqg5qqr89nbf-python3.7-fsspec-0.7.4/lib/python3.7/site-packages/fsspec/core.py", line 269, in _un_chain
    bits = [_un_chain(p, kwargs) for p in path]
  File "/nix/store/74mar7c28mc4igypzn2dfqg5qqr89nbf-python3.7-fsspec-0.7.4/lib/python3.7/site-packages/fsspec/core.py", line 269, in <listcomp>
    bits = [_un_chain(p, kwargs) for p in path]
  File "/nix/store/74mar7c28mc4igypzn2dfqg5qqr89nbf-python3.7-fsspec-0.7.4/lib/python3.7/site-packages/fsspec/core.py", line 284, in _un_chain
    if "::" in path
io.UnsupportedOperation: not readable
```

Why did dask remove the ability to write to a file object?

I need to write the entire dataframe into a file object, because that file object is accessing a custom storage system.

**Comment by CMCDragonkai** [comment]
DW, false alarm. I forgot I had changed to the pandas dataframe by this point.
