### ISSUE TITLE
ERROR: conda env create -n dask-dev -f continuous_integration/environment-latest.yaml

### ISSUE THREAD

**Issue by DavidKatz-il** [dask/dask#6808]
**What happened**:

Trying to create a `conda` environment has suggesting [here](https://docs.dask.org/en/latest/develop.html), it cause the following error:
```
(base) PS C:\...\GitHub\dask> conda env create -n dask-dev -f continuous_integration/environment-latest.yaml                                                                                     
# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "C:\...\anaconda3\lib\site-packages\conda\exceptions.py", line 1079, in __call__
        return func(*args, **kwargs)
      File "C:\...\anaconda3\lib\site-packages\conda_env\cli\main.py", line 80, in do_call
        exit_code = getattr(module, func_name)(args, parser)
      File "C:\...\anaconda3\lib\site-packages\conda_env\cli\main_create.py", line 87, in execute
        spec = specs.detect(name=name, filename=filename, directory=os.getcwd())
      File "C:\...\anaconda3\lib\site-packages\conda_env\specs\__init__.py", line 43, in detect
        if spec.can_handle():
      File "C:\...\anaconda3\lib\site-packages\conda_env\specs\yaml_file.py", line 18, in can_handle
        self._environment = env.from_file(self.filename)
      File "C:\...\anaconda3\lib\site-packages\conda_env\env.py", line 160, in from_file
        return from_yaml(yamlstr, filename=filename)
      File "C:\...\anaconda3\lib\site-packages\conda_env\env.py", line 142, in from_yaml
        data = validate_keys(data, kwargs)
      File "C:\...\anaconda3\lib\site-packages\conda_env\env.py", line 37, in validate_keys
        new_data = data.copy() if data else {}
    AttributeError: 'str' object has no attribute 'copy'

`$ C:\...\anaconda3\Scripts\conda-env-script.py create -n dask-dev -f continuous_integration/environment-latest.yaml`

  environment variables:
                 CIO_TEST=<not set>
  CONDA_AUTO_UPDATE_CONDA=false
        CONDA_DEFAULT_ENV=base
                CONDA_EXE=C:\...\anaconda3\Scripts\conda.exe
             CONDA_PREFIX=C:\...\anaconda3
    CONDA_PROMPT_MODIFIER=(base)
         CONDA_PYTHON_EXE=C:\...\anaconda3\python.exe
               CONDA_ROOT=C:\...\anaconda3
              CONDA_SHLVL=1
           CURL_CA_BUNDLE=<not set>
                 HOMEPATH=\...
                     PATH=C:\...\anaconda3;C:\...\anaconda3\Library\mingw-w64\bi
                          n;C:\...\anaconda3\Library\usr\bin;C:\...\anaconda3\Li
                          brary\bin;C:\...\anaconda3\Scripts;C:\...\anaconda3\bi
                          n;C:\...\anaconda3;C:\...\anaconda3\Library\mingw-w64\
                          bin;C:\...\anaconda3\Library\usr\bin;C:\...\anaconda3\
                          Library\bin;C:\...\anaconda3\Scripts;C:\...\anaconda3\
                          bin;C:\...\anaconda3\condabin;C:\Program Files (x86)\Common Fi
                          les\Oracle\Java\javapath;C:\Windows\System32;C:\Windows;C:\Windows\Sys
                          tem32\wbem;C:\Windows\System32\WindowsPowerShell\v1.0;C:\Windows\Syste
                          m32\OpenSSH;C:\Program Files\Microsoft SQL
                          Server\130\Tools\Binn;C:\Program Files\Git\cmd;C:\PROGRA~1\Java\JDK18~
                          1.0_2\bin;C:\Hadoop\hadoop-3.1.0\bin;.;C:\Program Files\Docker\Docker\
                          resources\bin;C:\ProgramData\DockerDesktop\version-bin;C:\Program File
                          s\nodejs;C:\...\AppData\Local\Microsoft\WindowsApps;C:\..
                          .\AppData\Local\GitHubDesktop\bin;C:\...\AppData\Local\Prog
                          rams\Microsoft VS
                          Code\bin;C:\Progra~1\Java\jdk1.8.0_251\bin;C:\Spark\spark-2.4.6-bin-
                          hadoop2.7\bin;C:\Hadoop\hadoop-3.1.0\bin;.;C:\Program
                          Files\JetBrains\IntelliJ IDEA 2020.1.4\bin;.;C:\Program Files
                          (x86)\GitHub CLI;C:\...\AppData\Local\Microsoft\WindowsApps;C:
                          \...\AppData\Roaming\npm
             PSMODULEPATH=C:\...\WindowsPowerShell\Modules;C:\Program Files\Wi
                          ndowsPowerShell\Modules;C:\WINDOWS\system32\WindowsPowerShell\v1.0\Mod
                          ules
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>

     active environment : base
    active env location : C:\...\anaconda3
            shell level : 1
       user config file : C:\...\.condarc
 populated config files : C:\...\.condarc
          conda version : 4.9.1
    conda-build version : 3.18.11
         python version : 3.8.3.final.0
       virtual packages : __win=0=0
                          __archspec=1=x86_64
       base environment : C:\...\anaconda3  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/win-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\...\anaconda3\pkgs
                          C:\...\.conda\pkgs
                          C:\...\AppData\Local\conda\conda\pkgs
       envs directories : C:\...\anaconda3\envs
                          C:\...\.conda\envs
                          C:\...\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.9.1 requests/2.24.0 CPython/3.8.3 Windows/10 Windows/10.0.18362
          administrator : False
             netrc file : None
           offline mode : False

An unexpected error has occurred. Conda has prepared the above report.
```

**Anything else we need to know?**:

When running the following line it works fine and successfully create a `conda` environment:
```
 conda env create -n dask-dev -f continuous_integration/environment-3.8.yaml
```

**Environment**:
- Python version: 3.8.3
- Operating System: Windows
- Install method (conda, pip, source): conda

**Comment by quasiben** [comment]
Does the same occur with `environment-3.8.yaml` ?

**Comment by DavidKatz-il** [comment]
> **Anything else we need to know?**:
> 
> When running the following line it works fine and successfully create a `conda` environment:
> 
> ```
>  conda env create -n dask-dev -f continuous_integration/environment-3.8.yaml
> ```

> Does the same occur with `environment-3.8.yaml`?

**Comment by jrbourbeau** [comment]
I think our documentation might be out of date as it doesn't look like we use `continuous_integration/environment-latest.yaml` anywhere. We should update the docs to point to `environment-3.8.yaml` instead. @DavidKatz-il is that something you'd be interested in working on? (no obligation though)

**Comment by quasiben** [comment]
@DavidKatz-il apologies, my eyes passed over your notes there

**Comment by DavidKatz-il** [comment]
> I think our documentation might be out of date as it doesn't look like we use `continuous_integration/environment-latest.yaml` anywhere. We should update the docs to point to `environment-3.8.yaml` instead. @DavidKatz-il is that something you'd be interested in working on? (no obligation though)

I will be happy to make a PR.
Does it need to be changed only [here](https://github.com/dask/dask/blob/5bf5b70eabf87aa461e44bbcbc249e4cf0a93838/docs/source/develop.rst)?

**Comment by TomAugspurger** [comment]
Environment-latest is a symlink to `environment-3.8.yaml`. I think it's there just for the contributing docs.

@DavidKatz-il do you see the same error? Maybe conda doesn't follow symlinks on some platforms?

**Comment by DavidKatz-il** [comment]
> Environment-latest is a symlink to `environment-3.8.yaml`. I think it's there just for the contributing docs.
> 
> @DavidKatz-il do you see the same error? Maybe conda doesn't follow symlinks on some platforms?

I'm not sure that I'm understanding your question.
I saw that it's only a Symbolic Link, but when running ``` conda env create -n dask-dev -f continuous_integration/environment-latest.yaml``` on a `Windows` machine it didn't work.

Are you familiar with a way that in the docs it will automatically show ``` conda env create -n dask-dev -f continuous_integration/environment-3.8.yaml``` instead of ```conda env create -n dask-dev -f continuous_integration/environment-latest.yaml```

**Comment by GenevieveBuckley** [comment]
Do we have someone with access to a Windows machine who can reproduce this? (I have access to linux and mac computers, but not Windows).

If we go with the suggestion to update the developer installation docs, I've opened https://github.com/dask/dask/pull/8259 here. I'm also happy if we can find a better (non-documentation) fix, too.
