### ISSUE TITLE
read_parquet from an S3 bucket with many partitions takes hours

### ISSUE THREAD

**Issue by aburkov** [dask/dask#6920]
The problematic code:

`text_df = dd.read_parquet(f"s3://{data_read_bucket}/{data_read_dir}", columns=[id_column, text_column])`

**What happened**: When f"s3://{data_read_bucket}/{data_read_dir}" is a partitioned parquet on S3 and contains thousands of parquet files, Dask executes read_parquet for hours.

**What you expected to happen**: instant execution because no data is really read. I understand that read_parquet reads some metadata about the parquet files. Can this be done in parallel?

**Environment**: AWS S3

- Dask version: 2.30.0
- Python version: Python 3.8.6
- Operating System: AWS Linux V2
- Install method (conda, pip, source): conda

**Comment by jsignell** [comment]
It would be helpful to know whether you are using pyrarrow or fastparquet along with the version. But I suspect that reading thousands of parquet files is expected to be slow. You might have better luck consolidating them into fewer/larger files.

**Comment by rjzamora** [comment]
In addition to knowing the backend you are using (pyarrow vs fastparquet), I am also interested to know if there is a shared `_metadata` file available?  If not, you may want to consider generating one with the [create_metadata_file](https://github.com/dask/dask/blob/c58b031c6f979d93e67d66e982693dbea9daea71/dask/dataframe/io/parquet/core.py#L667) utility (currently requires pyarrow).  It is certainly possible to parse the metadata in parallel, but for now graph construction (including metadata collection) is currently performed on the client only for `read_parquet`.

If the engine is "pyarrow", I'd also be interested to know if using `engine="pyarrow-dataset"` improves performance at all (however, that would require building from the latest source)

**Comment by rjzamora** [comment]
#6921 proposes a way to collect metadata in parallel when `_metadata` is missing (for pyarrow only).

**Comment by aburkov** [comment]
Thank you. We will try to generate _metadata file when we dump the data to S3. Our devops team uses Spark for dumping data from database to S3, I asked them to see if they can do that.

As for using engine="pyarrow" I have a different trouble with it. It only works when engine is fastparquet. Otherwise, here's the error:

```
/home/aburkov/anaconda3/lib/python3.8/site-packages/pyarrow/filesystem.py:412: RuntimeWarning: coroutine 'S3FileSystem._ls' was never awaited
  for key in list(self.fs._ls(path, refresh=refresh)):
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
Traceback (most recent call last):
  File "/home/aburkov/p/VS_Code_Projects/SkillExtractor/extract_skill_relationships.py", line 144, in <module>
    text_df = dd.read_parquet(f"s3://{data_read_bucket}/{data_read_dir}", columns=[id_column, text_column], gather_statistics = False, engine="pyarrow")
  File "/home/aburkov/anaconda3/lib/python3.8/site-packages/dask/dataframe/io/parquet/core.py", line 231, in read_parquet
    meta, statistics, parts, index = engine.read_metadata(
  File "/home/aburkov/anaconda3/lib/python3.8/site-packages/dask/dataframe/io/parquet/arrow.py", line 655, in read_metadata
    ) = _gather_metadata(
  File "/home/aburkov/anaconda3/lib/python3.8/site-packages/dask/dataframe/io/parquet/arrow.py", line 166, in _gather_metadata
    dataset, base, fns = _get_dataset_object(paths, fs, filters, dataset_kwargs)
  File "/home/aburkov/anaconda3/lib/python3.8/site-packages/dask/dataframe/io/parquet/arrow.py", line 144, in _get_dataset_object
    dataset = pq.ParquetDataset(paths[0], filesystem=fs, filters=filters, **kwargs)
  File "/home/aburkov/anaconda3/lib/python3.8/site-packages/pyarrow/parquet.py", line 1180, in __init__
    self.metadata_path) = _make_manifest(
  File "/home/aburkov/anaconda3/lib/python3.8/site-packages/pyarrow/parquet.py", line 1357, in _make_manifest
    manifest = ParquetManifest(path_or_paths, filesystem=fs,
  File "/home/aburkov/anaconda3/lib/python3.8/site-packages/pyarrow/parquet.py", line 930, in __init__
    self._visit_level(0, self.dirpath, [])
  File "/home/aburkov/anaconda3/lib/python3.8/site-packages/pyarrow/parquet.py", line 945, in _visit_level
    _, directories, files = next(fs.walk(base_path))
  File "/home/aburkov/anaconda3/lib/python3.8/site-packages/pyarrow/filesystem.py", line 412, in walk
    for key in list(self.fs._ls(path, refresh=refresh)):
TypeError: 'coroutine' object is not iterable
```

Googling didn't result in any suggestions.

We will also try your recent fix #6921. I'll let you know if there's a difference.

**Comment by rjzamora** [comment]
>As for using engine="pyarrow" I have a different trouble with it. It only works when engine is fastparquet. Otherwise, here's the error:

Interesting - Can you share your pyarrow version? 2.0.0 has known FS problems.

**Comment by aburkov** [comment]
Sorry, I reinstalled anaconda, and the problem with pyarrow was solved before you I saw your request. I didn't keep the version from the previous installation.

I installed the version of dask with the fix #6921 in it and it's still slow. What I noticed is that in dask/dataframe/io/parquet/arrow.py the execution goes inside this if:

```
            if not (split_row_groups or gather_statistics):
                # Don't need to construct real metadata if
                # we are not gathering statistics or splitting
                # by row-group
                metadata = [p.path for p in dataset.pieces]
                
                if schema is None:
                    schema = dataset.pieces[0].get_metadata().schema.to_arrow_schema()
                return (
                    schema,
                    metadata,
                    base,
                    partition_info,
                    split_row_groups,
                    gather_statistics,
                )
```

so, if I understand correctly, the metadata is only read from one partition in this line:

`schema = dataset.pieces[0].get_metadata().schema.to_arrow_schema()`

However, this line still takes hours to execute:

`text_df = dd.read_parquet(f"s3://{data_read_bucket}/{data_read_dir}", columns=[id_column, text_column], gather_statistics = False, split_row_groups = False, engine = "pyarrow-legacy")`

The number of partitions si 10k. The size of one partition is ~37 megabytes.

**Comment by rjzamora** [comment]
>so, if I understand correctly, the metadata is only read from one partition in this line:

Right - For the code you are running (`gather_statistics = False, split_row_groups = False`), I wouldn't expect metadata parsing to scale with the number of files, because we only read the footer metadata on the first file.

Given that you are not splitting by row-group or gathering statistics, I am a bit surprised that it is taking so long to execute `read_parquet`.  My understanding is that the majority of time should correspond to the discovery of all paths in the dataset (ie. the file system).  Is it possible to try specifying a small subset of the files and collect a simple profile (using something like prun)?

**Comment by jrbourbeau** [comment]
Just checking in here, @aburkov are you able to try @rjzamora's suggestion of specifying a small subset of the files and collect a simple profile (using something like prun)?

**Comment by jrbourbeau** [comment]
Closing due to lack of activity. Feel free to re-open if you'd like to continue
