### ISSUE TITLE
"Event loop was unresponsive in Worker" during df.set_index

### ISSUE THREAD

**Issue by stephanie-wang** [dask/dask#6983]
**What happened**:

I'm trying to call df.set_index on a large dataframe (10GB, with 64GiB RAM) and am seeing lots of errors, followed by Dask worker crashes and restarts. At first, I see 100% CPU usage, then close to 0% CPU with some disk writes from Dask workers (which I assume is spilling to disk), then many errors like this:
```
distributed.core - INFO - Event loop was unresponsive in Worker for 7.13s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
```

Eventually, the workers seem to get repeatedly killed and restarted, and I think the script is not making any progress.

I tried also experimenting with the number of partitions (10, 20, 50). With fewer partitions, I get this error instead (also eventually crashes):

```
distributed.worker - WARNING - Memory use is high but worker has no data to store to disk.  Perhaps some other process is leaking memory?  Process memory: 3.25 GB -- Worker memory limit: 4.12 GB
```

**What you expected to happen**: I thought this would spill to disk if needed, but wasn't expecting the crashes. It's possible this would have finished successfully after some time, but it seemed like no progress was being made (I killed it after several minutes).

**Minimal Complete Verifiable Example**: [Here](https://gist.github.com/stephanie-wang/842669be51a263e5637c0e5ba0236132) is a minimal script that reproduces the issue. It uses Dask to generate one file per partition, then calls `df.set_index().compute()`.
Run this script with `python dask_sort.py --nbytes 10_000_000_000` (sort 10GB of data, 100 partitions of 100MB each).

**Anything else we need to know?**: 

**Environment**:

- Dask version: 2.23 (Dask.distributed, dask-worker with --nprocs 16 --nthreads 1)
- Python version: 3.6
- Operating System: Ubuntu 18.04, Ubuntu 18.04, 16 CPU, 64GiB RAM.
- Install method (conda, pip, source): pip

I'm not sure if this is the right place for this, or if something is wrong with my setup. Please let me know if so!

**Comment by rjzamora** [comment]
From a quick look at your script, I would guess that the `compute()` is causing most of the pain.  Calling `compute` means that you are performing the `set_index` (already an expensive operation), and then converting your Dask DataFrame to a Pandas DataFrame - which requires all 10GB of data to be sent from your workers to your client process.

I suggst that you try the following to time a `set_index` operation:

```python
from dask.distributed import wait

...
trial_start = time.time()
df2 = set_index("a")
wait(df2.persist())
trial_end = time.time()
client.cancel(df2)
...
```

Note that you will need to [aggressively clear d2 from memory](https://distributed.dask.org/en/latest/memory.html#aggressively-clearing-data) to ensure that trials are actually independent.

**Comment by stephanie-wang** [comment]
Thanks, I'll try that out!

**Comment by stephanie-wang** [comment]
Hmm I tried this out without the `.compute()` call, and I'm still seeing similar errors. Here is some more output from the worker logs if it's helpful:
```
istributed.nanny - INFO - Worker process 29750 was killed by signal 15
distributed.worker - ERROR - Worker stream died during communication: tcp://127.0.0.1:44401
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/distributed/comm/tcp.py", line 184, in read
    n_frames = await stream.read_bytes(8)
tornado.iostream.StreamClosedError: Stream is closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/distributed/worker.py", line 1980, in gather_dep
    self.rpc, deps, worker, who=self.address
  File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/distributed/worker.py", line 3251, in get_data_from_worker
    return await retry_operation(_get_data, operation="get_data_from_worker")
  File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/distributed/utils_comm.py", line 390, in retry_operation
    operation=operation,
  File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/distributed/utils_comm.py", line 370, in retry
    return await coro()
  File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/distributed/worker.py", line 3238, in _get_data
    max_connections=max_connections,
  File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/distributed/core.py", line 589, in send_recv
    response = await comm.read(deserializers=deserializers)
  File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/distributed/comm/tcp.py", line 199, in read
    convert_stream_closed_error(self, e)
  File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/distributed/comm/tcp.py", line 123, in convert_stream_closed_error
    raise CommClosedError("in %s: %s" % (obj, exc))
distributed.comm.core.CommClosedError: in <closed TCP>: Stream is closed
distributed.core - INFO - Event loop was unresponsive in Worker for 3.41s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
```
