### ISSUE TITLE
groupby raises: negative dimensions are not allowed

### ISSUE THREAD

**Issue by jangorecki** [dask/dask#6990]
**What happened**:

Unexpected exception during groupby operation.

**What you expected to happen**:

Compute sum by group and number of rows in group.

**Minimal Complete Verifiable Example**:

Reproducible on 5GB csv dataset, generate data using:

```sh
wget https://raw.githubusercontent.com/h2oai/db-benchmark/783a677bd53196ab9b9a97b35ef488687fa2bc79/_data/groupby-datagen.R
Rscript groupby-datagen.R 1e8 1e2 0 0
python
```

Reproduce error
```py
import dask as dk
import dask.dataframe as dd
from dask import distributed
client = distributed.Client(processes=True, silence_logs=logging.ERROR)
# running on local cluster of processes
dk.config.set({"optimization.fuse.ave-width": 20})
dk.__version__
#'2020.12.0'
x = dd.read_csv("G1_1e8_1e2_0_0.csv", dtype={"id1":"category", "id2":"category", "id3":"category", "id4":"Int32", "id5":"Int32", "id6":"Int32", "v1":"Int32", "v2":"Int32", "v3":"float64"})
x = x.persist()
in_rows = len(x)
print(in_rows, flush=True)
#100000000
ans = x.groupby(['id1','id2','id3','id4','id5','id6']).agg({'v3':'sum', 'v1':'size'}).compute()
```
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jan/git/db-benchmark/dask/py-dask/lib/python3.6/site-packages/dask/base.py", line 279, in compute
    (result,) = compute(self, traverse=False, **kwargs)
  File "/home/jan/git/db-benchmark/dask/py-dask/lib/python3.6/site-packages/dask/base.py", line 567, in compute
    results = schedule(dsk, keys, **kwargs)
  File "/home/jan/git/db-benchmark/dask/py-dask/lib/python3.6/site-packages/distributed/client.py", line 2632, in get
    results = self.gather(packed, asynchronous=asynchronous, direct=direct)
  File "/home/jan/git/db-benchmark/dask/py-dask/lib/python3.6/site-packages/distributed/client.py", line 1931, in gather
    asynchronous=asynchronous,
  File "/home/jan/git/db-benchmark/dask/py-dask/lib/python3.6/site-packages/distributed/client.py", line 780, in sync
    self.loop, func, *args, callback_timeout=callback_timeout, **kwargs
  File "/home/jan/git/db-benchmark/dask/py-dask/lib/python3.6/site-packages/distributed/utils.py", line 347, in sync
    raise exc.with_traceback(tb)
  File "/home/jan/git/db-benchmark/dask/py-dask/lib/python3.6/site-packages/distributed/utils.py", line 331, in f
    result[0] = yield future
  File "/home/jan/git/db-benchmark/dask/py-dask/lib/python3.6/site-packages/tornado/gen.py", line 1133, in run
    value = future.result()
  File "/home/jan/git/db-benchmark/dask/py-dask/lib/python3.6/site-packages/distributed/client.py", line 1790, in _gather
    raise exception.with_traceback(traceback)
  File "/home/jan/git/db-benchmark/dask/py-dask/lib/python3.6/site-packages/dask/utils.py", line 30, in apply
    return func(*args, **kwargs)
  File "/home/jan/git/db-benchmark/dask/py-dask/lib/python3.6/site-packages/dask/dataframe/groupby.py", line 920, in _groupby_apply_
funcs
    r = func(grouped, **func_kwargs)
  File "/home/jan/git/db-benchmark/dask/py-dask/lib/python3.6/site-packages/dask/dataframe/groupby.py", line 964, in _apply_func_to_
column
    return func(df_like[column])
  File "/home/jan/git/db-benchmark/dask/py-dask/lib/python3.6/site-packages/dask/utils.py", line 894, in __call__
    return getattr(obj, self.method)(*args, **kwargs)
  File "/home/jan/git/db-benchmark/dask/py-dask/lib/python3.6/site-packages/pandas/core/groupby/groupby.py", line 1537, in size
    return self._reindex_output(result, fill_value=0)
  File "/home/jan/git/db-benchmark/dask/py-dask/lib/python3.6/site-packages/pandas/core/groupby/groupby.py", line 2718, in _reindex_
output
    levels_list, names=self.grouper.names
  File "/home/jan/git/db-benchmark/dask/py-dask/lib/python3.6/site-packages/pandas/core/indexes/multi.py", line 565, in from_product
    codes = cartesian_product(codes)
  File "/home/jan/git/db-benchmark/dask/py-dask/lib/python3.6/site-packages/pandas/core/reshape/util.py", line 51, in cartesian_prod
uct
    return [_tile_compat(np.repeat(x, b[i]), np.product(a[i])) for i, x in enumerate(X)]
  File "/home/jan/git/db-benchmark/dask/py-dask/lib/python3.6/site-packages/pandas/core/reshape/util.py", line 51, in <listcomp>
    return [_tile_compat(np.repeat(x, b[i]), np.product(a[i])) for i, x in enumerate(X)]
  File "/home/jan/git/db-benchmark/dask/py-dask/lib/python3.6/site-packages/numpy/core/fromnumeric.py", line 445, in repeat
    return _wrapfunc(a, 'repeat', repeats, axis=axis)
  File "/home/jan/git/db-benchmark/dask/py-dask/lib/python3.6/site-packages/numpy/core/fromnumeric.py", line 51, in _wrapfunc
    return getattr(obj, method)(*args, **kwds)
ValueError: negative dimensions are not allowed
```

**Anything else we need to know?**:

**Environment**:

- Dask version: 2020.12.0
- Python version: 3.6
- Operating System: Linux
- Install method (conda, pip, source): pip

**Comment by quasiben** [comment]
@jangorecki I took the time to install R and generate the dataset but I'm not sure what's happening here.  When running with  a sample of the data (first 100 rows), everything worked smoothly .  Out of curiosity I tried this with pandas and was unable to accomplish the task:

> MemoryError: Unable to allocate 6.74 EiB for an array with shape (7766279631452241600,) and data type int8

The message above leads me to believe that we are hitting some memory error in the dask case.  Does this also fail if instead of persisting prior to the groupby call, you execute compute() directly after read_csv ?

**Comment by quasiben** [comment]
Also, have you tested with Dask.Distributed ?

**Comment by jsignell** [comment]
From the traceback it looks like you are using distributed, it'd be helpful to include that set up in the MRE

**Comment by jangorecki** [comment]
@quasiben for pandas you probably need to add `observed=True` in `groupby` call.
@jschendel Sorry, I simplified code to much, already added missing piece in my first post.

**Comment by jangorecki** [comment]
In recent dask 2021.04.1 I am getting now the following error
```
Traceback (most recent call last):
  File "./dask/groupby-dask.py", line 5, in <module>
    exec(open("./dask/groupby-dask2.py").read())
  File "<string>", line 309, in <module>
  File "/home/jan/git/db-benchmark/dask/py-dask/lib/python3.7/site-packages/dask
/base.py", line 285, in compute
    (result,) = compute(self, traverse=False, **kwargs)
  File "/home/jan/git/db-benchmark/dask/py-dask/lib/python3.7/site-packages/dask
/base.py", line 567, in compute
    results = schedule(dsk, keys, **kwargs)
  File "/home/jan/git/db-benchmark/dask/py-dask/lib/python3.7/site-packages/dist
ributed/client.py", line 2666, in get
    results = self.gather(packed, asynchronous=asynchronous, direct=direct)
  File "/home/jan/git/db-benchmark/dask/py-dask/lib/python3.7/site-packages/dist
ributed/client.py", line 1981, in gather
    asynchronous=asynchronous,
  File "/home/jan/git/db-benchmark/dask/py-dask/lib/python3.7/site-packages/dist
ributed/client.py", line 844, in sync
    self.loop, func, *args, callback_timeout=callback_timeout, **kwargs
  File "/home/jan/git/db-benchmark/dask/py-dask/lib/python3.7/site-packages/dist
ributed/utils.py", line 353, in sync
    raise exc.with_traceback(tb)
  File "/home/jan/git/db-benchmark/dask/py-dask/lib/python3.7/site-packages/dist
ributed/utils.py", line 336, in f
    result[0] = yield future
  File "/home/jan/git/db-benchmark/dask/py-dask/lib/python3.7/site-packages/torn
ado/gen.py", line 762, in run
    value = future.result()
  File "/home/jan/git/db-benchmark/dask/py-dask/lib/python3.7/site-packages/dist
ributed/client.py", line 1840, in _gather
    raise exception.with_traceback(traceback)
distributed.scheduler.KilledWorker: ("('aggregate-combine-63e10a348d6782ffeda58d
daf71e054f', 2, 0, 0)", <Worker 'tcp://127.0.0.1:41469', name: 7, memory: 0, pro
cessing: 1>)
distributed.core - ERROR - Exception while handling op heartbeat_worker
Traceback (most recent call last):
  File "/home/jan/git/db-benchmark/dask/py-dask/lib/python3.7/site-packages/dist
ributed/core.py", line 497, in handle_comm
    result = handler(comm, **msg)
  File "/home/jan/git/db-benchmark/dask/py-dask/lib/python3.7/site-packages/dist
ributed/scheduler.py", line 3821, in heartbeat_worker
    parent._tasks[key]: duration for key, duration in executing.items()
  File "/home/jan/git/db-benchmark/dask/py-dask/lib/python3.7/site-packages/dist
ributed/scheduler.py", line 3821, in <dictcomp>
    parent._tasks[key]: duration for key, duration in executing.items()
KeyError: "('aggregate-chunk-aggregate-combine-63e10a348d6782ffeda58ddaf71e054f'
, 2, 1, 0)"
tornado.application - ERROR - Exception in callback functools.partial(<bound met
hod IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOLoop objec
t at 0x7fa2f528eed0>>, <Task finished coro=<Worker.heartbeat() done, defined at 
/home/jan/git/db-benchmark/dask/py-dask/lib/python3.7/site-packages/distributed/
worker.py:942> exception=KeyError("('aggregate-chunk-aggregate-combine-63e10a348
d6782ffeda58ddaf71e054f', 2, 1, 0)")>)
Traceback (most recent call last):
  File "/home/jan/git/db-benchmark/dask/py-dask/lib/python3.7/site-packages/torn
ado/ioloop.py", line 741, in _run_callback
    ret = callback()
  File "/home/jan/git/db-benchmark/dask/py-dask/lib/python3.7/site-packages/torn
ado/ioloop.py", line 765, in _discard_future_result
    future.result()
  File "/home/jan/git/db-benchmark/dask/py-dask/lib/python3.7/site-packages/dist
ributed/worker.py", line 960, in heartbeat
    for key in active_keys
  File "/home/jan/git/db-benchmark/dask/py-dask/lib/python3.7/site-packages/dist
ributed/utils_comm.py", line 390, in retry_operation
    operation=operation,
  File "/home/jan/git/db-benchmark/dask/py-dask/lib/python3.7/site-packages/dist
ributed/utils_comm.py", line 370, in retry
    return await coro()
  File "/home/jan/git/db-benchmark/dask/py-dask/lib/python3.7/site-packages/dist
ributed/core.py", line 862, in send_recv_from_rpc
    result = await send_recv(comm=comm, op=key, **kwargs)
  File "/home/jan/git/db-benchmark/dask/py-dask/lib/python3.7/site-packages/dist
ributed/core.py", line 661, in send_recv
    raise exc.with_traceback(tb)
  File "/home/jan/git/db-benchmark/dask/py-dask/lib/python3.7/site-packages/dist
ributed/core.py", line 497, in handle_comm
    result = handler(comm, **msg)
  File "/home/jan/git/db-benchmark/dask/py-dask/lib/python3.7/site-packages/dist
ributed/scheduler.py", line 3821, in heartbeat_worker
    parent._tasks[key]: duration for key, duration in executing.items()
  File "/home/jan/git/db-benchmark/dask/py-dask/lib/python3.7/site-packages/dist
ributed/scheduler.py", line 3821, in <dictcomp>
    parent._tasks[key]: duration for key, duration in executing.items()
KeyError: "('aggregate-chunk-aggregate-combine-63e10a348d6782ffeda58ddaf71e054f'
, 2, 1, 0)"
```
note that I also added `observed=True` to groupby call as it is now supported

**Comment by jrbourbeau** [comment]
Thanks @jangorecki -- see https://github.com/dask/distributed/issues/4587

**Comment by mrocklin** [comment]
This is maybe now resolved
