### ISSUE TITLE
Key Error in distributed worker tasks dictionary

### ISSUE THREAD

**Issue by chrisroat** [dask/dask#6999]
**What happened**:

In a dask-gateway GKE cluster, I have a graph that consistently stalls with the error below.  The error appears across many workers, and they all get wedged -- all referencing the same key value.  The workers stop communicating (last seen of 15+ minutes) and stop doing any work .  Killing the corresponding GKE pods does not help -- the scheduler still seems to happily wait for them.  I did not see any errors in the scheduler.

```
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/distributed/worker.py", line 2627, in execute
    self.ensure_communicating()
  File "/opt/conda/lib/python3.8/site-packages/distributed/worker.py", line 1880, in ensure_communicating
    to_gather, total_nbytes = self.select_keys_for_gather(
  File "/opt/conda/lib/python3.8/site-packages/distributed/worker.py", line 1985, in select_keys_for_gather
    total_bytes = self.tasks[dep].get_nbytes()
KeyError: 'xarray-image-bc4e1224600f3930ab9b691d1009ed0c'
```

```
tornado.application - ERROR - Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOLoop object at 0x7fac3d04f4f0>>, <Task finished name='Task-143' coro=<Worker.execute() done, defined at /opt/conda/lib/python3.8/site-packages/distributed/worker.py:2524> exception=KeyError('xarray-image-bc4e1224600f3930ab9b691d1009ed0c')>)
```

**What you expected to happen**:

Ideally, the key would not be missing.  At the very least, the worker would go away and be replaced with a new worker.

**Minimal Complete Verifiable Example**:

Running locally on a small data sample does not show the problem.

**Environment**:

- Dask version: 2020.12.0 (dask-gateway 0.9.0)
- Python version: 3.8
- Operating System: Ubuntu
- Install method (conda, pip, source): conda

What might cause this?  Is there something else I should be looking into?

**Comment by chrisroat** [comment]
Belongs in dask/distributed: https://github.com/dask/distributed/issues/4382
