### ISSUE TITLE
"Gaps in blk ref_locs" error during join on categorical column

### ISSUE THREAD

**Issue by jangorecki** [dask/dask#7015]
**What happened**:

Confusing error that does not provide really any useful information for user, and seems more like an internal error.

**What you expected to happen**:

No error, join computed successfully. Eventually an error which is more meaningful.

**Minimal Complete Verifiable Example**:

I tried to provide minimal example but it does work properly on a 2-3 rows datasets. Below code generates 0.5 GB dataset.

```sh
wget https://raw.githubusercontent.com/h2oai/db-benchmark/f9a6ce54db7d7b6cdab0780306c990f197a5e3e0/_data/join-datagen.R
Rscript join-datagen.R 1e7 0 5 0
python
```

Reproduce error
```py
import dask as dk
import dask.dataframe as dd
from dask import distributed
client = distributed.Client(processes=True, silence_logs=logging.ERROR)
dk.config.set({"optimization.fuse.ave-width": 20})
dk.__version__
#'2020.12.0'
x = dd.read_csv('J1_1e7_NA_5_0.csv', dtype={'id1':'Int32','id2':'Int32','id3':'Int32','id4':'category','id5':'category','id6':'category','v1':'float64'}).persist()
medium = dd.read_csv('J1_1e7_1e4_5_0.csv', dtype={'id1':'Int32','id2':'Int32','id4':'category','id5':'category','v2':'float64'}).persist()
ans = x.merge(medium, on='id5').compute()
```
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jan/git/db-benchmark/dask/py-dask/lib/python3.6/site-packages/dask/base.py", line 279, in compute
    (result,) = compute(self, traverse=False, **kwargs)
  File "/home/jan/git/db-benchmark/dask/py-dask/lib/python3.6/site-packages/dask/base.py", line 567, in compute
    results = schedule(dsk, keys, **kwargs)
  File "/home/jan/git/db-benchmark/dask/py-dask/lib/python3.6/site-packages/dask/threaded.py", line 84, in get
    **kwargs
  File "/home/jan/git/db-benchmark/dask/py-dask/lib/python3.6/site-packages/dask/local.py", line 486, in get_async
    raise_exception(exc, tb)
  File "/home/jan/git/db-benchmark/dask/py-dask/lib/python3.6/site-packages/dask/local.py", line 316, in reraise
    raise exc
  File "/home/jan/git/db-benchmark/dask/py-dask/lib/python3.6/site-packages/dask/local.py", line 222, in execute_task
    result = _execute_task(task, data)
  File "/home/jan/git/db-benchmark/dask/py-dask/lib/python3.6/site-packages/dask/core.py", line 121, in _execute_task
    return func(*(_execute_task(a, cache) for a in args))
  File "/home/jan/git/db-benchmark/dask/py-dask/lib/python3.6/site-packages/dask/utils.py", line 30, in apply
    return func(*args, **kwargs)
  File "/home/jan/git/db-benchmark/dask/py-dask/lib/python3.6/site-packages/dask/dataframe/multi.py", line 274, in merge_chunk
    out = lhs.merge(rhs, *args, **kwargs)
  File "/home/jan/git/db-benchmark/dask/py-dask/lib/python3.6/site-packages/pandas/core/frame.py", line 7963, in merge
    validate=validate,
  File "/home/jan/git/db-benchmark/dask/py-dask/lib/python3.6/site-packages/pandas/core/reshape/merge.py", line 87, in merge
    validate=validate,
  File "/home/jan/git/db-benchmark/dask/py-dask/lib/python3.6/site-packages/pandas/core/reshape/merge.py", line 652, in __init__
    ) = self._get_merge_keys()
  File "/home/jan/git/db-benchmark/dask/py-dask/lib/python3.6/site-packages/pandas/core/reshape/merge.py", line 1063, in _get_merge_
keys
    self.right = self.right._drop_labels_or_levels(right_drop)
  File "/home/jan/git/db-benchmark/dask/py-dask/lib/python3.6/site-packages/pandas/core/generic.py", line 1646, in _drop_labels_or_l
evels
    dropped.drop(labels_to_drop, axis=1, inplace=True)
  File "/home/jan/git/db-benchmark/dask/py-dask/lib/python3.6/site-packages/pandas/core/frame.py", line 4174, in drop
    errors=errors,
  File "/home/jan/git/db-benchmark/dask/py-dask/lib/python3.6/site-packages/pandas/core/generic.py", line 3889, in drop
    obj = obj._drop_axis(labels, axis, level=level, errors=errors)
  File "/home/jan/git/db-benchmark/dask/py-dask/lib/python3.6/site-packages/pandas/core/generic.py", line 3924, in _drop_axis
    result = self.reindex(**{axis_name: new_axis})
  File "/home/jan/git/db-benchmark/dask/py-dask/lib/python3.6/site-packages/pandas/util/_decorators.py", line 309, in wrapper
    return func(*args, **kwargs)
  File "/home/jan/git/db-benchmark/dask/py-dask/lib/python3.6/site-packages/pandas/core/frame.py", line 4036, in reindex
    return super().reindex(**kwargs)
  File "/home/jan/git/db-benchmark/dask/py-dask/lib/python3.6/site-packages/pandas/core/generic.py", line 4464, in reindex
    axes, level, limit, tolerance, method, fill_value, copy
  File "/home/jan/git/db-benchmark/dask/py-dask/lib/python3.6/site-packages/pandas/core/frame.py", line 3877, in _reindex_axes
    columns, method, copy, level, fill_value, limit, tolerance
  File "/home/jan/git/db-benchmark/dask/py-dask/lib/python3.6/site-packages/pandas/core/frame.py", line 3925, in _reindex_columns
    allow_dups=False,
  File "/home/jan/git/db-benchmark/dask/py-dask/lib/python3.6/site-packages/pandas/core/generic.py", line 4532, in _reindex_with_ind
exers
    copy=copy,
  File "/home/jan/git/db-benchmark/dask/py-dask/lib/python3.6/site-packages/pandas/core/internals/managers.py", line 1291, in reinde
x_indexer
    new_blocks = self._slice_take_blocks_ax0(indexer, fill_value=fill_value)
  File "/home/jan/git/db-benchmark/dask/py-dask/lib/python3.6/site-packages/pandas/core/internals/managers.py", line 1371, in _slice
_take_blocks_ax0
    self.blknos, slobj, fill_value=-1, allow_fill=allow_fill
  File "/home/jan/git/db-benchmark/dask/py-dask/lib/python3.6/site-packages/pandas/core/internals/managers.py", line 175, in blknos
    self._rebuild_blknos_and_blklocs()
  File "/home/jan/git/db-benchmark/dask/py-dask/lib/python3.6/site-packages/pandas/core/internals/managers.py", line 254, in _rebuil
d_blknos_and_blklocs
    raise AssertionError("Gaps in blk ref_locs")
AssertionError: Gaps in blk ref_locs
```

**Anything else we need to know?**:

**Environment**:

- Dask version: 2020.12.0
- Python version: 3.6
- Operating System: Linux
- Install method (conda, pip, source): pip

**Comment by jsignell** [comment]
Ok I created the data with this conda env:

```
conda create -n R r-core r-data.table
conda activate R
``` 

I was able to reproduce the issue and found that there is some additional information in the logs:

```python
Function:  merge_chunk
args:      (         id1    id2      id3   id4      id5        id6         v1
0         11   7820  4952494  id11   id7820  id4952494  81.469227
1         10    459  4780625  id10    id459  id4780625   4.058981
2          4   1291  6397757   id4   id1291  id6397757  44.926386
3          4   9747     <NA>   id4   id9747        NaN  48.502045
4          8  10713  4284249   id8  id10713  id4284249  18.910482
...      ...    ...      ...   ...      ...        ...        ...
1441197    5    908     <NA>   id5    id908        NaN  38.996284
1441198    4   5044  2772601   id4   id5044  id2772601   5.637272
1441199    8   2505  2592521   id8   id2505  id2592521  90.941858
1441200    3   <NA>  5021343   id3      NaN  id5021343  41.811443
1441201    7  10166  2753441   id7  id10166  id2753441  46.440159

[1441202 rows x 7 columns], < could not convert arg to str >)
kwargs:    {'how': 'inner', 'right_on': 'id5', 'left_on': 'id5', 'left_index': False, 'right_index': False, 'suffixes': ('_x', '_y'), 'indicator': False, 'empty_index_dtype': dtype('int64'), 'categorical_columns': Index(['id4_x', 'id5', 'id6', 'id4_y'], dtype='object')}
Exception: AssertionError('Gaps in blk ref_locs')

distributed.worker - WARNING -  Compute Failed
```

It'll probably take a while to get further than this.
