### ISSUE TITLE
KeyError: "j" in latest version of dask/dask and dask/distributed

### ISSUE THREAD

**Issue by lostmygithubaccount** [dask/dask#7040]
**What happened**:

I ran into https://github.com/dmlc/xgboost/issues/6577 trying to build a distributed xgboost example - full stack trace available there, will post here as well.

After investigation, the issue is not related to xgboost and is reproducible with dask, distributed, and a few others when:

- ``dask==2020.12.0``
- ``distributed==2020.12.0``

Downgrading both to ``2.30.0`` fixes the issue.

**What you expected to happen**:
Dask arrays can be persisted and used in xgboost.dask

**Minimal Complete Verifiable Example**:

```python
import pandas as pd
import dask.dataframe as dd

from distributed import Client
from adlfs import AzureBlobFileSystem

# setup variables
container_name = "malware"
storage_options = {"account_name": "azuremlexamples"}

# create distributed client
c = Client()

# create Azure filesystem
fs = AzureBlobFileSystem(**storage_options)

# list files 
files = fs.ls(f"{container_name}/processed")

# read in training data
for f in files:
    if "train" in f:
        df = dd.read_parquet(f"az://{f}", storage_options=storage_options)

# advanced feature engineering
cols = [col for col in df.columns if df.dtypes[col] != "object"]

# define system input and output
## FAILS HERE
X = df[cols].drop("HasDetections", axis=1).values.persist()
y = df["HasDetections"].values.persist()

# print something
print(len(X))
print(len(y))
```

**Anything else we need to know?**:

Slightly more realistic code with ``environment.yml`` used to reproduce available here: https://github.com/Azure/azureml-examples/pull/324 

**Environment**:

- Dask version: 2020.12.0
- Python version: 3.8
- Operating System: macos, linux
- Install method (conda, pip, source): pip

**Stack Trace**:

```

KeyError: 'j'
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-21-87b8ab28e9c9> in <module>
      1 import xgboost as xgb
      2 
----> 3 dtrain = xgb.dask.DaskDMatrix(c, X, y)
      4 dtrain
~/miniconda3/envs/dkdc/lib/python3.8/site-packages/xgboost/dask.py in __init__(self, client, data, label, missing, weight, base_margin, label_lower_bound, label_upper_bound, feature_names, feature_types)
    225         self.is_quantile = False
    226 
--> 227         self._init = client.sync(self.map_local_data,
    228                                  client, data, label=label, weights=weight,
    229                                  base_margin=base_margin,
~/miniconda3/envs/dkdc/lib/python3.8/site-packages/distributed/client.py in sync(self, func, asynchronous, callback_timeout, *args, **kwargs)
    829             return future
    830         else:
--> 831             return sync(
    832                 self.loop, func, *args, callback_timeout=callback_timeout, **kwargs
    833             )
~/miniconda3/envs/dkdc/lib/python3.8/site-packages/distributed/utils.py in sync(loop, func, callback_timeout, *args, **kwargs)
    338     if error[0]:
    339         typ, exc, tb = error[0]
--> 340         raise exc.with_traceback(tb)
    341     else:
    342         return result[0]
~/miniconda3/envs/dkdc/lib/python3.8/site-packages/distributed/utils.py in f()
    322             if callback_timeout is not None:
    323                 future = asyncio.wait_for(future, callback_timeout)
--> 324             result[0] = yield future
    325         except Exception as exc:
    326             error[0] = sys.exc_info()
~/miniconda3/envs/dkdc/lib/python3.8/site-packages/tornado/gen.py in run(self)
    760 
    761                     try:
--> 762                         value = future.result()
    763                     except Exception:
    764                         exc_info = sys.exc_info()
~/miniconda3/envs/dkdc/lib/python3.8/site-packages/xgboost/dask.py in map_local_data(self, client, data, label, weights, base_margin, label_lower_bound, label_upper_bound)
    255                 ' chunks=(partition_size, X.shape[1])'
    256 
--> 257         data = data.persist()
    258         for meta in [label, weights, base_margin, label_lower_bound,
    259                      label_upper_bound]:
~/miniconda3/envs/dkdc/lib/python3.8/site-packages/dask/base.py in persist(self, **kwargs)
    250         dask.base.persist
    251         """
--> 252         (result,) = persist(self, traverse=False, **kwargs)
    253         return result
    254 
~/miniconda3/envs/dkdc/lib/python3.8/site-packages/dask/base.py in persist(*args, **kwargs)
    757             else:
    758                 if client.get == schedule:
--> 759                     results = client.persist(
    760                         collections, optimize_graph=optimize_graph, **kwargs
    761                     )
~/miniconda3/envs/dkdc/lib/python3.8/site-packages/distributed/client.py in persist(self, collections, optimize_graph, workers, allow_other_workers, resources, retries, priority, fifo_timeout, actors, **kwargs)
   2974         assert all(map(dask.is_dask_collection, collections))
   2975 
-> 2976         dsk = self.collections_to_dsk(collections, optimize_graph, **kwargs)
   2977 
   2978         names = {k for c in collections for k in flatten(c.__dask_keys__())}
~/miniconda3/envs/dkdc/lib/python3.8/site-packages/distributed/client.py in collections_to_dsk(collections, *args, **kwargs)
   3960     @staticmethod
   3961     def collections_to_dsk(collections, *args, **kwargs):
-> 3962         return collections_to_dsk(collections, *args, **kwargs)
   3963 
   3964     def get_task_stream(
~/miniconda3/envs/dkdc/lib/python3.8/site-packages/dask/base.py in collections_to_dsk(collections, optimize_graph, **kwargs)
    330             dsk, keys = _extract_graph_and_keys(val)
    331             groups[opt] = (dsk, keys)
--> 332             _opt = opt(dsk, keys, **kwargs)
    333             _opt_list.append(_opt)
    334 
~/miniconda3/envs/dkdc/lib/python3.8/site-packages/dask/array/optimization.py in optimize(dsk, keys, fuse_keys, fast_functions, inline_functions_fast_functions, rename_fused_keys, **kwargs)
     46     dsk = optimize_blockwise(dsk, keys=keys)
     47     dsk = fuse_roots(dsk, keys=keys)
---> 48     dsk = dsk.cull(set(keys))
     49 
     50     if not config.get("optimization.fuse.active"):
~/miniconda3/envs/dkdc/lib/python3.8/site-packages/dask/highlevelgraph.py in cull(self, keys)
    625         """
    626 
--> 627         all_ext_keys = self.get_all_external_keys()
    628         ret_layers = {}
    629         ret_key_deps = {}
~/miniconda3/envs/dkdc/lib/python3.8/site-packages/dask/highlevelgraph.py in get_all_external_keys(self)
    516             self._all_external_keys = set()
    517             for layer in self.layers.values():
--> 518                 self._all_external_keys.update(layer.get_output_keys())
    519         return self._all_external_keys
    520 
~/miniconda3/envs/dkdc/lib/python3.8/site-packages/dask/blockwise.py in get_output_keys(self)
    283             (self.output, *p)
    284             for p in itertools.product(
--> 285                 *[range(self.dims[i]) for i in self.output_indices]
    286             )
    287         }
~/miniconda3/envs/dkdc/lib/python3.8/site-packages/dask/blockwise.py in <listcomp>(.0)
    283             (self.output, *p)
    284             for p in itertools.product(
--> 285                 *[range(self.dims[i]) for i in self.output_indices]
    286             )
    287         }
KeyError: 'j'
```

**Comment by lostmygithubaccount** [comment]
driver log from AML which fails on ``persist()`` instead of the xgboost.dask call:

```
[2021-01-07T17:33:10.126644] Entering context manager injector.
[context_manager_injector.py] Command line Options: Namespace(inject=['ProjectPythonPath:context_managers.ProjectPythonPath', 'RunHistory:context_managers.RunHistory', 'TrackUserError:context_managers.TrackUserError', 'UserExceptions:context_managers.UserExceptions'], invocation=['run.py'])
This is an MPI job. Rank:1
Script type = None
Starting the daemon thread to refresh tokens in background for process with pid = 121
Entering Run History Context Manager.
[2021-01-07T17:33:12.549591] Current directory: /mnt/batch/tasks/shared/LS_root/jobs/default/azureml/xgboost-cpu-tutorial_1610040108_f29decf7/mounts/workspaceblobstore/azureml/xgboost-cpu-tutorial_1610040108_f29decf7
[2021-01-07T17:33:12.557936] Preparing to call script [run.py] with arguments:[]
[2021-01-07T17:33:12.558039] After variable expansion, calling script [run.py] with arguments:[]

initializing...
<Client: 'tcp://10.0.0.4:41157' processes=1 threads=1, memory=3.58 GB>
creating dataframes...
processing data...
Starting the daemon thread to refresh tokens in background for process with pid = 121


[2021-01-07T17:33:18.136621] The experiment failed. Finalizing run...
Cleaning up all outstanding Run operations, waiting 900.0 seconds
1 items cleaning up...
Cleanup took 0.0627279281616211 seconds
Starting the daemon thread to refresh tokens in background for process with pid = 121
Traceback (most recent call last):
  File "run.py", line 33, in <module>
    X = df_train[cols].drop("HasDetections", axis=1).values.persist()
  File "/azureml-envs/azureml_ffbb10db4a6af4f6397c992e16ad5e69/lib/python3.8/site-packages/dask/base.py", line 252, in persist
    (result,) = persist(self, traverse=False, **kwargs)
  File "/azureml-envs/azureml_ffbb10db4a6af4f6397c992e16ad5e69/lib/python3.8/site-packages/dask/base.py", line 759, in persist
    results = client.persist(
  File "/azureml-envs/azureml_ffbb10db4a6af4f6397c992e16ad5e69/lib/python3.8/site-packages/distributed/client.py", line 2976, in persist
    dsk = self.collections_to_dsk(collections, optimize_graph, **kwargs)
  File "/azureml-envs/azureml_ffbb10db4a6af4f6397c992e16ad5e69/lib/python3.8/site-packages/distributed/client.py", line 3962, in collections_to_dsk
    return collections_to_dsk(collections, *args, **kwargs)
  File "/azureml-envs/azureml_ffbb10db4a6af4f6397c992e16ad5e69/lib/python3.8/site-packages/dask/base.py", line 332, in collections_to_dsk
    _opt = opt(dsk, keys, **kwargs)
  File "/azureml-envs/azureml_ffbb10db4a6af4f6397c992e16ad5e69/lib/python3.8/site-packages/dask/array/optimization.py", line 48, in optimize
    dsk = dsk.cull(set(keys))
  File "/azureml-envs/azureml_ffbb10db4a6af4f6397c992e16ad5e69/lib/python3.8/site-packages/dask/highlevelgraph.py", line 627, in cull
    all_ext_keys = self.get_all_external_keys()
  File "/azureml-envs/azureml_ffbb10db4a6af4f6397c992e16ad5e69/lib/python3.8/site-packages/dask/highlevelgraph.py", line 518, in get_all_external_keys
    self._all_external_keys.update(layer.get_output_keys())
  File "/azureml-envs/azureml_ffbb10db4a6af4f6397c992e16ad5e69/lib/python3.8/site-packages/dask/blockwise.py", line 285, in get_output_keys
    *[range(self.dims[i]) for i in self.output_indices]
  File "/azureml-envs/azureml_ffbb10db4a6af4f6397c992e16ad5e69/lib/python3.8/site-packages/dask/blockwise.py", line 285, in <listcomp>
    *[range(self.dims[i]) for i in self.output_indices]
KeyError: 'j'

[2021-01-07T17:33:18.397146] Finished context manager injector with Exception.
```

**Comment by quasiben** [comment]
Are there any errors on the worker ?  Perhaps something which looks like:

> TypeError: can not serialize 'CreateArraySubgraph' object

?

**Comment by lostmygithubaccount** [comment]
this reproduces locally as well, would that error still be possible?

**Comment by lostmygithubaccount** [comment]
local stack trace looks the same, and I don't see anything in dask-worker-space to really check? 

```
KeyError: 'j'
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-7-8333897085d4> in <module>
----> 1 X = df_train[cols].drop("HasDetections", axis=1).values.persist()
      2 X
~/miniconda3/envs/dkdc/lib/python3.8/site-packages/dask/base.py in persist(self, **kwargs)
    250         dask.base.persist
    251         """
--> 252         (result,) = persist(self, traverse=False, **kwargs)
    253         return result
    254 
~/miniconda3/envs/dkdc/lib/python3.8/site-packages/dask/base.py in persist(*args, **kwargs)
    757             else:
    758                 if client.get == schedule:
--> 759                     results = client.persist(
    760                         collections, optimize_graph=optimize_graph, **kwargs
    761                     )
~/miniconda3/envs/dkdc/lib/python3.8/site-packages/distributed/client.py in persist(self, collections, optimize_graph, workers, allow_other_workers, resources, retries, priority, fifo_timeout, actors, **kwargs)
   2974         assert all(map(dask.is_dask_collection, collections))
   2975 
-> 2976         dsk = self.collections_to_dsk(collections, optimize_graph, **kwargs)
   2977 
   2978         names = {k for c in collections for k in flatten(c.__dask_keys__())}
~/miniconda3/envs/dkdc/lib/python3.8/site-packages/distributed/client.py in collections_to_dsk(collections, *args, **kwargs)
   3960     @staticmethod
   3961     def collections_to_dsk(collections, *args, **kwargs):
-> 3962         return collections_to_dsk(collections, *args, **kwargs)
   3963 
   3964     def get_task_stream(
~/miniconda3/envs/dkdc/lib/python3.8/site-packages/dask/base.py in collections_to_dsk(collections, optimize_graph, **kwargs)
    330             dsk, keys = _extract_graph_and_keys(val)
    331             groups[opt] = (dsk, keys)
--> 332             _opt = opt(dsk, keys, **kwargs)
    333             _opt_list.append(_opt)
    334 
~/miniconda3/envs/dkdc/lib/python3.8/site-packages/dask/array/optimization.py in optimize(dsk, keys, fuse_keys, fast_functions, inline_functions_fast_functions, rename_fused_keys, **kwargs)
     46     dsk = optimize_blockwise(dsk, keys=keys)
     47     dsk = fuse_roots(dsk, keys=keys)
---> 48     dsk = dsk.cull(set(keys))
     49 
     50     if not config.get("optimization.fuse.active"):
~/miniconda3/envs/dkdc/lib/python3.8/site-packages/dask/highlevelgraph.py in cull(self, keys)
    625         """
    626 
--> 627         all_ext_keys = self.get_all_external_keys()
    628         ret_layers = {}
    629         ret_key_deps = {}
~/miniconda3/envs/dkdc/lib/python3.8/site-packages/dask/highlevelgraph.py in get_all_external_keys(self)
    516             self._all_external_keys = set()
    517             for layer in self.layers.values():
--> 518                 self._all_external_keys.update(layer.get_output_keys())
    519         return self._all_external_keys
    520 
~/miniconda3/envs/dkdc/lib/python3.8/site-packages/dask/blockwise.py in get_output_keys(self)
    283             (self.output, *p)
    284             for p in itertools.product(
--> 285                 *[range(self.dims[i]) for i in self.output_indices]
    286             )
    287         }
~/miniconda3/envs/dkdc/lib/python3.8/site-packages/dask/blockwise.py in <listcomp>(.0)
    283             (self.output, *p)
    284             for p in itertools.product(
--> 285                 *[range(self.dims[i]) for i in self.output_indices]
    286             )
    287         }
KeyError: 'j'
```

**Comment by jrbourbeau** [comment]
cc @rjzamora

**Comment by rjzamora** [comment]
Thanks for raising this @lostmygithubaccount - There are known serialization issues with the new `BlockwiseIO` implementation (used by `read_parquet`) that absolutely need to be fixed.  The problem may require a slight redesign of `BlockwiseIO`, but I am working on it.  Your issue may be a separate problem, but it probably makes sense to wait on the redesign... Sorry for the trouble.

**Comment by jrbourbeau** [comment]
@lostmygithubaccount could you try with the latest release of `xgboost` / `dask` / `distributed`? There's been several updates since you originally ran into this issue. I wonder if this issue still exists

**Comment by lostmygithubaccount** [comment]
this issue is no longer present

**Comment by jrbourbeau** [comment]
Great, thanks for following up @lostmygithubaccount!
