### ISSUE TITLE
HighLevelGraph.cull culling doesn't rename layers

### ISSUE THREAD

**Issue by bmerry** [dask/dask#7137]
**What happened**: when looking at the code I noticed that HighLevelGraph.cull doesn't rename layers. This can lead to problems because the layer name no longer uniquely identifies the layer. When manually optimising graphs (e.g. with the public `dask.optimize`) this can cause problems.

**What you expected to happen**: Culled layers should have new names, either UUIDs or hashes that describe the new set of keys.

**Minimal Complete Verifiable Example**:

I haven't actually stepped through the code to check that what I've described is actually the cause of this failure, but I wrote the code to trigger the condition. If it's not the cause, then I've found a bonus bug :-) The idea is that `a1` and `a2` end up with a layer with the same name but a different subset of keys, and only one copy of the layer is retained in `b`.
```python
#!/usr/bin/env python3

import dask.array as da
import dask

with dask.config.set({'optimization.fuse.active': False}):
    a = da.from_array([1, 2], chunks=1)
    a1 = a[:1]
    a2 = a[1:]
    (a1,) = dask.optimize(a1)
    (a2,) = dask.optimize(a2)
    b = a1 + a2
    print(b.compute())
```

Output:
```
Traceback (most recent call last):
  File "cull-rename.py", line 13, in <module>
    print(b.compute())
  File "/home/bmerry/work/sdp/env3/lib/python3.8/site-packages/dask/base.py", line 279, in compute
    (result,) = compute(self, traverse=False, **kwargs)
  File "/home/bmerry/work/sdp/env3/lib/python3.8/site-packages/dask/base.py", line 561, in compute
    results = schedule(dsk, keys, **kwargs)
  File "/home/bmerry/work/sdp/env3/lib/python3.8/site-packages/dask/threaded.py", line 76, in get
    results = get_async(
  File "/home/bmerry/work/sdp/env3/lib/python3.8/site-packages/dask/local.py", line 487, in get_async
    raise_exception(exc, tb)
  File "/home/bmerry/work/sdp/env3/lib/python3.8/site-packages/dask/local.py", line 317, in reraise
    raise exc
  File "/home/bmerry/work/sdp/env3/lib/python3.8/site-packages/dask/local.py", line 222, in execute_task
    result = _execute_task(task, data)
  File "/home/bmerry/work/sdp/env3/lib/python3.8/site-packages/dask/core.py", line 121, in _execute_task
    return func(*(_execute_task(a, cache) for a in args))
TypeError: tuple indices must be integers or slices, not tuple
```

**Anything else we need to know?**:

**Environment**:

- Dask version: 2021.1.1
- Python version: 3.8.5
- Operating System: Ubuntu 20.04
- Install method (conda, pip, source): pip

**Comment by bmerry** [comment]
Ping @madsbk since it looks like you wrote the code in question.

**Comment by jsignell** [comment]
Sorry this has slipped through the cracks a bit. I added a label to try to help with visibility

**Comment by jrbourbeau** [comment]
cc @crusaderky as he's been looking into `HighLevelGraph` consistency recently

**Comment by crusaderky** [comment]
I don't think this can be fixed without overhauling the design of the ``__dask_layers__`` method first. At the moment,  ``__dask_layers__`` is making blind assumptions on the layer name based on the ``__dask_keys__`` - which works in 99% of the cases, except when it doesn't - see #7177.

A reasonable solution would be to store the top-level layers in an attribute of HighlevelGraph; the ``__dask_layers__`` method would then become a trivial accessor.

On a separate note, I'm curious to understand what is the use case of culling a graph and then adding to it afterwards, as opposed to leaving optimization as the very last step before computation?

**Comment by bmerry** [comment]
> On a separate note, I'm curious to understand what is the use case of culling a graph and then adding to it afterwards, as opposed to leaving optimization as the very last step before computation?

If you have an intermediate array where optimisation is expensive but gives a much smaller graph (I'm thinking in particular of #5918, but I think the same could apply if there were many layers that could be fused), and you then construct and compute many graphs from it, it is cheaper to just optimise the intermediate array once rather than in each computation.

BTW I haven't hit this exact bug in real code (yet) - it's just something I spotted while reading Dask source code to understand how the HLG culling works.

**Comment by crusaderky** [comment]
> If you have an intermediate array where optimisation is expensive but gives a much smaller graph (I'm thinking in particular of #5918, but I think the same could apply if there were many layers that could be fused), and you then construct and compute many graphs from it, it is cheaper to just optimise the intermediate array once rather than in each computation.

Wouldn't it be better to use persist() in this case?

**Comment by bmerry** [comment]
> Wouldn't it be better to use persist() in this case?

Not if the intermediate array is hundreds of GB large.

**Comment by crusaderky** [comment]
PR #7276 introduces a new method ``HighLevelGraph.cull_layers()``, which would sidestep the problem very nicely albeit at the cost of unculled keys in the case of slicing.
