### ISSUE TITLE
Reading avro multiple calls

### ISSUE THREAD

**Issue by lqrz** [dask/dask#7158]
**What happened**:

I'm reading an avro dataset, and converting in into a parquet one, inside a class, and as a result I get my original method being called multiple times.

I get I'm doing something wrong...

**What you expected to happen**:
I would have expected my method being called only once.

**Minimal Complete Verifiable Example**:

```python
#--- Converter.py

import dask.dataframe as dd
import dask.bag as db


class Converter(object):

    
    def __init__(self, path:str, file_format:str):
        self.gcs_path = path
        self.file_format = file_format

    
    def convert(self):

        print('Converting AVRO dataset to parquet')

        _ = (
            db
             .read_avro(f'{self.gcs_path}/{self.file_format}/*.{self.file_format.lower()}')
             .to_dataframe()
             .to_parquet(f'{self.gcs_path}/PARQUET', write_index=False, partition_on=[])
            )
```

```python
#--- run_convert.py

from edo.lib.dataset.Converter import Converter

c = Converter(path='gs://.../dataset_categorical_encoding', file_format='AVRO')
c.convert()
```

**Anything else we need to know?**:

As a result, I get the following output:

```
jupyter@:~/scripts$ python3 run_convert.py

Converting AVRO dataset to parquet
Converting AVRO dataset to parquet
Converting AVRO dataset to parquet
Converting AVRO dataset to parquet
Converting AVRO dataset to parquet
Converting AVRO dataset to parquet
Converting AVRO dataset to parquet
Converting AVRO dataset to parquet
Converting AVRO dataset to parquet
Converting AVRO dataset to parquet
Converting AVRO dataset to parquet
Converting AVRO dataset to parquet
Converting AVRO dataset to parquet
Converting AVRO dataset to parquet
Converting AVRO dataset to parquet
Converting AVRO dataset to parquet
Converting AVRO dataset to parquet
Converting AVRO dataset to parquet
Converting AVRO dataset to parquet
Converting AVRO dataset to parquet
Converting AVRO dataset to parquet
Converting AVRO dataset to parquet
Converting AVRO dataset to parquet
Converting AVRO dataset to parquet
Converting AVRO dataset to parquet
Converting AVRO dataset to parquet
Converting AVRO dataset to parquet
Converting AVRO dataset to parquet
Converting AVRO dataset to parquet
Converting AVRO dataset to parquet
Converting AVRO dataset to parquet
Converting AVRO dataset to parquet
Converting AVRO dataset to parquet
Converting AVRO dataset to parquet
Converting AVRO dataset to parquet

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/opt/conda/lib/python3.7/multiprocessing/spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "/opt/conda/lib/python3.7/multiprocessing/spawn.py", line 114, in _main
    prepare(preparation_data)
  File "/opt/conda/lib/python3.7/multiprocessing/spawn.py", line 225, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "/opt/conda/lib/python3.7/multiprocessing/spawn.py", line 277, in _fixup_main_from_path
    run_name="__mp_main__")
  File "/opt/conda/lib/python3.7/runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "/opt/conda/lib/python3.7/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/opt/conda/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/jupyter/scripts/run_convert.py", line 4, in <module>
    c.convert()
  File "/opt/conda/lib/python3.7/site-packages/-2.0.0-py3.7.egg/dataset/Converter.py", line 32, in convert
  File "/opt/conda/lib/python3.7/site-packages/dask/bag/core.py", line 1538, in to_dataframe
    head = self.take(1, warn=False)
  File "/opt/conda/lib/python3.7/site-packages/dask/bag/core.py", line 1402, in take
    return tuple(b.compute())
  File "/opt/conda/lib/python3.7/site-packages/dask/base.py", line 279, in compute
    (result,) = compute(self, traverse=False, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/dask/base.py", line 561, in compute
    results = schedule(dsk, keys, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/dask/multiprocessing.py", line 196, in get
    pool = context.Pool(num_workers, initializer=initialize_worker_process)
  File "/opt/conda/lib/python3.7/multiprocessing/context.py", line 119, in Pool
    context=self.get_context())
  File "/opt/conda/lib/python3.7/multiprocessing/pool.py", line 176, in __init__
    self._repopulate_pool()
  File "/opt/conda/lib/python3.7/multiprocessing/pool.py", line 241, in _repopulate_pool
    w.start()
  File "/opt/conda/lib/python3.7/multiprocessing/process.py", line 112, in start
    self._popen = self._Popen(self)
  File "/opt/conda/lib/python3.7/multiprocessing/context.py", line 284, in _Popen
    return Popen(process_obj)
  File "/opt/conda/lib/python3.7/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/opt/conda/lib/python3.7/multiprocessing/popen_fork.py", line 20, in __init__
    self._launch(process_obj)
  File "/opt/conda/lib/python3.7/multiprocessing/popen_spawn_posix.py", line 42, in _launch
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "/opt/conda/lib/python3.7/multiprocessing/spawn.py", line 143, in get_preparation_data
    _check_not_importing_main()
  File "/opt/conda/lib/python3.7/multiprocessing/spawn.py", line 136, in _check_not_importing_main
    is not going to be frozen to produce an executable.''')
RuntimeError: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
```

**Environment**:

- Dask version: `2021.1.1`
- Python version: `3.7.8`
- Operating System: `Debian GNU/Linux 10`
- Install method (conda, pip, source): `pip3`

**Comment by jrbourbeau** [comment]
Thanks for raising an issue @lqrz. Could you post the contents of your `run_convert.py` script so others can see what code you're running? Also, from the error message, you need to place your code inside a `if __name__ == '__main__':` block -- something along the lines of 

```python
# run_convert.py

if __name__ == '__main__':
    <your-code-here>
```

**Comment by lqrz** [comment]
Hi @jrbourbeau thanks for the quick response! I updated the original post; `run_convert.py` was just the instantiation of the class and the method call.

Protecting the `run_conver.py` entrypoint with `if __name__ == '__main__'` solved my problem indeed! Thanks!
