### ISSUE TITLE
"ResourceWarning: unclosed file" warnings in the test suite

### ISSUE THREAD

**Issue by jrbourbeau** [dask/dask#7167]
I noticed there are many warnings that look like:

```
dask/bytes/tests/test_http.py::test_simple
  /usr/share/miniconda3/envs/test-environment/lib/python3.8/site-packages/_pytest/unraisableexception.py:78: PytestUnraisableExceptionWarning: Exception ignored in: <_io.FileIO [closed]>
  
  Traceback (most recent call last):
    File "/home/runner/work/dask/dask/dask/bytes/tests/test_http.py", line 50, in test_simple
      assert data == open(os.path.join(dir_server, fn), "rb").read()
  ResourceWarning: unclosed file <_io.BufferedReader name='/tmp/tmp2zbuwztd/a'>
  
    warnings.warn(pytest.PytestUnraisableExceptionWarning(msg))
```

in the test suite (see [this build](https://github.com/dask/dask/runs/1827520833#step:5:168) for an example). It would be good at some point to go through and resolve these warnings.

**Comment by jsignell** [comment]
A lot of these are also coming from parquet. It doesn't seem like there is any attempt at closing files in pyarrow. I am not sure how best to workaround this or if I am missing something. In particular, these parts seem to cause issues:

```
  Traceback (most recent call last):
    File "/home/julia/dask/dask/dataframe/io/parquet/arrow.py", line 1586, in _parquet_piece_as_arrow
      arrow_table = piece.read(
  ResourceWarning: unclosed file <_io.BufferedReader name='/tmp/pytest-of-julia/pytest-39/popen-gw7/test_select_partitioned_column1/fake_categorical1=C/fake_categorical2=E/part.1.parquet'>

  Traceback (most recent call last):
    File "/home/julia/dask/dask/dataframe/io/parquet/arrow.py", line 1786, in _gather_metadata
      md = piece.get_metadata()
  ResourceWarning: unclosed file <_io.BufferedReader name='/tmp/pytest-of-julia/pytest-39/popen-gw7/test_categories_large_pyarrow_0/parquet_int16.parq'>
```

I am wondering if we need to write our own versions of `get_metadata` and `piece.read` @rjzamora

**Comment by jsignell** [comment]
I will open a PR to try to make this discussion clearer.

**Comment by jrbourbeau** [comment]
Awesome, thanks @jsignell

**Comment by GenevieveBuckley** [comment]
7303 was a [partial fix](https://github.com/dask/dask/pull/7303#issuecomment-910396991) - should this issue be kept open to track the remaining arrow stuff?

**Comment by jrbourbeau** [comment]
Whoops, good catch @GenevieveBuckley -- reopening

**Comment by jrbourbeau** [comment]
Just checked the latest CI build on `main` and, indeed, these unclosed file `ResourceWarning` are gone 🎉 

Thanks for following-up here @GenevieveBuckley

**Comment by j-bennet** [comment]
This came up again, CI job:

https://github.com/dask/dask/actions/runs/4421267540/jobs/7751871262

```
dask/dataframe/io/tests/test_parquet.py::test_retries_on_remote_filesystem
  /usr/share/miniconda3/envs/test-environment/lib/python3.10/site-packages/_pytest/unraisableexception.py:78: PytestUnraisableExceptionWarning: Exception ignored in: <_io.FileIO [closed]>
  
  Traceback (most recent call last):
    File "/home/runner/work/dask/dask/dask/dataframe/io/parquet/arrow.py", line 1005, in _collect_dataset_info
      physical_schema = file_frag.physical_schema
  ResourceWarning: unclosed file <_io.BufferedReader name='/tmp/tmp57eq_7ze/d549ad8b59c1797315fcb393c08f3fb30bf1195da24aabd1b0dca178e4f34afd'>
  
    warnings.warn(pytest.PytestUnraisableExceptionWarning(msg))
```

Reopening to fix again.
