### ISSUE TITLE
Client creation fails on python 3.9

### ISSUE THREAD

**Issue by yannikschaelte** [dask/dask#7204]
**What happened**:

A minimal example which ran without problems on python 3.8 fails on 3.9 with the below error message. 

This error occured while investigating why in our tool, where we optionally start a local client for distributed sampling (see [here](https://github.com/ICB-DCM/pyABC/blob/main/pyabc/sampler/dask_sampler.py#L49)), tests just hang forever in the `my_client = Client()` line (not sure if this is the same problem, but also only occurs in python 3.9). There, no error occurs, just nothing happens.

**Minimal Complete Verifiable Example**:

Python script, called via `python script.py`:
```python
from dask.distributed import Client
from time import sleep

if __name__ == '__main__':
    sleep(1)
    client = Client()
    sleep(1)
    client.close()

```

**Environment**:

- Dask version: 2021.2.0 (on python 3.8: 2.30.0)
- Python version: 3.9.1 (anaconda)
- Operating System: Ubuntu
- Install method (conda, pip, source): pip

**Error message**:
```
/home/yannik/anaconda3/envs/py39/lib/python3.9/site-packages/distributed/node.py:151: UserWarning: Port 8787 is already in use.
Perhaps you already have a cluster running?
Hosting the HTTP server on port 35859 instead
  warnings.warn(
Task exception was never retrieved
future: <Task finished name='Task-12' coro=<_wrap_awaitable() done, defined at /home/yannik/anaconda3/envs/py39/lib/python3.9/asyncio/tasks.py:680> exception=ImportError("cannot import name 'Popen' from partially initialized module 'multiprocessing.popen_spawn_posix' (most likely due to a circular import) (/home/yannik/anaconda3/envs/py39/lib/python3.9/multiprocessing/popen_spawn_posix.py)")>
Traceback (most recent call last):
  File "/home/yannik/anaconda3/envs/py39/lib/python3.9/asyncio/tasks.py", line 687, in _wrap_awaitable
    return (yield from awaitable.__await__())
  File "/home/yannik/anaconda3/envs/py39/lib/python3.9/site-packages/distributed/core.py", line 284, in _
    await self.start()
  File "/home/yannik/anaconda3/envs/py39/lib/python3.9/site-packages/distributed/nanny.py", line 295, in start
    response = await self.instantiate()
  File "/home/yannik/anaconda3/envs/py39/lib/python3.9/site-packages/distributed/nanny.py", line 378, in instantiate
    result = await self.process.start()
  File "/home/yannik/anaconda3/envs/py39/lib/python3.9/site-packages/distributed/nanny.py", line 575, in start
    await self.process.start()
  File "/home/yannik/anaconda3/envs/py39/lib/python3.9/site-packages/distributed/process.py", line 33, in _call_and_set_future
    res = func(*args, **kwargs)
  File "/home/yannik/anaconda3/envs/py39/lib/python3.9/site-packages/distributed/process.py", line 203, in _start
    process.start()
  File "/home/yannik/anaconda3/envs/py39/lib/python3.9/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/home/yannik/anaconda3/envs/py39/lib/python3.9/multiprocessing/context.py", line 283, in _Popen
    from .popen_spawn_posix import Popen
ImportError: cannot import name 'Popen' from partially initialized module 'multiprocessing.popen_spawn_posix' (most likely due to a circular import) (/home/yannik/anaconda3/envs/py39/lib/python3.9/multiprocessing/popen_spawn_posix.py)
```

**Comment by yannikschaelte** [comment]
Update: This is already tracked in https://github.com/dask/distributed/issues/4168, therefore closing here. The patch given there also applies here.
