### ISSUE TITLE
cumsum for empty partitions fails

### ISSUE THREAD

**Issue by m-rossi** [dask/dask#7224]
**What happened**:

I want to calculate the `.cumsum()` for a DataFrame which has been filtered with some condition. This filter leads to some empty partitions. The calculation fails with the following error

```python
Traceback (most recent call last):
  File "C:\miniforge\lib\site-packages\pandas\core\ops\array_ops.py", line 142, in _na_arithmetic_op
    result = expressions.evaluate(op, left, right)
  File "C:\miniforge\lib\site-packages\pandas\core\computation\expressions.py", line 235, in evaluate
    return _evaluate(op, op_str, a, b)  # type: ignore[misc]
  File "C:\miniforge\lib\site-packages\pandas\core\computation\expressions.py", line 69, in _evaluate_standard
    return op(a, b)
TypeError: unsupported operand type(s) for +: 'int' and 'NoneType'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\rossmar\Documents\github\dask\issues\empty-partitions.py", line 6, in <module>
    ddf[ddf.x > 4].x.cumsum().compute()
  File "C:\miniforge\lib\site-packages\dask\base.py", line 281, in compute
    (result,) = compute(self, traverse=False, **kwargs)
  File "C:\miniforge\lib\site-packages\dask\base.py", line 563, in compute
    results = schedule(dsk, keys, **kwargs)
  File "C:\miniforge\lib\site-packages\dask\threaded.py", line 76, in get
    results = get_async(
  File "C:\miniforge\lib\site-packages\dask\local.py", line 487, in get_async
    raise_exception(exc, tb)
  File "C:\miniforge\lib\site-packages\dask\local.py", line 317, in reraise
    raise exc
  File "C:\miniforge\lib\site-packages\dask\local.py", line 222, in execute_task
    result = _execute_task(task, data)
  File "C:\miniforge\lib\site-packages\dask\core.py", line 121, in _execute_task
    return func(*(_execute_task(a, cache) for a in args))
  File "C:\miniforge\lib\site-packages\pandas\core\ops\common.py", line 65, in new_method
    return method(self, other)
  File "C:\miniforge\lib\site-packages\pandas\core\arraylike.py", line 89, in __add__
    return self._arith_method(other, operator.add)
  File "C:\miniforge\lib\site-packages\pandas\core\series.py", line 4995, in _arith_method
    result = ops.arithmetic_op(lvalues, rvalues, op)
  File "C:\miniforge\lib\site-packages\pandas\core\ops\array_ops.py", line 189, in arithmetic_op
    res_values = _na_arithmetic_op(lvalues, rvalues, op)
  File "C:\miniforge\lib\site-packages\pandas\core\ops\array_ops.py", line 149, in _na_arithmetic_op
    result = _masked_arith_op(left, right, op)
  File "C:\miniforge\lib\site-packages\pandas\core\ops\array_ops.py", line 111, in _masked_arith_op
    result[mask] = op(xrav[mask], y)
TypeError: unsupported operand type(s) for +: 'int' and 'NoneType'
```

**What you expected to happen**:

Calculation of the cumulative sum.

**Minimal Complete Verifiable Example**:

```python
import dask.dataframe as dd
import pandas as pd

df = pd.DataFrame({'x': [1, 2, 3, 4, 5, 6, 7, 8]})
ddf = dd.from_pandas(df, npartitions=4)
ddf[ddf.x > 4].x.cumsum().compute()
```

**Anything else we need to know?**:

This bug is similar to #5726 and #4743, the code snippets from that issues seem to work. However the filtering is different.

**Environment**:

- Dask version: 2021.2.0
- Python version: 3.8.6
- Operating System: Windows 10 1909
- Install method (conda, pip, source): conda

**Comment by jsignell** [comment]
Thanks for raising this. I can reproduce and I think I understand why this fails when the example in #4743 does not. There is a special case in the code for the first and second partitions. So right now it matters where the empty partitions fall.

**Comment by m-rossi** [comment]
Thanks @jsignell !
