### ISSUE TITLE
LocalCluster throws "not enough values to unpack"

### ISSUE THREAD

**Issue by DahnJ** [dask/dask#7269]
When I try to run 

```python
from dask.distributed import LocalCluster
LocalCluster(host='0.0.0.0', processes=False)
```

I get the following error:
```python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/dahn/miniconda3/lib/python3.8/site-packages/distributed/deploy/local.py", line 229, in __init__
    super().__init__(
  File "/home/dahn/miniconda3/lib/python3.8/site-packages/distributed/deploy/spec.py", line 276, in __init__
    self.sync(self._start)
  File "/home/dahn/miniconda3/lib/python3.8/site-packages/distributed/deploy/cluster.py", line 183, in sync
    return sync(self.loop, func, *args, **kwargs)
  File "/home/dahn/miniconda3/lib/python3.8/site-packages/distributed/utils.py", line 340, in sync
    raise exc.with_traceback(tb)
  File "/home/dahn/miniconda3/lib/python3.8/site-packages/distributed/utils.py", line 324, in f
    result[0] = yield future
  File "/home/dahn/miniconda3/lib/python3.8/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/home/dahn/miniconda3/lib/python3.8/site-packages/distributed/deploy/spec.py", line 304, in _start
    self.scheduler = await self.scheduler
  File "/home/dahn/miniconda3/lib/python3.8/site-packages/distributed/core.py", line 305, in _
    await self.start()
  File "/home/dahn/miniconda3/lib/python3.8/site-packages/distributed/scheduler.py", line 1483, in start
    self.ip = get_address_host(self.listen_address)
  File "/home/dahn/miniconda3/lib/python3.8/site-packages/distributed/comm/addressing.py", line 142, in get_address_host
    return backend.get_address_host(loc)
  File "/home/dahn/miniconda3/lib/python3.8/site-packages/distributed/comm/inproc.py", line 341, in get_address_host
    self.manager.validate_address(loc)
  File "/home/dahn/miniconda3/lib/python3.8/site-packages/distributed/comm/inproc.py", line 70, in validate_address
    ip, pid, suffix = addr.split("/")
ValueError: not enough values to unpack (expected 3, got 1)
```

The problem is with setting the host. Without that argument, the method works fine. Either way, I am not sure this is intended behaviour, or whether the mistake is on my side.

**Environment**:

- Dask version: 2.30.0
- Python version: 3.8.5
- Operating System: Ubunt 18.04
- Install method (conda, pip, source): pip

**Comment by jsignell** [comment]
The host is intended to include a port number in it. For instance: 

```python
from dask.distributed import LocalCluster
LocalCluster(host='0.0.0.0:8786', processes=False)
```

Please open a Pull Request on https://github.com/dask/distributed if you have ideas about how to improve the documentation or raise a more informative error message.

**Comment by vlagorsse** [comment]
Hi,
I got the same error message with 

``` 
LocalCluster(host='0.0.0.0:8786',  n_workers=2, processes=False, threads_per_worker=1)
```

```
    File "/opt/conda/lib/python3.7/site-packages/distributed/comm/addressing.py", line 142, in get_address_host
    return backend.get_address_host(loc)
   File "/opt/conda/lib/python3.7/site-packages/distributed/comm/inproc.py", line 341, in get_address_host
     self.manager.validate_address(loc)
   File "/opt/conda/lib/python3.7/site-packages/distributed/comm/inproc.py", line 70, in validate_address
     ip, pid, suffix = addr.split("/")
   ValueError: not enough values to unpack (expected 3, got 1)
```

**Comment by vlagorsse** [comment]
Ok, I found what was the issue. You have to set `protocol="tcp://"` if you want to set an host option that listen on the network.

```LocalCluster(host='0.0.0.0:8786',  n_workers=2, processes=False, threads_per_worker=1, protocol="tcp://")```

I would suggest that the documentation could be updated with a working example.

**Comment by jsignell** [comment]
I'm glad you found the answer! Please feel free to open a pull request with any improvements to the docs.
