### ISSUE TITLE
Cannot fit with HyperbandSearchCV

### ISSUE THREAD

**Issue by martaccmoreno** [dask/dask#7571]
**What happened**:

When I try to run HyperbandSearchCV's documentation example, I get an error during fit, and the client fails to shutdown.

**What you expected to happen**:

I would expect to be able to fit to the generated training data.

**Minimal Complete Verifiable Example**:

```python
from dask_ml.model_selection import HyperbandSearchCV
from dask_ml.datasets import make_classification
from sklearn.linear_model import SGDClassifier
from dask.distributed import Client
from dask_ml.model_selection import train_test_split
from scipy.stats import uniform, loguniform

if __name__ == '__main__':
    client = Client()

    X, y = make_classification(chunks=20, random_state=0)

    X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=0)

    clf = SGDClassifier(tol=1e-3, penalty='elasticnet', random_state=0)

    params = {'alpha': loguniform(1e-2, 1e0), 'l1_ratio': uniform(0, 1)}

    search = HyperbandSearchCV(clf, params, max_iter=81, random_state=0)
    search.fit(X_train, y_train, classes=[0, 1])
    print(search.best_params_)

    client.shutdown()
```

**Anything else we need to know?**:

On my end, the minimal example outputs the following error message:

```
distributed.protocol.core - CRITICAL - Failed to Serialize
Traceback (most recent call last):
  File "/home/marta/IdeaProjectsVenvs/ML-DASK3.9/lib/python3.9/site-packages/distributed/protocol/core.py", line 70, in dumps
    frames[0] = msgpack.dumps(msg, default=_encode_default, use_bin_type=True)
  File "/home/marta/IdeaProjectsVenvs/ML-DASK3.9/lib/python3.9/site-packages/msgpack/__init__.py", line 35, in packb
    return Packer(**kwargs).pack(o)
  File "msgpack/_packer.pyx", line 292, in msgpack._cmsgpack.Packer.pack
  File "msgpack/_packer.pyx", line 298, in msgpack._cmsgpack.Packer.pack
  File "msgpack/_packer.pyx", line 295, in msgpack._cmsgpack.Packer.pack
  File "msgpack/_packer.pyx", line 264, in msgpack._cmsgpack.Packer._pack
  File "msgpack/_packer.pyx", line 231, in msgpack._cmsgpack.Packer._pack
  File "msgpack/_packer.pyx", line 231, in msgpack._cmsgpack.Packer._pack
  File "msgpack/_packer.pyx", line 229, in msgpack._cmsgpack.Packer._pack
  File "msgpack/_packer.pyx", line 264, in msgpack._cmsgpack.Packer._pack
  File "msgpack/_packer.pyx", line 289, in msgpack._cmsgpack.Packer._pack
TypeError: can not serialize 'Delayed' object
distributed.comm.utils - ERROR - can not serialize 'Delayed' object
Traceback (most recent call last):
  File "/home/marta/IdeaProjectsVenvs/ML-DASK3.9/lib/python3.9/site-packages/distributed/comm/utils.py", line 31, in _to_frames
    protocol.dumps(
  File "/home/marta/IdeaProjectsVenvs/ML-DASK3.9/lib/python3.9/site-packages/distributed/protocol/core.py", line 70, in dumps
    frames[0] = msgpack.dumps(msg, default=_encode_default, use_bin_type=True)
  File "/home/marta/IdeaProjectsVenvs/ML-DASK3.9/lib/python3.9/site-packages/msgpack/__init__.py", line 35, in packb
    return Packer(**kwargs).pack(o)
  File "msgpack/_packer.pyx", line 292, in msgpack._cmsgpack.Packer.pack
  File "msgpack/_packer.pyx", line 298, in msgpack._cmsgpack.Packer.pack
  File "msgpack/_packer.pyx", line 295, in msgpack._cmsgpack.Packer.pack
  File "msgpack/_packer.pyx", line 264, in msgpack._cmsgpack.Packer._pack
  File "msgpack/_packer.pyx", line 231, in msgpack._cmsgpack.Packer._pack
  File "msgpack/_packer.pyx", line 231, in msgpack._cmsgpack.Packer._pack
  File "msgpack/_packer.pyx", line 229, in msgpack._cmsgpack.Packer._pack
  File "msgpack/_packer.pyx", line 264, in msgpack._cmsgpack.Packer._pack
  File "msgpack/_packer.pyx", line 289, in msgpack._cmsgpack.Packer._pack
TypeError: can not serialize 'Delayed' object
distributed.batched - ERROR - Error in batched write
Traceback (most recent call last):
  File "/home/marta/IdeaProjectsVenvs/ML-DASK3.9/lib/python3.9/site-packages/distributed/batched.py", line 93, in _background_send
    nbytes = yield self.comm.write(
  File "/home/marta/IdeaProjectsVenvs/ML-DASK3.9/lib/python3.9/site-packages/tornado/gen.py", line 762, in run
    value = future.result()
  File "/home/marta/IdeaProjectsVenvs/ML-DASK3.9/lib/python3.9/site-packages/distributed/comm/tcp.py", line 235, in write
    frames = await to_frames(
  File "/home/marta/IdeaProjectsVenvs/ML-DASK3.9/lib/python3.9/site-packages/distributed/comm/utils.py", line 51, in to_frames
    return _to_frames()
  File "/home/marta/IdeaProjectsVenvs/ML-DASK3.9/lib/python3.9/site-packages/distributed/comm/utils.py", line 31, in _to_frames
    protocol.dumps(
  File "/home/marta/IdeaProjectsVenvs/ML-DASK3.9/lib/python3.9/site-packages/distributed/protocol/core.py", line 70, in dumps
    frames[0] = msgpack.dumps(msg, default=_encode_default, use_bin_type=True)
  File "/home/marta/IdeaProjectsVenvs/ML-DASK3.9/lib/python3.9/site-packages/msgpack/__init__.py", line 35, in packb
    return Packer(**kwargs).pack(o)
  File "msgpack/_packer.pyx", line 292, in msgpack._cmsgpack.Packer.pack
  File "msgpack/_packer.pyx", line 298, in msgpack._cmsgpack.Packer.pack
  File "msgpack/_packer.pyx", line 295, in msgpack._cmsgpack.Packer.pack
  File "msgpack/_packer.pyx", line 264, in msgpack._cmsgpack.Packer._pack
  File "msgpack/_packer.pyx", line 231, in msgpack._cmsgpack.Packer._pack
  File "msgpack/_packer.pyx", line 231, in msgpack._cmsgpack.Packer._pack
  File "msgpack/_packer.pyx", line 229, in msgpack._cmsgpack.Packer._pack
  File "msgpack/_packer.pyx", line 264, in msgpack._cmsgpack.Packer._pack
  File "msgpack/_packer.pyx", line 289, in msgpack._cmsgpack.Packer._pack
TypeError: can not serialize 'Delayed' object
Future exception was never retrieved
future: <Future finished exception=KeyError('_score-2ee7ee41-549a-4298-939c-a81d2358c5e3')>
Traceback (most recent call last):
  File "/home/marta/IdeaProjectsVenvs/ML-DASK3.9/lib/python3.9/site-packages/dask_ml/model_selection/_incremental.py", line 652, in _fit
    results = await fit(
  File "/home/marta/IdeaProjectsVenvs/ML-DASK3.9/lib/python3.9/site-packages/dask_ml/model_selection/_incremental.py", line 466, in fit
    return await _fit(
  File "/home/marta/IdeaProjectsVenvs/ML-DASK3.9/lib/python3.9/site-packages/dask_ml/model_selection/_incremental.py", line 262, in _fit
    metas = await client.gather(new_scores)
  File "/home/marta/IdeaProjectsVenvs/ML-DASK3.9/lib/python3.9/site-packages/distributed/client.py", line 1820, in _gather
    await All(
  File "/home/marta/IdeaProjectsVenvs/ML-DASK3.9/lib/python3.9/site-packages/distributed/utils.py", line 237, in All
    result = await tasks.next()
  File "/home/marta/IdeaProjectsVenvs/ML-DASK3.9/lib/python3.9/site-packages/distributed/client.py", line 1811, in wait
    st = self.futures[k]
KeyError: '_score-88b35868-a7ee-46d0-9939-1b9321b915e5'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/marta/IdeaProjectsVenvs/ML-DASK3.9/lib/python3.9/site-packages/tornado/gen.py", line 769, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/home/marta/IdeaProjectsVenvs/ML-DASK3.9/lib/python3.9/site-packages/distributed/utils.py", line 250, in quiet
    yield task
  File "/home/marta/IdeaProjectsVenvs/ML-DASK3.9/lib/python3.9/site-packages/tornado/gen.py", line 762, in run
    value = future.result()
  File "/home/marta/IdeaProjectsVenvs/ML-DASK3.9/lib/python3.9/site-packages/distributed/client.py", line 1811, in wait
    st = self.futures[k]
KeyError: '_score-2ee7ee41-549a-4298-939c-a81d2358c5e3'
/usr/local/lib/python3.9/asyncio/base_events.py:1875: RuntimeWarning: coroutine 'Future._result' was never awaited
  handle = self._ready.popleft()
Traceback (most recent call last):
  File "/home/marta/IdeaProjects/ML-DASK/hyperband_example.py", line 26, in <module>
    search.fit(X_train, y_train, classes=[0, 1])
  File "/home/marta/IdeaProjectsVenvs/ML-DASK3.9/lib/python3.9/site-packages/dask_ml/model_selection/_incremental.py", line 706, in fit
    return client.sync(self._fit, X, y, **fit_params)
  File "/home/marta/IdeaProjectsVenvs/ML-DASK3.9/lib/python3.9/site-packages/distributed/client.py", line 843, in sync
    return sync(
  File "/home/marta/IdeaProjectsVenvs/ML-DASK3.9/lib/python3.9/site-packages/distributed/utils.py", line 353, in sync
    raise exc.with_traceback(tb)
  File "/home/marta/IdeaProjectsVenvs/ML-DASK3.9/lib/python3.9/site-packages/distributed/utils.py", line 336, in f
    result[0] = yield future
  File "/home/marta/IdeaProjectsVenvs/ML-DASK3.9/lib/python3.9/site-packages/tornado/gen.py", line 762, in run
    value = future.result()
  File "/home/marta/IdeaProjectsVenvs/ML-DASK3.9/lib/python3.9/site-packages/dask_ml/model_selection/_hyperband.py", line 401, in _fit
    _SHAs = await asyncio.gather(
  File "/home/marta/IdeaProjectsVenvs/ML-DASK3.9/lib/python3.9/site-packages/dask_ml/model_selection/_incremental.py", line 652, in _fit
distributed.protocol.core - CRITICAL - Failed to Serialize
Traceback (most recent call last):
  File "/home/marta/IdeaProjectsVenvs/ML-DASK3.9/lib/python3.9/site-packages/distributed/protocol/core.py", line 70, in dumps
    frames[0] = msgpack.dumps(msg, default=_encode_default, use_bin_type=True)
  File "/home/marta/IdeaProjectsVenvs/ML-DASK3.9/lib/python3.9/site-packages/msgpack/__init__.py", line 35, in packb
    return Packer(**kwargs).pack(o)
  File "msgpack/_packer.pyx", line 292, in msgpack._cmsgpack.Packer.pack
  File "msgpack/_packer.pyx", line 298, in msgpack._cmsgpack.Packer.pack
  File "msgpack/_packer.pyx", line 295, in msgpack._cmsgpack.Packer.pack
  File "msgpack/_packer.pyx", line 264, in msgpack._cmsgpack.Packer._pack
  File "msgpack/_packer.pyx", line 231, in msgpack._cmsgpack.Packer._pack
  File "msgpack/_packer.pyx", line 231, in msgpack._cmsgpack.Packer._pack
  File "msgpack/_packer.pyx", line 229, in msgpack._cmsgpack.Packer._pack
  File "msgpack/_packer.pyx", line 264, in msgpack._cmsgpack.Packer._pack
  File "msgpack/_packer.pyx", line 289, in msgpack._cmsgpack.Packer._pack
TypeError: can not serialize 'Delayed' object
    results = await fit(distributed.comm.utils - ERROR - can not serialize 'Delayed' object
Traceback (most recent call last):
  File "/home/marta/IdeaProjectsVenvs/ML-DASK3.9/lib/python3.9/site-packages/distributed/comm/utils.py", line 31, in _to_frames
    protocol.dumps(
  File "/home/marta/IdeaProjectsVenvs/ML-DASK3.9/lib/python3.9/site-packages/distributed/protocol/core.py", line 70, in dumps
    frames[0] = msgpack.dumps(msg, default=_encode_default, use_bin_type=True)
  File "/home/marta/IdeaProjectsVenvs/ML-DASK3.9/lib/python3.9/site-packages/msgpack/__init__.py", line 35, in packb
    return Packer(**kwargs).pack(o)
  File "msgpack/_packer.pyx", line 292, in msgpack._cmsgpack.Packer.pack
  File "msgpack/_packer.pyx", line 298, in msgpack._cmsgpack.Packer.pack
  File "msgpack/_packer.pyx", line 295, in msgpack._cmsgpack.Packer.pack
  File "msgpack/_packer.pyx", line 264, in msgpack._cmsgpack.Packer._pack
  File "msgpack/_packer.pyx", line 231, in msgpack._cmsgpack.Packer._pack
  File "msgpack/_packer.pyx", line 231, in msgpack._cmsgpack.Packer._pack
  File "msgpack/_packer.pyx", line 229, in msgpack._cmsgpack.Packer._pack
  File "msgpack/_packer.pyx", line 264, in msgpack._cmsgpack.Packer._pack
  File "msgpack/_packer.pyx", line 289, in msgpack._cmsgpack.Packer._pack
TypeError: can not serialize 'Delayed' object

  File "/home/marta/IdeaProjectsVenvs/ML-DASK3.9/lib/python3.9/site-packages/dask_ml/model_selection/_incremental.py", line 466, in fit
    return await _fit(
  File "/home/marta/IdeaProjectsVenvs/ML-DASK3.9/lib/python3.9/site-packages/dask_ml/model_selection/_incremental.py", line 262, in _fit
distributed.batched - ERROR - Error in batched write
Traceback (most recent call last):
  File "/home/marta/IdeaProjectsVenvs/ML-DASK3.9/lib/python3.9/site-packages/distributed/batched.py", line 93, in _background_send
    nbytes = yield self.comm.write(
  File "/home/marta/IdeaProjectsVenvs/ML-DASK3.9/lib/python3.9/site-packages/tornado/gen.py", line 762, in run
    value = future.result()
  File "/home/marta/IdeaProjectsVenvs/ML-DASK3.9/lib/python3.9/site-packages/distributed/comm/tcp.py", line 235, in write
    frames = await to_frames(
  File "/home/marta/IdeaProjectsVenvs/ML-DASK3.9/lib/python3.9/site-packages/distributed/comm/utils.py", line 51, in to_frames
    return _to_frames()
  File "/home/marta/IdeaProjectsVenvs/ML-DASK3.9/lib/python3.9/site-packages/distributed/comm/utils.py", line 31, in _to_frames
    protocol.dumps(
  File "/home/marta/IdeaProjectsVenvs/ML-DASK3.9/lib/python3.9/site-packages/distributed/protocol/core.py", line 70, in dumps
    frames[0] = msgpack.dumps(msg, default=_encode_default, use_bin_type=True)
  File "/home/marta/IdeaProjectsVenvs/ML-DASK3.9/lib/python3.9/site-packages/msgpack/__init__.py", line 35, in packb
    return Packer(**kwargs).pack(o)
  File "msgpack/_packer.pyx", line 292, in msgpack._cmsgpack.Packer.pack
  File "msgpack/_packer.pyx", line 298, in msgpack._cmsgpack.Packer.pack
  File "msgpack/_packer.pyx", line 295, in msgpack._cmsgpack.Packer.pack
  File "msgpack/_packer.pyx", line 264, in msgpack._cmsgpack.Packer._pack
  File "msgpack/_packer.pyx", line 231, in msgpack._cmsgpack.Packer._pack
  File "msgpack/_packer.pyx", line 231, in msgpack._cmsgpack.Packer._pack
  File "msgpack/_packer.pyx", line 229, in msgpack._cmsgpack.Packer._pack
  File "msgpack/_packer.pyx", line 264, in msgpack._cmsgpack.Packer._pack
  File "msgpack/_packer.pyx", line 289, in msgpack._cmsgpack.Packer._pack
TypeError: can not serialize 'Delayed' object
    metas = await client.gather(new_scores)
  File "/home/marta/IdeaProjectsVenvs/ML-DASK3.9/lib/python3.9/site-packages/distributed/client.py", line 1820, in _gather
    await All(
  File "/home/marta/IdeaProjectsVenvs/ML-DASK3.9/lib/python3.9/site-packages/distributed/utils.py", line 237, in All
    result = await tasks.next()
  File "/home/marta/IdeaProjectsVenvs/ML-DASK3.9/lib/python3.9/site-packages/distributed/client.py", line 1811, in wait
    st = self.futures[k]
KeyError: '_score-88b35868-a7ee-46d0-9939-1b9321b915e5'
Task exception was never retrieved
future: <Task finished name='Task-462' coro=<Client._gather.<locals>.wait() done, defined at /home/marta/IdeaProjectsVenvs/ML-DASK3.9/lib/python3.9/site-packages/distributed/client.py:1809> exception=KeyError('_score-1a88a85a-8cf0-4088-9921-150314a56e61')>
Traceback (most recent call last):
  File "/home/marta/IdeaProjectsVenvs/ML-DASK3.9/lib/python3.9/site-packages/distributed/client.py", line 1811, in wait
    st = self.futures[k]
KeyError: '_score-1a88a85a-8cf0-4088-9921-150314a56e61'
Task exception was never retrieved
future: <Task finished name='Task-463' coro=<Client._gather.<locals>.wait() done, defined at /home/marta/IdeaProjectsVenvs/ML-DASK3.9/lib/python3.9/site-packages/distributed/client.py:1809> exception=KeyError('_score-10517a40-9eb3-4764-9672-986977a1b44e')>
Traceback (most recent call last):
  File "/home/marta/IdeaProjectsVenvs/ML-DASK3.9/lib/python3.9/site-packages/distributed/client.py", line 1811, in wait
    st = self.futures[k]
KeyError: '_score-10517a40-9eb3-4764-9672-986977a1b44e'
Task exception was never retrieved
future: <Task finished name='Task-464' coro=<Client._gather.<locals>.wait() done, defined at /home/marta/IdeaProjectsVenvs/ML-DASK3.9/lib/python3.9/site-packages/distributed/client.py:1809> exception=KeyError('_score-16bf6082-1efd-458e-986f-507bd5974e5e')>
Traceback (most recent call last):
  File "/home/marta/IdeaProjectsVenvs/ML-DASK3.9/lib/python3.9/site-packages/distributed/client.py", line 1811, in wait
    st = self.futures[k]
KeyError: '_score-16bf6082-1efd-458e-986f-507bd5974e5e'
Task exception was never retrieved
future: <Task finished name='Task-465' coro=<Client._gather.<locals>.wait() done, defined at /home/marta/IdeaProjectsVenvs/ML-DASK3.9/lib/python3.9/site-packages/distributed/client.py:1809> exception=KeyError('_score-b72d0a35-32f7-44b1-9aa3-5b32a13e7064')>
Traceback (most recent call last):
  File "/home/marta/IdeaProjectsVenvs/ML-DASK3.9/lib/python3.9/site-packages/distributed/client.py", line 1811, in wait
    st = self.futures[k]
KeyError: '_score-b72d0a35-32f7-44b1-9aa3-5b32a13e7064'
Task exception was never retrieved
future: <Task finished name='Task-466' coro=<Client._gather.<locals>.wait() done, defined at /home/marta/IdeaProjectsVenvs/ML-DASK3.9/lib/python3.9/site-packages/distributed/client.py:1809> exception=KeyError('_score-8efbd194-c234-4c55-8137-952ea07ce2c6')>
Traceback (most recent call last):
  File "/home/marta/IdeaProjectsVenvs/ML-DASK3.9/lib/python3.9/site-packages/distributed/client.py", line 1811, in wait
    st = self.futures[k]
KeyError: '_score-8efbd194-c234-4c55-8137-952ea07ce2c6'
Task exception was never retrieved
future: <Task finished name='Task-467' coro=<Client._gather.<locals>.wait() done, defined at /home/marta/IdeaProjectsVenvs/ML-DASK3.9/lib/python3.9/site-packages/distributed/client.py:1809> exception=KeyError('_score-e0bd6984-01eb-4fed-abb4-9dc699f2b450')>
Traceback (most recent call last):
  File "/home/marta/IdeaProjectsVenvs/ML-DASK3.9/lib/python3.9/site-packages/distributed/client.py", line 1811, in wait
    st = self.futures[k]
KeyError: '_score-e0bd6984-01eb-4fed-abb4-9dc699f2b450'
```

I have tried a couple different earlier python versions and different dask search techniques that require partial fit without success. However, I've had no issues with RandomizedSearchCV, using this toy example:

```python
from dask_ml.model_selection import RandomizedSearchCV
from dask_ml.datasets import make_classification
from sklearn.linear_model import SGDClassifier
from dask.distributed import Client
from dask_ml.model_selection import train_test_split
from scipy.stats import uniform, loguniform

if __name__ == '__main__':
    client = Client()

    X, y = make_classification(chunks=20, random_state=0)

    X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=0)

    clf = SGDClassifier(tol=1e-3, penalty='elasticnet', random_state=0)

    params = {'alpha': loguniform(1e-2, 1e0), 'l1_ratio': uniform(0, 1)}

    search = RandomizedSearchCV(clf, params, random_state=0)
    search.fit(X_train, y_train)
    print(search.best_params_)

    client.shutdown()
```

**Environment**:

- Dask version: 2021.04.0
- Python version: 3.9.4
- Operating System: Ubuntu 20.04.2 LTS
- Install method (conda, pip, source): pip

Thank you very much for any help.

**Comment by TomAugspurger** [comment]
Can you try with the latest `main` of Dask and Distributed. I could reproduce with earlier versions, but it may be fixed.

**Comment by martaccmoreno** [comment]
> Can you try with the latest `main` of Dask and Distributed. I could reproduce with earlier versions, but it may be fixed.

Running the same code example with `dask-2021.4.0+24.g29e17a05` and `distributed-2021.4.0+17.g74a9aff7`, I get a similar error:

```
distributed.protocol.core - CRITICAL - Failed to Serialize
Traceback (most recent call last):
  File "/home/marta/IdeaProjectsVenvs/ML-DASK3.9/lib/python3.9/site-packages/distributed/protocol/core.py", line 70, in dumps
    frames[0] = msgpack.dumps(msg, default=_encode_default, use_bin_type=True)
  File "/home/marta/IdeaProjectsVenvs/ML-DASK3.9/lib/python3.9/site-packages/msgpack/__init__.py", line 35, in packb
    return Packer(**kwargs).pack(o)
  File "msgpack/_packer.pyx", line 292, in msgpack._cmsgpack.Packer.pack
  File "msgpack/_packer.pyx", line 298, in msgpack._cmsgpack.Packer.pack
  File "msgpack/_packer.pyx", line 295, in msgpack._cmsgpack.Packer.pack
  File "msgpack/_packer.pyx", line 264, in msgpack._cmsgpack.Packer._pack
  File "msgpack/_packer.pyx", line 231, in msgpack._cmsgpack.Packer._pack
  File "msgpack/_packer.pyx", line 231, in msgpack._cmsgpack.Packer._pack
  File "msgpack/_packer.pyx", line 229, in msgpack._cmsgpack.Packer._pack
  File "msgpack/_packer.pyx", line 264, in msgpack._cmsgpack.Packer._pack
  File "msgpack/_packer.pyx", line 289, in msgpack._cmsgpack.Packer._pack
TypeError: can not serialize 'Delayed' object
distributed.comm.utils - ERROR - can not serialize 'Delayed' object
Traceback (most recent call last):
  File "/home/marta/IdeaProjectsVenvs/ML-DASK3.9/lib/python3.9/site-packages/distributed/comm/utils.py", line 31, in _to_frames
    protocol.dumps(
  File "/home/marta/IdeaProjectsVenvs/ML-DASK3.9/lib/python3.9/site-packages/distributed/protocol/core.py", line 70, in dumps
    frames[0] = msgpack.dumps(msg, default=_encode_default, use_bin_type=True)
  File "/home/marta/IdeaProjectsVenvs/ML-DASK3.9/lib/python3.9/site-packages/msgpack/__init__.py", line 35, in packb
    return Packer(**kwargs).pack(o)
  File "msgpack/_packer.pyx", line 292, in msgpack._cmsgpack.Packer.pack
  File "msgpack/_packer.pyx", line 298, in msgpack._cmsgpack.Packer.pack
  File "msgpack/_packer.pyx", line 295, in msgpack._cmsgpack.Packer.pack
  File "msgpack/_packer.pyx", line 264, in msgpack._cmsgpack.Packer._pack
  File "msgpack/_packer.pyx", line 231, in msgpack._cmsgpack.Packer._pack
  File "msgpack/_packer.pyx", line 231, in msgpack._cmsgpack.Packer._pack
  File "msgpack/_packer.pyx", line 229, in msgpack._cmsgpack.Packer._pack
  File "msgpack/_packer.pyx", line 264, in msgpack._cmsgpack.Packer._pack
  File "msgpack/_packer.pyx", line 289, in msgpack._cmsgpack.Packer._pack
TypeError: can not serialize 'Delayed' object
distributed.batched - ERROR - Error in batched write
Traceback (most recent call last):
  File "/home/marta/IdeaProjectsVenvs/ML-DASK3.9/lib/python3.9/site-packages/distributed/batched.py", line 93, in _background_send
    nbytes = yield self.comm.write(
  File "/home/marta/IdeaProjectsVenvs/ML-DASK3.9/lib/python3.9/site-packages/tornado/gen.py", line 762, in run
    value = future.result()
  File "/home/marta/IdeaProjectsVenvs/ML-DASK3.9/lib/python3.9/site-packages/distributed/comm/tcp.py", line 235, in write
    frames = await to_frames(
  File "/home/marta/IdeaProjectsVenvs/ML-DASK3.9/lib/python3.9/site-packages/distributed/comm/utils.py", line 51, in to_frames
    return _to_frames()
  File "/home/marta/IdeaProjectsVenvs/ML-DASK3.9/lib/python3.9/site-packages/distributed/comm/utils.py", line 31, in _to_frames
    protocol.dumps(
  File "/home/marta/IdeaProjectsVenvs/ML-DASK3.9/lib/python3.9/site-packages/distributed/protocol/core.py", line 70, in dumps
    frames[0] = msgpack.dumps(msg, default=_encode_default, use_bin_type=True)
  File "/home/marta/IdeaProjectsVenvs/ML-DASK3.9/lib/python3.9/site-packages/msgpack/__init__.py", line 35, in packb
    return Packer(**kwargs).pack(o)
  File "msgpack/_packer.pyx", line 292, in msgpack._cmsgpack.Packer.pack
  File "msgpack/_packer.pyx", line 298, in msgpack._cmsgpack.Packer.pack
  File "msgpack/_packer.pyx", line 295, in msgpack._cmsgpack.Packer.pack
  File "msgpack/_packer.pyx", line 264, in msgpack._cmsgpack.Packer._pack
  File "msgpack/_packer.pyx", line 231, in msgpack._cmsgpack.Packer._pack
  File "msgpack/_packer.pyx", line 231, in msgpack._cmsgpack.Packer._pack
  File "msgpack/_packer.pyx", line 229, in msgpack._cmsgpack.Packer._pack
  File "msgpack/_packer.pyx", line 264, in msgpack._cmsgpack.Packer._pack
  File "msgpack/_packer.pyx", line 289, in msgpack._cmsgpack.Packer._pack
TypeError: can not serialize 'Delayed' object
Traceback (most recent call last):
  File "/home/marta/IdeaProjects/ML-DASK/hyperband_example.py", line 20, in <module>
    search.fit(X_train, y_train, classes=[0, 1])
  File "/home/marta/IdeaProjectsVenvs/ML-DASK3.9/lib/python3.9/site-packages/dask_ml/model_selection/_incremental.py", line 706, in fit
    return client.sync(self._fit, X, y, **fit_params)
  File "/home/marta/IdeaProjectsVenvs/ML-DASK3.9/lib/python3.9/site-packages/distributed/client.py", line 843, in sync
    return sync(
  File "/home/marta/IdeaProjectsVenvs/ML-DASK3.9/lib/python3.9/site-packages/distributed/utils.py", line 353, in sync
    raise exc.with_traceback(tb)
  File "/home/marta/IdeaProjectsVenvs/ML-DASK3.9/lib/python3.9/site-packages/distributed/utils.py", line 336, in f
    result[0] = yield future
  File "/home/marta/IdeaProjectsVenvs/ML-DASK3.9/lib/python3.9/site-packages/tornado/gen.py", line 762, in run
    value = future.result()
  File "/home/marta/IdeaProjectsVenvs/ML-DASK3.9/lib/python3.9/site-packages/dask_ml/model_selection/_hyperband.py", line 401, in _fit
    _SHAs = await asyncio.gather(
  File "/home/marta/IdeaProjectsVenvs/ML-DASK3.9/lib/python3.9/site-packages/dask_ml/model_selection/_incremental.py", line 652, in _fit
    results = await fit(
  File "/home/marta/IdeaProjectsVenvs/ML-DASK3.9/lib/python3.9/site-packages/dask_ml/model_selection/_incremental.py", line 466, in fit
    return await _fit(
  File "/home/marta/IdeaProjectsVenvs/ML-DASK3.9/lib/python3.9/site-packages/dask_ml/model_selection/_incremental.py", line 174, in _fit
    m, m2 = await models[ident].result()
  File "/home/marta/IdeaProjectsVenvs/ML-DASK3.9/lib/python3.9/site-packages/distributed/client.py", line 222, in result
    raise result
TypeError: exceptions must derive from BaseException
```

And so on until I cancel execution.

**Comment by jrbourbeau** [comment]
I'm not able to reproduce the `msgpack` serialization error using `dask` and `distributed` 2021.04.0 or the latest `main` branch. 

@martaccmoreno could you add something like

```python
    import dask
    import distributed
    print(f"{dask.__version__ = }")
    print(f"{distributed.__version__ = }")
```

to the top of your example to double check the installed version of `dask` and `distributed`

**Comment by martaccmoreno** [comment]
> I'm not able to reproduce the `msgpack` serialization error using `dask` and `distributed` 2021.04.0 or the latest `main` branch.
> 
> @martaccmoreno could you add something like
> 
> ```python
>     import dask
>     import distributed
>     print(f"{dask.__version__ = }")
>     print(f"{distributed.__version__ = }")
> ```
> 
> to the top of your example to double check the installed version of `dask` and `distributed`

Hello,

By doing that I get the following output:

```
dask.__version__ = '2021.04.0+24.g29e17a05'
distributed.__version__ = '2021.04.0+17.g74a9aff7'
```

Which I believe is the expected result.

Also, I let the script run all the way through and edited the main post with the full error message, in case that sheds any further light on the issue.

**Comment by jrbourbeau** [comment]
Okay, that's good to know -- thanks @martaccmoreno! Could you try using the latest `dask-ml` main branch? There was a recent PR in `dask-ml` (https://github.com/dask/dask-ml/pull/793) which includes some `distributed` compatibility updates. I suspect that will fix the `TypeError: can not serialize 'Delayed' object` issue you're seeing

**Comment by martaccmoreno** [comment]
> I'm not able to reproduce the `msgpack` serialization error using `dask` and `distributed` 2021.04.0 or the latest `main` branch.
> 
> @martaccmoreno could you add something like
> 
> ```python
>     import dask
>     import distributed
>     print(f"{dask.__version__ = }")
>     print(f"{distributed.__version__ = }")
> ```
> 
> to the top of your example to double check the installed version of `dask` and `distributed`

Hello,

I updated to the latest main branch of dask-ml (in addition to updating dask and distributed) and now I'm capable of obtaining the expected result!

```
dask.__version__ = '2021.04.0+27.g42433599'
distributed.__version__ = '2021.04.0+19.g4e591531'
dask_ml.__version__ = '1.8.1.dev19+g0ea276da'

{'alpha': 0.5105423589265119, 'l1_ratio': 0.04464024357686458}
```

Further this fixed the issues I had encountered with running my own custom scripts. 

Thank you so much for  all the help!
