### ISSUE TITLE
Unexpected behaviour of /health endpoint of Dask sheduler and workers

### ISSUE THREAD

**Issue by peterroelants** [dask/dask#7582]
**What happened**:

Each time when I call the [`/health` HTTP endpoint](https://distributed.dask.org/en/latest/http_services.html#:~:text=/health) on either the Dask scheduler and worker my logs get printed the following line:
```
distributed.comm.tcp - INFO - Connection closed before handshake completed
```

What is more, when looking at the output I see binary output (and not [JSON](https://distributed.dask.org/en/latest/http_services.html#:~:text=JSON%20endpoints)):
```
$ wget --quiet -O - http://dask-scheduler:8786/health
:*��compression��python�	�
```
The status code seems to be `000`:
```
$ curl --silent --output /dev/null -w "%{http_code}" https://dask-scheduler:8786/health
000
```

**What you expected to happen**:

- I would expect the `/health` endpoints not to write to the logs when the status is ok. If something has to be printed I expect it to be less cryptic.
- I would expect the `/health` endpoint just [check if the service is alive](https://distributed.dask.org/en/latest/http_services.html#:~:text=check%20server%20is%20alive).
- I would expect the `/health` endpoint to return a status code of 200 when the service is ok.
- I would expect the `/health` endpoint to maybe return some additional information as [json](https://distributed.dask.org/en/latest/http_services.html#:~:text=JSON%20endpoints).
- I would expect the `/health` endpoint to work similar to (for example) [Hasura's /healthz](https://hasura.io/docs/latest/graphql/core/api-reference/health.html) endpoint. 

**Minimal Complete Verifiable Example**:

Start Dask scheduler (or worker) in a container with service name `dask-scheduler`:
```bash
dask-scheduler \
  --dashboard \
  --port 8786 \
  --host dask-scheduler \
  --dashboard-address ":8787"
```

Call [HTTP `/health` endpoint](https://distributed.dask.org/en/latest/http_services.html#:~:text=/health) via `curl`:
```bash
curl --output - http://dask-scheduler:8786/health 
```
or `wget`:
```
wget --quiet -O - http://dask-scheduler:8786/health
```

The dask scheduler can be replaced by a worker service with similar results.

**Anything else we need to know?**:

- I'm trying to use the `/health` endpoint for [Docker healthchecks](https://docs.docker.com/engine/reference/builder/#healthcheck) of my Dask deployment. I want to avoid setting the logger to a higher level to still capture other messages, however, the `/health` endpoint gets called on a regular interval and thus the current message spams my logs.
- I found a [stackoverflow message](https://stackoverflow.com/q/65853555) of someone running into the same issue on K8s (I think because K8s does this healthchecks automatically).
- Please let me know if I'm using the `/health` endpoint wrong. However, the status code of `000` together with the `Connection closed before handshake completed` message leads me to believe that somehow the connection is being disconnected prematurely.

**Environment**:

- Dask version: 2021.04.0+24.g29e17a05 (master branch)
- Python version: 3.9.2.final.0
- Operating System: Linux 5.8.0-50-generic (Debian Buster slim)
- Install method (conda, pip, source): pip in conda environment (`git+https://github.com/dask/dask@main` & `git+https://github.com/dask/distributed@main`)

**Comment by peterroelants** [comment]
This seems to be beyond just the `/health` endpoint. I just tried getting the `/sitemap.json` and get the following:
```
# wget --quiet -O - http://dask-scheduler:8786/sitemap.json
:*��compression��python�	�pickle-protocol
```
This output does not seem like json, as the extension would like me to believe.

**Comment by peterroelants** [comment]
Using Python and `urllib` I got a `http.client.BadStatusLine` error:

```
>>> import urllib.request
>>> req = urllib.request.Request('http://dask-scheduler:8786/sitemap.json')
>>> url_handle = urllib.request.urlopen(req)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/venv/lib/python3.9/urllib/request.py", line 214, in urlopen
    return opener.open(url, data, timeout)
  File "/venv/lib/python3.9/urllib/request.py", line 517, in open
    response = self._open(req, data)
  File "/venv/lib/python3.9/urllib/request.py", line 534, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/venv/lib/python3.9/urllib/request.py", line 494, in _call_chain
    result = func(*args)
  File "/venv/lib/python3.9/urllib/request.py", line 1375, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "/venv/lib/python3.9/urllib/request.py", line 1350, in do_open
    r = h.getresponse()
  File "/venv/lib/python3.9/http/client.py", line 1347, in getresponse
    response.begin()
  File "/venv/lib/python3.9/http/client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "/venv/lib/python3.9/http/client.py", line 289, in _read_status
    raise BadStatusLine(line)
http.client.BadStatusLine: :*«compressionÀ¦python	¯pickle-protocol
```
