### ISSUE TITLE
ValueError: bytes object is too large

### ISSUE THREAD

**Issue by nerdylinius** [dask/dask#7618]
### Description
I've been getting a "ValueError: bytes object is too large" error while using lightgbm with dask. How can I fix it?

 ### Reproducible example

```
from dask import array as da
train_df, val_df = get_train_val_data('2020-01-01', '2020-02-28', time_gap = 5, daily_fold=0, daily_k_fold=2, intraday_fold=0, intraday_k_fold=2)
train_chunks = min(100000, int(train_df.shape[0]/16))
val_chunks = min(100000, int(val_df.shape[0]/16))
Xy1 = da.from_array(train_df[selected_feats.ALL_FEATS+[selected_feats.TARGETS[0],]].values)
Xy2 = da.from_array(val_df[selected_feats.ALL_FEATS+[selected_feats.TARGETS[0],]].values)
X1, y1 = Xy1[:,:-1].rechunk(train_chunks), Xy1[:,-1].rechunk(train_chunks)
X2, y2 = Xy2[:,:-1].rechunk(val_chunks), Xy2[:,-1].rechunk(val_chunks)
print(X1.compute_chunk_sizes(), y1.compute_chunk_sizes())

dask_model = lg.DaskLGBMClassifier(num_leaves=1024, learning_rate=0.02, n_estimators=1000, colsample_bytree=0.7,
                                       n_jobs=300, silent=False)
dask_model.fit(X1, y1, eval_set=[(X2, y2)], eval_metric='auc', early_stopping_rounds=15)
```
### output
```
dask.array<rechunk-merge, shape=(6107340, 1002), dtype=float32, chunksize=(100000, 1002), chunktype=numpy.ndarray> dask.array<rechunk-merge, shape=(6107340,), dtype=float32, chunksize=(100000,), chunktype=numpy.ndarray>
Finding random open ports for workers
Traceback (most recent call last):
  File "/media/st2000/workspace/darkquant/darkquant/auto_trader/ashare/alpha_v10c/tree/dask_lg_train.py", line 138, in <module>
    dask_model.fit(X1, y1, eval_set=[(X2, y2)], eval_metric='auc', early_stopping_rounds=15)
  File "/home/hadoop/anaconda2/envs/pytorchenv/lib/python3.6/site-packages/lightgbm/dask.py", line 736, in fit
    **kwargs
  File "/home/hadoop/anaconda2/envs/pytorchenv/lib/python3.6/site-packages/lightgbm/dask.py", line 626, in _lgb_dask_fit
    **kwargs
  File "/home/hadoop/anaconda2/envs/pytorchenv/lib/python3.6/site-packages/lightgbm/dask.py", line 447, in _train
    for worker, list_of_parts in worker_map.items()
  File "/home/hadoop/anaconda2/envs/pytorchenv/lib/python3.6/site-packages/lightgbm/dask.py", line 447, in <listcomp>
    for worker, list_of_parts in worker_map.items()
  File "/home/hadoop/anaconda2/envs/pytorchenv/lib/python3.6/site-packages/distributed/client.py", line 1596, in submit
    actors=actor,
  File "/home/hadoop/anaconda2/envs/pytorchenv/lib/python3.6/site-packages/distributed/client.py", line 2594, in _graph_to_futures
    dsk = highlevelgraph_pack(dsk, self, keyset)
  File "/home/hadoop/anaconda2/envs/pytorchenv/lib/python3.6/site-packages/distributed/protocol/highlevelgraph.py", line 124, in highlevelgraph_pack
    return dumps_msgpack({"layers": layers})
  File "/home/hadoop/anaconda2/envs/pytorchenv/lib/python3.6/site-packages/distributed/protocol/core.py", line 184, in dumps_msgpack
    payload = msgpack.dumps(msg, default=msgpack_encode_default, use_bin_type=True)
  File "/home/hadoop/anaconda2/envs/pytorchenv/lib/python3.6/site-packages/msgpack/__init__.py", line 35, in packb
    return Packer(**kwargs).pack(o)
  File "msgpack/_packer.pyx", line 286, in msgpack._cmsgpack.Packer.pack
  File "msgpack/_packer.pyx", line 292, in msgpack._cmsgpack.Packer.pack
  File "msgpack/_packer.pyx", line 289, in msgpack._cmsgpack.Packer.pack
  File "msgpack/_packer.pyx", line 225, in msgpack._cmsgpack.Packer._pack
  File "msgpack/_packer.pyx", line 258, in msgpack._cmsgpack.Packer._pack
  File "msgpack/_packer.pyx", line 225, in msgpack._cmsgpack.Packer._pack
  File "msgpack/_packer.pyx", line 225, in msgpack._cmsgpack.Packer._pack
  File "msgpack/_packer.pyx", line 225, in msgpack._cmsgpack.Packer._pack
  File "msgpack/_packer.pyx", line 196, in msgpack._cmsgpack.Packer._pack
ValueError: bytes object is too large
```

### Environment info
lightgbm==3.2.1
dask==2021.01.1
python==3.6.8

**Comment by jrbourbeau** [comment]
Thanks for raising an issue @nerdylinius. This issue has been resolved in a recent release. Can you upgrade your `dask` and `distributed` versions to the latest release (version `2021.04.1`)?

**Comment by nerdylinius** [comment]
@jrbourbeau unfortunately, version 2021.04.1 is not supported by python 3.6， and it is not convenient for me to update python from 3.6 to 3.7+

**Comment by jrbourbeau** [comment]
In that case can you try `2021.03.0` (that's the last version to support Python 3.6)?

**Comment by nerdylinius** [comment]
@jrbourbeau I have tried 2021.03.0, but nothing changed

**Comment by jrbourbeau** [comment]
Hmm sorry to hear that. I believe this should be resolved by https://github.com/dask/dask/pull/7525 which was included in the `2021.04.1` release. However, given that you're on Python 3.6 I would recommend rolling back `dask` and `distributed` versions until the you get to a version that predates is bug that https://github.com/dask/dask/pull/7525 fixes. Unfortunately, I'm not sure what version that is off of memory.

**Comment by nerdylinius** [comment]
@jrbourbeau thank you any way, I will try 2021.04.1 when I update python from 3.6 to 3.7+

**Comment by jrbourbeau** [comment]
Sounds good 👍 Let us know if you're still experiencing this issue once you're on `2021.04.1`
