### ISSUE TITLE
Asynchronous clients cannot compute delayed

### ISSUE THREAD

**Issue by agoose77** [dask/dask#7646]
[![Binder](https://mybinder.org/badge_logo.svg)](https://mybinder.org/v2/gh/agoose77/5b61e23614fd82a5148de749d826ad1f/HEAD?filepath=reproducer.ipynb)

Running `dask.compute` on a `delayed` function with an asynchronous client raises an `Exception`. Locally, I see `'coroutine' object is not iterable`, but in the Binder I see `zip` complains about the first argument not being iterable. I presume these are the same errors that relate to differences in the Python version.

```python3
from dask import distributed, delayed
import dask
import numpy as np

client = await distributed.Client(asynchronous=True)
client

@delayed(pure=True)
def random_data(n):
    return np.random.random(size=n)

data = random_data(24)

dask.compute(data)
```

**Comment by jsignell** [comment]
Thanks for opening this and sorry it took a while to get to it. I am going to move this to the distributed issue tracker.

As a note, I tried using `client.compute(data)` instead of `dask.compute(data)` as recommended in https://examples.dask.org/applications/async-await.html and I got a different issue:

```python-traceback
tornado.application - ERROR - Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOLoop object at 0x7ff7489dfd90>>, <Task finished name='Task-10' coro=<Worker.heartbeat() done, defined at /home/julia/distributed/distributed/worker.py:943> exception=OSError('Timed out during handshake while connecting to tcp://127.0.0.1:33771 after 10 s')>)
Traceback (most recent call last):
  File "/home/julia/distributed/distributed/comm/core.py", line 320, in connect
    handshake = await asyncio.wait_for(comm.read(), time_left())
  File "/home/julia/conda/envs/dask-dev/lib/python3.8/asyncio/tasks.py", line 498, in wait_for
    raise exceptions.TimeoutError()
asyncio.exceptions.TimeoutError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/julia/conda/envs/dask-dev/lib/python3.8/site-packages/tornado/ioloop.py", line 741, in _run_callback
    ret = callback()
  File "/home/julia/conda/envs/dask-dev/lib/python3.8/site-packages/tornado/ioloop.py", line 765, in _discard_future_result
    future.result()
  File "/home/julia/distributed/distributed/worker.py", line 994, in heartbeat
    raise e
  File "/home/julia/distributed/distributed/worker.py", line 954, in heartbeat
    response = await retry_operation(
  File "/home/julia/distributed/distributed/utils_comm.py", line 385, in retry_operation
    return await retry(
  File "/home/julia/distributed/distributed/utils_comm.py", line 370, in retry
    return await coro()
  File "/home/julia/distributed/distributed/core.py", line 859, in send_recv_from_rpc
    comm = await self.pool.connect(self.addr)
  File "/home/julia/distributed/distributed/core.py", line 1010, in connect
    comm = await connect(
  File "/home/julia/distributed/distributed/comm/core.py", line 325, in connect
    raise IOError(
OSError: Timed out during handshake while connecting to tcp://127.0.0.1:33771 after 10 s
tornado.application - ERROR - Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOLoop object at 0x7f73280cdd60>>, <Task finished name='Task-10' coro=<Worker.heartbeat() done, defined at /home/julia/distributed/distributed/worker.py:943> exception=OSError('Timed out during handshake while connecting to tcp://127.0.0.1:33771 after 10 s')>)
Traceback (most recent call last):
  File "/home/julia/distributed/distributed/comm/core.py", line 320, in connect
    handshake = await asyncio.wait_for(comm.read(), time_left())
  File "/home/julia/conda/envs/dask-dev/lib/python3.8/asyncio/tasks.py", line 498, in wait_for
    raise exceptions.TimeoutError()
asyncio.exceptions.TimeoutError
```
