### ISSUE TITLE
dataclass issue with fields that have init=False

### ISSUE THREAD

**Issue by dboeckenhoff** [dask/dask#7654]
The issue is when using dataclasses with init=False fields:

import dataclasses
import dask

```python
@dataclasses.dataclass
class Entry:
    """
    Sql database entry using dataclass fields
    """
    primary_key: int = dataclasses.field(
        init=False, repr=False,
    )
    other_field: int = dataclasses.field(default=4)


@dask.delayed
def fun(entry):
    return "Hack works"


e = Entry()
graph = fun(e)
result = graph.compute()
print(result)
```

**What happened**:
Traceback (most recent call last):
  File "mwe2.py", line 22, in <module>
    graph = fun(e)
  File "/opt/anaconda/envs/py38/lib/python3.8/site-packages/dask/delayed.py", line 640, in __call__
    return call_function(
  File "/opt/anaconda/envs/py38/lib/python3.8/site-packages/dask/delayed.py", line 607, in call_function
    args2, collections = unzip(map(unpack_collections, args), 2)
  File "/opt/anaconda/envs/py38/lib/python3.8/site-packages/dask/delayed.py", line 25, in unzip
    out = list(zip(*ls))
  File "/opt/anaconda/envs/py38/lib/python3.8/site-packages/dask/delayed.py", line 108, in unpack_collections
    [[f.name, getattr(expr, f.name)] for f in dataclass_fields(expr)]
  File "/opt/anaconda/envs/py38/lib/python3.8/site-packages/dask/delayed.py", line 108, in <listcomp>
    [[f.name, getattr(expr, f.name)] for f in dataclass_fields(expr)]
AttributeError: 'Entry' object has no attribute 'primary_key'

**What you expected to happen**:
No problem. init=False should be treated.

**Minimal Complete Verifiable Example**:
see above

**Fix**:
To circumvent this bug, I added this ugly hack. This could be easily integrated in a clean way to dask.

```python
import dataclasses

# Hack to circumvent bug with dask.delayed and not initialized fields:
fields = dataclasses.fields
def dataclass_fields(expr):
    """
    Hack to bugfix dask datclass handling in case of init=False and not other setter
    """
    ret = []
    for field in fields(expr):
        if field.init or hasattr(expr, field.name):
            ret.append(field)
    return tuple(ret)
dataclasses.fields = dataclass_fields
import dask.compatibility
dask.compatibility.dataclass_fields = dataclass_fields
dataclasses.fields = fields
# hack end|

import dask


@dataclasses.dataclass
class Entry:
    """
    Sql database entry using dataclass fields
    """
    primary_key: int = dataclasses.field(
        init=False, repr=False,
    )
    other_field: int = dataclasses.field(default=4)


@dask.delayed
def fun(entry):
    return "Hack works"


e = Entry()
print("dataclass.fields:", [field.name for field in dataclasses.fields(e)])
print("dataclass_fields:", [field.name for field in dask.compatibility.dataclass_fields(e)])
dask.compatibility.dataclass_fields(e)
graph = fun(e)
result = graph.compute()
print(result)
```

**Environment**:

- Dask version: 2021.03.0
- Python version: 3.8
- Operating System: ubuntu
- Install method (conda, pip, source): conda

**Comment by jsignell** [comment]
Thanks for the great write-up! I just opened a PR for the fix.
