### ISSUE TITLE
Exception: signed integer is greater than maximum

### ISSUE THREAD

**Issue by RichardScottOZ** [dask/dask#7703]
**What happened**:

Errors when it should be fine

**What you expected to happen**:

Completiion of all examples

**Minimal Complete Verifiable Example**:

Satellite data processing on someone else's platform that I don't have access to via Open Datacube - so very complicated  to do that.

```python
# Put your MCVE code here
Index satellite data
Make a grid of futures
Result
Send to a parallelised future raster uploading to s3 function

```

**Anything else we need to know?**:
Same overflow error stopped a scheduler from beginning, too

**Environment**:

- Dask version:
- dask                              2021.3.0
dask-gateway                      0.9.0
dask-glm                          0.2.0
dask-image                        0.6.0
dask-kubernetes                   2021.3.1
dask-labextension                 4.0.1
dask-ml                           1.9.0
- Python version:
- 3.8
- Operating System:
- ubuntu
- Install method (conda, pip, source):
- pip

**Comment by RichardScottOZ** [comment]
``` python
distributed.core - ERROR - signed integer is greater than maximum
Traceback (most recent call last):
  File "/env/lib/python3.8/site-packages/distributed/core.py", line 554, in handle_stream
    msgs = await comm.read()
  File "/env/lib/python3.8/site-packages/distributed/comm/tcp.py", line 199, in read
    n = await stream.read_into(frames)
  File "/env/lib/python3.8/site-packages/tornado/iostream.py", line 475, in read_into
    self._try_inline_read()
  File "/env/lib/python3.8/site-packages/tornado/iostream.py", line 842, in _try_inline_read
    pos = self._read_to_buffer_loop()
  File "/env/lib/python3.8/site-packages/tornado/iostream.py", line 755, in _read_to_buffer_loop
    if self._read_to_buffer() == 0:
  File "/env/lib/python3.8/site-packages/tornado/iostream.py", line 867, in _read_to_buffer
    bytes_read = self.read_from_fd(buf)
  File "/env/lib/python3.8/site-packages/tornado/iostream.py", line 1592, in read_from_fd
    return self.socket.recv_into(buf, len(buf))
  File "/usr/lib/python3.8/ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.8/ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
OverflowError: signed integer is greater than maximum
```
This is the other one mentioned

**Comment by RichardScottOZ** [comment]
There is a reference to this happening to someone with 3.6

**Comment by RichardScottOZ** [comment]
``` python
distributed.scheduler - INFO - Retire workers {<Worker 'tls://10.0.108.82:35303', name: dask-worker-6976d1dd59bd49ffb870f3a9a93a00b9-79w9m, memory: 221, processing: 0>, <Worker 'tls://10.0.97.220:37351', name: dask-worker-6976d1dd59bd49ffb870f3a9a93a00b9-8d272, memory: 0, processing: 0>, <Worker 'tls://10.0.103.192:35103', name: dask-worker-6976d1dd59bd49ffb870f3a9a93a00b9-5ldjq, memory: 0, processing: 0>, <Worker 'tls://10.0.120.130:43769', name: dask-worker-6976d1dd59bd49ffb870f3a9a93a00b9-srnvj, memory: 0, processing: 0>, <Worker 'tls://10.0.126.145:44669', name: dask-worker-6976d1dd59bd49ffb870f3a9a93a00b9-86msn, memory: 0, processing: 0>, <Worker 'tls://10.0.102.194:40003', name: dask-worker-6976d1dd59bd49ffb870f3a9a93a00b9-4dm4q, memory: 0, processing: 0>, <Worker 'tls://10.0.114.165:36839', name: dask-worker-6976d1dd59bd49ffb870f3a9a93a00b9-pms9s, memory: 0, processing: 0>, <Worker 'tls://10.0.111.60:39735', name: dask-worker-6976d1dd59bd49ffb870f3a9a93a00b9-4svb7, memory: 0, processing: 0>, <Worker 'tls://10.0.107.252:43647', name: dask-worker-6976d1dd59bd49ffb870f3a9a93a00b9-l9lfj, memory: 0, processing: 0>, <Worker 'tls://10.0.121.78:34267', name: dask-worker-6976d1dd59bd49ffb870f3a9a93a00b9-slrzn, memory: 0, processing: 0>, <Worker 'tls://10.0.127.135:46627', name: dask-worker-6976d1dd59bd49ffb870f3a9a93a00b9-4gtk9, memory: 0, processing: 0>, <Worker 'tls://10.0.106.160:41721', name: dask-worker-6976d1dd59bd49ffb870f3a9a93a00b9-zbsdw, memory: 0, processing: 0>, <Worker 'tls://10.0.125.13:38993', name: dask-worker-6976d1dd59bd49ffb870f3a9a93a00b9-pc5f8, memory: 0, processing: 0>}

distributed.scheduler - INFO - Moving 221 keys to other workers

dask_gateway.scheduler_preload - WARNING - Failed to send heartbeat Traceback (most recent call last): File "/env/lib/python3.8/site-packages/dask_gateway/scheduler_preload.py", line 292, in heartbeat_loop await self.heartbeat() File "/env/lib/python3.8/site-packages/dask_gateway/scheduler_preload.py", line 278, in heartbeat await self.scheduler.retire_workers( File "/env/lib/python3.8/site-packages/distributed/scheduler.py", line 5752, in retire_workers await self.replicate( File "/env/lib/python3.8/site-packages/distributed/scheduler.py", line 5508, in replicate results = await asyncio.gather( File "/env/lib/python3.8/site-packages/distributed/utils_comm.py", line 384, in retry_operation return await retry( File "/env/lib/python3.8/site-packages/distributed/utils_comm.py", line 369, in retry return await coro() File "/env/lib/python3.8/site-packages/distributed/core.py", line 861, in send_recv_from_rpc result = await send_recv(comm=comm, op=key, **kwargs) File "/env/lib/python3.8/site-packages/distributed/core.py", line 662, in send_recv raise Exception(response["text"]) Exception: signed integer is greater than maximum
```

**Comment by RichardScottOZ** [comment]
``` python
distributed.worker - WARNING - Could not find data: {'my_func3-b9f1f140dd6b7894d38d461361bd50e6': ['tls://10.0.108.82:35303'], 'my_func3-9e8738986831bd557ac30f4ee7fcb727': ['tls://10.0.108.82:35303'], 'my_func3-013b409d539f0021077af0c01df11d14': ['tls://10.0.108.82:35303'], 'my_func3-f0018b22b29a8ef0a938b5fd928a2acf': ['tls://10.0.108.82:35303'], 'my_func3-76f7456a968f6cbcf5bf528ffe91287a': ['tls://10.0.108.82:35303'], 'my_func3-eff5533a7194155a4427b277d0962d76': ['tls://10.0.108.82:35303'], 'my_func3-7e691161d7f18e21dc8ae0cc26922561': ['tls://10.0.108.82:35303'], 'my_func3-4de607b2bf40e3e34b654151befcff2e': ['tls://10.0.108.82:35303'], 'my_func3-52a96ffde8b7c8c16d762891ea0f285e': ['tls://10.0.108.82:35303'], 'my_func3-d5d323765e220fbdc97777bc82ba5e04': ['tls://10.0.108.82:35303'], 'my_func3-092fe47889045119ceb7eb6166f69ebb': ['tls://10.0.108.82:35303'], 'my_func3-6199b611d893d844b9a556ae898d8e6b': ['tls://10.0.108.82:35303'], 'my_func3-68ac0516e6a8e30981794aa93d00fc6c': ['tls://10.0.108.82:35303'], 'my_func3-310a7a094172805853f144fb676083d9': ['tls://10.0.108.82:35303'], 'my_func3-a3d7e7560cb06ee83fb69971031441f2': ['tls://10.0.108.82:35303'], 'my_func3-b315b45b14ae913fa5c50cce557a88ef': ['tls://10.0.108.82:35303'], 'my_func3-12227e7b3eb6789a055dd2794ce59d23': ['tls://10.0.108.82:35303'], 'my_func3-96d9af24341c91522c25a055a7adaa60': ['tls://10.0.108.82:35303'], 'my_func3-7f357bdc5a8899cc5944828f04ae3c13': ['tls://10.0.108.82:35303'], 'my_func3-0c6c9fabe978cfd257dcf653da289f21': ['tls://10.0.108.82:35303'], 'my_func3-e8c88c01b0a0f69e0daece9801745324': ['tls://10.0.108.82:35303'], 'my_func3-1d6420766260cb699f35235c9cbc3daa': ['tls://10.0.108.82:35303'], 'my_func3-c5ba0d9cc8975ffecdb778c28c98f1f2': ['tls://10.0.108.82:35303'], 'my_func3-721e49280012c1707818f5360ea90c5d': ['tls://10.0.108.82:35303'], 'my_func3-3328160ccac615ecdf3ce61813bd5cb1': ['tls://10.0.108.82:35303'], 'my_func3-ffb8e8e7d5d15aef1c1d1e2bce965c76': ['tls://10.0.108.82:35303'], 'my_func3-ea81d885b8e98edb893b01a0131de87a': ['tls://10.0.108.82:35303'], 'my_func3-7684faa0593393534cac06425f32a40d': ['tls://10.0.108.82:35303'], 'my_func3-f061f7c926e1f00bf3fa45b038cc1b28': ['tls://10.0.108.82:35303'], 'my_func3-8a88dfd3c64d326aca39667e9f83e0ee': ['tls://10.0.108.82:35303'], 'my_func3-ae3e4b7c6c6983a70e9cc2fa0d683b18': ['tls://10.0.108.82:35303'], 'my_func3-ba874f55ef8fd0a72754d9e4d389c024': ['tls://10.0.108.82:35303'], 'my_func3-f4a5e60f9f3867384105f56869797299': ['tls://10.0.108.82:35303'], 'my_func3-b4a2d4f932a820dfc3b123b570eedb61': ['tls://10.0.108.82:35303'], 'my_func3-116d9a9a8390302c4f311f006fa321e2': ['tls://10.0.108.82:35303'], 'my_func3-0eb556d5b6e863dc03a64dfc20627fbf': ['tls://10.0.108.82:35303'], 'my_func3-1bd9e28f231b141e4103b5686e893efd': ['tls://10.0.108.82:35303'], 'my_func3-5146041b6be82e6cfbfbdf5f4b419725': ['tls://10.0.108.82:35303'], 'my_func3-f35480bb3d2ed00676ee6ee215903ad5': ['tls://10.0.108.82:35303'], 'my_func3-66cd7876e92f4d643e920aa092cab39b': ['tls://10.0.108.82:35303'], 'my_func3-f21c91d7000c8fe558231aab862078a9': ['tls://10.0.108.82:35303']} on workers: ['tls://10.0.108.82:35303'] (who_has: {'my_func3-52a96ffde8b7c8c16d762891ea0f285e': ['tls://10.0.108.82:35303'], 'my_func3-c5ba0d9cc8975ffecdb778c28c98f1f2': ['tls://10.0.108.82:35303'], 'my_func3-1bd9e28f231b141e4103b5686e893efd': ['tls://10.0.108.82:35303'], 'my_func3-7e691161d7f18e21dc8ae0cc26922561': ['tls://10.0.108.82:35303'], 'my_func3-e8c88c01b0a0f69e0daece9801745324': ['tls://10.0.108.82:35303'], 'my_func3-310a7a094172805853f144fb676083d9': ['tls://10.0.108.82:35303'], 'my_func3-eff5533a7194155a4427b277d0962d76': ['tls://10.0.108.82:35303'], 'my_func3-66cd7876e92f4d643e920aa092cab39b': ['tls://10.0.108.82:35303'], 'my_func3-12227e7b3eb6789a055dd2794ce59d23': ['tls://10.0.108.82:35303'], 'my_func3-f061f7c926e1f00bf3fa45b038cc1b28': ['tls://10.0.108.82:35303'], 'my_func3-ba874f55ef8fd0a72754d9e4d389c024': ['tls://10.0.108.82:35303'], 'my_func3-d5d323765e220fbdc97777bc82ba5e04': ['tls://10.0.108.82:35303'], 'my_func3-f4a5e60f9f3867384105f56869797299': ['tls://10.0.108.82:35303'], 'my_func3-013b409d539f0021077af0c01df11d14': ['tls://10.0.108.82:35303'], 'my_func3-68ac0516e6a8e30981794aa93d00fc6c': ['tls://10.0.108.82:35303'], 'my_func3-6199b611d893d844b9a556ae898d8e6b': ['tls://10.0.108.82:35303'], 'my_func3-8a88dfd3c64d326aca39667e9f83e0ee': ['tls://10.0.108.82:35303'], 'my_func3-3328160ccac615ecdf3ce61813bd5cb1': ['tls://10.0.108.82:35303'], 'my_func3-a3d7e7560cb06ee83fb69971031441f2': ['tls://10.0.108.82:35303'], 'my_func3-b4a2d4f932a820dfc3b123b570eedb61': ['tls://10.0.108.82:35303'], 'my_func3-ea81d885b8e98edb893b01a0131de87a': ['tls://10.0.108.82:35303'], 'my_func3-f0018b22b29a8ef0a938b5fd928a2acf': ['tls://10.0.108.82:35303'], 'my_func3-721e49280012c1707818f5360ea90c5d': ['tls://10.0.108.82:35303'], 'my_func3-9e8738986831bd557ac30f4ee7fcb727': ['tls://10.0.108.82:35303'], 'my_func3-7684faa0593393534cac06425f32a40d': ['tls://10.0.108.82:35303'], 'my_func3-7f357bdc5a8899cc5944828f04ae3c13': ['tls://10.0.108.82:35303'], 'my_func3-4de607b2bf40e3e34b654151befcff2e': ['tls://10.0.108.82:35303'], 'my_func3-76f7456a968f6cbcf5bf528ffe91287a': ['tls://10.0.108.82:35303'], 'my_func3-b315b45b14ae913fa5c50cce557a88ef': ['tls://10.0.108.82:35303'], 'my_func3-0c6c9fabe978cfd257dcf653da289f21': ['tls://10.0.108.82:35303'], 'my_func3-116d9a9a8390302c4f311f006fa321e2': ['tls://10.0.108.82:35303'], 'my_func3-ae3e4b7c6c6983a70e9cc2fa0d683b18': ['tls://10.0.108.82:35303'], 'my_func3-b9f1f140dd6b7894d38d461361bd50e6': ['tls://10.0.108.82:35303'], 'my_func3-f21c91d7000c8fe558231aab862078a9': ['tls://10.0.108.82:35303'], 'my_func3-1d6420766260cb699f35235c9cbc3daa': ['tls://10.0.108.82:35303'], 'my_func3-092fe47889045119ceb7eb6166f69ebb': ['tls://10.0.108.82:35303'], 'my_func3-ffb8e8e7d5d15aef1c1d1e2bce965c76': ['tls://10.0.108.82:35303'], 'my_func3-0eb556d5b6e863dc03a64dfc20627fbf': ['tls://10.0.108.82:35303'], 'my_func3-5146041b6be82e6cfbfbdf5f4b419725': ['tls://10.0.108.82:35303'], 'my_func3-f35480bb3d2ed00676ee6ee215903ad5': ['tls://10.0.108.82:35303'], 'my_func3-96d9af24341c91522c25a055a7adaa60': ['tls://10.0.108.82:35303']})
```

**Comment by RichardScottOZ** [comment]
combined with this now:-

``` python
distributed.worker - ERROR - failed during get data with tls://10.0.99.197:35515 -> tls://10.0.125.3:41273 Traceback (most recent call last): File "/env/lib/python3.8/site-packages/tornado/iostream.py", line 867, in _read_to_buffer bytes_read = self.read_from_fd(buf) File "/env/lib/python3.8/site-packages/tornado/iostream.py", line 1592, in read_from_fd return self.socket.recv_into(buf, len(buf)) File "/usr/lib/python3.8/ssl.py", line 1241, in recv_into return self.read(nbytes, buffer) File "/usr/lib/python3.8/ssl.py", line 1099, in read return self._sslobj.read(len, buffer) ConnectionResetError: [Errno 104] Connection reset by peer The above exception was the direct cause of the following exception: Traceback (most recent call last): File "/env/lib/python3.8/site-packages/distributed/worker.py", line 1360, in get_data response = await comm.read(deserializers=serializers) File "/env/lib/python3.8/site-packages/distributed/comm/tcp.py", line 205, in read convert_stream_closed_error(self, e) File "/env/lib/python3.8/site-packages/distributed/comm/tcp.py", line 124, in convert_stream_closed_error raise CommClosedError( distributed.comm.core.CommClosedError: in <closed TLS>: ConnectionResetError: [Errno 104] Connection reset by peer
```
``` python
istributed.scheduler - INFO - Moving 479 keys to other workers

dask_gateway.scheduler_preload - WARNING - Failed to send heartbeat Traceback (most recent call last): File "/env/lib/python3.8/site-packages/dask_gateway/scheduler_preload.py", line 292, in heartbeat_loop await self.heartbeat() File "/env/lib/python3.8/site-packages/dask_gateway/scheduler_preload.py", line 278, in heartbeat await self.scheduler.retire_workers( File "/env/lib/python3.8/site-packages/distributed/scheduler.py", line 5752, in retire_workers await self.replicate( File "/env/lib/python3.8/site-packages/distributed/scheduler.py", line 5508, in replicate results = await asyncio.gather( File "/env/lib/python3.8/site-packages/distributed/utils_comm.py", line 384, in retry_operation return await retry( File "/env/lib/python3.8/site-packages/distributed/utils_comm.py", line 369, in retry return await coro() File "/env/lib/python3.8/site-packages/distributed/core.py", line 861, in send_recv_from_rpc result = await send_recv(comm=comm, op=key, **kwargs) File "/env/lib/python3.8/site-packages/distributed/core.py", line 662, in send_recv raise Exception(response["text"]) Exception: signed integer is greater than maximum
```

**Comment by jrbourbeau** [comment]
Thanks for reporting @RichardScottOZ. I've re-opened https://github.com/dask/distributed/issues/4538. Let's continue the conversation over there since that thread has some previous discussions in it
