### ISSUE TITLE
Install with pyodide

### ISSUE THREAD

**Issue by mrocklin** [dask/dask#7764]
I was playing around with jupyterlite and tried to install Dask

```python
import micropip
await micropip.install("dask")
```

I think that it would be fun if we could get dask and distributed running smoothly.  My guess is that this is doable _if_ we're able to package things up in a pure python way, but that currently we're not in some way. 

cc @jakirkham who I suspect understands this space well

<details>

<summary> Traceback </summary>

```python-traceback
Traceback (most recent call last):
  File "<console>", line 2, in <module>
  File "/lib/python3.8/asyncio/futures.py", line 260, in __await__
    yield self  # This tells Task to wait for completion.
  File "/lib/python3.8/asyncio/tasks.py", line 349, in __wakeup
    future.result()
  File "/lib/python3.8/asyncio/futures.py", line 178, in result
    raise self._exception
  File "/lib/python3.8/asyncio/tasks.py", line 282, in __step
    result = coro.throw(exc)
  File "/lib/python3.8/site-packages/micropip.py", line 158, in install
    transaction = await self.gather_requirements(requirements, ctx)
  File "/lib/python3.8/site-packages/micropip.py", line 154, in gather_requirements
    await gather(*requirement_promises)
  File "/lib/python3.8/asyncio/futures.py", line 260, in __await__
    yield self  # This tells Task to wait for completion.
  File "/lib/python3.8/asyncio/tasks.py", line 349, in __wakeup
    future.result()
  File "/lib/python3.8/asyncio/futures.py", line 178, in result
    raise self._exception
  File "/lib/python3.8/asyncio/tasks.py", line 280, in __step
    result = coro.send(None)
  File "/lib/python3.8/site-packages/micropip.py", line 227, in add_requirement
    await self.add_requirement(recurs_req, ctx, transaction)
  File "/lib/python3.8/site-packages/micropip.py", line 222, in add_requirement
    wheel, ver = self.find_wheel(metadata, req)
  File "/lib/python3.8/site-packages/micropip.py", line 238, in find_wheel
    release = releases[str(ver)]
KeyError: '3.9'
PythonError: Traceback (most recent call last):
  File "/lib/python3.8/asyncio/futures.py", line 178, in result
    raise self._exception
  File "/lib/python3.8/asyncio/tasks.py", line 282, in __step
    result = coro.throw(exc)
  File "/lib/python3.8/site-packages/pyolite/interpreter.py", line 23, in run
    result = await self.run_complete
  File "/lib/python3.8/asyncio/futures.py", line 260, in __await__
    yield self  # This tells Task to wait for completion.
  File "/lib/python3.8/asyncio/tasks.py", line 349, in __wakeup
    future.result()
  File "/lib/python3.8/asyncio/futures.py", line 178, in result
    raise self._exception
  File "/lib/python3.8/asyncio/tasks.py", line 282, in __step
    result = coro.throw(exc)
  File "/lib/python3.8/site-packages/pyodide/console.py", line 253, in load_packages_and_run
    raise e
  File "/lib/python3.8/site-packages/pyodide/console.py", line 247, in load_packages_and_run
    result = await eval_code_async(
  File "/lib/python3.8/site-packages/pyodide/_base.py", line 419, in eval_code_async
    return await CodeRunner(
  File "/lib/python3.8/site-packages/pyodide/_base.py", line 278, in run_async
    res = await res
  File "<console>", line 2, in <module>
  File "/lib/python3.8/asyncio/futures.py", line 260, in __await__
    yield self  # This tells Task to wait for completion.
  File "/lib/python3.8/asyncio/tasks.py", line 349, in __wakeup
    future.result()
  File "/lib/python3.8/asyncio/futures.py", line 178, in result
    raise self._exception
  File "/lib/python3.8/asyncio/tasks.py", line 282, in __step
    result = coro.throw(exc)
  File "/lib/python3.8/site-packages/micropip.py", line 158, in install
    transaction = await self.gather_requirements(requirements, ctx)
  File "/lib/python3.8/site-packages/micropip.py", line 154, in gather_requirements
    await gather(*requirement_promises)
  File "/lib/python3.8/asyncio/futures.py", line 260, in __await__
    yield self  # This tells Task to wait for completion.
  File "/lib/python3.8/asyncio/tasks.py", line 349, in __wakeup
    future.result()
  File "/lib/python3.8/asyncio/futures.py", line 178, in result
    raise self._exception
  File "/lib/python3.8/asyncio/tasks.py", line 280, in __step
    result = coro.send(None)
  File "/lib/python3.8/site-packages/micropip.py", line 227, in add_requirement
    await self.add_requirement(recurs_req, ctx, transaction)
  File "/lib/python3.8/site-packages/micropip.py", line 222, in add_requirement
    wheel, ver = self.find_wheel(metadata, req)
  File "/lib/python3.8/site-packages/micropip.py", line 238, in find_wheel
    release = releases[str(ver)]
KeyError: '3.9'

    at new_error (https://cdn.jsdelivr.net/pyodide/v0.17.0/full/pyodide.asm.js:9:175413)
    at wrap_exception (https://cdn.jsdelivr.net/pyodide/v0.17.0/full/pyodide.asm.wasm:wasm-function[297]:0x1a6c94)
    at FutureDoneCallback_call (https://cdn.jsdelivr.net/pyodide/v0.17.0/full/pyodide.asm.wasm:wasm-function[379]:0x1aaab3)
    at byn$fpcast-emu$FutureDoneCallback_call (https://cdn.jsdelivr.net/pyodide/v0.17.0/full/pyodide.asm.wasm:wasm-function[14420]:0x7a257c)
    at _PyObject_MakeTpCall (https://cdn.jsdelivr.net/pyodide/v0.17.0/full/pyodide.asm.wasm:wasm-function[760]:0x1cabed)
    at __static_1198 (https://cdn.jsdelivr.net/pyodide/v0.17.0/full/pyodide.asm.wasm:wasm-function[2906]:0x2c54f1)
    at byn$fpcast-emu$__static_1198 (https://cdn.jsdelivr.net/pyodide/v0.17.0/full/pyodide.asm.wasm:wasm-function[22640]:0x7bf866)
    at __static_678 (https://cdn.jsdelivr.net/pyodide/v0.17.0/full/pyodide.asm.wasm:wasm-function[1621]:0x21220e)
    at byn$fpcast-emu$__static_678 (https://cdn.jsdelivr.net/pyodide/v0.17.0/full/pyodide.asm.wasm:wasm-function[22120]:0x7bdce6)
    at PyVectorcall_Call (https://cdn.jsdelivr.net/pyodide/v0.17.0/full/pyodide.asm.wasm:wasm-function[763]:0x1cb006)
```

</details>

**Comment by mrocklin** [comment]
Ah, it looks like this problem goes deeper

```python
import micropip
await micropip.install("tornado")
```

```python-traceback
ValueError: Couldn't find a pure Python 3 wheel for 'tornado'
```

**Comment by mrocklin** [comment]
Also, I'm guessing that micropip is the right way to install, given https://pyodide.org/en/stable/usage/loading-packages.html#micropip but I'm very new to this.

**Comment by mrocklin** [comment]
This works

```python
import micropip
await micropip.install("https://files.pythonhosted.org/packages/94/7c/f4b5259130ecdb0d2c7bc12b32eb8465b74e98b52c86f85de8b6ba5b112c/dask-2021.5.1-py3-none-any.whl")
```

It looks like maybe pyyaml is the blocker here.

**Comment by gjoseph92** [comment]
As a more theoretical question—what would the point be of using dask in pyodide right now? pyodide doesn't seem to support threads or other forms of concurrency yet https://github.com/pyodide/pyodide/issues/237.

```python
Welcome to the Pyodide terminal emulator 🐍
Python 3.8.2 (default, Apr 21 2021 19:58:37) on WebAssembly VM
Type "help", "copyright", "credits" or "license" for more information.
>>> import concurrent.futures
>>> import time
>>> with concurrent.futures.ThreadPoolExecutor() as exc:
...   _ = exc.map(lambda _: time.sleep(1), range(10))
... 
Traceback (most recent call last):
  File "<console>", line 2, in <module>
  File "/lib/python3.8/concurrent/futures/_base.py", line 600, in map
    fs = [self.submit(fn, *args) for args in zip(*iterables)]
  File "/lib/python3.8/concurrent/futures/_base.py", line 600, in <listcomp>
    fs = [self.submit(fn, *args) for args in zip(*iterables)]
  File "/lib/python3.8/concurrent/futures/thread.py", line 188, in submit
    self._adjust_thread_count()
  File "/lib/python3.8/concurrent/futures/thread.py", line 213, in _adjust_thread_count
    t.start()
  File "/lib/python3.8/threading.py", line 852, in start
    _start_new_thread(self._bootstrap, ())
RuntimeError: can't start new thread
```

The [WASM threading model](https://github.com/WebAssembly/threads) is still at the proposal stage, so it'll probably still be some time until that's matured to where making a Python thread in pyodide just works.

So you couldn't use dask for parallel computation in the browser right now. The main cool thing I can imagine would be constructing graphs in the browser, then connecting to a real Python cluster running elsewhere and submitting them.

I agree this will be cool, but let's define what "running smoothly" will actually mean right now.

**Comment by jakirkham** [comment]
> cc @jakirkham who I suspect understands this space well

Hehe not really 😅

**Comment by jakirkham** [comment]
cc @rth (who may know more here)

**Comment by rth** [comment]
If all the dependencies are pure Python and have wheels  they would indeed be uninstallable with micropip.

> It looks like maybe pyyaml is the blocker here.

Indeed, it should be resolved with https://github.com/pyodide/pyodide/pull/1181

A complication is that
 - tornado has some C extensions and so would need to be compiled via the Pyodide build system by adding it as a [package here](https://github.com/pyodide/pyodide/tree/main/packages)
 -  and more importantly sockets aren't supported in the Webassembly VM : that might be a blocker for tornado?

If tornado doesn't work, I imagine, then one would need to find some alternative for communicating between nodes, possibly with WebSockets.

In the WASM VM, multiprocessing is indeed not supported, threading is not supported yet on all browsers (and not enabled in Pyodide), however there is a possibility to use [WebWorkers](https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API/Using_web_workers) which also allow to create separate threads although with a different API.

> As a more theoretical question — what would the point be of using dask in pyodide right now?

One could be to offload expensive calculations to a cluster. Though in that respect one could also just use jupyter notebook directly with a locally running dask.

Another use case would be to be able to send commands to Python in WASM from Python running locally (or the other way around), for instance for testing https://github.com/pytest-dev/pytest-xdist/issues/336

**Comment by mrocklin** [comment]
> As a more theoretical question—what would the point be of using dask in pyodide right now? pyodide doesn't seem to support threads or other forms of concurrency yet pyodide/pyodide#237.

We could connect to remote Dask clusters

> and more importantly sockets aren't supported in the Webassembly VM : that might be a blocker for tornado?

Ah, if sockets are out then yeah, this has limited utility.

**Comment by mrocklin** [comment]
So, how not-supported are sockets.  Are there any inter-node communication systems available?  Websockets maybe?

**Comment by tomwhite** [comment]
Dask array in local synchronous mode works fine (with a workaround from https://github.com/pyodide/pyodide/issues/1603) on https://pyodide.org/en/latest/console.html

Nice for demos, teaching, trying things out etc.

```
Welcome to the Pyodide terminal emulator 🐍
Python 3.9.5 (default, Aug 28 2021 07:18:29) on WebAssembly VM
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> sys.modules['_multiprocessing'] = object # see https://github.com/pyodide/pyodide/issues/1603
>>> import micropip
>>> await micropip.install("dask[array]")
>>> import dask
>>> dask.config.set(scheduler='synchronous')
<dask.config.set object at 0xc8ef10>
>>> import numpy # not sure why this is needed, following line fails otherwise
>>> import dask.array as da
>>> x = da.random.random((1000, 1000), chunks=(100, 100))
>>> x.compute()
array([[0.13043454, 0.16097226, 0.12493807, ..., 0.71990046, 0.64542954,
        0.55997499],
       [0.02051068, 0.59918816, 0.25248748, ..., 0.05438529, 0.05219407,
        0.97351945],
       [0.76723807, 0.95366328, 0.10620701, ..., 0.66297666, 0.52551189,
        0.5808868 ],
       ...,
       [0.58133475, 0.16766972, 0.71604937, ..., 0.62901447, 0.9411289 ,
        0.45654889],
       [0.44033403, 0.59576681, 0.81159661, ..., 0.60512902, 0.99332665,
        0.10700775],
       [0.73980408, 0.05269962, 0.079521  , ..., 0.8677161 , 0.25877279,
        0.39054187]])
>>> 
 
 

```

**Comment by jakirkham** [comment]
@ashokgaire my guess is one would need to build [a new package for Pyodide]( https://pyodide.org/en/stable/development/new-packages.html ). In any event this is off-topic for this issue. So would recommend following up on [the pyodide issue tracker]( https://github.com/pyodide/pyodide/issues/new ) for help getting that started. Thanks! 😄

**Comment by jakirkham** [comment]
cc @davidbrochart (for awareness)

**Comment by davidbrochart** [comment]
The long-term approach is to have conda-forge support a Wasm platform, then we would use conda to build environments as we are used to, instead of having a monolithic "Python + shipped libraries".
[CPython can now "officially" be build for Wasm](https://github.com/ethanhs/python-wasm), and we have started working on the conda-forge wasm target. It's going to take some time, but we'll get there!

**Comment by bollwyvl** [comment]
Huzzah, looks like a bunch of the examples Just Work :tm:  in [jupyterlite](https://jupyterlite.readthedocs.io/en/latest/_static/lab/index.html) today:

```python
import piplite
await piplite.install('dask[array,dataframe,diagnostics]')
import dask.array as da

x = da.random.random((1000, 1000), chunks=(100, 100))
x.compute()
```

And the demo site even has `ipycytoscape`:
```
import dask
df = dask.datasets.timeseries()
df.visualize()
```

Seems like some hot examples in the docs are more than possible now, akin to what `numpy`, `pandas`, `sympy` and `ipywidgets` are doing.

**Comment by jakirkham** [comment]
Sounds like this more-or-less works. Going to close. Please feel free to raise anything else as a new issue. Thanks all! 🙏
