### ISSUE TITLE
Add `DataFrame.to_numpy()` and `Series.to_numpy()` to deal with nullable int

### ISSUE THREAD

**Issue by flcong** [dask/dask#7816]
While `DataFrame.values` and `Series.values` are implemented, since the introduction of nullable int in pandas, the `values` attribute does not work with nullable int. For example, although
```python
dd.from_pandas(pd.DataFrame({'x': [1, 2, pd.NA], 'y': [1, 2, 3]}, dtype='Int32'), npartitions=1).values
```
returns a dask array
```python
dask.array<values, shape=(nan, 2), dtype=object, chunksize=(nan, 2), chunktype=numpy.ndarray>
```
,
```python
dd.from_pandas(pd.DataFrame({'x': [1, 2, pd.NA], 'y': [1, 2, 3]}, dtype='Int32'), npartitions=1)['x'].values
```
raises an error:
```
Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm 2021.1.1\plugins\python\helpers\pydev\_pydevd_bundle\pydevd_exec2.py", line 3, in Exec
    exec(exp, global_vars, local_vars)
  File "<input>", line 1, in <module>
  File "C:\Programs\miniconda3\envs\dask-sql\lib\site-packages\dask\dataframe\core.py", line 2903, in values
    return self.map_partitions(methods.values)
  File "C:\Programs\miniconda3\envs\dask-sql\lib\site-packages\dask\dataframe\core.py", line 691, in map_partitions
    return map_partitions(func, self, *args, **kwargs)
  File "C:\Programs\miniconda3\envs\dask-sql\lib\site-packages\dask\dataframe\core.py", line 5734, in map_partitions
    return new_dd_object(graph, name, meta, divisions)
  File "C:\Programs\miniconda3\envs\dask-sql\lib\site-packages\dask\dataframe\core.py", line 6788, in new_dd_object
    return da.Array(dsk, name=name, chunks=chunks, dtype=meta.dtype)
  File "C:\Programs\miniconda3\envs\dask-sql\lib\site-packages\dask\array\core.py", line 1122, in __new__
    meta = meta_from_array(meta, dtype=dtype)
  File "C:\Programs\miniconda3\envs\dask-sql\lib\site-packages\dask\array\utils.py", line 66, in meta_from_array
    x = x(shape=(0,) * (ndim or 0), dtype=dtype)
TypeError: Cannot interpret 'Int32Dtype()' as a data type
```

**Comment by jsignell** [comment]
Thank you for writing this up. This is a known issue that is captured in https://github.com/dask/dask/issues/7206 and there are two PRs open to discuss possible approaches #7375 and #7399
