### ISSUE TITLE
AttributeError: module 'sparse' has no attribute 'SparseArray' 

### ISSUE THREAD

**Issue by ericdill** [dask/dask#7909]
Honestly not totally sure even how to debug this one. If I add `sparse` to my requirements then things work just fine, but its weird that this combination of packages seems to make dask unhappy

**What happened**:
conda/mamba creation of new environment results in unimportable dask.dataframe

**What you expected to happen**:
Be able to import dask.dataframe

**Minimal Complete Verifiable Example**:
requirements.txt:
```file
pandas
tqdm
requests
ipykernel
dask
```

Run either mamba or conda create:
`conda/mamba create -n testenv --file requirements.txt`

Activate env and try to import:
```
$ conda activate testenv
$ python -c "import dask.dataframe"

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/ericdill/miniconda/envs/test2/lib/python3.9/site-packages/dask/dataframe/__init__.py", line 3, in <module>
    from . import backends, dispatch, rolling
  File "/Users/ericdill/miniconda/envs/test2/lib/python3.9/site-packages/dask/dataframe/backends.py", line 19, in <module>
    from .core import DataFrame, Index, Scalar, Series, _Frame
  File "/Users/ericdill/miniconda/envs/test2/lib/python3.9/site-packages/dask/dataframe/core.py", line 26, in <module>
    from .. import array as da
  File "/Users/ericdill/miniconda/envs/test2/lib/python3.9/site-packages/dask/array/__init__.py", line 3, in <module>
    from . import backends, fft, lib, linalg, ma, overlap, random
  File "/Users/ericdill/miniconda/envs/test2/lib/python3.9/site-packages/dask/array/fft.py", line 13, in <module>
    from .core import concatenate as _concatenate
  File "/Users/ericdill/miniconda/envs/test2/lib/python3.9/site-packages/dask/array/core.py", line 62, in <module>
    from .chunk_types import is_valid_array_chunk, is_valid_chunk_type
  File "/Users/ericdill/miniconda/envs/test2/lib/python3.9/site-packages/dask/array/chunk_types.py", line 124, in <module>
    register_chunk_type(sparse.SparseArray)
AttributeError: module 'sparse' has no attribute 'SparseArray'
```

**Anything else we need to know?**:

**Environment**:
```
# packages in environment at /Users/ericdill/miniconda/envs/test2:
#
# Name                    Version                   Build  Channel
appnope                   0.1.2            py39h2804cbe_1    conda-forge
backcall                  0.2.0              pyh9f0ad1d_0    conda-forge
backports                 1.0                        py_2    conda-forge
backports.functools_lru_cache 1.6.4              pyhd8ed1ab_0    conda-forge
bokeh                     2.3.3            py39h2804cbe_0    conda-forge
brotlipy                  0.7.0           py39h5161555_1001    conda-forge
ca-certificates           2021.5.30            h4653dfc_0    conda-forge
certifi                   2021.5.30        py39h2804cbe_0    conda-forge
cffi                      1.14.6           py39hda8b47f_0    conda-forge
chardet                   4.0.0            py39h2804cbe_1    conda-forge
charset-normalizer        2.0.0              pyhd8ed1ab_0    conda-forge
click                     8.0.1            py39h2804cbe_0    conda-forge
cloudpickle               1.6.0                      py_0    conda-forge
cryptography              3.4.7            py39h73257c9_0    conda-forge
cytoolz                   0.11.0           py39h5161555_3    conda-forge
dask                      2021.7.0           pyhd8ed1ab_0    conda-forge
dask-core                 2021.7.0           pyhd8ed1ab_0    conda-forge
debugpy                   1.3.0            py39hfb83b0d_0    conda-forge
decorator                 5.0.9              pyhd8ed1ab_0    conda-forge
distributed               2021.7.0         py39h2804cbe_0    conda-forge
freetype                  2.10.4               h17b34a0_1    conda-forge
fsspec                    2021.7.0           pyhd8ed1ab_0    conda-forge
heapdict                  1.0.1                      py_0    conda-forge
idna                      3.1                pyhd3deb0d_0    conda-forge
ipykernel                 6.0.2            py39h32adebf_0    conda-forge
ipython                   7.25.0           py39h32adebf_1    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
jbig                      2.1               h3422bc3_2003    conda-forge
jedi                      0.18.0           py39h2804cbe_2    conda-forge
jinja2                    3.0.1              pyhd8ed1ab_0    conda-forge
jpeg                      9d                   h27ca646_0    conda-forge
jupyter_client            6.1.12             pyhd8ed1ab_0    conda-forge
jupyter_core              4.7.1            py39h2804cbe_0    conda-forge
lcms2                     2.12                 had6a04f_0    conda-forge
lerc                      2.2.1                h9f76cd9_0    conda-forge
libblas                   3.9.0                9_openblas    conda-forge
libcblas                  3.9.0                9_openblas    conda-forge
libcxx                    12.0.1               h168391b_0    conda-forge
libdeflate                1.7                  h27ca646_5    conda-forge
libffi                    3.3                  h9f76cd9_2    conda-forge
libgfortran               5.0.0.dev0      11_0_1_hf114ba7_22    conda-forge
libgfortran5              11.0.1.dev0         hf114ba7_22    conda-forge
liblapack                 3.9.0                9_openblas    conda-forge
libopenblas               0.3.15          openmp_hf330de4_1    conda-forge
libpng                    1.6.37               hf7e6567_2    conda-forge
libsodium                 1.0.18               h27ca646_1    conda-forge
libtiff                   4.3.0                hc6122e1_1    conda-forge
libwebp-base              1.2.0                h27ca646_2    conda-forge
llvm-openmp               12.0.1               hf3c4609_0    conda-forge
locket                    0.2.0                      py_2    conda-forge
lz4-c                     1.9.3                h9f76cd9_0    conda-forge
markupsafe                2.0.1            py39h5161555_0    conda-forge
matplotlib-inline         0.1.2              pyhd8ed1ab_2    conda-forge
msgpack-python            1.0.2            py39h4d2d688_1    conda-forge
ncurses                   6.2                  h9aa5885_4    conda-forge
numpy                     1.21.0           py39h1f3b974_0    conda-forge
olefile                   0.46               pyh9f0ad1d_1    conda-forge
openjpeg                  2.4.0                h062765e_1    conda-forge
openssl                   1.1.1k               h27ca646_0    conda-forge
packaging                 21.0               pyhd8ed1ab_0    conda-forge
pandas                    1.3.0            py39h7f752ed_0    conda-forge
parso                     0.8.2              pyhd8ed1ab_0    conda-forge
partd                     1.2.0              pyhd8ed1ab_0    conda-forge
pexpect                   4.8.0              pyh9f0ad1d_2    conda-forge
pickleshare               0.7.5                   py_1003    conda-forge
pillow                    8.3.1            py39ha74c66e_0    conda-forge
pip                       21.1.3             pyhd8ed1ab_0    conda-forge
prompt-toolkit            3.0.19             pyha770c72_0    conda-forge
psutil                    5.8.0            py39h5161555_1    conda-forge
ptyprocess                0.7.0              pyhd3deb0d_0    conda-forge
pycparser                 2.20               pyh9f0ad1d_2    conda-forge
pygments                  2.9.0              pyhd8ed1ab_0    conda-forge
pyopenssl                 20.0.1             pyhd8ed1ab_0    conda-forge
pyparsing                 2.4.7              pyh9f0ad1d_0    conda-forge
pysocks                   1.7.1            py39h2804cbe_3    conda-forge
python                    3.9.6           h54d631c_1_cpython    conda-forge
python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
python_abi                3.9                      2_cp39    conda-forge
pytz                      2021.1             pyhd8ed1ab_0    conda-forge
pyyaml                    5.4.1            py39h46acfd9_0    conda-forge
pyzmq                     22.1.0           py39h02c6a76_0    conda-forge
readline                  8.1                  hedafd6a_0    conda-forge
requests                  2.26.0             pyhd8ed1ab_0    conda-forge
setuptools                49.6.0           py39h2804cbe_3    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
sortedcontainers          2.4.0              pyhd8ed1ab_0    conda-forge
sqlite                    3.36.0               h72a2b83_0    conda-forge
tblib                     1.7.0              pyhd8ed1ab_0    conda-forge
tk                        8.6.10               hf7e6567_1    conda-forge
toolz                     0.11.1                     py_0    conda-forge
tornado                   6.1              py39h5161555_1    conda-forge
tqdm                      4.61.2             pyhd8ed1ab_1    conda-forge
traitlets                 5.0.5                      py_0    conda-forge
typing_extensions         3.10.0.0           pyha770c72_0    conda-forge
tzdata                    2021a                he74cb21_1    conda-forge
urllib3                   1.26.6             pyhd8ed1ab_0    conda-forge
wcwidth                   0.2.5              pyh9f0ad1d_2    conda-forge
wheel                     0.36.2             pyhd3deb0d_0    conda-forge
xz                        5.2.5                h642e427_1    conda-forge
yaml                      0.2.5                h642e427_0    conda-forge
zeromq                    4.3.4                h9f76cd9_0    conda-forge
zict                      2.0.0                      py_0    conda-forge
zlib                      1.2.11            h31e879b_1009    conda-forge
zstd                      1.5.0                h861e0a7_0    conda-forge
```

- Dask version: 2021.7.0
- Python version: 3.9.6
- Operating System: mac m1
- Install method conda & mamba (tried both, same result)

**Comment by ericdill** [comment]
there's a folder in my git repo called `sparse/` 
![shame](https://user-images.githubusercontent.com/6223243/126039021-8bbf7ddd-4a60-4c5b-82b6-66b7d93768e7.gif)

**Comment by mrocklin** [comment]
+1 on the choice of gif :)

Good to see you back around these parts Eric
