### ISSUE TITLE
dd.to_hdf produces HDF5ExtError ( unable to lock file, errno = 11, error message = 'Resource temporarily unavailable') on local cluster

### ISSUE THREAD

**Issue by N4321D** [dask/dask#7926]
dask.dataframe (dd) produces a HDF5ExtError when running on local cluster.

some data (~100MB) is written to the file, so I suspect it is an parallel writing issue maybe? 

The script works if not using client

**Minimal example:**
```
import dask.dataframe as dd
import dask.array as da

# load dask client
from dask.distributed import Client
client = Client()
client

ddf = da.random.randint(0, 0xFFFF, (int(1e8), 10)).to_dask_dataframe(columns=[f"test {i}" for i in range (10)])

ddf.to_hdf("delme.h5", 
           key='/data*',
           complevel=5, 
           complib="blosc:lz4hc", 
)

```

**Output:**
```
---------------------------------------------------------------------------
HDF5ExtError                              Traceback (most recent call last)
<ipython-input-6-557a3a58ea58> in <module>
----> 1 ddf.to_hdf("delme.h5", 
      2            key='/data*',
      3            complevel=5,
      4            complib="blosc:lz4hc",
      5            mode='w'

~/anaconda3/lib/python3.8/site-packages/dask/dataframe/core.py in to_hdf(self, path_or_buf, key, mode, append, **kwargs)
   1464         from .io import to_hdf
   1465 
-> 1466         return to_hdf(self, path_or_buf, key, mode, append, **kwargs)
   1467 
   1468     def to_csv(self, filename, **kwargs):

~/anaconda3/lib/python3.8/site-packages/dask/dataframe/io/hdf.py in to_hdf(df, path, key, mode, append, scheduler, name_function, compute, lock, dask_kwargs, **kwargs)
    249 
    250     if compute:
--> 251         compute_as_if_collection(
    252             DataFrame, dsk, keys, scheduler=scheduler, **dask_kwargs
    253         )

~/anaconda3/lib/python3.8/site-packages/dask/base.py in compute_as_if_collection(cls, dsk, keys, scheduler, get, **kwargs)
    311     schedule = get_scheduler(scheduler=scheduler, cls=cls, get=get)
    312     dsk2 = optimization_function(cls)(ensure_dict(dsk), keys, **kwargs)
--> 313     return schedule(dsk2, keys, **kwargs)
    314 
    315 

~/anaconda3/lib/python3.8/site-packages/distributed/client.py in get(self, dsk, keys, workers, allow_other_workers, resources, sync, asynchronous, direct, retries, priority, fifo_timeout, actors, **kwargs)
   2702                     should_rejoin = False
   2703             try:
-> 2704                 results = self.gather(packed, asynchronous=asynchronous, direct=direct)
   2705             finally:
   2706                 for f in futures.values():

~/anaconda3/lib/python3.8/site-packages/distributed/client.py in gather(self, futures, errors, direct, asynchronous)
   2016             else:
   2017                 local_worker = None
-> 2018             return self.sync(
   2019                 self._gather,
   2020                 futures,

~/anaconda3/lib/python3.8/site-packages/distributed/client.py in sync(self, func, asynchronous, callback_timeout, *args, **kwargs)
    857             return future
    858         else:
--> 859             return sync(
    860                 self.loop, func, *args, callback_timeout=callback_timeout, **kwargs
    861             )

~/anaconda3/lib/python3.8/site-packages/distributed/utils.py in sync(loop, func, callback_timeout, *args, **kwargs)
    324     if error[0]:
    325         typ, exc, tb = error[0]
--> 326         raise exc.with_traceback(tb)
    327     else:
    328         return result[0]

~/anaconda3/lib/python3.8/site-packages/distributed/utils.py in f()
    307             if callback_timeout is not None:
    308                 future = asyncio.wait_for(future, callback_timeout)
--> 309             result[0] = yield future
    310         except Exception:
    311             error[0] = sys.exc_info()

~/anaconda3/lib/python3.8/site-packages/tornado/gen.py in run(self)
    760 
    761                     try:
--> 762                         value = future.result()
    763                     except Exception:
    764                         exc_info = sys.exc_info()

~/anaconda3/lib/python3.8/site-packages/distributed/client.py in _gather(self, futures, errors, direct, local_worker)
   1881                             exc = CancelledError(key)
   1882                         else:
-> 1883                             raise exception.with_traceback(traceback)
   1884                         raise exc
   1885                     if errors == "skip":

~/anaconda3/lib/python3.8/site-packages/dask/dataframe/io/hdf.py in _pd_to_hdf()
     25         lock.acquire()
     26     try:
---> 27         pd_to_hdf(*args, **kwargs)
     28     finally:
     29         if lock:

~/anaconda3/lib/python3.8/site-packages/pandas/core/generic.py in to_hdf()
   2698         from pandas.io import pytables
   2699 
-> 2700         pytables.to_hdf(
   2701             path_or_buf,
   2702             key,

~/anaconda3/lib/python3.8/site-packages/pandas/io/pytables.py in to_hdf()
    309     path_or_buf = stringify_path(path_or_buf)
    310     if isinstance(path_or_buf, str):
--> 311         with HDFStore(
    312             path_or_buf, mode=mode, complevel=complevel, complib=complib
    313         ) as store:

~/anaconda3/lib/python3.8/site-packages/pandas/io/pytables.py in __init__()
    589         self._fletcher32 = fletcher32
    590         self._filters = None
--> 591         self.open(mode=mode, **kwargs)
    592 
    593     def __fspath__(self):

~/anaconda3/lib/python3.8/site-packages/pandas/io/pytables.py in open()
    738             raise ValueError(msg)
    739 
--> 740         self._handle = tables.open_file(self._path, self._mode, **kwargs)
    741 
    742     def close(self):

~/anaconda3/lib/python3.8/site-packages/tables/file.py in open_file()
    313 
    314     # Finally, create the File instance, and return it
--> 315     return File(filename, mode, title, root_uep, filters, **kwargs)
    316 
    317 

~/anaconda3/lib/python3.8/site-packages/tables/file.py in __init__()
    776 
    777         # Now, it is time to initialize the File extension
--> 778         self._g_new(filename, mode, **params)
    779 
    780         # Check filters and set PyTables format version for new files.

tables/hdf5extension.pyx in tables.hdf5extension.File._g_new()

HDF5ExtError: HDF5 error back trace

  File "H5F.c", line 509, in H5Fopen
    unable to open file
  File "H5Fint.c", line 1400, in H5F__open
    unable to open file
  File "H5Fint.c", line 1615, in H5F_open
    unable to lock the file
  File "H5FD.c", line 1640, in H5FD_lock
    driver lock request failed
  File "H5FDsec2.c", line 941, in H5FD_sec2_lock
    unable to lock file, errno = 11, error message = 'Resource temporarily unavailable'

End of HDF5 error back trace

Unable to open/create file 'delme.h5'
```

**Environment**:

- Dask version: '2021.07.0'
- tables version: '3.6.1'
- Python version:   Python 3.8.2  (Ananconda)
- Operating System: Ubuntu 21.04
- Install method (conda, pip, source): conda

**Comment by jsignell** [comment]
Thanks for opening this @N4321D. @martindurant do you have any ideas about this one?

**Comment by martindurant** [comment]
There are *loads* of issues related to hdf5 writing across processes (e.g., https://github.com/dask/dask/issues/3074 and all the links therein). I can confirm that I also see the exception, even when explicitly providing a distributed lock. I ran a quick test and I can see that a lock is indeed making its way into `dask.dataframe.io.hdf._pd_to_hdf`: 
```python
def _pd_to_hdf(pd_to_hdf, lock, args, kwargs=None):
    """A wrapper function around pd_to_hdf that enables locking"""

    if lock:
        lock.acquire()
    try:
        print("#### LOCK: ", lock)
        pd_to_hdf(*args, **kwargs)
    finally:
        if lock:
            lock.release()

    return None
```
