### ISSUE TITLE
Cannot `set_index` with `string[pyarrow]` column

### ISSUE THREAD

**Issue by DahnJ** [dask/dask#8017]
It seems that `string[pyarrow]` does not yet support all operations. I haven't found an issue about it, so I'm posting this.

Possibly will result in an issue for PyArrrow, but since I encountered it using Dask, I decided to post here.

## Reproducible example

```python
import pandas as pd
import dask.dataframe as dd

df = pd.DataFrame({'col': ['a', 'b']})
df = df.astype({'col': 'string[pyarrow]'})
ddf = dd.from_pandas(df, npartitions=1)

ddf.set_index('col')
```

Results in

```python
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
~/miniconda3/lib/python3.9/site-packages/dask/dataframe/utils.py in raise_on_meta_error(funcname, udf)
    175     try:
--> 176         yield
    177     except Exception as e:

~/miniconda3/lib/python3.9/site-packages/dask/dataframe/core.py in _emulate(func, *args, **kwargs)
   5611     with raise_on_meta_error(funcname(func), udf=kwargs.pop("udf", False)):
-> 5612         return func(*_extract_meta(args, True), **_extract_meta(kwargs, True))
   5613 

~/miniconda3/lib/python3.9/site-packages/dask/utils.py in __call__(self, obj, *args, **kwargs)
    962     def __call__(self, obj, *args, **kwargs):
--> 963         return getattr(obj, self.method)(*args, **kwargs)
    964 

~/miniconda3/lib/python3.9/site-packages/pandas/core/generic.py in min(self, axis, skipna, level, numeric_only, **kwargs)
  10826         def min(self, axis=None, skipna=None, level=None, numeric_only=None, **kwargs):
> 10827             return NDFrame.min(self, axis, skipna, level, numeric_only, **kwargs)
  10828 

~/miniconda3/lib/python3.9/site-packages/pandas/core/generic.py in min(self, axis, skipna, level, numeric_only, **kwargs)
  10349     def min(self, axis=None, skipna=None, level=None, numeric_only=None, **kwargs):
> 10350         return self._stat_function(
  10351             "min", nanops.nanmin, axis, skipna, level, numeric_only, **kwargs

~/miniconda3/lib/python3.9/site-packages/pandas/core/generic.py in _stat_function(self, name, func, axis, skipna, level, numeric_only, **kwargs)
  10344             )
> 10345         return self._reduce(
  10346             func, name=name, axis=axis, skipna=skipna, numeric_only=numeric_only

~/miniconda3/lib/python3.9/site-packages/pandas/core/series.py in _reduce(self, op, name, axis, skipna, numeric_only, filter_type, **kwds)
   4381             # dispatch to ExtensionArray interface
-> 4382             return delegate._reduce(name, skipna=skipna, **kwds)
   4383 

~/miniconda3/lib/python3.9/site-packages/pandas/core/arrays/string_arrow.py in _reduce(self, name, skipna, **kwargs)
    378         if name in ["min", "max"]:
--> 379             return getattr(self, name)(skipna=skipna)
    380 

AttributeError: 'ArrowStringArray' object has no attribute 'min'

The above exception was the direct cause of the following exception:

ValueError                                Traceback (most recent call last)
<ipython-input-28-c124afaa310c> in <module>
----> 1 ddf.set_index('col')

~/miniconda3/lib/python3.9/site-packages/dask/dataframe/core.py in set_index(***failed resolving arguments***)
   4177             from .shuffle import set_index
   4178 
-> 4179             return set_index(
   4180                 self,
   4181                 other,

~/miniconda3/lib/python3.9/site-packages/dask/dataframe/shuffle.py in set_index(df, index, npartitions, shuffle, compute, drop, upsample, divisions, partition_size, **kwargs)
    160 
    161     if divisions is None:
--> 162         divisions, mins, maxes = _calculate_divisions(
    163             df, index2, repartition, npartitions, upsample, partition_size
    164         )

~/miniconda3/lib/python3.9/site-packages/dask/dataframe/shuffle.py in _calculate_divisions(df, partition_col, repartition, npartitions, upsample, partition_size)
     31     sizes = df.map_partitions(sizeof) if repartition else []
     32     divisions = partition_col._repartition_quantiles(npartitions, upsample=upsample)
---> 33     mins = partition_col.map_partitions(M.min)
     34     maxes = partition_col.map_partitions(M.max)
     35     divisions, sizes, mins, maxes = base.compute(divisions, sizes, mins, maxes)

~/miniconda3/lib/python3.9/site-packages/dask/dataframe/core.py in map_partitions(self, func, *args, **kwargs)
    689         None as the division.
    690         """
--> 691         return map_partitions(func, self, *args, **kwargs)
    692 
    693     @insert_meta_param_description(pad=12)

~/miniconda3/lib/python3.9/site-packages/dask/dataframe/core.py in map_partitions(func, meta, enforce_metadata, transform_divisions, *args, **kwargs)
   5666         # Use non-normalized kwargs here, as we want the real values (not
   5667         # delayed values)
-> 5668         meta = _emulate(func, *args, udf=True, **kwargs)
   5669     else:
   5670         meta = make_meta(meta, index=meta_index, parent_meta=parent_meta)

~/miniconda3/lib/python3.9/site-packages/dask/dataframe/core.py in _emulate(func, *args, **kwargs)
   5610     """
   5611     with raise_on_meta_error(funcname(func), udf=kwargs.pop("udf", False)):
-> 5612         return func(*_extract_meta(args, True), **_extract_meta(kwargs, True))
   5613 
   5614 

~/miniconda3/lib/python3.9/contextlib.py in __exit__(self, type, value, traceback)
    133                 value = type()
    134             try:
--> 135                 self.gen.throw(type, value, traceback)
    136             except StopIteration as exc:
    137                 # Suppress StopIteration *unless* it's the same exception that

~/miniconda3/lib/python3.9/site-packages/dask/dataframe/utils.py in raise_on_meta_error(funcname, udf)
    195         )
    196         msg = msg.format(" in `{0}`".format(funcname) if funcname else "", repr(e), tb)
--> 197         raise ValueError(msg) from e
    198 
    199 

ValueError: Metadata inference failed in `min`.

You have supplied a custom function and Dask is unable to 
determine the type of output that that function returns. 

To resolve this please provide a meta= keyword.
The docstring of the Dask function you ran should have more information.

Original error is below:
------------------------
AttributeError("'ArrowStringArray' object has no attribute 'min'")

Traceback:
---------
  File "/home/dahn/miniconda3/lib/python3.9/site-packages/dask/dataframe/utils.py", line 176, in raise_on_meta_error
    yield
  File "/home/dahn/miniconda3/lib/python3.9/site-packages/dask/dataframe/core.py", line 5612, in _emulate
    return func(*_extract_meta(args, True), **_extract_meta(kwargs, True))
  File "/home/dahn/miniconda3/lib/python3.9/site-packages/dask/utils.py", line 963, in __call__
    return getattr(obj, self.method)(*args, **kwargs)
  File "/home/dahn/miniconda3/lib/python3.9/site-packages/pandas/core/generic.py", line 10827, in min
    return NDFrame.min(self, axis, skipna, level, numeric_only, **kwargs)
  File "/home/dahn/miniconda3/lib/python3.9/site-packages/pandas/core/generic.py", line 10350, in min
    return self._stat_function(
  File "/home/dahn/miniconda3/lib/python3.9/site-packages/pandas/core/generic.py", line 10345, in _stat_function
    return self._reduce(
  File "/home/dahn/miniconda3/lib/python3.9/site-packages/pandas/core/series.py", line 4382, in _reduce
    return delegate._reduce(name, skipna=skipna, **kwds)
  File "/home/dahn/miniconda3/lib/python3.9/site-packages/pandas/core/arrays/string_arrow.py", line 379, in _reduce
    return getattr(self, name)(skipna=skipna)
```

**Environment**:

- Dask version: `2021.07.0`
- Pandas: `1.3.1`
- Pyarrow: `5.0.0`
- Python version: `3.9.5`
- Operating System: `Ubuntu 18.04.5 LTS`
- Install method (conda, pip, source): `conda`

**Comment by mrocklin** [comment]
This is reported upstream in 

- https://github.com/pandas-dev/pandas/issues/42597
- https://issues.apache.org/jira/browse/ARROW-13410

**Comment by jsignell** [comment]
Closing this as it's a purely upstream issue.
