### ISSUE TITLE
`da.percentile` of dask array with dask 2021.8.1 requires pandas

### ISSUE THREAD

**Issue by ericpre** [dask/dask#8078]
**What happened**:
Latest version of dask breaks hyperspy test suite: https://github.com/hyperspy/hyperspy/actions/runs/1156515097
It seems that this is due to the fact that `da.percentile` of dask array with dask 2021.8.1 requires pandas

**What you expected to happen**:
pandas is not required as dependency

**Minimal Complete Verifiable Example**:

```python
import dask.array as da

array = da.random.random(100)
da.percentile(array, [25, 57])
```
raises the following error:
```python

  File "/opt/miniconda3/envs/dask/lib/python3.8/site-packages/dask/dataframe/__init__.py", line 3, in <module>
    from . import backends, dispatch, rolling

  File "/opt/miniconda3/envs/dask/lib/python3.8/site-packages/dask/dataframe/backends.py", line 4, in <module>
    import pandas as pd

ModuleNotFoundError: No module named 'pandas'


The above exception was the direct cause of the following exception:

Traceback (most recent call last):

  File "/home/eric/Dev/hyperspy/untitled3.py", line 12, in <module>
    da.percentile(array, [25, 57])

  File "/opt/miniconda3/envs/dask/lib/python3.8/site-packages/dask/array/percentile.py", line 94, in percentile
    from dask.dataframe.dispatch import _percentile

  File "/opt/miniconda3/envs/dask/lib/python3.8/site-packages/dask/dataframe/__init__.py", line 60, in <module>
    raise ImportError(msg) from e

ImportError: Dask dataframe requirements are not installed.

Please either conda or pip install as follows:

  conda install dask                     # either conda install
  python -m pip install "dask[dataframe]" --upgrade  # or python -m pip install
```

**Anything else we need to know?**:
dask 2021.8.0 works fine without dask

**Environment**:

- Dask version: 2021.8.1
- Python version: 3.8
- Operating System: Fedora
- Install method (conda, pip, source): pip

**Comment by quasiben** [comment]
@galipremsagar I recall you submitting a PR to resolve this, did that go in?

**Comment by jrbourbeau** [comment]
Thank you for reporting @ericpre. @quasiben I thought https://github.com/dask/dask/pull/8055 was sufficient, but there was an indirect `pandas` import through the dispatches in `dask.dataframe.dispatch`. Also, see https://github.com/dask/dask/pull/8079
