### ISSUE TITLE
`git clone` issue in gpuCI build

### ISSUE THREAD

**Issue by jrbourbeau** [dask/dask#8154]
In a couple of PRs we've noticed gpuCI failing to clone the `dask` repo (see [this build](https://gpuci.gpuopenanalytics.com/job/dask/job/dask/job/prb/job/dask-prb/397/console) for an example)

```
15:37:20  > git fetch --tags --progress -- ssh://git@github.com/dask/dask.git +refs/heads/*:refs/remotes/origin/* # timeout=10

15:37:20 ERROR: Error cloning remote repo 'origin'

15:37:20 hudson.plugins.git.GitException: Command "git fetch --tags --progress -- ssh://git@github.com/dask/dask.git +refs/heads/*:refs/remotes/origin/*" returned status code 128:

15:37:20 stdout: 

15:37:20 stderr: git@github.com: Permission denied (publickey).

15:37:20 fatal: Could not read from remote repository.

15:37:20 

15:37:20 Please make sure you have the correct access rights

15:37:20 and the repository exists.

15:37:20 

15:37:20 	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:2639)

15:37:20 	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandWithCredentials(CliGitAPIImpl.java:2079)

15:37:20 	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.access$500(CliGitAPIImpl.java:84)

15:37:20 	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$1.execute(CliGitAPIImpl.java:601)

15:37:20 	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$2.execute(CliGitAPIImpl.java:830)

15:37:20 	at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler$GitCommandMasterToSlaveCallable.call(RemoteGitImpl.java:161)

15:37:20 	at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler$GitCommandMasterToSlaveCallable.call(RemoteGitImpl.java:154)

15:37:20 	at hudson.remoting.UserRequest.perform(UserRequest.java:211)

15:37:20 	at hudson.remoting.UserRequest.perform(UserRequest.java:54)

15:37:20 	at hudson.remoting.Request$2.run(Request.java:376)

15:37:20 	at hudson.remoting.InterceptingExecutorService.lambda$wrap$0(InterceptingExecutorService.java:78)

15:37:20 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)

15:37:20 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)

15:37:20 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)

15:37:20 	at java.lang.Thread.run(Thread.java:748)

15:37:20 	Suppressed: hudson.remoting.Channel$CallSiteStackTrace: Remote call to EC2 (aws-b) - runner-m5d2xl (i-0b6343379e50bf41c)

15:37:20 		at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1800)

15:37:20 		at hudson.remoting.UserRequest$ExceptionResponse.retrieve(UserRequest.java:356)

15:37:20 		at hudson.remoting.Channel.call(Channel.java:1001)

15:37:20 		at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler.execute(RemoteGitImpl.java:146)

15:37:20 		at sun.reflect.GeneratedMethodAccessor624.invoke(Unknown Source)

15:37:20 		at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

15:37:20 		at java.lang.reflect.Method.invoke(Method.java:498)

15:37:20 		at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler.invoke(RemoteGitImpl.java:132)

15:37:20 		at com.sun.proxy.$Proxy102.execute(Unknown Source)

15:37:20 		at hudson.plugins.git.GitSCM.retrieveChanges(GitSCM.java:1223)

15:37:20 		at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1301)

15:37:20 		at hudson.scm.SCM.checkout(SCM.java:505)

15:37:20 		at hudson.model.AbstractProject.checkout(AbstractProject.java:1204)

15:37:20 		at hudson.model.AbstractBuild$AbstractBuildExecution.defaultCheckout(AbstractBuild.java:636)

15:37:20 		at jenkins.scm.SCMCheckoutStrategy.checkout(SCMCheckoutStrategy.java:86)

15:37:20 		at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:508)

15:37:20 		at hudson.model.Run.execute(Run.java:1907)

15:37:20 		at hudson.matrix.MatrixBuild.run(MatrixBuild.java:323)

15:37:20 		at hudson.model.ResourceController.execute(ResourceController.java:97)

15:37:20 		at hudson.model.Executor.run(Executor.java:429)

15:37:20 ERROR: Error cloning remote repo 'origin'

15:37:20 Setting status of 03cc7f0a144aa0fb0473b47b7fbc99aa31181717 to FAILURE with url https://gpuci.gpuopenanalytics.com/job/dask/job/dask/job/prb/job/dask-prb/397/ and message: 'Build failure

15:37:20  '
```

cc @dask/gpu

**Comment by jakirkham** [comment]
cc @charlesbluca

**Comment by jakirkham** [comment]
Mentioned internally though my guess is most folks are already signed out for the day.

**Comment by ajschmidt8** [comment]
We just pushed some updates to CI that should address this. Please try re-running the tests again to see if it is resolved.

**Comment by jrbourbeau** [comment]
Re-running tests here https://github.com/dask/dask/pull/7719#issuecomment-920959574

**Comment by jakirkham** [comment]
Looks like [it worked]( https://gpuci.gpuopenanalytics.com/job/dask/job/dask/job/prb/job/dask-prb/CUDA_VER=11.2,LINUX_VER=ubuntu18.04,PYTHON_VER=3.8,RAPIDS_VER=21.10/lastBuild/consoleFull ) 😄

**Comment by ajschmidt8** [comment]
Cool. Feel free to close this issue. We added `ssh` credentials to the clone operations to prevent them from hitting GitHub's rate-limit for unauthenticated requests.

**Comment by jrbourbeau** [comment]
Thanks @ajschmidt8!
