### ISSUE TITLE
Possible bug: `dask.array.compute()` hanging with `multiprocessing.Pool`

### ISSUE THREAD

**Issue by valeriupredoi** [dask/dask#8218]
**What happened**:

Calling `compute()` twice in the same function hangs: first time one calls `compute()` in a straightforward manner, second time via `multiprocessing.Pool`; see example below:

- if I call `my_func(2)` then I go ahead and execute the mpi block (with the dask cluster commented out), the execution hangs (see stack trace below, after a `KeyboardInterrupt`);
- if I repeat the operation - call `my_func(2)` then execute just the dask cluster block (with the mpi block commented out) all goes through to finish (slowly, but it is expected);

Outline: I know we should be using the dask distributed client to operate multiprocessing jobs, but unfortunately, our actual code machinery makes use of `multiprocessing.Pool` at the moment and it will take a lot of changes to adapt it to use dask distributed; but we also want to use dask arrays, and finally, compute actual numerical values. Unfortunately, in a particular setup, we are faced with this odd combination of having to call a function twice - once explicitly on one thread and second time over in a `Pool`, and our whole machinery grinds to a halt. Any advice would be highly appreciated :beer: Very many thanks in advance! Cheers

Stack trace after a `KeyboardInterrupt`:
```
^CProcess ForkPoolWorker-2:
Process ForkPoolWorker-1:
Traceback (most recent call last):
  File "/home/valeriu/miniconda3/envs/esmvaltool-standard2/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/valeriu/miniconda3/envs/esmvaltool-standard2/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/valeriu/miniconda3/envs/esmvaltool-standard2/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/home/valeriu/miniconda3/envs/esmvaltool-standard2/lib/python3.9/multiprocessing/queues.py", line 366, in get
    res = self._reader.recv_bytes()
  File "/home/valeriu/miniconda3/envs/esmvaltool-standard2/lib/python3.9/multiprocessing/connection.py", line 221, in recv_bytes
    buf = self._recv_bytes(maxlength)
  File "/home/valeriu/miniconda3/envs/esmvaltool-standard2/lib/python3.9/multiprocessing/connection.py", line 419, in _recv_bytes
    buf = self._recv(4)
  File "/home/valeriu/miniconda3/envs/esmvaltool-standard2/lib/python3.9/multiprocessing/connection.py", line 384, in _recv
    chunk = read(handle, remaining)
KeyboardInterrupt
Traceback (most recent call last):
  File "/home/valeriu/dask_fail.py", line 28, in <module>
    main()
  File "/home/valeriu/dask_fail.py", line 19, in main
    x = pool.map(my_func, [2])
  File "/home/valeriu/miniconda3/envs/esmvaltool-standard2/lib/python3.9/multiprocessing/pool.py", line 364, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/home/valeriu/miniconda3/envs/esmvaltool-standard2/lib/python3.9/multiprocessing/pool.py", line 765, in get
Traceback (most recent call last):
  File "/home/valeriu/miniconda3/envs/esmvaltool-standard2/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/valeriu/miniconda3/envs/esmvaltool-standard2/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/valeriu/miniconda3/envs/esmvaltool-standard2/lib/python3.9/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/home/valeriu/miniconda3/envs/esmvaltool-standard2/lib/python3.9/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
  File "/home/valeriu/dask_fail.py", line 10, in my_func
    s = compute(a)
  File "/home/valeriu/miniconda3/envs/esmvaltool-standard2/lib/python3.9/site-packages/dask/base.py", line 570, in compute
    results = schedule(dsk, keys, **kwargs)
  File "/home/valeriu/miniconda3/envs/esmvaltool-standard2/lib/python3.9/site-packages/dask/threaded.py", line 79, in get
    results = get_async(
  File "/home/valeriu/miniconda3/envs/esmvaltool-standard2/lib/python3.9/site-packages/dask/local.py", line 506, in get_async
    for key, res_info, failed in queue_get(queue).result():
  File "/home/valeriu/miniconda3/envs/esmvaltool-standard2/lib/python3.9/site-packages/dask/local.py", line 134, in queue_get
    return q.get()
  File "/home/valeriu/miniconda3/envs/esmvaltool-standard2/lib/python3.9/queue.py", line 171, in get
    self.not_empty.wait()
  File "/home/valeriu/miniconda3/envs/esmvaltool-standard2/lib/python3.9/threading.py", line 312, in wait
    waiter.acquire()
KeyboardInterrupt
    self.wait(timeout)
  File "/home/valeriu/miniconda3/envs/esmvaltool-standard2/lib/python3.9/multiprocessing/pool.py", line 762, in wait
    self._event.wait(timeout)
  File "/home/valeriu/miniconda3/envs/esmvaltool-standard2/lib/python3.9/threading.py", line 574, in wait
    signaled = self._cond.wait(timeout)
  File "/home/valeriu/miniconda3/envs/esmvaltool-standard2/lib/python3.9/threading.py", line 312, in wait
    waiter.acquire()
KeyboardInterrupt
```

**What you expected to happen**:

**Minimal Complete Verifiable Example**:

```python
import dask.array as da
from dask import compute
from dask.distributed import Client
from multiprocessing import Pool


def my_func(x1):
    a = da.arange(4)
    print(a)
    s = compute(a)


def main():
    # call function like a peasant
    my_func(2)

    # mpi block
    pool = Pool(processes=2)
    x = pool.map(my_func, [2])

    # dask cluster block
    client = Client()
    x = client.map(my_func, [2])
    x = client.gather(x)


if __name__ == '__main__':
    main()
```

**Anything else we need to know?**:

**Environment**:

- Dask version:
```
dask                      2021.9.1           pyhd8ed1ab_0    conda-forge
dask-core                 2021.9.1           pyhd8ed1ab_0    conda-forge
```
- Python version: `3.9.7`
- Operating System:
```
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.7 LTS
Release:	16.04
Codename:	xenial
```
- Install method (conda, pip, source): `conda-forge` (see build hash above)

**Comment by jsignell** [comment]
I am probably missing something, but I am confused by what you are trying to achieve. Even using `client.map` it seems unusual to call compute within the function that you are trying to distribute. I just don't see what the value of that is. If you are using `Pool` already then why not just use `numpy.Array` and skip dask altogether?

**Comment by valeriupredoi** [comment]
@jsignell cheers muchly for getting back to me! That is just a toy example to show what the setup is within our stack - there is a process that needs to call a function that should `compute()` at the same time when another process is sending the same function to mpi via `Pool` - don't worry about fixing the toy example, in the actual setup things are way more complicated but it boils down to this basic chain of events. The question here is why isn't the function sent to mpi finishing its job (unlike the one that is sent via the dask distributed, that finishes fine) :beer:
