### ISSUE TITLE
Client() causes concurrent.futures._base.CancelledError 

### ISSUE THREAD

**Issue by cmp1** [dask/dask#8303]
**What happened**:
When I run the following code with client() and then call any method that invokes 'compute()', the process fails and each time I receive the above error. 

**Minimal Complete Verifiable Example**:

```python

import dask.dataframe as dd
import dask.distributed
import logging
import numpy as np

# import gdal
 
from geopy.distance import geodesic
from osgeo import gdal
from pathlib import Path
from skimage.graph import route_through_array


ABSOLUTE_CURRENT_DIR = Path(__file__).parent.absolute() # used to open local file
# loading current file
filpath = ABSOLUTE_CURRENT_DIR / "map.tif"
filepath_str = str(filpath.resolve().absolute())
 
#Transforming a raster map to array datatype.
raster = gdal.Open(filepath_str)
#raster = gdal.Open(Path("map.tif"))

#A raster consists of a matrix of cells (or pixels) organized into rows and columns (or a grid) where each cell contains a value representing information
band = raster.GetRasterBand(1)
 
# The world map in an array/df. 99999 ==> Land/white       1 ==> Water / Black
mapArray = band.ReadAsArray()

def get_logger(name):
    logger = logging.getLogger(name)
    logger.setLevel(logging.INFO)
    
    formatter = logging.Formatter('%(asctime)s - %(name)s - %(levelname)s - %(message)s')
    ch = logging.StreamHandler()
    ch.setFormatter(formatter)
    ch.setLevel(logging.INFO)
    logger.addHandler(ch) 
    return logger

#Calculate the geodesic distance starts from the first pair of points to the last.
def calculate_distance(lat_array=None,lon_array=None,lat_lon_pathIndices=None, horizontal_lat_lon_array = False):
    if not horizontal_lat_lon_array:
        lat_lon_pathIndices = np.array([lat_array,lon_array])

    distance = 0
    for i in range(0,(len(lat_lon_pathIndices[0])-1)):
        distance += geodesic((lat_lon_pathIndices[0,i], lat_lon_pathIndices[1,i]), (lat_lon_pathIndices[0,i+1], lat_lon_pathIndices[1,i+1])).miles*0.868976
    return distance

# The current distance function might have some issues when we use shorter interval data (hourly etc)
# the distance function may not indicate any distance covered 
# if the change in the longitude or latitude between the data points is less than 0.33 degrees.

def get_distance_paths_optim(row, delete_coordinates_on_land=False):                                     

    #Get geotransform information and declare some variables for later use
    geotransform = raster.GetGeoTransform()                                    #To obtain spatial references
    originX = geotransform[0]
    originY = geotransform[3] 
    pixelWidth = geotransform[1] 
    pixelHeight = geotransform[5]
    
    #transform the coordinates to the exact position in the array.
    def coord2pixelOffset(x,y):
        xOffset = int((x - originX)/pixelWidth)
        yOffset = int((y - originY)/pixelHeight)
        return xOffset,yOffset
    
    #create a path which travels through the cost map.
    def createPath(costSurfaceArray,startCoord,stopCoord, delete_coordinates_on_land=delete_coordinates_on_land):   
    
        # coordinates to array index
        startCoordX = startCoord[1]
        startCoordY = startCoord[0]
        startIndexX,startIndexY = coord2pixelOffset(startCoordX,startCoordY)
    
        stopCoordX = stopCoord[1]
        stopCoordY = stopCoord[0]
        stopIndexX,stopIndexY = coord2pixelOffset(stopCoordX,stopCoordY)
    
        # create path
        indices, weight = route_through_array(costSurfaceArray, (startIndexY, startIndexX), (stopIndexY, stopIndexX), geometric=True, fully_connected=True)
        indices = np.array(indices).T

        coordinates_on_land = costSurfaceArray[indices[0],indices[1]]>1
        number_of_coordinates_on_land = sum(coordinates_on_land)
        
        if number_of_coordinates_on_land != 0:
#             print(f"Between {startCoord} and {stopCoord}, there are {number_of_coordinates_on_land} path coordinates that are on land")
#             logger.info(f"Between {startCoord} and {stopCoord}, there are {number_of_coordinates_on_land} path coordinates that are on land")
            index_of_coordinates_on_land = np.where(coordinates_on_land)
        
            if delete_coordinates_on_land:
                indices = np.delete(indices, index_of_coordinates_on_land, axis=1)


        indices = indices.astype(float)
        indices[1] = indices[1]*pixelWidth + originX
        indices[0] = indices[0]*pixelHeight + originY
        return indices
    
    #Calculate the 
    def distanceCalculator(startCoord, stopCoord, delete_coordinates_on_land=delete_coordinates_on_land):
        # First row is lat data. Second row is lon data. First column is start point and last is end
        lat_lon_pathIndices = createPath(mapArray,startCoord,stopCoord, delete_coordinates_on_land=delete_coordinates_on_land)
                  
        distance = calculate_distance(lat_lon_pathIndices=lat_lon_pathIndices, horizontal_lat_lon_array= True)
#        print(distance)
        return distance, lat_lon_pathIndices
    
    start_lat_lon = [row[0], row[1]]
    end_lat_lon  = [row[2], row[3]]
    
    if np.isnan(start_lat_lon[0]) or np.isnan(start_lat_lon[1]) or np.isnan(end_lat_lon[0]) or np.isnan(end_lat_lon[1]):
        return np.nan
    
    distance, lat_lon_pathIndices = distanceCalculator(start_lat_lon, end_lat_lon)
    #return distance, lat_lon_pathIndices
    return distance

if __name__ == '__main__':

    client = dask.distributed.client._get_global_client() or dask.distributed.client.Client()
    
    ddf_original = dd.read_csv(r"C:\Users\CPrice2\test_5_rows.csv")
    
    ddf_original = ddf_original[["lat","lon","dest_lat","dest_lon"]]
    
    # Compute
    ddf_original['distance'] = ddf_original.apply(get_distance_paths_optim, meta=('float64'), axis=1)
    #ddf_original['distance'] = ddf_original.apply(get_distance_paths_optim, axis=1)
    
    # Convert to pandas
    df_original = ddf_original.compute()
    
    # Dump
    df_original.to_csv(r"C:\Users\CPrice2\test_with_comps_2.csv")


```

**Anything else we need to know?**:

Full Stack Trace

distributed.protocol.core - CRITICAL - Failed to Serialize
Traceback (most recent call last):
  File "C:\Users\CPrice2\Venv\ais\lib\site-packages\distributed\protocol\core.py", line 76, in dumps
    frames[0] = msgpack.dumps(msg, default=_encode_default, use_bin_type=True)
  File "C:\Users\CPrice2\Venv\ais\lib\site-packages\msgpack\__init__.py", line 35, in packb
    return Packer(**kwargs).pack(o)
  File "msgpack\_packer.pyx", line 292, in msgpack._cmsgpack.Packer.pack
  File "msgpack\_packer.pyx", line 298, in msgpack._cmsgpack.Packer.pack
  File "msgpack\_packer.pyx", line 295, in msgpack._cmsgpack.Packer.pack
  File "msgpack\_packer.pyx", line 264, in msgpack._cmsgpack.Packer._pack
  File "msgpack\_packer.pyx", line 231, in msgpack._cmsgpack.Packer._pack
  File "msgpack\_packer.pyx", line 231, in msgpack._cmsgpack.Packer._pack
  File "msgpack\_packer.pyx", line 264, in msgpack._cmsgpack.Packer._pack
  File "msgpack\_packer.pyx", line 231, in msgpack._cmsgpack.Packer._pack
  File "msgpack\_packer.pyx", line 231, in msgpack._cmsgpack.Packer._pack
  File "msgpack\_packer.pyx", line 285, in msgpack._cmsgpack.Packer._pack
  File "C:\Users\CPrice2\Venv\ais\lib\site-packages\distributed\protocol\core.py", line 62, in _encode_default
    size=frame_split_size,
  File "C:\Users\CPrice2\Venv\ais\lib\site-packages\distributed\protocol\serialize.py", line 426, in serialize_and_split
    header, frames = serialize(x, serializers, on_error, context)
  File "C:\Users\CPrice2\Venv\ais\lib\site-packages\distributed\protocol\serialize.py", line 258, in serialize
    iterate_collection=True,
  File "C:\Users\CPrice2\Venv\ais\lib\site-packages\distributed\protocol\serialize.py", line 350, in serialize
    raise TypeError(msg, str(x)[:10000])
TypeError: ('Could not serialize object of type SubgraphCallable.', 'subgraph_callable-8a851854-46b2-4eab-9c33-2aee24324f58')
distributed.comm.utils - ERROR - ('Could not serialize object of type SubgraphCallable.', 'subgraph_callable-8a851854-46b2-4eab-9c33-2aee24324f58')
Traceback (most recent call last):
  File "C:\Users\CPrice2\Venv\ais\lib\site-packages\distributed\comm\utils.py", line 33, in _to_frames
    return list(protocol.dumps(msg, **kwargs))
  File "C:\Users\CPrice2\Venv\ais\lib\site-packages\distributed\protocol\core.py", line 76, in dumps
    frames[0] = msgpack.dumps(msg, default=_encode_default, use_bin_type=True)
  File "C:\Users\CPrice2\Venv\ais\lib\site-packages\msgpack\__init__.py", line 35, in packb
    return Packer(**kwargs).pack(o)
  File "msgpack\_packer.pyx", line 292, in msgpack._cmsgpack.Packer.pack
  File "msgpack\_packer.pyx", line 298, in msgpack._cmsgpack.Packer.pack
  File "msgpack\_packer.pyx", line 295, in msgpack._cmsgpack.Packer.pack
  File "msgpack\_packer.pyx", line 264, in msgpack._cmsgpack.Packer._pack
  File "msgpack\_packer.pyx", line 231, in msgpack._cmsgpack.Packer._pack
  File "msgpack\_packer.pyx", line 231, in msgpack._cmsgpack.Packer._pack
  File "msgpack\_packer.pyx", line 264, in msgpack._cmsgpack.Packer._pack
  File "msgpack\_packer.pyx", line 231, in msgpack._cmsgpack.Packer._pack
  File "msgpack\_packer.pyx", line 231, in msgpack._cmsgpack.Packer._pack
  File "msgpack\_packer.pyx", line 285, in msgpack._cmsgpack.Packer._pack
  File "C:\Users\CPrice2\Venv\ais\lib\site-packages\distributed\protocol\core.py", line 62, in _encode_default
    size=frame_split_size,
  File "C:\Users\CPrice2\Venv\ais\lib\site-packages\distributed\protocol\serialize.py", line 426, in serialize_and_split
    header, frames = serialize(x, serializers, on_error, context)
  File "C:\Users\CPrice2\Venv\ais\lib\site-packages\distributed\protocol\serialize.py", line 258, in serialize
    iterate_collection=True,
  File "C:\Users\CPrice2\Venv\ais\lib\site-packages\distributed\protocol\serialize.py", line 350, in serialize
    raise TypeError(msg, str(x)[:10000])
TypeError: ('Could not serialize object of type SubgraphCallable.', 'subgraph_callable-8a851854-46b2-4eab-9c33-2aee24324f58')
distributed.batched - ERROR - Error in batched write
Traceback (most recent call last):
  File "C:\Users\CPrice2\Venv\ais\lib\site-packages\distributed\batched.py", line 94, in _background_send
    payload, serializers=self.serializers, on_error="raise"
  File "C:\Users\CPrice2\Venv\ais\lib\site-packages\tornado\gen.py", line 762, in run
    value = future.result()
  File "C:\Users\CPrice2\Venv\ais\lib\site-packages\distributed\comm\tcp.py", line 260, in write
    frame_split_size=self.max_shard_size,
  File "C:\Users\CPrice2\Venv\ais\lib\site-packages\distributed\comm\utils.py", line 50, in to_frames
    return _to_frames()
  File "C:\Users\CPrice2\Venv\ais\lib\site-packages\distributed\comm\utils.py", line 33, in _to_frames
    return list(protocol.dumps(msg, **kwargs))
  File "C:\Users\CPrice2\Venv\ais\lib\site-packages\distributed\protocol\core.py", line 76, in dumps
    frames[0] = msgpack.dumps(msg, default=_encode_default, use_bin_type=True)
  File "C:\Users\CPrice2\Venv\ais\lib\site-packages\msgpack\__init__.py", line 35, in packb
    return Packer(**kwargs).pack(o)
  File "msgpack\_packer.pyx", line 292, in msgpack._cmsgpack.Packer.pack
  File "msgpack\_packer.pyx", line 298, in msgpack._cmsgpack.Packer.pack
  File "msgpack\_packer.pyx", line 295, in msgpack._cmsgpack.Packer.pack
  File "msgpack\_packer.pyx", line 264, in msgpack._cmsgpack.Packer._pack
  File "msgpack\_packer.pyx", line 231, in msgpack._cmsgpack.Packer._pack
  File "msgpack\_packer.pyx", line 231, in msgpack._cmsgpack.Packer._pack
  File "msgpack\_packer.pyx", line 264, in msgpack._cmsgpack.Packer._pack
  File "msgpack\_packer.pyx", line 231, in msgpack._cmsgpack.Packer._pack
  File "msgpack\_packer.pyx", line 231, in msgpack._cmsgpack.Packer._pack
  File "msgpack\_packer.pyx", line 285, in msgpack._cmsgpack.Packer._pack
  File "C:\Users\CPrice2\Venv\ais\lib\site-packages\distributed\protocol\core.py", line 62, in _encode_default
    size=frame_split_size,
  File "C:\Users\CPrice2\Venv\ais\lib\site-packages\distributed\protocol\serialize.py", line 426, in serialize_and_split
    header, frames = serialize(x, serializers, on_error, context)
  File "C:\Users\CPrice2\Venv\ais\lib\site-packages\distributed\protocol\serialize.py", line 258, in serialize
    iterate_collection=True,
  File "C:\Users\CPrice2\Venv\ais\lib\site-packages\distributed\protocol\serialize.py", line 350, in serialize
    raise TypeError(msg, str(x)[:10000])
TypeError: ('Could not serialize object of type SubgraphCallable.', 'subgraph_callable-8a851854-46b2-4eab-9c33-2aee24324f58')
Traceback (most recent call last):
  File "C:\Users\CPrice2\.p2\pool\plugins\org.python.pydev.core_8.1.0.202012051215\pysrc\pydevd.py", line 3215, in <module>
    main()
  File "C:\Users\CPrice2\.p2\pool\plugins\org.python.pydev.core_8.1.0.202012051215\pysrc\pydevd.py", line 3208, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "C:\Users\CPrice2\.p2\pool\plugins\org.python.pydev.core_8.1.0.202012051215\pysrc\pydevd.py", line 2282, in run
    return self._exec(is_module, entry_point_fn, module_name, file, globals, locals)
  File "C:\Users\CPrice2\.p2\pool\plugins\org.python.pydev.core_8.1.0.202012051215\pysrc\pydevd.py", line 2306, in _exec
    runpy._run_module_as_main(module_name, alter_argv=False)
  File "C:\Users\CPrice2\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\CPrice2\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\CPrice2\Git\AIS\ais\distances\geodesic_distances.py", line 283, in <module>
    df_original = ddf_original.compute()
  File "C:\Users\CPrice2\Venv\ais\lib\site-packages\dask\base.py", line 288, in compute
    (result,) = compute(self, traverse=False, **kwargs)
  File "C:\Users\CPrice2\Venv\ais\lib\site-packages\dask\base.py", line 570, in compute
    results = schedule(dsk, keys, **kwargs)
  File "C:\Users\CPrice2\Venv\ais\lib\site-packages\distributed\client.py", line 2693, in get
    results = self.gather(packed, asynchronous=asynchronous, direct=direct)
  File "C:\Users\CPrice2\Venv\ais\lib\site-packages\distributed\client.py", line 1975, in gather
    asynchronous=asynchronous,
  File "C:\Users\CPrice2\Venv\ais\lib\site-packages\distributed\client.py", line 866, in sync
    self.loop, func, *args, callback_timeout=callback_timeout, **kwargs
  File "C:\Users\CPrice2\Venv\ais\lib\site-packages\distributed\utils.py", line 327, in sync
    raise exc.with_traceback(tb)
  File "C:\Users\CPrice2\Venv\ais\lib\site-packages\distributed\utils.py", line 310, in f
    result[0] = yield future
  File "C:\Users\CPrice2\Venv\ais\lib\site-packages\tornado\gen.py", line 762, in run
    value = future.result()
concurrent.futures._base.CancelledError

**Environment**:

- Dask version: 2021.10.0
- Python version: 3.7.9
- Operating System: Windows 10
- Install method (conda, pip, source): pip
[test_5_rows.csv](https://github.com/dask/dask/files/7427924/test_5_rows.csv)

**Comment by jsignell** [comment]
Seems like this might be similar to https://github.com/dask/distributed/issues/5504 maybe you can use the advice in that issue as a guide?

**Comment by pavithraes** [comment]
Closing as stalled, please feel free to re-open if your issue persists. :)
