### ISSUE TITLE
read_parquet from HDFS always raise error "list index out of range"

### ISSUE THREAD

**Issue by JinrongGuo1** [dask/dask#8320]
**What happened**:
can't read parquet from HDFS correctly, use cmd "hadoop fs -ls hdfs://ns/user/ana/conda/v1/input", I got the right file list.

```python
>>> import dask.dataframe as dd
>>> res=dd.read_parquet('hdfs://ns/user/ana/conda/v3/input', engine='pyarrow')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/export/App/training_platform/anaconda3/envs/9n-train/lib/python3.8/site-packages/dask/dataframe/io/parquet/core.py", line 307, in read_parquet
    read_metadata_result = engine.read_metadata(
  File "/export/App/training_platform/anaconda3/envs/9n-train/lib/python3.8/site-packages/dask/dataframe/io/parquet/arrow.py", line 507, in read_metadata
    ) = cls._gather_metadata(
  File "/export/App/training_platform/anaconda3/envs/9n-train/lib/python3.8/site-packages/dask/dataframe/io/parquet/arrow.py", line 1678, in _gather_metadata
    dataset, base, fns = _get_dataset_object(paths, fs, filters, dataset_kwargs)
  File "/export/App/training_platform/anaconda3/envs/9n-train/lib/python3.8/site-packages/dask/dataframe/io/parquet/arrow.py", line 1639, in _get_dataset_object
    allpaths, base, fns = _sort_and_analyze_paths(allpaths, fs)
  File "/export/App/training_platform/anaconda3/envs/9n-train/lib/python3.8/site-packages/dask/dataframe/io/parquet/utils.py", line 397, in _sort_and_analyze_paths
    base, fns = _analyze_paths(file_list, fs, root=root)
  File "/export/App/training_platform/anaconda3/envs/9n-train/lib/python3.8/site-packages/dask/dataframe/io/parquet/utils.py", line 463, in _analyze_paths
    basepath = path_parts_list[0][:-1]
IndexError: list index out of range
```

**Environment**:

- Dask version: 2021.04.0
- Python version: 3.8
- Operating System: centos
- Install method (conda, pip, source): conda

**Comment by jsignell** [comment]
This is going to be a hard one to debug without a reproducible example @JinrongGuo1. I certainly recommend updating to a more recent version of dask if possible. Also if you are able to get the output of `path_parts_list` (using pdb or a breakpoint) that would be helpful.

**Comment by jrbourbeau** [comment]
Closing due to lack of response. Feel free to re-open if you'd like to continue
