### ISSUE TITLE
Broken usage of capsys for inspecting logging output

### ISSUE THREAD

**Issue by amirkdv** [dask/dask#8622]
**What happened**:

1. We have one unit test that uses capsys to make assertions about emitted logs: [`dask/dataframe/io/tests/test_sql.py`](https://github.com/dask/dask/blob/2022.01.0/dask/dataframe/io/tests/test_sql.py#L410-L425)
1. Add a second unit test that does the same
1. You can't have more than one test using that pattern, the first one works and anything after does not
    - add new test after old test: old test passes, new test fails
    - skip old test: new test passes
    - add new test before old test: new test passes, old test fails

**What you expected to happen**:

We can have as many tests as we want making assertions about logs.

**Minimal Complete Verifiable Example**:

```python
# repro.py
import sqlalchemy as sa
from tempfile import NamedTemporaryFile

def do_something():
    with NamedTemporaryFile() as f:
        engine = sa.create_engine(f'sqlite:///{f.name}', echo=True)
        engine.execute("CREATE TABLE t (id INTEGER);")

def test1(capsys):
    do_something()
    out, err = capsys.readouterr()
    assert 'CREATE' in out

def test2(capsys):
    do_something()
    out, err = capsys.readouterr()
    assert 'CREATE' in out
```

Usage:
```sh
$ pytest -v repro.py -k test1 # passes
$ pytest -v repro.py -k test2 # passes
$ pytest -v repro.py # test1 passes, test2 fails
```

<details> <summary> inspected stderr of failed test case </summary>
<pre>
Traceback (most recent call last):
  File "/usr/lib/python3.8/logging/__init__.py", line 1088, in emit
    stream.write(msg + self.terminator)
ValueError: I/O operation on closed file.
Call stack:
  File "/dask/venv/bin/pytest", line 8, in <module>
    sys.exit(console_main())
  File "/dask/venv/lib/python3.8/site-packages/_pytest/config/__init__.py", line 185, in console_main
    code = main()
  File "/dask/venv/lib/python3.8/site-packages/_pytest/config/__init__.py", line 162, in main
    ret: Union[ExitCode, int] = config.hook.pytest_cmdline_main(
  File "/dask/venv/lib/python3.8/site-packages/pluggy/_hooks.py", line 265, in __call__
    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
  File "/dask/venv/lib/python3.8/site-packages/pluggy/_manager.py", line 80, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "/dask/venv/lib/python3.8/site-packages/pluggy/_callers.py", line 39, in _multicall
    res = hook_impl.function(*args)
  File "/dask/venv/lib/python3.8/site-packages/_pytest/main.py", line 316, in pytest_cmdline_main
    return wrap_session(config, _main)
  File "/dask/venv/lib/python3.8/site-packages/_pytest/main.py", line 269, in wrap_session
    session.exitstatus = doit(config, session) or 0
  File "/dask/venv/lib/python3.8/site-packages/_pytest/main.py", line 323, in _main
    config.hook.pytest_runtestloop(session=session)
  File "/dask/venv/lib/python3.8/site-packages/pluggy/_hooks.py", line 265, in __call__
    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
  File "/dask/venv/lib/python3.8/site-packages/pluggy/_manager.py", line 80, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "/dask/venv/lib/python3.8/site-packages/pluggy/_callers.py", line 39, in _multicall
    res = hook_impl.function(*args)
  File "/dask/venv/lib/python3.8/site-packages/_pytest/main.py", line 348, in pytest_runtestloop
    item.config.hook.pytest_runtest_protocol(item=item, nextitem=nextitem)
  File "/dask/venv/lib/python3.8/site-packages/pluggy/_hooks.py", line 265, in __call__
    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
  File "/dask/venv/lib/python3.8/site-packages/pluggy/_manager.py", line 80, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "/dask/venv/lib/python3.8/site-packages/pluggy/_callers.py", line 39, in _multicall
    res = hook_impl.function(*args)
  File "/dask/venv/lib/python3.8/site-packages/_pytest/runner.py", line 109, in pytest_runtest_protocol
    runtestprotocol(item, nextitem=nextitem)
  File "/dask/venv/lib/python3.8/site-packages/_pytest/runner.py", line 126, in runtestprotocol
    reports.append(call_and_report(item, "call", log))
  File "/dask/venv/lib/python3.8/site-packages/_pytest/runner.py", line 215, in call_and_report
    call = call_runtest_hook(item, when, **kwds)
  File "/dask/venv/lib/python3.8/site-packages/_pytest/runner.py", line 254, in call_runtest_hook
    return CallInfo.from_call(
  File "/dask/venv/lib/python3.8/site-packages/_pytest/runner.py", line 311, in from_call
    result: Optional[TResult] = func()
  File "/dask/venv/lib/python3.8/site-packages/_pytest/runner.py", line 255, in <lambda>
    lambda: ihook(item=item, **kwds), when=when, reraise=reraise
  File "/dask/venv/lib/python3.8/site-packages/pluggy/_hooks.py", line 265, in __call__
    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
  File "/dask/venv/lib/python3.8/site-packages/pluggy/_manager.py", line 80, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "/dask/venv/lib/python3.8/site-packages/pluggy/_callers.py", line 39, in _multicall
    res = hook_impl.function(*args)
  File "/dask/venv/lib/python3.8/site-packages/_pytest/runner.py", line 162, in pytest_runtest_call
    item.runtest()
  File "/dask/venv/lib/python3.8/site-packages/_pytest/python.py", line 1641, in runtest
    self.ihook.pytest_pyfunc_call(pyfuncitem=self)
  File "/dask/venv/lib/python3.8/site-packages/pluggy/_hooks.py", line 265, in __call__
    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
  File "/dask/venv/lib/python3.8/site-packages/pluggy/_manager.py", line 80, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "/dask/venv/lib/python3.8/site-packages/pluggy/_callers.py", line 39, in _multicall
    res = hook_impl.function(*args)
  File "/dask/venv/lib/python3.8/site-packages/_pytest/python.py", line 183, in pytest_pyfunc_call
    result = testfunction(**testargs)
  File "/dask/repro.py", line 23, in test2
    do_something()
  File "/dask/repro.py", line 13, in do_something
    engine.execute("CREATE TABLE t (id INTEGER);")
  File "<string>", line 2, in execute
  File "/dask/venv/lib/python3.8/site-packages/sqlalchemy/util/deprecations.py", line 401, in warned
    return fn(*args, **kwargs)
  File "/dask/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3146, in execute
    return connection.execute(statement, *multiparams, **params)
  File "/dask/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1274, in execute
    return self._exec_driver_sql(
  File "/dask/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1578, in _exec_driver_sql
    ret = self._execute_context(
  File "/dask/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1755, in _execute_context
    self._log_info(statement)
  File "/dask/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 136, in _log_info
    self.engine.logger.info(message, *arg, **kw)
  File "/dask/venv/lib/python3.8/site-packages/sqlalchemy/log.py", line 117, in info
    self.log(logging.INFO, msg, *args, **kwargs)
  File "/dask/venv/lib/python3.8/site-packages/sqlalchemy/log.py", line 163, in log
    self.logger._log(level, msg, args, **kwargs)
Message: 'CREATE TABLE t (id INTEGER);'
</pre>
</details>

**Anything else we need to know?**: the issue manifested in #8609.

**Environment**:

- SQLAlchemy verison: 1.4.31
- pytest version: 6.2.5
- Dask version: main
- Python version: 3.8.10
- Operating System: Ubuntu 20.04
- Install method (conda, pip, source): source

**Comment by scharlottej13** [comment]
Thank you @amirkdv for writing this up so clearly and including the reproducible example!

**Comment by amirkdv** [comment]
Right, good point! I think the funkiness happens after we exit the test case. On pytest's end, every fixture has a lifecycle [like this](https://github.com/pytest-dev/pytest/blob/325744ef8/src/_pytest/capture.py#L878-L891):
```python
def capsys(...):
    # ... fixture setup, runs before entering test case
    yield capture_fixture # fed into test function
    # ... fixture teardown, runs after test case has finished
```

I think it's the fixture teardown logic for capsys that messes with io streams in a way that breaks log handlers.

The way people seem to be working around this in `pytest-dev/pytest#5502` is to clear their registered log handlers during test teardown (which happens before pytest's teardown of fixtures used in a test, aye so confusing). This is fine if you're ok to ignore logging, but in our case here we're actually testing log output.

**Comment by juanchoflorez** [comment]
Have you tried using `capsys` as a module fixture, i.e. calling it once per module instead of once per test? To avoid `capsys` shutdown to interfere with the logger. AFAIK it should set a buffer for stderr and stdout that all the tests should use, WDYT?
