### ISSUE TITLE
`dask.array.from_zarr` causes FileNotFound errors on HDFS if zarr contains empty chunks

### ISSUE THREAD

**Issue by MaximLippeveld** [dask/dask#8927]
**What happened**:
I tried creating a Dask Array from a zarr array stored on Hadoop Distributed File System. The source file from which the zarr was created  contains chunks that are all zero. By default these chunks are not written to the zarr array on disk. `dask.array.from_zarr` apparently iterates over all chunks that should be present, and does not check if a chunk exists prior to loading it. This causes FileNotFound errors.

**What you expected to happen**:
`dask.array.from_zarr` should check if a chunk exists prior to loading it.

**Minimal Complete Verifiable Example**:
Set up an HDFS cluster. Write a zarr with missing chunks to it.
```python
z = dask.array.from_zarr("hdfs://hdfs-address:9000/data.zarr")
```

**Environment**:

- Dask version: 2022.01.1
- Python version: 3.9.7
- Operating System: Centos 7
- Install method (conda, pip, source): conda

**Comment by pavithraes** [comment]
@MaximLippeveld Thanks for opening this issue! Could you please confirm if `da.from_zarr` works as expected when the chunks do exist? Because I found #5758 which also throws a FileNotFound error, but for a different reason (packages need to be installed locally). Could you also share the full error traceback, and some details about your HDFS cluster for folks not familiar with it?

**Comment by MaximLippeveld** [comment]
Yes `da.from_zarr` works as expected if they exist.

The HDFS cluster is very basic. It contains one Namenode which keeps track of the files distributed over four Datanodes. Communication happens over a local network. There is no special configuration.

Here is the stack trace for one missing file:
```hdfsOpenFile(/data/45_000.zarr/6.44.13): FileSystem#open((Lorg/apache/hadoop/fs/Path;I)Lorg/apache/hadoop/fs/FSDataInputStream;) error:
RemoteException: File does not exist: /data/45_000.zarr/6.44.13
	at org.apache.hadoop.hdfs.server.namenode.INodeFile.valueOf(INodeFile.java:86)
	at org.apache.hadoop.hdfs.server.namenode.INodeFile.valueOf(INodeFile.java:76)
	at org.apache.hadoop.hdfs.server.namenode.FSDirStatAndListingOp.getBlockLocations(FSDirStatAndListingOp.java:156)
	at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.getBlockLocations(FSNamesystem.java:2071)
	at org.apache.hadoop.hdfs.server.namenode.NameNodeRpcServer.getBlockLocations(NameNodeRpcServer.java:773)
	at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolServerSideTranslatorPB.getBlockLocations(ClientNamenodeProtocolServerSideTranslatorPB.java:458)
	at org.apache.hadoop.hdfs.protocol.proto.ClientNamenodeProtocolProtos$ClientNamenodeProtocol$2.callBlockingMethod(ClientNamenodeProtocolProtos.java)
	at org.apache.hadoop.ipc.ProtobufRpcEngine2$Server$ProtoBufRpcInvoker.call(ProtobufRpcEngine2.java:600)
	at org.apache.hadoop.ipc.ProtobufRpcEngine2$Server$ProtoBufRpcInvoker.call(ProtobufRpcEngine2.java:568)
	at org.apache.hadoop.ipc.ProtobufRpcEngine2$Server$ProtoBufRpcInvoker.call(ProtobufRpcEngine2.java:552)
	at org.apache.hadoop.ipc.RPC$Server.call(RPC.java:1093)
	at org.apache.hadoop.ipc.Server$RpcCall.run(Server.java:1035)
	at org.apache.hadoop.ipc.Server$RpcCall.run(Server.java:963)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:422)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1878)
	at org.apache.hadoop.ipc.Server$Handler.run(Server.java:2966)
java.io.FileNotFoundException: File does not exist: /data/45_000.zarr/6.44.13
	at org.apache.hadoop.hdfs.server.namenode.INodeFile.valueOf(INodeFile.java:86)
	at org.apache.hadoop.hdfs.server.namenode.INodeFile.valueOf(INodeFile.java:76)
	at org.apache.hadoop.hdfs.server.namenode.FSDirStatAndListingOp.getBlockLocations(FSDirStatAndListingOp.java:156)
	at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.getBlockLocations(FSNamesystem.java:2071)
	at org.apache.hadoop.hdfs.server.namenode.NameNodeRpcServer.getBlockLocations(NameNodeRpcServer.java:773)
	at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolServerSideTranslatorPB.getBlockLocations(ClientNamenodeProtocolServerSideTranslatorPB.java:458)
	at org.apache.hadoop.hdfs.protocol.proto.ClientNamenodeProtocolProtos$ClientNamenodeProtocol$2.callBlockingMethod(ClientNamenodeProtocolProtos.java)
	at org.apache.hadoop.ipc.ProtobufRpcEngine2$Server$ProtoBufRpcInvoker.call(ProtobufRpcEngine2.java:600)
	at org.apache.hadoop.ipc.ProtobufRpcEngine2$Server$ProtoBufRpcInvoker.call(ProtobufRpcEngine2.java:568)
	at org.apache.hadoop.ipc.ProtobufRpcEngine2$Server$ProtoBufRpcInvoker.call(ProtobufRpcEngine2.java:552)
	at org.apache.hadoop.ipc.RPC$Server.call(RPC.java:1093)
	at org.apache.hadoop.ipc.Server$RpcCall.run(Server.java:1035)
	at org.apache.hadoop.ipc.Server$RpcCall.run(Server.java:963)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:422)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1878)
	at org.apache.hadoop.ipc.Server$Handler.run(Server.java:2966)

	at sun.reflect.GeneratedConstructorAccessor2.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.apache.hadoop.ipc.RemoteException.instantiateException(RemoteException.java:121)
	at org.apache.hadoop.ipc.RemoteException.unwrapRemoteException(RemoteException.java:88)
	at org.apache.hadoop.hdfs.DFSClient.callGetBlockLocations(DFSClient.java:894)
	at org.apache.hadoop.hdfs.DFSClient.getLocatedBlocks(DFSClient.java:881)
	at org.apache.hadoop.hdfs.DFSClient.getLocatedBlocks(DFSClient.java:870)
	at org.apache.hadoop.hdfs.DFSClient.open(DFSClient.java:1038)
	at org.apache.hadoop.hdfs.DistributedFileSystem$4.doCall(DistributedFileSystem.java:339)
	at org.apache.hadoop.hdfs.DistributedFileSystem$4.doCall(DistributedFileSystem.java:335)
	at org.apache.hadoop.fs.FileSystemLinkResolver.resolve(FileSystemLinkResolver.java:81)
	at org.apache.hadoop.hdfs.DistributedFileSystem.open(DistributedFileSystem.java:352)
Caused by: org.apache.hadoop.ipc.RemoteException(java.io.FileNotFoundException): File does not exist: /data/45_000.zarr/6.44.13
	at org.apache.hadoop.hdfs.server.namenode.INodeFile.valueOf(INodeFile.java:86)
	at org.apache.hadoop.hdfs.server.namenode.INodeFile.valueOf(INodeFile.java:76)
	at org.apache.hadoop.hdfs.server.namenode.FSDirStatAndListingOp.getBlockLocations(FSDirStatAndListingOp.java:156)
	at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.getBlockLocations(FSNamesystem.java:2071)
	at org.apache.hadoop.hdfs.server.namenode.NameNodeRpcServer.getBlockLocations(NameNodeRpcServer.java:773)
	at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolServerSideTranslatorPB.getBlockLocations(ClientNamenodeProtocolServerSideTranslatorPB.java:458)
	at org.apache.hadoop.hdfs.protocol.proto.ClientNamenodeProtocolProtos$ClientNamenodeProtocol$2.callBlockingMethod(ClientNamenodeProtocolProtos.java)
	at org.apache.hadoop.ipc.ProtobufRpcEngine2$Server$ProtoBufRpcInvoker.call(ProtobufRpcEngine2.java:600)
	at org.apache.hadoop.ipc.ProtobufRpcEngine2$Server$ProtoBufRpcInvoker.call(ProtobufRpcEngine2.java:568)
	at org.apache.hadoop.ipc.ProtobufRpcEngine2$Server$ProtoBufRpcInvoker.call(ProtobufRpcEngine2.java:552)
	at org.apache.hadoop.ipc.RPC$Server.call(RPC.java:1093)
	at org.apache.hadoop.ipc.Server$RpcCall.run(Server.java:1035)
	at org.apache.hadoop.ipc.Server$RpcCall.run(Server.java:963)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:422)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1878)
	at org.apache.hadoop.ipc.Server$Handler.run(Server.java:2966)

	at org.apache.hadoop.ipc.Client.getRpcResponse(Client.java:1573)
	at org.apache.hadoop.ipc.Client.call(Client.java:1519)
	at org.apache.hadoop.ipc.Client.call(Client.java:1416)
	at org.apache.hadoop.ipc.ProtobufRpcEngine2$Invoker.invoke(ProtobufRpcEngine2.java:242)
	at org.apache.hadoop.ipc.ProtobufRpcEngine2$Invoker.invoke(ProtobufRpcEngine2.java:129)
	at com.sun.proxy.$Proxy9.getBlockLocations(Unknown Source)
	at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolTranslatorPB.getBlockLocations(ClientNamenodeProtocolTranslatorPB.java:333)
	at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.hadoop.io.retry.RetryInvocationHandler.invokeMethod(RetryInvocationHandler.java:422)
	at org.apache.hadoop.io.retry.RetryInvocationHandler$Call.invokeMethod(RetryInvocationHandler.java:165)
	at org.apache.hadoop.io.retry.RetryInvocationHandler$Call.invoke(RetryInvocationHandler.java:157)
	at org.apache.hadoop.io.retry.RetryInvocationHandler$Call.invokeOnce(RetryInvocationHandler.java:95)
	at org.apache.hadoop.io.retry.RetryInvocationHandler.invoke(RetryInvocationHandler.java:359)
	at com.sun.proxy.$Proxy10.getBlockLocations(Unknown Source)
	at org.apache.hadoop.hdfs.DFSClient.callGetBlockLocations(DFSClient.java:892)
	... 7 more```

**Comment by pavithraes** [comment]
Thanks for the stack trace!

> The HDFS cluster is very basic. It contains one Namenode which keeps track of the files distributed over four Datanodes. Communication happens over a local network. There is no special configuration.

Could you please share some detail or steps for setting up an HDFS cluster locally, as well as, some sample data? I'm personally not familiar with this.

Some notes: The stack trace is coming from the HDFS server, which seems to be in Java. We're not sure where it's coming from -- could be `zarr.Array` or `da.from_array`:
https://github.com/dask/dask/blob/23408870a5b0a1db8e2abb96f97236b1db47c0f3/dask/array/core.py#L3400-L3416

@martindurant Do you have thoughts on this? Looks like we can improve the user experience here. :)

**Comment by martindurant** [comment]
Is there also a python stack trace of the FileNotFound? It makes sense that java should complain when we try to read the non-existent file - this is expected. The resulting FileNotFound should be turned by zarr into NaNs (or whatever the fill value is) for that chunk.

**Comment by MaximLippeveld** [comment]
[This Apache Hadoop documentation page](https://hadoop.apache.org/docs/stable/hadoop-project-dist/hadoop-common/SingleCluster.html) should explain everything to set up a local cluster. Using `zarr.creation.zeros` you can create an empty zarr array in which you can fill in a few values in one contingent location. If you then use `zarr.convenience.save` you can save the zarr with missing chunks. With `hdfs dfs -put <localsrc> <dest>` the zarr can be stored on the HDFS after which you can read it in with `da.from_zarr`. This will trigger the errors.

I cannot find a python stack trace linked to the Java FileNotFound exceptions. It seems that the python code is catching the missing file error and indeed filling in the appropriate fill value.

To be clear, `da.from_zarr` is able to correctly load the zarr array from disk. It is just causing a lot of these warnings while doing so.

**Comment by martindurant** [comment]
Oh, I see - so it's just the annoyance of the java error stuff appearing. That's probably configurable in your hadoop/log4j setup, but I don't know how. Maybe this doesn't happen with a production hadoop setup rather than the simplistic one-node version?

**Comment by MaximLippeveld** [comment]
No, it's actually happening in our production setup as well. It's definitely not a major bug, but I just felt it wasn't very clean that Dask (or zarr) was trying to access those files without first checking if they exist. So like @pavithraes said, it's more of a user experience thing.

**Comment by martindurant** [comment]
This is not something that dask controls: zarr specifically determines the non-existence of some file by trying to read it. Where fsspec is involved, there could be a pre-check to see if the file exists, but that would both complicate things and also slow down the process.

**Comment by pavithraes** [comment]
Thanks for the notes, `@martindurant`!

`@MaximLippeveld` Since it currently doesn't make sense for Dask to control the warning message, I'll go ahead and close this issue. Please feel free to re-open it if/when needed!
