### ISSUE TITLE
Sort Values Division By Zero

### ISSUE THREAD

**Issue by kevjumba** [dask/dask#8939]
**What happened**:

Calling dataframe.sort_values on a dataframe without npartitions specified causes ZeroDivisionError.

**What you expected to happen**:

No error

**Minimal Complete Verifiable Example**:

```python
# Put your MCVE code here
source_df = source_df.sort_values(by=event_timestamp_column)
```

**Anything else we need to know?**:
This only happens in the specific case where everything in the dataframe column to be sorted is equal, explained below.

Cause: Stack tracing down to `shuffle.py::rearrange_by_divisions` on line 146 of `dask/dataframe/shuffle.py`, the repartitioning removes all duplicates and doesn't actually check if removal of duplicates results in only 1 row in the dataframe => This is then used in `rearrange_column` as npartitions=0 because we set npartitions=len(division)-1 which causes the error. 

Linking this issue for reproducability: https://github.com/feast-dev/feast/issues/2399

**Environment**:

- Dask version: 2022.1.1
- Python version: 3.8.12
- Operating System: Mac OS M1
- Install method (conda, pip, source): pip

<details>
<summary>Cluster Dump State:</summary>

Traceback (most recent call last):
  File "example.py", line 31, in <module>
    fs.materialize(
  File "/Users/kevinzhang/tecton-ai/offline_store/feast/sdk/python/feast/usage.py", line 269, in wrapper
    return func(*args, **kwargs)
  File "/Users/kevinzhang/tecton-ai/offline_store/feast/sdk/python/feast/feature_store.py", line 1174, in materialize
    provider.materialize_single_feature_view(
  File "/Users/kevinzhang/tecton-ai/offline_store/feast/sdk/python/feast/infra/passthrough_provider.py", line 154, in materialize_single_feature_view
    table = offline_job.to_arrow()
  File "/Users/kevinzhang/tecton-ai/offline_store/feast/sdk/python/feast/infra/offline_stores/offline_store.py", line 121, in to_arrow
    return self._to_arrow_internal()
  File "/Users/kevinzhang/tecton-ai/offline_store/feast/sdk/python/feast/usage.py", line 280, in wrapper
    raise exc.with_traceback(traceback)
  File "/Users/kevinzhang/tecton-ai/offline_store/feast/sdk/python/feast/usage.py", line 269, in wrapper
    return func(*args, **kwargs)
  File "/Users/kevinzhang/tecton-ai/offline_store/feast/sdk/python/feast/infra/offline_stores/file.py", line 77, in _to_arrow_internal
    df = self.evaluation_function().compute()
  File "/Users/kevinzhang/tecton-ai/offline_store/feast/sdk/python/feast/infra/offline_stores/file.py", line 308, in evaluate_offline_job
    source_df = source_df.sort_values(by=event_timestamp_column, npartitions=5)
  File "/Users/kevinzhang/.pyenv/versions/feast_env/lib/python3.8/site-packages/dask/dataframe/core.py", line 4387, in sort_values
    return sort_values(
  File "/Users/kevinzhang/.pyenv/versions/feast_env/lib/python3.8/site-packages/dask/dataframe/shuffle.py", line 149, in sort_values
    df = rearrange_by_divisions(
  File "/Users/kevinzhang/.pyenv/versions/feast_env/lib/python3.8/site-packages/dask/dataframe/shuffle.py", line 456, in rearrange_by_divisions
    df3 = rearrange_by_column(
  File "/Users/kevinzhang/.pyenv/versions/feast_env/lib/python3.8/site-packages/dask/dataframe/shuffle.py", line 482, in rearrange_by_column
    df = df.repartition(npartitions=npartitions)
  File "/Users/kevinzhang/.pyenv/versions/feast_env/lib/python3.8/site-packages/dask/dataframe/core.py", line 1319, in repartition
    return repartition_npartitions(self, npartitions)
  File "/Users/kevinzhang/.pyenv/versions/feast_env/lib/python3.8/site-packages/dask/dataframe/core.py", line 6858, in repartition_npartitions
    npartitions_ratio = df.npartitions / npartitions
ZeroDivisionError: division by zero

</details>

**Comment by pavithraes** [comment]
@kevjumba Thanks for opening an issue! I can reproduce it on, and it does look like a bug.

Here's a reproducer for future reference:

```python
import pandas as pd
import dask.dataframe as dd

df = pd.DataFrame({
    'x': [5] * 10,
    'y': range(10)
})

ddf = dd.from_pandas(df, npartitions=2)

ddf.sort_values(by='x').compute() # ZeroDivisionError

ddf.sort_values(by='x', npartitions=2).compute() # ZeroDivisionError
```

**Comment by pavithraes** [comment]
@kevjumba Thanks for opening an issue! I can reproduce this on dask 2022.3.0, but it works fine on dask-2022.4.0. :)

Here's a reproducer for future reference:

```python
import pandas as pd
import dask.dataframe as dd

df = pd.DataFrame({
    'x': [5] * 10,
    'y': range(10)
})

ddf = dd.from_pandas(df, npartitions=2)

ddf.sort_values(by='x').compute()

ddf.sort_values(by='x', npartitions=2).compute()
```

**Comment by jsignell** [comment]
I'm going to close this for now, but please reopen @kevjumba if you are still seeing this on the latest releases of dask

**Comment by Cognitus-Stuti** [comment]
This is still an issue

**Comment by phofl** [comment]
this works on main, can you add more information?
