### ISSUE TITLE
Save and read database for dusk dataframe

### ISSUE THREAD

**Issue by PROehidna** [dask/dask#8943]
### Discussed in https://github.com/dask/dask/discussions/8936

<div type='discussions-op-text'>

<sup>Originally posted by **PROehidna** April 14, 2022</sup>
The program takes some .csv database, performs computational manipulations with them, and then saves the resulting database using the function `df.to_csv(filename, index=False, mode='a', compression="gzip")`
When reading back the uploaded file in Python, the column types that the dataframe had in the loop should be preserved.
How can I read a large file in one dataframe?
I do this using the following functions:
```
df = dd.read_csv("./genfiles/13_Apr_2022_17_18_04.gz")
    df1 = df.compute()
    df2 = (df['VAL_RUB'].sum()).compute() # Пробуем просуммировать столбец
    df_len = len(df)
    print(df.head(10))
    print("stop")
```
But the program gives an error
```
Traceback (most recent call last):
  File "c:/Users/proeh/Downloads/tt/repo/main_programm.py", line 254, in <module>
    df = dd.read_csv("./genfiles/13_Apr_2022_17_18_04.gz")
  File "C:\Users\proeh\AppData\Local\Programs\Python\Python35\lib\site-packages\dask\dataframe\io\csv.py", line 578, in read
    **kwargs
  File "C:\Users\proeh\AppData\Local\Programs\Python\Python35\lib\site-packages\dask\dataframe\io\csv.py", line 444, in read_pandas  
    head = reader(BytesIO(b_sample), **kwargs)
  File "C:\Users\proeh\AppData\Local\Programs\Python\Python35\lib\site-packages\pandas\io\parsers.py", line 702, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "C:\Users\proeh\AppData\Local\Programs\Python\Python35\lib\site-packages\pandas\io\parsers.py", line 429, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "C:\Users\proeh\AppData\Local\Programs\Python\Python35\lib\site-packages\pandas\io\parsers.py", line 895, in __init__
    self._make_engine(self.engine)
  File "C:\Users\proeh\AppData\Local\Programs\Python\Python35\lib\site-packages\pandas\io\parsers.py", line 1122, in _make_engine    
    self._engine = CParserWrapper(self.f, **self.options)
  File "C:\Users\proeh\AppData\Local\Programs\Python\Python35\lib\site-packages\pandas\io\parsers.py", line 1853, in __init__        
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas\_libs\parsers.pyx", line 542, in pandas._libs.parsers.TextReader.__cinit__
  File "pandas\_libs\parsers.pyx", line 782, in pandas._libs.parsers.TextReader._get_header
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
```
Perhaps the problem is due to saving data, but the main thing is that the data can then be read and enjoy all the benefits of dataframes with a large amount of data (about a million records)</div>

**Comment by pavithraes** [comment]
@PROehidna Thanks for opening this issue! Based on the traceback, I think you need to pass the compression type in `read_csv`:

```
df = dd.read_csv("/genfiles/13_Apr_2022_17_18_04.gz", compression='gzip')
```

If that doesn't work, can you please confirm if you can read (maybe a subset of the data if it's too large) using pandas `read_csv`?

**Comment by pavithraes** [comment]
@PROehidna Just checking in, were you able to resolve this using the above suggestion?

**Comment by pavithraes** [comment]
@PROehidna If you're getting the same error using pandas' `read_csv`, the issue might be in the file itself. I'd suggest trying to unzip the file locally to make sure the contents are as expected? I'd also encourage you to share this on StackOverflow -- where a broader community can help diagnose what's going on. :)

Unfortunately, we won't be able to help you from the Dask side here, so I'll go ahead and close this issue. Feel free to re-open it if needed!
