### ISSUE TITLE
KeyError on Cache (race condition)

### ISSUE THREAD

**Issue by hcarvalhoalves** [dask/dask#896]
I'm setting up cache as in the documentation with:
```
from dask.cache import Cache
cache = Cache(2e9)
cache.register()
```

On `compute()`, eventually I get an unhandled KeyError in caching logic:

```
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-2-decf9890590b> in <module>()
----> 1 model = build.build_all(num_workers=5)

/Users/henriquealves/Code/nu/lusa-model/src/lusa/build.pyc in build_all(**kwargs)
     26     cache.register()
     27
---> 28     return build_model(score_time_col='score_time', mordor=mordor, **kwargs)

/Users/henriquealves/Code/nu/lusa-model/src/lusa/build.pyc in build_model(score_time_col, mordor, **kwargs)
      5
      6 def build_model(score_time_col, mordor, **kwargs):
----> 7     return dask_cached.DaskRunner(**kwargs).run(train.full_pipeline(mordor, score_time_col))
      8
      9

/Users/henriquealves/anaconda/envs/lusa/lib/python2.7/site-packages/common_models/dask_cached.pyc in run(self, obj, prev)
     44         result = self.build(obj, prev)
     45         with dask.set_options(get=self.get_function):
---> 46             return result.compute(**self.dask_options)

/Users/henriquealves/anaconda/envs/lusa/lib/python2.7/site-packages/dask/base.pyc in compute(self, **kwargs)
     32
     33     def compute(self, **kwargs):
---> 34         return compute(self, **kwargs)[0]
     35
     36     @classmethod

/Users/henriquealves/anaconda/envs/lusa/lib/python2.7/site-packages/dask/base.pyc in compute(*args, **kwargs)
    100                 for opt, val in groups.items()])
    101     keys = [arg._keys() for arg in args]
--> 102     results = get(dsk, keys, **kwargs)
    103     return tuple(a._finalize(a, r) for a, r in zip(args, results))
    104

/Users/henriquealves/anaconda/envs/lusa/lib/python2.7/site-packages/dask/threaded.pyc in get(dsk, result, cache, num_workers, **kwargs)
     55     results = get_async(pool.apply_async, len(pool._pool), dsk, result,
     56                         cache=cache, queue=queue, get_id=_thread_get_id,
---> 57                         **kwargs)
     58
     59     return results

/Users/henriquealves/anaconda/envs/lusa/lib/python2.7/site-packages/dask/async.pyc in get_async(apply_async, num_workers, dsk, result, cache, queue, get_id, raise_on_exception, rerun_exceptions_locally, callbacks, **kwargs)
    485         finish_task(dsk, key, state, results, keyorder.get)
    486         for f in posttask_cbs:
--> 487             f(key, res, dsk, state, worker_id)
    488         while state['ready'] and len(state['running']) < num_workers:
    489             fire_task()

/Users/henriquealves/anaconda/envs/lusa/lib/python2.7/site-packages/dask/cache.pyc in _posttask(self, key, value, dsk, state, id)
     47
     48     def _posttask(self, key, value, dsk, state, id):
---> 49         duration = default_timer() - self.starttimes[key]
     50         deps = state['dependencies'][key]
     51         if deps:

KeyError: '_f-_4'
```

I have "two levels" of lazy computations with `do` decorator (a decorated fn calls other decorated fns internally, realizing the intermediate values), maybe this is the source of the problem. I've found hard to reproduce with a synthetic example.

Anyway, looks like a race condition due to mutable cache object here https://github.com/blaze/dask/blob/master/dask/cache.py#L37.

Can I specify separate cache objects per-compute, instead of having one thread-unsafe global?

**Comment by mrocklin** [comment]
Yes, you can use `get(dsk, keys, callbacks=[cache])` or `compute(..., callbacks=[cache])`

Generally its best to combine all of your computations into one graph and compute from there if possible.

**Comment by hcarvalhoalves** [comment]
The callbacks argument for `compute()` seem to expect something different:

```
>>> import dask
>>> from dask.cache import Cache
>>> cache = Cache(2e9)
>>> @dask.do
... def f(x):
...    return x + 'bar'
...
>>> f('foo')
Value('f-_1')
>>> f('foo').compute(callbacks=[cache])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/henriquealves/anaconda/envs/lusa/lib/python2.7/site-packages/dask/base.py", line 34, in compute
    return compute(self, **kwargs)[0]
  File "/Users/henriquealves/anaconda/envs/lusa/lib/python2.7/site-packages/dask/base.py", line 102, in compute
    results = get(dsk, keys, **kwargs)
  File "/Users/henriquealves/anaconda/envs/lusa/lib/python2.7/site-packages/dask/threaded.py", line 57, in get
    **kwargs)
  File "/Users/henriquealves/anaconda/envs/lusa/lib/python2.7/site-packages/dask/async.py", line 423, in get_async
    start_cbs, pretask_cbs, posttask_cbs, finish_cbs = unpack_callbacks(callbacks)
  File "/Users/henriquealves/anaconda/envs/lusa/lib/python2.7/site-packages/dask/callbacks.py", line 75, in unpack_callbacks
    return [[i for i in f if i] for f in zip(*cbs)]
TypeError: zip argument #1 must support iteration
```

**Comment by mrocklin** [comment]
Oh, my apologies, try `compute(callbacks=[cache._callback])` 

cc-ing @jcrist who knows more about this part of dask than I do.

**Comment by jcrist** [comment]
Matt's right, it should be `compute(callbacks=[cache._callback])`. Note that nested scheduler calls are frowned upon, and might lead to odd behavior. If possible, it'd be better to restructure your code to have the inner functions return `Value` objects, which can then be merged into the outer graph.

**Comment by hcarvalhoalves** [comment]
Works.

Yes, I understand I'm doing something unorthodox, but I'm using dask as a backend for my already existent data pipeline library so I can't control nesting.

Might want to think at those global callbacks though, the way it works it's hard to make thread-safe. I'm having similar problems with the diagnostic callbacks now.

**Comment by mrocklin** [comment]
This immediate issue seems to be resolved. 

If you plan to continue nesting then you might want to try the [distributed scheduler](http://distributed.readthedocs.org) (which works fine on a single machine too) which will handle this far more reliably.
