### ISSUE TITLE
Unable to install nightly `dask` conda package

### ISSUE THREAD

**Issue by jrbourbeau** [dask/dask#8984]
When I attempt to install the nightly `dask` package from the `dask/label/dev` conda channel with

```
 conda create -n dask-dev -c dask/label/dev dask
```

I get

```
CondaHTTPError: HTTP 404 NOT FOUND for url <https://conda.anaconda.org/dask/label/dev/noarch/dask-core-2022.04.2a220426-py_g23408870a_20.tar.bz2>
Elapsed: 00:00.142452
CF-RAY: 7022325708d326cb-MSP

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.
```

(full output is below). Are other folks experiencing something similar? cc @charlesbluca @jakirkham 

<details>
<summary>Details:</summary>

```
❯ conda create -n dask-dev -c dask/label/dev dask
WARNING: A conda environment already exists at '/Users/james/mambaforge/envs/dask-dev'
Remove existing environment (y/[n])? y

Collecting package metadata (current_repodata.json): done
Solving environment: done


==> WARNING: A newer version of conda exists. <==
  current version: 4.10.3
  latest version: 4.12.0

Please update conda by running

    $ conda update -n base conda



## Package Plan ##

  environment location: /Users/james/mambaforge/envs/dask-dev

  added / updated specs:
    - dask


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    bokeh-2.4.2                |  py310h2ec42d9_1        13.7 MB  conda-forge
    dask-2022.04.2a220426      |  py_g84cbb099_41           5 KB  dask/label/dev
    dask-core-2022.04.2a220426 | py_g23408870a_20         815 KB  dask/label/dev
    distributed-2022.04.2a220426|  py_g84cbb099_41         714 KB  dask/label/dev
    numpy-1.22.3               |  py310hb608527_2         6.4 MB  conda-forge
    pandas-1.4.2               |  py310h514ec25_1        12.1 MB  conda-forge
    pillow-9.1.0               |  py310h382dc3b_2        45.1 MB  conda-forge
    ------------------------------------------------------------
                                           Total:        78.8 MB

The following NEW packages will be INSTALLED:

  bokeh              conda-forge/osx-64::bokeh-2.4.2-py310h2ec42d9_1
  brotlipy           conda-forge/osx-64::brotlipy-0.7.0-py310h1961e1f_1004
  bzip2              conda-forge/osx-64::bzip2-1.0.8-h0d85af4_4
  ca-certificates    conda-forge/osx-64::ca-certificates-2021.10.8-h033912b_0
  certifi            conda-forge/osx-64::certifi-2021.10.8-py310h2ec42d9_2
  cffi               conda-forge/osx-64::cffi-1.15.0-py310hcc37b68_0
  click              conda-forge/osx-64::click-8.1.2-py310h2ec42d9_0
  cloudpickle        conda-forge/noarch::cloudpickle-2.0.0-pyhd8ed1ab_0
  cryptography       conda-forge/osx-64::cryptography-36.0.2-py310hd6fa1ae_1
  cytoolz            conda-forge/osx-64::cytoolz-0.11.2-py310h1961e1f_2
  dask               dask/label/dev/noarch::dask-2022.04.2a220426-py_g84cbb099_41
  dask-core          dask/label/dev/noarch::dask-core-2022.04.2a220426-py_g23408870a_20
  distributed        dask/label/dev/noarch::distributed-2022.04.2a220426-py_g84cbb099_41
  freetype           conda-forge/osx-64::freetype-2.10.4-h4cff582_1
  fsspec             conda-forge/noarch::fsspec-2022.3.0-pyhd8ed1ab_0
  giflib             conda-forge/osx-64::giflib-5.2.1-hbcb3906_2
  heapdict           conda-forge/noarch::heapdict-1.0.1-py_0
  idna               conda-forge/noarch::idna-3.3-pyhd8ed1ab_0
  jbig               conda-forge/osx-64::jbig-2.1-h0d85af4_2003
  jinja2             conda-forge/noarch::jinja2-3.1.1-pyhd8ed1ab_0
  jpeg               conda-forge/osx-64::jpeg-9e-h5eb16cf_1
  lcms2              conda-forge/osx-64::lcms2-2.12-h577c468_0
  lerc               conda-forge/osx-64::lerc-3.0-he49afe7_0
  libblas            conda-forge/osx-64::libblas-3.9.0-14_osx64_openblas
  libcblas           conda-forge/osx-64::libcblas-3.9.0-14_osx64_openblas
  libcxx             conda-forge/osx-64::libcxx-13.0.1-hc203e6f_0
  libdeflate         conda-forge/osx-64::libdeflate-1.10-h0d85af4_0
  libffi             conda-forge/osx-64::libffi-3.4.2-h0d85af4_5
  libgfortran        conda-forge/osx-64::libgfortran-5.0.0-9_3_0_h6c81a4c_23
  libgfortran5       conda-forge/osx-64::libgfortran5-9.3.0-h6c81a4c_23
  liblapack          conda-forge/osx-64::liblapack-3.9.0-14_osx64_openblas
  libopenblas        conda-forge/osx-64::libopenblas-0.3.20-openmp_hb3cd9ec_0
  libpng             conda-forge/osx-64::libpng-1.6.37-h7cec526_2
  libtiff            conda-forge/osx-64::libtiff-4.3.0-h17f2ce3_3
  libwebp            conda-forge/osx-64::libwebp-1.2.2-h28dabe5_0
  libwebp-base       conda-forge/osx-64::libwebp-base-1.2.2-h0d85af4_1
  libxcb             conda-forge/osx-64::libxcb-1.13-h0d85af4_1004
  libzlib            conda-forge/osx-64::libzlib-1.2.11-h6c3fc93_1014
  llvm-openmp        conda-forge/osx-64::llvm-openmp-13.0.1-hcb1a161_1
  locket             conda-forge/noarch::locket-1.0.0-pyhd8ed1ab_0
  lz4-c              conda-forge/osx-64::lz4-c-1.9.3-he49afe7_1
  markupsafe         conda-forge/osx-64::markupsafe-2.1.1-py310h1961e1f_1
  msgpack-python     conda-forge/osx-64::msgpack-python-1.0.3-py310h6be76da_1
  ncurses            conda-forge/osx-64::ncurses-6.3-h96cf925_1
  numpy              conda-forge/osx-64::numpy-1.22.3-py310hb608527_2
  openjpeg           conda-forge/osx-64::openjpeg-2.4.0-h6e7aa92_1
  openssl            conda-forge/osx-64::openssl-1.1.1n-h6c3fc93_0
  packaging          conda-forge/noarch::packaging-21.3-pyhd8ed1ab_0
  pandas             conda-forge/osx-64::pandas-1.4.2-py310h514ec25_1
  partd              conda-forge/noarch::partd-1.2.0-pyhd8ed1ab_0
  pillow             conda-forge/osx-64::pillow-9.1.0-py310h382dc3b_2
  pip                conda-forge/noarch::pip-22.0.4-pyhd8ed1ab_0
  psutil             conda-forge/osx-64::psutil-5.9.0-py310h1961e1f_1
  pthread-stubs      conda-forge/osx-64::pthread-stubs-0.4-hc929b4f_1001
  pycparser          conda-forge/noarch::pycparser-2.21-pyhd8ed1ab_0
  pyopenssl          conda-forge/noarch::pyopenssl-22.0.0-pyhd8ed1ab_0
  pyparsing          conda-forge/noarch::pyparsing-3.0.8-pyhd8ed1ab_0
  pysocks            conda-forge/osx-64::pysocks-1.7.1-py310h2ec42d9_5
  python             conda-forge/osx-64::python-3.10.4-h8b4d769_0_cpython
  python-dateutil    conda-forge/noarch::python-dateutil-2.8.2-pyhd8ed1ab_0
  python_abi         conda-forge/osx-64::python_abi-3.10-2_cp310
  pytz               conda-forge/noarch::pytz-2022.1-pyhd8ed1ab_0
  pyyaml             conda-forge/osx-64::pyyaml-6.0-py310h1961e1f_4
  readline           conda-forge/osx-64::readline-8.1-h05e3726_0
  setuptools         conda-forge/osx-64::setuptools-62.1.0-py310h2ec42d9_0
  six                conda-forge/noarch::six-1.16.0-pyh6c4a22f_0
  sortedcontainers   conda-forge/noarch::sortedcontainers-2.4.0-pyhd8ed1ab_0
  sqlite             conda-forge/osx-64::sqlite-3.38.2-hb516253_0
  tblib              conda-forge/noarch::tblib-1.7.0-pyhd8ed1ab_0
  tk                 conda-forge/osx-64::tk-8.6.12-h5dbffcc_0
  toolz              conda-forge/noarch::toolz-0.11.2-pyhd8ed1ab_0
  tornado            conda-forge/osx-64::tornado-6.1-py310h1961e1f_3
  typing_extensions  conda-forge/noarch::typing_extensions-4.2.0-pyha770c72_1
  tzdata             conda-forge/noarch::tzdata-2022a-h191b570_0
  urllib3            conda-forge/noarch::urllib3-1.26.9-pyhd8ed1ab_0
  wheel              conda-forge/noarch::wheel-0.37.1-pyhd8ed1ab_0
  xorg-libxau        conda-forge/osx-64::xorg-libxau-1.0.9-h35c211d_0
  xorg-libxdmcp      conda-forge/osx-64::xorg-libxdmcp-1.1.3-h35c211d_0
  xz                 conda-forge/osx-64::xz-5.2.5-haf1e3a3_1
  yaml               conda-forge/osx-64::yaml-0.2.5-h0d85af4_2
  zict               conda-forge/noarch::zict-2.1.0-pyhd8ed1ab_0
  zlib               conda-forge/osx-64::zlib-1.2.11-h6c3fc93_1014
  zstd               conda-forge/osx-64::zstd-1.5.2-h582d3a0_0


Proceed ([y]/n)? y


Downloading and Extracting Packages
pandas-1.4.2         | 12.1 MB   | ################################################################################################################ | 100%
distributed-2022.04. | 714 KB    | ################################################################################################################ | 100%
dask-2022.04.2a22042 | 5 KB      | ################################################################################################################ | 100%
bokeh-2.4.2          | 13.7 MB   | ################################################################################################################ | 100%
dask-core-2022.04.2a | 815 KB    |                                                                                                                  |   0%
numpy-1.22.3         | 6.4 MB    | ################################################################################################################ | 100%
pillow-9.1.0         | 45.1 MB   | ################################################################################################################ | 100%

CondaHTTPError: HTTP 404 NOT FOUND for url <https://conda.anaconda.org/dask/label/dev/noarch/dask-core-2022.04.2a220426-py_g23408870a_20.tar.bz2>
Elapsed: 00:00.142452
CF-RAY: 7022325708d326cb-MSP

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.



```

</details>

**Comment by bryanwweber** [comment]
I can reproduce this, but I get a different error (from Mamba):

<details>

```
error    libmamba File not valid: file size doesn't match expectation "/Users/bryan/mambaforge/pkgs/dask-core-2022.04.2a220426-py_g23408870a_20.tar.bz2"
    Expected: 834200
    Actual: 10014
dask-core                                           10.0kB @  30.4kB/s  0.3s
dask-core-2022.04.2a220426-py_g23408870a_20.tar.bz2 tarball has incorrect size
distributed                                        730.6kB @   1.2MB/s  0.6s

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/Users/bryan/mambaforge/lib/python3.9/site-packages/conda/exceptions.py", line 1082, in __call__
        return func(*args, **kwargs)
      File "/Users/bryan/mambaforge/lib/python3.9/site-packages/mamba/mamba.py", line 951, in exception_converter
        raise e
      File "/Users/bryan/mambaforge/lib/python3.9/site-packages/mamba/mamba.py", line 945, in exception_converter
        exit_code = _wrapped_main(*args, **kwargs)
      File "/Users/bryan/mambaforge/lib/python3.9/site-packages/mamba/mamba.py", line 901, in _wrapped_main
        result = do_call(args, p)
      File "/Users/bryan/mambaforge/lib/python3.9/site-packages/mamba/mamba.py", line 767, in do_call
        exit_code = create(args, parser)
      File "/Users/bryan/mambaforge/lib/python3.9/site-packages/mamba/mamba.py", line 643, in create
        return install(args, parser, "create")
      File "/Users/bryan/mambaforge/lib/python3.9/site-packages/mamba/mamba.py", line 599, in install
        transaction.fetch_extract_packages()
    RuntimeError: Found incorrect download: dask-core. Aborting

`$ /Users/bryan/mambaforge/bin/mamba create -n dask-dev-version -c dask/label/dev dask`

  environment variables:
                 CIO_TEST=<not set>
        CONDA_DEFAULT_ENV=parquet
                CONDA_EXE=/Users/bryan/mambaforge/bin/conda
             CONDA_PREFIX=/Users/bryan/mambaforge/envs/parquet
           CONDA_PREFIX_1=/Users/bryan/mambaforge
    CONDA_PROMPT_MODIFIER=
         CONDA_PYTHON_EXE=/Users/bryan/mambaforge/bin/python
               CONDA_ROOT=/Users/bryan/mambaforge
              CONDA_SHLVL=2
           CURL_CA_BUNDLE=<not set>
                     PATH=/Users/bryan/mambaforge/bin:/Users/bryan/mambaforge/envs/parquet/bin:/
                          Users/bryan/mambaforge/condabin:/opt/homebrew/bin:/usr/local/bin:/usr/
                          bin:/bin:/usr/sbin:/sbin:/Users/bryan/.local/bin:/opt/homebrew/opt/fzf
                          /bin:/Users/bryan/.local/bin
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>

     active environment : parquet
    active env location : /Users/bryan/mambaforge/envs/parquet
            shell level : 2
       user config file : /Users/bryan/.condarc
 populated config files : /Users/bryan/mambaforge/.condarc
                          /Users/bryan/.condarc
          conda version : 4.12.0
    conda-build version : 3.21.8
         python version : 3.9.12.final.0
       virtual packages : __osx=12.3.1=0
                          __unix=0=0
                          __archspec=1=arm64
       base environment : /Users/bryan/mambaforge  (writable)
      conda av data dir : /Users/bryan/mambaforge/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/dask/label/dev/osx-arm64
                          https://conda.anaconda.org/dask/label/dev/noarch
                          https://conda.anaconda.org/conda-forge/osx-arm64
                          https://conda.anaconda.org/conda-forge/noarch
          package cache : /Users/bryan/mambaforge/pkgs
                          /Users/bryan/.conda/pkgs
       envs directories : /Users/bryan/mambaforge/envs
                          /Users/bryan/.conda/envs
               platform : osx-arm64
             user-agent : conda/4.12.0 requests/2.27.1 CPython/3.9.12 Darwin/21.4.0 OSX/12.3.1
                UID:GID : 501:20
             netrc file : None
           offline mode : False


An unexpected error has occurred. Conda has prepared the above report.
```

</details>

**Comment by jakirkham** [comment]
This is not specific to the Dask nightly or this channel. Anaconda.org is experiencing some issues and they are working on it

**Comment by jrbourbeau** [comment]
Ah, thanks @jakirkham 👍  I'll close this issue then

**Comment by jakirkham** [comment]
This got fixed earlier today. So should be good to retry

https://twitter.com/condaproject/status/1519110109321830400
