### ISSUE TITLE
`corrcoef` with Sparse Arrays

### ISSUE THREAD

**Issue by ilan-gold** [dask/dask#9021]
**What happened**:
I am trying to compute a correlation matrix and am getting some errors.

**What you expected to happen**:
The matrix should be computed

**Minimal Complete Verifiable Example**:

```python
from scipy.sparse import csr_matrix
import sparse
import dask.array as da

x = csr_matrix([[0,1],[2,2]])
x = sparse.COO.from_scipy_sparse(x)
dask_data = da.from_array(x, asarray=False)
corr = da.corrcoef(dask_data)
corr.compute()
```
Error:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/ilangold/Library/Caches/pypoetry/virtualenvs/scfglue--xSM6sHX-py3.9/lib/python3.9/site-packages/dask/base.py", line 292, in compute
    (result,) = compute(self, traverse=False, **kwargs)
  File "/Users/ilangold/Library/Caches/pypoetry/virtualenvs/scfglue--xSM6sHX-py3.9/lib/python3.9/site-packages/dask/base.py", line 575, in compute
    results = schedule(dsk, keys, **kwargs)
  File "/Users/ilangold/Library/Caches/pypoetry/virtualenvs/scfglue--xSM6sHX-py3.9/lib/python3.9/site-packages/dask/threaded.py", line 81, in get
    results = get_async(
  File "/Users/ilangold/Library/Caches/pypoetry/virtualenvs/scfglue--xSM6sHX-py3.9/lib/python3.9/site-packages/dask/local.py", line 508, in get_async
    raise_exception(exc, tb)
  File "/Users/ilangold/Library/Caches/pypoetry/virtualenvs/scfglue--xSM6sHX-py3.9/lib/python3.9/site-packages/dask/local.py", line 316, in reraise
    raise exc
  File "/Users/ilangold/Library/Caches/pypoetry/virtualenvs/scfglue--xSM6sHX-py3.9/lib/python3.9/site-packages/dask/local.py", line 221, in execute_task
    result = _execute_task(task, data)
  File "/Users/ilangold/Library/Caches/pypoetry/virtualenvs/scfglue--xSM6sHX-py3.9/lib/python3.9/site-packages/dask/core.py", line 119, in _execute_task
    return func(*(_execute_task(a, cache) for a in args))
  File "/Users/ilangold/Library/Caches/pypoetry/virtualenvs/scfglue--xSM6sHX-py3.9/lib/python3.9/site-packages/dask/core.py", line 119, in <genexpr>
    return func(*(_execute_task(a, cache) for a in args))
  File "/Users/ilangold/Library/Caches/pypoetry/virtualenvs/scfglue--xSM6sHX-py3.9/lib/python3.9/site-packages/dask/core.py", line 119, in _execute_task
    return func(*(_execute_task(a, cache) for a in args))
  File "/Users/ilangold/Library/Caches/pypoetry/virtualenvs/scfglue--xSM6sHX-py3.9/lib/python3.9/site-packages/dask/core.py", line 119, in <genexpr>
    return func(*(_execute_task(a, cache) for a in args))
  File "/Users/ilangold/Library/Caches/pypoetry/virtualenvs/scfglue--xSM6sHX-py3.9/lib/python3.9/site-packages/dask/core.py", line 119, in _execute_task
    return func(*(_execute_task(a, cache) for a in args))
  File "/Users/ilangold/Library/Caches/pypoetry/virtualenvs/scfglue--xSM6sHX-py3.9/lib/python3.9/site-packages/dask/core.py", line 119, in <genexpr>
    return func(*(_execute_task(a, cache) for a in args))
  File "/Users/ilangold/Library/Caches/pypoetry/virtualenvs/scfglue--xSM6sHX-py3.9/lib/python3.9/site-packages/dask/core.py", line 119, in _execute_task
    return func(*(_execute_task(a, cache) for a in args))
  File "<__array_function__ internals>", line 5, in diag
TypeError: no implementation found for 'numpy.diag' on types that implement __array_function__: [<class 'sparse._coo.core.COO'>
```

**Environment**:

- Dask version: `2022.4.1`
- Python version: `3.9`
- Operating System: Mac OS
- Install method (conda, pip, source): `pip`/`poetry`

**Comment by ilan-gold** [comment]
Thanks @pavithraes - perhaps just documenting this would close the issue? Or should functions that aren't implemented for sparse arrays in numpy still work with sparse arrays in dask?

**Comment by pavithraes** [comment]
> perhaps just documenting this would close the issue?

@ilan-gold I agree, would be interested in opening a PR for this? We can maybe add a docstring with a note here that says `corrceof` doesn't support `sparse` arrays:
https://github.com/dask/dask/blob/5fbda77cfc5bc1b8f1453a2dbb034b048fc10726/dask/array/routines.py#L1561-L1569

>  Or should functions that aren't implemented for sparse arrays in numpy still work with sparse arrays in dask?

Generally, I don't think so, becauase Dask Array tries to match NumPy. One exception could be if there is an implementation in the [`sparse` API](https://sparse.pydata.org/en/stable/generated/sparse.html). :)

**Comment by jakirkham** [comment]
Might be worth reading through issue ( https://github.com/pydata/sparse/issues/262 ).

Also issue ( https://github.com/pydata/sparse/issues/288 ) and PR ( https://github.com/pydata/sparse/pull/289 ) appear directly relevant. Looking at those the Dask algorithm may need some slight tweaking to work with Sparse. Hopefully that provides a starting point as to how that might work.
