### ISSUE TITLE
Unexpected `AttributeError` on `Series.cumsum`

### ISSUE THREAD

**Issue by charlesbluca** [dask/dask#9067]
**What happened**:
When attempting to compute `cumsum` on a series that is the result of a `map_partitions` call, I am getting an unexpected `AttributeError`:

```python
Traceback (most recent call last):
  File "/datasets/charlesb/dev/rapids/dask-sql/test.py", line 6, in <module>
    res = ddf.map_partitions(lambda x: 1).cumsum().compute()
  File "/datasets/charlesb/dev/rapids/dask/dask/base.py", line 311, in compute
    (result,) = compute(self, traverse=False, **kwargs)
  File "/datasets/charlesb/dev/rapids/dask/dask/base.py", line 599, in compute
    results = schedule(dsk, keys, **kwargs)
  File "/datasets/charlesb/dev/rapids/dask/dask/threaded.py", line 81, in get
    results = get_async(
  File "/datasets/charlesb/dev/rapids/dask/dask/local.py", line 508, in get_async
    raise_exception(exc, tb)
  File "/datasets/charlesb/dev/rapids/dask/dask/local.py", line 316, in reraise
    raise exc
  File "/datasets/charlesb/dev/rapids/dask/dask/local.py", line 221, in execute_task
    result = _execute_task(task, data)
  File "/datasets/charlesb/dev/rapids/dask/dask/core.py", line 119, in _execute_task
    return func(*(_execute_task(a, cache) for a in args))
  File "/datasets/charlesb/dev/rapids/dask/dask/optimization.py", line 990, in __call__
    return core.get(self.dsk, self.outkey, dict(zip(self.inkeys, args)))
  File "/datasets/charlesb/dev/rapids/dask/dask/core.py", line 149, in get
    result = _execute_task(task, cache)
  File "/datasets/charlesb/dev/rapids/dask/dask/core.py", line 119, in _execute_task
    return func(*(_execute_task(a, cache) for a in args))
  File "/datasets/charlesb/dev/rapids/dask/dask/utils.py", line 40, in apply
    return func(*args, **kwargs)
  File "/datasets/charlesb/dev/rapids/dask/dask/dataframe/core.py", line 6429, in apply_and_enforce
    df = func(*args, **kwargs)
  File "/datasets/charlesb/dev/rapids/dask/dask/utils.py", line 1046, in __call__
    return getattr(__obj, self.method)(*args, **kwargs)
AttributeError: 'int' object has no attribute 'cumsum'
```

**What you expected to happen**:
The same code works if I compute the result of the `map_partitions` call prior to computing `cumsum`, so I would expect that result regardless of intermediate computes.

**Minimal Complete Verifiable Example**:
This fails:

```python
import dask.dataframe as dd
import pandas as pd

ddf = dd.from_pandas(pd.DataFrame({"a": range(10)}), 2)

res = ddf.map_partitions(lambda x: len(x)).cumsum().compute()
```

While this succeeds:

```python
res = ddf.map_partitions(lambda x: len(x)).compute().cumsum()
```

**Environment**:

- Dask version: latest `main`
- Python version: 3.9
- Operating System: ubuntu 20.04
- Install method (conda, pip, source): source

**Comment by pavithraes** [comment]
Yes, I agree with Julia's thoughts here.

> it is probably a better practice to be explicit about what the output of your function should be.

It'll be nice to update the `map_partitions` docstring to include this. :)
