### ISSUE TITLE
Msgpack TypeError when performing dask-geopandas sjoin

### ISSUE THREAD

**Issue by avriiil** [dask/dask#9072]
**What happened**:
Performing a spatial join with `dask-geopandas` fails with a `msgpack` TypeError.

**Minimal Complete Verifiable Example**:
Not quite an MCVE, but the code below produces the error. Notebook + environment.yml [here](https://github.com/coiled/coiled-resources/blob/rrp-spatialjoin/spatial-join/debugging.ipynb).

```python
from coiled.v2 import Cluster

cluster = Cluster(
    name="spatial-join",
    software="coiled-examples/spatial-join",
    n_workers=50,
    worker_memory="16Gib",
)

from distributed import Client
client = Client(cluster)

import dask.dataframe as dd

ddf = dd.read_parquet(
    "s3://coiled-datasets/dask-book/nyc-tlc/2009-2013/*",
    engine="pyarrow",
    storage_options={"anon": True},
)

import dask_geopandas

ddf = ddf.set_geometry(
    dask_geopandas.points_from_xy(ddf, "pickup_longitude", "pickup_latitude"),
)

ddf = ddf.set_crs(4326)

import geopandas as gpd

ngbhoods = gpd.read_file(
    "CHS_2009_DOHMH_2010B/CHS_2009_DOHMH_2010B.shp"
)
ngbhoods = ngbhoods[["FIRST_UHF_", "UHF_CODE", "geometry"]]
ngbhoods = ngbhoods[:34]
ngbhoods = ngbhoods.to_crs(epsg=4326)

joined = ddf.sjoin(ngbhoods, predicate="within")

joined1.head()
```

TRACEBACK:
```
distributed.protocol.core - CRITICAL - Failed to Serialize
Traceback (most recent call last):
  File "/Users/rpelgrim/mambaforge/envs/dask-dataframe/lib/python3.9/site-packages/distributed/protocol/core.py", line 76, in dumps
    frames[0] = msgpack.dumps(msg, default=_encode_default, use_bin_type=True)
  File "/Users/rpelgrim/mambaforge/envs/dask-dataframe/lib/python3.9/site-packages/msgpack/__init__.py", line 35, in packb
    return Packer(**kwargs).pack(o)
  File "msgpack/_packer.pyx", line 294, in msgpack._cmsgpack.Packer.pack
  File "msgpack/_packer.pyx", line 300, in msgpack._cmsgpack.Packer.pack
  File "msgpack/_packer.pyx", line 297, in msgpack._cmsgpack.Packer.pack
  File "msgpack/_packer.pyx", line 264, in msgpack._cmsgpack.Packer._pack
  File "msgpack/_packer.pyx", line 231, in msgpack._cmsgpack.Packer._pack
  File "msgpack/_packer.pyx", line 231, in msgpack._cmsgpack.Packer._pack
  File "msgpack/_packer.pyx", line 264, in msgpack._cmsgpack.Packer._pack
  File "msgpack/_packer.pyx", line 231, in msgpack._cmsgpack.Packer._pack
  File "msgpack/_packer.pyx", line 231, in msgpack._cmsgpack.Packer._pack
  File "msgpack/_packer.pyx", line 231, in msgpack._cmsgpack.Packer._pack
  File "msgpack/_packer.pyx", line 264, in msgpack._cmsgpack.Packer._pack
  File "msgpack/_packer.pyx", line 264, in msgpack._cmsgpack.Packer._pack
  File "msgpack/_packer.pyx", line 291, in msgpack._cmsgpack.Packer._pack
TypeError: can not serialize 'numpy.int64' object
distributed.comm.utils - INFO - Unserializable Message: [{'op': 'update-graph-hlg', 'hlg': {'layers': [{'__module__': 'dask.blockwise', '__name__': 'Blockwise', 'state': {'output': '_set_crs-6ca0659b532951365eb2f3c74d7d5dda', 'output_indices': ('.0',), 'func': b'\x80\x04\x95\x03\x00\x01\x00\x00\x00\x00\x00\x8c\x11dask.optimization\x94\x8c\x10SubgraphCallable\x94\x93\x94(}\x94(\x8c)_set_crs-6ca0659b532951365eb2f3c74d7d5dda\x94\x8cEpoints_from_xy-set_geometry-_set_crs-6ca0659b532951365eb2f3c74d7d5dda\x94\x8c0read-parquet-520df5ddd4d8ac310c949ff50485dcbb_.
```

**Anything else we need to know?**:
- Paired with @crusaderky briefly. We confirmed that `dd.from_pandas(ngbhoods, npartitions=1).compute()` works so it can make a roundtrip fine. His first instinct is that something is likely off in `dask.dataframe` where it's letting `numpy.int64` slip to `msgpack`.

**Environment**:

- Dask version: 2022.01.0
- Python version: 3.9.7
- Operating System: MacOS
- Install method (conda, pip, source): conda

**Comment by gjoseph92** [comment]
cc @rjzamora @madsbk, looks like an HLG serialization issue

**Comment by jorisvandenbossche** [comment]
I ran into this as well in the past (also with dask-geopandas). I did a fix on the dask-geopandas side (ensuring we always convert the np.int64 to a python int already on our side), https://github.com/geopandas/dask-geopandas/pull/113, but in the end I didn't merge it because I could not reproduce the issue ...
