### ISSUE TITLE
dask-cudf groupby call failing

### ISSUE THREAD

**Issue by jnke2016** [dask/dask#9089]
A recent change in dask-cudf is causing an issue with the `groupby` call. Below is a minimal reproducer
```
import cudf
import cugraph
from dask_cuda import LocalCUDACluster
import dask_cudf
from dask.distributed import Client
​
def setup():
    cluster = LocalCUDACluster()
    client = Client(cluster)
​
    return (client, cluster)
​
def teardown(client, cluster=None):
    client.close()
    if cluster:
        cluster.close()
​
def symmetrize(ddf, src_name, dst_name):
    if not isinstance(src_name, list):
        src_name = [src_name]
    if not isinstance(dst_name, list):
        dst_name = [dst_name]
​
    num_partitions = ddf.npartitions
    
    ddf2 = ddf[[*dst_name, *src_name]]
    ddf2.columns = [*src_name, *dst_name]
    result = dask_cudf.concat([ddf, ddf2]).reset_index(drop=True)
    
    vertex_col_name = src_name + dst_name
    result = result.groupby(by=[*vertex_col_name]).min(
        split_out=num_partitions).reset_index()
​
    return result
​
​
if __name__ == "__main__":
    setup_objs = setup()
    client = setup_objs[0]
    workers = client.scheduler_info()['workers']
    num_gpus = len(workers)
    
​
    df = cudf.DataFrame()
​
    df["src"] = [v for v in range(20)]
    df["dst"] = [v for v in range(1, 21)]
    ddf = dask_cudf.from_cudf(df, npartitions=num_gpus)
    ddf_sym = symmetrize(ddf, "src", "dst")
​
    print(ddf_sym.compute())
​
    teardown(*setup_objs)
```

The above script works on `dask-cudf 22.4.0a0+gb50ae82 pypi_0  pypi` and worked on a prior 22.6 version from a 22.06 `Rapids container` (but since it recently got updated with a later `dask-cudf` version, it is no longer working).

The script above is currently failing on `dask-cudf 22.06.00a220514` which I believe is the latest version.

**Comment by jnke2016** [comment]
Here is a traceback of the error I get
```
/opt/conda/envs/rapids/lib/python3.8/site-packages/cudf/core/dataframe.py:1055: FutureWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  return pd.Series(self._dtypes)
2022-05-14 22:20:59,536 - distributed.worker - WARNING - Compute Failed
Key:       ('groupby_partition_agg-375460dc3661b54d1e2b5b22a300f5b0', 0)
Function:  _groupby_partition_agg
args:      (   src  dst
0    0    1
1    1    2
2    2    3
3    3    4
4    4    5
5    5    6
6    6    7
7    7    8
8    8    9
9    9   10, ['src', 'dst'], {}, [], 2, True, None, '___')
kwargs:    {}
Exception: "ValueError('tuple.index(x): x not in tuple')"

Traceback (most recent call last):
  File "reproducer.py", line 49, in <module>
    print(ddf_sym.compute())
  File "/opt/conda/envs/rapids/lib/python3.8/site-packages/dask/base.py", line 292, in compute
    (result,) = compute(self, traverse=False, **kwargs)
  File "/opt/conda/envs/rapids/lib/python3.8/site-packages/dask/base.py", line 575, in compute
    results = schedule(dsk, keys, **kwargs)
  File "/opt/conda/envs/rapids/lib/python3.8/site-packages/distributed/client.py", line 3004, in get
    results = self.gather(packed, asynchronous=asynchronous, direct=direct)
  File "/opt/conda/envs/rapids/lib/python3.8/site-packages/distributed/client.py", line 2178, in gather
    return self.sync(
  File "/opt/conda/envs/rapids/lib/python3.8/site-packages/distributed/utils.py", line 318, in sync
    return sync(
  File "/opt/conda/envs/rapids/lib/python3.8/site-packages/distributed/utils.py", line 385, in sync
    raise exc.with_traceback(tb)
  File "/opt/conda/envs/rapids/lib/python3.8/site-packages/distributed/utils.py", line 358, in f
    result = yield future
  File "/opt/conda/envs/rapids/lib/python3.8/site-packages/tornado/gen.py", line 762, in run
    value = future.result()
  File "/opt/conda/envs/rapids/lib/python3.8/site-packages/distributed/client.py", line 2041, in _gather
    raise exception.with_traceback(traceback)
  File "/opt/conda/envs/rapids/lib/python3.8/contextlib.py", line 75, in inner
    return func(*args, **kwds)
  File "/opt/conda/envs/rapids/lib/python3.8/site-packages/dask_cudf/groupby.py", line 732, in _groupby_partition_agg
2022-05-14 22:20:59,551 - distributed.worker - WARNING - Compute Failed
Key:       ('groupby_partition_agg-375460dc3661b54d1e2b5b22a300f5b0', 2)
Function:  _groupby_partition_agg
args:      (   src  dst
0    1    0
1    2    1
2    3    2
3    4    3
4    5    4
5    6    5
6    7    6
7    8    7
8    9    8
9   10    9, ['src', 'dst'], {}, [], 2, True, None, '___')
kwargs:    {}
Exception: "ValueError('tuple.index(x): x not in tuple')"

    gb.partition_by_hash(gb_cols, split_out, keep_index=False)
  File "/opt/conda/envs/rapids/lib/python3.8/contextlib.py", line 75, in inner
    return func(*args, **kwds)
  File "/opt/conda/envs/rapids/lib/python3.8/site-packages/cudf/core/dataframe.py", line 4052, in partition_by_hash
    key_indices = [self._column_names.index(k) for k in columns]
  File "/opt/conda/envs/rapids/lib/python3.8/site-packages/cudf/core/dataframe.py", line 4052, in <listcomp>
    key_indices = [self._column_names.index(k) for k in columns]
ValueError: tuple.index(x): x not in tuple
2022-05-14 22:21:00,864 - tornado.application - ERROR - Exception in callback <bound method Client._heartbeat of <Client: 'tcp://127.0.0.1:33167' processes=0 threads=0, memory=0 B>>
Traceback (most recent call last):
  File "/opt/conda/envs/rapids/lib/python3.8/site-packages/tornado/ioloop.py", line 905, in _run
    return self.callback()
  File "/opt/conda/envs/rapids/lib/python3.8/site-packages/distributed/client.py", line 1343, in _heartbeat
    self.scheduler_comm.send({"op": "heartbeat-client"})
  File "/opt/conda/envs/rapids/lib/python3.8/site-packages/distributed/batched.py", line 137, in send
    raise CommClosedError(f"Comm {self.comm!r} already closed.")
distributed.comm.core.CommClosedError: Comm <TCP (closed) Client->Scheduler local=tcp://127.0.0.1:53298 remote=tcp://127.0.0.1:33167> already closed.
```

**Comment by jakirkham** [comment]
Is it possible to reproduce this without cuDF? IOW just using Pandas?

**Comment by pavithraes** [comment]
I tried running this with only pandas, Dask DataFrame, and LocalCLuster -- it seems to be working fine.

<details>
<summary>Code</summary>

```python

import pandas as pd
import dask.dataframe as dd
from dask.distributed import Client, LocalCluster


def setup():
    cluster = LocalCluster()
    client = Client(cluster)

    return (client, cluster)


def teardown(client, cluster=None):
    client.close()
    if cluster:
        cluster.close()


def symmetrize(ddf, src_name, dst_name):
    if not isinstance(src_name, list):
        src_name = [src_name]
    if not isinstance(dst_name, list):
        dst_name = [dst_name]

    num_partitions = ddf.npartitions
    
    ddf2 = ddf[[*dst_name, *src_name]]
    ddf2.columns = [*src_name, *dst_name]
    result = dd.concat([ddf, ddf2]).reset_index(drop=True)
    
    vertex_col_name = src_name + dst_name
    result = result.groupby(by=[*vertex_col_name]).min(
        split_out=num_partitions).reset_index()

    return result


if __name__ == "__main__":
    setup_objs = setup()
    client = setup_objs[0]
    workers = client.scheduler_info()['workers']
    num_gpus = len(workers)
    

    df = pd.DataFrame()

    df["src"] = [v for v in range(20)]
    df["dst"] = [v for v in range(1, 21)]
    ddf = dd.from_pandas(df, npartitions=num_gpus)
    ddf_sym = symmetrize(ddf, "src", "dst")

    print(ddf_sym.compute())

    teardown(*setup_objs)

```

</details>

**Comment by jnke2016** [comment]
I think this is not the right repository for the issue. I apologize about that

**Comment by jakirkham** [comment]
Moved to issue ( https://github.com/rapidsai/cudf/issues/10863 )

**Comment by jnke2016** [comment]
Thanks
