### ISSUE TITLE
serialization issue

### ISSUE THREAD

**Issue by cristianmtr** [dask/dask#9190]
**What happened**:
Full trace here:

<details>

```python
distributed.protocol.core - CRITICAL - Failed to Serialize
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/distributed/protocol/core.py", line 76, in dumps
    frames[0] = msgpack.dumps(msg, default=_encode_default, use_bin_type=True)
  File "/opt/conda/lib/python3.7/site-packages/msgpack/__init__.py", line 38, in packb
    return Packer(**kwargs).pack(o)
  File "msgpack/_packer.pyx", line 294, in msgpack._cmsgpack.Packer.pack
  File "msgpack/_packer.pyx", line 300, in msgpack._cmsgpack.Packer.pack
  File "msgpack/_packer.pyx", line 297, in msgpack._cmsgpack.Packer.pack
  File "msgpack/_packer.pyx", line 231, in msgpack._cmsgpack.Packer._pack
  File "msgpack/_packer.pyx", line 231, in msgpack._cmsgpack.Packer._pack
  File "msgpack/_packer.pyx", line 285, in msgpack._cmsgpack.Packer._pack
  File "/opt/conda/lib/python3.7/site-packages/distributed/protocol/core.py", line 62, in _encode_default
    size=frame_split_size,
  File "/opt/conda/lib/python3.7/site-packages/distributed/protocol/serialize.py", line 435, in serialize_and_split
    header, frames = serialize(x, serializers, on_error, context)
  File "/opt/conda/lib/python3.7/site-packages/distributed/protocol/serialize.py", line 267, in serialize
    iterate_collection=True,
  File "/opt/conda/lib/python3.7/site-packages/distributed/protocol/serialize.py", line 359, in serialize
    raise TypeError(msg, str(x)[:10000])
TypeError: ('Could not serialize object of type function.', '<function PandasDataframe._reorder_labels.<locals>.<lambda> at 0x7f5b54920b00>')
distributed.comm.utils - ERROR - ('Could not serialize object of type function.', '<function PandasDataframe._reorder_labels.<locals>.<lambda> at 0x7f5b54920b00>')
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/distributed/comm/utils.py", line 33, in _to_frames
    return list(protocol.dumps(msg, **kwargs))
  File "/opt/conda/lib/python3.7/site-packages/distributed/protocol/core.py", line 76, in dumps
    frames[0] = msgpack.dumps(msg, default=_encode_default, use_bin_type=True)
  File "/opt/conda/lib/python3.7/site-packages/msgpack/__init__.py", line 38, in packb
    return Packer(**kwargs).pack(o)
  File "msgpack/_packer.pyx", line 294, in msgpack._cmsgpack.Packer.pack
  File "msgpack/_packer.pyx", line 300, in msgpack._cmsgpack.Packer.pack
  File "msgpack/_packer.pyx", line 297, in msgpack._cmsgpack.Packer.pack
  File "msgpack/_packer.pyx", line 231, in msgpack._cmsgpack.Packer._pack
  File "msgpack/_packer.pyx", line 231, in msgpack._cmsgpack.Packer._pack
  File "msgpack/_packer.pyx", line 285, in msgpack._cmsgpack.Packer._pack
  File "/opt/conda/lib/python3.7/site-packages/distributed/protocol/core.py", line 62, in _encode_default
    size=frame_split_size,
  File "/opt/conda/lib/python3.7/site-packages/distributed/protocol/serialize.py", line 435, in serialize_and_split
    header, frames = serialize(x, serializers, on_error, context)
  File "/opt/conda/lib/python3.7/site-packages/distributed/protocol/serialize.py", line 267, in serialize
    iterate_collection=True,
  File "/opt/conda/lib/python3.7/site-packages/distributed/protocol/serialize.py", line 359, in serialize
    raise TypeError(msg, str(x)[:10000])
TypeError: ('Could not serialize object of type function.', '<function PandasDataframe._reorder_labels.<locals>.<lambda> at 0x7f5b54920b00>')
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
/tmp/ipykernel_4769/4274681390.py in <module>
----> 1 df.sample(5)

/opt/conda/lib/python3.7/site-packages/modin/pandas/base.py in sample(self, n, frac, replace, weights, random_state, axis, ignore_index)
   2255             return self.__constructor__(query_compiler=query_compiler)
   2256         else:
-> 2257             query_compiler = self._query_compiler.getitem_row_array(samples)
   2258             return self.__constructor__(query_compiler=query_compiler)
   2259 

/opt/conda/lib/python3.7/site-packages/modin/core/storage_formats/pandas/query_compiler.py in getitem_row_array(self, key)
   2152 
   2153     def getitem_row_array(self, key):
-> 2154         return self.__constructor__(self._modin_frame.mask(row_numeric_idx=key))
   2155 
   2156     def setitem(self, axis, key, value):

/opt/conda/lib/python3.7/site-packages/modin/core/dataframe/pandas/dataframe/dataframe.py in mask(self, row_indices, row_numeric_idx, col_indices, col_numeric_idx)
    613             new_col_order = None
    614         return intermediate._reorder_labels(
--> 615             row_numeric_idx=new_row_order, col_numeric_idx=new_col_order
    616         )
    617 

/opt/conda/lib/python3.7/site-packages/modin/core/dataframe/pandas/dataframe/dataframe.py in _reorder_labels(self, row_numeric_idx, col_numeric_idx)
    738         if row_numeric_idx is not None:
    739             ordered_rows = self._partition_mgr_cls.map_axis_partitions(
--> 740                 0, self._partitions, lambda df: df.iloc[row_numeric_idx]
    741             )
    742             row_idx = self.index[row_numeric_idx]

/opt/conda/lib/python3.7/site-packages/modin/core/dataframe/pandas/partitioning/partition_manager.py in map_axis_partitions(cls, axis, partitions, map_func, keep_partitioning, lengths, enumerate_partitions, **kwargs)
    558             lengths=lengths,
    559             enumerate_partitions=enumerate_partitions,
--> 560             **kwargs,
    561         )
    562 

/opt/conda/lib/python3.7/site-packages/modin/core/dataframe/pandas/partitioning/partition_manager.py in broadcast_axis_partitions(cls, axis, apply_func, left, right, keep_partitioning, apply_indices, enumerate_partitions, lengths, **kwargs)
    421         else:
    422             num_splits = NPartitions.get()
--> 423         preprocessed_map_func = cls.preprocess_func(apply_func)
    424         left_partitions = cls.axis_partition(left, axis)
    425         right_partitions = None if right is None else cls.axis_partition(right, axis)

/opt/conda/lib/python3.7/site-packages/modin/core/dataframe/pandas/partitioning/partition_manager.py in preprocess_func(cls, map_func)
    111         you are using does not require any modification to a given function.
    112         """
--> 113         return cls._partition_class.preprocess_func(map_func)
    114 
    115     # END Abstract Methods

/opt/conda/lib/python3.7/site-packages/modin/core/execution/dask/implementations/pandas_on_dask/partitioning/partition.py in preprocess_func(cls, func)
    266             An object that can be accepted by ``apply``.
    267         """
--> 268         return default_client().scatter(func, hash=False, broadcast=True)
    269 
    270     @classmethod

/opt/conda/lib/python3.7/site-packages/distributed/client.py in scatter(self, data, workers, broadcast, direct, hash, timeout, asynchronous)
   2363             timeout=timeout,
   2364             asynchronous=asynchronous,
-> 2365             hash=hash,
   2366         )
   2367 

/opt/conda/lib/python3.7/site-packages/distributed/utils.py in sync(self, func, asynchronous, callback_timeout, *args, **kwargs)
    308         else:
    309             return sync(
--> 310                 self.loop, func, *args, callback_timeout=callback_timeout, **kwargs
    311             )
    312 

/opt/conda/lib/python3.7/site-packages/distributed/utils.py in sync(loop, func, callback_timeout, *args, **kwargs)
    374     if error:
    375         typ, exc, tb = error
--> 376         raise exc.with_traceback(tb)
    377     else:
    378         return result

/opt/conda/lib/python3.7/site-packages/distributed/utils.py in f()
    347                 future = asyncio.wait_for(future, callback_timeout)
    348             future = asyncio.ensure_future(future)
--> 349             result = yield future
    350         except Exception:
    351             error = sys.exc_info()

/opt/conda/lib/python3.7/site-packages/tornado/gen.py in run(self)
    760 
    761                     try:
--> 762                         value = future.result()
    763                     except Exception:
    764                         exc_info = sys.exc_info()

/opt/conda/lib/python3.7/site-packages/distributed/client.py in _scatter(self, data, workers, broadcast, direct, local_worker, timeout, hash)
   2244                     client=self.id,
   2245                     broadcast=broadcast,
-> 2246                     timeout=timeout,
   2247                 )
   2248 

/opt/conda/lib/python3.7/site-packages/distributed/core.py in send_recv_from_rpc(**kwargs)
    903             prev_name, comm.name = comm.name, "ConnectionPool." + key
    904             try:
--> 905                 return await send_recv(comm=comm, op=key, **kwargs)
    906             finally:
    907                 self.pool.reuse(self.addr, comm)

/opt/conda/lib/python3.7/site-packages/distributed/core.py in send_recv(comm, reply, serializers, deserializers, **kwargs)
    670 
    671     try:
--> 672         await comm.write(msg, serializers=serializers, on_error="raise")
    673         if reply:
    674             response = await comm.read(deserializers=deserializers)

/opt/conda/lib/python3.7/site-packages/distributed/comm/tcp.py in write(self, msg, serializers, on_error)
    258                 **self.handshake_options,
    259             },
--> 260             frame_split_size=self.max_shard_size,
    261         )
    262         frames_nbytes = [nbytes(f) for f in frames]

/opt/conda/lib/python3.7/site-packages/distributed/comm/utils.py in to_frames(msg, allow_offload, **kwargs)
     48         return await offload(_to_frames)
     49     else:
---> 50         return _to_frames()
     51 
     52 

/opt/conda/lib/python3.7/site-packages/distributed/comm/utils.py in _to_frames()
     31     def _to_frames():
     32         try:
---> 33             return list(protocol.dumps(msg, **kwargs))
     34         except Exception as e:
     35             logger.info("Unserializable Message: %s", msg)

/opt/conda/lib/python3.7/site-packages/distributed/protocol/core.py in dumps(msg, serializers, on_error, context, frame_split_size)
     74                 return msgpack_encode_default(obj)
     75 
---> 76         frames[0] = msgpack.dumps(msg, default=_encode_default, use_bin_type=True)
     77         return frames
     78 

/opt/conda/lib/python3.7/site-packages/msgpack/__init__.py in packb(o, **kwargs)
     36     See :class:`Packer` for options.
     37     """
---> 38     return Packer(**kwargs).pack(o)
     39 
     40 

msgpack/_packer.pyx in msgpack._cmsgpack.Packer.pack()

msgpack/_packer.pyx in msgpack._cmsgpack.Packer.pack()

msgpack/_packer.pyx in msgpack._cmsgpack.Packer.pack()

msgpack/_packer.pyx in msgpack._cmsgpack.Packer._pack()

msgpack/_packer.pyx in msgpack._cmsgpack.Packer._pack()

msgpack/_packer.pyx in msgpack._cmsgpack.Packer._pack()

/opt/conda/lib/python3.7/site-packages/distributed/protocol/core.py in _encode_default(obj)
     60                         on_error=on_error,
     61                         context=context,
---> 62                         size=frame_split_size,
     63                     )
     64                     _inplace_compress_frames(sub_header, sub_frames)

/opt/conda/lib/python3.7/site-packages/distributed/protocol/serialize.py in serialize_and_split(x, serializers, on_error, context, size)
    433     merge_and_deserialize
    434     """
--> 435     header, frames = serialize(x, serializers, on_error, context)
    436     num_sub_frames = []
    437     offsets = []

/opt/conda/lib/python3.7/site-packages/distributed/protocol/serialize.py in serialize(x, serializers, on_error, context, iterate_collection)
    265             on_error=on_error,
    266             context=context,
--> 267             iterate_collection=True,
    268         )
    269 

/opt/conda/lib/python3.7/site-packages/distributed/protocol/serialize.py in serialize(x, serializers, on_error, context, iterate_collection)
    357         return {"serializer": "error"}, frames
    358     elif on_error == "raise":
--> 359         raise TypeError(msg, str(x)[:10000])
    360 
    361 

TypeError: ('Could not serialize object of type function.', '<function PandasDataframe._reorder_labels.<locals>.<lambda> at 0x7f5b54920b00>')
```
</details>

**What you expected to happen**:

To see the sample

**Minimal Complete Verifiable Example**:

```python
import modin.pandas as pd
import swifter
from modin.config import Engine
Engine.put("dask")

from dask.distributed import Client
client = Client(n_workers=5)

import numpy as np

frame_data = np.random.randint(0, 100, size=(2**10, 2**8))
df = pd.DataFrame(frame_data)

df.sample(5)
```

**Anything else we need to know?**:

**Environment**:

- Dask version: modin==0.12.1, dask==2022.2.0
- Python version: 3.7
- Operating System: Ubuntu
- Install method (conda, pip, source): pip

<details>
<summary>Cluster Dump State:</summary>

</details>

**Comment by cristianmtr** [comment]
Not supported on 3.8, it seems

```
ERROR: Ignored the following versions that require a different python version: 2022.2.1 Requires-Python >=3.8; 2022.3.0 Requires-Python >=3.8; 2022.4.0 Requires-Python >=3.8; 2022.4.1 Requires-Python >=3.8; 2022.4.2 Requires-Python >=3.8; 2022.5.0 Requires-Python >=3.8; 2022.5.1 Requires-Python >=3.8; 2022.5.2 Requires-Python >=3.8; 2022.6.0 Requires-Python >=3.8
ERROR: Could not find a version that satisfies the requirement dask==2022.6.0 (from versions: 0.7.4.linux-x86_64, 0.7.5.linux-x86_64, 0.7.6.linux-x86_64, 0.8.1.macosx-10.5-x86_64, 0.2.0, 0.2.1, 0.2.2, 0.2.3, 0.2.4, 0.2.5, 0.2.6, 0.3.0, 0.4.0, 0.5.0, 0.6.0, 0.6.1, 0.7.0, 0.7.1, 0.7.2, 0.7.3, 0.7.4, 0.7.5, 0.7.6, 0.8.0, 0.8.1, 0.8.2, 0.9.0, 0.10.0, 0.10.1, 0.10.2, 0.11.0, 0.11.1, 0.12.0, 0.13.0rc1, 0.13.0, 0.14.0, 0.14.1, 0.14.2, 0.14.3, 0.15.0, 0.15.1, 0.15.2, 0.15.3, 0.15.4, 0.16.0, 0.16.1, 0.17.0, 0.17.1, 0.17.2, 0.17.3, 0.17.4, 0.17.5, 0.18.0, 0.18.1, 0.18.2, 0.19.0, 0.19.1, 0.19.2, 0.19.3, 0.19.4, 0.20.0, 0.20.1, 0.20.2, 1.0.0, 1.1.0, 1.1.1, 1.1.2, 1.1.3, 1.1.4, 1.1.5, 1.2.0, 1.2.1, 1.2.2, 2.0.0, 2.1.0, 2.2.0, 2.3.0, 2.4.0, 2.5.0, 2.5.2, 2.6.0, 2.7.0, 2.8.0, 2.8.1, 2.9.0, 2.9.1, 2.9.2, 2.10.0, 2.10.1, 2.11.0, 2.12.0, 2.13.0, 2.14.0, 2.15.0, 2.16.0, 2.17.0, 2.17.1, 2.17.2, 2.18.0, 2.18.1, 2.19.0, 2.20.0, 2.21.0, 2.22.0, 2.23.0, 2.24.0, 2.25.0, 2.26.0, 2.27.0, 2.28.0, 2.29.0, 2.30.0, 2020.12.0, 2021.1.0, 2021.1.1, 2021.2.0, 2021.3.0, 2021.3.1, 2021.4.0, 2021.4.1, 2021.5.0, 2021.5.1, 2021.6.0, 2021.6.1, 2021.6.2, 2021.7.0, 2021.7.1, 2021.7.2, 2021.8.0, 2021.8.1, 2021.9.0, 2021.9.1, 2021.10.0, 2021.11.0, 2021.11.1, 2021.11.2, 2021.12.0, 2022.1.0, 2022.1.1, 2022.2.0)
ERROR: No matching distribution found for dask==2022.6.0
```

**Comment by pavithraes** [comment]
@cristianmtr Welcome to Dask!

As `@quasiben` suggested, I tried your code locally with the latest Dask, and it does seem to work.

How are you installing/updating Dask? Dask [doesn't support Python 3.7 anymore](https://docs.dask.org/en/stable/changelog.html#v2022-02-1), but python=3.8 should work.

**Comment by jrbourbeau** [comment]
FWIW I'm not able to reproduce the error locally when I use a fresh conda environment created with 

```
mamba create -n test python=3.7 dask=2022.2.0 modin=0.12.1 swifter
```

and run the following script

```python
if __name__ == "__main__":
    import modin.pandas as pd
    import swifter
    from modin.config import Engine
    Engine.put("dask")

    from dask.distributed import Client
    client = Client(n_workers=5)

    import numpy as np

    frame_data = np.random.randint(0, 100, size=(2**10, 2**8))
    df = pd.DataFrame(frame_data)

    print(df.sample(5))
```

which outputs 

```
dask.__version__ = 2022.02.0
distributed.__version__ = 2022.02.0
modin.__version__ = 0.12.1
swifter.__version__ = 1.1.3
UserWarning: Distributing <class 'numpy.ndarray'> object. This may take some time.
     0    1    2    3    4    5    6    7    8    9    10   245  246  247  248  249  250  251  252  253  254  255
581   88   25   18   46   56   36    2   30   60   76   39   67   97   33   90    8   46   59   78    5   55   70
480   43   18   24    8   54   19   87   39    4   74   67   87   22   58   23   67   53    1   95   32   68   42
52    29   37    2   15   46   88   12   73   93   26   79   78   95   41   84   40   48   94   44    7   29   37
122    1   29   25   25   33   86    6   49   29    7   93   19   74   35   65   68   90   45   59   24   80   13
817   91   94   60   44   31   46   48   51   40   17   36   67   93    7   37   34   63   78   79   67   76   20

[5 rows x 256 columns]
```

@cristianmtr can you confirm whether the steps above also work for you too?

**Comment by cristianmtr** [comment]
they work locally, but not on this remote machine. I guess there must be something wrong with the setup of it.
