### ISSUE TITLE
Windows CI failure during conda setup

### ISSUE THREAD

**Issue by jrbourbeau** [dask/dask#9195]
We're consistently seeing 

```python
     Traceback (most recent call last):
      File "C:\Miniconda3\lib\site-packages\conda\_vendor\boltons\setutils.py", line 206, in remove
        didx = self.item_index_map.pop(item)
    KeyError: PackageRecord(_hash=8557279097056026566, name='__win', version='0', build='0', build_number=0, channel=Channel("@"), subdir='win-64', fn='__win', md5='12345678901234567890123456789012', package_type='virtual_system')
    During handling of the above exception, another exception occurred:
    Traceback (most recent call last):
      File "C:\Miniconda3\lib\site-packages\conda\exceptions.py", line 1082, in __call__
        return func(*args, **kwargs)
      File "C:\Miniconda3\lib\site-packages\mamba\mamba.py", line 951, in exception_converter
        raise e
      File "C:\Miniconda3\lib\site-packages\mamba\mamba.py", line 945, in exception_converter
        exit_code = _wrapped_main(*args, **kwargs)
      File "C:\Miniconda3\lib\site-packages\mamba\mamba.py", line 901, in _wrapped_main
        result = do_call(args, p)
      File "C:\Miniconda3\lib\site-packages\mamba\mamba.py", line 765, in do_call
        exit_code = remove(args, parser)
      File "C:\Miniconda3\lib\site-packages\mamba\mamba.py", line 247, in remove
        conda_transaction = to_txn(
      File "C:\Miniconda3\lib\site-packages\mamba\utils.py", line 425, in to_txn
        final_precs = compute_final_precs(
      File "C:\Miniconda3\lib\site-packages\mamba\utils.py", line 360, in compute_final_precs
        final_precs.remove(i_rec)
      File "C:\Miniconda3\lib\site-packages\conda\_vendor\boltons\setutils.py", line 208, in remove
        raise KeyError(item)
    KeyError: PackageRecord(_hash=8557279097056026566, name='__win', version='0', build='0', build_number=0, channel=Channel("@"), subdir='win-64', fn='__win', md5='12345678901234567890123456789012', package_type='virtual_system')
```

in CI during this step in our test workflow

https://github.com/dask/dask/blob/6b0b297046bbc8aa61ea5ee2304b3dc968f857f5/.github/workflows/tests.yml#L57

`distributed` is seeing similar behavior as well (xref https://github.com/dask/distributed/issues/6592)

**Comment by jrbourbeau** [comment]
@jakirkham not sure if that error message had any meaning to you. Any idea what might be happening here?

**Comment by crusaderky** [comment]
The issue is still present in dask/dask with ipython 8.4.0, but it doesn't affect dask/distributed anymore

```
worker 'gw2' crashed while running 'dask/tests/test_base.py::test_tokenize_object_with_recursion_error'
```
