### ISSUE TITLE
Ambiguous column name for sql queries with joins

### ISSUE THREAD

**Issue by f-hafner** [dask/dask#9214]
I get a `sqlite3.OperationalError` when doing `read_sql_query` from a sqlite database with a join, but it seems work with pandas. 

**Example:**

```python
import dask.dataframe as dd
from sqlalchemy.sql import select
import sqlalchemy as sa
import pandas as pd
import os 

# generate empty db, make engine
dbname = "db.sqlite"
open(dbname, 'a').close()
path = os.getcwd()
db_uri = "sqlite:///" + path + "/" + dbname

engine = sa.create_engine(db_uri)

# generate two tables, add to db
df1 = pd.DataFrame(data = {'id': [1, 2, 3, 4], 'value1': [10, 20, 30, 40]})
df2 = pd.DataFrame(data = {'id': [4, 3, 2, 1], 'value2': [50, 60, 70, 80]})

df1.to_sql('table1', con=engine)
df2.to_sql('table2', con=engine)

# check
engine.execute("select * from table1 inner join table2 using(id)").fetchall() # works 

# prepare queries
metadata = sa.MetaData()
table1 = sa.Table("table1", metadata, autoload_with = engine)
table2 = sa.Table("table2", metadata, autoload_with = engine)

query = (select(table1.c.id, table1.c.value1, table2.c.value2).
        select_from(table1).
        join(table2, table1.c.id == table2.c.id))


# make queries 
pd_df = pd.read_sql(con = db_uri, sql = query, index_col = "id")
pd_df.head() # works 
dask_df = dd.read_sql_query(con = db_uri, sql = query, index_col = "id")
dask_df.head() # fails 
```

**Traceback:**
```python-traceback
Traceback (most recent call last):
  File "/home/flavio/.local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1819, in _execute_context
    self.dialect.do_execute(
  File "/home/flavio/.local/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 732, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: ambiguous column name: id

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/flavio/.local/lib/python3.10/site-packages/dask/dataframe/core.py", line 1225, in head
    return self._head(n=n, npartitions=npartitions, compute=compute, safe=safe)
  File "/home/flavio/.local/lib/python3.10/site-packages/dask/dataframe/core.py", line 1259, in _head
    result = result.compute()
  File "/home/flavio/.local/lib/python3.10/site-packages/dask/base.py", line 312, in compute
    (result,) = compute(self, traverse=False, **kwargs)
  File "/home/flavio/.local/lib/python3.10/site-packages/dask/base.py", line 600, in compute
    results = schedule(dsk, keys, **kwargs)
  File "/home/flavio/.local/lib/python3.10/site-packages/dask/threaded.py", line 81, in get
    results = get_async(
  File "/home/flavio/.local/lib/python3.10/site-packages/dask/local.py", line 508, in get_async
    raise_exception(exc, tb)
  File "/home/flavio/.local/lib/python3.10/site-packages/dask/local.py", line 316, in reraise
    raise exc
  File "/home/flavio/.local/lib/python3.10/site-packages/dask/local.py", line 221, in execute_task
    result = _execute_task(task, data)
  File "/home/flavio/.local/lib/python3.10/site-packages/dask/core.py", line 119, in _execute_task
    return func(*(_execute_task(a, cache) for a in args))
  File "/home/flavio/.local/lib/python3.10/site-packages/dask/utils.py", line 41, in apply
    return func(*args, **kwargs)
  File "/home/flavio/.local/lib/python3.10/site-packages/dask/dataframe/io/sql.py", line 423, in _read_sql_chunk
    df = pd.read_sql(q, engine, **kwargs)
  File "/home/flavio/.local/lib/python3.10/site-packages/pandas/io/sql.py", line 592, in read_sql
    return pandas_sql.read_query(
  File "/home/flavio/.local/lib/python3.10/site-packages/pandas/io/sql.py", line 1557, in read_query
    result = self.execute(*args)
  File "/home/flavio/.local/lib/python3.10/site-packages/pandas/io/sql.py", line 1402, in execute
    return self.connectable.execution_options().execute(*args, **kwargs)
  File "<string>", line 2, in execute
  File "/home/flavio/.local/lib/python3.10/site-packages/sqlalchemy/util/deprecations.py", line 402, in warned
    return fn(*args, **kwargs)
  File "/home/flavio/.local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 3176, in execute
    return connection.execute(statement, *multiparams, **params)
  File "/home/flavio/.local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1306, in execute
    return meth(self, multiparams, params, _EMPTY_EXECUTION_OPTS)
  File "/home/flavio/.local/lib/python3.10/site-packages/sqlalchemy/sql/elements.py", line 332, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/home/flavio/.local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1498, in _execute_clauseelement
    ret = self._execute_context(
  File "/home/flavio/.local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1862, in _execute_context
    self._handle_dbapi_exception(
  File "/home/flavio/.local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2043, in _handle_dbapi_exception
    util.raise_(
  File "/home/flavio/.local/lib/python3.10/site-packages/sqlalchemy/util/compat.py", line 208, in raise_
    raise exception
  File "/home/flavio/.local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1819, in _execute_context
    self.dialect.do_execute(
  File "/home/flavio/.local/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 732, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) ambiguous column name: id
[SQL: SELECT table1.id, table1.value1, table2.value2 
FROM table1 JOIN table2 ON table1.id = table2.id 
WHERE id >= ? AND id <= ?]
[parameters: (1, 4)]
(Background on this error at: https://sqlalche.me/e/14/e3q8)

```
I have little experience with dask and sqlalchemy, but I suspect it has to do with https://github.com/dask/dask/blob/95fdd3fe127fe116e02c222c3d38303c3375af4b/dask/dataframe/io/sql.py#L170.

and the sql query should include the table name, as in:
```python
[SQL: SELECT table1.id, table1.value1, table2.value2 
FROM table1 JOIN table2 ON table1.id = table2.id 
WHERE table1.id >= ? AND table1.id <= ?]
[parameters: (1, 4)]
```

**Environment**:

- Dask version:  2022.6.0
- Python version: 3.10.4
- Operating System: ubuntu 22.04
- Install method (conda, pip, source): pip

**Comment by pavithraes** [comment]
@f-hafner Welcome to Dask, and thanks for a well-written bug report! I can reproduce this. :)

**Comment by ian-r-rose** [comment]
Hi @f-hafner, thanks for the report.

The way Dask handles SQL queries is by assuming we have an indexed column that we can easily and quickly partition along. Internally, we create a series of sub-queries based upon your initial query that gets subsets of the data for each partition. This is the snippet that you correctly identified as the problem. This is quite difficult to do in general, and you've come across one limitation -- if the `index_col` that you specify doesn't unambiguously refer to a column in the result, sqlalchemy rightfully complains.

I'm not sure if I can see a good way for Dask to handle all SQLAlchemy queries which might be based on arbitrarily complex subqueries. But I do think we can solve your particular use-case by ensuring that we unambiguously refer to the index column in your *resulting* joined table. Here I rename the resulting index column to `"result_id"`, then partition along that:

```python
query = (select(table1.c.id.label("result_id"), table1.c.value1, table2.c.value2).
        select_from(table1).
        join(table2, table1.c.id == table2.c.id))

dask_df = dd.read_sql_query(con = db_uri, sql = query, index_col = "result_id")
dask_df.head() # succeeds! 
```

This works with both pandas and Dask. Does that seem like a reasonable way forwards for your use-case?

**Comment by ian-r-rose** [comment]
Some more docs on how dask handles SQL indexes and SQLAlchemy expressions can be found [here](https://docs.dask.org/en/stable/dataframe-sql.html#index-column), in case you are not already aware of it.

**Comment by f-hafner** [comment]
Hi @ian-r-rose. I had not been thinking far enough to try to rename the column, but that works well for my use-case. Thanks!

**Comment by chilligerchief** [comment]
Is there also a solution for postgresql, since it does not support column aliases in where clauses?
If I use the same approach with postgres, i always get 

`sqlalchemy.exc.ProgrammingError: (psycopg2.errors.UndefinedColumn) column "result_id" does not exist LINE 3`

Any help would be appreciated!
