### ISSUE TITLE
Int64Index operations not working

### ISSUE THREAD

**Issue by DominiqueGarmier** [dask/dask#9253]
```python
>>> import pandas as pd
>>> import dask.dataframe as dd
>>> a
   a  b
1  1  3
2  2  4
>>> a = pd.DataFrame(data={'a': [1, 2], 'b': [3, 4]}, index=[1,2])
>>> a[a.index > 1]  # works as expected
   a  b
2  2  4
>>> b = dd.from_pandas(a, npartitions=1)
>>> b[b.index > 1].compute()  # crashes
>>> b[b.a > 1].compute()  # works
   a  b
2  2  4
```
I get the following error:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/****/.venv/lib/python3.10/site-packages/dask/dataframe/core.py", line 4458, in __getitem__
    raise NotImplementedError(key)
NotImplementedError: dask.array<gt, shape=(nan,), dtype=bool, chunksize=(nan,), chunktype=numpy.ndarray>
```
with these dependencies
```
dask==2022.6.1
numpy==1.23.0
pandas==1.4.3
```

**Comment by DominiqueGarmier** [comment]
im sorry, the correct way of doing it `b.loc[b.index ? 1].compute()`. Not sure why I didn't find this earlier.
