### ISSUE TITLE
get_dummies error: order of columns does not match

### ISSUE THREAD

**Issue by lodo1995** [dask/dask#9258]
**What happened**:
When applying `categorize` and then `get_dummies` to columns that originally had a numerical data type, in some cases `get_dummies` fails with
```
ValueError: The columns in the computed data do not match the columns in the provided metadata
Order of columns does not match
```

I could not find the exact pattern behind these failures (happens on real-world data only on some columns, with no clear pattern), but I managed to produce a tiny example that exhibits the issue.

**What you expected to happen**:
`get_dummies` works without exceptions.

**Minimal Complete Verifiable Example**:

```python
import pandas as pd
import dask.dataframe as dd

data = pd.DataFrame(data={
    'a': [0.0, 0.0, 1.0, 1.0, 0.0],
    'b': [1.0, 0.0, 1.0, 0.0, 1.0]
})

data = dd.from_pandas(data, npartitions=2)

CAT = ['a', 'b']
data[CAT] = data[CAT].categorize(CAT)

dd.get_dummies(data[CAT]).compute()
```

**Traceback**:
```
Traceback (most recent call last):
  File "<redacted>/src/test_dd.py", line 16, in <module>
    dd.get_dummies(data[CAT]).compute()
  File "<redacted>/lib/python3.9/site-packages/dask/base.py", line 292, in compute
    (result,) = compute(self, traverse=False, **kwargs)
  File "<redacted>/lib/python3.9/site-packages/dask/base.py", line 575, in compute
    results = schedule(dsk, keys, **kwargs)
  File "<redacted>/lib/python3.9/site-packages/dask/threaded.py", line 81, in get
    results = get_async(
  File "<redacted>/lib/python3.9/site-packages/dask/local.py", line 508, in get_async
    raise_exception(exc, tb)
  File "<redacted>/lib/python3.9/site-packages/dask/local.py", line 316, in reraise
    raise exc
  File "<redacted>/lib/python3.9/site-packages/dask/local.py", line 221, in execute_task
    result = _execute_task(task, data)
  File "<redacted>/lib/python3.9/site-packages/dask/core.py", line 119, in _execute_task
    return func(*(_execute_task(a, cache) for a in args))
  File "<redacted>/lib/python3.9/site-packages/dask/optimization.py", line 990, in __call__
    return core.get(self.dsk, self.outkey, dict(zip(self.inkeys, args)))
  File "<redacted>/lib/python3.9/site-packages/dask/core.py", line 149, in get
    result = _execute_task(task, cache)
  File "<redacted>/lib/python3.9/site-packages/dask/core.py", line 119, in _execute_task
    return func(*(_execute_task(a, cache) for a in args))
  File "<redacted>/lib/python3.9/site-packages/dask/utils.py", line 40, in apply
    return func(*args, **kwargs)
  File "<redacted>/lib/python3.9/site-packages/dask/dataframe/core.py", line 6436, in apply_and_enforce
    check_matching_columns(meta, df)
  File "<redacted>/lib/python3.9/site-packages/dask/dataframe/utils.py", line 415, in check_matching_columns
    raise ValueError(
ValueError: The columns in the computed data do not match the columns in the provided metadata
Order of columns does not match
```

**Environment**:

- Dask version: 2022.05.00
- Python version: 3.9.12
- Operating System: Ubuntu 20.04
- Install method (conda, pip, source): conda

**Comment by pavithraes** [comment]
@lodo1995 Thanks for reporting! This does look like a bug, and I've opened a PR (with @ian-r-rose's help) to fix it. :)
