### ISSUE TITLE
Memory usage TypeError with Index

### ISSUE THREAD

**Issue by SrSoto** [dask/dask#9286]
Dask's `memory_usage` function is giving a `TypeError` depending on the order we call `compute` and `memory_usage`. I am concerned this function is rarely of direct usage, but we were doing some tests with Dask's `sizeof` function and metrics of managed and unmanaged memory (we are spotting some differences between estimated sizes that I'll give report soon)

The following MCVE tries to compare `memory_usage` call before and after callling `compute` but fails on Dask case.

```python
import pandas as pd
from dask.dataframe import from_pandas
ser = pd.Series([f"2020-01-{i}" for i in range(1,10)])
ser_ts = ser.astype("datetime64[ns]")
df = pd.DataFrame({'a': ser, 'b': ser_ts}).set_index('b')
ddf = from_pandas(df, npartitions=2)
print("-- memory_usage on Pandas DataFrame --")
print(ddf.compute().memory_usage())
print("-- memory_usage on Dask DataFrame --")
print(ddf.memory_usage().compute())
print("-- memory_usage on Pandas Index --")
print(ddf.compute().index.memory_usage())
print("-- memory_usage on Dask Index --")
print(ddf.index.memory_usage().compute())
```

Executing this code leads to the following exception:

```python
TypeError: memory_usage() got an unexpected keyword argument 'index'
```

<details>
<summary>Full traceback</summary>

```python
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
~/anaconda3/envs/3.9testing/lib/python3.9/site-packages/dask/dataframe/utils.py in raise_on_meta_error(funcname, udf)
    181     try:
--> 182         yield
    183     except Exception as e:

~/anaconda3/envs/3.9testing/lib/python3.9/site-packages/dask/dataframe/core.py in _emulate(func, udf, *args, **kwargs)
   6348     with raise_on_meta_error(funcname(func), udf=udf):
-> 6349         return func(*_extract_meta(args, True), **_extract_meta(kwargs, True))
   6350 

~/anaconda3/envs/3.9testing/lib/python3.9/site-packages/dask/utils.py in __call__(self, _methodcaller__obj, *args, **kwargs)
   1052     def __call__(self, __obj, *args, **kwargs):
-> 1053         return getattr(__obj, self.method)(*args, **kwargs)
   1054 

TypeError: memory_usage() got an unexpected keyword argument 'index'

The above exception was the direct cause of the following exception:

ValueError                                Traceback (most recent call last)
<ipython-input-46-8a9d393d6d85> in <module>
     12 print(ddf.compute().index.memory_usage())
     13 print("-- memory_usage on Dask Index --")
---> 14 print(ddf.index.memory_usage().compute())

~/anaconda3/envs/3.9testing/lib/python3.9/site-packages/dask/dataframe/core.py in memory_usage(self, index, deep)
   3990     @derived_from(pd.Series)
   3991     def memory_usage(self, index=True, deep=False):
-> 3992         result = self.map_partitions(
   3993             M.memory_usage, index=index, deep=deep, enforce_metadata=False
   3994         )

~/anaconda3/envs/3.9testing/lib/python3.9/site-packages/dask/dataframe/core.py in map_partitions(self, func, *args, **kwargs)
    855         None as the division.
    856         """
--> 857         return map_partitions(func, self, *args, **kwargs)
    858 
    859     @insert_meta_param_description(pad=12)

~/anaconda3/envs/3.9testing/lib/python3.9/site-packages/dask/dataframe/core.py in map_partitions(func, meta, enforce_metadata, transform_divisions, align_dataframes, *args, **kwargs)
   6422         # Use non-normalized kwargs here, as we want the real values (not
   6423         # delayed values)
-> 6424         meta = _emulate(func, *args, udf=True, **kwargs)
   6425         meta_is_emulated = True
   6426     else:

~/anaconda3/envs/3.9testing/lib/python3.9/site-packages/dask/dataframe/core.py in _emulate(func, udf, *args, **kwargs)
   6347     """
   6348     with raise_on_meta_error(funcname(func), udf=udf):
-> 6349         return func(*_extract_meta(args, True), **_extract_meta(kwargs, True))
   6350 
   6351 

~/anaconda3/envs/3.9testing/lib/python3.9/contextlib.py in __exit__(self, typ, value, traceback)
    135                 value = typ()
    136             try:
--> 137                 self.gen.throw(typ, value, traceback)
    138             except StopIteration as exc:
    139                 # Suppress StopIteration *unless* it's the same exception that

~/anaconda3/envs/3.9testing/lib/python3.9/site-packages/dask/dataframe/utils.py in raise_on_meta_error(funcname, udf)
    201         )
    202         msg = msg.format(f" in `{funcname}`" if funcname else "", repr(e), tb)
--> 203         raise ValueError(msg) from e
    204 
    205 

ValueError: Metadata inference failed in `memory_usage`.

You have supplied a custom function and Dask is unable to 
determine the type of output that that function returns. 

To resolve this please provide a meta= keyword.
The docstring of the Dask function you ran should have more information.

Original error is below:
------------------------
TypeError("memory_usage() got an unexpected keyword argument 'index'")

Traceback:
---------
  File "/home/manuel.soto/anaconda3/envs/3.9testing/lib/python3.9/site-packages/dask/dataframe/utils.py", line 182, in raise_on_meta_error
    yield
  File "/home/manuel.soto/anaconda3/envs/3.9testing/lib/python3.9/site-packages/dask/dataframe/core.py", line 6349, in _emulate
    return func(*_extract_meta(args, True), **_extract_meta(kwargs, True))
  File "/home/manuel.soto/anaconda3/envs/3.9testing/lib/python3.9/site-packages/dask/utils.py", line 1053, in __call__
    return getattr(__obj, self.method)(*args, **kwargs)
```
</details>

Studying `memory_usage` code, it is possible that this problem is caused by an incorrect delegation of this method, calling the function of `memory_usage` from a `Series` instead of an `Index`, as the `index` argument has no sense in the second case (this may be because of the `MethodCache` calling the incorrect found function).

**Environment**:

- Dask version: 2022.6.0
- Python version: 3.9.7
- Operating System: Ubuntu 21.04
- Install method (conda, pip, source): pip

**Comment by jrbourbeau** [comment]
Thanks for opening up this issue and providing a nice minimal reproducer @SrSoto. I just pushed up https://github.com/dask/dask/pull/9290 which should fix Dask's `Index.memory_usage`

**Comment by jrbourbeau** [comment]
Closed via https://github.com/dask/dask/pull/9290
