### ISSUE TITLE
Exception after merging two dataframes on index

### ISSUE THREAD

**Issue by billiejoe-bw** [dask/dask#9294]
**What happened**:

After I merge two data frames on their index, then `reset_index` and try to access the column that was the index, I get an exception.

**Minimal Complete Verifiable Example**:

```python
import pandas as pd
import dask
import dask.dataframe as dd

A_df = dd.from_pandas(
    pd.DataFrame(
        [('aaa', 10), ('bbb', 20)],
        columns=['string_key_A', 'value1']
    ),
    npartitions=1
).set_index('string_key_A')

B_df = dd.from_pandas(
    pd.DataFrame(
        [('aaa', 100)],
        columns=['string_key_B', 'value2']
    ),
    npartitions=1
).set_index('string_key_B')

print(A_df.compute())
print()

print(B_df.compute())
print()

merged_df = dd.merge(A_df, B_df, left_index=True, right_index=True).reset_index()

print(merged_df)
print()

print(merged_df.dtypes)
print()

print(merged_df.compute())
print()

print(merged_df['string_key_A'])
print()

print(merged_df['string_key_A'].compute())
```

Here's the output I get, including the traceback:

```              value1
string_key_A
aaa               10
bbb               20

              value2
string_key_B
aaa              100

Dask DataFrame Structure:
              string_key_A value1 value2
npartitions=1
                    object  int64  int64
                       ...    ...    ...
Dask Name: reset_index, 13 tasks

string_key_A    object
value1           int64
value2           int64
dtype: object

  index  value1  value2
0   aaa      10     100

Dask Series Structure:
npartitions=1
    object
       ...
Name: string_key_A, dtype: object
Dask Name: getitem, 14 tasks

Traceback (most recent call last):
  File "/home/ubuntu/.cache/pypoetry/virtualenvs/bug-TT33av2A-py3.9/lib/python3.9/site-packages/pandas/core/indexes/base.py", line 3621, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas/_libs/index.pyx", line 136, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 163, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 5198, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 5206, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'string_key_A'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ubuntu/bug/bug.py", line 42, in <module>
    print(merged_df['string_key_A'].compute())
  File "/home/ubuntu/.cache/pypoetry/virtualenvs/bug-TT33av2A-py3.9/lib/python3.9/site-packages/dask/base.py", line 315, in compute
    (result,) = compute(self, traverse=False, **kwargs)
  File "/home/ubuntu/.cache/pypoetry/virtualenvs/bug-TT33av2A-py3.9/lib/python3.9/site-packages/dask/base.py", line 603, in compute
    results = schedule(dsk, keys, **kwargs)
  File "/home/ubuntu/.cache/pypoetry/virtualenvs/bug-TT33av2A-py3.9/lib/python3.9/site-packages/dask/threaded.py", line 89, in get
    results = get_async(
  File "/home/ubuntu/.cache/pypoetry/virtualenvs/bug-TT33av2A-py3.9/lib/python3.9/site-packages/dask/local.py", line 511, in get_async
    raise_exception(exc, tb)
  File "/home/ubuntu/.cache/pypoetry/virtualenvs/bug-TT33av2A-py3.9/lib/python3.9/site-packages/dask/local.py", line 319, in reraise
    raise exc
  File "/home/ubuntu/.cache/pypoetry/virtualenvs/bug-TT33av2A-py3.9/lib/python3.9/site-packages/dask/local.py", line 224, in execute_task
    result = _execute_task(task, data)
  File "/home/ubuntu/.cache/pypoetry/virtualenvs/bug-TT33av2A-py3.9/lib/python3.9/site-packages/dask/core.py", line 119, in _execute_task
    return func(*(_execute_task(a, cache) for a in args))
  File "/home/ubuntu/.cache/pypoetry/virtualenvs/bug-TT33av2A-py3.9/lib/python3.9/site-packages/dask/optimization.py", line 990, in __call__
    return core.get(self.dsk, self.outkey, dict(zip(self.inkeys, args)))
  File "/home/ubuntu/.cache/pypoetry/virtualenvs/bug-TT33av2A-py3.9/lib/python3.9/site-packages/dask/core.py", line 149, in get
    result = _execute_task(task, cache)
  File "/home/ubuntu/.cache/pypoetry/virtualenvs/bug-TT33av2A-py3.9/lib/python3.9/site-packages/dask/core.py", line 119, in _execute_task
    return func(*(_execute_task(a, cache) for a in args))
  File "/home/ubuntu/.cache/pypoetry/virtualenvs/bug-TT33av2A-py3.9/lib/python3.9/site-packages/pandas/core/frame.py", line 3505, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/home/ubuntu/.cache/pypoetry/virtualenvs/bug-TT33av2A-py3.9/lib/python3.9/site-packages/pandas/core/indexes/base.py", line 3623, in get_loc
    raise KeyError(key) from err
KeyError: 'string_key_A'
```

**Anything else we need to know?**:

It looks like the problem is that after the `merge`, the metadata thinks that the index (now turned into a regular column by `reset_index`) is called `string_key_A` but when you actually compute to a pandas dataframe, it's called `index`. This causes things to crash later.

Interestingly if you call the column the same thing e.g. just `string_key` in both dataframes before you `merge` them, the same problem doesn't arise.

**Environment**:

Dask version: 2022.7.0
Python version: 3.9.7
Operating System: Ubuntu 20.04.3 LTS
Install method: poetry

**Comment by pavithraes** [comment]
@billiejoe-bw Thanks for reporting!

When we call `compute()`, Dask DataFrame results in the same thing as pandas.

You're right that the metadata inference is what's wrong here. So, the error is valid (pandas raises the same), we need to raise this before `compute` though such that `merged_df['string_key_A']` fails.

**Comment by kutal10** [comment]
@pavithraes @jsignell Hey both - i've been working on this issue for the past few days

### **Approach**

At the minute, i'm looking at comparing the Dask Dataframe metadata to the Pandas equivalent using `compute()` all within the `__getitem__` method. I don't know if this approach is necessarily optimal, but it passes the test cases i've written for it. 

I do acknowledge that maybe:

1. I need to not touch `__getitem__` and I just need to look at adjusting how `_meta` is adjusted by  `reset_index()`
2. Or I need to look at an alternate solution within `__getitem__`

### **Tests**

I've already written out two tests that check when the merged indices are different and when the merged indices are the same, as per @billiejoe-bw examples above.

### **Problem**

The problem with my solution at the minute, is that, no tests fail except one re materialization which keeps failing:

```python
def test_repr_materialize():
    # DataFrame/Series repr should not materialize
    # any layers in timeseries->shuffle->getitem
    s = timeseries(end="2000-01-03").shuffle("id", shuffle="tasks")["id"]
    assert all([not l.is_materialized() for l in s.dask.layers.values()])
    s.__repr__()
    s.to_frame().__repr__()
    assert all([not l.is_materialized() for l in s.dask.layers.values()])
```

I believe, this is because `compute()` always materializes. Even making a deepcopy of the Dask Dataframe within `__getitem__` does not solve this.

Is this the right approach?

**Comment by pavithraes** [comment]
@kutal10 Thanks for working on this! I think you may want to look into how `meta` is created by `merge()` when `left_index=True, right_index=True`. Dask is using `'string_key_A'` as the index column name instead of `'index'`, while creating the meta.

Note that Dask creates the right `meta` here:

```python
merged_df = dd.merge(A_df, B_df, left_on='string_key_A', right_on='string_key_B').reset_index()
print(merged_df)
# Output:
# Dask DataFrame Structure:
#                index value1 value2
# npartitions=1                     
#                int64  int64  int64
#                  ...    ...    ...
# Dask Name: reset_index, 13 tasks
```

So, I might also look at the code path this operation takes. :)

**Comment by jorloplaz** [comment]
Beware, because what is happening here is:

1. When you join on 2 indexes with different names, Pandas sets the result index name to `None`, but not to `'index'`. It's `reset_index()` the one that switches from `None` to `'index'` when `drop=False`.
2. Dask is doing it wrong with `meta`, because it's assuming `index.name` should be `string_key_A`, but it should be `None` instead. And then `string_key_A` doesn't exist anymore (neither as index nor as column, so the `KeyError` can be raised before any `compute()`.
3. This doesn't happen when both indexes are named the same, because in that case both Pandas and Dask keep `index.name` untouched. And when one does `reset_index(drop=False)` later on, that name is preserved as the column name.

So 2) must be corrected, but, aside from that I personally think that Dask should NOT allow doing `reset_index(drop=False)` when `index.name is None`. Introducing a column named `'index'` is a poor approach, because 1) the fact that the index is anonymous should indicate that it was NEVER a column of the original data, but just an auxiliary thing, 2) there may be another column called `'index'` already. This is related to my [recent PR](https://github.com/dask/dask/pull/9422) (which would make point2 fail), and to the discussion going on about [this issue](https://github.com/dask/dask/issues/9380) (which covers point 1).
