### ISSUE TITLE
Simple `cumsum` code is failing for CuPy.

### ISSUE THREAD

**Issue by jcfaracco** [dask/dask#9315]
**What happened**:

A simple code using Dask's `cumsum` function is throwing an issue if the input array is CuPy.

**What you expected to happen**:

A simple code should work fine for Dask.

**Minimal Complete Verifiable Example**:

```python
import cupy as cp
import dask.array as da

A = cp.array([[1,2,3], [4,5,6]])

DA = da.from_array(A, chunks=(1, 1))

DAC = DA.cumsum(axis=0)

DAC.compute()
```

**Anything else we need to know?**:

This is the error below after executing the code above:

```python
Traceback (most recent call last):
  File "/tmp/test_cumsum.py", line 10, in <module>
    DAC.compute()
  File "/root/micromamba/envs/dasf/lib/python3.9/site-packages/dask/base.py", line 312, in compute
    (result,) = compute(self, traverse=False, **kwargs)
  File "/root/micromamba/envs/dasf/lib/python3.9/site-packages/dask/base.py", line 600, in compute
    results = schedule(dsk, keys, **kwargs)
  File "/root/micromamba/envs/dasf/lib/python3.9/site-packages/dask/threaded.py", line 81, in get
    results = get_async(
  File "/root/micromamba/envs/dasf/lib/python3.9/site-packages/dask/local.py", line 508, in get_async
    raise_exception(exc, tb)
  File "/root/micromamba/envs/dasf/lib/python3.9/site-packages/dask/local.py", line 316, in reraise
    raise exc
  File "/root/micromamba/envs/dasf/lib/python3.9/site-packages/dask/local.py", line 221, in execute_task
    result = _execute_task(task, data)
  File "/root/micromamba/envs/dasf/lib/python3.9/site-packages/dask/core.py", line 119, in _execute_task
    return func(*(_execute_task(a, cache) for a in args))
  File "/root/micromamba/envs/dasf/lib/python3.9/site-packages/dask/array/reductions.py", line 1507, in _cumsum_merge
    return a + b
  File "cupy/_core/core.pyx", line 1591, in cupy._core.core.ndarray.__array_ufunc__
  File "cupy/_core/_kernel.pyx", line 1218, in cupy._core._kernel.ufunc.__call__
  File "cupy/_core/_kernel.pyx", line 138, in cupy._core._kernel._preprocess_args
  File "cupy/_core/_kernel.pyx", line 124, in cupy._core._kernel._preprocess_arg
TypeError: Unsupported type <class 'numpy.ndarray'>
```

**Environment**:

- Dask version: 2022.5.2
- Python version: 3.9.13
- CuPy version: 10.6.0
- Operating System: Ubuntu 20.04
- Install method (conda, pip, source): miniconda (see the error output)

**Comment by jcfaracco** [comment]
It sounds that cupy ufunc `add()` does not support numpy which is fair. But the input is a cupy array, so it should not be a problem.

**Comment by GenevieveBuckley** [comment]
I'm also seeing some weirdness in the array type metadata. 

@jcfaracco  can you run this code snippet and tell us what you see?
```python
print(DA._meta)
print(DAC._meta)
```

I see both of these falsely reporting that they are numpy, not cupy.

**Comment by GenevieveBuckley** [comment]
Then I tried this to force the metadata to be what it should look like:
```python
import cupy as cp
import dask.array as da


A = cp.array([[1,2,3], [4,5,6]])
metadata = cp.array([], dtype=A.dtype)
DA = da.from_array(A, chunks=(1, 1), meta=metadata)
print(type(DA._meta))
DAC = DA.cumsum(axis=0)
print(type(DAC._meta))  # still showing numpy, even though we forced DA to have cupy metadata
DAC._meta = metadata  # hacky attempt to fix the metadata problem

DAC.compute()  # still getting an error

```
But there's still some problems, so there's still some extra work to do here.

**Comment by GenevieveBuckley** [comment]
I think I found it!

1. This line has `np.full` in it, creating a numpy specific array:
https://github.com/dask/dask/blob/c98fab7112e92c6455a1e840a0d0f8b6c7ddc55d/dask/array/reductions.py#L1515


2. Less important but still nice to have, would be changing [this line](https://github.com/dask/dask/blob/c98fab7112e92c6455a1e840a0d0f8b6c7ddc55d/dask/array/reductions.py#L1535) to add a `meta=` keyword argument, like this:

```python
    result = Array(graph, name, x.chunks, m.dtype, meta=x._meta)
```
