### ISSUE TITLE
GroupBy get_group KeyError when category and npartitions >1

### ISSUE THREAD

**Issue by ba05** [dask/dask#9359]
Appears there is an issue when using groupby get_group and the group was derived from a pandas categorical type. Only get error when npartitions is >1. Possibly related to #[5847](https://github.com/dask/dask/issues/5847)

````python
def checker(npartitions, toCategory):
    import dask.dataframe as dd
    import pandas as pd

    df = pd.DataFrame({'make':['a','b','c'], 'model': [2,5,7]})
    
    if toCategory:
        df['make'] = df['make'].astype('category')
        
    dd = dd.from_pandas(df, npartitions=npartitions)
    
    gbCol = 'make'
    for g in dd[gbCol].unique().compute():
        dd.groupby(gbCol).get_group(g).min(numeric_only=True).compute()
    return

checker(npartitions=2, toCategory=True)  # doesnt work, KeyError: 'a', 2 partitions
checker(npartitions=2, toCategory=False) # works
checker(npartitions=1, toCategory=True)  # works, only 1 partition
checker(npartitions=1, toCategory=False) # works
````
**Traceback**:
````python-traceback
Traceback (most recent call last):

  File "C:\Users\User1\AppData\Local\Temp\ipykernel_5608\2821702366.py", line 18, in <cell line: 18>
    checker(npartitions=2, toCategory=True)  # doesnt work, KeyError: 'a', 2 partitions

  File "C:\Users\User1\AppData\Local\Temp\ipykernel_5608\2821702366.py", line 15, in checker
    dd.groupby(gbCol).get_group(g).min(numeric_only=True).compute() #get their associated group which is dataframe type

  File "C:\ProgramData\Anaconda3\envs\env3\lib\site-packages\dask\base.py", line 315, in compute
    (result,) = compute(self, traverse=False, **kwargs)

  File "C:\ProgramData\Anaconda3\envs\env3\lib\site-packages\dask\base.py", line 598, in compute
    results = schedule(dsk, keys, **kwargs)

  File "C:\ProgramData\Anaconda3\envs\env3\lib\site-packages\dask\threaded.py", line 89, in get
    results = get_async(

  File "C:\ProgramData\Anaconda3\envs\env3\lib\site-packages\dask\local.py", line 511, in get_async
    raise_exception(exc, tb)

  File "C:\ProgramData\Anaconda3\envs\env3\lib\site-packages\dask\local.py", line 319, in reraise
    raise exc

  File "C:\ProgramData\Anaconda3\envs\env3\lib\site-packages\dask\local.py", line 224, in execute_task
    result = _execute_task(task, data)

  File "C:\ProgramData\Anaconda3\envs\env3\lib\site-packages\dask\core.py", line 119, in _execute_task
    return func(*(_execute_task(a, cache) for a in args))

  File "C:\ProgramData\Anaconda3\envs\env3\lib\site-packages\dask\optimization.py", line 990, in __call__
    return core.get(self.dsk, self.outkey, dict(zip(self.inkeys, args)))

  File "C:\ProgramData\Anaconda3\envs\env3\lib\site-packages\dask\core.py", line 149, in get
    result = _execute_task(task, cache)

  File "C:\ProgramData\Anaconda3\envs\env3\lib\site-packages\dask\core.py", line 119, in _execute_task
    return func(*(_execute_task(a, cache) for a in args))

  File "C:\ProgramData\Anaconda3\envs\env3\lib\site-packages\dask\core.py", line 119, in <genexpr>
    return func(*(_execute_task(a, cache) for a in args))

  File "C:\ProgramData\Anaconda3\envs\env3\lib\site-packages\dask\core.py", line 113, in _execute_task
    return [_execute_task(a, cache) for a in arg]

  File "C:\ProgramData\Anaconda3\envs\env3\lib\site-packages\dask\core.py", line 113, in <listcomp>
    return [_execute_task(a, cache) for a in arg]

  File "C:\ProgramData\Anaconda3\envs\env3\lib\site-packages\dask\core.py", line 119, in _execute_task
    return func(*(_execute_task(a, cache) for a in args))

  File "C:\ProgramData\Anaconda3\envs\env3\lib\site-packages\dask\core.py", line 119, in <genexpr>
    return func(*(_execute_task(a, cache) for a in args))

  File "C:\ProgramData\Anaconda3\envs\env3\lib\site-packages\dask\core.py", line 113, in _execute_task
    return [_execute_task(a, cache) for a in arg]

  File "C:\ProgramData\Anaconda3\envs\env3\lib\site-packages\dask\core.py", line 113, in <listcomp>
    return [_execute_task(a, cache) for a in arg]

  File "C:\ProgramData\Anaconda3\envs\env3\lib\site-packages\dask\core.py", line 119, in _execute_task
    return func(*(_execute_task(a, cache) for a in args))

  File "C:\ProgramData\Anaconda3\envs\env3\lib\site-packages\dask\utils.py", line 71, in apply
    return func(*args, **kwargs)

  File "C:\ProgramData\Anaconda3\envs\env3\lib\site-packages\dask\dataframe\core.py", line 6650, in apply_and_enforce
    df = func(*args, **kwargs)

  File "C:\ProgramData\Anaconda3\envs\env3\lib\site-packages\dask\dataframe\groupby.py", line 239, in _groupby_get_group
    return grouped.get_group(get_key)

  File "C:\ProgramData\Anaconda3\envs\env3\lib\site-packages\pandas\core\groupby\groupby.py", line 747, in get_group
    raise KeyError(name)

KeyError: 'a'
````

**Environment**:

- Dask version: 2022.8.0
- Python version: 3.10
- Operating System: Windows 10
- Install method (conda, pip, source): conda

**Comment by pavithraes** [comment]
@ba05 Thanks for reporting! Your code seems to work with dask=2022.7.1, but fails with the latest release dask=2022.8.0.

The `npartitions` and `divisions` calculated is different between the versions, which might be causing this error:

`dask=2022.7.1`:

```python
import dask.dataframe as dd
import pandas as pd

df = pd.DataFrame({'make':['a','b','c'], 'model': [2,5,7]})    
df['make'] = df['make'].astype('category')

ddf = dd.from_pandas(df, npartitions=2)

ddf.npartitions
# Output = 1

ddf.divisions
# Output = (0, 2)
```

`dask=2022.8.0`:

```python
ddf.npartitions
# Output = 2

ddf.divisions
# Output = (0, 2, 2)
```

I think this might be related to #9221? cc @jrbourbeau @ian-r-rose @rjzamora

**Comment by pavithraes** [comment]
The core issue is in how the categories are represented in Dask. The `make` column always retains metadata about *all* the categories, even if we wish to work only on a single partition.

Continuing from my above code snippet:

```python
for p in ddf.partitions:
    print(p.make.compute())

# Output:
# 
# 0    a
# 1    b
# 2    c
# Name: make, dtype: category
# Categories (6, object): ['a', 'b', 'c', 'd', 'e', 'f']
# 3    d
# 4    e
# 5    f
# Name: make, dtype: category
# Categories (6, object): ['a', 'b', 'c', 'd', 'e', 'f']
```

Since the metadata has all the groups, we see that the `else` block on line 242 is never reached:

https://github.com/dask/dask/blob/bf66221722cce8f09a9b09895bdb4596f14a5430/dask/dataframe/groupby.py#L233-L248

But, instead, the control always enters the `if` blocks and raises a `KeyError` when it can't find the `a` in the second partition which actually doesn't have `a`.
