### ISSUE TITLE
Dask Dataframe does not support Pandas dtype 'Float32'

### ISSUE THREAD

**Issue by Tishj** [dask/dask#9401]
```py
pd_df = pd.DataFrame({
		'float32': pd.Series([None, 1, 4294967295], dtype="Float32"),
		'float64': pd.Series([None, 1, 18446744073709551615], dtype="Float64")}
)

dd_df = dd.from_pandas(pd_df, npartitions=10)
print(dd_df['float32'].values)
# This last line caused the crash
```

**What happened**:
```
Traceback (most recent call last):
  File "dask_test.py", line 17, in <module>
    print(dd_df['float32'].values)
  File "/opt/homebrew/lib/python3.9/site-packages/dask/dataframe/core.py", line 3324, in values
    return self.map_partitions(methods.values)
  File "/opt/homebrew/lib/python3.9/site-packages/dask/dataframe/core.py", line 867, in map_partitions
    return map_partitions(func, self, *args, **kwargs)
  File "/opt/homebrew/lib/python3.9/site-packages/dask/dataframe/core.py", line 6578, in map_partitions
    return new_dd_object(graph, name, meta, divisions)
  File "/opt/homebrew/lib/python3.9/site-packages/dask/dataframe/core.py", line 7706, in new_dd_object
    return da.Array(dsk, name=name, chunks=chunks, dtype=meta.dtype)
  File "/opt/homebrew/lib/python3.9/site-packages/dask/array/core.py", line 1329, in __new__
    meta = meta_from_array(meta, dtype=dtype)
  File "/opt/homebrew/lib/python3.9/site-packages/dask/array/utils.py", line 57, in meta_from_array
    x = x(shape=(0,) * (ndim or 0), dtype=dtype)
TypeError: Cannot interpret 'Float32Dtype()' as a data type
```

**What you expected to happen**:
I would expect the either `from_pandas` to fail instantly, or for it to be able to work with the dtype

**Anything else we need to know?**:

**Environment**:

- Dask version: installed through `python3 -m pip install dask`
```py
>>> dask._version.version_json
'\n{\n "dirty": false,\n "error": null,\n "full-revisionid": "a77ce9513745d64cb47033d5f8026b3acc5424bf",\n "version": "2022.8.0"\n}\n'
```
- Python version: 3.9.13
- Operating System: MacOS
- Install method (conda, pip, source): pip

**Comment by rjzamora** [comment]
Thanks for raising @Tishj 

It looks like the problem here is in the creation of a `dask.array.Array` with a `Float32Dtype()` (and probably not in `dask.dataframe`). As far as I can tell, `dask.dataframe` works with these dtypes just fine, but `dask.array` gets tripped up at creation time (i.e. when `ddf.values` is used). Here is another reproducer:

```python
import dask.array as da
import dask.dataframe as dd
import pandas as pd

s_f32 = pd.Series([None, 1, 4294967295], dtype="float32")
s_F32 = pd.Series([None, 1, 4294967295], dtype="Float32")

dd.from_pandas(s_f32, npartitions=2).compute()  # Works fine
dd.from_pandas(s_F32, npartitions=2).compute()  # Works fine

da.from_array(s_f32)  # Works fine
da.from_array(s_F32)  # Fails with `TypeError: Cannot interpret 'Float32Dtype()' as a data type`
```

**Comment by jorloplaz** [comment]
This is an ongoing issue. Dask doesn't support extension types altogether. Not just this one, but all of them, see #5720
