### ISSUE TITLE
ValueError with dataframe.read_csv when running with fsspec 2022.8.0 but not fsspec 2022.7.1

### ISSUE THREAD

**Issue by kiramt** [dask/dask#9445]
**What happened**:
I called dask.dataframe.read_csv and a ValueError was raised.

**What you expected to happen**:
I expected the call to read the csv file without error.

**Minimal Complete Verifiable Example**:

```python
> python                                                                                                                                         09:56:14
Python 3.9.12 (main, Mar 26 2022, 15:51:15)
[Clang 13.1.6 (clang-1316.0.21.2)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import dask.dataframe as dd
>>> df = dd.read_csv("predict.txt")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "../.venv/lib/python3.9/site-packages/dask/dataframe/io/csv.py", line 744, in read
    return read_pandas(
  File "../.venv/lib/python3.9/site-packages/dask/dataframe/io/csv.py", line 548, in read_pandas
    b_out = read_bytes(
  File "../.venv/lib/python3.9/site-packages/dask/bytes/core.py", line 149, in read_bytes
    values = [
  File "../.venv/lib/python3.9/site-packages/dask/bytes/core.py", line 150, in <listcomp>
    delayed_read(
  File "../.venv/lib/python3.9/site-packages/dask/delayed.py", line 695, in __call__
    return call_function(
  File "../.venv/lib/python3.9/site-packages/dask/delayed.py", line 662, in call_function
    args2, collections = unzip(map(unpack_collections, args), 2)
  File "../.venv/lib/python3.9/site-packages/dask/delayed.py", line 38, in unzip
    out = list(zip(*ls))
  File "../.venv/lib/python3.9/site-packages/dask/delayed.py", line 93, in unpack_collections
    if is_dask_collection(expr):
  File "../.venv/lib/python3.9/site-packages/dask/base.py", line 187, in is_dask_collection
    return x.__dask_graph__() is not None
  File "../.venv/lib/python3.9/site-packages/fsspec/core.py", line 212, in __getattr__
    return getattr(self.f, item)
  File "../.venv/lib/python3.9/site-packages/fsspec/core.py", line 149, in f
    raise ValueError(
ValueError: I/O operation on closed file. Please call open() or use a with context
```

**Anything else we need to know?**:
The call fails when the fsspec dependency uses fsspec 2022.8.0 but works with fsspec 2022.7.1

**Environment**:

- Dask version: 2022.8.1
- Python version: 3.9.12
- Operating System: macOS / debian
- Install method (conda, pip, source): pip

**Comment by pavithraes** [comment]
@kiramt Thanks for reporting! There's already a PR open to fix this: https://github.com/dask/dask/pull/9443 :)

**Comment by jrbourbeau** [comment]
Thanks for reporting @kiramt! The new `fsspec=2022.8.1` release (just pushed to PyPI and should be on conda-forge soon) contains an update that should fix this issue. Could you install the the `fsspec=2022.8.1` release and confirm you're no longer see this issue?

**Comment by kiramt** [comment]
I've checked with `fsspec=2022.8.1` (and also `fsspec=2022.8.2`) and can confirm it's fixed. Thank you!

**Comment by pavithraes** [comment]
Awesome! Thanks, @kiramt and @jrbourbeau! Closing as resolved. :)
