### ISSUE TITLE
LocalCluster(processes=True) broken?

### ISSUE THREAD

**Issue by jeremyfirst22** [dask/dask#9543]
**Describe the issue**: Launching a `LocalCluster(processes=True)` appears to be broken, with the cluster failing the launch and `RuntimeError` thrown from `mutlipocessing/spawn.py`. Based on the output below, I suspect a race condition in the subprocess setup. 

**Minimal Complete Verifiable Example**:

```python
# -*- coding: utf-8 -*-

from dask.distributed import Client, LocalCluster

cluster = LocalCluster(n_workers=8, processes=True)
client = Client(cluster)


def test():
    return "hello"


print(client.run(test))
```

**Anything else we need to know?**:
Here is a sample of the long traceback (although I am not exactly sure where each processes traceback begins): 

```
The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/jfirst/opt/miniconda3/envs/dask/lib/python3.10/asyncio/tasks.py", line 650, in _wrap_awaitable
    return (yield from awaitable.__await__())
  File "/Users/jfirst/opt/miniconda3/envs/dask/lib/python3.10/site-packages/distributed/core.py", line 488, in start
    raise RuntimeError(f"{type(self).__name__} failed to start.") from exc
RuntimeError: Nanny failed to start.
Task exception was never retrieved
future: <Task finished name='Task-27' coro=<_wrap_awaitable() done, defined at /Users/jfirst/opt/miniconda3/envs/dask/lib/python3.10/asyncio/tasks.py:643> exception=RuntimeError('Nanny failed to start.')>
Traceback (most recent call last):
  File "/Users/jfirst/opt/miniconda3/envs/dask/lib/python3.10/site-packages/distributed/core.py", line 480, in start
    await asyncio.wait_for(self.start_unsafe(), timeout=timeout)
  File "/Users/jfirst/opt/miniconda3/envs/dask/lib/python3.10/asyncio/tasks.py", line 408, in wait_for
    return await fut
  File "/Users/jfirst/opt/miniconda3/envs/dask/lib/python3.10/site-packages/distributed/nanny.py", line 363, in start_unsafe
    response = await self.instantiate()
  File "/Users/jfirst/opt/miniconda3/envs/dask/lib/python3.10/site-packages/distributed/nanny.py", line 436, in instantiate
    result = await self.process.start()
  File "/Users/jfirst/opt/miniconda3/envs/dask/lib/python3.10/site-packages/distributed/nanny.py", line 679, in start
    await self.process.start()
  File "/Users/jfirst/opt/miniconda3/envs/dask/lib/python3.10/site-packages/distributed/process.py", line 38, in _call_and_set_future
    res = func(*args, **kwargs)
  File "/Users/jfirst/opt/miniconda3/envs/dask/lib/python3.10/site-packages/distributed/process.py", line 199, in _start
    process.start()
  File "/Users/jfirst/opt/miniconda3/envs/dask/lib/python3.10/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/Users/jfirst/opt/miniconda3/envs/dask/lib/python3.10/multiprocessing/context.py", line 284, in _Popen
    return Popen(process_obj)
  File "/Users/jfirst/opt/miniconda3/envs/dask/lib/python3.10/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/Users/jfirst/opt/miniconda3/envs/dask/lib/python3.10/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/Users/jfirst/opt/miniconda3/envs/dask/lib/python3.10/multiprocessing/popen_spawn_posix.py", line 42, in _launch
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "/Users/jfirst/opt/miniconda3/envs/dask/lib/python3.10/multiprocessing/spawn.py", line 154, in get_preparation_data
    _check_not_importing_main()
  File "/Users/jfirst/opt/miniconda3/envs/dask/lib/python3.10/multiprocessing/spawn.py", line 134, in _check_not_importing_main
    raise RuntimeError('''
RuntimeError:
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.

The above exception was the direct cause of the following exception:
```
It's worth noting that this bug does not appear from within `ipython`. If I load the interactive shell and execute the commands above, I get the expected behavior. However, running `ipython -i test.py` on the source code above results in the issue. 

**Environment**:

- Dask version: 2022.7.0
- Python version: Python 3.10.4
- Operating System: `macOS 12.0.1`, also observed on `CentOS Linux release 7.7.1908 (Core)`
- Install method (conda, pip, source):
```
conda create -n dask
conda install dask ipython 
```

**Comment by jrbourbeau** [comment]
Thanks for raising an issue @jeremyfirst22! You need include a `if __name__ == "__main__":` block to when creating a `LocalCluster`. See https://docs.dask.org/en/stable/scheduling.html#standalone-python-scripts for more details.
