### ISSUE TITLE
dd.read_parquet with filters fails with TypeError

### ISSUE THREAD

**Issue by sushi30** [dask/dask#9591]
**Describe the issue**:

After upgrading to `fastparquet==0.8.3`, this example fails. With `fastparquet==0.7.2` it succeeds.

**Minimal Complete Verifiable Example**:

```python
from dask.distributed import Client
import dask.dataframe as dd
import pandas as pd


def main():
    client = Client()
    df = pd.DataFrame({"a": [1, 2, 3], "b": [4, 5, 6]})
    ddf = dd.from_pandas(df, npartitions=2)
    ddf.to_parquet("./result/", engine="fastparquet", partition_on=["a"])
    df2 = dd.read_parquet("./result/", engine="fastparquet")
    df2.head()  # this is fine :)
    df2 = dd.read_parquet("./result/", engine="fastparquet", filters=[("a", ">", 1)])
    df2.head()  # this fails :(


if __name__ == "__main__":
    main()
```

**Anything else we need to know?**:

**Environment**:

- Dask version: 2022.10.0
- Python version: 3.10
- Operating System: Windows/Linux (os dask docker image)
- Install method (conda, pip, source): pip on windows

**Comment by jrbourbeau** [comment]
Thanks for reporting and providing a nice reproducer @sushi30. FWIW I also get an error, but it's an `AssertionError` instead of a `TypeError`

```python
Traceback (most recent call last):
  File "/Users/james/projects/dask/dask/test-fp.py", line 18, in <module>
    main()
  File "/Users/james/projects/dask/dask/test-fp.py", line 11, in main
    df2 = dd.read_parquet("./result/", engine="fastparquet")
  File "/Users/james/projects/dask/dask/dask/backends.py", line 122, in wrapper
    return getattr(self, dispatch_name)(*args, **kwargs)
  File "/Users/james/projects/dask/dask/dask/dataframe/io/parquet/core.py", line 473, in read_parquet
    read_metadata_result = engine.read_metadata(
  File "/Users/james/projects/dask/dask/dask/dataframe/io/parquet/fastparquet.py", line 835, in read_metadata
    dataset_info = cls._collect_dataset_info(
  File "/Users/james/projects/dask/dask/dask/dataframe/io/parquet/fastparquet.py", line 438, in _collect_dataset_info
    pf = ParquetFile(
  File "/Users/james/mambaforge/envs/dask/lib/python3.10/site-packages/fastparquet/api.py", line 120, in __init__
    basepath, fmd = metadata_from_many(fn, verify_schema=verify,
  File "/Users/james/mambaforge/envs/dask/lib/python3.10/site-packages/fastparquet/util.py", line 218, in metadata_from_many
    basepath, file_list = analyse_paths(file_list, root=root)
  File "/Users/james/mambaforge/envs/dask/lib/python3.10/site-packages/fastparquet/util.py", line 366, in analyse_paths
    assert all(p[:l] == basepath for p in path_parts_list
AssertionError: All paths must begin with the given root
```

It looks like `fastparquet` is having problems with filepath parsing. cc @martindurant 

I did notice that if I switch to using the `pyarrow` engine, then the example runs as expected.

**Comment by martindurant** [comment]
This does work fine with the fastparquet direct API or with pd.read_parquet

**Comment by jrbourbeau** [comment]
> This does work fine with the fastparquet direct API or with pd.read_parquet

So then probably an issue with `dask`s parsing of filepaths then? 

@phobson is this something you have interest / bandwidth for looking into?

**Comment by phobson** [comment]
@jrbourbeau Absolutely.

**Comment by phobson** [comment]
@sushi30 I think I figured this out. The `fastparquet` library isn't parsing the leading `.` in `./results/` properly. If you change your example to:

```python
    ...
    df3 = dd.read_parquet("result/", engine="fastparquet", filters=[("a", ">", 1)])
```

Everything works well. 

This issue occurs when the roots of partition paths are being compared to a base path. The base path has the `.` parsed correctly, the partitions do not.

```
> /Users/paul/mambaforge/envs/dask-dev/lib/python3.10/site-packages/fastparquet/util.py(366)analyse_paths()
    364         basepath = join_path(root).split('/')
    365         l = len(basepath)
--> 366         assert all(p[:l] == basepath for p in path_parts_list
    367                    ), "All paths must begin with the given root"
    368     out_list = []

ipdb> print(l)
7
ipdb> path_parts_list
[['', 'Users', 'paul', 'work', 'sources', 'dask', '.', 'result', 'a=1', 'part.0.parquet']]
ipdb> basepath
['', 'Users', 'paul', 'work', 'sources', 'dask', 'result']
```

Two or three things we can do here:
1) put a shim/guard against this on our end
2) raise an issue in fastparquet
3) submit a fix to fast parquet

I'll take care of (2) now. @jrbourbeau, any thoughts on (1) and (3)?

**Comment by phobson** [comment]
In light of

https://github.com/dask/dask/issues/9591#issuecomment-1290721021
> This does work fine with the fastparquet direct API or with pd.read_parquet 

I do think we should address this issue in dask

**Comment by jrbourbeau** [comment]
Sounds good to me. @martindurant does `fsspec` have a utility for normalizing paths (specifically, stripping out that `.`)?

**Comment by martindurant** [comment]
`fs._strip_protocol` is normally what you do, which does absolute pathing for LocalFileSystem. There is a generic `fsspec.core.strip_protocol` version of this too.

**Comment by sushi30** [comment]
How does this work with other fsspec backends? I hit the same error when working with `s3://` protocol.

**Comment by martindurant** [comment]
How did you specify a relative path for s3?

**Comment by sushi30** [comment]
I did not. It failed with the same issue that was documented by OP.

**Comment by martindurant** [comment]
@sushi30 , can you please show exactly what you did.

**Comment by sushi30** [comment]
I posted the example to reproduce the issue. I am noting that it is also rising when using s3 protocol. You can try to reproduce by switching the `./results/` to an s3 path.

**Comment by martindurant** [comment]
Thanks @sushi30 . We'll try to fix it. It sounds like we should be able to put an explicit `_strip_protocol` early in `read_parquet` to make an absolute path.

**Comment by martindurant** [comment]
I **cannot** confirm this on s3:
```
import dask.dataframe as dd
import pandas as pd
df = pd.DataFrame({"a": [1, 2, 3], "b": [4, 5, 6]})
# with pandas or dask API for writing, both are fine
df.to_parquet("s3://mymdtemp/result/", engine="fastparquet", partition_on=["a"])
df2 = dd.read_parquet("s3://mymdtemp/result/", engine="fastparquet", filters=[("a", ">", 1)]).compute()
>    b  a
0  5  2
0  6  3
```

**Comment by sushi30** [comment]
I can confirm this is failing with the same `TypeError`

```python
Traceback (most recent call last):
  File "C:\Users\user\AppData\Roaming\JetBrains\PyCharm2021.3\scratches\scratch_28.py", line 20, in <module>
    main()
  File "C:\Users\user\AppData\Roaming\JetBrains\PyCharm2021.3\scratches\scratch_28.py", line 16, in main
    df2.head()  # this fails :(
  File "C:\Users\user\projects\airflow-dags\.venv\lib\site-packages\dask\dataframe\core.py", line 1263, in head
    return self._head(n=n, npartitions=npartitions, compute=compute, safe=safe)
  File "C:\Users\user\projects\airflow-dags\.venv\lib\site-packages\dask\dataframe\core.py", line 1297, in _head
    result = result.compute()
  File "C:\Users\user\projects\airflow-dags\.venv\lib\site-packages\dask\base.py", line 315, in compute
    (result,) = compute(self, traverse=False, **kwargs)
  File "C:\Users\user\projects\airflow-dags\.venv\lib\site-packages\dask\base.py", line 600, in compute
    results = schedule(dsk, keys, **kwargs)
  File "C:\Users\user\projects\airflow-dags\.venv\lib\site-packages\distributed\client.py", line 3037, in get
    futures = self._graph_to_futures(
  File "C:\Users\user\projects\airflow-dags\.venv\lib\site-packages\distributed\client.py", line 2945, in _graph_to_futures
    dsk = dsk.__dask_distributed_pack__(self, keyset, annotations)
  File "C:\Users\user\projects\airflow-dags\.venv\lib\site-packages\dask\highlevelgraph.py", line 1078, in __dask_distributed_pack__
    "state": layer.__dask_distributed_pack__(
  File "C:\Users\user\projects\airflow-dags\.venv\lib\site-packages\dask\blockwise.py", line 631, in __dask_distributed_pack__
    else dumps_function(dsk[0])
  File "C:\Users\user\projects\airflow-dags\.venv\lib\site-packages\distributed\worker.py", line 2887, in dumps_function
    result = pickle.dumps(func, protocol=4)
  File "C:\Users\user\projects\airflow-dags\.venv\lib\site-packages\distributed\protocol\pickle.py", line 58, in dumps
    result = cloudpickle.dumps(x, **dump_kwargs)
  File "C:\Users\user\projects\airflow-dags\.venv\lib\site-packages\cloudpickle\cloudpickle_fast.py", line 73, in dumps
    cp.dump(obj)
  File "C:\Users\user\projects\airflow-dags\.venv\lib\site-packages\cloudpickle\cloudpickle_fast.py", line 633, in dump
    return Pickler.dump(self, obj)
  File "fastparquet\cencoding.pyx", line 779, in fastparquet.cencoding.ThriftObject.__reduce_ex__
  File "fastparquet\cencoding.pyx", line 769, in fastparquet.cencoding.ThriftObject.to_bytes
TypeError: object of type 'NoneType' has no len()
```

### Snippet

```python
from dask.distributed import Client
import dask.dataframe as dd
import pandas as pd


def main():
    # path = "./result/"
    path = "s3://some-bucket/result/"
    client = Client()
    df = pd.DataFrame({"a": [1, 2, 3], "b": [4, 5, 6]})
    ddf = dd.from_pandas(df, npartitions=2)
    ddf.to_parquet(path, engine="fastparquet", partition_on=["a"])
    df2 = dd.read_parquet(path, engine="fastparquet")
    df2.head()  # this is fine :)
    df2 = dd.read_parquet(path, engine="fastparquet", filters=[("a", ">", 1)])
    df2.head()  # this fails :(


if __name__ == "__main__":
    main()
```

**Comment by martindurant** [comment]
https://github.com/fsspec/filesystem_spec/pull/1112

**Comment by phobson** [comment]
Thanks, @martindurant. Do you recommend that we do anything in dask in between now and the next fsspec release? (My guess would be "no", but I wanted to check).

**Comment by jrbourbeau** [comment]
Awesome, thanks @martindurant!
