### ISSUE TITLE
`sort_values()` can fail with `Timestamp` data

### ISSUE THREAD

**Issue by jrbourbeau** [dask/dask#9641]
The following `sort_values()` computation fails using the latest `dask` `main` branch and `pandas=1.5.0` 

```python
from pandas import Timestamp
import pandas as pd
import dask.dataframe as dd

df = pd.DataFrame.from_records(
       [[Timestamp('2002-01-11 21:00:01+0000', tz='UTC'), 4223, 54719.0],
       [Timestamp('2002-01-14 21:00:01+0000', tz='UTC'), 6942, 19223.0],
       [Timestamp('2002-01-15 21:00:01+0000', tz='UTC'), 12551, 72865.0],
       [Timestamp('2002-01-23 21:00:01+0000', tz='UTC'), 6005, 57670.0],
       [Timestamp('2002-01-29 21:00:01+0000', tz='UTC'), 2043, 58600.0],
       [Timestamp('2002-02-01 21:00:01+0000', tz='UTC'), 6909, 8459.0],
       [Timestamp('2002-01-14 21:00:01+0000', tz='UTC'), 5326, 77339.0],
       [Timestamp('2002-01-14 21:00:01+0000', tz='UTC'), 4711, 54135.0],
       [Timestamp('2002-01-22 21:00:01+0000', tz='UTC'), 103, 57627.0],
       [Timestamp('2002-01-30 21:00:01+0000', tz='UTC'), 16862, 54458.0],
       [Timestamp('2002-01-31 21:00:01+0000', tz='UTC'), 4143, 56280.0]],
    columns=["time", "id1", "id2"]
)
dd.from_pandas(df, npartitions=2).sort_values("time").compute()
```

with `TypeError: value should be a 'Timestamp', 'NaT', or array of those. Got 'StringArray' instead.` (full traceback below)

<details>
<summary>Traceback:</summary>

```python
Traceback (most recent call last):
  File "/Users/james/projects/dask/dask/dask/dataframe/shuffle.py", line 851, in set_partitions_pre
    partitions = divisions.searchsorted(s, side="right") - 1
  File "/Users/james/mambaforge/envs/dask/lib/python3.10/site-packages/pandas/core/series.py", line 3054, in searchsorted
    return base.IndexOpsMixin.searchsorted(self, value, side=side, sorter=sorter)
  File "/Users/james/mambaforge/envs/dask/lib/python3.10/site-packages/pandas/core/base.py", line 1296, in searchsorted
    return values.searchsorted(value, side=side, sorter=sorter)
  File "/Users/james/mambaforge/envs/dask/lib/python3.10/site-packages/pandas/core/arrays/_mixins.py", line 238, in searchsorted
    npvalue = self._validate_searchsorted_value(value)
  File "/Users/james/mambaforge/envs/dask/lib/python3.10/site-packages/pandas/core/arrays/datetimelike.py", line 782, in _validate_searchsorted_value
    value = self._validate_listlike(value)
  File "/Users/james/mambaforge/envs/dask/lib/python3.10/site-packages/pandas/core/arrays/datetimelike.py", line 774, in _validate_listlike
    raise TypeError(msg)
TypeError: value should be a 'Timestamp', 'NaT', or array of those. Got 'StringArray' instead.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/james/projects/dask/dask/test.py", line 19, in <module>
    dd.from_pandas(df, npartitions=2).sort_values("time").compute()
  File "/Users/james/projects/dask/dask/dask/base.py", line 315, in compute
    (result,) = compute(self, traverse=False, **kwargs)
  File "/Users/james/projects/dask/dask/dask/base.py", line 600, in compute
    results = schedule(dsk, keys, **kwargs)
  File "/Users/james/projects/dask/dask/dask/threaded.py", line 89, in get
    results = get_async(
  File "/Users/james/projects/dask/dask/dask/local.py", line 511, in get_async
    raise_exception(exc, tb)
  File "/Users/james/projects/dask/dask/dask/local.py", line 319, in reraise
    raise exc
  File "/Users/james/projects/dask/dask/dask/local.py", line 224, in execute_task
    result = _execute_task(task, data)
  File "/Users/james/projects/dask/dask/dask/core.py", line 119, in _execute_task
    return func(*(_execute_task(a, cache) for a in args))
  File "/Users/james/projects/dask/dask/dask/optimization.py", line 990, in __call__
    return core.get(self.dsk, self.outkey, dict(zip(self.inkeys, args)))
  File "/Users/james/projects/dask/dask/dask/core.py", line 149, in get
    result = _execute_task(task, cache)
  File "/Users/james/projects/dask/dask/dask/core.py", line 119, in _execute_task
    return func(*(_execute_task(a, cache) for a in args))
  File "/Users/james/projects/dask/dask/dask/core.py", line 119, in <genexpr>
    return func(*(_execute_task(a, cache) for a in args))
  File "/Users/james/projects/dask/dask/dask/core.py", line 119, in _execute_task
    return func(*(_execute_task(a, cache) for a in args))
  File "/Users/james/projects/dask/dask/dask/utils.py", line 71, in apply
    return func(*args, **kwargs)
  File "/Users/james/projects/dask/dask/dask/dataframe/core.py", line 6773, in apply_and_enforce
    df = func(*args, **kwargs)
  File "/Users/james/projects/dask/dask/dask/dataframe/shuffle.py", line 859, in set_partitions_pre
    partitions[not_null] = divisions.searchsorted(s[not_null], side="right") - 1
  File "/Users/james/mambaforge/envs/dask/lib/python3.10/site-packages/pandas/core/series.py", line 3054, in searchsorted
    return base.IndexOpsMixin.searchsorted(self, value, side=side, sorter=sorter)
  File "/Users/james/mambaforge/envs/dask/lib/python3.10/site-packages/pandas/core/base.py", line 1296, in searchsorted
    return values.searchsorted(value, side=side, sorter=sorter)
  File "/Users/james/mambaforge/envs/dask/lib/python3.10/site-packages/pandas/core/arrays/_mixins.py", line 238, in searchsorted
    npvalue = self._validate_searchsorted_value(value)
  File "/Users/james/mambaforge/envs/dask/lib/python3.10/site-packages/pandas/core/arrays/datetimelike.py", line 782, in _validate_searchsorted_value
    value = self._validate_listlike(value)
  File "/Users/james/mambaforge/envs/dask/lib/python3.10/site-packages/pandas/core/arrays/datetimelike.py", line 774, in _validate_listlike
    raise TypeError(msg)
TypeError: value should be a 'Timestamp', 'NaT', or array of those. Got 'StringArray' instead.
```

</details>

**Comment by jrbourbeau** [comment]
Closed via https://github.com/dask/dask/pull/9642
