### ISSUE TITLE
Meta_error when using dropna on dask 2022.5.0 dataframe

### ISSUE THREAD

**Issue by greg500** [dask/dask#9689]
**Describe the issue**:

Since upgrading from dask 2021.4.0 to 2022.5.0 (through anaconda 2022.10 update),
 dask dataframe dropna method raises a meta error.
I am asked to provide dropna method with a meta argument which it doesn't accept.

Traceback (most recent call last):

  File "C:\Users\Greg\Anaconda3\envs\new2\lib\site-packages\dask\dataframe\utils.py", line 182, in raise_on_meta_error
    yield

  File "C:\Users\Greg\Anaconda3\envs\new2\lib\site-packages\dask\dataframe\core.py", line 6247, in _emulate
    return func(*_extract_meta(args, True), **_extract_meta(kwargs, True))

  File "C:\Users\Greg\Anaconda3\envs\new2\lib\site-packages\dask\utils.py", line 1022, in __call__
    return getattr(__obj, self.method)(*args, **kwargs)

  File "C:\Users\Greg\Anaconda3\envs\new2\lib\site-packages\pandas\util\_decorators.py", line 331, in wrapper
    return func(*args, **kwargs)

  File "C:\Users\Greg\Anaconda3\envs\new2\lib\site-packages\pandas\core\frame.py", line 6526, in dropna
    raise TypeError(

TypeError: You cannot set both the how and thresh arguments at the same time.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):

  File "C:\Users\Greg\AppData\Local\Temp\ipykernel_15328\1036061993.py", line 10, in <module>
    d.dropna().compute()

  File "C:\Users\Greg\Anaconda3\envs\new2\lib\site-packages\dask\dataframe\core.py", line 4917, in dropna
    return self.map_partitions(

  File "C:\Users\Greg\Anaconda3\envs\new2\lib\site-packages\dask\dataframe\core.py", line 845, in map_partitions
    return map_partitions(func, self, *args, **kwargs)

  File "C:\Users\Greg\Anaconda3\envs\new2\lib\site-packages\dask\dataframe\core.py", line 6316, in map_partitions
    meta = _emulate(func, *args, udf=True, **kwargs)

  File "C:\Users\Greg\Anaconda3\envs\new2\lib\site-packages\dask\dataframe\core.py", line 6247, in _emulate
    return func(*_extract_meta(args, True), **_extract_meta(kwargs, True))

  File "C:\Users\Greg\Anaconda3\envs\new2\lib\contextlib.py", line 137, in __exit__
    self.gen.throw(typ, value, traceback)

  File "C:\Users\Greg\Anaconda3\envs\new2\lib\site-packages\dask\dataframe\utils.py", line 203, in raise_on_meta_error
    raise ValueError(msg) from e

ValueError: Metadata inference failed in `dropna`.

You have supplied a custom function and Dask is unable to 
determine the type of output that that function returns. 

To resolve this please provide a meta= keyword.
The docstring of the Dask function you ran should have more information.

Original error is below:
------------------------
TypeError('You cannot set both the how and thresh arguments at the same time.')

Traceback:
---------
  File "C:\Users\Greg\Anaconda3\envs\new2\lib\site-packages\dask\dataframe\utils.py", line 182, in raise_on_meta_error
    yield
  File "C:\Users\Greg\Anaconda3\envs\new2\lib\site-packages\dask\dataframe\core.py", line 6247, in _emulate
    return func(*_extract_meta(args, True), **_extract_meta(kwargs, True))
  File "C:\Users\Greg\Anaconda3\envs\new2\lib\site-packages\dask\utils.py", line 1022, in __call__
    return getattr(__obj, self.method)(*args, **kwargs)
  File "C:\Users\Greg\Anaconda3\envs\new2\lib\site-packages\pandas\util\_decorators.py", line 331, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\Greg\Anaconda3\envs\new2\lib\site-packages\pandas\core\frame.py", line 6526, in dropna
    raise TypeError(
**Minimal Complete Verifiable Example**:

```python
import pandas as pd
import numpy as np
from dask import dataframe as dd

arr=np.ones((100,10))
df=pd.DataFrame(arr)
df.iloc[:10]=np.nan
d=dd.from_pandas(df,npartitions=2)
d.dropna().compute()

```

**Anything else we need to know?**:

**Environment**:

- Dask version: 2022.5.0
- Python version: 3.9.15
- Operating System: Windows 10
- Install method (conda, pip, source): conda

**Comment by greg500** [comment]
@phobson  thank you for your reply. I cannot upgrade to 2022.8.1 dask for now through conda. A temporary workaround found in a previous post "dropna(how=_NoDefault.no_default,thresh=_NoDefault.no_default)" seems to work fine.

**Comment by phobson** [comment]
Glad you found the work around. I'll close this for now.
