### ISSUE TITLE
It raises Error to Index dask.dataframe's index by applied series.

### ISSUE THREAD

**Issue by Crispy13** [dask/dask#9763]
**Describe the issue**:

**Minimal Complete Verifiable Example**:
```
toy_df = pd.DataFrame(
                    np.random.randn(10,3),
                    columns = list("ABC"),
                    index = list(range(10)),
)

toy_ddf1 = dd.from_pandas(toy_df, npartitions=2)

s1 = toy_ddf1['A'].apply(lambda x: abs(x) < 0.5 , meta = ('A', 'bool'))

toy_ddf1.index[s1]
```

raises an Error
```
Traceback (most recent call last):
  File "/software/anaconda3/envs/TOSC_ML/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3398, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "/tmp/ipykernel_2591361/913354499.py", line 1, in <cell line: 1>
    toy_ddf1.index[s1]
  File "/software/anaconda3/envs/TOSC_ML/lib/python3.10/site-packages/dask/dataframe/core.py", line 3486, in __getitem__
    return Series(graph, name, self._meta, self.divisions)
  File "/software/anaconda3/envs/TOSC_ML/lib/python3.10/site-packages/dask/dataframe/core.py", line 321, in __init__
    raise TypeError(
TypeError: Expected meta to specify type Series, got type pandas.core.indexes.numeric.Int64Index
```

```python
# Put your MCVE code here
```

**Anything else we need to know?**:

**Environment**:

- Dask version: 2022.2.1
- Python version: 3.10
- Operating System: CentOS Linux release 8.4.2105
- Install method (conda, pip, source): conda

**Comment by quasiben** [comment]
Can you write the full equivalent of what you are trying to do with Pandas ?  When I do what I _think_ you are trying to do it is invalid:

```python
In [22]: toy_df.index[toy_df.apply(lambda x: abs(x) < 0.5)]
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
Input In [22], in <module>
----> 1 toy_df.index[toy_df.apply(lambda x: abs(x) < 0.5)]

File ~/miniconda3/envs/dask-dev/lib/python3.9/site-packages/pandas/core/indexes/base.py:5055, in Index.__getitem__(self, key)
   5048 if com.is_bool_indexer(key):
   5049     # if we have list[bools, length=1e5] then doing this check+convert
   5050     #  takes 166 µs + 2.1 ms and cuts the ndarray.__getitem__
   5051     #  time below from 3.8 ms to 496 µs
   5052     # if we already have ndarray[bool], the overhead is 1.4 µs or .25%
   5053     key = np.asarray(key, dtype=bool)
-> 5055 result = getitem(key)
   5056 # Because we ruled out integer above, we always get an arraylike here
   5057 if result.ndim > 1:

IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed
```

**Comment by Crispy13** [comment]
For pandas code,

```
toy_df = pd.DataFrame(
                    np.random.randn(10,3),
                    columns = list("ABC"),
                    index = list(range(10)),
)

s1 = toy_df['A'].apply(lambda x: abs(x) < 0.5)

toy_df.index[s1]
```

**Comment by quasiben** [comment]
Apologies, I had misread your initial code example.  I think in this case Dask does not have full selection of an `index`.  You could either reset the index and select from the column with the boolean mask you computed: `s1` or you could convert the index to a series then do the boolean selection:

> toy_ddf1.index.to_series()[s1]

Not sure how easy / difficult this would be to fully implement

**Comment by vladjohnson** [comment]
Please fix

**Comment by phofl** [comment]
This seems to work on main and the newest release
