### ISSUE TITLE
`sort_values` fails to sort by nullable numeric columns when a partition is entirely null

### ISSUE THREAD

**Issue by charlesbluca** [dask/dask#9765]
**Describe the issue**:
When attempting to sort a dataframe by a nullable numeric column (e.g. `Int64`) that has a partition made up entirely of `pd.NA`, we fail at the computation of divisions with `TypeError: boolean value of NA is ambiguous`.

It looks like the underlying issue here is that the various algorithms behind `_repartition_quantiles` (specifically `merge_and_compress_summaries` and `process_val_weights`) have support for `np.nan` but not `pd.NA`.

**Minimal Complete Verifiable Example**:

```python
import dask.dataframe as dd
import pandas as pd

df = pd.DataFrame({"a": [2, 3, 1, 2, None, None]})
df["a"] = df["a"].astype("Int64")

ddf = dd.from_pandas(df, npartitions=3)
ddf.sort_values("a")
```
**Environment**:

- Dask version: latest
- Python version: 3.10
- Operating System: ubuntu20.04
- Install method (conda, pip, source): source

**Comment by jrbourbeau** [comment]
Thanks @charlesbluca! I'm able to reproduce. Including the traceback below for completeness 

```python
Traceback (most recent call last):
  File "/Users/james/projects/dask/dask/test-sort-values.py", line 9, in <module>
    ddf.sort_values("a")
  File "/Users/james/projects/dask/dask/dask/dataframe/core.py", line 4781, in sort_values
    return sort_values(
  File "/Users/james/projects/dask/dask/dask/dataframe/shuffle.py", line 151, in sort_values
    divisions, mins, maxes = _calculate_divisions(
  File "/Users/james/projects/dask/dask/dask/dataframe/shuffle.py", line 66, in _calculate_divisions
    raise e
  File "/Users/james/projects/dask/dask/dask/dataframe/shuffle.py", line 47, in _calculate_divisions
    divisions, sizes, mins, maxes = compute(divisions, sizes, mins, maxes)
  File "/Users/james/projects/dask/dask/dask/base.py", line 600, in compute
    results = schedule(dsk, keys, **kwargs)
  File "/Users/james/projects/dask/dask/dask/threaded.py", line 89, in get
    results = get_async(
  File "/Users/james/projects/dask/dask/dask/local.py", line 511, in get_async
    raise_exception(exc, tb)
  File "/Users/james/projects/dask/dask/dask/local.py", line 319, in reraise
    raise exc
  File "/Users/james/projects/dask/dask/dask/local.py", line 224, in execute_task
    result = _execute_task(task, data)
  File "/Users/james/projects/dask/dask/dask/core.py", line 119, in _execute_task
    return func(*(_execute_task(a, cache) for a in args))
  File "/Users/james/projects/dask/dask/dask/dataframe/partitionquantiles.py", line 281, in merge_and_compress_summaries
    it = merge_sorted(*[zip(x, y) for x, y in vals_and_weights])
  File "cytoolz/itertoolz.pyx", line 312, in cytoolz.itertoolz.merge_sorted
  File "cytoolz/itertoolz.pyx", line 289, in cytoolz.itertoolz.c_merge_sorted
  File "cytoolz/itertoolz.pyx", line 179, in cytoolz.itertoolz._merge_sorted_binary
  File "cytoolz/itertoolz.pyx", line 203, in cytoolz.itertoolz._merge_sorted.__next__
  File "pandas/_libs/missing.pyx", line 382, in pandas._libs.missing.NAType.__bool__
TypeError: boolean value of NA is ambiguous
```

Just checking in, is this something you have bandwidth to look into? (no worries if not)

**Comment by jrbourbeau** [comment]
Thinking about this is a bit a couple of possible fixes come to mind. 

1. I see the error is coming from the fact that `merged_sorted` in `toolz` isn't `pd.NA` aware. Is there a way we can make it aware? 
2. Things seem to work with `np.nan` instead of `pd.NA`. What if we just made that replacement ourselves? To be clear, I'm not sure what downstream side-effects this may cause

**Comment by charlesbluca** [comment]
> is this something you have bandwidth to look into?

Yeah, I took some time to look into this while toying around with the reproducer - think we'll probably want to go with solution 2 here, as even after unblocking `_repartition_quantiles` we still end up with quantile divisions containing `pd.NA`, which raises issues later on when we attempt to do a `searchsorted` as part of `set_partitions_pre`.

It seems like this solution works at least for this specific reproducer, but one point of difficulty here is that it isn't immediately obvious how to get a good mapping between pandas nullable dtypes and their equivalent numpy dtypes (e.g. mapping `Int64` to `float64`) - happy to open up a PR with what I have so far to continue discussion there

**Comment by jrbourbeau** [comment]
> how to get a good mapping between pandas nullable dtypes and their equivalent numpy dtypes

I could be missing something, but is this the thing you're after? 

```python
In [1]: import pandas as pd

In [2]: d = pd.Int64Dtype()

In [3]: d.numpy_dtype
Out[3]: dtype('int64')
```

**Comment by j-bennet** [comment]
I didn't see this issue before, but this might possibly fix it:

https://github.com/dask/dask/pull/10054

**Comment by j-bennet** [comment]
https://github.com/dask/dask/pull/10054 does not fix this issue; that part was reverted.
