### ISSUE TITLE
parquet removes custom index when saving with schema

### ISSUE THREAD

**Issue by thomasf1** [dask/dask#9773]
to_parquet seems to set preserve_index=False when using a schema.

**Minimal Complete Verifiable Example**:

```python
df3 = pd.DataFrame.from_dict({11: {'a': 'a11'}, 22: {'a': 'a22'}}, orient='index')
#>>> df3
#      a
#11  a11
#22  a22
df4 = dd.from_pandas(df3, chunksize=1, sort=True)
#>>> df4.compute()
#      a
#11  a11
#22  a22

# Saving without schema (works as expected)
df4.to_parquet('users2', compression="brotli", write_metadata_file=True)

# reading it back - works
df5 = dd.read_parquet('users2', compression="brotli")
#>>> df5.compute()
#      a
#11  a11
#22  a22

# Saving with schema (deletes the index)

import pyarrow as pa
schema = pa.schema([pa.field('a', pa.string())])
df4.to_parquet('users2', compression="brotli", schema=schema, write_metadata_file=True)
df5 = dd.read_parquet('users2', compression="brotli")
#>>> df5.compute()
#     a
#0  a11
#0  a22
```

**Anything else we need to know?**:

when including the index in the schema, the following trace from the exception is shown, locating the problem:

```
Traceback (most recent call last):
  File "/Users/tom/Dev/test/dask/testCompression.py", line 79, in <module>
    df.to_parquet('users', schema=schema, compression="brotli", write_metadata_file=True, preserve_index=True)
  File "/opt/homebrew/lib/python3.10/site-packages/dask/dataframe/core.py", line 5272, in to_parquet
    return to_parquet(self, path, *args, **kwargs)
  File "/opt/homebrew/lib/python3.10/site-packages/dask/dataframe/io/parquet/core.py", line 1037, in to_parquet
    out = out.compute(**compute_kwargs)
  File "/opt/homebrew/lib/python3.10/site-packages/dask/base.py", line 315, in compute
    (result,) = compute(self, traverse=False, **kwargs)
  File "/opt/homebrew/lib/python3.10/site-packages/dask/base.py", line 600, in compute
    results = schedule(dsk, keys, **kwargs)
  File "/opt/homebrew/lib/python3.10/site-packages/dask/threaded.py", line 89, in get
    results = get_async(
  File "/opt/homebrew/lib/python3.10/site-packages/dask/local.py", line 511, in get_async
    raise_exception(exc, tb)
  File "/opt/homebrew/lib/python3.10/site-packages/dask/local.py", line 319, in reraise
    raise exc
  File "/opt/homebrew/lib/python3.10/site-packages/dask/local.py", line 224, in execute_task
    result = _execute_task(task, data)
  File "/opt/homebrew/lib/python3.10/site-packages/dask/core.py", line 119, in _execute_task
    return func(*(_execute_task(a, cache) for a in args))
  File "/opt/homebrew/lib/python3.10/site-packages/dask/optimization.py", line 990, in __call__
    return core.get(self.dsk, self.outkey, dict(zip(self.inkeys, args)))
  File "/opt/homebrew/lib/python3.10/site-packages/dask/core.py", line 149, in get
    result = _execute_task(task, cache)
  File "/opt/homebrew/lib/python3.10/site-packages/dask/core.py", line 119, in _execute_task
    return func(*(_execute_task(a, cache) for a in args))
  File "/opt/homebrew/lib/python3.10/site-packages/dask/dataframe/io/parquet/core.py", line 172, in __call__
    return self.engine.write_partition(
  File "/opt/homebrew/lib/python3.10/site-packages/dask/dataframe/io/parquet/arrow.py", line 771, in write_partition
    t = cls._pandas_to_arrow_table(df, preserve_index=preserve_index, schema=schema)
  File "/opt/homebrew/lib/python3.10/site-packages/dask/dataframe/io/parquet/arrow.py", line 719, in _pandas_to_arrow_table
    return pa.Table.from_pandas(
  File "pyarrow/table.pxi", line 3475, in pyarrow.lib.Table.from_pandas
  File "/opt/homebrew/lib/python3.10/site-packages/pyarrow/pandas_compat.py", line 570, in dataframe_to_arrays
    convert_fields) = _get_columns_to_convert(df, schema, preserve_index,
  File "/opt/homebrew/lib/python3.10/site-packages/pyarrow/pandas_compat.py", line 357, in _get_columns_to_convert
    return _get_columns_to_convert_given_schema(df, schema, preserve_index)
  File "/opt/homebrew/lib/python3.10/site-packages/pyarrow/pandas_compat.py", line 439, in _get_columns_to_convert_given_schema
    raise ValueError(
ValueError: name '__index_level_0__' present in the specified schema corresponds to the index, but 'preserve_index=False' was specified
```

**Environment**:

- Dask version: 2022.12.1
- Python version: python3.10
- Operating System: macos 12.6
- Install method (conda, pip, source): pip

**Comment by jrbourbeau** [comment]
Thanks for the issue @thomasf1. @rjzamora do you have bandwidth to look at this one?

**Comment by rjzamora** [comment]
I will poke around and see if there is a clean way to still use the pandas metadata for index-preservation purposes when a proper pyarrow schema is already defined.

With that said, you should be able to specify something like `schema={"a": pa.string()}` to make it clear that you only want to specify the schema for a specific column (and that the rest of the schema can be inferred). Hopefully you won't loose the index using the `dict` approach.

**Comment by thomasf1** [comment]
Great. Do you need me to test anything? I gues i could built it from source with the pull request :)

I´ll also test the dict approach and report back, might require some documentation though or outputting a warning for other users.

**Comment by thomasf1** [comment]
Update1: It did fix the Minimal Complete Verifiable Example, testing my original usecase now.

**Comment by mrocklin** [comment]
Glad to hear it.  If your original use case is good then the PR looks good to me and I'd be happy to merge.

**Comment by thomasf1** [comment]
Verified that the PR also works with the larger usecase. Thanks for the help :)

The reason I was using schema is that it seems to be required for parquet as otherwise infers datatype on each partition which could be as low as one row (using e.g. chunksize=10000) - with varing data that leads to issues merging things back together when reading the data again.

I would have thought that write_metadata_file=True also saves the schema an re-uses when saving again, but this does not seem to be the case?

Therefore I opted for schema, as it has a serialize function to save the schema to disk when saving the dataframe. If you guys know a more elegant way, I´d be grateful for a hint :).

**Comment by thomasf1** [comment]
Done some more testing and it doesn´t seem to work in all cases. I´ll have a closer look... :o

**Comment by mrocklin** [comment]
Thanks @thomasf1 I'll be curious to see what you learn

**Comment by rjzamora** [comment]
>Done some more testing and it doesn´t seem to work in all cases. I´ll have a closer look... :o

Thanks for testing this @thomasf1 - Are you able to share a reproducer for a case that isn't covered by https://github.com/dask/dask/pull/9780?
