### ISSUE TITLE
Indexing a dask DataFrame with a dask boolean array

### ISSUE THREAD

**Issue by gcaria** [dask/dask#9798]
This seems related to https://github.com/dask/dask/issues/2651

```python
import dask.dataframe as dkd
import dask.array as dka
import numpy as np
arr = np.random.rand(25,2)
ddf = dkd.from_array(arr)
darr_bool = dka.from_array([True]*25)
ddf[darr_bool]
------------------------------------------------
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ubuntu/envs/test-dask/lib/python3.10/site-packages/dask/dataframe/core.py", line 4639, in __getitem__
    raise NotImplementedError(key)
NotImplementedError: dask.array<array, shape=(25,), dtype=bool, chunksize=(25,), chunktype=numpy.ndarray>
```

I got this error running on main (indexing a dask Series with a dask boolean array works fine).

Is there some fundamental issue with this type of feature?

**Comment by TomAugspurger** [comment]
dask seems to be treating that argument as a column to look up. It's not special-casing boolean ndarrays as a mask on the rows.

Here's the workaround:

```python
In [3]: ddf.loc[darr_bool, :]
Out[3]:
Dask DataFrame Structure:
                     0        1
npartitions=1
0              float64  float64
24                 ...      ...
Dask Name: loc-series, 5 graph layers
```

**Comment by gcaria** [comment]
Ah! That's reassuring. Was it intentional to not replicate this pandas-like behaviour?
