### ISSUE TITLE
Dask hangs at the creation of .csv file

### ISSUE THREAD

**Issue by lime-n** [dask/dask#9834]
<!-- Please include a self-contained copy-pastable example that generates the issue if possible.

Code I am using:
```
from dask.distributed import Client
import dask.dataframe as dd
import dask

dask.config.set({"optimization.fuse.active": True})

longer_pivot = dd.read_csv("cmp_product_long.csv")
print('Imported csv')
longer_pivot = longer_pivot.rename(columns={'value': 'ranges'})
pivot_longer = longer_pivot[['variable', 'ranges']]
print(pivot_longer)

def main(self):
    longer_pivot['ranges'] = self.apply(lambda x: x.ranges.replace('--', x.variable), axis=1, meta=(None,object))
    print(longer_pivot)
    result_of_agg = longer_pivot.groupby('market').agg({
        'ranges':'count'
    })
    print(result_of_agg.compute().to_csv('result_of_agg.csv'))
    result_of_agg_var = longer_pivot.groupby(['market','variable']).agg({
        'ranges':'count'
    })
    result_of_agg_var.compute().to_csv('result_of_agg_var.csv')
    print(result_of_agg_var)
        
if __name__ == '__main__':
    client = Client(n_workers=2, threads_per_worker=4, processes=True)
    client
    main(pivot_longer)

```
**Describe the issue**:

I find that when my script enters the line to create a .csv file, it hangs in the terminal. The dataset is approximately 70gb in size.

**Anything else we need to know?**:

**Environment**:

- Dask version: dask, version 2023.1.0
- Python version: python3.9.13
- Operating System:  Microsoft Windows 10
- Install method (conda, pip, source): pip

**Comment by fjetter** [comment]
The way you wrote your code, i.e. calling `compute` and then `to_csv` will collect the entire dataframe in a single process and then use pandas to_csv to write the CSV file, i.e. you will end up with a single file.
My guess is that your local machine doens't have sufficient memory for this, does it? Keep in mind that writing the CSV file requires some memory as well, i.e. you'll need much more than the size of the dataframe if you want to do everything in a single process.

Instead, consider writing the data out into multiple files using the dask API, see https://docs.dask.org/en/stable/generated/dask.dataframe.to_csv.html#dask-dataframe-to-csv

**Comment by lime-n** [comment]
Hello @fjetter , thank you for the reply!

After waiting for some extra while I get a Permission denied error:

```
Traceback (most recent call last):
  File "C:\Users\users\Tealium\Tealium\cmp.py", line 58, in <module>

  File "C:\Users\users\Tealium\Tealium\cmp.py", line 47, in main
    print(result_of_agg.compute().to_csv('result_of_agg.csv'))
  File "C:\Users\users\Anaconda3\lib\site-packages\pandas\util\_decorators.py", line 211, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\users\Anaconda3\lib\site-packages\pandas\core\generic.py", line 3720, in to_csv
    return DataFrameRenderer(formatter).to_csv(
  File "C:\Users\users\Anaconda3\lib\site-packages\pandas\util\_decorators.py", line 211, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\users\Anaconda3\lib\site-packages\pandas\io\formats\format.py", line 1189, in to_csv
    csv_formatter.save()
  File "C:\Users\users\Anaconda3\lib\site-packages\pandas\io\formats\csvs.py", line 241, in save
    with get_handle(
  File "C:\Users\users\Anaconda3\lib\site-packages\pandas\io\common.py", line 856, in get_handle
    handle = open(
PermissionError: [Errno 13] Permission denied: 'result_of_agg.csv'
``` 

I currently work with a company laptop and do not have elevated access on all things. Would there be a way to perform the above?

**Comment by j-bennet** [comment]
@lime-n,

There are two separate problems.

First, this is your original issue of writing a single-partition `.csv` file that is taking too long, and seemingly hangs, but actually finishes after a while. Since you're reading your original dataframe from a single `csv` file, it probably has a single partition - check if that's the case with `print(longer_pivot.npartitions)`. You can repartition the dataframe after reading, example:

```python
longer_pivot = dd.read_csv("cmp_product_long.csv").repartition(10)
```

After you did the transformations on the datframe, don't call `compute()` before writing the csv, and you'll be writing to multiple csv files, one per partition:

```python
result_of_agg_var.compute().to_csv('result_of_agg_var.csv')
```

Writing the file in chunks should be quicker, and hopefully would solve the first problem.

The other issue is your permission error. You need to be writing in a location where you have permissions to create files and directories. If you as a user can't `touch some_file.txt` or `mkdir some_dir` in this location, then your script won't be able to either. Make sure you're providing a path to a writeable directory, it may have to be an absolute path, so it's not dependent on how you're running the script:

```python
df.to_csv('C:/Users/<some-user>/result_of_agg_var.csv')
```
