### ISSUE TITLE
read_parquet raises an error with config {scheduler : processes}

### ISSUE THREAD

**Issue by Crispy13** [dask/dask#9931]
```
from dask import dataframe as dd
import dask

dask.config.set(
    {
        "scheduler":'processes', 
        "num_workers" : 8,
    }
)

collected_parquet1 = dd.read_parquet("/.tmp/*.parquet").compute()
collected_parquet1.head()
```

The above code raised: `FileNotFoundError: [Errno 2] No such file or directory: '.tmp/d9bd5494-1b21-4bea-b65d-4d72d1e3c145'`
and running infinitely.

When I interrupted the code after the above error, I got: `BrokenProcessPool`

I was using Jupyter Notebook and VS code.

When I set `schduler` to `threads`, It worked.

**Environment**:

- Dask version: 2023.1.1
- Python version: 3.11.0
- Operating System: CentOS Linux release 8.4.2105
- Install method (conda, pip, source): conda

**Comment by wence-** [comment]
This is likely https://github.com/jupyter-server/jupyter_server/issues/1198 can you try downgrading ipykernel to `ipykernel=6.20.1`?

**Comment by j-bennet** [comment]
It can be https://github.com/jupyter-server/jupyter_server/issues/1198, but the `FileNotFoundError: [Errno 2] No such file or directory: '.tmp/d9bd5494-1b21-4bea-b65d-4d72d1e3c145'` is surprising.

@Crispy13 Can the error be reproduced reliably, or is it intermittent? Are you able to post the full traceback?

**Comment by Crispy13** [comment]
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/anaconda3/envs/TOSC_ML_py-3.11/lib/python3.11/multiprocessing/spawn.py", line 120, in spawn_main
    exitcode = _main(fd, parent_sentinel)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/anaconda3/envs/TOSC_ML_py-3.11/lib/python3.11/multiprocessing/spawn.py", line 129, in _main
    prepare(preparation_data)
  File "/anaconda3/envs/TOSC_ML_py-3.11/lib/python3.11/multiprocessing/spawn.py", line 240, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "/anaconda3/envs/TOSC_ML_py-3.11/lib/python3.11/multiprocessing/spawn.py", line 291, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen runpy>", line 290, in run_path
  File "<frozen runpy>", line 254, in _get_code_from_file
FileNotFoundError: [Errno 2] No such file or directory: '.tmp/09ddcc61-889d-4ba4-bc8c-6241830d80aa'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/anaconda3/envs/TOSC_ML_py-3.11/lib/python3.11/multiprocessing/spawn.py", line 120, in spawn_main
    exitcode = _main(fd, parent_sentinel)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/anaconda3/envs/TOSC_ML_py-3.11/lib/python3.11/multiprocessing/spawn.py", line 129, in _main
    prepare(preparation_data)
  File "/anaconda3/envs/TOSC_ML_py-3.11/lib/python3.11/multiprocessing/spawn.py", line 240, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "/anaconda3/envs/TOSC_ML_py-3.11/lib/python3.11/multiprocessing/spawn.py", line 291, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen runpy>", line 290, in run_path
  File "<frozen runpy>", line 254, in _get_code_from_file
FileNotFoundError: [Errno 2] No such file or directory: '.tmp/09ddcc61-889d-4ba4-bc8c-6241830d80aa'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/anaconda3/envs/TOSC_ML_py-3.11/lib/python3.11/multiprocessing/spawn.py", line 120, in spawn_main
    exitcode = _main(fd, parent_sentinel)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/anaconda3/envs/TOSC_ML_py-3.11/lib/python3.11/multiprocessing/spawn.py", line 129, in _main
    prepare(preparation_data)
  File "/anaconda3/envs/TOSC_ML_py-3.11/lib/python3.11/multiprocessing/spawn.py", line 240, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "/anaconda3/envs/TOSC_ML_py-3.11/lib/python3.11/multiprocessing/spawn.py", line 291, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen runpy>", line 290, in run_path
  File "<frozen runpy>", line 254, in _get_code_from_file
FileNotFoundError: [Errno 2] No such file or directory: '.tmp/09ddcc61-889d-4ba4-bc8c-6241830d80aa'
```

When interrupted
```
---------------------------------------------------------------------------
BrokenProcessPool                         Traceback (most recent call last)
File /anaconda3/envs/TOSC_ML_py-3.11/lib/python3.11/site-packages/dask/multiprocessing.py:233, in get(dsk, keys, num_workers, func_loads, func_dumps, optimize_graph, pool, initializer, chunksize, **kwargs)
    231 try:
    232     # Run
--> 233     result = get_async(
    234         pool.submit,
    235         pool._max_workers,
    236         dsk3,
    237         keys,
    238         get_id=_process_get_id,
    239         dumps=dumps,
    240         loads=loads,
    241         pack_exception=pack_exception,
    242         raise_exception=reraise,
    243         chunksize=chunksize,
    244         **kwargs,
    245     )
    246 finally:

File /anaconda3/envs/TOSC_ML_py-3.11/lib/python3.11/site-packages/dask/local.py:500, in get_async(submit, num_workers, dsk, result, cache, get_id, rerun_exceptions_locally, pack_exception, raise_exception, callbacks, dumps, loads, chunksize, **kwargs)
    499 fire_tasks(chunksize)
--> 500 for key, res_info, failed in queue_get(queue).result():
    501     if failed:
...
-> 1132     if lock.acquire(block, timeout):
   1133         lock.release()
   1134         self._stop()

KeyboardInterrupt: 
```

@j-bennet This error can be produced reliably.

**Comment by rjzamora** [comment]
@Crispy13 - Can you share what version of `ipykernel` you are on (e.g. `pip list | grep ipykernel`)?  I was having similar problems with `6.21.1`, so it would be nice to rule that out.

**Comment by Crispy13** [comment]
@rjzamora 
```
ipykernel                     6.21.1
```
It is `6.21.1`.

**Comment by rjzamora** [comment]
>It is 6.21.1.

Thanks for confirming @Crispy13 - In that case, https://github.com/jupyter-server/jupyter_server/issues/1198 does seem likely to be the culprit.  Therefore, I don't think anyone should start investigating this issue until you confirm that the problem remains after you downgrade to `6.20.1`.
